### ISSUE TITLE
Log file is saved in application directory

### ISSUE THREAD

**Issue by rmcardle** [mRemoteNG/mRemoteNG#1]
The log file mRemoteNG.log is saved in the application directory.  This may cause problems on Windows Vista and Windows 7 when User Account Control is enabled.

The log file location should be moved to %USERPROFILE%\AppData\Local\mRemoteNG\mRemoteNG.log or preferably, made configurable.

**Comment by robertpopa22** [comment]
test

**Comment by robertpopa22** [comment]
Apologies — test comment posted by mistake. Please ignore.
