### ISSUE TITLE
[Connections]: disabling filtering without clearing keyword leaves filtered state

### ISSUE THREAD

**Issue by PetbkA** [mRemoteNG/mRemoteNG#1002]
## Expected Behavior

If filtering is disabled while keyword hasn't been cleared, behavior should be like if this keyword was just searched, i.e.:
- All connections should be shown;
- Matched connection should be chosen in the list.

## [Current Behavior](https://user-images.githubusercontent.com/22843816/41740079-a689c1fa-759f-11e8-8d5c-4d5d6c16fd43.gif)

- Connections list stays in filtered state;
- Neither clearing search filed nor using _Expand/Collapse_ buttons can show all nodes. Moreover, _Collapse_ button hides node from list;
- _Create New Connection/Folder_ buttons are working, but you can't see new nodes until you restart the app.

## Steps to Reproduce (for bugs)

1. Enable filtering in options;
2. Filter connections by keyword so only part of them were matching;
3. Without clearing search field, disable filtering.

## Your Environment

* Version used: 1.76.4.16229;
* Operating System: Windows 7 x64 SP1;
* .NET Framework 4.7.1

**Comment by sparerd** [comment]
This is resolved. The fix will be available in the next v1.76 release
