### ISSUE TITLE
Unable to sort connections alphabetically

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1007]
When trying to automatically sort all connections by clicking the ![devenv_2018-06-23_15-00-02](https://user-images.githubusercontent.com/22905106/41809948-2295e588-76f6-11e8-9139-b8e43d39ed67.png) button, mRemoteNG just freezes.
From a quick view into the code it seems to me like the application enters a never ending loop.

## Environment
Version used: 1.76.4.16229
Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 Build 17134.82

**Comment by sparerd** [comment]
I'm not able to easily reproduce this bug. What is the smallest reproducible connection tree sample that produces the loop? Or, where in the code do you believe it is looping?

**Comment by farosch** [comment]
It seems like I have been too impatient.
There is no loop in the code, it just takes forever to complete. I have a connection file with ca. 390 connections. When sorting alphabetically it takes about 4 minutes to complete. 83 config backup files will be created in %APPDATA%\mRemoteNG during the sorting (~100MB).
This has not been an issue in earlier versions of mRemote, unfortunately I cannot tell with which update it became slow.
I have sent you an email with my configuration file for you to make some tests, if needed.

**Comment by sparerd** [comment]
I have a fix that I'm happy enough with for this release. Merged in commit 8029e49. This will be available in the next release.

2 main changes:
- Once a sort operation is started, saves are batched. A single save (if any) is run at the end of the sort.
- The save is now done on a background thread. This was previously using the UI thread for some reason.

This brings the sort operation down to ~5sec on my machine. The save still takes about 15sec, but you can use the app while that happens.
