### ISSUE TITLE
W10 power down reports mRemoteNG still active 

### ISSUE THREAD

**Issue by TwobrainsOne** [mRemoteNG/mRemoteNG#1009]
After closing mRemoteNG and shutdown W10-1803, it reports mRemoteNG process still active 

## Expected Behavior
Quit and powerdown W10 without notification

## Current Behavior
I noticed on 2 upgraded W10 1803 machiens that mRemoteNG has a running process afterpowering down W10.
It looks as if you quit mRemoteNG with open sessions, something in the background stays active.

I did not notice this on pre 1803 releses from W10.

## Possible Solution
not sure .....
## Steps to Reproduce (for bugs)

1. Open mRemoteNG
2. Open more session
3. Close mRemoteNG while sessions are open
4. powerdown the machine

## Your Environment
* Operating System is W10, upgraded to 1803 release unsing mremote Latest 1.75 verion

**Comment by kmscode** [comment]
Options -> Connections -> When closing connections:
![image](https://user-images.githubusercontent.com/16654335/42169850-ed14f464-7de2-11e8-8495-39b0e7e05bc2.png)


By default this is set to "warn me when closing". This will cause mRemoteNG to wait for user input (click OK to close all connections type prompt):
![image](https://user-images.githubusercontent.com/16654335/42169893-0506fc48-7de3-11e8-80e5-4b5f968a5a46.png)

If you don't address it, mRemoteNG will remain open and have to be killed by windows on shutdown.

**Comment by TwobrainsOne** [comment]
Hi,

This is not th eissue.


1.       I shutdown all connections in mRemoteNG (disconnect or logout)

2.       I shutdown mRemote NG

3.       I shut down all other applications

4.       I go to START – SHUTDOWN( the laptop)

5.       Windows shutdown is performing, but..

6.       … poping up with “mRemoteNG” is preventing windows to shutdown; select proceed or cancel”


I cannot reproduce this yet  on-the-spot, but it looks as if you use the SAVE AS option somewhere/in combination with new connections, etc….

Thanks

**Comment by kmscode** [comment]
Can you validate that the mremoteng.exe process has exited (via task manager) after closing the UI?

If it's hanging, try generating a memory dump with [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump):

    procdump -ma [mremoteng pid]

**Comment by TwobrainsOne** [comment]
yep, closed all applications and it keeps running. See dump file 

(can not upload due to the size (161MB as ZIP). Pls mention alternative to send!
