### ISSUE TITLE
Suggestion 1.76 Right Menu - Connection properties

### ISSUE THREAD

**Issue by TwobrainsOne** [mRemoteNG/mRemoteNG#1010]
Suggestion 1.76 Right Menu - Connection properties

I suggest to make a right-Mouse menu option PROPERTIES that pops-up the (Floating) Config option box for quick changing parameters on a entry 

This works faster than selecting the top VIEW - CONFIG box... particular when there is a log list of servers in the left- menu pane

**Comment by sparerd** [comment]
Can you explain what you mean by "the floating" config box?

If i normally have the config box docked to the left side of the screen, but it is currently hidden, would clicking the Properties menu item simply show the config panel (docked on the left) or would it show in some separate window or fly-out control?

**Comment by TwobrainsOne** [comment]
like this : undock, float, unpin. On the machine a right Mouse wiht PROPERTIES is much quicker, and "easier" to navigate.

![capture](https://user-images.githubusercontent.com/40592887/41930971-2c443ddc-796c-11e8-8af2-60ee3b72e14a.GIF)
...
