### ISSUE TITLE
 v1.75.7012 does not run anymore

### ISSUE THREAD

**Issue by KeithDib** [mRemoteNG/mRemoteNG#1014]
## Current Behavior

version  v1.75.7012 was working and now the process just stops without error, Windows 10 1709 Build 16299.371. 

I have now installed the v1.76 Alpha 6 version, this does indeed open but i cannot open my saved connection files. 

## Steps to Reproduce (for bugs)

1. uninstalled, cleaned registry and files, reinstalled. same issue
2. installed Alpha version with above results
3.
4.

## Your Environment

* Version used: Stable v1.75.7012 and Prerelease v1.76 Alpha 6
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 Build 16299.371.

**Comment by farosch** [comment]
@KeithDib Since this is a very old issue and you have failed to response to any questions asked I will close this issue now. Please feel free to re-open it in case you still have that problem!
