### ISSUE TITLE
Feature Request, Storing settings when portable.

### ISSUE THREAD

**Issue by jaydenthorup** [mRemoteNG/mRemoteNG#1018]
I found http://jakub.kotrla.net/putty/ This version of putty, which will save sessions as files. This makes the putty defaults portable between machines. Please consider using this version of Putty. I have tested it and it works 100%.

**Comment by sparerd** [comment]
We have had several requests for this sort of feature and have decided to focus on integrating KiTTY. The work for this has not yet started, but you can follow #851 for further updates
