### ISSUE TITLE
Uvnc support

### ISSUE THREAD

**Issue by crizz11** [mRemoteNG/mRemoteNG#1019]
Is it possible to use ultravnc to connect to clients as it has a nice chat feature you can use to interact with the end user.  I know you can integrate it but it is a poor work around as you have to manually enter the hostname and the password each time you connect and it also opens up a new window outside the mRemoteNG window.

thanks
Chris

**Comment by sparerd** [comment]
Currently Uvnc only works through external tool integration. There is an enhancement request to add first-class support for Uvnc (#573). You can follow that issue for further updates

Closing this as a duplicate
