### ISSUE TITLE
Backup File Keep Count Setting Problem.

### ISSUE THREAD

**Issue by buraktoprak** [mRemoteNG/mRemoteNG#1020]
The value "BackupFileKeepCount" comes as "10" by default. I noticed when I was using the program .The number of files with the .backup extension exceeds 10. I'm changing this value manually, but it doesn't work. When the value is set to "0", the problem disappears. But of course, he's undermining the backup process!
## Expected Behavior
 Automatically back up to a maximum of 10.

## Current Behavior
 It automatically backs up more than 10 backups. (Forever)
 

## Possible Solution
"BackupFileKeepCount" has no choice but to "0".

## Steps to Reproduce (for bugs)

1.I tried "BackupFileKeepCount" with a value of "3".
2.I tried "BackupFileKeepCount" with a value of "0".

## Context
 As a result, the program does not accept the value "BackupFileKeepCount" other than 0.

## Your Environment

* Version used:1.76.4.16261
* Operating System and version (e.g. Windows 10 1709 x64):Windows 10 Pro 64 TR

**Comment by sparerd** [comment]
I've submitted a fix for this. It should be available in the next v1.76 release.
