### ISSUE TITLE
False window width when docking winow to side of desktop

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1024]
## Expected Behavior
Docking mRemoteNG to either side of the desktop (dragging the title bar to the side) should set the width of the windows to 50%

## Current Behavior
Window does not get sized correctly

## Your Environment
* Version used: 1.76.4.16229
* Operating System and version: Windows 1803 (Build 17134.165)

**Comment by sparerd** [comment]
This was due to a FrmMain minimum size change introduced in 3b9de84

The minimum form size was set too high and should be adjusted down.

**Comment by sparerd** [comment]
400x400 seems to be a reasonable minimum size. The app isn't terribly usable at that size, but most of the UI remains visible and features such as the Windows split-docking work nicer.
