### ISSUE TITLE
Improve SSH File Transfer user manual page

### ISSUE THREAD

**Issue by bgailer** [mRemoteNG/mRemoteNG#1025]
I created a connection, entered ip, username, password then clicked v on the protocol entry 

## Expected Behavior
According to the User Guide SFTP should appear in the list

## Current Behavior
protocols listed are RDP, VNC,  SSH version 1, SSH version 2, Telnet, rLogin, RAW,  HTTP, HTTPS, ICA, Ext. App
 SFTP does not appear in the list

## Workarounds
Start a terminal session ,right click the tab, select Transfer File  (SSH)
Use FileZilla

## Proposed Fix
revise the User Guide

## Steps to Reproduce (for bugs)
1. Install mRemoteNG using the MSI 
2. start the program 
3. create a new connection
4. enter ip, username, password then click v on the protocol entry

## Context
How has this issue affected you? About 1 hour
What are you trying to accomplish? transfer files

## Your Environment
* Operating System Windows 10

**Comment by sparerd** [comment]
I can see how the guide may be confusing. We should place the section for 'using ssh file transfer' higher in the guide and ideally include screenshots.

https://github.com/mRemoteNG/mRemoteNG/wiki/SSH-File-Transfer

**Comment by farosch** [comment]
No longer valid since the documentation has been moved to Sphinx:
https://mremoteng.readthedocs.io/en/latest/
