### ISSUE TITLE
Can't Install on Windows 7 - KB2574819 - The DTLS protocol provides communications privacy

### ISSUE THREAD

**Issue by sicinthemind** [mRemoteNG/mRemoteNG#1029]
Not sure if it's even worth the time to figure it out but I figured I would point it out. The Installer package looks explicitly for KB2574819 but does not account for other updates that supersede that patch.

The Installation fails - Indicating that I need this package. KB2574819: https://support.microsoft.com/en-us/help/2574819/an-update-is-available-that-adds-support-for-dtls-in-windows-7-sp1-and
![msiexec_2018-07-20_15-15-53](https://user-images.githubusercontent.com/15975980/43020939-d8978898-8c2f-11e8-8ed8-fb78d801b80f.jpg)

One approach - I might look get the binary version and if it's major.minor > xyz by OS could be one method. Account for more recent patches than the oldest patch. Other patches that include similar solutions to leverage DTLS for RDP.
KB2574819
KB2857650
KB2830477
KB2913751
KB2923545
KB2984972
KB3125574

Simple reproduction: 
Create a VM w/ Windows 7 SP1 and install updates until most recent and try to install.

**Comment by kmscode** [comment]
workaround is to install from command line with IGNOREPREREQUISITES=1option

https://github.com/mRemoteNG/mRemoteNG/blob/develop/README.MD

**Comment by Tampa** [comment]
This is apparently an issue with latest pre-release as well and worse still the workaround link is dead now. The fix mentioned in the other issue is closed, but seems to not actually be part of the latest pre-release?

Would be better if the installer simply informed the user, hey rdp isn't going to work if you don't have this update, rather than quit, but rdp does work as other updates provide the update anyways so this doesn't actually apply.

**Comment by farosch** [comment]
Closing, as we only provide compatibility with supported versions of Windows.
Windows 7 reached its end of life 01/14/2020, so we will not support it any more, see [this](https://docs.microsoft.com/en-us/lifecycle/products/windows-7).
You will most likely still be able to run mRemoteNG on a Windows 7 machine, but might encounter problems like the one mentioned above or may be forced to use old versions of mRemoteNG, as newer ones break compatibility.
