### ISSUE TITLE
Main menu text un-translates when themes are active and Options window is opened

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1037]
When app is started with russian locale with themes active, opening Options switches menu toolbar (but none of it's sections contents) to English;

[GIF](https://user-images.githubusercontent.com/22843816/41654130-17539682-7491-11e8-8180-bac7ce93ca41.gif)

## Expected Behavior
Main menu text should remain translated in the currently set culture.

## Current Behavior
Main menu text switches back to English

## Steps to Reproduce (for bugs)

1. Ensure non-English language is set and themes are active (restart)
2. Notice that main menu text is in the correct (non-English) language
3. Open Tools -> Options
4. Notice that the main menu text is now in English (sub-menu items are still translated)

## Your Environment

* Version used: 1.76.4

**Comment by kmscode** [comment]
I can reproduce this, but I can't find any cause so far. Initial code review looks good and no reason why the menu would be changed. 

The Help menu briefly disappears also...

Really weird...

**Comment by kmscode** [comment]
related to #981 perhaps?

**Comment by sparerd** [comment]
Hmmm interesting. The plot thickens

**Comment by sparerd** [comment]
Moving this out of v1.76. This is going to take time to track down and v1.76 is essentially done

**Comment by sparerd** [comment]
I cant reproduce this issue on the current `develop` branch (v1.77.0). This might be resolved.
