### ISSUE TITLE
Unable to add connection with active filter

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1038]
## Current Behavior
When a filtering is set and a filter is applied you cannot add a new connection.

## Steps to Reproduce (for bugs)
1. Create new connection file
2. Add connection `Test`
3. Filter for `Test`
4. Click on parent node
5. Click add connection (mRemoteNG enters renaming-mode on selected node)
6. Remove filter
7. Find created connection

## Your Environment
* Version used: 1.76.4.16229
* Operating System and version: Windows 10 1803 build 17134.167

**Comment by sparerd** [comment]
Looks like we will need to make some special accommodations in the `ConnectionTreeSearchTextFilter` class to handle the special case of newly created nodes.

**Comment by sparerd** [comment]
Just committed a fix for this. New nodes will survive filtering (regardless of the filter) until they leave edit mode. Once their name is set, they will have filtering applied like any other node.
