### ISSUE TITLE
Canceling "select panel" form does not cancel

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1040]
## Possible Solution
Make the cancel button really cancel or change the layout to something like this:
![mremoteng_2018-07-25_01-30-36 - kopie](https://user-images.githubusercontent.com/22905106/43171775-f4d07888-8fab-11e8-8d95-c571ae55e3c7.png)

## Steps to Reproduce (for bugs)
1. start connection
2. when asked to select/create panel click cancel -> a panel gets created anyways

## Your Environment
Version used: 1.76.4.16229
Operating System and version: Windows 10 1803 build 17134.167

**Comment by kmscode** [comment]
Reference #802
