### ISSUE TITLE
Dragging (grabbing) the program window requires 2 clicks.

### ISSUE THREAD

**Issue by june07** [mRemoteNG/mRemoteNG#1044]
## Expected Behavior
With every other windows program, windows can be grabbed and dragged by one click then drag.  

## Current Behavior
However, with mRemoteNG the first click only seems to highlight the window but not give the ability to drag it.  To drag you have to click the window a second time!  It sounds like a small thing but it's really annoying.

## Steps to Reproduce (for bugs)
Click one on the mRemoteNG window coming from another context (ie from using a different windows program, and not while already using mRemoteNG)
Try to drag the window (you won't be able to).
If you click again, you can now drag the window.

## Context
If mRemoteNG worked as every other program, workflow would be improved as you wouldn't constantly make the failed attempt at dragging/moving the window.

## Your Environment
1.76.4.16229
Windows 10 Home, version 1803, build 17134.165

**Comment by kmscode** [comment]
Reproduced. Odd... 

Seems that once the application has focus, it can be dragged immediately. But if another application had focus, the 2nd times a charm...

**Comment by june07** [comment]
Yeah, would be lovely to have this fixed.  I'm not well versed in the
language or else I would dig in deeper.

**Comment by june07** [comment]
Any ideas on this one?

**Comment by june07** [comment]
This issue is back in 1.76.20.24615
