### ISSUE TITLE
[Feature Request] Periodic save function/setting for Connection File

### ISSUE THREAD

**Issue by BloodyIron** [mRemoteNG/mRemoteNG#1046]
I'm on v1.75.7012.16814

Any chance we could get a setting for auto save of the connection file stuff? This way we don't forget to save changes we've made by mistake.

**Comment by kmscode** [comment]
We already have this:
![image](https://user-images.githubusercontent.com/16654335/43289031-a484b05e-90f7-11e8-8be3-0d3d3b9a8e80.png)

Or are you looking for something else? If so, please clarify.

**Comment by BloodyIron** [comment]
Ooops! I somehow missed that when looking ;P Sorry about that!
