### ISSUE TITLE
[Feature Request] SSH - Right click on session tab to copy console to clipboard

### ISSUE THREAD

**Issue by BloodyIron** [mRemoteNG/mRemoteNG#1048]
I'm on v1.75.7012.16814

PuTTY has the ability to copy the entire SSH console to clipboard, and I was hoping that we could get the same thing in mRemoteNG. Is that possible? :)

I tried to look for this feature, couldn't find it :( So sorry if this is already in there somewhere.

**Comment by kmscode** [comment]
This is a PuTTY native feature via Ctrl + Right Click -> Copy All to Clipboard. 

PuTTYNG (which is what we use/provide) is a minimally modified version of PuTTY and it includes the same functionality.

**Comment by BloodyIron** [comment]
Well, any chance we could get a gui display to do this? While I may know now that you have told me, I don't see how others users would naturally discover this hidden feature.
