### ISSUE TITLE
Issue with Windows 10 Insider Preview

### ISSUE THREAD

**Issue by helmar74** [mRemoteNG/mRemoteNG#1058]
There's an issue in the current Windows 10 Insider Preview (Build 17728) with the remote desktop client (mstsc.exe). The RDP Client shows a dialog, that there are not enough system ressources to create a rdp session. After Ignoring this message, the session is established. 
Mremoteng doesn't ignore (or even shows) this message, so no connections from windows 10 insider can be connected. Maybe it is possible either to show or ignore those error messages.
Detail about can be found here:
https://blogs.windows.com/windowsexperience/2018/07/31/announcing-windows-10-insider-preview-build-17728/ 
(search for remote)

## Expected Behavior
Error Messages of mstsc.exe should be shown

## Current Behavior
Error message isn't shown and session can not be established.

## Steps to Reproduce (for bugs)

2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by tontonrally** [comment]
Same here with version 1.76.4.16229

**Comment by sparerd** [comment]
Closing since the underlying library issue was fixed
