### ISSUE TITLE
[Feature Request] Set force inheritance to all new sub-entities

### ISSUE THREAD

**Issue by BloodyIron** [mRemoteNG/mRemoteNG#1060]
This is regarding v1.75.7012.16814

Could we get a parameter we can set on a folder, whereby it forces (by default) inheritance on all/some parameters for all new connections/folders created under its scope?

This way I can set it on the parent folder, and not have to specify inheritance for each new connection/folder ever made. This would save a lot of time when dealing with adding a lot of new connections/folders.

Please?

**Comment by sparerd** [comment]
This is possible for new nodes by setting the default inheritance on the root node.

Click root connections node -> click the default inheritance button in the Config window (i think its the right-most button) -> set the inheritance values new nodes should have

The default connection info / default inheritance will be slightly redone in the future to allow separate default settings per protocol.

**Comment by BloodyIron** [comment]
Nice! Awesome! Any chance we could also get this to have default inheritance parameters set per-folder? So that way it's not just forced from root onto all?

For now, this gets me what I want though! :DDD

**Comment by sparerd** [comment]
Not sure about setting it on a per-folder basis. While it would be possible, we would need to be careful about how it was implemented.

It might be possible to make it an assignment-based property, similar to how the new credential management feature is going to work. You could manage a list of 'Defaults' that would represents named default connection/inheritance objects. Then assign these defaults to folders. New connections & folders would take defaults from their parent folder. Folders could also be set to inherit the default values from their parents.

**Comment by sparerd** [comment]
I'm going to close out this issue since it seems the current feature will work for you. You can follow #238  and #239 for further updates on the default connection/inheritance UI improvements
