### ISSUE TITLE
Entering correct password when starting app does not load connections file

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1062]
Cannot get past the enter password step when starting the app.

## Expected Behavior
Entering correct password does nothing

## Current Behavior
Enter correct password and clicking OK does nothing - the app continues to request a password.

## Steps to Reproduce (for bugs)

1. Ensure your connections file has a custom password set
2. Start mRemoteNG
3. Enter correct password
4. Click Ok
5. Notice that the app does not load the connections file

## Your Environment

* Version used: 1.76.5

**Comment by Laetterman** [comment]
Hi
I updated to the latest version but unfortunately 1.76.6.14594 on my environment the issue is not fixed.
Regards
Marc
