### ISSUE TITLE
UX: "Esc" button does nothing (does not close) some dialogs

### ISSUE THREAD

**Issue by bluikko** [mRemoteNG/mRemoteNG#1064]
If I have "Save Connection File As..." or "Delete Connection..." dialog open, pressing the "Esc" button does nothing.

It is the same in "Options" dialog, probably others as well.

## Expected Behavior
Pressing the "Esc" button should close the dialog, same as the "Cancel" action.

## Current Behavior
Nothing happens.

## Steps to Reproduce (for bugs)
1. Click "File" -> "Save Connection File As..."
2. Press the "Esc" button
3. Nothing happens

## Context
It would improve the user experience and make using mRemoteNG quicker because no need to fumble with mouse or other pointer device.

## Your Environment
* Version used: 1.76.6
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 x64

**Comment by sparerd** [comment]
The following dialogs now close (cancel) when hitting the `Esc` key:
- "Delete connection" confirmation dialog
- Options window
- Save As dialog (I actually didn't do anything for this one - it was already working for me)

This will be available in the first v1.77 alpha release. Feel free to reopen this issue if there are more dialog that you can identify that I should update.
