### ISSUE TITLE
Password protected connection file

### ISSUE THREAD

**Issue by havalo-lolawo** [mRemoteNG/mRemoteNG#1067]
Password protected file overwrites the connection file when entering password wrong 3 times

## Expected Behavior
When save connections on exit option is enabled, this will automatically overwrite the file when exiting mRemoteNG if the password is entered wrong

## Possible Solution
If password has been entered wrong 3 times, the application should exit without opening the configured connection file, this will save the file from being overwritten. 

## Context
I have lost all configured servers but luckily having a backup helps :)

## Your Environment
* Version used: 1.76.4.16229

**Comment by sparerd** [comment]
This was resolved in #961 and released in 1.76.5 (but you should use 1.76.6 due to a bug in 1.76.5)

**Comment by havalo-lolawo** [comment]
Thank you very much @sparerd - downloading now!
