### ISSUE TITLE
CefSharp Browser engine

### ISSUE THREAD

**Issue by spisarau** [mRemoteNG/mRemoteNG#1071]
Could you add Chromium Engine to mRemoteNG?

https://github.com/cefsharp/CefSharp

**Comment by leaskovski** [comment]
@sparerd I have just started knocking something up for this.  Whilst it looks pretty simple to add in, for some reason I am having difficulties with getting the actual control to render in the application.  Any pointers for my current implementation?

**Comment by amaitland** [comment]
> I have just started knocking something up for this

@leaskovski Push your changes to `GitHub` and post a link, I'll have a quick look and see if anything stands out.

**Comment by leaskovski** [comment]
@amaitland you can find my fork of the repo here, https://github.com/leaskovski/mRemoteNG

**Comment by amaitland** [comment]
Does google.com load? I don't see anything glaring from a CefSharp point of view. 

The finalizer you've added to Dispose of the browser is almost guaranteed to cause problems,  hopefully whoever reviews your PR provides a constructive review.

Finalizer should only free unmanaged resources,  see https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#the-disposeboolean-overload

**Comment by leaskovski** [comment]
@amaitland , ok thanks, I will review that dispose doc.  The google site does load as we get a title change event trigger fired and thus to page title then gets loaded into the connection tab caption, so that looks to be working ok.
I am going to create a sample app from scratch and see what is different between the two.  I have a feeling it might be related to how the web browser component gets attached to the tab.

**Comment by amaitland** [comment]
You can use https://github.com/cefsharp/CefSharp.MinimalExample for testing purposes.

**Comment by leaskovski** [comment]
@amaitland just realised that you also work on CEFSharp!  Doh.  Anyway, I got around my issue.  Had to change how the browser control was being added to the control collection and this solved the loading problem.  So now have a kind of working version of the implementation.  Might submit a pull request.

**Comment by spisarau** [comment]
Recently Microsoft released a new version of Microsoft Edge browser. So it can be used as external tool and integrated into mRemoteNG window without any problem. 
The following startup arguments allow to start ech host in a separate tab
`%Hostname% --start-fullscreen --user-data-dir=C:/TEMP/%Hostname%`

**Comment by leaskovski** [comment]
I dont know why I didnt even think of doing that!!!  lol....
`chrome.exe --app=%HostName%`
