### ISSUE TITLE
Secruity Review/Info ?

### ISSUE THREAD

**Issue by Clickbaitcake** [mRemoteNG/mRemoteNG#1078]
Hello,

My organization are looking to "approve" an RDP manager for our staff.
Can anyone point me to documentation or guidelines on how mRemoteNG stores username, password and domain? I understand it saves them into a .XML file with AES? Are more specific details available on this? 
Thanks!

**Comment by sparerd** [comment]
The encryption process:
1. User provides the *encryption key* (the password used to open mRemoteNG) and the *plain text* that they wish to encrypt.
2. The user-provided encryption key and a randomly generated salt is run through the Pkcs5S2 key generation function a set number of times (determined by the `Key Derivation Function Iterations` option). The minimum number of iterations is 1000. The recommended iteration number is 5000 or greater. This step provides us a *derived key*.
3. The *derived key* and *plain text* are encrypted with the selected encryption engine/cipher mode.
   - We currently support 3 encryption engines: AES, Serpent, Twofish
   - We currently support 3 block cipher modes: GCM, CCM, EAX
4. The salt and encrypted data are combined and converted to Base64. This Base64 data is what is written to disk.

A few further notes:
- By default, only the `password` property of connection records are encrypted. This can be changed by enabling the `Completely encrypt connection file` option, which will encrypt the password field as normal, but then also encrypts the entire xml document (except the root xml node, which is required for decryption).
- By default, a connection file will use a pre-configured encryption key. This is a legacy feature and is not secure at all. It is recommended that you set a custom password on all connection files. The pre-configured key feature is currently being phased out - you can follow the progress on this issue: #376.
- Related to this, we are implementing a credential manager which will further separate connection details for sensitive credentials. The main goal of this is to let users import credentials from programs who are designed for credential management (KeePass, LastPass, PasswordSafe, etc). This feature has been delayed, but is still planned for release. You can follow #208 for updates.

**Comment by Clickbaitcake** [comment]
Thank you for the excellent and clear information friend!
Just to be absolutely clear; if the user does not set a password to open the application, a default key is used to encrypt the login credentials. The credentials are encrypted and based64 encoded and then written to disk. Is this correct?

Also, what’s to stop me copying someone’s .XML file and logging in as them?

It would be great to see a registry key or some other centrally controllable setting so that administrators can control the encryption behaviour.

Integration with password managers sounds like a excellent step!

Again, thanks for the information.


________________________________

**Comment by sparerd** [comment]
> Just to be absolutely clear; if the user does not set a password to open the application, a default key is used to encrypt the login credentials.

That is correct. The default key is publicly available in the source code. Encrypting using the default key is only marginally more secure than not encrypting at all.

> The credentials are encrypted and based64 encoded and then written to disk. Is this correct?

That is essentially correct.

> Also, what’s to stop me copying someone’s .XML file and logging in as them?

Unless I'm misunderstanding the question, nothing. If someone has your .xml file and has your password, they have access to the contents of the file.

> It would be great to see a registry key or some other centrally controllable setting so that administrators can control the encryption behaviour.

There have been a few others that have mentioned similar sentiments (wanting more support for manageing mRemoteNG deployments). I'm not opposed to it, though I honestly haven't thought much about it either.
