### ISSUE TITLE
mREmoteNG

### ISSUE THREAD

**Issue by roseannajmcdonald** [mRemoteNG/mRemoteNG#1079]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by benwa** [comment]
Seems you forgot some info there.  Can you edit your post to fill out the issue?

**Comment by sparerd** [comment]
Closing due to lack of... anything
