### ISSUE TITLE
Connect with /admin

### ISSUE THREAD

**Issue by pwrpwr** [mRemoteNG/mRemoteNG#1081]
I need to be able to connect to a set of RDS servers using the /admin argument. If I don't use this, the RD broker will not connect me to the right server.

**Comment by sparerd** [comment]
Try setting the `Use Console Session` property on the mRemoteNG connection record to `Yes`

I believe the mstsc `/console` switch was renamed to `/admin` at some point, though we have not changed our property name to match it.

**Comment by pwrpwr** [comment]
Brilliant, that's it, thanks!

**Comment by lispeedyg** [comment]
Hi, I'm trying to use this functionality on the current version (1.76.20 (2019-04-12)).  However, I cannot seem to find the function in the Protocol section.  Can someone please give me some guidance?
Thanks

**Comment by pwrpwr** [comment]
It's just as  sparerd describes above, in the config section set 'Use Console Session' to Yes
![image](https://user-images.githubusercontent.com/42669509/76682764-a56d8600-65f6-11ea-8416-fb28f56cf468.png)

**Comment by lispeedyg** [comment]
Thanks for this.  My settings did not show these options:
![image](https://user-images.githubusercontent.com/8366831/76684004-be6a3d00-65de-11ea-92d9-7c24b1c9e3f1.png)
These settings were imported.  However, when I created a "new" session they appeared.  In the imported session the "default Properties button was grayed out.

I guess threre's no way to re-set the connection properties with imported items.

Thanks for the pointer.

**Comment by pwrpwr** [comment]
ah that's a bit crap, not sure why that would be the case. No worries anyway, good luck,

**Comment by theworm4002** [comment]
Close mRemoteNG
Go to the mRemoteNG directory file  IE: D:\mRemoteNG-Portable
Open confCons.xml in a text editor like notepad++ or windows notepad whatever.
Find the line with the PC you want to change the settings to and go over until you see ' Port="3389" ConnectToConsole="false" '
change the false to say true and save that bugger.
Re-open mRemoteNG and connect to the PC.
Mission accomplished.
