### ISSUE TITLE
Feature request, connection groups

### ISSUE THREAD

**Issue by aplocher** [mRemoteNG/mRemoteNG#1094]
**Feature request**: Have a way to create groups of connections in the Connections list.  

These would be "shortcuts" to the actual Connection element and not necessarily an actual connection.  The Connection Groups  allow for grouping one or more connection together and certain properties of that actual connection to be overridden (for example, the Panel property or Resolution property)

This wouldn't replace Connection or Folder nodes in the treeview, but be an additional type that acts as a connection-shortcut/folder-group hybrid sorta thing.

Double clicking a Group with 2 items would trigger both items to connect.  It could be configured in such a way that they would connect side-by-side (split screen) or with two separate tabs.

Possible considerations:

 - Would it make sense to have nested groups?  (e.g. I want two tabs, each with two split-screen connections)
 - How about enabling the ability to drag a connection group to your desktop to have a quick launch icon (heck, what about that for any connection, not limited to this "groups" idea? Perhaps another issue should be submitted for this)

Thank you for your consideration - keep up the great work! 👍 

-Adam

**Comment by MarioWitdoek** [comment]
Yeah, this a great feature request. Like in Terminals there is an option 'Groups' that appear in the treeview where you can sort the connections. I use it a lot where a server (1 configuration) can be in multiple "function groups" (SSH, Ubuntu, Domotics).

and also KUTGW!

**Comment by kmscode** [comment]
This is working now in the "removemagiclib" branch that will be included in 1.77:

![image](https://user-images.githubusercontent.com/16654335/52416152-f0919d00-2ab6-11e9-951f-a7fb38a2c4f7.png)
