### ISSUE TITLE
Password input box buttons not fully visible

### ISSUE THREAD

**Issue by Hovn** [mRemoteNG/mRemoteNG#1098]
从1.72开始测试至1.76，密码输入框的按钮都被遮挡。希望改进。
![111](https://user-images.githubusercontent.com/6801952/44971849-ad705280-af89-11e8-9ed1-896e075d7a89.png)
![222](https://user-images.githubusercontent.com/6801952/44971850-ad705280-af89-11e8-82a9-e07922d24042.png)

**Comment by farosch** [comment]
@Hovn Please update to the latest version of mRemoteNG. This seems to be already fixed for both traditional and simplified chinese.
@Hovn请更新到mRemoteNG的最新版本。对于传统和简体中文来说，这似乎已经得到了解决。

Simplified chinese:
![mRemoteNG_2019-03-10_12-04-50](https://user-images.githubusercontent.com/22905106/54084145-6050ad00-432d-11e9-849d-f78d90cb012b.png)
![mRemoteNG_2019-03-10_12-02-12](https://user-images.githubusercontent.com/22905106/54084146-6050ad00-432d-11e9-98bc-507adcd8c631.png)
Traditional chinese:
![mRemoteNG_2019-03-10_12-04-13](https://user-images.githubusercontent.com/22905106/54084148-6050ad00-432d-11e9-9b14-09a233712c9b.png)
![mRemoteNG_2019-03-10_12-03-30](https://user-images.githubusercontent.com/22905106/54084147-6050ad00-432d-11e9-90dd-bce7ec90faf1.png)

**Comment by Hovn** [comment]
你好：
从github获取最新便携版本进行测试，密码框按钮被遮挡问题仍然存在。


环境：
在win7 x64及win10 x64上测试均存在遮挡问题
OS语言均为简体中文
显示缩放级别100%


版本：


遮挡问题仍然存在：
设定密码时：


进入软件时：









在2019-03-10 19:12:11，"Faryan Rezagholi" <notifications@github.com> 写道：


@Hovn Please update to the latest version of mRemoteNG. This seems to be already fixed for both traditional and simplified chinese.
@Hovn请更新到mRemoteNG的最新版本。对于传统和简体中文来说，这似乎已经得到了解决。

Simplified chinese: Traditional chinese:

**Comment by farosch** [comment]
@Hovn 我可以用当前版本（v1.76.16）调整问题。在当前的开发分支中，问题已经解决，并将与v1.77一起发布。
@Hovn I was able to recreate the problem with the current version (v1.76.16). In the develop branch the problem is solved already and will be published with v1.77.
