### ISSUE TITLE
[Feature] Button next to search to clear searchbox

### ISSUE THREAD

**Issue by SaschaJohn** [mRemoteNG/mRemoteNG#1102]
As a mouse user, it would be helpful to have a clear button for the search/filter box next to it.

**Comment by farosch** [comment]
@sparerd would this be an appropriate icon to do so?
![textfield_delete](https://user-images.githubusercontent.com/22905106/50487701-a15c4500-09ff-11e9-8b56-f4d3ef8f5206.png)
It's the `textfield_delete.png` from famfamfam

**Comment by sparerd** [comment]
Either that or one of these. Depends on which makes more sense in context.

![image](https://user-images.githubusercontent.com/6999446/50487903-a56b7100-09c5-11e9-9749-b964ef3dad85.png)
![image](https://user-images.githubusercontent.com/6999446/50487896-9b497280-09c5-11e9-8924-456bc26954df.png)
![image](https://user-images.githubusercontent.com/6999446/50487970-e2376800-09c5-11e9-9330-9d57523cff59.png)
![image](https://user-images.githubusercontent.com/6999446/50487987-009d6380-09c6-11e9-9f49-39b0a9d4b319.png)
![image](https://user-images.githubusercontent.com/6999446/50487999-0eeb7f80-09c6-11e9-9ce7-fc72473c873c.png)

**Comment by farosch** [comment]
I think ![cross](https://user-images.githubusercontent.com/22905106/50488224-b5a14180-0a01-11e9-8c81-ff246ee0b469.png) or ![keyboard_delete](https://user-images.githubusercontent.com/22905106/50488230-be921300-0a01-11e9-82cb-b7684f1239e5.png) would be best for this context.
I'd like to go for the keyboard one as it is a little less striking.
Is this alright? If so I'll push another commit to my redesign branch to include this.

**Comment by sparerd** [comment]
Yea that sounds good, although I'm worried the redesign branch is getting a bit large (and is about ready for merging I think). Could we do a separate PR for this? It would make it easier to code review

**Comment by farosch** [comment]
True. I'll create a new PR for this
