### ISSUE TITLE
External tools password error when use complicate password

### ISSUE THREAD

**Issue by icysplendor** [mRemoteNG/mRemoteNG#1104]
## Expected Behavior

logon system successfully when use external tools 
## Current Behavior

For example: authenticating with pre-entered password and access denied when use WinSCP as external tools
## Possible Solution

Change a password
## Steps to Reproduce (for bugs)

1. setup a external tools like WinSCP or filezilla the argument is like protocol://%Username%:%Password%@%Hostname%:%Port%
2. Connect server use external tool (the password is complicate like jhlw(okBmewzvWA)
3. 
4.

## Context

common operation will be brooked when the bug happed
## Your Environment

* Version used: 1.75.7012.16814
* Operating System and version (e.g. Windows 10 1709 x64): WIN10 * 64

**Comment by sparerd** [comment]
@icysplendor This is likely due to shell meta-character escaping. Try using `%!Password%` (notice the `!`) to disable this feature.

https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#shell-metacharacter-escaping

**Comment by Deaton64** [comment]
The `%!Password%` works for me, when previously it didn't. Thanks for that 🥇
