### ISSUE TITLE
[Connections][Rename]: Delete button causes connection deleting

### ISSUE THREAD

**Issue by PetbkA** [mRemoteNG/mRemoteNG#1110]
## Expected Behavior

When renaming a connection, pressing *Delete* button should work like in any text editor - delete one symbol or the highlighted symbols

## Current Behavior

Pressing *Delete* triggers deleting of connection

## Steps to Reproduce (for bugs)

1. Press *F2* or *Right Mouse Button -> Rename* on the connection in question;
2. Press *Delete*

## Your Environment

* Version used: 1.76.8.17214
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1607 x64

**Comment by sparerd** [comment]
Resolved this bug - it will be available in the next release
