### ISSUE TITLE
It's time to search bar???

### ISSUE THREAD

**Issue by febelus** [mRemoteNG/mRemoteNG#1119]
## Expected Behavior
Hi, it's time to add a search bar for search "inside" connection and folder name (i have 150 connection and is very difficult to looking for one) with auto complete must be the best!!!!

## Current Behavior
no way to search for connection or folder name

## Possible Solution
Integrate a simple searchbar
## Steps to Reproduce (for bugs)

no
## Context

no

## Your Environment
All
* Version used:
* Operating System and versionALL

**Comment by sparerd** [comment]
Does this search bar not do want you want?
![image](https://user-images.githubusercontent.com/6999446/46410312-0bee3500-c6de-11e8-8838-f7741157bfde.png)

**Comment by febelus** [comment]
i'm so stupid…. i doesn't see that!! lol!! its grate
