### ISSUE TITLE
RestrictedAdmin Mode Support

### ISSUE THREAD

**Issue by kim182** [mRemoteNG/mRemoteNG#1125]
In a Windows Server 2012 R2 environment with RestrictedAdminMode set, it is mandatory to connect using mstsc /restrictedadmin, and MremoteNG has no switch for this. 

Regards.

**Comment by kmscode** [comment]
Do you mean "[/RestrictedAdmin](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)"?

I don't see this command switch being exposed within the RDP methods based on my initial search:
https://docs.microsoft.com/en-us/windows/desktop/termserv/msrdpclient10notsafeforscripting

Assuming that it's not exposed we would not be able to implement it.

**Comment by kim182** [comment]
Thanks for the response, as i can see the setting we are looking for is "RestrictedLogon":
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/93cb63d8-b4ff-40dd-8d11-66867db6258f/rdp-activex-and-restrictedadminmode?forum=winforms

**Comment by sparerd** [comment]
Looks like we can set this property like this:

```csharp
((IMsRdpExtendedSettings)_rdpClient).set_Property("RestrictedLogon", true);
```

**Comment by Alex-ABIT** [comment]
Hello together,
is it possible to implement "/remoteGuard" in the same step?
Both of these parameters are important features to make RDP connections more secure.
This would be great, thanks in advanced.

![mstsc](https://user-images.githubusercontent.com/44974369/48355316-fd5b4c00-e693-11e8-82e9-0ae6ab4e1c71.png)

**Comment by c3rberus** [comment]
I am also looking for this switch, note that /restrictedAdmin and /remoteGuard are two different switches. This is described in [https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard](url) at the bottom of the page.

**Comment by Glober777** [comment]
Any news on this one?

**Comment by jeekkd** [comment]
Hello, myself and our other admins are/were users of mRemoteNG. After seeing that mRemoteNG does not support Restricted Admin or Credential Guard, and as I am moving my environment towards more security, we sadly had to give up the software. We moved to Royal TS instead so we could have support for these features.

**Comment by simonai1254** [comment]
Consider parameter /remoteguard as well when implementing this -> #2147

**Comment by tecxx** [comment]
doing some investigation how to possibly implement this.

the RDP ActiveX docs do not mention remoteguard or restrictedadmin
https://docs.microsoft.com/en-us/windows/win32/termserv/msrdpclient10notsafeforscripting

found the protocol specification for remoteguard (MS-RDPEAR)
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpear/a32e17ec-5869-4fad-bdae-d35f342fcb6f

here is a hint that at least "restrictedadmin" could be set via an undocumented extended property
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/93cb63d8-b4ff-40dd-8d11-66867db6258f/rdp-activex-and-restrictedadminmode?forum=winforms
    "The setting I was looking for is "RestrictedLogon" I had to use a decompiler on the mstscax.dll and searched the code for hints. After a lot of trial and error, I finally was able to identify the correct setting.


not sure i'm skilled enough to make this work... help appreciated.

EDIT: ok looks like this was easy,
`SetExtendedProperty("RestrictedLogon", true);`
EDIT2: and it seems spared mentioned this 4 years ago in this thread already. funny...

not sure aboute remote credential guard though, will keep looking.

**Comment by tecxx** [comment]
using a hexeditor i found a possible parameter "RedirectedAuthentication" for Remote Credential Guard 

![image](https://user-images.githubusercontent.com/4305825/163578902-f3a8221f-815c-4d4e-9749-7b8c145c7988.png)


it seems to be the right one, but something is missing still:
![image](https://user-images.githubusercontent.com/4305825/163578892-beedbb42-0967-4840-8056-491a2701eb4b.png)


an indicator that my finding is correct: https://gist.github.com/awakecoding/838c7fe2ed3a6208e3ca5d8af25363f6


this here might be helpful as well
https://twitter.com/awakecoding/status/1394660009255051267

![image](https://user-images.githubusercontent.com/4305825/163580335-212ac765-751f-4ea6-94d6-1c3ee33e0462.png)

**Comment by tecxx** [comment]
whoohoooo, i made it work

create a connection that has no credentials and no credvault api connector active
![image](https://user-images.githubusercontent.com/4305825/163581001-6b02505b-342e-4976-bf9d-dfa84577277b.png)

set up both attributes in the initialize phase

![image](https://user-images.githubusercontent.com/4305825/163581044-4f6e9e33-a61b-45f5-84de-58fe79e80f01.png)

and connection works without credentials as expected

![image](https://user-images.githubusercontent.com/4305825/163581071-9c0955b6-31aa-44f8-b195-6b515d58a317.png)

great stuff! i'll try to add the UI options and push a PR

**Comment by Kvarkas** [comment]
https://github.com/mRemoteNG/mRemoteNG/pull/2203
