### ISSUE TITLE
Windows compatibily ?

### ISSUE THREAD

**Issue by Stef-33560** [mRemoteNG/mRemoteNG#1126]
Hi all :)

Would it be possible to avoir dependencies with .Net 3.5 or low ?
Win 10 don't have .Net 3.5 pre-installed so mRemoteNG won't work easilly :(

Thanks for any feedbacks :)

**Comment by sparerd** [comment]
What version of mRemoteNG are you using?

**Comment by kmscode** [comment]
Current builds target .Net 4.6:  https://github.com/mRemoteNG/mRemoteNG/wiki/Prerequisites

You should be good to go with Windows 10 out of the box:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

Version 1.74 targeted .net 4. Version 1.75+ targets .net 4.6

**Comment by Stef-33560** [comment]
Seems I missed some info...

Nevertheless, can I avoid totally .net framework ans replace it with only some KB ?

**Comment by kmscode** [comment]
.net 4.6 is included Windows 10. You shouldn't have to do anything other than install the latest stable release of mRemoteNG.

Older versions of Windows will require the .net framework to be updated and if on Windows 7 some KBs need to be applied as well (assuming that these aren't already on the system).

**Comment by Stef-33560** [comment]
OK, I check if the W10 master planned to be deployed in my enterprise will contain .net 4.6 ...

**Comment by farosch** [comment]
@Stef-33560 Take a look at THIS
