### ISSUE TITLE
Windows Installer can't find us1me0hk.msi

### ISSUE THREAD

**Issue by mdio33** [mRemoteNG/mRemoteNG#1130]
When trying to upgrade from 1.75.7012.16814 to 1.76.10.42392 Windows Installer can't find us1me0hk.msi.

## Current Behavior
If I run the setup of 1.76.10.42392 it will try to uninstall the previous version, but it fails asking for the file us1me0hk.msi in the folder C:\Users\User\AppData\Local\Temp\

## Possible Solution
Uninstall the old version

## Steps to Reproduce (for bugs)
Just trying to update version.

## Your Environment
Windows 10 Pro Insider Preview 18252.180928-1410
![mremoteng](https://user-images.githubusercontent.com/44021265/46726242-df09c700-cc75-11e8-9bea-00c05cfbe164.jpg)

**Comment by mdio33** [comment]
Anyone?? :(

**Comment by sparerd** [comment]
Your best bet is to uninstall v1.75 (from control panel / programs and features) then try to install v1.76. 

I'm not sure why the upgrade install isn't using the cached msi in `%windir%\installer\` though. I figured that is what WiX does by default, but maybe I need to look into that.

**Comment by mdio33** [comment]
Is there any chance to force installation withtou uninstalling the old version?
Tried to force uninstall with an unistalling application and now I don't have the old version and still can't install the new version. :/

**Comment by sparerd** [comment]
You can try to reinstall/repair the old installation (it will need to be the exact same version that is/was installed). That should re-cache the msi and allow you to uninstall or upgrade to the newer version.

**Comment by mdio33** [comment]
I did try that too... same error.

I don't understand... even after force uninstalling and with cleaning all registry keys, no traces of mRemoteNG, still says that I need to uninstall it.

Is there any chance to force installation withtout uninstalling the old version?

**Comment by sparerd** [comment]
You can try to manually uninstall using the steps below:

1. Remove all mRemoteNG files from the install location. (Default is "C:\Program Files (x86)\mRemoteNG")
1. Delete the following key in the registry: `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{81E5E36D-C131-4AB8-BABD-BA124F28AF1B}`

**Comment by mdio33** [comment]
Thank you for the help.
That key is not present.
![reg](https://user-images.githubusercontent.com/44021265/47018093-e33d5500-d14b-11e8-88f5-2e5821b86416.jpg)
But even with nothing to uninstall in Programs and no key in registry the instalation gives the same error. 
The strange thing is that the error appears only in the end of instalation, if i click "Cancel" it roll back the instalation, if I end all instalation tasks from task manager without clicking "Cancel", mRemoteNG stays installed and usefull... but if I try to install it again, error appears.

**Comment by farosch** [comment]
Same as #1324. More info [here](https://support.venafi.com/hc/en-us/articles/215911917-Error-Uninstall-an-MSI-and-msiexec-fails-asking-for-path-of-old-MSI).
@mdio33  Feel free to reopen this if you need further support!
Closing as this is not directly related to mRemoteNG.
