### ISSUE TITLE
RDP Connections open at other User's Gui too (SQL)

### ISSUE THREAD

**Issue by peterriederer** [mRemoteNG/mRemoteNG#1134]
We're using latest mRemoteNG stable 1.76.10 with SQL database backend for sharing the connections.
There are round about 50 RDP entries and several SSH/Putty Connections.

With the new release we have the following Problem:
User 1 opens a RDP Connection to Server 1
in some circumstances the connection tree flickers at User 2 and the same Connection from User 1 with Server 1 opens at User 2 too.

Any Issues known so far?

**Comment by olfolfolf** [comment]
Could be the same issue:

#1128

**Comment by peterriederer** [comment]
Yes this also happens.

**Comment by sparerd** [comment]
To resolve this, I think I will disable saving the connection status to the database. It doesn't make sense that the connection status would be saved to a shared location anyways. That property (along with several others) should be saved on a user's local machine to prevent the issues seen here.

**Comment by sparerd** [comment]
Since this is a pretty annoying bug, I'm going to fix it as a hotfix to v1.76

**Comment by sparerd** [comment]
The fix for this will be available in v1.76.12. We can now save certain properties locally when using the database feature.
