### ISSUE TITLE
"reconnect to previously opened sessions" no working after 1.76.10 update

### ISSUE THREAD

**Issue by federicozanardi** [mRemoteNG/mRemoteNG#1139]
"reconnect to previously opened sessions" no working after 1.76.10 update
also "save connections on exit" is enabled of course

**Comment by Biero1** [comment]
I have the same problem.
Win10 x64

**Comment by federicozanardi** [comment]
I confirm that I have problem only on win10 x64
on win 2008r2 no issue

**Comment by edwillis777** [comment]
Same problem any idea when this will be fixed?

**Comment by mlen31** [comment]
same problem win 8.1

**Comment by edwillis777** [comment]
@sparerd any idea when the fix will be released?

**Comment by sparerd** [comment]
I'm going to try to get it out today
