### ISSUE TITLE
Feature Request: Right click option to copy hostname

### ISSUE THREAD

**Issue by goingmonk** [mRemoteNG/mRemoteNG#1141]
Feature Request: 
Add a Right click option to copy Hostname to clipboard added to general connection tab right click menu.

Benefits:
It allows for a quick source of the current hosts you working on for documentation or reference.

If there are a number of connections open it allows you to quickly go back and grab a host name for other use.

**Comment by sparerd** [comment]
Implemented by @MitchellBot in #1160 

This will be available in v1.77
