### ISSUE TITLE
Feature request: SSH tunnel for RDP

### ISSUE THREAD

**Issue by thany** [mRemoteNG/mRemoteNG#1142]
Connect through a SSH tunnel and then onto an RDP session.

## Expected Behavior
I'd like to be able to connect through a SSH tunnel. This is great for RDP servers that sit behind a firewall, where the firewall runs SSH and nothing (much) else. One shouldn't generally expose RDP to the internet directly anyway for security reasons.

The only available option that appears to do something vaguely similar, is RD gateway. However, this requires a Windows server, which is hugely expensive and RD gateway is a nightmare to set up anyway, last time I tried, so I assume no sane person would think to use it.

## Current Behavior
Since SSH functionality is in the program already, it probably doesn't involve more than adding some extra fields: SSH server, SSH port, SSH user, SSH password, SSH private key file.

It already knows how to deal with SSH, so setting up a tunnel before attempting a RDP connection is hardly different from SSH file transfers or SSH terminal.

## Possible Solution
Use existing SSH functionality. Alternatively, the program could use the underlying OS to deal with SSH. Windows 10 has several options to add a true SSH client, but since the program has it built-in already, use that if it's anywhere near up-to-date.

## Context
My RDP server sits behind a firewall for obvious reasons. That firewall can only be connected to via SSH with private key login. I will not be exposing this machine's RDP to the internet. I'm too paranoid to do that :)

## Your Environment
* Version used: 1.76.10.42480
* Operating System and version: Windows 10 x64 (10.0.17134.345)

**Comment by richard-scott** [comment]
That could be handy for any protocol. For example I frequently SSH to one server, to then SSH to the next hop inside that network. It would be great to be able to automatically setup a SSH tunnel and connect direct.

[RoyalTS](https://www.royalapplications.com/ts/win/features) has this feature and its really good.

**Comment by lars18th** [comment]
Hi,

This is already requested and planned: https://github.com/mRemoteNG/mRemoteNG/issues/420

So please, close this issue.

**Comment by sparerd** [comment]
As mentioned, this is a duplicate request. Please follow #420 for any updates
