### ISSUE TITLE
mRemoteNG Connection to Virtual Machine Starts up but then closes everything and logs off.

### ISSUE THREAD

**Issue by blackufinal** [mRemoteNG/mRemoteNG#1143]
## Expected Behavior
Normaly, i use my Remote Connection and it connects to the System, automaticly logs me in to the Desktop.

## Current Behavior
It connects to the system, logs me in, then cmd window shows up with some text and the task bar is missing with only some tray icons showing up and shortly after it logs off and closes the Remote connection.

## Context
I just wanna use my Virtual Machine normaly via Remote.
Alternative i log in to my Server where the Virtual Machine is running and use it there, also when i have an active session on the Server from the Virtual Machine the mRemote connection works.

## Your Environment
mRemoteNG
Version used: 1.75.7012.16814
Operating System: Windows 10 Pro but on every other OS i use same problem.
The Virtual Machine i try to use has: Windows 7 Professional
![unbenannt](https://user-images.githubusercontent.com/44231200/47085623-7abbaa00-d217-11e8-9246-799fb9f0148e.PNG)

**Comment by sparerd** [comment]
Is this using RDP? Does the same thing happen if you try to connect with a different client?

**Comment by blackufinal** [comment]
Somehow the Problem is gone now. It's strange because we had TsPlus running on this VM and TsPlus runs also VMs for other clients and we had the similiar problem there. We fixed a configuration problem in TsPlus recently and now the VM works fine.
