### ISSUE TITLE
Window doesn't move to Primary Monitor when unplugging Secondary

### ISSUE THREAD

**Issue by knightsofn1** [mRemoteNG/mRemoteNG#1147]
I use this a lot on my laptop and my secondary display is the one I use most as it is larger. If I unplug the secondary to leave my desk, the mRemoteNG window fails to move to the primary display with all the other open applications.

## Expected Behavior
If the window is open on the secondary monitor, it should move to the primary monitor when I unplug the secondary. 

## Current Behavior
Currently the window remains in the exact same position on the secondary display, forcing me to use [Alt]+[Space] to find the move window option and bring it back to the primary.

## Steps to Reproduce (for bugs)
1. Plug second monitor in
2. Open mRemoteNG
3. Move mRemoteNG window to second monitor
4. Unplug second monitor

## Context
This is primarily an irritation, but no other programs I use display this behaviour.

## Your Environment

* Version used: 1.76.10.42392
* Windows 10 x64, all versions since at least 1703.

**Comment by kmscode** [comment]
FYI - I was not able to reproduce this.

I have 3 monitors: 2* DVI in a docking station and 1 HDMI plugged in directly to the laptop, setup as follows:
HDMI DVI1 DVI2

DVI1 is my main display.

mRemoteNG is on HDMI.

Unplug HDMI (literally unplug it - no undocking, etc), application is then moved to DVI1 accordingly.

Tested on 1.76.10 on Win 10 1809.

**Comment by knightsofn1** [comment]
Embarrassingly I'm forced to agree with you. I can't reproduce this myself now. Apologies for this, if there's no action to take then you might as well close this issue.

**Comment by kmscode** [comment]
No worries. If you're able to narrow down the specific chain of events that cause the problem to reproduce the problem just reopen the issue.

**Comment by amousa1968** [comment]
Sure. I will send the details today when I reproduce the issue. 

Thanks 
Ayman Mousa
