### ISSUE TITLE
Creating bulk connections script is broke

### ISSUE THREAD

**Issue by sajalshres** [mRemoteNG/mRemoteNG#1149]
Error in generating bulk connections via the powershell script.

## Error
```
New-Object : Cannot find type 
[mRemoteNG.Config.Serializers.XmlConnectionNodeSerializer]: verify that the 
assembly containing this type is loaded.
At 
CreateBulkConnections_ConfCons2_6.ps1:31 
char:26
```

## Possible Solution
Update script as following:
$xmlSerializer = New-Object -TypeName mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26 -ArgumentList @($cryptoProvider, $encryptionKey, $saveFilter)

$xmlSerializer.Serialize($connectionInfo)

## Steps to Reproduce (for bugs)
1. PS> cd  [MRemoteNG_DIR]\Tools (enter)
2. PS> .\CreateBulkConnections_ConfCons2_6.ps1 (enter)

## Your Environment
**Powershell Version**
- PSVersion                      5.1.17134.228
- PSEdition                      Desktop
- PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
- BuildVersion                   10.0.17134.228
- CLRVersion                     4.0.30319.42000
- WSManStackVersion              3.0
- PSRemotingProtocolVersion      2.3
- SerializationVersion           1.1.0.1

**Comment by chreestopher** [comment]
im still having issues with the createBulkConnections script.
It works fine if i want to make a flat collection of connections.

However, even the examples included in the script of how to make something structured with different containers doesnt work. It always just outputs an empty string for the SerializedXML

No errors.

Wasnt sure if I should open another issue or raise this one from the dead. Please let me know if i should submit a new issue
