### ISSUE TITLE
Requested session access is denied

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1161]
I am getting the following error with one of my connections:
![image](https://user-images.githubusercontent.com/22905106/47677387-3c32d180-dbbf-11e8-9397-1ea86d8916b5.png)

I already tried deleting/recreating the connection but the result stays the same.
When I'm using the Windows RDP-Client I can connect just fine.
The Server is a 2008R2 Terminalserver.
In the Log it seems like the connection is being established just fine:

> 2018-10-29 21:15:47,359 [1] INFO  - mRemoteNG 1.76.11.40527 starting.
> 2018-10-29 21:15:47,369 [1] INFO  - Command Line: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
> 2018-10-29 21:15:48,689 [1] INFO  - Microsoft Windows 10 Pro  64-bit
> 2018-10-29 21:15:48,689 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
> 2018-10-29 21:15:48,689 [1] INFO  - System Culture: de-DE/Deutsch (Deutschland)
> 2018-10-29 21:15:48,689 [1] INFO  - Checking FIPS Policy...
> 2018-10-29 21:15:48,689 [1] INFO  - Checking Lenovo AutoScroll Utility...
> 2018-10-29 21:15:48,959 [1] INFO  - Loading External Apps from: C:\Users\USERNAME\AppData\Roaming\mRemoteNG\extApps.xml
> 2018-10-29 21:15:48,969 [1] INFO  - Adding External App: WinSCP C:\Program Files (x86)\WinSCP\WinSCP.exe scp://%Username%:%Password%@%Hostname%/
> 2018-10-29 21:15:48,969 [1] INFO  - Adding External App: SSMS ssms -S %Hostname% -E
> 2018-10-29 21:15:51,819 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
> 2018-10-29 21:15:59,369 [1] INFO  - Setzen der Konsolenumschaltung für RDC 10.0.17763.
> 2018-10-29 21:15:59,369 [1] INFO  - RDP-Gateway wird unterstützt.
> 2018-10-29 21:15:59,914 [7] INFO  - Saving connections...
> 2018-10-29 21:16:01,489 [1] INFO  - Ereignis Verbindung hergestellt
> 2018-10-29 21:16:01,489 [1] INFO  - Verbindung zu "ts1" mit "RDP" hergestellt von Benutzer "USERNAME" (Beschreibung: ""; Benutzer Feld: "")
> 2018-10-29 21:16:01,697 [7] INFO  - Successfully saved connections

I have no clue how I could investigate this further. Any ideas?

## Your Environment
* Version used: 1.76.11.40527
* Windows 10 18**09** Build 17763.55

**Comment by sparerd** [comment]
Have you tried to right click connection -> `Connect (with options)` -> `Connect to console session`?

**Comment by farosch** [comment]
I just did - same result.

**Comment by sparerd** [comment]
Did some quick googling and found a few posts that actually say to turn that option off. Does that connection have the `Use Console Session` property enabled? Or maybe it's inheriting it from a folder?

**Comment by farosch** [comment]
@sparerd that was it! I unintendedly inherited this setting onto the onnection. It then tried to connect to the console session on the server, which is impossible for a non-admin account on a terminal server.
Sorry for this non-issue ;)
