### ISSUE TITLE
Connection through MSSQL

### ISSUE THREAD

**Issue by paperplane90** [mRemoteNG/mRemoteNG#1162]
When we trying to connect to servers tab open in all users who are using MSSQL
## Steps to Reproduce (for bugs)

1. Connect to MSSQL
2. Connect to server
3.
4.

## Your Environment

* Version used: 1.76.11.40527
* Operating System and version (e.g. Windows 10 1709 x64):

Windows 10

**Comment by sparerd** [comment]
Could you provide more information? I'm not sure what the issue is or what you are trying to do

**Comment by paperplane90** [comment]
We have 1 database MSSQL.
All my teammates use this DB.

When I start new connection (ssh, rdp) this connection opening in all my teammates

**Comment by sparerd** [comment]
Ahh I understand now. This is a known issue - please follow #1134 for further updates
