### ISSUE TITLE
highlight command output

### ISSUE THREAD

**Issue by ruggia70** [mRemoteNG/mRemoteNG#1163]
## Current Behavior
Please it is possibile to highlight output commands? For example during telnet session on a switch, if a port is connected show the "Connected" in green?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
That would be a putty setting, though I don't think Putty has anything like that. To my knowledge, you can only change font/background for the entire putty session.

**Comment by farosch** [comment]
@ruggia70 Take a look at [THIS](https://blogs.msdn.microsoft.com/astebner/2007/03/14/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os/)

**Comment by farosch** [comment]
This is not possible for us to do. Even if we were to use another implementation than PuTTY for SSH sessions that supports colored output we would still need the server to colorize its output.
Simply searching for let's say `Connected` in the output and coloring it green is no solution. There are a ton of scenarios where that word could be part of an output and you wouldn't want it to be colorized.
