### ISSUE TITLE
Inheritance Propagation

### ISSUE THREAD

**Issue by jreagan00** [mRemoteNG/mRemoteNG#1164]
## Expected Behavior

A way to apply\force inheritance on all sub folders\connections, It should propagate to all sub folders and connections.

## Current Behavior

Inheritance has to be set on each folder or connection one at a time.

## Possible Solution

A way to apply\force inheritance on all sub folders\connections, It should propagate to all sub folders and connections.

## Steps to Reproduce (for bugs)

1. Set Inheritance on Top level folder
2. Nothing below it has any inheritance set
3.
4.

## Context

I imported a large organized list of servers from a previous RDP Manager and having to set inheritance on all of them is a deal breaker. I dont have a couple days to go through hundreds of servers. 

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 using latest Stable

**Comment by sparerd** [comment]
Closing as duplicate of #870
