### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Lincoln23** [mRemoteNG/mRemoteNG#1166]
## Context
Trying to update to version 1.76.11.40527  but I am getting this error when I try to download and install.
`The request was aborted: Could not create SSL/TLS secure channel.`

## Your Environment

Windows 10, the latest version

**Comment by sparerd** [comment]
Please see this comment: https://github.com/mRemoteNG/mRemoteNG/issues/1135#issuecomment-429641183

Closing as duplicate
