### ISSUE TITLE
Chromium Rendering Engine?

### ISSUE THREAD

**Issue by leaskovski** [mRemoteNG/mRemoteNG#1167]
I thought it would be an idea to use https://remotedesktop.google.com/access as a HTTPS connection type to get access to machines using the Chrome Remote Desktop tool.

I have tried using both the current rendering engines (Gecko and IE) but neither of them seem to ply nice with the site, and to be honest, the site does say that Chrome is a recommended browser to use it, so I was wondering if it is possible to include chromium as a rendering engine for websites, as in theory, that should load the site fine?  Maybe?

**Comment by leaskovski** [comment]
Doh!  I should search better, just found this, #1071

**Comment by TrueOsiris** [comment]
In case you cannot get your chromium rendering engine to work (blank pages) look at #2428
