### ISSUE TITLE
Connection and Config tab won't open

### ISSUE THREAD

**Issue by UNiXMIT** [mRemoteNG/mRemoteNG#1168]
Very often when I connect to a remote machine using mRemoteNG and then I want to connect to another, when I click the connections tab or config tab they won't open. I have to close my current connection first.

This worked before I updated recently. My tabs are set up on the side as in the attached screenshot:

![screenshot_1](https://user-images.githubusercontent.com/4117073/47848627-d749c800-ddc6-11e8-9690-8ef1a6a74276.jpg)

## Expected Behavior
When I am connected to a remote machine i should still be able to open the conections tab without having to disconnect my current session. This is a regression.

## Current Behavior
When I am connected to a machine already, when i click connections on the left tab i set up then it doesn't open.

## Your Environment
* Version used: 1.76.11 (2018-10-18) This started happening after the latest update.
* Operating System and version (e.g. Windows 10 1709 x64): Windows 7 64bit

**Comment by sparerd** [comment]
What is the protocol of the connections that cause this bug? I'm not able to replicate the issue with an RDP session open.

**Comment by UNiXMIT** [comment]
I think when it happened this morning I was connected to my linux machine via ssh2. I’ll double check this again shortly.

**Comment by sparerd** [comment]
Ok, thanks for checking.

**Comment by sparerd** [comment]
Interestingly, disabling then enabling either the connections or config window (View -> Connections) stops the bug from occurring.

**Comment by sparerd** [comment]
But then alt+tabbing away form mremoteng makes it come back..

**Comment by sparerd** [comment]
Fixed the issue - the fix will be available in the v1.76.12 release

**Comment by UNiXMIT** [comment]
Excellent thank you. I have disabled themes in the mean time as I wasn't using them anyway.
