### ISSUE TITLE
Connection File GUI on Startup is buggy

### ISSUE THREAD

**Issue by weshinsley** [mRemoteNG/mRemoteNG#1184]
## Expected Behavior
Previously loaded configuration file should reload on startup.
Import an Existing File should allow loading of an XML file.

## Current Behavior
"The connection file could not be found" GUI appears on every start up since upgrading to 1.76
Clicking "Import an Existing File" on that GUI doesn't do anything.
The workaround is:
Click on "Use a Custom File Path"
Click Cancel
Click "Ask me again later" or "Use Recommended Settings"
Click File Open Connection File and browse to %UserProfile%\AppData\Roaming\mRemoteNG\confCons.xml.
All appears to work - until you restart mRemoteNG

## Possible Solution
Not sure - but before upgrading from 1.75, I had none of these problems.

## Steps to Reproduce (for bugs)
For me, it happens every time on startup.
1. Start up mRemote.
2. Try clicking Import an Existing File...
3. Follow steps in "Current Behavior"
4. Close mRemoteNG
5. Run it again... and do the process all again.

## Context
It's just very annoying to go through the workaround every time on startup.

## Your Environment
* Version used: 1.76.11.40592
* Windows 10 1803, fully udpated.
* But no issues at all in this enviroment on v1.75 (unsure of exact previous version)

**Comment by sparerd** [comment]
It sounds like your settings file is either never saving preferences or being deleted. Since you are on the portable version, the settings file saves in the same directory as the mRemoteNG.exe file and is called `mRemoteNG.settings`. 

If you watch this file while doing your mRemoteNG startup workaround, does the file ever update? If you do the workaround then close the app immediately, does the file update then?

**Comment by weshinsley** [comment]
Ok, so copying my confCons.xml file into the installation directory (C:\Program File (x86)\mRemoteNG) indeed causes it to load my config file automatically on startup, and I don't get any message about that - which is fine (although the not-working menu option for "Import an Existing File" may still be worth looking into).

There's no "mRemoteNG.settings" file in that folder.

What I get now every time I start up is a dialog about Automatic update settings, with options "Use the recommended settings", "Customize the settings now", and "Ask me again later". Whichever of these I choose, I get the message popping up the next time mRemote is run.

**Comment by weshinsley** [comment]
Right, I think I see what's happening - I've installed the 1.76 upgrade on top of where the 1.75 version was - C:\Program Files (x86)\mRemoteNG - and am re-using the same shortcut to run it as I did before - but the shortcut does not seem to be set to "run as administrator", which it would probably need to be, in order to write files in C:\Program Files (x86)\mRemoteNG. My 1.75 version didn't need to because all its files were written to my profile, which doesn't need admin rights.

I am also wondering whether I have have somehow upgraded from an install version, to a portable version - hence, the portable version might not be expecting to run from within C:\Program Files (x86). So perhaps to really clear things up, a full uninstall and reinstall of an install (non-portable) version might be a good idea...

**Comment by sparerd** [comment]
Yes that seems very odd. The version you posted in your OP (1.76.11.40592) is definitely the portable version, which doesn't need to be installed (just unzipped). It needs write access to the dir the EXE is located in. The installed version (1.76.11.40527) writes its data to the user profile (as you were expecting).

It sounds like you may have overwritten your installed version with the portable version. I agree that it's probably best to make a backup of your connections file (to be safe) and completely uninstall/reinstall mRemoteNG using the MSI installer.

**Comment by farosch** [comment]
Closed due to inactivity.
