### ISSUE TITLE
Enhancement - Windows Multi-System Login

### ISSUE THREAD

**Issue by jmartins1** [mRemoteNG/mRemoteNG#1187]
Situation:
I am an admin at a school. We have two computer labs.
During student testing staff is required to login to each computer to setup the testing environment.
As you can image after multiple days of testing and having to manually login 100 devices each day the task becomes frustrating.

What I'm NOT looking for:
I'm not looking for RDP
nor 
VNC

I do not want to defeat the login. I simple want to send a command to multiple computer to log them in.

What I NEED:
Have a centralized way to login into each computer using a single user name and password.

The closest item I was able to find to offering this feature is: https://www.evidian.com/

If you are aware of a free or opensource product that already supports this feature please let me know. 

Thank you for your time.

**Comment by sparerd** [comment]
I think I see what you are after, but I want to clarify:

Currently:
- A staff member who is in the comp lab will manually login to each machine using a generic account (ex: lab_user) and perform the setup.

Ideally:
- When setup needs to be done, someone lets you know and you send a command to a set of computers that will begin a local user session using the generic account (lab_user). Now the staff member in the comp lab can setup the testing environment without worrying about the "login" step.
- The reason VNC/RDP is not a valid solution is because you are not doing the testing setup yourself, you just want to make things go smoother for the computer lab staff.

**Comment by jmartins1** [comment]
Yes, exactly. It’s odd there are thousands of schools and no product to do just that!

 

Simply, send a command to multiple computers so that others can use them without logging in. RDP would work except that it locks out the session to anyone at the computer. VNC would work but it requires that a user is already logged in.

 

 

Thank you,

 

Jose Martins, M.Ed., MCSA, MCP

IT Administrator

 



 

303.362.1266

705 Austin Ave. Erie, Co 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by sparerd** [comment]
This tool *might* do what you want: https://www.logonexpert.com/help/command.html. Install the tool on any machine you need to login to, then run `le.exe -logon <details>` from cmd line using either powershell remoting or PSExec. I haven't used this tool before and I haven't tested it to see if your use case works as expected. 

I'm not sure how it performs the login step on the local machine, though I can guess that it might be using the auto-logon feature of Windows (and then disabling it right away after the logon has succeeded).

This workaround might do what you want as well: https://superuser.com/questions/80334/remote-desktop-connection-without-locking-the-remote-computer#415829. Login to each box via RDP then run the `tscon` command to transfer the session to the local machine. Haven't tested it myself but seems like a valid solution.

To my knowledge, there is no built-in way to start a local user session from the command line. At some point in the process, [Advapi32.dll+LogonUserA](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-logonusera) gets called. Though I'm not sure if there is a higher function that should be called to ensure things like profile info, logon scripts, etc get called correctly.

**Comment by jmartins1** [comment]
Thank you, gave it a shot but didn’t work and the documentation is poor. I’m down to creating a GPO to enable and disable automatic login. There has to be a more elegant solution. mRemote, schools everywhere would love you if you came up with a solution.

 

 

 

 

Jose Martins, M.Ed., MCSA, MCP

IT Administrator

 



 

303.362.1266

705 Austin Ave. Erie, Co 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.
