### ISSUE TITLE
add additional putty menu options

### ISSUE THREAD

**Issue by lukastribus** [mRemoteNG/mRemoteNG#1189]
From the context menu of an active session we can already access the settings menu of puttyng (`PuTTY Settings`).

If woud be useful to also access putty menu items like `Clear scrollback`, `Reset terminal`, `Copy all to clipboard` and especially `Event log`. Also `Restart Session` on inactive/dead sessions. Superputty does exactly this.

## Expected Behavior
Just as `PuTTY Settings`, also implement other putty options like `Clear scrollback`, `Reset terminal`, `Copy all to clipboard` and especially `Event log`. Also `Restart Session` on inactive/dead sessions.

## Current Behavior
Only `PuTTY Settings` can be accessed.

## Context
Clearing scrollback, retrying something in the terminal and copying the entire output to clipboad is what I use regularly in my workflow. Event log is also often necessary for me, when troubleshooting SSH related issues, among others. Restarting the sessions after a timeout is also regularly needed. All of this is in vanilla putty and accessible in Superputty.

## Your Environment
* Version used: mRemoteNG 1.76.12.38511
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 x64

**Comment by BloodyIron** [comment]
I'd love this too! Yay! :D

**Comment by farosch** [comment]
As @kmscode said use `CTRL`+`right click` to access the PuTTY context menu.
We will not integrate PuTTYNG into mRemoteNG any further, as the overall goal is to get rid of PuTTY completely, for obvious reasons.
#1262, #181, #1408, #398 and so on and so forth... (just to name a few)
