### ISSUE TITLE
Could not remote desktop to server using mremoteNG on windows 10

### ISSUE THREAD

**Issue by vupv** [mRemoteNG/mRemoteNG#1194]
Hi All,

Could you help me on problem when remote destop to server  using mremoteNG on windows 10. 

Sometime I can remote but sometime not and got error below

----------
WarningMsg
11/19/2018 14:39:34
RDP disconnected!
3334 Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again.
----------

My windows 10 version 1809

**Comment by vupv** [comment]
"how the server is setup" what do you want to know ?

**Comment by nmat** [comment]
is firewall set correctly? Is the server on static or dynamic ip? What does event viewer on server say?

Also is the service turned on correctly inside this pc -> properties -> remote settings?

**Comment by farosch** [comment]
Windows 10 1809 comes with a corrupted version of mstsc.exe that results in a variety of different errors.
So this has most likely nothing to do with mRemote. You can replace your mstsc.exe with a working version from Windows 1803 or earlier which will resolve these issues or wait for Microsoft to release a fix via Windows Update.

**Comment by farosch** [comment]
@vupv To what Version of Windows are you trying to connect to?

**Comment by farosch** [comment]
@vupv This seems not to be an issue with mrng. Most likely this is related to the server you are trying to connect to. Error 3334 can occur when you have reached the limit of rdp connections (which would fit your statement, that it sometimes works and sometimes doesn't)

As this is a relatively old issue and you have yet missed to answer any questions from me or @nmat I will close this issue. If you still need support on this topic feel free to reopen this issue.
