### ISSUE TITLE
[feature request] Copy all to clipboard

### ISSUE THREAD

**Issue by irsl** [mRemoteNG/mRemoteNG#1209]
## Expected Behavior
Putty features "Copy all to clipboard" to put all lines in the current session to the clipboard.

## Current Behavior
Feature is missing

## Possible Solution
Implementing the same or exposing Putty's drop down menu.

## Steps to Reproduce (for bugs)
-

## Context
This is a feature I use on a daily basis.

## Your Environment
Windows 10, but doesn't really relevant.

**Comment by BloodyIron** [comment]
I actually really need this functionality! I use it regularly in putty, and it would be a big help if it were in mRemoteNG! :D  

Please? 🤔

**Comment by farosch** [comment]
@irsl @BloodyIron You can already do so by using `CTRL+LEFT_MOUSE` inside an SSH session.
This is a default PuTTY behaviour and opens this sub-menu:
![image](https://user-images.githubusercontent.com/22905106/59640595-db143a00-915e-11e9-9d22-744f1f85c593.png)
I've also just added a hint in the documentation, as not every user may know this.

**Comment by BloodyIron** [comment]
@farosch oooo looks like I'll have to try that! Thanks! :D
