### ISSUE TITLE
Double click on "tab-switcher" closes tab

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1211]
Double-clicking on one of the marked arrows in the picture below closes the current tab.

![2018-12-17_18-21-26](https://user-images.githubusercontent.com/22905106/50103859-e4acfb80-0228-11e9-9454-f0f7c6029c28.png)

## Your Environment

* Version used: 1.76.11.40527
* Operating System and version: Windows 10 x64 1809 17763.194

**Comment by farosch** [comment]
Related  MagicLibrary, See #155.

**Comment by kmscode** [comment]
Marking this one as resolved since magiclibrary is removed in the removemagiclib branch and these controls are no longer available.

The controls were created by magiclibrary and we don't have any trusted source for that component.
