### ISSUE TITLE
Request: Move searchbar to top of connection tree

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1216]
The searchbar in the connection tree panel is currently placed at the buttom of the window.
The handling would IMHO be easier, if placed at the top for numerous reasons. Some of them being:

- Mostly searchbars are placed at the top, so this is where you'd expect it to be
- All functional UI elements are gathered at the same place
- Shorter distances to travel with your cursor, especially when filtering (see screenshot below)

![image](https://user-images.githubusercontent.com/22905106/50284560-aa767080-0459-11e9-86b9-7ae0f91e63cf.png)

This is a simple mock-up of how it could look:
![gimp-2 10_2018-12-20_13-16-21](https://user-images.githubusercontent.com/22905106/50284595-cc6ff300-0459-11e9-9c64-2ae4d8a6f95e.png)

I'd be happy to provide a PR if you want me to ;)

**Comment by kmscode** [comment]
I would love a PR for this! I think it makes a lot of sense.
