### ISSUE TITLE
Impossible to proceed to an update

### ISSUE THREAD

**Issue by OSITEX** [mRemoteNG/mRemoteNG#1225]
Error SSL / TLS
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.75.7012.16814
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 17134.472 x64

**Comment by sparerd** [comment]
This is a known issue. Please see this comment for more information: https://github.com/mRemoteNG/mRemoteNG/issues/1135#issuecomment-429641183
