### ISSUE TITLE
Impossible to proceed to an update

### ISSUE THREAD

**Issue by OSITEX** [mRemoteNG/mRemoteNG#1226]
La demande a été abandonnée : Impossible de créer un canal sécurisé SSL/TLS.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
This is a known issue. Please see this comment for more information: https://github.com/mRemoteNG/mRemoteNG/issues/1135#issuecomment-429641183
