### ISSUE TITLE
When will you support radmin?

### ISSUE THREAD

**Issue by okman523** [mRemoteNG/mRemoteNG#1242]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
Given that it is a commercial solution, it is unlikely we ever will support Radmin. If their protocol was open source or they provided a freely distributable client API, then it would be possible.

**Comment by farosch** [comment]
Like @sparerd already said, radmin is a proprietary solution, which makes it impossible for us to implement it ito mRemoteNG.
