### ISSUE TITLE
Options form takes nearly 3 seconds to appear when Theming is active

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1245]
When a theme is active, the Tools -> Options window takes ~3 seconds to display.

## Expected Behavior
The window should display nearly instantly (~300ms or less).

## Current Behavior
Options window displays after a delay of ~3 sec.

## Possible Solution
Investigate runtime calls to determine what is using up so much time. Optimize calls where possible.

## Steps to Reproduce (for bugs)

1. Without theming active, open the Options window and notice that it opens instantly.
1. Activate a theme (Tools -> Options -> Theme -> Enable Themes) and restart mRemoteNG
2. Open the Options window and notice a long delay before the window appears.

## Your Environment

* Version used: Current `develop` branch, may be in released versions too

**Comment by sparerd** [comment]
@kmscode Seems to be slightly faster, but still takes an oddly long time to show the form.

**Comment by sparerd** [comment]
Cancel that, tried in a non-debug build and it was better

**Comment by kmscode** [comment]
LoadSettings calls cboTheme_SelectionChangeCommitted which calls ColorMeList - which takes about 500ms in a debug build. But I don't see any way to speed that up.
