### ISSUE TITLE
Installation issue on Window 10

### ISSUE THREAD

**Issue by ap-nsx** [mRemoteNG/mRemoteNG#1251]
Installation issue on Window 10

Expected Behavior = Installation should work

Current Behavior - When trying to install on corporate windows 10 build, the install process genereates a error stating that it can't find/access a dll file. 

Possible Solution - Can you tell me what dll file it is trying to find /access as I cant find the file listed in the logfile. 
The install.log is attached. 
Thanks in advance
Andy

Your Environment - Windows 10 enterprise. 
Below is my logfile 
[mremoteng_install-v1.log](https://github.com/mRemoteNG/mRemoteNG/files/2727242/mremoteng_install-v1.log)

**Comment by ap-nsx** [comment]
![mremote error](https://user-images.githubusercontent.com/19490919/50692013-6757f800-102a-11e9-9d84-1bd1a0e68e8f.JPG)

**Comment by sparerd** [comment]
The dll gets copied to a temp location on every run of the installer. The file it attempted to run during the install that your log file was from was `%LOCALAPPDATA%\Temp\MSI3877.tmp`. This file name is not likely to be the same between install runs.

If the file is getting copied to the temp dir correctly, it may be a permissions issue when trying to execute the dll. Are there any security restrictions on your machine that might be interfering?

**Comment by ap-nsx** [comment]
Thanks for the info. I believe that there are no security restrictions, but I will get confirmation. Once I know either way I will update this thread. Thanks again for the quick response.

**Comment by ap-nsx** [comment]
Just to let you know that the issue is fixed. There seems to be a wider issue with windows 10 installing programs.
FYI The workaround was to install mremoteng via the command line as per this article. 

https://www.wikihow.com/Run-Exe-from-Cmd-on-PC-or-Mac

I suspect MS wil release a fix at some point.

Thanks for all your help. I am just glad that I can now install and use mremoteng. Its a great application

**Comment by sparerd** [comment]
Thanks for following up @ap-nsx, glad to hear there's a workaround
