### ISSUE TITLE
Put some screenshots on the homepage.

### ISSUE THREAD

**Issue by oliverjanik** [mRemoteNG/mRemoteNG#1263]
https://mremoteng.org

**Comment by benwa** [comment]
Sounds good to me.  I can imagine we can get the main window with a good list of servers and open connections in one screenshot.  Any ideas of other screenshots, or should it just be the one main screen?

**Comment by sparerd** [comment]
Maybe one showing the external tools management and/or using an integrated external tool?

**Comment by kmscode** [comment]
Maybe we should wait until 1.77 when magic lib is removed and the cred manager is in there... With just DPS and the new themes, it does look a bit nicer... Cred manager would be good to show off also...
