### ISSUE TITLE
putty panel not fitted into window (you can drag it around like a mdichild)

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#1265]
Reference #1261

## Steps to Reproduce (for bugs)

1. Open putty connection
2. See a sliver of the putty window
![image](https://user-images.githubusercontent.com/16654335/50974248-cef1c580-14b8-11e9-98cd-98201cfffe7a.png)

3. this can be dragged within the connection panel
![image](https://user-images.githubusercontent.com/16654335/50974316-f779bf80-14b8-11e9-8d32-4b6baa7b416f.png)

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
Dev note: any fix for this should be tested on multiple OS versions, MRNG themes, and on a HiDPI machine.

The fact that this has been an issue several times before tells me we haven't found a good fix for it. Might need deeper investigation into the current method used for finding the putty window's system border width.
