### ISSUE TITLE
unable to rearrange connections within same level in the connection tree by dragging

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#1266]
Problem occurs in **develop** _and_ removemagiclib branches. Does not occur in 1.76

## Steps to Reproduce (for bugs)

1. Drag from top level connections to folder or vice-versa: OK
2. Attempt to Drag connection to place it above or below another connection within the same level of the tree and the 🚫 symbol is displayed
3. Ctrl + Up/Down works
4. Right click move up/down works

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by sparerd** [comment]
Dev note: start investigation in the `ConnectionTreeDragAndDropHandler` class

**Comment by kmscode** [comment]
Looks like HandleEvent_ModelCanDrop is always getting "Item" as e.DropTargetLocation.

**Comment by kmscode** [comment]
ConnectionTreeDragAndDropHandler.cs hasn't been modified since 11/2017...

ConnectionTree.cs was modified for the Segoe UI font with some other refactoring, I reverted that change and still had the problem. Reference commit: d87283b7d7686b9d6927e29ea3a60fa5fe7431b8

Some thoughts:
pull the source for ObjectListView and build the latest to see how that goes. There a a few fixes, but none related to this problem.

DPI related fixes might be having a negative impact on this?

**Comment by kmscode** [comment]
Confirmed fix. Closing.
