### ISSUE TITLE
Issus with prompt on settings change

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1274]
## Expected Behavior
When a setting is changed that requires a restart a prompt is being shown.

## Current Behavior
 - Prompt always says the restart is needed to apply a theme
![2019-01-12_18-54-55](https://user-images.githubusercontent.com/22905106/51076684-fb196c00-169b-11e9-9d7a-7b16c0250081.gif)

 - Prompt is shown even when setting does not require a restart
![2019-01-12_19-04-35](https://user-images.githubusercontent.com/22905106/51076754-028d4500-169d-11e9-8e05-70d5faa7ca07.gif)

## Your Environment

* Version used: latest RemoveMagicLib branch
* Operating System and version: Windows 10 1809 x64

**Comment by kmscode** [comment]
See if you still get the prompt after restarting and changing other unrelated options again. The latest changed made a few changed and it might prompt you once/the first time options are modified since some theme names changed.

**Comment by farosch** [comment]
confirmed, only appears once
