### ISSUE TITLE
crash when using Barco Clickshare

### ISSUE THREAD

**Issue by Zenn1th** [mRemoteNG/mRemoteNG#1278]
After few seconds/minutes mremote closes, without warning or crashreport.

## Expected Behavior
It should keep displaying servers when sharing your screen in a meeting

## Current Behavior
After few seconds/minutes mremote closes, without warning or crashreport.

## Steps to Reproduce (for bugs)

1. open mremote
2. start clickshare button
3. use mremote and wait for it to crash
4.

## Context
When presenting multiple servers in a work environment, we have to recoonect to all sessions

## Your Environment
W 10 1803 x64 enterprise
mremote 1.76.11.40527

**Comment by sparerd** [comment]
Is there anything in the log file or was a crashdump produced?

https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by Zenn1th** [comment]
Dump files
[mRemoteNG.exe.258108.zip](https://github.com/mRemoteNG/mRemoteNG/files/2763254/mRemoteNG.exe.258108.zip)

**Comment by farosch** [comment]
We do have ClickShare in our company - I'll try to take a look into this next week.

**Comment by farosch** [comment]
@Zenn1th 
I've been using mRemoteNG with ClickShare for almost an hour now and I haven't had any crashes yet.
Are you sure you aren't doing anything special that could cause the crash or do you maybe have another software installed that might interfere with ClickShare?
Also please make sure that your base and the dongles are on the latest firmware. The ones I am using were updated yesterday a colleague told me.

**Comment by Zenn1th** [comment]
openening multiple servers tofast when using clickshare?

its almost and instantanious crash

**Comment by martinreis** [comment]
same for me: ClickShare-adapter and central unit are now on the latest firmware, but mRemote on Win10 is crashing still.

**Comment by farosch** [comment]
I've been using clickshare with mRemoteNG for one hour every week for the last 17 month and did not have a crash once.
My guess is that this has something to do with a specific combination of hardware/clickshare/windows.
Can anyone please reaffirm, that this is indeed still a problem?

**Comment by farosch** [comment]
Closing as stale.
