### ISSUE TITLE
Minimize window closes connections

### ISSUE THREAD

**Issue by csveazey** [mRemoteNG/mRemoteNG#1279]
When working in the app if I click the - to minimize the window it closes all of my open connections and exits the application.  Is this normal or just me?  

Running on Windows 10 Pro and it's happening on all 3 of my workstations.  
This workstation:
Dell Precision M75 Laptop
Windows 10 Pro 1709 build 16299.431
Xeon E3-1535 v5 @ 2.90GHz
48GB RAM
NVIDIA Quadro M2000M 4GB Video

**Comment by sparerd** [comment]
Which version of mRemoteNG?

**Comment by csveazey** [comment]
Installed version is 1.76.11.40527

**Comment by farosch** [comment]
@csveazey Can you please check if the "minimize to notification area" setting is checked?
![image](https://user-images.githubusercontent.com/22905106/52742807-db49d080-2fd8-11e9-8f15-bb8125e22585.png)
If so, mrng does not actually closes but minimizes to your taskbar.

**Comment by farosch** [comment]
Closed due to OP not responding
