### ISSUE TITLE
Few pixels of the first char of putty pane is covered by the vertical scroll bar

### ISSUE THREAD

**Issue by xiaoguazh** [mRemoteNG/mRemoteNG#1282]
The same slight issue happens on the latest stable version and also the pre-release version.
The left of putty pane is covered by the vertical scroll bar with few pixels (about 1/10 ~ 1/5 of a char)
This doesn't impact any functionality, but from user friendly point of view, this UI may looks wired for certain people.

## Expected Behavior
I expect the putty-pane can be properly displayed without any side being covered by other pane. 
I didn't notice this slight UI issue with the elder version. 

## Current Behavior
Start mRemoteNG, open one e.g. ssh session, the console will show the prompt lines, and about 1/10 ~ 1/5 or the first char are covered by the middle vertical scrollbar.

## Possible Solution
Not find a workaround.

NOT sure whether this is a wrong-configuration issue? or any code changes on mRemoteNG when displaying putty-pane?

## Steps to Reproduce (for bugs)
This can be easily reproduced.

Start mRemoteNG, open one e.g. ssh session, the console will show the prompt lines, and about 1/10 ~ 1/5 or the first char are covered by the middle vertical scrollbar.

## Context
I can tolerate this slight UI issue, luckily only few pixel are covered to the first char of each line on putty pane, I can identify the char/words

## Your Environment
Win7 Enterprise, v 6.1.7610

mRemoteNG 1.76.13 (2018-12-22)
mRemoteNG 1.76.12 (2018-11-08)
mRemoteNG 1.76.11 (2018-10-18)

**Comment by xiaoguazh** [comment]
Tried change the Theme setting, I could confirm it caused by Themes :-)

Theme: "vs2013xxx" and "vs2012xxx" are better.
Theme: "vs2015xxx" will cover few pixels of the first char of each line.
Theme: "vs2003", "vs2005", "darcula" will cause error always.

**Comment by coloomb** [comment]
Changing themes (and restarting mRemoteNG doesn't help.I've tried every single theme and restarted mRemoteNG without any success. Still same issue and as I have very small font I can's see first character. Please see attached screenshot. 
I'm running the latest pre-release - 1.76.13 (2018-12-22):

![2019-01-21 11_54_38-clipboard](https://user-images.githubusercontent.com/6411739/51473134-5f5ebe80-1d73-11e9-85c3-249aa18a7fc2.png)

**Comment by xiaoguazh** [comment]
@coloomb 

I'm using the same version, it looks your case are even worse than me, I'm now using theme: vs2912light, it looks acceptable for me.

![image](https://user-images.githubusercontent.com/19484664/51475802-74147400-1dbe-11e9-9f2f-e3bad5824458.png)

**Comment by coloomb** [comment]
Thanks for the workaround but there is reason I'm using ProggyTiny 8-point font and this workaround doesn't work for me. I'm going to revert to the previous version for now as I'm not really affected by any of the bugs fixed in those new versions. 
I'm glad that Devs are working on it and I love this software so big thanks to the DEVS for keep it alive and forking from mRemote! Cheers!

**Comment by xiaoguazh** [comment]
@kmscode

Thanks a loooooot !! :-) This v 1.77.0 does resolve this issue. We can close this issue now :-)

 I did a test also with ProggyTiny font, see screenshot:

![image](https://user-images.githubusercontent.com/19484664/51651419-c4f6b900-1fc6-11e9-9cc7-61d75c5aa19b.png)
