### ISSUE TITLE
Error with connection files after reopening the application for the second time.

### ISSUE THREAD

**Issue by safejrz** [mRemoteNG/mRemoteNG#1284]
After installing the aplication I re-open it for the second time and it shows me an error message like: 
The startup connection file could not be loaded 

## Expected Behavior

It should open normally

Workaround is to delete the connections file and reopen the application.

## Current Behavior

It brakes instead of opening with the latest connection config.

## Possible Solution

Fix the Export process, it seems also broken
The save connection process is broken, that may be the root cause. idk.

## Steps to Reproduce (for bugs)

1.Clean Install 
2.Choose open from import
3.Close the application saving the connections file.
4.Re launch the application.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 1709  x64 V5.2 June 2018

**Comment by farosch** [comment]
Closing as stale
