### ISSUE TITLE
SSH sessions show malformed on ncurses apps

### ISSUE THREAD

**Issue by JonAnder83** [mRemoteNG/mRemoteNG#1285]
## Expected Behavior
When connection via SSH from a windows machine, the characters are supposed to have certain alignment, tabulations, etc, so they can display the information correctly.

## Current Behavior
Some tabs, spaces, etc, are not properly drawn.
Example screenshots:
https://imgur.com/a/HbBS6xn
https://imgur.com/a/VNouRKf

## Possible Solution
I wish I knew

## Steps to Reproduce (for bugs)
1. Login via SSH to any connection from a windows machine
2. Launch any ncurses utility like, for example, glances

## Context
It happens with many scenarios and it just makes the whole sessions look weird.

## Your Environment
Latest mRemoteNG
Windows (No matter the version, tried 10, 2019, 2016, 2012, 2008, windows 7....

**Comment by kmscode** [comment]
Unable to reproduce in magiclibbrach with #1265 (latest changed that touch some PuTTYNG and display items). 

My putty sessions send to a large area of the window, so I had a lot of space available in comparison to your screen shots. I then shrunk the sessions down quite small by resizing the mRemoteNG window and everything still looked good.

Will keep an eye on this going forward...

**Comment by JonAnder83** [comment]
Ok, this had to do with my old system or something, since I had to re install my machine and now I don't see those malformations I used to see before.
However, I still have issues with some characters, specially with ncurses apps that try to draw menus:
![image](https://user-images.githubusercontent.com/2203386/62832771-25cca280-bc34-11e9-90ba-0ee87f794399.png)

It happens with those special characters that draw borders, corners, etc....

**Comment by farosch** [comment]
As for your initial request, mRemoteNG could have been causing your issues, as we somewhat mess around with the windows handling - glad a fresh installation solved this for you.

But your other problems can't be caused by mRemoteNG, as we completely rely on PuTTY for ssh sessions.
IMHO this is caused by wrong character setting either on the server or the client side. see https://serverfault.com/questions/475925/how-to-fix-putty-showing-garbled-characters for example. You can Ctrl+right click in your ssh session in mRemoteNG to access the setting for your current session, or you can change the default settings through the settings menu.

**Comment by wockerman** [comment]
> As for your initial request, mRemoteNG could have been causing your issues, as we somewhat mess around with the windows handling - glad a fresh installation solved this for you.
> 
> But your other problems can't be caused by mRemoteNG, as we completely rely on PuTTY for ssh sessions. IMHO this is caused by wrong character setting either on the server or the client side. see https://serverfault.com/questions/475925/how-to-fix-putty-showing-garbled-characters for example. You can Ctrl+right click in your ssh session in mRemoteNG to access the setting for your current session, or you can change the default settings through the settings menu.

The bad "corner/linedrawing" characters were solved on my system by enabling in the PuttyNG Reconfiguration, Window -> Translation -> Enable VT100 linedrawing even in UTF-8 mode.
