### ISSUE TITLE
problem remote using local account 

### ISSUE THREAD

**Issue by longtth** [mRemoteNG/mRemoteNG#1292]
My remote-server is in the same domain with my client PC, I want to remote using server's local administrator account but it doesn't work. 
Error image if needed: https://i.imgur.com/MTqvtBF.png
## Expected Behavior

If input to Username `.\administrator`, using the _local_ administrator account to login, instead of using `domain\.\administrator` (as in image) 

## Current Behavior

mRemoteNG auto concat the domain and the `.\administrator` to `domain\.\administrator` so it failed to remote. 

## Possible Solution

check whether the Username field is `.\` or not, if yes, remote using the local account instead of domain account

## Steps to Reproduce (for bugs)

1. get 1 server and 1 client in same domain 
2. input in Username field the `.\administrator` 
3. do remoting 

## Context

I can't remote using the local account 

## Your Environment

* Version used:  1.76.11
* Operating System and version (e.g. Windows 10 1709 x64):Windows 10 1709 x64

**Comment by sparerd** [comment]
Do you have the following setting set to something other than `None`? My guess is that this is where the domain value is coming from.

![image](https://user-images.githubusercontent.com/6999446/51922990-b259f680-23af-11e9-8a4c-f5cdb60fa89f.png)

You can also try the following for that connection:
- Set the username field to `administrator`
- Set the domain field to `.`

This should ensure that the domain is set to the local machine.

You are correct that we don't currently parse the username field for domain info.

**Comment by longtth** [comment]
@sparerd : Sorry for late reply, 
I've set in Options/Credentials like this: 
```
username: my-company-username
password: ***** 
domain: my.company.com 
```
in Connection/Config/Connection I set: 
```
Hostname/IP: 1.2.3.4
Username: Administrator //this is my server's local account
Password: **** 
Domain: . 
```
`Domain = . ` failed, `Domain = <blank>` failed too.

**Comment by longtth** [comment]
Sorry for late reply, 
Today I've got a new server, 
retry with @sparerd 's guide, now it works, 
The old server still failed :( 
Here is the screenshot. [Imgur](https://i.imgur.com/OG1dinN.png)
Issue close.

**Comment by pablo-padua** [comment]
I have the same issue, It is getting the current logged windows user as domain and whenever I want to connect to that specific server I have to click once and wait for it to fail and then click more choices and manually input just "administrator, it will fail once because domain is "C:myCurrentUser/administrator" instead of just "administrator".

my settings are :

Hostname/IP : 1.2.3.4
Username    : Administrator //this is my server's local account
Password    : **** 
Domain      :  . or <blank>

**Comment by simonai1254** [comment]
First of all: what version are you working with? 

Then: Please try to use the server hostname as domain, this should make the trick for the saved connections. It's a bit of a hassle to get your connections set up properly, but it should work better than using the "." in the domain name.

**Comment by pablo-padua** [comment]
> First of all: what version are you working with?
> 
> Then: Please try to use the server hostname as domain, this should make the trick for the saved connections. It's a bit of a hassle to get your connections set up properly, but it should work better than using the "." in the domain name.

that did solve the issue, much appreciated

**Comment by Bittenichtlesen** [comment]
As stupid as its sounds, for me leaving Username and Domain empty (also set to none in credentials) worked
![image](https://github.com/user-attachments/assets/6b813575-9dfd-43db-850e-012e60004ff4)
