### ISSUE TITLE
New window open Bug

### ISSUE THREAD

**Issue by Treemax** [mRemoteNG/mRemoteNG#1306]
Hi, i'm using the mRemoteNG Portable Edition (Version 1.76.11.40592) and have a problem. Everytime i open a new "window", than it opend will be open on the top left side (Screenshot). If i wana try to focus a window in the middle at the focus symbol, it takes my window again on the top left side. Maybe one of you can help me to fix this bug. 

![screenshot_window](https://user-images.githubusercontent.com/47565294/52641006-2f20c080-2ed8-11e9-9fa3-69c0d1216b48.PNG)

PS: i already tried to set back the layout config and removed the whole folder with the program.

**Comment by farosch** [comment]
This is related to either the MagicLib library or the Components check window.
The first is not part of mrng anymore and the latter was completely rewritten.
So in the next major release of mrng this will be fixed.
If you do not want to wait for that long you might want to check out our latest prerelease build
