### ISSUE TITLE
Move CHANGELOG.TXT to CHANGELOG.md

### ISSUE THREAD

**Issue by benwa** [mRemoteNG/mRemoteNG#1310]
By switching the extension-since the changelog is already using markdown formatting-when viewed in GitHub, it'll render correctly.  It would also follow other projects naming (see https://keepachangelog.com/en/1.0.0/#filename).

## Expected Behavior
A nice looking GitHub changelog page

## Current Behavior
A changelog page

## Possible Solution
Change the extension.
Following that, the changelog (and even CREDITS.TXT) could be rendered in the application with the [Markdown Parser](https://docs.microsoft.com/en-us/windows/communitytoolkit/parsers/markdownparser).

## Your Environment
* Version used: 1.76.11
* Operating System and version: Windows 10 1803 x64

**Comment by sparerd** [comment]
Makes sense, i have no issue with this. Nice to see we are (for the most part) following changelog best practices.

Our issue grouping could maybe be better (we order entries within a section by github issue #, descending).

**Comment by benwa** [comment]
I think I'll submit a PR while reformatting the whole changelog so it's consistent

**Comment by farosch** [comment]
Isn't this the same file being shown on the about page inside mrng?

**Comment by kmscode** [comment]
Yes, this will have a negative impact on the about page... But I wouldn't be opposed to removing the release notes from the about page and/or using something like [pandoc](https://github.com/jgm/pandoc) to pretty up the release notes on the about page in an html format (or, back to plain text if necessary).

That would require a build time job since pandoc doesn't have a viable/current c# interface. This isn't really a big deal other than likely a minor delay in AppVeyor build times.

**Comment by benwa** [comment]
Couldn't it be rendered with [Markdown Parser](https://docs.microsoft.com/en-us/windows/communitytoolkit/parsers/markdownparser)?  It doesn't even technically have to be rendered at first, since it's still a plain text file.

**Comment by auchri** [comment]
Or we remove the changelog from the about page and just place a link to the changelog file on github there.

**Comment by sparerd** [comment]
I would be in favor of displaying the page via a markdown parser. I would definitely still like to distribute the changelog with the app.

**Comment by benwa** [comment]
I did about a third of the restructure last night, so it's coming along

**Comment by benwa** [comment]
![image](https://user-images.githubusercontent.com/1351571/52895958-fb1ef700-3186-11e9-9f00-64405acb09ec.png)
Here's what it'll look like without a parser.  I took some very light liberties in reformatting the structure to be as consistent as possible so if we want to in the future, it can be parsed out programmatically.
That Markdown Parser I posted earlier is for UWP, but [Commonmark.NET](https://github.com/Knagis/CommonMark.NET) should work.  I just need to learn how to actually use it (remember, I haven't really programmed since high school).

**Comment by benwa** [comment]
https://github.com/mRemoteNG/mRemoteNG/tree/markdown

**Comment by nmat** [comment]
whats the status with this?

**Comment by benwa** [comment]
Sorry about the MIA status, life has left me with very little time for these projects, even though it's pretty small. I don't know if I'll be able to commit this any time soon, but it is a fairly simple change someone else could take over.
