### ISSUE TITLE
winbox as in new tab

### ISSUE THREAD

**Issue by homi88** [mRemoteNG/mRemoteNG#1311]
Winbox 3.18         mRemoteNG 1.76.11.40592       Windows 10 Pro 10.0.17763.316

Winbox as a new window in the program will not show up after login. Only a gray screen remains.
I would like to correctly open the winbox in the program window and go to use Winbox.

Screen after successful login to Mikrotik
![image](https://user-images.githubusercontent.com/47633974/52790474-efd4aa00-3066-11e9-81f4-628713113048.png)

The window opens as a separate Winbox application.

**Comment by farosch** [comment]
Duplicate of #895
