### ISSUE TITLE
Move properties window

### ISSUE THREAD

**Issue by auchri** [mRemoteNG/mRemoteNG#1312]
If you have many connections in the connections tree, the properties panel at the bottom of the connection tree takes away a lot of space and there are a lot of options in this panel (at least if you use RDO).

So I suggest to remove this panel and move the connection properties to a new windows, which can be opened with the context menu on each connection.
Each section of the properties panel could be a tab or something like that.

When a new connection is created, this window should be opened.

**Comment by cheesecracker** [comment]
I'm using ver 1.76 and I see that this is already possible, well, sort of.

The properties panel has a title bar called "Config".  Press and hold the mouse button on this title bar and move the mouse such that the panel moves out of the "zone" where it was.  And the panel will become a window.

**Comment by farosch** [comment]
This is already possible in the latest alpha.
