### ISSUE TITLE
Minor UI artifact in Notifications panel

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1314]
When no message is selected in the Notifications panel, the icon in the details portion is just a white background. This clashes slightly with the normal background of the panel. The icon background does change with the theme, but never matches the panel background.

![image](https://user-images.githubusercontent.com/6999446/52867747-337ef080-3107-11e9-82ea-9f0e47984719.png)  ![image](https://user-images.githubusercontent.com/6999446/52868069-f9621e80-3107-11e9-8f99-00adc42916f3.png)

## Expected Behavior
If the icon isn't displayed, there should be a seamless background.

## Current Behavior
When the icon isn't displayed, a slightly off-color square is visible.

**Comment by kmscode** [comment]
@sparerd if I recall correctly, that's a "PictureBox" which gets updated to the warning icon or whatever when a message is displayed.

The easiest solution might be to hide that element when no notifications exist. I attempted to get that fully/properly themed, but this was the best result...

But that was 4-6 weeks ago, so I don't remember any further specifics without looking into the code to jog my memory.

**Comment by sparerd** [comment]
Yea, hiding element might be the best option. It's not a big deal, I just wanted to get it documented in case someone has time to look at it. It's just a "polish" issue really.
