### ISSUE TITLE
Password entry dialog isn't fully themed

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1315]
Only certain elements of the password entry textbox is themed. This textbox appears when the user has a custom password set for their confcons file.

![image](https://user-images.githubusercontent.com/6999446/52868187-3d552380-3108-11e9-93b5-dd0e9d4b7c4c.png)

**Comment by farosch** [comment]
![image](https://user-images.githubusercontent.com/22905106/64033109-0eeee100-cb4c-11e9-81ed-d6b240f92a84.png)
Seems like this has already been fixed by now...
