### ISSUE TITLE
Code style: Place attributes on a separate line

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1319]
In the recent code cleanup, attributes were placed in-line with the code that they decorate. I propose we place attributes on a separate line before the target code that they decorate.

## Current style
```csharp
[Browsable(false)] public RootPuttySessionsNodeInfo RootRootPuttySessionsInfo { get; set; }
```

## Proposed style:
```csharp
[Browsable(false)]
public RootPuttySessionsNodeInfo RootRootPuttySessionsInfo { get; set; }
```

## Justification
Attribute adornments are not critical to the immediate understanding of the code they decorate. It is easier to pick out language keywords (public/readonly/etc) and type information when the definition of a class/property/method is at the start of a line.

In addition, placing attributes in-line with a normal code adds quite a bit of length to that line. This may cause us to add line breaks to the property/method definition that further reduces readability.

**Comment by sparerd** [comment]
RFC @kmscode @farosch @jotatsu

**Comment by farosch** [comment]
Added to the wiki:
https://github.com/mRemoteNG/mRemoteNG/wiki/Code-Style
