### ISSUE TITLE
Not able to translate to the new language

### ISSUE THREAD

**Issue by jonsbun** [mRemoteNG/mRemoteNG#1323]
Guide ["How to Help Translating mRemoteNG"](https://github.com/mRemoteNG/mRemoteNG/wiki/How%20to%20Help%20Translating%20mRemoteNG) explains how to use Zeta Resource Editor for mRemoteNG translation.

However, seems like Zeta Resource Editor not working properly on Windows 10. I got the following error when try to add main Language.resx to Zeta Resource Editor:
![image](https://user-images.githubusercontent.com/25233048/53123835-ae5e6600-3562-11e9-89e5-8a21ba7b9e02.png)

@nmat confirms the same issue from his side.

**Comment by nmat** [comment]
It is a bit hard to get started with how to help with translations I have to admit. Maybe this can be improved in some way. The above error seems to be coming from Zeta Resource Editor but in anyway....it is hard to understand how to get started with translations.

**Comment by farosch** [comment]
@jonsbun The wiki entry on [How to Help Translating mRemoteNG](https://github.com/mRemoteNG/mRemoteNG/wiki/How%20to%20Help%20Translating%20mRemoteNG) has been updated. Furthermore I just made a little gif to demonstrate the use of Zeta:
![2019-03-10_11-04-03](https://user-images.githubusercontent.com/22905106/54083633-5d9e8980-4326-11e9-9d09-62dc3c5cc3b5.gif)
