### ISSUE TITLE
Cannot uninstall/update mRemote NG : Windows Installer can't find "slfa5msk.msi"

### ISSUE THREAD

**Issue by turnleftatorion** [mRemoteNG/mRemoteNG#1324]
![20190221_mremoteng-01-install_new_version_1_76_11_40592](https://user-images.githubusercontent.com/47852444/53165370-d5ed1700-35d2-11e9-8aaa-559e0f316b5c.png)
![20190221_mremoteng-02-install_new_version_1_76_11_40592-error_trying_to_uninstall_older_version](https://user-images.githubusercontent.com/47852444/53165371-d5ed1700-35d2-11e9-8a72-dfc34093eb1e.png)
![20190221_mremoteng-03-install_new_version_1_76-error_trying_to_uninstall_older_version-click_ok](https://user-images.githubusercontent.com/47852444/53165372-d685ad80-35d2-11e9-94e7-8e59800ed43a.png)
![20190221_mremoteng-04-install_new_version_1_76-error_trying_to_uninstall_older_version-click_cancel](https://user-images.githubusercontent.com/47852444/53165373-d685ad80-35d2-11e9-8299-14962819528f.png)
![20190221_mremoteng-05-install_new_version_1_76-error_trying_to_uninstall_older_version-rolling_back](https://user-images.githubusercontent.com/47852444/53165374-d685ad80-35d2-11e9-9bc6-8c402710feec.png)
![20190221_mremoteng-06-uninstall_though_windows_control_panel-01](https://user-images.githubusercontent.com/47852444/53165376-d685ad80-35d2-11e9-829f-4339d49d0844.png)
![20190221_mremoteng-07-version_information](https://user-images.githubusercontent.com/47852444/53165377-d685ad80-35d2-11e9-9bd8-ab1e552a8ec8.png)

When trying to uninstall/update mRemote NG, we get a Windows Installer which says "can't find "slfa5msk.msi" in the folder "C:\Users\username\AppData\Local\Temp"   "

## Expected Behavior
The file "slfa5msk.msi" should be in the folder "C:\Users\username\AppData\Local\Temp" I don't understand why it's not.
Or there should be other way to uninstall mRemoteNG like a "uninstall.exe" file in the installation path "C:\Program Files (x86)\mRemoteNG\" or a readme file to explain how to uninstall mRemoteNG manually.

## Current Behavior
Windows box with the message : 
"The feature you are trying to use is on a network resource that is unavailable"
"Click OK to try again, or enter an alternate path to a folder containing the installation package 'slfa5msk.msi' in the box below."

"Use source : C:\Users\juliens\AppData\Local\Temp\"

## Possible Solution
Not find yet.

## Steps to Reproduce (for bugs)
Try to uninstall mRemoteNG.
Update a new version of mRemoteNG-Installer.msi (like for example : "mRemoteNG-Installer-1.76.11.40527.msi"), then run the setup.

## Context
This issue might be related to the use of CCleaner application (freeware for files cleaning, registry cleaning, programs deleting, etc).

## Your Environment
Windows 8.1 Professionnal version x64
8 Gb Ram
Intel Core i5-5200U CPU @ 2.20 GHz
* Version used:
* version :
mRemoteNG 1.75.7012.16814

**Comment by sparerd** [comment]
You can try reinstalling/repairing the old version (1.75.7012) and then try to uninstall it, though I don't have great confidence that it will work.

In the mean time, I will create a wiki page for doing a manual uninstall.

**Comment by sparerd** [comment]
Added a wiki entry for manual installation: https://github.com/mRemoteNG/mRemoteNG/wiki/Installing#manual-uninstallation

**Comment by farosch** [comment]
Same as #1130. More info [here](https://support.venafi.com/hc/en-us/articles/215911917-Error-Uninstall-an-MSI-and-msiexec-fails-asking-for-path-of-old-MSI).
@turnleftatorion Feel free to reopen this if you need further support!
Closing as this is not directly related to mRemoteNG.

**Comment by turnleftatorion** [comment]
Hello David, hello Faryan,

I've tried all the methods you've been telling me and it finally worked but
unfortunately, *none of them you were telling me was working....*
I think the best one should be that you kept older./archived versions of
old mRemoteNG on your server, so we could still download them and we would
just have then to right-click and choose "uninstall", then everything would
be fine finally...


---------- Forwarded message ---------

**Comment by sparerd** [comment]
>I think the best one should be that you kept older./archived versions of old mRemoteNG on your server

Older versions (going back to v1.72) can always be downloaded here: https://github.com/mRemoteNG/mRemoteNG/releases. Or https://github.com/mRemoteNG/mRemoteNG -> click the Code tab -> click the Releases button near the top-middle of the page
