### ISSUE TITLE
Language resource files cleanup

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1325]
Language resource files need to be cleaned up to make it easier to work with.
 - Less entries to translate
 - Code more readable

We should:
 - generalize
 - unify
 - remove unused
 - remove duplicate
 - remove _str_-prefix

**Comment by sparerd** [comment]
I don't think prepending the translation strings with `str` is useful. We already know it's a string and it takes up space.

**Comment by farosch** [comment]
Added it to the list.

Also nouns before verbs would be nice.
So this:
`strConnectionOpen`
`strCoseConnection`
would become this:
`ConnectionOpen`
`ConnectionClose`

**Comment by sparerd** [comment]
Yea, that seems sensible
