### ISSUE TITLE
Icon of connected session "Rename" context menu item difficult to see in dark themes

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1331]
It is difficult to see the icon of the connected session "Rename" context menu item.

![image](https://user-images.githubusercontent.com/6999446/53577208-ddfd0780-3b3a-11e9-8e1f-3c0654e0aa06.png)

*The theme in the screenshot is vs2015Dark*

## Possible Solution
Use an icon that has both light and dark outlining to ensure it can be seen in both light and dark themes.

**Comment by farosch** [comment]
This icon will replace the old one: ![Rename](https://user-images.githubusercontent.com/22905106/54084251-c7bb2c80-432e-11e9-8cec-6d2164c8759b.png)

**Comment by sparerd** [comment]
I'll replace the icon today

**Comment by farosch** [comment]
Fixed with 5a226ff
