### ISSUE TITLE
Exception after close mRemoteNG

### ISSUE THREAD

**Issue by konpl** [mRemoteNG/mRemoteNG#1337]
## Expected Behavior

Successful close.

## Current Behavior

I am build mRemoteNG from Visual Studio 2017 and after close mRemoteNG window IDE catch exception:
```
System.Runtime.InteropServices.SEHException:
   в mRemoteNG.App.NativeMethods.CloseHandle(IntPtr handle)
   в mRemoteNG.Tools.SystemMenu.ReleaseHandle() в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\Tools\Tools.SystemMenu.cs:строка 63
   в mRemoteNG.Tools.SystemMenu.Dispose(Boolean disposing) в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\Tools\Tools.SystemMenu.cs:строка 91
   в mRemoteNG.Tools.SystemMenu.Dispose() в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\Tools\Tools.SystemMenu.cs:строка 82
   в mRemoteNG.UI.Menu.ScreenSelectionSystemMenu.Dispose(Boolean disposing) в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\UI\Menu\ScreenSelectionSystemMenu.cs:строка 64
   в mRemoteNG.UI.Menu.ScreenSelectionSystemMenu.Dispose() в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\UI\Menu\ScreenSelectionSystemMenu.cs:строка 69
   в mRemoteNG.UI.Forms.FrmMain.Dispose(Boolean disposing) в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\UI\Forms\FrmMain.Designer.cs:строка 18
   в System.Windows.Forms.Form.WmClose(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m) в C:\Users\Trifonov\Source\Repos\mRemoteNG\mRemoteV1\UI\Forms\FrmMain.cs:строка 558
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Possible Solution

Perhaps for destroy SystemMenu a DestroyMenu function should be used instead.
See [StackOverflow](https://stackoverflow.com/questions/2003700/cleaning-up-after-calling-getsystemmenu) and [DestroyMenu doc](https://docs.microsoft.com/ru-ru/windows/desktop/api/winuser/nf-winuser-destroymenu).

## Steps to Reproduce (for bugs)

1. Start mRemoteNG build (I try release and release portable) from Visual Studio.
2. Close mRemoteNG window.
3. Visual Studio catch exception.

It happens only in develop branch. SystemMenu.ReleaseHandle() is never executed in master and 1.76 Release (try to set breakpoint).

## Environment

Version used: Latest develop branch.
Operating System and version: Windows 10 1607 x64.

**Comment by kmscode** [comment]
I've also encountered this, but didn't have a chance to review it further. Only seems to have started happening semi-recently.

**Comment by konpl** [comment]
It started after commit a512465d0774fed339a6f1ce0137996c041c0e20. This commit add the following code in frmMain.Designer.cs:
`_screenSystemMenu.Dispose();` After this `SystemMenu.ReleaseHandle()` function starts execution with Exception (As I see it wasn't invoked before). I changed `ReleaseHandle()` to `DestroyMenu()` and everything looks OK.

**Comment by farosch** [comment]
@konpl could you submit a pull request for this?

**Comment by farosch** [comment]
This method in `Tools.SystemMenu.cs` must have been responsible for this exception:

	protected override void Dispose(bool disposing)
	{
		if (disposed) return;
		if (!disposing) return;

		ReleaseHandle();

		disposed = true;
	}

Removed the negation from the second if statement and the error is gone.
