### ISSUE TITLE
Application terminates when connecting to RDP session

### ISSUE THREAD

**Issue by MatsAnd** [mRemoteNG/mRemoteNG#1343]
mRemoteNG crashes when connecting to RDP session. There is nothing logged in the mRemoteNG.log-file, but the following messages appears in Windows event viewer:
> Application: mRemoteNG.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: exception code e06d7363, exception address 77634C22

> Loggnavn:      Application
> Kilde:         Application Error
> Dato:          11.03.2019 12:56:43
> Hendelses-ID:  1000
> Oppgavekategori:(100)
> Nivå:          Feil
> Nøkkelord:     Klassisk
> Bruker:        I/T
> Datamaskin:    VFK-2YQ85S2.login.top.no
> Beskrivelse:
> Programnavn med feil: mRemoteNG.exe, versjon: 1.76.15.31277, tidsangivelse: 0x5c83f65e
> Modulnavn med feil: KERNELBASE.dll, versjon: 10.0.18342.1, tidsangivelse: 0x43a77f85
> Unntakskode: 0xe06d7363
> Feilforskyvning: 0x00114c22
> Feil prosess-ID: 0x2350
> Feil starttid for program: 0x01d4d8017a41c532
> Feil programbane: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
> Feil modulbane: C:\WINDOWS\System32\KERNELBASE.dll
> Rapport-ID: 70450255-19f1-493c-97bf-5bbc3c2acaac

## Expected Behavior
Connecting to RDP should work without the application crashing...

## Current Behavior
When clicking on a connection, the application is immediately closed.

## Your Environment
* Version used: 1.76.15.31277
* Operating System: Windows 10 Enterprise 1903 (Insider build 18342.8)

**Comment by nmat** [comment]
looks like you are using some insider version of windows 10?

**Comment by MatsAnd** [comment]
That's correct, but shouldn't it just work? I mean, what happens when Windows 10 1903 is released for everybody?

**Comment by sparerd** [comment]
@MatsAnd Are there any crash dumps available? https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging#crash-information

Does this happen immediately on the first RDP session you attempt to open, or does it work for a few connections than crashes?

**Comment by MatsAnd** [comment]
It now seems like it doesn't happen all the time, but when it first happens it won't stop for a while (reboot doesn't seem to work either). There is nothing logged in the logfile, but there was a couple of crash dumps, I uploaded the last one for you to check out:

[mRemoteNG.exe.dmp.zip](https://github.com/mRemoteNG/mRemoteNG/files/2953935/mRemoteNG.exe.dmp.zip)

**Comment by kmscode** [comment]
> 
> 
> That's correct, but shouldn't it just work? I mean, what happens when Windows 10 1903 is released for everybody?

Ideally the problem will be gone by the time the final 1903 build rolls around... Microsoft has release "broken" insider builds that had poor experiences with mRemoteNG in the past... Reference #337, #339, and #1058.

We will do due diligence on our end, but unless we find a smoking gun in our code, it's unlilkey that we'll be able to confirm and fix anything until after the final 1903 is released should the problem still occur.

And it's not like MS only releases broken insider builds these days... Not that I had any problems with 1809 (and still don't) but that was a debacle and a half from the tech media coverage of it... :wink:

**Comment by nmat** [comment]
@MatsAnd since the 1903 is nearing release I was wondering if you have had this problem occurring more now or is it not occurring in 1903 anymore?

**Comment by jaoord** [comment]
Hi, this problem is happening to me as well. I'm on 1903 and it started after I updated to 1903. 
I'm on version 1.77.0.41252 but it also happened on the current stable version (1.76).

**Comment by jaoord** [comment]
@sparerd I have done some further testing and it appears to happen on my PC when I have mremoteng opened on my second screen that is connected via a usb/c dock. When the second screen is connected over hdmi or when working from my laptop screen only, the application does not crash upon connecting.

**Comment by anhlqn** [comment]
Windows: Windows 10 1803
mRemoteNG: v1.76.20 and v1.77.0.41252

mRemoteNG started crashing randomly for me with stable version 1.76.20, so I decided to give the prerelease a try. Still crashing, but not often. It usually crashes when I have a few opening RDP connections and try to connect to another one.

I'll enable debug log and post additional information later.

**Comment by sparerd** [comment]
It may be worth trying an `sfc /scannow` to verify that your system files are still healthy. https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

**Comment by arampon** [comment]
@sparerd Hello, I work for DisplayLink, the technology in most of the USB docking station @jaoord referred to, and another end user reached out to me. I believe there could have been a change in Windows around RDP and the Indirect Display Interface API which was rolled out in v1903/19H1. That could be why your application terminates when _docked_ whilst the inbox RDP client works.

**Comment by arampon** [comment]
A workaround is to change the 3D settings in GPU (or Windows 10) to use the integrated graphics instead of discrete. Impact is likely to only be dual-GPU/hybrid machines.
A new build of Windows 10 will fix that issue.

**Comment by jaoord** [comment]
> A workaround is to change the 3D settings in GPU (or Windows 10) to use the integrated graphics instead of discrete. Impact is likely to only be dual-GPU/hybrid machines.

Can confirm this works. Thank you @arampon !

**Comment by sparerd** [comment]
@arampon Thanks for the context and work around!

**Comment by arampon** [comment]
The OS fix has been rolled out to Windows 10 Insiders build 18932 (20H1 - v2003).
I'd welcome external confirmation it solves it for you too before we can ask for a fix in a monthly patch for Windows 10 v1903.

**Comment by arampon** [comment]
Microsoft approved the fix for multi-GPU machines for deployment to Windows 10 v1903 (19H1).
It is currently tracking to be an optional update starting rolling out on Tuesday 27th August (overall OS patch, not just that) and then pushed to all machines as part of the Tuesday 10th September cumulative patch and newer.

Optional updates are manually installed by going to Settings > Updates & Security > Windows Update, and clicking on "Check for updates".
No driver change necessary.

**Comment by janis-veinbergs** [comment]
Huh, mRemoteNG crashed today with same/similar error (fault offset almost the same) and I'm on October 2019 Win updates. Giving heads up here may help gather clues if any other experiences this. Btw I do have 2x GPU's (built-in and dedicated) and multi-monitor setup.

Crashed after returning to work after 3 days and trying to open new RDP connection. I remember having this king of crash a week ago or so after long inactivity and then trying to initiate RDP connection.

```
Faulting application name: mRemoteNG.exe, version: 1.77.1.27654, time stamp: 0x5d6d3391
Faulting module name: KERNELBASE.dll, version: 10.0.18362.418, time stamp: 0x2b181c2c
Exception code: 0xe06d7363
Fault offset: 0x00113572
Faulting process id: 0x2764
Faulting application start time: 0x01d5825682e22c69
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b4347003-5108-4988-b82e-ba479e44bb37
Faulting package full name: 
Faulting package-relative application ID: 
```
and
```
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e06d7363, exception address 77283572
```

**Comment by Sender88** [comment]
Mremoteng crashed my rx480,  I was playing WoW 2 days and on the second day just crashed with greenscreen unable to run at all I had to replace my gpu

**Comment by Kvarkas** [comment]
Green screen of death (gsod) is an error due to a critical glitch in the Windows operating system, it's usually related to hardware malfunction, its just a coincident its happened then you use mR
