### ISSUE TITLE
freature request: Show host name when RDP suddenly disconnects

### ISSUE THREAD

**Issue by bbloksma** [mRemoteNG/mRemoteNG#1345]
When a RDP sessie suddenly disconnects it is not allways obvious which connection has been lost

## Current Behavior

 
When a RDP connection is lost all I get is is a warning tab with: (Dutch) 

----------
WarningMsg
03/13/2019 08:02:10
RDP disconnected!
516 Er kan geen verbinding met de externe computer worden gemaakt vanwege een van deze redenen:

1. Externe toegang tot de server is niet ingeschakeld
2. De externe computer staat niet aan
3. De externe computer is niet in het netwerk beschikbaar

Zorg ervoor dat de externe computer aanstaat en met het netwerk verbonden is, en dat externe toegang is ingeschakeld.

----------
Because I have mRemoteNG set for English and this warning is in Dutch I assume this is a default warning from the Windows RDP client and not from mRemoteNG itself.

## Possible Solution

Because mRemoteNG can open a "Notifications" tab with this warning I assume it is able to detect the failing RDP session. It would be nice it if also reported which session was lost. 

## Context

When I have only a few sessions open it is usually obvious which session I lost. When I have 5 to 10 sessions open it is a lot harder. Not all open sessions have to do with the same issue I am working on, I might be working on 2 or 3 issues at the same time. It would be nice if the warning was appended by mRemoteNG with the name of the session I lost.

## Your Environment

Running mRemoteNG 1.76.11 on Windows 10 (1803) and Windows 7 (Dutch)

**Comment by sparerd** [comment]
The work for this has been done under #929 and will be available in the first v1.77 alpha
