### ISSUE TITLE
Can't save RDP gateway credential (SQL server)

### ISSUE THREAD

**Issue by lastuptodate** [mRemoteNG/mRemoteNG#1347]
Since 1.76.15.31277, I can't save RDP gateway credential.

## Steps to Reproduce (for bugs)
1. Create a new RDP connection and fill all information (IP, user, password AND gateway IP, alternate username ans password)
2. Right-click and connect (That's OK)
3. Close mRemoteNG and re-open
4.Gateway user have been changed to: duISUz8kFs8Epa36zg9o/YtJnfjs5kU7ungs6trsHCjS1abjbHbxxlu4RNrtI3zp
![Capture](https://user-images.githubusercontent.com/7996346/54291407-ce56d780-45ac-11e9-945f-82d2dc359f3d.PNG)

## Context
It was working well in v1.76.11

## Your Environment

* Version used: mRemonteNG 1.76.15.31277
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1809 x64
* SQLServer 2008R2

**Comment by sparerd** [comment]
I will look into this right away

**Comment by sparerd** [comment]
Found the issue. I will be releasing a fix for this tonight

**Comment by sparerd** [comment]
v1.76.16 will be available shortly. Please update to this version. Unfortunately, you will need to set your gateway username fields again.

Thank you for reporting this issue and sorry for the disruption it may have caused
