### ISSUE TITLE
All folders are expanded

### ISSUE THREAD

**Issue by wickedave** [mRemoteNG/mRemoteNG#1348]
I'm saving all my connections in an SQL database and since the last update, all my folders in the "connections" view are expended. I looked in the database and the value in "Expanded" column for all the items in the database is set to 0. It means that it should open with everything collapsed but it's not the case.

Like I said, this feature was working as expected before the release 1.76.15.31277. Is it possible to fix it for a later release?

I'm working on Windows 10 1803 x64 and the database is hosted on MS SQL.

Thanks

**Comment by sparerd** [comment]
Some connection properties (whether a folder was expanded, which connections were active when mremoteng last closed) are now saved to the local machine (`%AppDataRoaming%\mRemoteNG\LocalConnectionProperties.xml`) rather than to the database.

Is there something in your environment that would prevent this file from being available between executions of mRemoteNG?

**Comment by sparerd** [comment]
I should also mention, if you are using the portable version, the local connection properties file is saved to the same directory as mRemoteNG.exe. The installed version of mRemoteNG saves the file to app data roaming

**Comment by wickedave** [comment]
Thanks for the information. The database is in read-only in my case so since the save is not working in the database, it not reaching the step to save this file. I modified it manually and it is now good.

**Comment by sparerd** [comment]
It should try to update the local connection properties first, before trying to save to the DB. Is there anything in the [log file](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) that might explain things? 

I haven't tried setting the database itself in read-only mode when testing this, so it could definitely be a bug.

**Comment by wickedave** [comment]
I'm sorry about this, it was my mistake. I just realized that there is now an option to be connected in read-only in database options. I granted myself as read-only directly on the DB before. With the option checked, everything is working as expected. Thanks for your patience.

**Comment by sparerd** [comment]
No problem! I'm actually going to open a new issue to track this (#1354), I would expect that we should still be able to save local connection properties if the db user only has read access. You shouldn't *need* to set the mRemoteNG option for this to work correctly.
