### ISSUE TITLE
Mouse pointer disappeared in SQL Server management studio

### ISSUE THREAD

**Issue by ajaychary** [mRemoteNG/mRemoteNG#1350]
i am unable to se the mouse pointer when connecting to SSMS. but i can see if i do RDP locallyt. by using remoteNG i cant.

**Comment by sparerd** [comment]
This is likely the same issue as #532. This will likely be solved by the HiDPI fixes we implemented in v1.77

**Comment by farosch** [comment]
Duplicate of #532
