### ISSUE TITLE
SQL not loading passwords

### ISSUE THREAD

**Issue by LawsMJ** [mRemoteNG/mRemoteNG#1352]
Reinstalled mRemoteNG. Reconnected to sql server.

All the Connections are visible but none of the password are retrieved. Other users working as expected. 

I have to re-enter passwords for all connections, then they are saved. 

## Your Environment
Windows 10. 
SQL Server 2014
mRemoteNG 1.75.7012.16814

**Comment by nmat** [comment]
looks like you are using a old version of mremoteng. Can you please try to use a later version and see if the problem occurs there also?

**Comment by LawsMJ** [comment]
Hi that looks better. Thanks
