### ISSUE TITLE
Panels are drawing red poly lines after changing theme

### ISSUE THREAD

**Issue by 3f0102fd9d3862ea** [mRemoteNG/mRemoteNG#1360]
## Expected Behavior
Red poly lines do not show. Window frames, panels should render without underlying wire frames.

## Current Behavior
Changing a theme to vs 2003 initiated some kind of rendering bug that causes the panel titles and frames to have red wire frame/poly lines shown.

## Steps to Reproduce (for bugs)

1. Click Tools
2. Options
3. Theme
4. Select vs2003
5. Click 'Continue' on the unhandled exception popup (seperate issue)

## Context

![tempsnip](https://user-images.githubusercontent.com/48727958/54623444-7f3ff500-4a39-11e9-9160-3518730b05a0.png)

## Your Environment
Windows 10

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by kmscode** [comment]
There were a lot of theming fixes/changes in the dev branch - this should be resolved in 1.77 - an alpha build should be available in the near future...
