### ISSUE TITLE
Update PuTTYNG to 0.71

### ISSUE THREAD

**Issue by JongleurNin** [mRemoteNG/mRemoteNG#1362]
mRemoteNG currently includes PuTTYNG v0.70, which has known security vulnerabilities.

## Expected Behavior
A new mRemoteNG release should be issued that bundles PuTTYNG v0.71. [PuTTYNG repo](https://github.com/mRemoteNG/PuTTYNG) to v0.71

## Current Behavior
mRemoteNG includes PuTTYNG v0.70, which has known security vulnerabilities that are documented at https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html.

## Possible Solution
It looks like the separate repo for PuTTYNG is already in the process of being updated, per https://github.com/mRemoteNG/PuTTYNG/commit/31890b846d0e50f6c89b7ee4f68a33bda01ef48a. So the developers already appear to be aware of this, it just hasn't been reported as an issue yet.

## Steps to Reproduce (for bugs)
1. Install mRemoteNG 1.76.16.41771.
2. Browse to C:\Program Files (x86)\mRemoteNG.
3. View properties of `PuTTYNG.exe` and verify that the version is 0.70.

## Context
Users want to ensure that they are not using tools with known security vulnerabilities.

## Your Environment
Windows 10

**Comment by kmscode** [comment]
Work has already been completed to merge 0.71 into puttyng. Testing has not yet been completed.

Build is available here if you want to test:
https://ci.appveyor.com/project/mremoteng/puttyng-77pmq/builds/23130281/artifacts


This will be included in 1.77 and we will discuss another 1.76 release.

**Comment by JongleurNin** [comment]
Thanks for the quick comment! I patched PuTTYNG.exe and verified that the version has been incremented, and that the code is signed by the developer. I also verified that I could SSH into a few Linux machines from Windows with this patch applied.

**Comment by nmat** [comment]
Getting some scaling problems inside mremoteng after this update..text is cut on the sides.

**Comment by sparerd** [comment]
@nmat  Within all mRemoteNG or just ssh sessions?

**Comment by nmat** [comment]
Only SSH it seems.

Tested with CentOS and Ubuntu and all of them scale out of the tabbed area

**Comment by nmat** [comment]
for example on ubuntu top and left side is cut by 1 character

**Comment by sparerd** [comment]
Hmm I thought we had fixed that. I'll take a look

**Comment by kmscode** [comment]
@sparerd we fixed that in 1.77... I'll find the code and backport to 1.76. PuTTYNG already has the necessary changes, so I think that's why we're seeing issues in 1.76 - I only tested 0.71 with 1.77.

**Comment by sparerd** [comment]
Ahh yea that's why... 😢

**Comment by sparerd** [comment]
I'll create a new issue for this

**Comment by sparerd** [comment]
@nmat @kmscode #1365 created

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty (CVEs).

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
