### ISSUE TITLE
Installer: Disk usage dialog shows string in header

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1363]
![image](https://user-images.githubusercontent.com/22905106/54645333-ec847200-4a9b-11e9-83dd-267cb89d9f70.png)

## Your Environment

* Version used: 1.76.16
* Operating System and version: Windows 10 1809 x64

**Comment by kmscode** [comment]
@sparerd - the entire app is less than 90 megs installed. If our target audience doesn't have that free, they have bigger problems. I say we just remove that dialog and simplify the installer...

**Comment by sparerd** [comment]
I'll look into removing it, though it might be *more* complicated to remove it than to just ignore it due to how default MSI installers work.
