### ISSUE TITLE
PuTTY window not centered after 0.71 update

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1365]
When connecting with putty after updating to v1.76.17, text on the left and top of the putty window is cut off by about 1 character.

## Possible Solution
Backport existing fix from the `develop` branch.

## Your Environment

* Version used: v1.76.17

**Comment by Davicitoo16** [comment]
Having the same issue, what's the solution?

**Comment by RafaMilow** [comment]
Same problem here.

**Comment by krayvyn** [comment]
Same here.

**Comment by sparerd** [comment]
Putty changed how they defined their window border width. We need to make a code change to handle the borders correctly. We will have a new build out shortly with the fix.

**Comment by sparerd** [comment]
v1.76.18 has been released which resolves this issue: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.18

**Comment by kmscode** [comment]
> 
> 
> Putty changed how they defined their window border width. We need to make a code change to handle the borders correctly. We will have a new build out shortly with the fix.

Actually @jotatsu and I did that to fix #1265 (among other related bugs)...
