### ISSUE TITLE
PuttyNG 0.71 - displays garbled text

### ISSUE THREAD

**Issue by pedroeloy** [mRemoteNG/mRemoteNG#1367]
## Expected Behavior
PuttyNG Should display text correctly.

## Current Behavior
Displays garbled text, with what seems to be the window icon on the start of some lines!
![Screenshot_263](https://user-images.githubusercontent.com/33546209/54773541-b82ac600-4c01-11e9-8409-59f11dd76ac4.png)

## Possible Solution
No ideia, previous version 0.70 works fine on the same computerwith the same putty settings.

## Steps to Reproduce (for bugs)

1. Open PuttyNG directly and ssh to a server.

## Context
Directly opening puttyng and connecting to ssh server.

## Your Environment
Windows 10 1703 x64
Display/Monitor scale as 125%

**Comment by kmscode** [comment]
The icon is a new addition to PuTTY 0.71 (upstream):
![image](https://user-images.githubusercontent.com/16654335/54775731-ef3eae80-4be4-11e9-9dcf-76a35d9ae6a4.png)

Please test with the standard PuTTY release to confirm the the other issues also happen in the upsteam build:
https://www.chiark.greenend.org.uk/~sgtatham/putty/releases/0.71.html

**Comment by tsargh** [comment]
Not a bug, it seems, but rather a new feature:

https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-auth-prompt-spoofing.html

(Definitely upstream, at any rate.)

**Comment by pedroeloy** [comment]
Thank you for the information.

Searched for a bug regarding Putty and an icon, and found nothing, only to learn now that it's not a bug a feature!! :)

PS: Looks awful, hope they change its appearence.
