### ISSUE TITLE
[Feature request] - Syntax highlighting

### ISSUE THREAD

**Issue by havalo-lolawo** [mRemoteNG/mRemoteNG#1369]
Is it possible to get syntax highlighting like it is available in MobaXTerm - it would be very handy to when parsing through files?

**Comment by nmat** [comment]
Could you explain this a bit more please?

I do not understand what would be a place for syntax highlight? Since mRemoteNG is using putty for the connection then you can change the color profile in there..

**Comment by havalo-lolawo** [comment]
For example, when reviewing log files, MobaXterm, RoyalTS and SecureCRT has the ability to add regex that highlights error in red or word that contains 'running, started or true' in greed. A bit like when viewing python file in vim... Hope this makes sense.

**Comment by nmat** [comment]
this has more to do with the application of which you use to view files.

As I mentioned before it has to do with syntax highlight in vim and for example putty.

**Comment by nmat** [comment]
its not mremoteng's "work load" to do syntax highlighting in that way.

**Comment by havalo-lolawo** [comment]
Backend of mRemoteNG is putty, likewise with RoyalTS and, RDM from Devolutions and MobaXterm. It is based on coloring on keywords, maybe I am not making sense :) hopefully links below will.

https://forum.devolutions.net/topic27430-solved-ssh-connection-syntax-highlighting.aspx

![image](https://user-images.githubusercontent.com/42204122/54984083-01826900-4fa6-11e9-8ded-4e0f372be4f6.png)

**Comment by nmat** [comment]
ok so lets explain this a bit more....

securecrt - is a terminal application for remote connections
mobaxterm - same
putty - same

mremoteng - USES putty to render. So therefore its putty that does the rendering of colors.

You can test it easily with downloading putty and just start it to a terminal. And see how it acts. All mremoteng is doing is to use the settings and more that putty has to render the colors. mremoteng does not do coloring more then the interface of mremoteng itself.

Therefore its up to putty to render the colors.

**Comment by nmat** [comment]
IF mremoteng was using its own terminal rendering then it would be different but it does not.

**Comment by havalo-lolawo** [comment]
I understand that, but what I am asking is will the feature that allows mRemoteNG to highlight keywords or colouring because it is the application that's doing the colour highlighting and not Putty?

**Comment by nmat** [comment]
The application does not do any form of highlighting. Its putty and the shell that does.

In that case putty would have to add the feature for the highlight. You can probably do highlight using the shell also but mremoteng does not do anything with the rendering of text in the shell.

**Comment by nmat** [comment]
In that case it would have to be a feature request to putty core team to fix highlighting. Since mremoteng can't manipulate that in anyway AFAIK.

**Comment by havalo-lolawo** [comment]
Thanks :) and nothing in the pipeline for mremoteng to render or manipulate the text in the shell?

I'll message Putty team to see what they say :)

**Comment by nmat** [comment]
AFAIK no. Because it would mean to develop its own terminal for connecting to remote sites. So not from what I know.

**Comment by havalo-lolawo** [comment]
Cool cool - thank you for you time and patience 🥇
