### ISSUE TITLE
Windows Authentication for SQL Connection

### ISSUE THREAD

**Issue by alexmcgeek** [mRemoteNG/mRemoteNG#1370]
Windows Authentication for SQL Connection

Currently, the connection to SQL server is via SQL account authentication; using Windows authentication makes assigning multiple users to allow access to the database quicker and easier to manage.

I'm currently managing the connection via just having two accounts, one SQL account with ReadOnly permissions, and one with Write, to control who is able to update the connections.

**Comment by JasonEverling** [comment]
Windows Authentication works, just leave the username/password field empty and it will use it.
