### ISSUE TITLE
Redirect Key Combinations as standard

### ISSUE THREAD

**Issue by Noiden** [mRemoteNG/mRemoteNG#1373]
## Expected Behavior
It had been nice to have "Redirect Key Combinations" as standard on connections that you don't have saved. Like a "Global option".

## Current Behavior
On connections I save I can add this but not on "quick connections".

## Your Environment
* Version used: 1.74.6023.15437
* Operating System and version: Windows 10 1709 x64

Thanks.

**Comment by sparerd** [comment]
I think this is undocumented, but setting default connection properties also applies to quick connections.

1. Click the Connections root node
1. Click the Default Connection Properties button
![image](https://user-images.githubusercontent.com/6999446/54922695-b0577400-4ed6-11e9-9d4c-5412ef2232a6.png)
1. Set `Redirect Key Combinations` to yes
1. New quick connections should now redirect key combinations

**Comment by Noiden** [comment]
Aah.. There it was, thank you very much.
