### ISSUE TITLE
Vertical Scroll Bar missing after 1.76.18 update

### ISSUE THREAD

**Issue by wrightt** [mRemoteNG/mRemoteNG#1374]
I ran the 1.76.18 update this morning, restarted and now the right scroll bar is missing from open terminal sessions.  I've searched for answers, resolutions without success.  I've insured that the 'display scroll in full screen' is enabled in the default settings. Please advise as this is a very often used tool/option. Thank you!

**Comment by PetruGr** [comment]
Hi 
I have the same problem, after installing the  1.76.18 version, the vertical scroll bar disappeared. 
From menus, or Options, there is not possibility to enable it. 

Please help to solve this problem.

**Comment by raminderis** [comment]
Experienced the exact same issue, I also upgraded to 1.76.18 and now no vertical scroll bar for me. Awaiting for a fix kindly.

**Comment by kmscode** [comment]
confirmed that this happens in puttyng 0.71 and not in 0.70 - didn't test 0.70.0.1 yet (a version that was in the dev branch for a bit before 0.71 was released upstream).

Will review further... No ETA.

**Comment by wrightt** [comment]
@kmscode, I am using Putty 0.70, not .71 and have the issue..  Thank you for working this issue.

**Comment by arodmond** [comment]
Experienced the same issue.
I upgraded to 1.76.18 and no vertical scroll bar.
The Putty version is 0.70.
If you have a mouse with scroll button is possible to scroll the windows but I prefer the vertical scroll bar.

**Comment by dalukyanov** [comment]
Same issue. mRemoteNG 1.76.18.26260

**Comment by cvasanth2707** [comment]
>Same issue. mRemoteNG 1.76.18.26260

+1

**Comment by sparerd** [comment]
@kmscode It appears this is an issue with placing putty within mRemoteNG and not a PuTTY issue itself. Opening a connection directly via PuTTYNG 0.71 has a scrollbar as expected. We need to review the putty Resize code again

**Comment by sparerd** [comment]
Oh wait, cancel that, looks like setting the hwndparent makes the scroll bar go away when run from within mRemoteNG... Never mind

**Comment by sparerd** [comment]
I think I've found an acceptable solution. I've submitted a fix to the PuTTYNG repo for @kmscode to review and verify.

**Comment by cvasanth2707** [comment]
Vertical bar works now !

**Comment by raminderis** [comment]
how do we get the fix? is mRemoteNG planning on releasing a patch or are we expected to incorporate this manually. Any help kindly. thanks.

**Comment by kmscode** [comment]
Sorry. Forgot to post the link here...

Fixed in 1.76.19: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.19

**Comment by kimfish** [comment]
Brilliant ! Thanks for fixing.  Was driving me nuts.
