### ISSUE TITLE
无法将类型为“System.Byte[]”的对象强制转换为类型“System.IConvertible”..

### ISSUE THREAD

**Issue by TheBloodthirster** [mRemoteNG/mRemoteNG#1375]
应用程序中发生了未经处理的异常。如果单击“继续”，应用程序将忽略次错误并尝试继续。如果单击“退出”，应用程序将立即关闭。

无法将类型为“System.Byte[]”的对象强制转换为类型“System.IConvertible”..

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidCastException: 无法将类型为“System.Byte[]”的对象强制转换为类型“System.IConvertible”。
   在 System.Convert.ToInt32(Object value)
   在 mRemoteNG.App.CompatibilityChecker.FipsPolicyEnabledForServer2008AndNewer()
   在 mRemoteNG.App.CompatibilityChecker.CheckFipsPolicy(MessageCollector messageCollector)
   在 mRemoteNG.App.CompatibilityChecker.CheckCompatibility(MessageCollector messageCollector)
   在 mRemoteNG.App.Startup.InitializeProgram(MessageCollector messageCollector)
   在 mRemoteNG.UI.Forms.FrmMain.frmMain_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 mRemoteNG.UI.Forms.FrmMain.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3362.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    程序集版本:1.76.18.26309
    Win32 版本:1.76.18.26309
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/mRemoteNG.exe
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3362.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3362.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    程序集版本:2.16.0.0
    Win32 版本:2.16.0.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
mRemoteNG.resources
    程序集版本:1.76.18.26309
    Win32 版本:1.76.18.26309
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/zh-CN/mRemoteNG.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2003
    程序集版本:2.16.0.0
    Win32 版本:2.16.0.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/WeifenLuo.WinFormsUI.Docking.ThemeVS2003.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012
    程序集版本:2.16.0.0
    Win32 版本:2.16.0.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/WeifenLuo.WinFormsUI.Docking.ThemeVS2012.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2013
    程序集版本:2.16.0.0
    Win32 版本:2.16.0.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/WeifenLuo.WinFormsUI.Docking.ThemeVS2013.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    程序集版本:2.16.0.0
    Win32 版本:2.16.0.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
MagicLibrary
    程序集版本:1.7.4.0
    Win32 版本:1.7.4.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/MagicLibrary.DLL
----------------------------------------
log4net
    程序集版本:2.0.8.0
    Win32 版本:2.0.8.0
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/log4net.DLL
----------------------------------------
BouncyCastle.Crypto
    程序集版本:1.8.1.0
    Win32 版本:1.8.15362.1
    基本代码:file:///E:/tool/mRemoteNG-Portable-1.76.18.26309/BouncyCastle.Crypto.DLL
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by TheBloodthirster** [comment]
win10系统
3月27日刚刚更新为mRemoteNG-Portable-1.76.18.26309
putty正常可以使用连接服务器
求助各位如歌解决这个问题。

**Comment by kmscode** [comment]
Can you please export your `HKLM\System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy` key and attach it to this issue for further review?

Thanks.

**Comment by TheBloodthirster** [comment]
> 您可以将您的`HKLM\System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy`密钥导出并附加到此问题以供进一步审核吗？
> 
> 谢谢。

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy]
"Enabled"=hex(4):00,00,00,00,00,00,00,00,28,00,00,00,04,00,00,00,0e,00,00,00,\
  45,00,6e,00,61,00,62,00,6c,00,65,00,64,00,00,00,6a,69,6e,76,00,00,69,62

**Comment by farosch** [comment]
Closed as stale
