### ISSUE TITLE
Change domain ownership

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#138]
We need to move the mremoteng.org domain off of Riley's account.
Requirements:
- Need email support
- We will need to work with CloudFlare to ensure https works correctly with the .io site.

Setting up CloudFlare for .io:
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by benwa** [comment]
If email support is too expensive, Zoho offers up to 25 accounts free: https://www.zoho.com/mail/zohomail-pricing.html

**Comment by jumoog** [comment]
how many email accounts the team needs?

**Comment by benwa** [comment]
I'd say only one for now, but Zoho is the only free service that I could find.

**Comment by sparerd** [comment]
The only address being actively used right now is support@mremoteng.org.
And to be clear, we really only need email forwarding.

**Comment by benwa** [comment]
Both Google Domains and NameCheap losses the ability to do email forwarding when CloudFlare is used.
To get it back, you can use Mailgun (free).
https://www.chrisanthropic.com/blog/2014/mail-forwarding-with-mailgun-and-cloudflare/

**Comment by sparerd** [comment]
Going to give Google Domains a try.

Registrar: Google Domains
Https support for GH: CloudFlare
MxForwarding: Mailgun

Will get the SSL cert through the same folks that did our code signing cert.

@benwa Am I forgetting anything?

**Comment by benwa** [comment]
The cert will be given through CloudFlare, no need to use a different
signer (not even sure it's possible).

**Comment by sparerd** [comment]
Ahh gotcha - even easier

**Comment by sparerd** [comment]
Domain xfer initiated. Transfer will occur sometime between Oct. 9 and the 11th due to a mandatory waiting period by the current registrar.

**Comment by sparerd** [comment]
Domain has been transferred

**Comment by sparerd** [comment]
Cutting dns over to cloudflare is posing a challenge. Getting the following when trying to reach the forum:

![2016-10-14_1000](https://cloud.githubusercontent.com/assets/6999446/19394211/518bb9e0-91f5-11e6-99b8-57623ac68d35.png)

Had to roll back the change

**Comment by sparerd** [comment]
Double checked and reloaded the dns entries, turned off proxy for the forum, and turned on developer mode. Things seem stable - cutover worked

**Comment by sparerd** [comment]
Mail forwarding setup via Mailgun

**Comment by almusaddar** [comment]
Here is  my Stack for managing my Blog:
- Namecheap - Domain registrar
- Github - Static pages hosting
- cloudflare - DNS hosting
- mailchimp - Mail Campaign
- MailGun - Mail Forwarder
- Disqus - Manage Comments
- Google analytics - Web analytics
- Zoho - Mail hosting

**Comment by sparerd** [comment]
Site switched over with (relatively) little pain.
