### ISSUE TITLE
.NetFrame work Memory Excpetion error

### ISSUE THREAD

**Issue by Pushpendra-blr** [mRemoteNG/mRemoteNG#1381]
I have been using version 1.76.18.26260 for 3 days now, app worked fine with no issues, however today in morning when I logged into my win 10 (1809) system I got 
".NetFrame work Memory Excpetion error"

I closed and re-launched app, it did open up except few RDP sessions were lost.
 let me know if you need more information.

**Comment by kmscode** [comment]
Do you have any associated [crash information](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging#crash-information) about this? Event logs, memory dump, etc?

**Comment by Pushpendra-blr** [comment]
I did not capture anything specific logs as it was first time occurrence after installation, I am waiting for issue to reoccur so that I can collect logs and share it with you accordingly, however if this helps I had opened multiple web links at least 6 of them and at least 10 RDP sessions.

Regards,


Sent from Mail for Windows 10

**Comment by farosch** [comment]
Closing because OP has been unable to provide an example that replicates. Remaining flexible to reopen if more info is provided...
