### ISSUE TITLE
Putty Crashes in 1.76.18.26260

### ISSUE THREAD

**Issue by DougHaigh** [mRemoteNG/mRemoteNG#1392]
After upgrade install to 1.76.18.26260, starting a SSH session causes PuTTY to crash. Backporting to 1.76.16.41771 allows it to work.

## Expected Behavior

I expect it to open a PuTTY session window.

## Current Behavior

PuTTY crashes

## Possible Solution

Backport to 1.76.16.41771

## Steps to Reproduce (for bugs)

1.Install latest update
2.Start a SSH session 

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 x64 build 10.0.16299.1029

**Comment by kmscode** [comment]
Please install 1.76.19: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.19

If the crash still occurs, please provide me with the memory dump.

**Comment by DougHaigh** [comment]
Where would PuTTY leave a memory dump? 
mRemoteNG starts just fine. 

When I click on one of my connections that starts PuTTY, I get the following:
![image](https://user-images.githubusercontent.com/15949661/55643883-424a6100-57a2-11e9-8ff0-96c2d7f432de.png)

**Comment by aldago** [comment]
Check last post in https://github.com/mRemoteNG/mRemoteNG/issues/1366

**Comment by DougHaigh** [comment]
Fix from [#1366](https://github.com/mRemoteNG/mRemoteNG/issues/1366) worked for me.
