### ISSUE TITLE
Feature Request: Credentials database

### ISSUE THREAD

**Issue by rickyweb** [mRemoteNG/mRemoteNG#1398]
## Expected Behavior
I'd like to be able in Options/Credentials to save multiple user/password/domain combinations which can be retreived with a dropdown in the connection configuration.

## Current Behavior
Currently, you have the possibility to save exactly one credential if the username/password/domain is empty. Any other credential needs to be saved in the connection configuration.

## Context
The current situation is good if you use the same credentials for all machines. If you have several different logins shared on a non negligible subset of machines, then all other credentials must be saved in the configuration of each connection. As it is generally recommended to regularly change the password, one finds oneself every now and then to go through all the connection configurations and change the password, which is time consuming and daunting.

## Your Environment

* Version used: 1.76.19.35762
* Operating System and version: Windows 10 x64

**Comment by Kvarkas** [comment]
will be possible with user profiles
