### ISSUE TITLE
MSI does not install successfully from Intune

### ISSUE THREAD

**Issue by o-l-a-v** [mRemoteNG/mRemoteNG#1405]
mRemoteNG must be the only MSI I've tried to deploy with Intune MDM that does not work as expected.

1. If mRemoteNG is installed already, Intune will still try to install it again. Something tells me Intune does not manage to get correct detection rules and/ or version info, thus making the MSI not compliant to the MSI standard.
2. If deployed to a computer not containing mRemoteNG already, the install usually succeeds. 

I will try to get some logs.
- Are anyone else here experiencing the same behaviour? 
- Does it work with SCCM, or Intune Silverlight? 
- Does mRemoteNG need some special install parameters in order for it to detect and/or upgrade over existing installation successfully?

**Comment by chudovsky** [comment]
Any logs from installation process ?

**Comment by sparerd** [comment]
> Does mRemoteNG need some special install parameters in order for it to detect and/or upgrade over existing installation successfully?

No special parameters should be necessary.

However, if you have some Windows 7 machines, the install may fail if an expected KB is not installed. Passing the installer `IGNOREPREREQUISITES=1` may solve the issue (https://mremoteng.readthedocs.io/en/latest/installation/install.html#extend-installer-properties). Please note that if the machines do not have a comparable KB installed, RDP may not work. Windows 10 is exempt from this extra check.`

**Comment by farosch** [comment]
Closed due to OP not responding

**Comment by o-l-a-v** [comment]
> Closed due to OP not responding

Sorry for not responding. I started pushing it using a Win32 package instead, specifying install prerequirements, and custom detection rules. Seems to work.


> Any logs from installation process ?

If I where to try raw MSI from Intune again, where should I go to find logs?

**Comment by farosch** [comment]
> If I where to try raw MSI from Intune again, where should I go to find logs?
I wouldn't know - You're the one using intune :P I guess https://docs.microsoft.com/en-us/intune/troubleshoot-app-install would be a good start.

**Comment by o-l-a-v** [comment]
> > If I where to try raw MSI from Intune again, where should I go to find logs?
> > I wouldn't know - You're the one using intune :P I guess https://docs.microsoft.com/en-us/intune/troubleshoot-app-install would be a good start.

Could be that mRemoteNG did some custom logging. But yeah, I can look for the standard MSI logs.
