### ISSUE TITLE
Collapse all folders not saved (with SQL Server)

### ISSUE THREAD

**Issue by NislAr98** [mRemoteNG/mRemoteNG#1407]
## Expected Behavior
When using the collapse all folders function it should have the same effect as collapsing all folders manually. After restarting mRemoteNG the folders should still be collapsed.

## Current Behavior
Using the collapse all folders function only changes the view temporary. After restarting the application the folders are expanded again.

## Steps to Reproduce (for bugs)
1. Configure mRemoteNG with SQL Server
2. All folders are expanded
3. Use the collapse all folders function
4. Close and reopen mRemoteNG

## Context
Using the search function often opens a lot of folders. Currenty I have to collapse them one by one manually.

## Your Environment
- mRemoteNG v1.76.15
- Windows 10 1803

**Comment by HenningSR** [comment]
This is explained in #1354

**Comment by NislAr98** [comment]
But the Problem only occurs when using the "collapse all folders" function.
When I collapse the folders manually every works fine.
Just to

**Comment by NislAr98** [comment]
But the problem only occurs when using the "collapse all folders" function.
Collapsing the folders manually works fine and everything is saved.
Just to point it out once again :)

**Comment by farosch** [comment]
As with the closure of #1180 the `expanded` property will always be saved as a local connection property and not inside the database. This is not a bug, it's a feature.
If you think this behaviour should be reversed or want a setting to control where the `expanded` property is stored please participate in #1420
