### ISSUE TITLE
bug：密码包含特定字符时，变量%password%不准确，导致外部工具无法正常运行

### ISSUE THREAD

**Issue by Hovn** [mRemoteNG/mRemoteNG#1411]
环境：
Windows10、Windows7下的1.76.20

描述：
当连接的password存在特殊字符时，可能导致变量%password%不准确，导致外部工具无法正常运行（比如外部工具 xshell无法打开连接）。

复现：
1、新建一个连接，设置密码为：!@#QWE
2、使用外部工具（cmd.exe /k echo "%password%"）进行获取%password%的值
3、获取到的密码为：^!@#QWE
4、开头多出来一个^

截图：
![image](https://user-images.githubusercontent.com/6801952/56292362-a7fefb80-6159-11e9-876d-61974bafbdc0.png)
![image](https://user-images.githubusercontent.com/6801952/56292889-9e29c800-615a-11e9-8425-c3db3215fc98.png)

**Comment by Hovn** [comment]
![image](https://user-images.githubusercontent.com/6801952/56292889-9e29c800-615a-11e9-8425-c3db3215fc98.png)

**Comment by yderi** [comment]
Use a password variable with Exclamation mark like this: %!password%

**Comment by Hovn** [comment]
非常感谢，是一个正确的解决方法。
能问一下%password%和%!password%变量的区别吗？%password%是否已过时？

**Comment by yderi** [comment]
No %password% variable is not obsolete. When you using special symbols in a password, mRemoteNG need to treat it as part of the password.
Read this thread: https://github.com/mRemoteNG/mRemoteNG/issues/604
User kmsode wrote - citation: Between 1.72 (a very old version) and the current version meta-characters are now escaped.
I have no more information.

**Comment by sparerd** [comment]
@Hovn This page provides more information: https://mremoteng.readthedocs.io/en/latest/user_interface/external_tools.html#special-character-escaping

**Comment by Hovn** [comment]
@yderi @sparerd   Thanks very much，get it！

**Comment by e345** [comment]
然而%!password%并没有解决复杂密码登录winscp的问题，希望能够提供urlencode的编码方法，例如使用两个感叹号表示urlencode转码：%!!password%
让错误的密码： scp://root:“J4Lk:;7=0!S>>/”@172.28.3.151:22
转换为正确的： scp://root:“J4Lk%3a%3b7%3d0!S%3e%3e%2f”@172.28.3.151:22
