### ISSUE TITLE
DLL missing when updating version 1.76.20.24615

### ISSUE THREAD

**Issue by tisoportes** [mRemoteNG/mRemoteNG#1416]
DLL missing when updating version 1.76.20.24615

## Expected Behavior
Installation is aborted and appears a dialog box just report DLL is missing with the following message:
"There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or pacakge vendor."

At least setup should inform which DLL is missing to try fix it.

Windows 10 Pro  Version 1803    build 17134.706
![problem](https://user-images.githubusercontent.com/30669391/56365380-bb907d80-61be-11e9-9f10-12379e138653.jpg)

**Comment by nmat** [comment]
I can't reproduce this with a:

v1.76.19 -> v1.76.20 upgrade on windows 10 1809 (OS Build 17763.437)

Can you please provide from version to what version you tested? Or did it work after you reported the issue?

**Comment by farosch** [comment]
Some software running on your system probably deleted that dll.
You should uninstall mRemoteNG manually (https://mremoteng.readthedocs.io/en/latest/installation/uninstall.html) and re-install it afterwards.
