### ISSUE TITLE
Domain credentials are being duplicated on login prompt

### ISSUE THREAD

**Issue by 9NickWynn** [mRemoteNG/mRemoteNG#1417]
When opening a remote connection, the Credentials used previously are now duplicating the domain.
What used to be passed in as DOMAIN\User.name
now show as DOMAIN\DOMAIN\user.name

And when I re-enter them correctly, they are not being saved.   I have to fix my credentials every time I log in.  
This behavior just started in the version I downloaded last week.  (which I think is 1.76.19)

This is on Windows 10, the environment has 150 connections.  I've never had this problem until the last update.

**Comment by nmat** [comment]
Could you show what you mean with a screenshot?

**Comment by 9NickWynn** [comment]
[cid:image001.png@01D4FA99.90ED0620]

**Comment by Marschinski** [comment]
Hi,

I experience the same problem and to give an additional information:

In my company this happens on Computers having Windows 10 1809 installed. My colleagues who have 1803 installed haven't this problem while all colleagues with 1809 have.

And the duplication is not consistent. There is a mixture of domain names with the Pre-Windows 2000 one (e.g. domain) and the 'real' one (e. g. domain.lan).

So we have

domain.lan\domain.lan\user
domain.lan\domain\user
domain\domain\user
domain\domain.lan\user

Hope that helps finding a solution.

Maik

**Comment by sparerd** [comment]
Does this happen with mstsc.exe as well (using .rdp files)? Or just when using mRemoteNG?

**Comment by 9NickWynn** [comment]
Only in mRemoteNG with the latest Windows Updates.

**Comment by Marschinski** [comment]
In my case the following workaround helped:

I had a domain saved in each server configuration I wanted to connect. After I deleted it my connection procedure worked like a charm and I had no longer the domain information doubled.

I guess there are some changes Microsoft provided in newer Windows 10 versions while getting domain and/or user information.

**Comment by ner00** [comment]
This even happened with the standard Windows client. It would take the existing last known username (including domain name) and re-append the domain name when specified in the RDP file. Removing it from the RDP file solved it. In some cases having the old DOMAIN\USER works better.

**Comment by 9NickWynn** [comment]
Adding the domain credentials to the server resolved the issue.
