### ISSUE TITLE
AD Imported connections cannot be modified

### ISSUE THREAD

**Issue by zakkojo** [mRemoteNG/mRemoteNG#1418]
After importing connections from AD the configuration TAB down't give me chance to change parameters other than name, description  and hostname.

## Expected Behavior
I would expect that imported connections would be editable as the created ones

## Current Behavior
Only few configurations parameters appears (name,description, hostaname)

## Steps to Reproduce (for bugs)
1. import connections from a specified OU in AD
2. changed grouping and order of the connections
3. tried to modify configuration of any of the imported connection

## Your Environment
Version used: 1.76.19 (2019-04-12)
Operating System: Windows 10 1709 x64

**Comment by Trueinsanity** [comment]
i also had this issue, but after connecting the first time i was able to edit everything like normal

**Comment by farosch** [comment]
@zakkojo Imported connections from AD have inheritance enabled by default.
You can take a look at how inheritance works [here](https://mremoteng.readthedocs.io/en/latest/folders_and_inheritance.html).
