### ISSUE TITLE
PropertyChanged event triggered twice

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#142]
|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.75 pre-alpha |

The `ConnectionTreeWindow.HandleCollectionPropertyChanged` event handler is being called twice for all ConnectionInfo property changes. This is a minor inefficiency but should still be investigated.

**Comment by kmscode** [comment]
@sparerd Check this out:
https://sourceforge.net/p/objectlistview/bugs/108/#817a
https://sourceforge.net/p/objectlistview/bugs/136/


Looks like there were some similar problems where things were being called twice in the upstream code. Might be worth opening a ticket with the author...

**Comment by jotatsu** [comment]
I double checked this one, its no longer present on develop branch as of ObjectListView 2.9.1. Please close
