### ISSUE TITLE
REGRESSION: Property "Expanded" no longer loaded from the database

### ISSUE THREAD

**Issue by HenningSR** [mRemoteNG/mRemoteNG#1420]
We have recently upgraded mRemoteNG Portable to version 1.76.18 from 1.72.

We run a setup where all users have read-only access to the SQL database, with the files in %ProgramFiles(x86)%\mRemoteNG read-only as well.

I can understand that the expand state of the tree was moved to LocalConnectionProperties.xml in #1180 

## Expected Behavior
The "Expanded" property should be deployable from the database.

## Current Behavior
The expand state of the tree is unique for each user and/or is not controllable from the database.

## Possible Solutions
I see several possible solution options:
1. Make it an option: Are settings global only or local for some? - or a setting option that makes more sense in this case (under SQL Server?)
2. Initialize all local settings with a default value configurable from the database
   * This way we can remove the local xml-file and remove write access and thus we have the same behavior as before where the setting is not configurable for the normal user, and is propagated from the database
3. Save "local" settings per user in the database in e.g. a new table
4. Make a database setting, which resets the local settings to the default

## Steps to Reproduce
1. Create a database with folders, subfolders and RDP connections
2. Create a db-user with read-only access
3. Configure mRemoteNG to load from the database with the user with read-only access
4. The property "Expanded" is not loaded from the database

## Context
We want all users to have the same folders expanded when the app is started, and we would like to configure this globally in the database. This was possible in 1.72

We use an admin-user when we make technical changes to servers and thus need to change the tree/connections.

## Your Environment

* Version used: 1.76.18.26309 portable
* Operating System and version:
   * Windows 10 (mainly 1803 (17134) and 1809 (17763))
   * Windows Server: 2016 (1607), 2012 R0 and 2008 R2

**Comment by sparerd** [comment]
I will take this under consideration, though I'm curious why you want to dictate the expansion state of folders to users. Is this to save them time, or more of an issue with the app trying to write in a read-only location?

**Comment by farosch** [comment]
Closed due to OP not answering and this being a silly request, for reasons sparerd commented above. Most people would wan't the exact oppsite to be true.
