### ISSUE TITLE
Editing the display name causes the connection hostname to be replaced by the display name

### ISSUE THREAD

**Issue by sahirns** [mRemoteNG/mRemoteNG#1421]
Editing the display name causes the connection hostname to be replaced by the display name

## Expected Behavior
Editing display name should not change the connection hostname/ipaddress 

## Current Behavior
Editing display name replaces the connection hostname/ipaddress with the new display name 

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
In Config panel, edit the display name of an existing connection
the connection hostname/ip gets filled with the new display name 

## Context
for almost a year - but it has annoyed me enough now to report as a bug

## Your Environment

* Version used: all versions, including the current 1.76.20 
* Operating System and version : Windows 10 x64 all versions including 1809

**Comment by farosch** [comment]
That's probably not a bug but a feature. Please make sure to uncheck this option:
![image](https://user-images.githubusercontent.com/22905106/56849734-960b1e80-68f8-11e9-9b24-7da294d3dd34.png)

**Comment by sahirns** [comment]
Gotcha. Thanks
