### ISSUE TITLE
connection panels missing after update

### ISSUE THREAD

**Issue by babelone** [mRemoteNG/mRemoteNG#1425]
I unzipped the Prerelease mRemoteNG-Portable-1.77.0.41307.zip and copied
extapps.xml
mremoteng.settings
pnllayout.xml
from the old version.
mRemote_Verbindungen_confCons.xml is located in a different document folder.

then I opend the new prerelease version and all connections which were opened before are started again as it always did.

But this time the defined PANELS which group my connections are not shown.
Instead all connection are opened separately side by side.

see screenshot attached
![2019-04-30 12_23_30-mRemoteNG - mRemote_Verbindungen_confCons xml - DCNG PROXY](https://user-images.githubusercontent.com/50138318/56955861-d1992900-6b42-11e9-9ee8-ee7bc50cda83.png)

## Environment
* Version used: 1.77.0.41307
* Operating System and version  Windows 10 Enterprise 1709 x64 Build 16299.1087

**Comment by sparerd** [comment]
@babelone Just to confirm, do some of the connections shown have a different `Panel` defined? If they all have the same `Panel` and the setting `Always show panel tabs` is not enabled, then a panel tab will not be shown if it is the only panel open.

**Comment by babelone** [comment]
yes, there should be 5 open panels.
see the screenshot taken from the last stable version

![2019-04-30 16_06_39-mRemoteNG - mRemote_Verbindungen_confCons xml - GAW PROXY](https://user-images.githubusercontent.com/50138318/56967684-fcdf4080-6b61-11e9-9509-db62fe4d505f.png)

**Comment by sparerd** [comment]
Panels show up correctly for me in 1.77.0 when manually opening connections. I'll try the auto-reconnect too.
![image](https://user-images.githubusercontent.com/6999446/56968592-1021ea00-6b29-11e9-8c10-fcf58c1d677d.png)

**Comment by sparerd** [comment]
Ok, I've been able to recreate the issue. For some reason only panels with "General" in the text are showing up. I'll look into it

**Comment by cinquestl** [comment]
I found that whatever connection you open first creating a panel will have all connections under that panel. Even when closing every connection and every panel while still in the app, it will still set the next connection into the same panel name as before. Completely closing out and ending the program then starting fresh will allow the first connection once again to be in the correct panel. But back to everything else in that panel as well. I confirmed all my panel names are set in each connection as well as in the panel config.

**Comment by sparerd** [comment]
I think I found the issue. I'm testing a fix right now.

**Comment by sparerd** [comment]
I think I've fixed this now. Check the next 1.77 alpha release for the fix

**Comment by kal10bach** [comment]
same issue with me - is there a new alpha 2 come with the fix? thx, georg
