### ISSUE TITLE
MR-975 - Replace TreeView with TreeListview for displaying ConnectionTree

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#143]
Replace the current TreeView object being used to display the ConnectionTree with TreeListView. This will greatly reduce coupling between UI and domain logic.

http://objectlistview.sourceforge.net/cs/recipes.html#how-do-i-use-a-treelistview

**Comment by sparerd** [comment]
Merged back into develop. Issue complete
