### ISSUE TITLE
Feature Request: Import MobaXterm connections

### ISSUE THREAD

**Issue by Paul-Richter** [mRemoteNG/mRemoteNG#1431]
## Expected Behavior
Request for ability to import MobaXterm saved connections file.
File > Import > Import from file... > MobaXterm
Add ability to choose MobaXterm.ini saved connections file.

## Current Behavior
Current behavior does not allow import from a MobaXterm saved connections file.

## Possible Solution
Include MobaXterm as a connection file import option 

## Steps to Reproduce (for bugs)
N/A

## Context
I wanted to migrate all my connections to mRemoteNG from MobaXterm, but since the option is not available, I have to manually enter over 60+ connections.

## Your Environment

* Version used: 1.76.20
* Operating System and version: Windows 10 1709 x64

**Comment by sparerd** [comment]
We can definitely look into this. Can't promise when we will get to it though. Might be a good project for new community developers.

**Comment by Paul-Richter** [comment]
I agree. I have no idea where to start, but if anyone would like my thoughts on this or would like me to test, please let me know.

**Comment by cyrus104** [comment]
I am really looking to move to mRemoteNG and wanted to see if there was any status on this. I have around 100 sessions that I need to move.

Thanks

**Comment by maprado-inetum** [comment]
Hello. What happened with this? I offer to test any implementation ideas. 
Thanks.

**Comment by Tabarane** [comment]
I'm with this feature, would be AMAZING and migrating to mRemoteNG will be alot easier , i use Mobxterm for last 5 years and i have more than 100+ sessions, and i really want to migrate fully but this is nightmare to manually move all session

**Comment by xBounceIT** [comment]
Im forking the project to work on it!

Im quite naive with the whole development process, but i'll keep you posted.

**Comment by Kvarkas** [comment]
the best way will be you you create a mapping file - what filed in mR should be receiving a data from what field in MobaXterm... then we could easy add into import section.

**Comment by xBounceIT** [comment]
Thanks.

If you could give me a quick overview on which files should be the one i need to work on we could speed up the process.

As i said im quite naive, and after forking and cloning into visual studio 2022 (which led to a lot of errors) i managed to recompile the app, execute it and verify the presence of a small change i made in the localization for test.

Im currently looking and working on the mRemoteNG/App/Import.cs file because it seems the one to be responsible for all the import functions, but feel free to guide me.

**Comment by JustBeta** [comment]
If you are interested, I have developed a PowerShell script to perform this conversion.
It may not be perfect, but it allowed me to convert 245 MobaXterm sessions to mRemoteNG.

Here is the link to download it: 
https://github.com/JustBeta/Export-MobaXtern2mRemoteNG/tree/main

**Comment by Kvarkas** [comment]
thanks a lot, will add into add-ons list, done! https://github.com/mRemoteNG/mRemoteNG/tree/v1.77.3-dev/Add-ons

**Comment by Paul-Richter** [comment]
Thank you so much for everyone that has contributed! Great work.
