### ISSUE TITLE
Connection tree sorting Ascending and Descending

### ISSUE THREAD

**Issue by nmat** [mRemoteNG/mRemoteNG#1434]
**Version:** 1.77 prerelease
**OS:** Windows 10 1809 (OS Build 17763.437)

When clicking on icon for sorting Ascending there is no way to go back to Descending sorting.

Suggestion is to have the icon change based on value.

1 click - Sort ascending
next click - Back to descending

**Comment by Titus-s** [comment]
If it's possible please limit it to current node. 
With one click I've destroy my order set from a long time, without possibility to undo.

**Comment by farosch** [comment]
@Titus-s If you want to apply sorting to only one node right click on that node and use the soting function there:
![image](https://user-images.githubusercontent.com/22905106/59880231-d2b13e80-93ac-11e9-8010-ab9bdd0be577.png)
