### ISSUE TITLE
Copy & Paste stopped working with latest version

### ISSUE THREAD

**Issue by bhicks-usa** [mRemoteNG/mRemoteNG#1435]
Running mremoteng v1.77.0.41307 and I cannot copy a local file and paste it across to an RDP session. To test this I unzipped a clean mRemoteNG-Portable-1.76.0.24669.zip, used my confCons.xml and I was able to successfully copy & paste files to the remote machine. I unzipped mRemoteNG-Portable-1.77.0.41307.zip over-top the 1.76 directory, connected to the same machine and copy & pasting files no longer works.

**Comment by nmat** [comment]
Do you have the clipboard shared?

in 1.77 there is a RDP option for shared clipboard did you try that?

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/57033468-45275d00-6c4d-11e9-8681-ef40863a6cba.png)

**Comment by bhicks-usa** [comment]
> Do you have the clipboard shared?
> 
> in 1.77 there is a RDP option for shared clipboard did you try that?

Yep, that was the issue here. Thanks. Since this option defaults to No I would need to set it to Yes at a high level then go through hundreds of connections to set inheritance to Yes as well. That's rough.

**Comment by lguimaraes10** [comment]
I am having the same problem, where I find this option, I am not finding in mRemote settings.

**Comment by oznxzar** [comment]
I had tried to change it massively in "confCons.xml" andt it works perfect just replace RedirectClipboard="false" with RedirectClipboard="true".

**Comment by muehterc** [comment]
> I had tried to change it massively in "confCons.xml" and it works perfect just replace RedirectClipboard="false" with RedirectClipboard="true".

worked like a charm, thank you so much!!

**Comment by karlochacon** [comment]
> I had tried to change it massively in "confCons.xml" andt it works perfect just replace RedirectClipboard="false" with RedirectClipboard="true".

cool I was after this

**Comment by barbosstech** [comment]
> I had tried to change it massively in "confCons.xml" andt it works perfect just replace RedirectClipboard="false" with RedirectClipboard="true".

Worked perfectly to me! Thanks.

**Comment by karlochacon** [comment]
don't know why does not work for me :|

**Comment by barbosstech** [comment]
> don't know why does not work for me :|

You must edit your main xml file and change for every line the sintax to RedirectClipboard="false" with RedirectClipboard="true".

![image](https://user-images.githubusercontent.com/69665244/113802168-9b05b900-9730-11eb-9b32-d78f161d1705.png)

**Comment by maestroat** [comment]
Hi, i have Version: 1.76.20.24615

i have no Clipboard in Menue on other as disk, printer .....  and i have no entry in my confcons.xml with redirectclipboard.

what can i do? thanks

**Comment by barbosstech** [comment]
> Hi, i have Version: 1.76.20.24615
> 
> i have no Clipboard in Menue on other as disk, printer ..... and i have no entry in my confcons.xml with redirectclipboard.
> 
> what can i do? thanks

You must select the root folder of your connections and then go to View -> Config. The clipboard option will be at the end of the list under "Redirect" options...

**Comment by maestroat** [comment]
Connection
 - folder 1 DomainController
	server 1
	server 2
 - Folder 2 Servers
	server 1
	server 2 

under Connection under Folders under server

only:
Redirect
Key Combinatoin
Disk Drivers
Printers
Ports
Smart Cards
Sounds


there is no Clipboard :(

**Comment by MaximvanMaanen** [comment]
> Connection
> 
> * folder 1 DomainController
>   server 1
>   server 2
> * Folder 2 Servers
>   server 1
>   server 2
> 
> under Connection under Folders under server
> 
> only:
> Redirect
> Key Combinatoin
> Disk Drivers
> Printers
> Ports
> Smart Cards
> Sounds
> 
> there is no Clipboard :(

Hello,

I had the same issue as you. the Clipboard is only available in version 1.77.0 (and newer). You'll want to download the Prerelease v1.77.0 from Mon, Apr 29, 2019 from [here](https://mremoteng.org/download).
