### ISSUE TITLE
Help file update for SQL table script update for portable 1.77.0.41307

### ISSUE THREAD

**Issue by ng3727** [mRemoteNG/mRemoteNG#1436]
When selecting the SQL Server Experimental Option via the Tools / Options the Sql script currently in the help file needs updating to include two fields; RedirectAudioCapture, InheritRedirectAudioCapture

If you already have the table created quick fix
alter table [mRemoteNG].[dbo].[tblCons] add [RedirectAudioCapture] [bit] NOT NULL DEFAULT 0
alter table [mRemoteNG].[dbo].[tblCons] add [InheritRedirectAudioCapture] [bit] NOT NULL DEFAULT 0

## Expected Behavior

Closes the screen without an error being produced.

## Current Behavior

Clicking Tools / Options then selecting SQL Server (mssql)
Add if not already done the SQL server connection info, click test.  This works.  But if the table is missing a field and you click Ok/Apply the screen the application will try to read from the table with an expected field list which then produces an error as the fields do not exist.

## Possible Solution

Amend the help file(s) 
mRemoteNG/Help/MSSQLScript.txt 
mRemoteNG/Help/MySQLScript.txt
or
alter table [mRemoteNG].[dbo].[tblCons] add [RedirectAudioCapture] [bit] NOT NULL DEFAULT 0
alter table [mRemoteNG].[dbo].[tblCons] add [InheritRedirectAudioCapture] [bit] NOT NULL DEFAULT 0
[MSSQLScript - update.txt](https://github.com/mRemoteNG/mRemoteNG/files/3145974/MSSQLScript.-.update.txt)
[MySQLScript - update.txt](https://github.com/mRemoteNG/mRemoteNG/files/3145990/MySQLScript.-.update.txt)

## Steps to Reproduce (for bugs)

1. Tools / Options
2. SQL Server
3. Set Connection Details, test connection (successful) mssql
4. Click Ok/Apply
Based on the user having previously created the table(s) via the script in the helpfile or using the files currently in the development source, which is slightly out of date

## Context

Minor issue, easily fixed
(would be nice if you can specify the sql port to connect on e.g. docker install can redirect the port or MSSQL or MySQL)

## Your Environment

* Version used: mRemoteNG Version: 1.77.0.41307 (portable)
* Operating System and version (e.g. Windows 10 1709 x64):
OS: Microsoft Windows NT 10.0.17763.0
Windows 10 Home 1809 17763.475

**Comment by src386** [comment]
Thank you @ng3727 I had the same issue.

The MS SQL script in the documentation: https://mremoteng.readthedocs.io/en/latest/sql_configuration.html explicitly forbids NULL values in `InheritRedirectAudioCapture` and `RedirectAudioCapture` but the first thing mRemoteNG does is trying to insert NULL entries... 

The documentation needs an update.

**Comment by farosch** [comment]
Thank for the Update @src386 
I'll update the documentation asap

**Comment by protocolist** [comment]
Any update on this? I encountered this problem today when setting up an MS SQL instance for mremoteng and came across this issue.
