### ISSUE TITLE
REGRESSION: Searching in hosts tree loses first keystroke

### ISSUE THREAD

**Issue by bluikko** [mRemoteNG/mRemoteNG#1439]
In 1.77.0.41252 a new bug appears: typing more than one letter on keyboard to search the hosts tree "loses" the first keystroke after more keystrokes are input.

## Expected Behavior
- Start with focus on a PuTTY window
- Move focus to hosts tree
- Press keys "h", "o", "s", "t"
- All four letters appear in the search bar as "host"
- Focus in hosts tree is moved to first match of search string "host"

## Current Behavior
- Start with focus on a PuTTY window
- Move focus to hosts tree
- Press key "h"
- Focus in hosts tree is moved to first match of "h"
- Continue to press keys "o", "s", "t"
- Only the subsequent three letters appear in the search bar "ost"
- Focus in hosts tree is moved to first match of search string "ost", if one exists

## Possible Solution
- ?

## Steps to Reproduce (for bugs)
Follow the "Current Behavior" steps.

## Context
In earlier releases all keystrokes were captured in the search bar correctly, including the first keystroke.

## Your Environment
* Version used: 1.77.0.41252
* Operating System and version: Windows 10 1803 x64

**Comment by sparerd** [comment]
Thanks for reporting this @bluikko. The fix will be in the next alpha release
