### ISSUE TITLE
Exporting connections in RemoteDesktop2008 format error

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#144]
Function CsvConnectionsSerializerRemoteDesktop2008Format.SerializeConnectionInfo still has a reference to connectionInfo.TreeNode which was deprecated in this update.

Need to find a new way of serializing in this format that does not use the TreeNode property.

**Comment by kmscode** [comment]
I say we just remove the ability to export to a format that is 8 years old and likely not well supported by current versions at this point...

So long as mRmoteNG XML and CSV options still work...

**Comment by sparerd** [comment]
Yea, that may be what we have to do. Not even sure the program is readily available anymore.

**Comment by sparerd** [comment]
visionapp Remote Desktop 2008 is not available anymore. Was bought by ASG who no longer provides earlier app versions.
