### ISSUE TITLE
Panel Tabs

### ISSUE THREAD

**Issue by TaraLT14** [mRemoteNG/mRemoteNG#1440]
Connections do not open under the Panel indicated in the conifg

## Expected Behavior
I have assigned each connection a Panel based on OS version ie: 2012 R2, 2016. When I open a connection it should open under the panel as specified in the config. When I click on the panel Tab 2008 R2 all my 2008R2 servers should be there.

## Current Behavior
The first connection opens a panel with the panel name specified in the config but all other connections open under the first panel even thought the Panel specified in the config is something different

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):  
Windows 2010 Pro version 1803 build 17134.648

**Comment by sparerd** [comment]
I am assuming this is using mRemoteNG v1.77.0. This bug will be fixed in the next release. Duplicates #1425
