### ISSUE TITLE
Clipboard Copy/Paste not working in RDP connection

### ISSUE THREAD

**Issue by sohnaych** [mRemoteNG/mRemoteNG#1448]
Copy paste is not working in the latest Prerelease v1.77.0 Mon, Apr 29, 2019.

I've tried rebooting etc. but then installing the stable version fixed the copy / paste issue.

**Comment by sparerd** [comment]
Please check that the `Clipboard` property in the Redirect section is set to `true` for that connection

**Comment by dmm4WiX** [comment]
I'm having the same issue, and I don't see a Clipboard property in the Redirect section.

**Comment by sparerd** [comment]
@dmm4WiX Please check that you are on the most recent pre-release alpha version (1.77.0) and that your connection is not currently inheriting the Clipboard property from its parent folder.

**Comment by dmm4WiX** [comment]
I'm currently on the release channel ... I will test the pre-release now ...

**Comment by sparerd** [comment]
@dmm4WiX Ah yea, the Clipboard property is currently only available in the pre-release. Please be cautious when testing non-stable builds (make manual backups of your connections file). Portable builds are good for testing new versions without committing to using it long-term.

**Comment by dmm4WiX** [comment]
Thanks ... I always use virtual systems for pre-release tests ... once bitten, twice shy ...

**Comment by sohnaych** [comment]
So copy paste is broken in this release, correct?

**Comment by sohnaych** [comment]
So I found the clipboard option in the pre release and did a mass edit on the config file to set  "clipboard to true" and that fixed it and also changed the default setting to set this to true..

What does the favourite button do? It doesn't do anything when I click and also right click on a connection doesn't have an option to add to favorite.. I believe that's what the favorite button is for?

**Comment by stryker09** [comment]
does anyone have issues with KeePass AutoType? it looks like that is broken as well, even after setting the Clipboard config to True.

**Comment by sparerd** [comment]
@stryker09 You may want to open a new issue for that. It is likely a window focus issue that we will need to look into.

**Comment by stryker09** [comment]
@sparerd thanks i just did that #1450

**Comment by farosch** [comment]
@sohnaych If you want a connection to appear under the favorites drop-down you'll need to set its *Favorite* Property to True.
You will find this setting (like any other connection related setting) in the config window under *Miscellaneous*:
![image](https://user-images.githubusercontent.com/22905106/59739784-3ed55a80-9266-11e9-89a0-9a08d55f6935.png)

I will close this issue now, as sharing the clipboard seems to working fine, when set up correctly.
This is merely a misunderstanding caused by making "Redirect Clipboard" it's own property in v.1.77.

**Comment by karlochacon** [comment]
is there a way to have clipboard to true as default? Instead of enable by connection? Like global setting o make it by default in the tool for next version?

thanks a lot

**Comment by JoeBrunsTR** [comment]
1.76 clipboard works as a default.  Someone thought it was a good idea to flip that over for 1.77?  Seriously?

**Comment by BLZB0B** [comment]
maybe I'm being blind... but I can't see an option to enable / disable clipboard in 1.76.20.24615 ? (clipboard isn't working for me - I need to enable it somehow)

![image](https://user-images.githubusercontent.com/17888955/141765654-47068e74-f976-417f-ba16-091c376157f6.png)

**Comment by Kvarkas** [comment]
![image](https://user-images.githubusercontent.com/3611964/141776089-dc9ded74-f88e-44d9-adaa-a6a8d0fdc800.png)

**Comment by Kvarkas** [comment]
> is there a way to have clipboard to true as default? Instead of enable by connection? Like global setting o make it by default in the tool for next version?
> 
> thanks a lot

Yes that's in todo to add to settings tab so user can select predefaults he wish, its also mint to be part of profile implementation so perhaps will appears a bit later

**Comment by s56rsv** [comment]
If Clipboard doesn't work , in 1.76 just restart the mRemoteNG. That was my case.

**Comment by ppamills** [comment]
It might not be an mRemoteNG issue per se.
https://support.jumpdesktop.com/hc/en-us/articles/216425123-RDP-Clipboard-syncing-stops-working-occasionally

Try: 

> 1. Kill the process rdpclip.exe using the task manager **in the remote computer**
> 2. Go to RUN command and start the application rdpclip.exe

**Comment by NijoLabs** [comment]
why would you made clipboard disabled by default in build 1.77.2? i was looking everywhere for it until i found the option disabled in settings, please make it enabled by default.

**Comment by BeBa-pL** [comment]
Printer seems to work for some reason..

**Comment by Kvarkas** [comment]
check settings for inheritance

**Comment by ppamills** [comment]
I've had to restart the clipboard service in the remote system.

**Comment by dorkalord** [comment]
> It might not be an mRemoteNG issue per se. https://support.jumpdesktop.com/hc/en-us/articles/216425123-RDP-Clipboard-syncing-stops-working-occasionally
> 
> Try:
> 
> > 1. Kill the process rdpclip.exe using the task manager **in the remote computer**
> > 2. Go to RUN command and start the application rdpclip.exe

Yeah this helped with my issiue, but I had to use a different RDP client. in my case 
https://apps.microsoft.com/store/detail/microsoft-remote-desktop/9WZDNCRFJ3PS?hl=sl-si&gl=SI

Build 1.76.20 didn't include clipboard setting in the config but updating it to preview version 1.77.1, I'll still try to figure out

**Comment by bugs84** [comment]
Version 1.76.20 is here more then 2 years.
When or Will be fixed stable version released?

**Comment by duckysuck** [comment]
its now October 2022 and I need this feature :)

**Comment by cptapple** [comment]
1.77.3, nothing new as far as i see.
EDIT: Found it.

**Comment by Kvarkas** [comment]
> check settings for inheritance

**Comment by baha2506** [comment]
Hi,

You should terminate the 'RDP Clipboard Monitor' process in Task Manager from Windows Server by navigating to the 'Users' tab. After that, press Windows + R, type rdpclip, and press Enter to restart the RDP Clipboard service.

Haseeb

**Comment by DaanSelen** [comment]
RDP'ing with clipboard redirection turned on still does not work. In the latest tagged release
