### ISSUE TITLE
REGRESSION: Cannot move host in Connections tree

### ISSUE THREAD

**Issue by bluikko** [mRemoteNG/mRemoteNG#1456]
In 1.77.0.41252 there is a regression: hosts cannot be moved in the "Connections" tree like before. It worked really nicely before and it is a shame to lose this functionality that highlighted in green where the host was going to go after drag and drop.

Now a host can only be dragged into a different "folder", but the ordering of hosts inside same folder cannot be changed with drag-and-drop.

Ctrl-Down / Ctrl-Up works or choosing the same action from right-click context menu works for ordering the hosts inside a folder.
**But** additionally this one has a bug also: if first moving a host with Ctrl-Down or Ctrl-Up and then pressing Up / Down, the focus jumps from the currently selected (just moved) host to the old position of the host that was moved.
A new bug should probably be filed for this issue...

## Expected Behavior
Select a host in the "Connections" list by pressing and holding down left mouse button, keep holding down the mouse button and drag the host to another location in "Connections" tree inside the same folder and the host can be moved to a different location in the folder. I.e. ordering of hosts inside a folder.

## Current Behavior
Cursor changes to "forbidden" icon and host can only be dragged to another folder.

## Steps to Reproduce (for bugs)
See "Expected Behavior".

## Your Environment

* Version used: 1.77.0.41252
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 x64

**Comment by sparerd** [comment]
Thanks for reporting this @bluikko, looking at it now

**Comment by sparerd** [comment]
Found the issue - the fix will be in the next v1.77 alpha

**Comment by CharlieAMS** [comment]
When is alpha coming out?
