### ISSUE TITLE
Readme has non-working link for "prerequisites". Suggested alternative.

### ISSUE THREAD

**Issue by carehart** [mRemoteNG/mRemoteNG#1457]
On the readme (https://github.com/mRemoteNG/mRemoteNG), the link to "prerequisites" goes to https://github.com/mRemoteNG/mRemoteNG/wiki/Prerequisites. That page no longer exists, it seems, and it leaves a prospective new user at the Dev wiki, being told to go elsewhere for docs.

It seems that the link should instead be to the "minimum requirements" page of the docs, whic his https://mremoteng.readthedocs.io/en/latest/installation/minimum_requirements.html.

Hope that's helpful. I'm just such a first-time visitor, prospective user.

**Comment by farosch** [comment]
@carehart We overhauled the whole documentation just recently and forgot to update that link!
Thank you very much for pointing that out!
