### ISSUE TITLE
fix error in the Language.ru.resx, need to correct the word "Приминить"  to "Применить"

### ISSUE THREAD

**Issue by GjBrutello** [mRemoteNG/mRemoteNG#1458]
fix error in the last source code, folder Resources > Language.ru.resx, need to correct the word "Приминить" to "Применить" . The word "Применить" is the same like Ok, so it looks very annoying.
Version: mRemoteNG-Portable-1.77.0.6549

**Comment by GjBrutello** [comment]
fix error in the Language.ru.resx, need to correct the word "Приминить" to "Применить"

**Comment by farosch** [comment]
@GjBrutello I've changed the translation just like you proposed.

**Comment by GjBrutello** [comment]
Hellow Mate, I thought you replaced this word in the whole file. There were two mistakes of the word. Now there are still one error remained in strButtonApply = "Приминить". Need to correct to "Применить" too. And btw I found another little a mistake in the  strPropertyNameRDPMinutesToIdleTimeout = "Минуты в режим ожидания". Correctly is "Минуты в режиме ожидания". Thanks Bro.

**Comment by aokunev** [comment]
Hello - I've just found there is another instance with the typo for 'strButtonApply' in Language.ru.resx. Line 2760

...
  </data>
  <data name="strButtonApply" xml:space="preserve">
    <value>Приминить</value>
  </data>

**Comment by farosch** [comment]
@aokunev I've fixed the second typo, too.
Thx for reporting it ! :)
