### ISSUE TITLE
Windows Admin Center not usable in a http/https connection

### ISSUE THREAD

**Issue by Songxwn** [mRemoteNG/mRemoteNG#1460]
Windows Admin Center is not usable in a http/https connection.
There are rendering and probably also functional issues calling the windows admin center from within mRemoteNG with the gecko engine.
Using the IE engine a popup is shown to use a different browser.

**Comment by nmat** [comment]
Not sure what you mean here. Can you please provide more information on how to reproduce this and what you are doing?

**Comment by farosch** [comment]
This is imho caused by the version of the gecko engine we currently use in mrng.
The Windows Admin Center works perfectly in newer versions of firefox.

**Comment by farosch** [comment]
#1477 would make this possible, too

**Comment by farosch** [comment]
It kinda works in GeckoFX but not as nicely as with CefSharp
