### ISSUE TITLE
Disable Language bar inheritance

### ISSUE THREAD

**Issue by andushow** [mRemoteNG/mRemoteNG#1464]
Multiple Windows (10) clients are connecting to a Windows server(box) using mRemoteNG (1.76.19.35762). The server is configured with only 1 entry in the language bar: EN [QWERTY]. However, whenever someone with (let's say) "FR" [AZERTY] as their primary language (on the Windows client computer) is connecting to the server, that (client) language becomes the "default" on the server for future connections and it gets really annoying.
I don't know if the feature exists (i haven't found it), but it would be nice to have a setting that would prohibit language bar redirection (from client to server), much like printer/disk drives/etc.

**Comment by farosch** [comment]
See this:
https://theitbros.com/fix-a-problem-with-language-bar-in-windows-server-20082012-r2/
