### ISSUE TITLE
Favorites fails to reload when configured with SQL server 1.77

### ISSUE THREAD

**Issue by ng3727** [mRemoteNG/mRemoteNG#1470]
## Expected Behavior

Favorites are reloaded when mRemoteNG is reloaded when using SQL/MySQL connections

## Current Behavior

This feature is missing the local property reload

## Possible Solution

[mRemoteNG-develop\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\LocalConnectionPropertiesXmlSerializer.cs](https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Config/Serializers/ConnectionSerializers/MsSql/LocalConnectionPropertiesXmlSerializer.cs)

```
public IEnumerable<LocalConnectionPropertiesModel> Deserialize(string serializedData)
                  .Select(m => new XElement("Node",
                                          new XAttribute("ConnectionId", m.ConnectionId),
                                          new XAttribute("Connected", m.Connected),
                                          new XAttribute("Expanded", m.Expanded),
                                          new XAttribute("Favorite", m.Favorite) // added #1470
                                          ));
```

```
public IEnumerable<LocalConnectionPropertiesModel> Deserialize(string serializedData)
                     .Select(e => new LocalConnectionPropertiesModel
                   {
                       ConnectionId = e.Attribute("ConnectionId")?.Value,
                       Connected = bool.Parse(e.Attribute("Connected")?.Value ?? "False"),
                       Expanded = bool.Parse(e.Attribute("Expanded")?.Value ?? "False"),
                       Favorite = bool.Parse(e.Attribute("Favorite")?.Value ?? "False") // added #1470
                   });
```

## Steps to Reproduce (for bugs)

1. Load mRemoteNG, configure SQL Server settings
2. Reload mRemoteNG
3. Select a connection
4. Set Favorite to Yes
5. Unload mRemoteNG
6. Load mRemoteNG
7. No Favorite's are reloaded from the Local Settings

## Context

The feature saves and reloads using the standard XML connection but not with SQL Server configured (haven't looked at the MySQL version)

## Your Environment

* Version used: mRemoteNG Version: 1.77.0 dev @31/05/2019
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Home 1809 17763.529

**Comment by nmat** [comment]
If possible can you create a merge request to have developers look at it?

**Comment by ng7323** [comment]
> If possible can you create a merge request to have developers look at it?

Sorry I am a newbie, don't know how to do that.
