### ISSUE TITLE
Feature request: Check parent property value if property empty

### ISSUE THREAD

**Issue by tplecko** [mRemoteNG/mRemoteNG#1471]
It would be less time consuming to organize the connection file if tree items would inherit parent items properties upon creation or when left empty

## Expected Behavior
Read parent nodes properties, if properties are empty

## Current Behavior
Every folder and every connection created is always the same. If username/password must be changed on a large number of nodes, it takes a long time.

## Possible Solution
In options/Credentials, add: "For empty username/password/domain, use: None, Current windows credentials, The following values, Parent node values"
When creating a connection or folder, set all values to 'inherit'.
When double clicking the connection, when checking for settings, if 'inherit' is set, check parent node, and its parent node (until a set value is found)
Connection file should hold default values for every connection type. That could be a new tab in Options called 'Defaults'

## Steps to Reproduce (for bugs)
Create a folder and/or connection

## Context
I had to change credentials on a large amount of connections, and while doing that, i also defined panel names for every connection

**Comment by sparerd** [comment]
I think much of this can be handle with the current inheritance and default inheritance system.

To set the default values of newly created connections, click the root connection node in the connection tree and then select one of the last two buttons in the "Config" window (default properties and default inheritance). I set most of my default inheritance properties to "true" and manage most of the settings at the folder level. When I need to change a password, I change it in one folder and the child connections and folders get the update.
![image](https://user-images.githubusercontent.com/6999446/58804952-a8a00400-85d8-11e9-9409-9fc791db92e3.png)

There is a plan to improve the default connection/inheritance system to make it more flexible (#239).

The default property/inheritance system only works for new connections. A feature for applying the inheritance values of a folder to all of its children is currently being tested for the next version v1.77 (#1451).

**Comment by tplecko** [comment]
I must apologize, I wasn't aware of this functionality.
Feel free to remove this post (mostly to cover my shame)

**Comment by sparerd** [comment]
Not a problem @tplecko. In your defense, the default property/inheritance system isn't documented very well and is somewhat buried in the UI. Many people miss it or don't fully understand what it's purpose is. Hope this has helped!
