### ISSUE TITLE
linux and android version

### ISSUE THREAD

**Issue by Banzaizaizai** [mRemoteNG/mRemoteNG#1479]
Hello.
i use this perfect RDP app in windows. 
please tell, do You have in plans version for other platform, like linux and android? 
 for now i use Remmina in linux, but mremoteNG is more power and functional application IMHO.

**Comment by sparerd** [comment]
Duplicate of #308, please follow that issue for updates. In short, we would like to but it is a massive amount of work. Without a lot of extra help, I don't see this happening any time soon. Even basic updates can take us quite a while to complete.
