### ISSUE TITLE
If credentials are saved in RDP file, mRemoteNG uses them

### ISSUE THREAD

**Issue by JRVcr** [mRemoteNG/mRemoteNG#1480]
Today I tried logging on to a server via RDS under unsaved credentials by using "Connect without credentials", and was surprised when mRemoteNG didn't prompt for credentials, but logged me in with my normal credentials.

I opened MSTSC to try logging on under alternate credentials, and discovered that I had saved my credentials in MSTSC at some point. Once I deleted them from MSTSC, mRemoteNG prompted me for credentials when I used "Connect without credentials".

## Expected Behavior
I expected mRemoteNG to prompt me for credentials.

## Current Behavior
mRemoteNG appears to use credentials saved in MSTSC, and without any warning.

## Possible Solution
I'd probably prefer that mRemoteNG ignore saved credentials in MSTSC. But I can also see that it could be useful for or maybe even expected by some. Maybe add a prompt that says "Do you want to log in with <DOMAIN\UserName> credentials saved in MSTSC?" With Yes/No buttons, and a "Do not ask me again" checkbox. And a corresponding Option, "Use MSTSC saved credentials when credentials are not specified in mRemoteNG" with option buttons Always/Prompt/Never.

## Steps to Reproduce (for bugs)
1. Save credentials for a server using MSTSC.
2. Log on to the same server via mRemoteNG where you've saved credentials, but specify "Connect without credentials".

## Context
Diagnostic: I was trying to log on to a server under alternate credentials to see if the same behavior I saw in my normal account was present with another account. In this case, was on the phone with tech support so it needlessly complicated a support call.

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1809 x64

**Comment by sparerd** [comment]
@JRVcr I've looked into this a little bit and I don't think we will be able to do what you are suggesting without some side effects.

Normally when connecting via RDP with mRemoteNG, we set the username/domain/password fields of the RDP control with the values provided in the connection record. When the RDP control sees that these fields are populated it attempts to use them. If those fields aren't populated (like when you select `Connect without credentials`), then the RDP client uses its fallback option of checking the Windows credential manager, and then finally it requests credentials from the user.

I don't believe we have any way to tell the client *not* to check the Windows credential manager. The best thing we could do is pass it bogus user/pass information to force a failed authentication (which should then trigger the credential prompt). The downside of this is that your server will now have a bogus failed login attempt from your machine in its logs. This might be just a minor issue, but it does feel very... hack-y. I don't think this would be very desirable, and definitely not intuitive for users who would see this as an option within mRemoteNG. We would definitely need to have this well documented.

Thoughts?

**Comment by JRVcr** [comment]
Not knowing the authentication flow, David, it caused a bit of panic, because it sure wasn’t behaving the way I expected. I might have noticed MSTSC’s message that it had saved creds if I wasn’t on the phone at the time on a support call.

I see your points, though, and thanks for explaining the auth flow. I figured it was going to be something like that, but didn’t know if there was a way to intervene. I agree that passing bogus credentials isn’t the right approach.

Going forward, I’ll (maybe…) remember this if I run across it again. Since it hasn’t happened before in the 3 or so years I’ve been using mRemoteNG, it’s unlikely to happen often; at least to me. Somebody with lots of stored credentials would find it more of an issue.

Thanks!
--

Jeff Vandervoort
Crescent IT Systems

**Comment by sparerd** [comment]
No problem, should we keep this issue open or would you like me to close it?

**Comment by JRVcr** [comment]
I guess close it if there’s no good solution.

Thanks!

--

Jeff Vandervoort
Crescent IT Systems

**Comment by CAT-hs** [comment]
I just wanted to comment for others that might find this thread: You can use the hacky 'use invalid creds' option David mentioned yourself if you feel like you need to just by saving bad creds to an object/connection, which will to force a password prompt but you will have a logged auth failure so be careful in monitored environments. 
Perhaps a "fix" for this could be as simple as a tool-tip text that pops up on hover over the connect without credentials option (and maybe a note in documentation) that briefly explains the conflict with saved credentials.
