### ISSUE TITLE
Language folder

### ISSUE THREAD

**Issue by thankuverymuch** [mRemoteNG/mRemoteNG#1481]
This is my favorite ssh program.
Thank you very much.
But I wish the language files were in one folder.
The folder is too complicated.

**Comment by farosch** [comment]
@thankuverymuch why should all files be in one folder? what difficulties does the current solution pose? please go into the problem in more detail.

**Comment by thankuverymuch** [comment]
Why not? 
It looks messy.
I wish the language folder was in one folder.
Readability will be better.
This is just a suggestion.
Thanks.
