### ISSUE TITLE
Gecko problem

### ISSUE THREAD

**Issue by A2Skad** [mRemoteNG/mRemoteNG#1482]
```
Сообщение исключения
"Не удается загрузить DLL "mozglue": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)"

Трассировка стека
   в Gecko.Xpcom.Alloc(IntPtr size)
   в Gecko.nsAString..ctor() в D:\temp\339b193\Geckofx-Core\nsString.cs:строка 883
   в Gecko.nsAString..ctor(String value) в D:\temp\339b193\Geckofx-Core\nsString.cs:строка 895
   в Gecko.Xpcom.Initialize(String binDirectory) в D:\temp\339b193\Geckofx-Core\Xpcom.cs:строка 324
   в mRemoteNG.UI.Window.ComponentsCheckWindow.CheckGeckoBrowser() в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:строка 722
   в mRemoteNG.UI.Window.ComponentsCheckWindow.CheckComponents() в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:строка 546
   в mRemoteNG.UI.Window.ComponentsCheckWindow.btnCheckAgain_Click(Object sender, EventArgs e) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Window\ComponentsCheckWindow.cs:строка 515
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Environment
OS: Microsoft Windows NT 10.0.18362.0
mRemoteNG Version: 1.77.0.41252
Edition: MSI
Cmd line args: 

```

**Comment by farosch** [comment]
@A2Skad What were you doing when that error occured?

**Comment by farosch** [comment]
Actually this looks like the `mozglue.dll` is missing from your install dir, most likely `C:\Program Files (x86)\mRemoteNG\Firefox`.
This file could have been deleted by accident or for example by an anti virus software.
Reinstalling mRemoteNG will fix this problem.

**Comment by jul-fls** [comment]
Hello, i've the same problem it happens that when i try to open a gecko connection nothing happens. 
I've already tried to install visual c++ redistribuables 2013, reinstalled mremoteng, updated windows, nothing works...
Here's the error log: 
`2021-09-26 01:55:11,403 [9] INFO  - Connexion terminée
2021-09-26 01:55:11,403 [9] INFO  - Connexion à 172.16.108.200 via HTTPS fermée par l'utilisateur Admin.
2021-09-26 01:57:21,098 [4] INFO  - Saving connections...
2021-09-26 01:57:21,357 [4] INFO  - Successfully saved connections
2021-09-26 01:57:23,563 [5] INFO  - Saving connections...
2021-09-26 01:57:23,758 [5] INFO  - Successfully saved connections
2021-09-26 01:57:30,449 [5] INFO  - Saving connections...
2021-09-26 01:57:30,642 [5] INFO  - Successfully saved connections
2021-09-26 01:57:42,087 [1] ERROR - Impossible de créer de nouvelles connexions HTTP !
Impossible de charger la DLL 'mozglue': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
   à Gecko.Xpcom.Alloc(IntPtr size)
   à Gecko.nsAString..ctor() dans D:\temp\2ea25a5\Geckofx-Core\nsString.cs:ligne 883
   à Gecko.nsAString..ctor(String value) dans D:\temp\2ea25a5\Geckofx-Core\nsString.cs:ligne 895
   à Gecko.Xpcom.Initialize(String binDirectory) dans D:\temp\2ea25a5\Geckofx-Core\Xpcom.cs:ligne 324
   à mRemoteNG.Connection.Protocol.Http.HTTPBase..ctor(RenderingEngine RenderingEngine) dans C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\Http\Connection.Protocol.HTTPBase.cs:ligne 28
2021-09-26 01:57:42,132 [1] ERROR - Échec de Set HTTP Props !`

Environment
OS: Microsoft Windows NT 19043.1237 21H1
mRemoteNG Version: 1.76.20.24615
Edition: MSI
Cmd line args:
