### ISSUE TITLE
Can't I increase the font size?

### ISSUE THREAD

**Issue by thankuverymuch** [mRemoteNG/mRemoteNG#1483]
I have bad eyesight.
Thank you.

**Comment by farosch** [comment]
This is not possible from within mRemoteNG.
You will have to adjust your scaling inside of Windows.

**Comment by dixi83** [comment]
Hi there, 
I don't have bad sight but I like this feature as well... in putty it is possible please check this link: https://globedrill.com/change-font-size-putty/ Since you are using putty as backend, it might not be impossible.
Thanks!
