### ISSUE TITLE
Feature request, time tracker

### ISSUE THREAD

**Issue by pavelsleis** [mRemoteNG/mRemoteNG#1485]
On end of session can be nice pop-up window with possibility to insert comment about work in the session done. The information can be later use as statement of work.

## Expected Behavior

I have experience the teamviewer has this feature and it is very usefull.
When I close the remote session there is simple pop-up window I can input notice abour work done. The notice is stored with data like: session name, time and date start /end, notice.

If I need to report my worksheet, I can export list of sessions into CSV in defined time interval.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
Closing, as this would exceed mremotengs' intended purpose by far.
mrng is a remote connections manager and nothing more.
