### ISSUE TITLE
mRemoteMG 1.76.20.24615 random crashing

### ISSUE THREAD

**Issue by kmacmillan25** [mRemoteNG/mRemoteNG#1490]
mRemoteMG 1.76.20.24615 seems to be randomly crashing for me. Usually it happens after the application has been open for a while but during the times it's happened I haven't been using the application.

The crash generated a dump file in the 
%localappdata%\CrashDumps folder.

Here's a link to the file:
https://we.tl/t-8b4cPuJH0p

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: msmpeg2vdec.dll_unloaded, version: 10.0.17763.348, time stamp: 0x3d0ae0c4
Exception code: 0xc0000005
Fault offset: 0x001ad830
Faulting process id: 0x4580
Faulting application start time: 0x01d50fe5bf9b50ac
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: msmpeg2vdec.dll
Report Id: 070c0a54-95e5-443a-a66c-3aae8c2e7be2
Faulting package full name: 
Faulting package-relative application ID: 

Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 3142D830

I'm using Windows 10 Professional x64 version 1809 (build 17763.379)

**Comment by sparerd** [comment]
@kmacmillan25 Does the log file contain any extra information about the error? (https://mremoteng.readthedocs.io/en/latest/troubleshooting.html)

**Comment by kmacmillan25** [comment]
Hello David,

No I don't see anything in the mRemoteNG.log file related to the error. I
attached this log file though.  (The error occurred yesterday June 13 at
3:48 pm and there is nothing the log file at around that time... Note that
the messages from 3:51 pm onwards are from when I restarted mRemoteNG)

There was this Windows error report in this folder though:
C:\Users\All Users\Microsoft\Windows\WER\ReportArchive\

Please see attached for the report file.

Thanks,

Kris MacMillan

**Comment by sparerd** [comment]
@kmacmillan25 Unfortunately GitHub does not pass on any file attachments when you reply via email. Would you be able to copy the related text in your reply or attach the file to this issue directly (via a web browser)?

**Comment by kmacmillan25** [comment]
Hello David,

Sure.... here are the two files I referred to in my last message...

[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/3293247/mRemoteNG.log)

[Report.zip](https://github.com/mRemoteNG/mRemoteNG/files/3293249/Report.zip)

**Comment by sparerd** [comment]
@kmacmillan25 I haven't been able to find out much about your error. There was a [similar report](https://forum.devolutions.net/topic29886-faulting-module-path-msmpegvdecdll.aspx) with a user of Devolution's remote desktop program. In that case they claimed it was a possible DirectX issue.

Since mRemoteNG doesn't directly use mpeg video for anything, it probably gets loaded by one of the connection protocols we use. It might be worth doing an `sfc /scannow` or updating graphics drivers to see if that helps.

**Comment by farosch** [comment]
Closed due to OP not responding
