### ISSUE TITLE
Help/Donate link shows 404

### ISSUE THREAD

**Issue by cinquestl** [mRemoteNG/mRemoteNG#1496]
Clicking on link does not bring up web page to donate to mRemoteNG

## Expected Behavior
Should open a browser window to donate to the cause

## Current Behavior
Displays 404 file not found

## Possible Solution
The link has a trailing slash after the word donate. If you remove the last slash, the page displays

## Steps to Reproduce (for bugs)

1.Click on Help
2.Click on donate
3.
4.

## Your Environment

* Version used: 1.77.0.41.41252
* Operating System and version (e.g. Windows 10 1709 x64): using Edge as browser

**Comment by farosch** [comment]
@cinquestl Thank you very much for noticing this!
I have pushed a fix for this to the current develop branch.
