### ISSUE TITLE
Missing Firefox folder on build 1.77

### ISSUE THREAD

**Issue by ng3727** [mRemoteNG/mRemoteNG#1502]
When building in debug portable config, the firefox folder appears to be not copied

## Expected Behavior

Help / About should work
## Current Behavior

Help / About does not load, debug text says mozglue.dll is missing.
## Possible Solution

Copy mRemoteNG\packages\Geckofx45.45.0.34\content\Firefox folder into mRemoteNG\mRemoteV1\bin\Debug Portable

## Steps to Reproduce (for bugs)

1. Load mRemoteNG
2. Goto menu Help / About
3. No message or error to user just doesn't load

## Context

Looking for the version no!!
(shouldn't there be an error message popup in this sort of situation?)

## Your Environment

Version used: mRemoteNG Version: 1.77.0 dev @27/06/2019
Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Home 1809 17763.557

**Comment by farosch** [comment]
This was caused by migrating packages.config to PackageReference.
I've reverted these commits. Thanks a lot @ng3727
