### ISSUE TITLE
RDP connection timed out

### ISSUE THREAD

**Issue by ivakinde** [mRemoteNG/mRemoteNG#1507]
Hi! Not sure if this bug already discovered, but it's pretty annoying issue for me. 
I expect RDP connection should work fine, probably expired by time out.
But after few hours working with mremoteng, I can't open new RDP connections anymore. They are all expiring by time out. But all my hosts are alive.
If I close and open software again, I can connect to the any host without any issues.
Steps to reproduce:
1) Open mremote ng, open 5-10 RDP tabs, close 2-3 RDP tabs, open again some RDP connection
2) Leave it for few hours, play again with RDP
3) Then try to close and open RDP connections again. You will get timed our error.
I recently moved to win10 from win 2012r2, I had same issues on older OS. I don't think this is OS issue.

**Comment by farosch** [comment]
There is a good chance this is related to a Microsoft Bug, that was just recently fixed. See #853 for more info.

> - Microsoft fixed this issue in Windows 10 1903: https://support.microsoft.com/en-us/help/4517211/windows-10-update-kb4517211
> - Microsoft fixed this issue in Windows 10 1809: https://support.microsoft.com/en-us/help/4516077/windows-10-update-kb4516077

Make sure to have the appropriate KB installed in case this fixes your issue.
If this does not fix your issue please provide a dump file and the mrng logfile for further analysis.
See https://mremoteng.readthedocs.io/en/latest/troubleshooting.html on how to do this.

**Comment by ivakinde** [comment]
Yes, I confirm the issue appears very rarely now. I've installed suggested patch and it solved the issue. Many thanks for your support!
