### ISSUE TITLE
MSI installer forgot to ask where to install

### ISSUE THREAD

**Issue by trasherdk** [mRemoteNG/mRemoteNG#1510]
MSI installer forgot to ask where to install
## Expected Behavior
Instead of blindly install to "C:\Program Files (x86)\mRemoteNG\", MSI installer should ask where to install.

Enough template.
I'm on a Windows 8.1 (64bit).
Long time user of SecureCRT/SecureFTP.
Remotes are mostly Slackeare (64) 14.2

On a side note: Why is this not called PuttyGUI ?

**Comment by ner00** [comment]
> On a side note: Why is this not called PuttyGUI ?

My assumption is that the intention is to not confuse people; the better questions is: why would you call this _PuttyGUI_?

**Comment by trasherdk** [comment]
Without diving into the source code, my feeling was: It looks like Putty in a wrapper. A nice one, though.
But. That was not the problem. The installer was.

**Comment by kmscode** [comment]
> Instead of blindly install to "C:\Program Files (x86)\mRemoteNG", MSI installer should ask where to install.

We'll flag this as an enhancement request for the installer. Currently it's a 32 bit app, so "Program Files (x86)" is the appropriate default location for the installer. You could drop the portable version anywhere you want if desired.


> On a side note: Why is this not called PuttyGUI ?

It's not just a wrapper for PuTTY... It can handle RDP, VNC and HTTP(S) connections natively as well as attempt to integrate user defined external tools.

**Comment by trasherdk** [comment]
Yes, you are right. It's the default location for 32 bit applications. But. I have chosen to install programs on a secondary drive, with a lot more space, mounted on "C:\Apps\" to separate OS from applications.

It's not exactly a bug. Only an annoyance, that one could overlook easily.

And. Forget about the Putty remark. I might have spoken too soon, as I'm still exploring possibilities in this thing.

**Comment by farosch** [comment]
Am I misunderstanding something here?I don't get the issue...
![image](https://user-images.githubusercontent.com/22905106/61174153-bf088a80-a59c-11e9-82c4-b9cbaec0123f.png)

**Comment by trasherdk** [comment]
![image](https://user-images.githubusercontent.com/5003891/61178902-befe9e00-a621-11e9-8ac0-8d310da5399f.png)

**Do you see it now?**
