### ISSUE TITLE
Capture keystrokes within an RDP session

### ISSUE THREAD

**Issue by kpinel** [mRemoteNG/mRemoteNG#1513]
## Expected Behavior
It would be very useful if keystrokes can be captured within the RDP session rather than on the workstation host.

## Current Behavior
Pressing Alt-PrtScrn currently takes a screenshot of the whole mRemoteNG window rather than the window within the RDP session.

## Context
When providing screenshots to vendors or clients, they need to be cropped prior to emailing them.
Trying to log off the horrible Windows Server 2012 RTM, it is very hard to find that 4 pixel menu "button" at the bottom left of the desktop.

## Your Environment
* Version used: 1.76.20
* Operating System and version: Windows 10 1809 x64
* Servers managed: Approx 900
* Server OS: Server 2008R2/2012/2012R2/2016/2019

**Comment by farosch** [comment]
This is already possible. You just need to redirect key combinations:
![image](https://user-images.githubusercontent.com/22905106/61173946-30930980-a59a-11e9-8a6a-916fd6ec4284.png)

**Comment by farosch** [comment]
Closed due to inactivity.
