### ISSUE TITLE
PuttySessions.Watcher.StartWatching() failed

### ISSUE THREAD

**Issue by mblissmer** [mRemoteNG/mRemoteNG#1514]
I'm running 1.76.20.24615

I was trying to get information about a crash that happened, and while in my log file I noticed the two following warnings back to back, every once in a while. I don't use any Putty sessions, only RDP. It's not on every connection, probably every five connections or so:

```
2019-07-11 14:21:01,252 [1] WARN  - PuttySessions.Watcher.StartWatching() failed.
Not found 
2019-07-11 14:21:01,253 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.
```

They always happen back to back. It looks like this was addressed in MR #760 but is still happening with my install.

Happy to provide any additional information I can!

**Comment by farosch** [comment]
Seems like this method is the Problem:
![image](https://user-images.githubusercontent.com/22905106/66199000-fff4d480-e69d-11e9-94cd-972823f5a522.png)

The file `C:\Source\mrng\mRemoteNG\mRemoteV1\bin\Debug Portable\putty.conf` simply does not exist.
Can anyone please enlighten me on that file?
