### ISSUE TITLE
Remote Desktop computers imported from AD have no settings.

### ISSUE THREAD

**Issue by joelsplace** [mRemoteNG/mRemoteNG#1518]
V1.77.0.41252

## Expected Behavior
When I import computers from AD for Remote Desktop almost no settings are available under Config after the import. Only Display/name and description, Connection/Hostname and Redirect/Audio capture are there.

## Current Behavior
All Config options are available if I add the connection manually

## Possible Solution
fix whatever removes most of the settings under config when importing from AD?

## Steps to Reproduce (for bugs)

1.  Import computers from AD
2.  Select View/Config
3.  Select a computer connection that was imported
4.  See that almost no options are available under config

## Context
This is my first attempt at using mRemoteNG.  I won't be able to use it if I can't use the import.

## Your Environment

* Version used: 1.77.0.41252
* Operating System and version Windows 10 Pro 1809.615 x64

**Comment by joelsplace** [comment]
Closed with no comment or solution?



Joel


-------- Original message --------

**Comment by farosch** [comment]
I have pushed commit c1b6bd4 to not enable inhertance by default when importing from AD.
You can read more about inheritance here: https://mremoteng.readthedocs.io/en/latest/folders_and_inheritance.html?highlight=inherit

**Comment by joelsplace** [comment]
I guess I didn’t make the problem clear.  It isn’t that the information doesn’t populate it is that the fields aren’t there for me to manually add the info.  Is that intentional?

**Comment by joelsplace** [comment]
That is great that it inherits username and password from the parent folder.  I can’t set the IP address in case the hostname has issues.  I’ll doublecheck when I’m back in the office Tuesday.
Thanks,
Joel

**Comment by joelsplace** [comment]
Just ignore me.  It works fine.

It does present a problem on our network because some PCs need to be logged into with a different account.  It is possible to log into them with the domain admin account but you don't have access to some programs that are user account specific so a way to over ride the inheritance per connection would be great.
Thanks!



Joel McGregor
817-994-8600


-------- Original message --------
