### ISSUE TITLE
Add to External Tools Toolbar option

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#152]
Received from user via e-mail...

Currently when one enables “External Tools Toolbar” under View, all of the external tools show up on the toolbar. I would like to be able to select which external tools will be available on the toolbar.

My suggestion is to create a new toolbar where tools can be added to it, by selecting a check box called something like “Add to External Tools Toolbar” under External Tools Properties. I have made the following mockup form screen shots to hopefully better illustrate my idea. I know that the example below is not the best but I hope it helps…

![image](https://cloud.githubusercontent.com/assets/16654335/19196113/3c05c4f8-8c82-11e6-921b-053468154f56.png)

I still want the External Tools to be available as they are, when right clicking on a connection and being able to run the commands against them.

**Comment by sparerd** [comment]
This will be available in v1.76
