### ISSUE TITLE
auto-login does not work on windows 10 1903

### ISSUE THREAD

**Issue by ggkr** [mRemoteNG/mRemoteNG#1520]
I have the latest version (1.76.20.24615) installed on windows 10 (64bit) 1803.
when trying to connect remotely to windows 10 (also 64 bit) 1903, using saved credentials, I hit the login screen of windows. username has been entered successfully, password hadn't been entered.

from what I can see this happens only  when connecting to the latest windows 10 versions

**Comment by ner00** [comment]
Is it a domain environement?
If it is, try yo include the domain name in the username field only: `DOMAIN\USERNAME`

**Comment by ggkr** [comment]
it is a domain environment. I tried your suggestion, didn't work

**Comment by ner00** [comment]
Have tou cleared the domain field too?

**Comment by ggkr** [comment]
yes

**Comment by farosch** [comment]
@ggkr Do you still have this isue?

**Comment by gkrBSE** [comment]
sorry for the late reply. yes, I do still have this issue. 
there are however some new developments (well maybe not new- but only now I am noticing them):

- if wrong credentials are entered, an authentication dialog (with an error message regarding credentials) will pop up. reentering correct credentials will connect to the desktop

- after connecting with saved connection (with credentials of course) and getting to the login screen. if I click "check for updates" from the help menu and close the tab that opened (I have the latest version), the session will reconnect (you can see that reconnecting a disconnected rdp session dialog for a sec) and actually enters into the desktop.  trying to manually reconnect the session (right click the connection tab and choosing "reconnect") does not produce the same result.

this same behavior happens to my colleagues that also use mRemoteNG

**Comment by farosch** [comment]
> if wrong credentials are entered, an authentication dialog (with an error message regarding credentials) will pop up. reentering correct credentials will connect to the desktop

imho this is the default behavior of rdp. depends on how the host you're connecting to is configured.

> after connecting with saved connection (with credentials of course) and getting to the login screen. if I click "check for updates" from the help menu and close the tab that opened (I have the latest version), the session will reconnect (you can see that reconnecting a disconnected rdp session dialog for a sec) and actually enters into the desktop. trying to manually reconnect the session (right click the connection tab and choosing "reconnect") does not produce the same result.

this is either no longer true in the current develop branch or caused by the panel size shrinking, depending on your tabs&panels settings
