### ISSUE TITLE
Remember open connections when closing

### ISSUE THREAD

**Issue by dalee-bis** [mRemoteNG/mRemoteNG#1521]
## Expected Behavior

When closing mRemote with connections open, it would be great if the list of open connections were saved and re-loaded when mRemote is next opened. This could also feature an "auto-save" in the event that mRemote or the machine crashes.

## Current Behavior

Closing mRemote warns that connections will be closed. When opening on the next run, the user must re-connect to each of the sessions from the connections panel.

## Possible Solution

It seems there are a few options:

* Save the currently connected sessions to the connection file and add an option for auto-save
* Create a new "state" file to be stored either alongside the connection file or to a user settings folder for mRemote (this may be the better option for autosave to prevent having lots of files in the same directory as the connection file).

## Context

I was logged on to ~10 servers and wanted to keep my sessions open but needed to shutdown my machine for the day. Had to re-connect the next day to each server individually.

This also leads into another issue where changing network (e.g. wired to wifi) will disconnect all of the currently open sessions and the user needs to re-connect them manually.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Enterprise 17763 x64

**Comment by sparerd** [comment]
This is already possible. Enable `Reconnect to previously opened sessions on startup` within Tools -> Options -> Startup/Exit

![image](https://user-images.githubusercontent.com/6999446/61535319-9ac30880-a9f7-11e9-888f-0038825bda65.png)


For situations when wifi drops you connections, you can turn on `Automatically try to reconnect when disconnected` to at least help with any RDP connections.

![image](https://user-images.githubusercontent.com/6999446/61535428-e1b0fe00-a9f7-11e9-9992-e0a72890578f.png)

**Comment by dalee-bis** [comment]
Oh, cool. My bad I should have read the documentation first. I find it a bit strange this isn't the default (or at least default is to prompt if you want to re-open closed) but consider my issue solved.

Out of interest since I've been looking through the options in the documentation, what does "Automatically get session information" do? (The description is missing in the docs).

**Comment by sparerd** [comment]
Oh actually I think we need to remove that option. That was tied to a feature that was removed between versions 1.72 and 1.74 I think. In short, it does absolutely nothing anymore :). Thanks for asking about it - we missed it for years.
