### ISSUE TITLE
Clipboard Doesnt work

### ISSUE THREAD

**Issue by Maxinfamily** [mRemoteNG/mRemoteNG#1525]
The clickpboard doesnt work at all. I have updated both windows and mRemoteNG to the latest version (on my local machine).

## Possible Solution
Maybe it is q confic between the remorte machine version and the local.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
 Windows 10 1809 build 17763.165 latest update KB4507419

**Comment by Benchwork** [comment]
when I installed the most recent stable version [1.77.0], all redirects on all my connections were turned off.
![image](https://user-images.githubusercontent.com/7304823/61724532-290ef580-ad3c-11e9-9cc3-63ce515093c7.png)

can you check to see if this is correct for you as well?

**Comment by farosch** [comment]
@Maxinfamily Have you been able to resolve your clipboard issues?

**Comment by hoanbc** [comment]
Hi, I have same issues with you. Enviroment i use is Windows10 path 1903 and mRemoteNG path 1.77.0.41252.
I can't use clipboard between my pc and remote server.

**Comment by Maxinfamily** [comment]
@Benchwork @farosch Thanks a lot to you all for answering!

Im sorry to answer so late but I found the solution the next day to the issue post. Its a "rdpclip.exe" process issue, and somehow, just by restarting it, the clipboard issue gets solved.

Check if the solution above helps @hoanbc :)
