### ISSUE TITLE
Extremely slow connecting to SSH session when using hostname instead of IP address

### ISSUE THREAD

**Issue by jf912** [mRemoteNG/mRemoteNG#1529]
When making a connection via SSH2 using a hostname the connection window appears to hang for many seconds - sometimes as much as 15 seconds before connecting.  If I specify IP address, the connection is almost instantaneous.  Using Putty directly, the connections open almost immediately either way.  NSLookup of hostnames on my system is extremely quick as well.

## Expected Behavior
Connection should be almost as fast when resolving by hostname.

## Current Behavior
Connections that are configured with hostname instead of IP take many seconds to connect and freeze the UI during this time.

## Possible Solution
Issue with DNS resolution code.

## Steps to Reproduce (for bugs)
1. Save a SSH2 session and supply hostname instead of IP address.
2. Connect

## Context
This was never a problem until several update releases ago when the issue emerged.

## Your Environment
Windows 10 Enterprise Version 10.0.18362 Build 18362 x64

**Comment by farosch** [comment]
I have no idea where code inside of mrng would interfere with dns resolution.
This should all be handled by your system or integrated tools like rdp and putty (though I think these will use operating system resources, too).
Can you please confirm, that this only happens in mrng and not in the default putty build.
And can you please also confirm, that this is not a general problem of your client / network in general? Make some tests with `nslookup` and maybe also take a look at this https://social.technet.microsoft.com/wiki/contents/articles/38126.how-to-measure-the-response-time-of-dns-servers-when-performing-name-server-lookups.aspx to test your dns servers response time. Btw my response time is around 0.026 seconds. (Im querying my companys domain controller over vpn)

**Comment by farosch** [comment]
Could be related to #540

**Comment by jf912** [comment]
Hi, Faryan. I was connecting to Linux servers so this is probably unrelated. Regardless, I have moved from a Windows machine to a Mac so I won’t be able to use mRemoteNG any longer.

Thanks,

Jeff

**Comment by limex** [comment]
I don't know why it works ... But I fixed the issue with "use console session" = YES. 
Maybe my problem was different: I never got a connection with FQN, but always with IP.
