### ISSUE TITLE
Using Remote Desktop, how can i Open a form seen ONLY by the user?

### ISSUE THREAD

**Issue by DKLeoBR** [mRemoteNG/mRemoteNG#1530]
User, for exemple, see a Overlay form with "Please Wait" and a Progress bar, for example
But ONLY the user will see this ONTOP form.

The controller will NOT see this form on Remote Desktop and can still controlling the remote computer with keyboard/mouse events.

Its possible? how? Thanks.

**Comment by farosch** [comment]
This is not possible.
RDP simply does not provide this kind of functionality.
