### ISSUE TITLE
Dissapears after minimizing

### ISSUE THREAD

**Issue by zmindless** [mRemoteNG/mRemoteNG#1531]
## Expected Behavior
minimizing mremoteng minimizes it, opens up after clicking on taskbar icon

## Current Behavior
if minimized, taskbar icon shows it as "not running". If I click on it, nothing happens. Process is still running, can be found under processes in Task Manager. The only way out is End Task and running again!

## Possible Solution
It may be caused only on multimonitor setups like mine.

## Steps to Reproduce (for bugs)

1. run remoteng
2. minimize it
3.click on taskbar icon

## Context
any time it's minimized it does this

## Your Environment

* Version used: 1.76.20.24669
* Operating System and version (e.g. Windows 10 1709 x64):Windows 10 Pro 1803 x64
3 monitors setup, multiple virtual desktops open (usually 2)

**Comment by farosch** [comment]
Is this what you mean? 

![YQcY8PKTBu](https://user-images.githubusercontent.com/22905106/64367584-b2daff80-d018-11e9-97ab-5b559f36acb1.gif)

**Comment by farosch** [comment]
Closed due to OP not responding
