### ISSUE TITLE
Problems with ipv6 connection

### ISSUE THREAD

**Issue by Spottel** [mRemoteNG/mRemoteNG#1539]
I have a problem connecting to my server via SSH2 with ipv6. Has always worked before. I think after an update not anymore. Maybe I'm doing something wrong.

I have created a new connection. Under IP address I have entered my ip6 address: 2axx:xxxx:xx:xxx::1

If I want to connect comes this error: 
Unable to open connection to 2axx
Host does not exist

Directly over Putty I can connect to the server with the same data, without problems.

I use the version 1.76.20.24615
Windows Pro x64 1809

Did I set something wrong? Maybe someone can help me.

Thank you very much
Frank

**Comment by farosch** [comment]
it should be enough to create a connection and set these values:
![image](https://user-images.githubusercontent.com/22905106/64014987-ce7b6d00-cb23-11e9-84d7-dd14480152ad.png)

> Under IP address I have entered **MY** ip6 address: 2axx:xxxx:xx:xxx::1
I'm guessing thats just bad wording but surely you need to enter the ip address of the server you want to connect to, not your own ip.

**Comment by Spottel** [comment]
Yes, I enter the data of my server and not my own ip address.

**Comment by cchaduka** [comment]
Faced the same issue, with the very same version of mRemoteNG. I then put the IPv6 address within square brackets and it worked... [2axx:xxxx:xx:xxx::1]

**Comment by Spottel** [comment]
Yes. Thank you cchaduka. Thats works!
