### ISSUE TITLE
mRemoteNG suddenly asking me for a password upon login

### ISSUE THREAD

**Issue by Gideon0157** [mRemoteNG/mRemoteNG#1541]
What the heck?
mRemoteNG suddenly asking me for a password upon login. How can I get rid of this?
I am not a programmer.
All my remote connections are in there!

**Comment by sparerd** [comment]
This typically indicates the connections file was corrupted - try recovering from a backup as described here: https://mremoteng.readthedocs.io/en/latest/troubleshooting.html#backup-and-recovery

**Comment by farosch** [comment]
Closed, as OP is not responding
