### ISSUE TITLE
The database version 2.7 is not compatible with this version of mRemoteNG.

### ISSUE THREAD

**Issue by HBN-Hans** [mRemoteNG/mRemoteNG#1542]
I get this error when I open mRemoteNG and when I want to add a new connection.
The database version 2.7 is not compatible with this version of mRemoteNG.

## Expected Behavior
I want to add and change credentials in my SQL connection

## Current Behavior
When I want to change the credentials or when I add an new connection I get the error 
The database version 2.7 is not compatible with this version of mRemoteNG.

We are connection trough SQL-Connection file.

Is there an way to upgrade the database version?

Kind Regards,
Hans Kroeze

**Comment by HBN-Hans** [comment]
Hi, I have never installed the beta version. I have installed the 1.76.20.
We are using it with 6 users at the same time.

Did you fix the issue?

**Comment by farosch** [comment]
@HBN-Hans One of your other users must have run a beta build and connected to your database, thats what updated the version.
You will have to set the version back to `2.6` manually.

**Comment by farosch** [comment]
Closed due to OP not responding
