### ISSUE TITLE
Replace MagicLibrary with DockPanelSuite

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#155]
Session tabs are created using MagicLibrary - no trustworthy source repo could be located. Assuming that this is no longer maintained by the original author (or anyone else). In addition, this does a lot of similar work to another library which is used for other panels that is actively maintained. The goal is to replace MagicLibrary with [DockPanelSuite](https://github.com/dockpanelsuite/dockpanelsuite).

**Comment by kmscode** [comment]
Problems related to MagicLibrary:

https://mremoteng.atlassian.net/browse/MR-873
When dragging a connection tab (e.g. to reorder), both the tabs in that tab panel bar and the icons in the Windows 10 notification area shift left/right rapidly, thus creating a flicking effect.

The longer you hold down the mouse button after initiating dragging, the longer the flickering is going to occur after you release the mouse button.

To reproduce, simply open two or more connections in the same panel and then click and drag one of the tabs left or right

---

https://mremoteng.atlassian.net/browse/MR-562
When the arrows at the far right of the tab bar are inactive (hollow triangles), they can still be clicked on, and what results is unexpected.

For example, if you have only a few tabs open in a panel, such that all tabs are currently visible without scrolling, then both tab arrows at the far right are in an inactive state, as expected. However, no matter which one you then click on, the focus will change to the right-most tab.

Expected behavior is that clicking on a "hollow"/inactive arrow will do nothing. 

---

https://mremoteng.atlassian.net/browse/MR-489

---

**Comment by kmscode** [comment]
https://mremoteng.atlassian.net/browse/MR-742
I I would like to see the ability to drag the tabs to their own windows. Many times I am RDP'd to two different machines and it would be nice to be able to drag one of the machines into its own window so that I could display it on a different monitor. This would really be useful when configuring one machine to have similar settings to another machine.

**Comment by kmscode** [comment]
Closing this one out... Primary efforts for removing magiclibrary have been completed by @jotatsu within the removemagiclib branch.

**Comment by SkyREgit** [comment]
New interface eats a lot of space though windows of RDP, putty sessions shows smaller.
Rolled back to 1.76
