### ISSUE TITLE
Win10 clients do not display dialog when attempting to connect via RDP to workstation with an active user console session

### ISSUE THREAD

**Issue by MrDwight** [mRemoteNG/mRemoteNG#1552]
Win10: mRemoteNG (portable) does not display dialog when attempting to connect via RDP to workstation with an active user console session.

## Expected Behavior
I've noticed this when attempting to connect to Windows 10 computers via RDP using mRemote portable (ver 1.77.0.41307).  When I attempt to initiate a Remote Desktop session to a Windows 10 workstation, if that workstation currently has a (different) user logged into it, the mRemote session does not refresh the screen to notify me that someone is already logged in, and if I continue it will lock the workstation for that person's session.  It should have a dialog prompt asking me if I want to continue?  (Yes)  (No).

Note: The screen refreshes and displays the warning/dialog properly when attempting to connect to a Windows 7 workstation.  It is only on Windows 10 that the dialog is not seen.

The end result is the person attempting the RDP connection doesn't realize that the RDP session is awaiting a response to the dialog because they are stuck viewing the spinning circle like it's still trying to connect.  Meanwhile, the Windows 10 workstation being connected to has initiated a countdown timer for the dialog.  If no response is received, then the RDP connection is dropped.

The problem is not encountered when using the Microsoft RDP client application to connect.

Sometimes, you can click on the screen (which looks like it's still trying to connect to the workstation) in the vicinity where the (Yes) dialog button would be (if the screen had refreshed), and it will accept the click and complete the RDP connection and initiate the RDP session, but it's nearly impossible to determine that without having the dialog visually in front of you.

Please refresh the screen to show that dialog when connecting to a Windows 10 workstation.

## Steps to Reproduce (for bugs)
1.  Initiate RDP connection in mRemote to a Windows 10 workstation with an active user session (different user).

## Context
It's a nuisance and difficult-to-impossible to make remote desktop connections when you can't see a dialog requiring a response.

## Your Environment

* Version used:  mRemote portable ver 1.77.0.41307 pre-release.  Also had same issue w/ stable version v1.76.20.
* Operating System and version (e.g. Windows 10 1709 x64):  I am running Microsoft Windows Pro x64 [Version 10.0.14393]

**Comment by farosch** [comment]
@MrDwight Are you trying to connect to a console session?
![image](https://user-images.githubusercontent.com/22905106/66140587-a8555b00-e602-11e9-8a67-9b7fa97484ef.png)

**Comment by MrDwight** [comment]
Sorry it took me so long to respond, but had a death in my family a couple of weeks ago, so was dealing with that.

To answer your question: No.  I am not attempting to connect to the active user console session.  I want to bump them off and login under my admin account.  But, what usually happens is when there is already an active user session, Windows alerts you to the fact that someone else is already logged on to the computer, and asks if you want to continue.  That's the dialog I am not getting under mRemote.  It works just fine under the MS Remote Desktop client.  Once you respond that you want to continue, Windows notifies the active user session with a dialog stating that (username) is attempting to connect to this workstation, and asks them for permission.  If they respond Yes, or do not respond within 30 seconds, then the active user session is switched to the remote desktop connection.

**Comment by MrDwight** [comment]
FWIW: I upgraded to the latest beta version (1.77.1.27713) and this issue appears to be resolved now.
