### ISSUE TITLE
Reimplement option to disable enhanced mode for vmrdp

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1564]
I have just tested this huge improvement in the latest preview. But I have one problem: Sometimes I need to be able to use the vmconnect in standard mode - not enhanced mode. And other VM's I have to use enhanced mode. As I read above, it is not possible to select standard mode. Is it possible to get that feature?

_Originally posted by @tboege in https://github.com/mRemoteNG/mRemoteNG/pull/1422#issuecomment-528563967_

I need it for a workaround for cisco anyconnect vpn. If I try to connect in enhanced mode, anyconnect fails (I think it detects its in an rdp-session (not entirely wrong), and the security settings forbids a connection). In default mode, I have no problems (with that).

I have tried in enhanced mode with no redirection of devices, but I still cannot connect with anyconnect.
So I think the only solution to make it work is to use default mode

_Originally posted by @tboege in https://github.com/mRemoteNG/mRemoteNG/pull/1422#issuecomment-528737774_

**Comment by farosch** [comment]
@tboege Could you pull the portable build from here and test this please?
https://ci.appveyor.com/project/mremoteng/mremoteng/builds/27239607/job/qllxyiba9in68d6f/artifacts

**Comment by tboege** [comment]
Thank you for your effort.

Unfortunately, my test shows, that I use enhanced mode, regardless of "Use enhanced mode" is true or false.

I think the easiest way to determine, if you are in enhanced or standard mode is to notice, if you connect directly to the desktop or if you are presented for the logon screen.
If I figure out, an easier way to determine enhanced/standard mode, I'll let you know.

**Comment by tboege** [comment]
Please ignore my advise on noticing logon screen. It depends on the typer of the former connect.
But you can use the command "query session" inside the VM. First I connect with standard mode, and the sessionname on my adm-session is console. After a change to enhanced mode, the sessionname change to some id. So  my conclusion is, that a standard session always shows console in query session.
C:\Users\adm>query session
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>console           adm                       1  Active
 31c5ce94259d4...                        65536  Listen

C:\Users\adm>query session
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>31c5ce94259d4...  adm                       1  Active
 console                                     3  Conn
 31c5ce94259d4...                        65536  Listen

**Comment by tboege** [comment]
Even though I am not a coder, I have a suggestion to where to look for the bug:
The patch adds: 
mRemoteV1/Connection/Protocol/RDP/RdpProtocol7.cs
                 rdpClient7.AdvancedSettings8.EnableCredSspSupport = true;
                    rdpClient7.AdvancedSettings8.NegotiateSecurityLayer = false;
                    rdpClient7.AdvancedSettings7.PCB = $"{connectionInfo.VmId};EnhancedMode=1";
+                    if (connectionInfo.UseEnhancedMode)
 +                       rdpClient7.AdvancedSettings7.PCB += ";EnhancedMode=1";
                }
            }

I think It wall always set EnhancedMode=1 - but twice if (connectionInfo.UseEnhancedMode)

So something like 
-                    rdpClient7.AdvancedSettings7.PCB = $"{connectionInfo.VmId};EnhancedMode=1";
+                    rdpClient7.AdvancedSettings7.PCB = $"{connectionInfo.VmId}";
+                    if (connectionInfo.UseEnhancedMode)
 +                       rdpClient7.AdvancedSettings7.PCB += ";EnhancedMode=1";

might work (just a long shot)?

**Comment by tboege** [comment]
Finally found out how to build mremoteng. I can confirm, that the change above works. Width that change, I can select standard or EnhancedMode.
