### ISSUE TITLE
PuTTY not logging

### ISSUE THREAD

**Issue by movinglightspeed** [mRemoteNG/mRemoteNG#1566]
## Expected Behavior

PuTTY should be logging -> Session left hand logging -> 
I went to tools -> options -> Advanced -> To configure putty sessions -> load Default settings -> All session output -> C:\Program Files (x86)\mRemoteNG\logs\&Y&M&D&T&Hputty.log logfile -> and back to Session -> Save to Default settings -> Close.

Closed nRemoteNG and reopened, connected to shell, wrote some commands, ran them and close the shell. No log file created.
## Current Behavior

No logs are created for putty shell sessions with commands ran and/or their outputs.
## Possible Solution

Make logs appear for putty session at specified location.
## Steps to Reproduce (for bugs)

1. Open mremoteNG 
2. Go to Tools -> Options - > Advanced -> To configure Putty Sessions -> Load Default Settings -> All session output -> input location "C:\Program Files (x86)\mRemoteNG\logs\&Y&M&D&T&Hputty.log" then back to Session -> Save to Default Settings -> Close 
3. Connect to shell, run some commands,
4. Close shell, and check location, you will find no logs generated

## Context

I can't use it for Sev 1 cases!! It is urgent 
## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 Enterprise 1903
mRemoteNG 1.77.1.27654

**Comment by farosch** [comment]
I have followed your steps exactly and logging is working fine. I am suspecting you are trying to write logs to a directory where you do not have permissions to write to.
