### ISSUE TITLE
Implement new cryptography providers

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#157]
Implement new cryptography providers to replace the current LegacyRigndaelCryptographyProvider.

Need to:
- Add a Security page to the Options
- Use the correct crypto provider during de/serialization

**Comment by sparerd** [comment]
This is related to the following old Jira tickets:
- https://mremoteng.atlassian.net/browse/MR-917
- https://mremoteng.atlassian.net/browse/MR-739
- https://mremoteng.atlassian.net/browse/MR-928

**Comment by sparerd** [comment]
Phase 1 complete. Security page created. We can now manipulate the encryption settings.

Now, we must make the de/serializers respect those settings.
- Serializers will respect the user settings, taken from the security options page.
- Deserializers will look for a particular attribute embedded within the serialized connections data. In the case of Xml, this will be a parent element that will not be encrypted.

**Comment by sparerd** [comment]
Note: We will still need to support deserializing the legacy encryption type.

**Comment by sparerd** [comment]
There are some issues with home I wanted to implement the confCons schema changes. Making the Connections node a child of the new EncryptionInfo node causes some rather uncomfortable issues. The best way to get around those issues is to move the attributes that were in EncryptionInfo into the Connections element. This requires the least amount of change... though admittedly it will require some rollbacks on the branch.

**Comment by sparerd** [comment]
Encryption/decryption with the new system is working well. Resolved all the bugs that I could find.

**Comment by jumoog** [comment]
old confCons.xml isn't working anymore.. password is invalid
