### ISSUE TITLE
putty zoom in out

### ISSUE THREAD

**Issue by hungrysnake** [mRemoteNG/mRemoteNG#1570]
Hi, Is it possible to configure or adding the feature to allow zoom in/out in the putty console?
I've been using mremoteng and love it so much. however, zooming is one of the feature I find it very useful in mobaxterm. I just hope mremoteng can also have that.

**Comment by farosch** [comment]
This is not possible, as mrng does nothing more than embedding PuTTY into the application and PuTTY does not have such a feature at the moment.
You would need to ask this request directly to the PuTTY project. See here on how to do this: https://www.chiark.greenend.org.uk/~sgtatham/putty/feedback.html#feedback-features
