### ISSUE TITLE
Save As wipes configuration file

### ISSUE THREAD

**Issue by dma550** [mRemoteNG/mRemoteNG#1572]
Using 1.77.0, on occasion (2X now) my confCons.XML has gotten wiped.  Backups to the rescue.  

It seems like making a change, doing a save as, overwrites the connection file with a fresh file, even though I have 10 connections defined.  It does not always do this.

The only solution I have found is a restore.  I am doing this to force saving a change.  I have noticed my confCons.xml does not always save.

Win 10Pro X64, Version 10.0.17134 Build 17134

**Comment by farosch** [comment]
Closing as I cannot reproduce this.
It's probably been fixed by now, as this occured in v.1.77.**0**
