### ISSUE TITLE
unable to update to 1.77.127654 due to undetected KB that already exists on PC

### ISSUE THREAD

**Issue by phatman81** [mRemoteNG/mRemoteNG#1576]
When trying to update to 1.77.127654, I get the following error on launch of the installer and then the installer exits.

ERROR:
mRemoteNG requires KB2574819 in order to create RDP connections. Windows 7 users will need to install this KB.

When I try to apply to my Win7 x64, I am advised that the update already is installed on my computer.

## Expected Behavior
Installer properly confirms the existence of KB2574819 .

## Current Behavior
Unable to install 1.77.127654 because the KB is not detected on my computer properly.

## Possible Solution
Maybe it is checking for the x86 version only?

## Steps to Reproduce (for bugs)
1. Launch installer for 1.77.127654
2. Error pops-up immediately
3.
4.

## Context
I can't upgrade...

## Your Environment
OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601
System Manufacturer	LENOVO
System Model	2352CTO
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz, 2901 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO G7ETB2WW (2.72 ), 6/12/2018
SMBIOS Version	2.7
Hardware Abstraction Layer	Version = "6.1.7601.24520"

**Comment by farosch** [comment]
https://mremoteng.readthedocs.io/en/latest/installation/install.html explains how to install mrng without the prerequisites check.

**Comment by farosch** [comment]
Closed due to OP not responding
