### ISSUE TITLE
Unexpected  shutdown of program

### ISSUE THREAD

**Issue by wdcadmin** [mRemoteNG/mRemoteNG#1580]
I run my rdp connector for remote PC. It tries to connect a long time and next the program shuts down. Next I stert again the program and everything is OK. I don't understand what's problem?

## Steps to Reproduce (for bugs)
1. I start the program
2. I connect to remote PC 
3. This operation isn't answering a long time.
4. After 15-20 seconds it closes unexpected. 
5. I start it again and connect well to remote PC. It's OK
6. I minimize it. 
7. I maximize it for use  and I get this error again.   

* Version used: 1.76.20.24615
* Operating System and version: Windows 10 1709 x64

**Comment by farosch** [comment]
Closed due to OP not responding
