### ISSUE TITLE
Putty session not active focus when changing tabs

### ISSUE THREAD

**Issue by luke-weller** [mRemoteNG/mRemoteNG#1586]
## Expected Behaviour
When changing into a connection tab running putty, the putty session should be the active focus for immediate keyboard input.

## Current Behaviour
When changing into a connection tab running putty, the putty session is not the active focus, which means that you have to click on putty for it to become active and receive keyboard input.

## Steps to Reproduce (for bugs)
1. Open two putty sessions into two separate tabs (the standard behaviour when opening two connections)
2. Click the tab to the previous (first opened) session.
3. Start typing, and notice that the keyboard input is not being received.
4. Click the tab to the second session, and see that's not receiving keyboard input either
5. Click the putty session, and see that keyboard input is back.

## Context
I connect to several ssh sessions each daily, and rapidly move between them. This current behaviour isn't a show stopped obviously, it's a little annoying!

## Your Environment
mRemoteNG 1.77.1.27654
Windows 10 1803 17134.1006

Many thanks! :)

**Comment by luke-weller** [comment]
Ah, this sounds like the same issue as #1535

**Comment by farosch** [comment]
It's actually more like #1408 😝

**Comment by luke-weller** [comment]
Dam, I spent longer searching for a similar issue then making this, and I still couldn't find it! Thanks for clearing up!
