### ISSUE TITLE
mRemoteNG crashed [1.77.1]

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#1587]
Yesterday I switched to 1.77.1 and it crashed twice. Older version 1.76 was stable.

Was working with mRemoteNG and had a couple (~10) tabs open and it just crashed.
Can't see an error in the mRemoteNG log, only in Windows eventlog.

Yesterday:
Faulting application name: mRemoteNG.exe, version: 1.77.1.27713, time stamp: 0x5d6d3405
Faulting module name: ntdll.dll, version: 10.0.16299.936, time stamp: 0x7b4896c1
Exception code: 0xc0000374
Fault offset: 0x000da2b9
Faulting process id: 0x1018
Faulting application start time: 0x01d56d4d921b2d33
Faulting application path: D:\Software\mRemoteNG-Portable-1.77.1.27713\mRemoteNG.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: f9cd5d4f-ba79-483f-bf48-3a3ad100391a
Faulting package full name: 
Faulting package-relative application ID: 

-------
Today:
Faulting application name: mRemoteNG.exe, version: 1.77.1.27713, time stamp: 0x5d6d3405
Faulting module name: Windows.UI.XamlHost.dll, version: 10.0.16299.696, time stamp: 0x683827d7
Exception code: 0xc0000409
Fault offset: 0x00005949
Faulting process id: 0x67e8
Faulting application start time: 0x01d56e2b97dc356a
Faulting application path: D:\Software\mRemoteNG-Portable-1.77.1.27713\mRemoteNG.exe
Faulting module path: C:\Windows\System32\Windows.UI.XamlHost.dll
Report Id: 1f208c74-1529-415a-b36b-a19624dab0ce
Faulting package full name: 
Faulting package-relative application ID: 

## Your Environment

* Version used: 1.77.1 Portable
* Operating System and version (e.g. Windows 10 1709 x64): Window 10 1709 x64

**Comment by farosch** [comment]
There's alredy an issue adressing that #853, unfortunately this isn't anything we can do something about: (Link to the article: https://support.royalapps.com/support/solutions/articles/17000084181-royal-ts-crashing-due-to-windows-ui-xamlhost-dll-when-using-remote-desktop)

> **Explanation**
> The crash is caused by the Windows DLL "Windows.UI.XamlHost.dll", which is responsible for the "Windows Security" dialog in Windows 10. This dialog is invoked by the Microsoft ActiveX RDP control we use to establish the RDP connections in our application. This is a component shipped with every Windows operating system directly by Microsoft.
> 
> More technical background: Once a RDP connection gets opened, the ActiveX RDP control is being initialized by our application. For example, when no or wrong credentials are provided, the said ActiveX control shows the "Windows Security Dialog". Unfortunately this kind of crash cannot be handled gracefully by Royal TS.
> 
> Based on our experience, similar crashes can happen because of faulty drivers (especially fingerprint-, graphics- or Thunderbolt-drivers).
> 
> Other products (like Microsoft Remote Desktop Manager or even Microsoft Outlook are suffering from these crashes). Microsoft has been made aware of the bug (see: Visual Studio developer community). We are still waiting for Microsoft to fix this. If you are experiencing these crashes, feel free to comment here and let Microsoft know.
> 
> **Solution**
> The only workaround so far and preventing the crash, is to provide a valid username and password or configure the Credential Mode of your Remote Desktop connection to use "Credential by name" and specify "?" as credential name (without the double-quotes) to invoke our own credential prompt. If you have setup a group policy to now allow password submission for Remote Desktop connections, there's no workaround.
> 
> We're waiting for a fix on Microsoft-side. There is unfortunately nothing we might be able to try preventing Royal TS from crashing in this scenario.
> 
> **Update from Microsoft**
> Microsoft acknowledged the bug and according to them, the fix has been approved and it’s making its way to 19H2 at the moment. Afterwards, it will get ported to 19H1 and RS5.

**Comment by janis-veinbergs** [comment]
See #853 comments - fixed with latest windows updates (September 26, 2019)
