### ISSUE TITLE
Clipboard not working

### ISSUE THREAD

**Issue by mattbob-brock** [mRemoteNG/mRemoteNG#1588]
## Expected Behavior
Clipboard should be a shared resource

## Current Behavior
Clipboard / rdpclip.exe does not work on prerelease v1.77.1

## Possible Solution
Reverting to 1.76.20.24615 it works.

## Steps to Reproduce (for bugs)

1. Install prerelease v1.77.1 on Windows 10 Enterprise (1709) 16299.1387
2. Launch mRemoteNG, Add a connection
3. Connect to the remote server (Windows Server 2016 Standard)
4. Attempt to copy paste from remote to local / visa versa

## Context

Trying latest release

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
prerelease v1.77.1 on Windows 10 Enterprise (1709) 16299.1387
Windows Server 2016 Standard

**Comment by farosch** [comment]
Have you enabled sharing the clipboard?
See #1562

**Comment by mattbob-brock** [comment]
Thanks farosch!  Didn't realize there was a new setting for this.

**Comment by farosch** [comment]
you welcome! I‘ll double check to confirm it‘s in the changelog asap 😌
