### ISSUE TITLE
Password protect connection file

### ISSUE THREAD

**Issue by thecosmictrickster** [mRemoteNG/mRemoteNG#159]
mRemote allowed you to password-protect your connection file. While mRemoteNG still supports [old] password-protected files, it doesn't seem to allow you to create a password-protected connection file, remove a password from a password-protected connection file, or change the password on a password-protected connection file. 

NB - this was in addition to encrypting the connection file. It's all well and good encrypting the file, but if someone else can get on your machine and just run mRemoteNG and view it, the value of it is lessened.

**Comment by sparerd** [comment]
Password protection is a current feature of mRemoteNG, though it is hidden in an odd location.

The feature can be turned on by going to the root "Connections" node in the connection tree and turning "Password protect" to Yes. The program will require that password to decrypt the file. To change the password, you must deactivate then reactivate this feature.

![2016-10-09_1529](https://cloud.githubusercontent.com/assets/6999446/19223795/8d0ee136-8e35-11e6-94b1-0749ae5e163d.png)


Does this adequately address your issue?

**Comment by thecosmictrickster** [comment]
It certainly does. Thanks.
