### ISSUE TITLE
Connecting to ssh with @ in username

### ISSUE THREAD

**Issue by tplecko** [mRemoteNG/mRemoteNG#1598]
Creating a SSH connection with @ character in username

## Expected Behavior
Loging in

## Current Behavior
Access denied
using the same username format from another linux machine si resolved by executing
ssh "user@domain"@server 

## Possible Solution
Didn't find any

## Steps to Reproduce (for bugs)
Create a connection to SSH server which uses username in format user@domain

## Context
Must enter username/password combination every time upon opening the connection

**Comment by farosch** [comment]
Let's make this example to verify, that I understand what you mean:
- You have a linux server `someserver` with a user called `peter@home`
- The server resides in the domain `domain.local`
- You are trying to connect to the server with these settings:
![image](https://user-images.githubusercontent.com/22905106/65838183-b2284700-e300-11e9-940e-7aeda7c3bdc5.png)

Is that right?

**Comment by tplecko** [comment]
Correct.

When using linux, the problem is solved by adding quotes around the username

now that i look at it a little better, that's not a mRemoteNG problem - that's a putty problem.

![mremote1](https://user-images.githubusercontent.com/33724115/65879529-45f52400-e390-11e9-9c58-29e50b927146.png)

**Comment by farosch** [comment]
In this case there isn't much we can do about this, as long as we're relying on PuTTY and #181  hasn't been implemented yet.
Please open a bug report directly at the PuTTY project:
https://www.chiark.greenend.org.uk/~sgtatham/putty/feedback.html#feedback-bugs
