### ISSUE TITLE
Add option to set resolution + SmartSize

### ISSUE THREAD

**Issue by Tragen** [mRemoteNG/mRemoteNG#1599]
When I set the RDP resolution to "smart size", then the remote desktop gets the resolution of my window size.
When I set it to ex. 1600x900 and I connect, I always have to click on the tab and choose "SmartSize". Please add an option to always do it.

**Comment by farosch** [comment]
I don't understand your problem.
Connecting with a specific resolution will set that resolution and conecting in smart size will use smart size.
Where exactly is the problem?

**Comment by farosch** [comment]
Closed due to OP not responding

**Comment by Tragen** [comment]
I wanted to connect with a specific size.
When I set "Smart Size" in the Resolution property, it always uses the resolution of my window.
What I want is a fixed resolution and the "SmartSize" selected from the tab.

![image](https://user-images.githubusercontent.com/1700241/66610942-5b065a00-ebbd-11e9-800c-e693a0ec6a57.png)

Currently mRemoteNG connects and I have scrollbars and I need to select "SmartSize".

This combination is not possible currently.

**Comment by farosch** [comment]
See #1606
