### ISSUE TITLE
Copy clipboard from/to remote computer

### ISSUE THREAD

**Issue by Tragen** [mRemoteNG/mRemoteNG#1600]
The new option to disable clipboard sharing is great. But sometimes I need to copy the clipboard.
Is it possible to have 2 buttons to copy the remote clipboard to the local computer and vice versa?

**Comment by farosch** [comment]
I am assuming you are talking about RDP connections.
When a RDP connection is initiated without clipboard sharing there is **absolutely no way** to copy something from the server to the client or the other way round.
This means there is no possibility for us to implement such a button.
If you want to be able to copy from/to the server you will have to initiate that connection with clipboard sharing enabled.

In case I misunderstood you, please let me know, I will then reopen this issue.
