### ISSUE TITLE
MySQL error Missing the DataColumn 'UseEnhancedMode' 

### ISSUE THREAD

**Issue by dimwazel** [mRemoteNG/mRemoteNG#1604]
Hello,

I am trying to configure mRemoteNG portable version 1.77.1.27713 with mysql for testing purpose.

I am getting this error when I try to create a new connection in a blank connection "file".

----------
ErrorMsg
09/30/2019 09:34:28
Couldn't save connections file as ""!
Missing the DataColumn 'UseEnhancedMode' in the DataTable 'tblCons' for the SourceColumn 'UseEnhancedMode'.
----------

I used this script to create database : mRemoteV1/Documentation/mysql_db_setup.sql
Which includes the column : `UseEnhancedMode` tinyint(1) DEFAULT NULL,

## Steps to Reproduce (for bugs)
1. Create new database.
2. Launch mRemoteNG 1.77.1.27713 with blank connection File.
3. Configure mysql connection, Test connection = successful. 
4. Create new connection.
5. If I delete the connection, I can save and reopen mRemoteNG without any errors.

Thank you very much!
Dimwazel

**Comment by farosch** [comment]
This issue has already been fixed in the develop branch.
Thank you very much for submitting this issue though!

**Comment by GnaXi** [comment]
That's great, but when can we expect the fix hits Prerelease, so that we might actually use the feature again? :P

**Comment by GnaXi** [comment]
For those as impatient as me, a develop build where the issue has been resolved can be found here:
https://ci.appveyor.com/api/buildjobs/96krv2bmo4uoi9fa/artifacts/Release%2FmRemoteNG-Installer-1.77.1.20543.msi

**Comment by mandras73** [comment]
> For those as impatient as me, a develop build where the issue has been resolved can be found here:
> https://ci.appveyor.com/api/buildjobs/96krv2bmo4uoi9fa/artifacts/Release%2FmRemoteNG-Installer-1.77.1.20543.msi

How can I download the new "msi"? It says: "Artifact not found or access denied"
Thank you

**Comment by GnaXi** [comment]
A newer build has been put up in the meantime it seems:
https://ci.appveyor.com/api/buildjobs/o3qfcbxlm4s807cl/artifacts/Release%2FmRemoteNG-Installer.msi (1.77.1.32135)

**Comment by mandras73** [comment]
> A newer build has been put up in the meantime it seems:
> https://ci.appveyor.com/api/buildjobs/o3qfcbxlm4s807cl/artifacts/Release%2FmRemoteNG-Installer.msi (1.77.1.32135)

Thank you!

**Comment by mandras73** [comment]
But it seems, now I have a new issue:

----------
ErrorMsg
09/11/2020 11:05:58
Couldn't save connections file as ""!
Missing the DataColumn 'Favorite' for the SourceColumn 'Favorite'.
----------

**Comment by mandras73** [comment]
Follow-up issue resolved here: https://github.com/mRemoteNG/mRemoteNG/issues/1807
