### ISSUE TITLE
Feature request: Save session log

### ISSUE THREAD

**Issue by JonAnder83** [mRemoteNG/mRemoteNG#1612]
Most of the times I work with mRemoteNG, I have to save a log of all the actions that I've performed.
I see no other way of doing so that to select all the terminal output and copy-paste it to an external file.
Is there a native way to do so from the app? If not, would it be too hard to implement this function in an upcoming release?
Nothing fancy, just an export to a txt file would be more than enough.

**Comment by farosch** [comment]
What kind of connection do you want to log?

**Comment by JonAnder83** [comment]
I already found out a way to do what I want, went ahead and configured putty to output a log of everything that happens on my ssh connections to a file with the hostname and timestamp.
I guess we can use it that way.... Any way to integrate it into mremoteng instead of just using putty?

**Comment by farosch** [comment]
Unfortunately, there is no native ssh handling in mremoteng at all. This is the only way to do it atm, except for copy-pasting like you already sugested. This will change, once #181 is implemented.
