### ISSUE TITLE
Open link in http connection creates ghost window for external link

### ISSUE THREAD

**Issue by nmat** [mRemoteNG/mRemoteNG#1614]
A ghost window is created when trying to access a link that goes outside of the mremoteng window. This is really a ugly way to handle external links and so should be fixed or opened in the default browser.

## Expected Behavior
Either get a question to open in default browser or follow the link in a new tab.

## Current Behavior
Creates a ghost window and nothing happens.

## Steps to Reproduce (for bugs)

1. Login to the administrative interface for a synology diskstation
2. Go to Control Panel -> Update and Restore
3. Try to go to version information for installed DSN software

BOOM creates a ghost window and nothing happens.

**Comment by farosch** [comment]
dev note:
looks like there is no handling of external links in http/https connections. This happens for connections using gecko as rendering engine. I will need to verify if this is also the case when using the IE engine.

**Comment by farosch** [comment]
No longer relevant since merging #1690
