### ISSUE TITLE
mremoteng - starting up process but not opening up on screen.

### ISSUE THREAD

**Issue by Matteo961** [mRemoteNG/mRemoteNG#1621]
2 users in our company are both experiencing the issue where mremoteng does not open up evry time you launch it. They have multiple other development tools installed like I-Series Sql-studio visual studio, ...

## Expected Behavior
Opening up the application launches the GUI.

## Current Behavior
Stating the exe shows loading symbol
Checking in taskmanager process is started 0% cpu usage.
Killing and re-opening sometimes gets the GUI to launch

##Troubleshooting
Uninstalling.
Reinstalling multiple versions.
Trying portable versions.
Clearing all related config files.

##Wondering..
What dependencies outside of the installation folder does mremoteng access ?
Maybe some other application is hidering its functionality ?

* Operating System and version (e.g. Windows 10 1809x64):

**Comment by Pulsatilla** [comment]
Same thing here: can no longer launch mRemoteng. Uninstalled and reinstalled, to no avail: can no longer start it...

**Comment by farosch** [comment]
Please provide a logfile and dump for further analysis:
https://mremoteng.readthedocs.io/en/latest/troubleshooting.html

**Comment by jdion81** [comment]
I had the same issue, but I am running Windows 7. I got it to open by changing the shortcut to open the app in Windows XP compatibility.

**Comment by Kvarkas** [comment]
Could you please provide what version of mRemoteNG you are referring?

**Comment by Kvarkas** [comment]
Close as no responce from user an we cant reproduce same
