### ISSUE TITLE
Breaks display adapter for Windows 10

### ISSUE THREAD

**Issue by tarmstrong69** [mRemoteNG/mRemoteNG#1623]
application windows flash causing issues when typing or working in the applications for ALL applications, I started in safe mode uninstalled the display adapter, set to normal mode ran Windows Update checker it found missing display driver from 2/2019 and installed, all worked correct again until I opened mRemoteNG again and now it is all broken AGAIN.

## Expected Behavior
application windows should not flash

## Current Behavior
application windows open and then the title bar flashes between windows green and clear, including task manager and system windows

## Steps to Reproduce (for bugs)

1. Start windows 10
2. Open mRemoteNG
3. Open task manager - see the windows title bar flash

## Context
Slows my work and makes errors when typing and it skips keystrokes during the flash

## Your Environment

* Version used: 1903
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Pro OS build 18362.418

**Comment by nmat** [comment]
Can you please provide version of mremoteng used here and also if you are getting the same effect on recent updates?

I am running mremoteng here and there is no flashing in the titlebar or anything. Would need a bit more information here I believe.

**Comment by tarmstrong69** [comment]
You can close this ticket, further digging found it to be a different application. Thanks
-------- Original message --------From: nmat <notifications@github.com> Date: 11/14/19  5:13 PM  (GMT-07:00) To: mRemoteNG/mRemoteNG <mRemoteNG@noreply.github.com> Cc: tarmstrong69 <teri@tystaxidermy.com>, Author <author@noreply.github.com> Subject: Re: [mRemoteNG/mRemoteNG] Breaks display adapter for Windows 10
  (#1623) Can you please provide version of mremoteng used here and also if you are getting the same effect on recent updates?
I am running mremoteng here and there is no flashing in the titlebar or anything. Would need a bit more information here I believe.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mRemoteNG/mRemoteNG/issues/1623?email_source=notifications\u0026email_token=ANQGRNQBXZWYCRIFXHX2XT3QTXSTVA5CNFSM4JBOTPMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEDZWSY#issuecomment-554146635",
"url": "https://github.com/mRemoteNG/mRemoteNG/issues/1623?email_source=notifications\u0026email_token=ANQGRNQBXZWYCRIFXHX2XT3QTXSTVA5CNFSM4JBOTPMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEDZWSY#issuecomment-554146635",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nmat** [comment]
@tarmstrong69 thank you for verifying. Closing ticket and please do not hesitate to ask questions :)
