### ISSUE TITLE
1.77.1 breaks RDP drive and sound redirection

### ISSUE THREAD

**Issue by klui2k1** [mRemoteNG/mRemoteNG#1632]
## Expected Behavior

Host drives should show up and there should be sound while using RDP. Microsoft's msts works.

## Current Behavior

No host drives show up when opening Windows Explorer, under Windows 7 or 10.

## Steps to Reproduce (for bugs)

1. Define an RDP connection
2. Under config, ensure Protocol is set to RDP, Version is set to Rdc6, Rdc8, or Highest. Probably doesn't matter.
3. Under config, ensure Redirect Disk Drives: Yes, Sounds: Bring to this Computer.
4. Connect then play a sound and open Windows Explorer
5. Sound doesn't play; Windows Explorer doesn't show host drive.

## Your Environment

* Version used: 1.77.1
* Operating System and version (e.g. Windows 10 1709 x64): Windows 7 x64 - up-to-date

**Comment by GurliGebis** [comment]
@klui2k1 are you seeing this problem with version 1.77.0 ?
If not, that helps narrow down where the problem was introduced :)

**Comment by klui2k1** [comment]
It also happens under 1.77.0.

**Comment by GurliGebis** [comment]
Okay, but it was introduced in the 1.77 branch? (not in the latest 1.76) 🙂

**Comment by klui2k1** [comment]
Correct, introduced in the 1.77 branch, not in 1.76.

It could be a regression issue with allowing which drives to map per https://github.com/mRemoteNG/mRemoteNG/issues/317

**Comment by GurliGebis** [comment]
Nope, it is caused by Clipboard redirection being set to No, which causes it to fail for some reason :(

**Comment by klui2k1** [comment]
Maybe related to a change in behavior in MS's main branch of RDP described at https://social.technet.microsoft.com/Forums/en-US/04ff5091-491d-4d80-ba0b-1819959904de/rds-2012-r2-disable-local-drive-redirection-with-working-clipboard?forum=winserverTS

**Comment by GurliGebis** [comment]
It is only blocled until it has been reviewed by someone with write access to the github project

**Comment by xbliss** [comment]
> Nope, it is caused by Clipboard redirection being set to No, which causes it to fail for some reason :(

Facing this again here: https://github.com/mRemoteNG/mRemoteNG/issues/1879 

Is there a work around or fix?
