### ISSUE TITLE
RDP session is not maintained if you move software from one monitor screen to another

### ISSUE THREAD

**Issue by studentforever-yahoo** [mRemoteNG/mRemoteNG#1647]
## Expected Behavior
Expected behavior should be if you move the application on same PC, across multiple attached LCD Screens, then the current RDP and other sessions should maintain, and continue.
## Current Behavior
Current behavior is that you move the application from screen to screen and it either closes the sessions or tries to connect again. 

## Possible Solution
Maintain current session to same remote device, regardless of moving the screens, tabs or application from one attached monitor to another. on the same PC.

## Steps to Reproduce (for bugs)
1. start application on a PC which has more than one Monitor
2. once started application on one monitor, start a RDP session to a server
3. once RDP session is running, move the application or tab from one monitor to another monitor
4. see if it maintains the remote connection
5. repeat step 3

## Context
This creates an issue if you are connected to a load balanced FQDN and each movement on screen to screen, creates a new session on a new server. if 10 servers were load balanced to the same name. you will have multiple seesions now open to multiple servers.

## Your Environment
* Version used: 1.76.20 (2019-04-12)
* Operating System and version Windows 10 1709 x64 with Two monitors.

**Comment by LIyoai** [comment]
this is probably because of this setting
![image](https://user-images.githubusercontent.com/6205123/69793523-e917bd80-11c8-11ea-9aa5-770bfb17db37.png)

**Comment by kmscode** [comment]
@LIyoai is correct. That is the most likely cause - in addition to the "Fit to panel" - this is working as designed.

When I know I'll be moving the window around, I set it to "SmartSize" by right clicking on the connection tab:
![image](https://user-images.githubusercontent.com/16654335/69968728-ff838900-14e8-11ea-8e3f-ef0659c18884.png)

**Comment by studentforever-yahoo** [comment]
Hi, yes all my connections having issues had this setting as "Yes".

![image](https://user-images.githubusercontent.com/22605021/70014439-df2dfa00-15ce-11ea-937d-838e920579a7.png)

I can confirm with setting as "No", i can move the tabs and it remains. (dosent' disconnect or tries to reconnect). Also tested the smart size setting.

Thank you for a quick reply. Ticket can be closed.
