### ISSUE TITLE
VNC remote access vulnerabilities

### ISSUE THREAD

**Issue by Neustradamus** [mRemoteNG/mRemoteNG#1648]
There are VNC remote access vulnerabilities: https://www.kaspersky.com/blog/vnc-vulnerabilities/31462/

**Comment by kmscode** [comment]
mRemoteNG uses [VncSharp](https://github.com/mRemoteNG/VncSharp) for it' VNC client. This client is not mentioned anywhere within the linked blog post.

We do not ship with any of the clients or servers listed.

Any vulnerable servers would be the users responsibility to update.

Further searching revealed no known vulnerabilities for VncSharp.

Thanks for reporting and feel free to reopen should you have any info that pertains to vulnerabilities in mRemoteNG/VncSharp, etc...
