### ISSUE TITLE
External tool command line arguments problem

### ISSUE THREAD

**Issue by artemibe** [mRemoteNG/mRemoteNG#1664]
I'm add new external tool `my.exe` with arguments:
`%Hostname% %Username% %Password%`
In connection profile add information:
Hostname = `192.168.0.1`
Username = `admin`
Password = `!12345678`

## Expected Behavior
Executing: `my.exe 192.168.0.1 admin !12345678`

## Current Behavior
Executing: `my.exe 192.168.0.1 admin ^!12345678`
(adds `^` to password field)

## Possible Solution
some parsing of special characters at begin of string

## Steps to Reproduce (for bugs)
Wrote in problem description

## Your Environment
Windows 10 x64 Prof, mRemoteNG 1.76.20

**Comment by kees-z** [comment]
You can use `%!password%` to avoid metacharacter escaping and argument splitting.
Set the External apps help in mRemoteNG for more information (press F1 and click External apps).

**Comment by artemibe** [comment]
> You can use `%!password%` to avoid metacharacter escaping and argument splitting.
> Set the External apps help in mRemoteNG for more information (press F1 and click External apps).
Add new external tool for each password variant?
If some symbols need to be replaced, arguments must have RAW mode: {raw %Password%}, {esc %password%}, {url_encode %Password%} etc...

**Comment by kees-z** [comment]
> Add new external tool for each password variant?

If passwords must be passed literally to an external app, you can create just one external app using the `%!password%` variable instead of `%password%`.

**Comment by artemibe** [comment]
It's works. Don't find it in documentation...

**Comment by kees-z** [comment]
It's here: https://mremoteng.readthedocs.io/en/latest/user_interface/external_tools.html
Scroll down to "Shell metacharacter escaping".
