### ISSUE TITLE
1.77.1.27654 copy / paste do not work between sessions

### ISSUE THREAD

**Issue by Aurelien-chiva** [mRemoteNG/mRemoteNG#1665]
1.77.1.27654 copy / paste do not work between sessions

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by kees-z** [comment]
Isn't this PR #950 that was implemented in V177?
If it's disabled, I guess you should be able to enable it in the connection settings.

**Comment by farosch** [comment]
Closed for voidness of the ticket and OP not answering.
Also, @kees-z is probably right and clipboard sharing is just not enabled.
