### ISSUE TITLE
Can Not Bring Up Help from F1

### ISSUE THREAD

**Issue by cinquestl** [mRemoteNG/mRemoteNG#1670]
Pressing F1 or selecting help\mRemoteNT Help displays error dialog

## Expected Behavior

To bring up a local help file.

## Current Behavior
Help is not available locally. You can still review on the web site.

## Possible Solution

I believe the request has a leading back slash making for an improper open.

## Steps to Reproduce (for bugs)

1.Start mRemoteNT
2.Hit F1. Error appears immediately

## Context
A hinderance in looking up help for the product. Not major, but does then require access from the web site to assist.

## Your Environment
* Version used: V1.77.1.27654
![mRemote-Help-Fail](https://user-images.githubusercontent.com/40247553/72191300-6426e300-33c7-11ea-8ce1-edd604365cf8.jpg)

* Operating System and version: Windows 10 1909 x64): OS Build 18363.535

**Comment by Eldaw** [comment]
I've encountered the same problem, with the portable version of v1.77.1. I think the problem is that it's trying to open 'index.html', when in fact the file is called 'index.htm'.

**Comment by Kvarkas** [comment]
I planning to move such away from local to web, so instead of local file it will point to global documentation file. More likely will be implemented (partially) in 1.77.2
