### ISSUE TITLE
Cannot open multiple RDP sessions on recent Windows fast ring builds 19541 and 19536

### ISSUE THREAD

**Issue by robertiansweetman** [mRemoteNG/mRemoteNG#1671]
## Expected Behavior
Should be able to run multiple RDP connections in parallel

## Current Behavior
Open second RDP connection and mRemoteNG crashes immediately
This does not occur with multiple SSH connections

Interestingly you *can* run a single mRemoteNG RDP session and use Windows Remote Desktop to connect to multiple other windows machines without either crashing...

## Possible Solution
Use SSH to connect to multiple windows clients instead
Run only 1 RDP session with mRemoteNG

## Steps to Reproduce (for bugs)
1. Open a windows RDP session
2. Open a second windows RDP session 
3. Application Crashes

No useful information in the mRemoteNG log as it simply crashes. All debug was set to 'on'.

Application Event log Error
```
Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, time stamp: 0x5cb09552
Faulting module name: mstscax.dll, version: 10.0.19541.1000, time stamp: 0xe5608cfd
Exception code: 0xc0000409
Fault offset: 0x0017505d
Faulting process id: 0xd8
Faulting application start time: 0x01d5cb2b7c235434
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\system32\mstscax.dll
Report Id: 410c08cb-2d03-4e13-b0ec-77cac408d72b
Faulting package full name: 
Faulting package-relative application ID: 
```
**Windows Error Report** included as txt file attachment
[Report.txt](https://github.com/mRemoteNG/mRemoteNG/files/4062196/Report.txt)

## Context
Just wondering whether it really is the underlying vendor (OS) issue or if there is something else I can actually change to get this back to working?

## Your Environment
* mRemoteNG Version used: 1.76.20.24615
* Windows 10 fast ring builds 19541 (8th Jan 2020 ) and 19536 (16th Dec 2019)
* See https://docs.microsoft.com/en-us/windows-insider/flight-hub/
* Remote Desktop Connection Control Version 10.0.19541 <-- this is 'possibly' the issue?

**Comment by JoakimOfficial** [comment]
Can confirm. Started with build 19536.

**Comment by farosch** [comment]
We will not investiate/fix issues occuring in versions of windows, that are not released to the general public. As the past has shown most of these will be fixed by microsoft as soon as these fixes are released to all versions of windows. Also all mrng does is calling third party functions to establish an RDP connection. These are provided by microsoft and are known to have caused problems in fast ring / preview builds.

Also: I would **strongly** advise against installing fast ring builds on productive machines, Microsoft clearly states:

> Be prepared for issues that might block key activities or might require workarounds.

https://docs.microsoft.com/en-us/windows-insider/at-home/rings

**Comment by JoakimOfficial** [comment]
Lucky it works on 1.77 then.

**Comment by robertiansweetman** [comment]
> 
> 
> Lucky it works on 1.77 then.

@JoakimOfficial I really appreciate you posting that info. Thanks! 😄

**Comment by robertiansweetman** [comment]
For those that are interested build 19551 has been released and this now works again
