### ISSUE TITLE
Mouse Lag High DPI

### ISSUE THREAD

**Issue by 2pascal** [mRemoteNG/mRemoteNG#1674]
Pre-release version causes extreme mouse lag, possibly due to high DPI? Connecting from a high DPI, high performance notebook to a desktop PC. Uninstalling and reinstalling stable build.

**Comment by farosch** [comment]
The mouse is controlled by the operating system and nowhere in mRemoteNG do we interfere with it. As you failed to provide the Windows version you are using I also cannot investigate this any further.
There are a variety of problems associated with this, as a quick google search shows this could be something as simple as using a HDMI cable that is not designed to transport HighDPI signals.
