### ISSUE TITLE
How to get old quick connection design ? 

### ISSUE THREAD

**Issue by doyl54** [mRemoteNG/mRemoteNG#1678]
I recently received a new computer on Windows 10 and i used to use mRemoteNg 1.72 (I've always been very happy with this version cause it answered all my needs). 

My problem is on windows 10 and with version 1.72 i can't open 2 RDP sessions to 2 windows server host simultaneously. So i've decided to go on the newer version and i chose version 1.77. 

On this version i can open multiple windows server host connection but i hate the new "Quick Connect" design. 
After entering an address in the quick connect box and hitting enter a protocol selection window came up previously, where I could navigate by the arrow keys to select the desired protocol. I cannot find this option in the most recent version.

Do you have any idea how can i get the older design ? is there an option i missed ? 

This is really boring for me, mRemote is my main tool for working and i'm going to be forced to change my favorite tool... 

If anybody can help...

**Comment by farosch** [comment]
There's no way to "get the older design".
The option to chose your protocol is right next to the textbox, like it always has:
![image](https://user-images.githubusercontent.com/22905106/73386230-d015b080-42ce-11ea-826b-5ba8e26652dd.png)

- Place your cursor in the search box
- Type in the host name
- Hit TAB key
- Use keyboard arrows to set protocol
- Hit ENTER key
