### ISSUE TITLE
confCons.xml connection password is invalid

### ISSUE THREAD

**Issue by jumoog** [mRemoteNG/mRemoteNG#168]
between 5d964f76383a7a57992a290a9954f24c5b4b66a3 and b934e29dc08b60026a87391c69fc464c1734cdf6 happend a error .. 

the connection password is always invalid even after change it and save the connections

**Comment by sparerd** [comment]
I'm replicating as well. Taking a look. May be connected to #166

**Comment by sparerd** [comment]
Was an issue with how the encryption key was being saved within the application session. resolved now, though more cleanup needs to be done.
