### ISSUE TITLE
Feature request: Copy field(s) from connection

### ISSUE THREAD

**Issue by JoostvdB94** [mRemoteNG/mRemoteNG#1681]
It would be great to have the option to copy/type certain fields from the connection into the remote session. 

For example: 
- Click a field in the remote session you want the value to be typed into.
- Right click the connection
- Click option "Type Config Field"
- Select the config field to type
- See that the field value is typed into the field on the remote machine.

Inspiration for this feature was a similar feature in RoyalTS.

**Comment by JoostvdB94** [comment]
As a fix: 
it is possible to do this using a external tool, which copies the fields required to clipboard:
Display Name|Filename|Arguments|
-- | -- | -- | -- | -- | -- | -- | --
Copy hostname+domain | C:\Windows\System32\cmd.exe | /Q /C "ECHO \| SET /P=%Hostname%%Domain%\| CLIP" | 


Hope this can be helpful to someone!
(This feature would still be nice though)

**Comment by farosch** [comment]
@JoostvdB94 Why don't you just simply copy and paste?
Select Hostname field ion connection settings. Press CTRL+C. Enter field in remote sesion. Press CTRL+V

**Comment by farosch** [comment]
Closed due to OP not responding
