### ISSUE TITLE
BUG - Changing Source/Destination Ports on a Reverse Tunnel Crashes the Session

### ISSUE THREAD

**Issue by HatterTheMadd** [mRemoteNG/mRemoteNG#1683]
##  Expected Behavior
You should be able to change the ports without having the session crash.

## Current Behavior
Your session crashes when you change the source port for forwarded ports.

## Possible Solution
\(O.o)/, no idea

## Steps to Reproduce (for bugs)
1) Open a session to server-1 then [right-click] the 'server-1' tab
2) Go to Connections > SSH > Tunnels
3) Input a destination IP and port: 192.168.0.1:443
4) Input a Source port: 7777
5) Select Add
6) Select Apply
7) Open a session to server-1 then [right-click] the 'server-1' tab
8) Go to Connections > SSH > Tunnels
9) Select the Forwarded ports entry: L7777 192.168.0.1:443
10) Select Remove
11) Change Source port : 7778
12) Select Add
13) Select Apply
[Session Will Now Crash]

## Context
We have to restart another session and any <scroll-up>, <putty-session-logs>, and more are lost and a new session is created.
We need to have a single consistent log for each device we connect to for auditing purposes.

## Your Environment
AWS Workspace - WinSvr2016 x64

**Comment by Quietus** [comment]
To add to this - it seems to be a PuttyNG issue.  I can reproduce the issue simply by deleting a tunnel as well and I get the same results if I run PuttyNG outside of mRemoteNG.
As a temporary workaround I have had to set mRemoteNG to use Putty instead.

**Comment by farosch** [comment]
mRemoteNG still uses PuTTY 0.71. Does the original PuTTY in version 0.71 have this issue?
Because if so, #1764 could be the answer

**Comment by Quietus** [comment]
Yes I can reproduce with Putty 0.71 so updating to the latest upstream version should resolve this.

**Comment by Kvarkas** [comment]
PuttyNG has been updated to 0.75.0.1
cant reproduce with new version, please confirm if still facing issues? (have a check with today NB v1.7.2)

**Comment by Quietus** [comment]
I tried to test with the nightly build of mRemoteNG (mRemoteNG.24062021NB.rar - containing mRemoteNG 1.77.2.41427) but this still has PuttyNG 0.71.0.1 within it and as expected, the issue persists.

So I downloaded 0.75 from https://github.com/mRemoteNG/PuTTYNG/releases and tested with that.  Thankfully, as expected, 0.75 does resolve the issue.

**Comment by Kvarkas** [comment]
> 0.75 does resolve the issue.

Super, thanks for confirming such ![ok](http://www.kolobok.us/smiles/standart/friends.gif)
have a mess a bit with archives ![sorry](http://www.kolobok.us/smiles/standart/facepalm.gif)
