### ISSUE TITLE
Feature request: Undocked config panel and context menu

### ISSUE THREAD

**Issue by ramiralez** [mRemoteNG/mRemoteNG#1686]
Please, add "Config" item in context menu of each connection item in "Connections" panel. Clicking on this item must open "Config" panel.

Now, if we using undocked "Config" panel and close it, only way to show it again - toolbar menu. This is not logical.

**Comment by Kvarkas** [comment]
Not sure I got you, could you explain?

**Comment by farosch** [comment]
Closing due to OP not responding.
