### ISSUE TITLE
crash half the time when using the Connect: box

### ISSUE THREAD

**Issue by Rom265** [mRemoteNG/mRemoteNG#1691]
## Current Behavior

Maybe half the time when I use the Connect: box to create a connection, after I hit enter, the program window disappears. mRemoteNG crashes/abends/dies.
I usually use an IP address; so, it might be specific to using an address.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1809 build 17763.973

**Comment by nmat** [comment]
Is there a specific protocol you are using? it would help to get some more information here.

**Comment by Rom265** [comment]
It happens with RDP. I can't think of what more I can say.
