### ISSUE TITLE
Copy and pasting with VM's using mRemote

### ISSUE THREAD

**Issue by newtechdude** [mRemoteNG/mRemoteNG#1697]
I've started using mRemote and am having lots of trouble being able to copy and paste within/out of my Vm's.
I looked through lots of your tickets on github and here and found this to be a solution
https://github.com/mRemoteNG/mRemoteNG/issues/1562

## Expected Behavior
I should be able to copy something within a VM, and be able to past it in my local machine's apps/docs/spreadsheets normall.y 

## Current Behavior
It worked once, but upon the next day's work, I cannot seem to be able to copy and paste again. Now, I cannot take information in/out of a VM using clipboard, despite following the step in the linked article - which tell me to change settings in the 'config' space.

## Steps to Reproduce (for bugs)

1. Open a VM in mRemote
2. copy some data/text/images from a VM's display
3. paste into a word/excel doc in local machine
4.

## Context
Just need to be able to easily attain data in a Vm session

## Your Environment
Currently running mRemote version 1.77.1.27654
on my:
64 bit windows 10, with a coreTM i5-9500
***Thank you in advance :)

**Comment by farosch** [comment]
What kind of protocol are you using?
Have you enabled clipboard redirection?
![image](https://user-images.githubusercontent.com/22905106/83950817-c6c4c380-a82d-11ea-8033-6f54605cd3be.png)

**Comment by newtechdude** [comment]
hey @farosch 
This was submitted in February... I really struggled to work it out. 
The above screenshot you provided indicated something that I knew from some basic research using google. It turned out I had a non-stable version of nRemoteNG - which when I switched to a more recent version, it worked fine.
Still don't know how I could have got it to work.
