### ISSUE TITLE
Export to csv edit add new host and import back not working

### ISSUE THREAD

**Issue by locki-cz** [mRemoteNG/mRemoteNG#1698]
Hi,
my idea was make basic tree structure of folders and subfolders export it to csv and add another hosts etc and import it back. Because I have 500+ connection in Putty connection manager and i want use mRemote because is just better tool!

But my problem is ... every host have generated own id .... and I dont know how it generate it in excel, parrent id make sence and I dont need generate it... becuase i maked basic folder tree.

my host have id:

0f7aaacf-909f-4c44-913b-b7f1ff491926

my idea was use another 

0f7aaacf-909f-4c44-913b-b7f1ff491927
0f7aaacf-909f-4c44-913b-b7f1ff491928 etc but it doesnt works ... when i import that ... i have just empty import folder :( 

Why not need ID and not generate it automaticaly when it missing or can somebody describe how to generate them simple? To be able to edit it in csv in excel? 

Thanks for any kick how to solve it, it make me life easier.

**Comment by kees-z** [comment]
I agree that auto-creation of ID's would ease bulk importing connections.
One way to workaround this, is to create empty host entries before exporting to CSV, like someone posted [here](https://www.reddit.com/r/mRemoteNG/comments/eq6ckj/importing_bulk_connections_for_dummies/).

**Comment by locki-cz** [comment]
Thank you for that link, it helps a lot! Just after save in excel it removed last ; on lines ... i fixed it in pspad with find and replace and all worked fine!

**Comment by farosch** [comment]
This works for me without any problem. I can just generate these IDs myself, as long as they are proper [GUIDs](https://de.wikipedia.org/wiki/Globally_Unique_Identifier)

See this post on how to generate GUIDs with Excel:
https://stackoverflow.com/questions/14990236/how-to-create-a-guid-in-excel
