### ISSUE TITLE
Request for two features: half-fullscreen reserving the taskbar of client & auto-hide notifications tab after successfully connected

### ISSUE THREAD

**Issue by mo-han** [mRemoteNG/mRemoteNG#1699]
My screen's vertical resolution is not high enough, so even when I maximize the mRemote window, the title bar, menu bar, connection tabs and the notifications tab still eat a lot of my screen space, leaving me insufficient height to use. I need to frequently switch between client and remote, so fully fullscreen is not suitable for me. That's basically why I request for this two features.

The "auto-hide notifications tab after successfully connected" one should be easy to understand. Sometimes due to wrong password typed or the network issues, the connecting would fail and there will be some notifications popped up to indicate the errors. But after successfully connecting to the remote, that notifications tab still remains at bottom. I suppose it could be auto removed after successfully login into the remote.

As for the "half-fullscreen", it's simply a maximized window, but without title bar, menu bar and connection tabs, so both of the client's taskbar and the remote taskbar can be disaplyed side by side, and the remote view can be maximum. There should be some kind of control to quit this mode of course, I suggest to put that into the taskbar button preview pannel, which is often used by media play software - they put the media control small button like play, pause, stop, next, prev into the taskbar button preview pannel, which will show up when mouse is hovered on the program's taskbar button.
![图片](https://user-images.githubusercontent.com/9916948/75211978-88485300-57c0-11ea-8291-79b5246b71e3.png)

**Comment by farosch** [comment]
> The "auto-hide notifications tab after successfully connected" one should be easy to understand. Sometimes due to wrong password typed or the network issues, the connecting would fail and there will be some notifications popped up to indicate the errors. But after successfully connecting to the remote, that notifications tab still remains at bottom. I suppose it could be auto removed after successfully login into the remote.

This is already the case in the develop branch.

> As for the "half-fullscreen", it's simply a maximized window, but without title bar, menu bar and connection tabs, so both of the client's taskbar and the remote taskbar can be disaplyed side by side, and the remote view can be maximum. There should be some kind of control to quit this mode of course, I suggest to put that into the taskbar button preview pannel, which is often used by media play software - they put the media control small button like play, pause, stop, next, prev into the taskbar button preview pannel, which will show up when mouse is hovered on the program's taskbar button.

There are a lot of bugs still in this programm and features that would be helpfull to a lot of people and thats what our focus should be on.
Also, you already identified the real problem:
> My screen's vertical resolution is not high enough
This is a physical problem and not a technical - in other words. Get yourself a screen that is big enough for your application. We won't change the UI for everyone just because your screen is too small.
