### ISSUE TITLE
Disable Pop Up Automatic Update Settings first start

### ISSUE THREAD

**Issue by aurelgodin** [mRemoteNG/mRemoteNG#1703]
I want to deploy mremote on our windows 10 computer with SCCM.
I have configured the file "mRemoteNG.exe.config" to disable auto updates.
But when I launch mremote the first time I have the pop-up "Automatic Update Settings" is it possible to deactivate it.

Thanks :)

**Comment by aurelgodin** [comment]
Hello ,

Do you have a solution because I have to deploy the application that all of our posts

Thanks

**Comment by farosch** [comment]
You would have to set both these values in the _mRemoteNG.exe.config_ fie:
- CheckForUpdatesOnStartup
- CheckForUpdatesAsked

It should look like this:
```
<setting name="CheckForUpdatesAsked" serializeAs="String">
  <value>True</value>
</setting>
<setting name="CheckForUpdatesOnStartup" serializeAs="String">
  <value>True</value>
</setting>
```

**Comment by captaineramirez** [comment]
Hello I've got the same issue : #2607
