### ISSUE TITLE
"Build Request" Migration to .Net Core

### ISSUE THREAD

**Issue by lxwulf** [mRemoteNG/mRemoteNG#1705]
I saw that mRemoteNG is based on C# and Powershell both of them have a new framework called .NetCore/powerhsell core which works on Linux, Mac and for sure on Windows. Wouldnt be a nice idea to change to this framework to build also this awesome program on linux and mac?

**Comment by kellcomnet2** [comment]
WinForms are still windows only even with the core frameworks, also the RDP is very COM dependent which is again Windows only.

**Comment by lxwulf** [comment]
thats very sad but rdp connection should over linux or mac because of freerdp or the implementation of remmina? right? or do i completly missunderstanding something?

**Comment by nmat** [comment]
I think its a good idea to check: https://github.com/mRemoteNG/mRemoteNG/issues/308

**Comment by lxwulf** [comment]
thank you for the mentioning! i hope this project go further - it seems to be very nice for alot of us =D

**Comment by farosch** [comment]
The following librarie that we are using are _officially not supported_ in .net core:

*mRemoteNGSPecs*
- BouncyCastle

*mRemoteNG*
- BouncyCastle
- ConsoleControl
- DockPanelSuite
- DockPanelSuite.ThemeVS2003
- DockPanelSuite.ThemeVS2012
- DockPanelSuite.ThemeVS2013
- DockPanelSuite.ThemeVS2015
- ObjectListView.Official
- System.Xml.Linq

The nuget _NUnit.Extensions.Forms_ cannot be found at all. Maybe I'm missing something here...

**Comment by lxwulf** [comment]
Maybe this here helps for the BouncyCastle 🤔 

https://www.nuget.org/packages/BouncyCastle.NetCore/

The other libraries are over my level 😅

**Comment by farosch** [comment]
This will need to be resolved https://github.com/cefsharp/CefSharp/issues/2796

**Comment by lxwulf** [comment]
Very nice this would make many things much easier. We look all forward to that projects and implementations.
