### ISSUE TITLE
SQL  Data deleted

### ISSUE THREAD

**Issue by Fabian-Ha** [mRemoteNG/mRemoteNG#1708]
Hello, 

I set up an MSSQL server and connected it to mRemoteNG, but after a while all my connection data was deleted from the server without me doing anything about it.

Did someone have the same problem or can someone help me?

**Comment by victorsh1968** [comment]
Yes, to me also, and i restored the database and in few minutes again all the data disappeared from the TblCons table.

I don't know what to do now actually....

**Comment by nmat** [comment]
Can you please provide information on version of mremoteng you are using and what howto you followed for the setup?

Please note that the database connection information is experimental still as mentioned in the information for the howtos.

**Comment by victorsh1968** [comment]
Hello,

I'm using version 1.76.20.24615.
I saw the 'experimental' issue but it works great, the change was by enlarging dramatically the team members that use the software.

thank you.

**Comment by nmat** [comment]
@victorsh1968 do you mean it was a short glitch or what happened? Not sure I follow what happened :/

**Comment by Filippo125** [comment]
Hello, sometimes it happens with 1.76, because every change delete and recreate all entries. Please try 1.77 version

**Comment by farosch** [comment]
Closed due to OP not responding.
Also OP failed to give us any reasonable input.
Will reopen if OP decides to respond and file a proper issue.
