### ISSUE TITLE
Intermittent Window/Toolbar Drawing Issues

### ISSUE THREAD

**Issue by dron99999** [mRemoteNG/mRemoteNG#1710]
Occasionally while mRemoteNG has been running for some time I will find it in a state with several drawing issues:

Toolbars/buttons are missing.
The entire 'Config' area is not drawn.
The current active RDP session is drawn at the wrong scale -- components of the guest session are overlapping with where mRemote toolbars / title bar should be.

If I minimize and restore/maximize the mRemoteNG window everything is drawn properly on the screen.

I have not found any specific steps to reproduce other than 'use mRemoteNG for a while until it happens.'  The issue will only start after switching from a different window, not while mRemoteNG is in focus.  It seems independent of how many active sessions/tabs I have open at the time.  No other applications on my system have had any drawing issues.  I do not have another system where I regularly use mRemoteNG.

This is primarily an annoyance, however as I use mRemoteNG as part of sales demos it reflects poorly on me to have GUI issues like this at all, which will likely force me to a different solution here.

## Environment Details
Windows 10 1909 x64
On latest mRemoteNG build as of this post 1.76.20.24615
Display setup varies but has occurred on:
- External UHD monitor connected via displayport
- External FHD monitor connected via displayport
- Laptop built-in UHD display (with and without external monitors also connected)

Screenshot showing issue.  Black/red rectangles are where I have manually obfuscated details of my own systems that I cannot disclose here.  Blue areas are where the active mRemoteNG RDP session was drawn, also obfuscated for security purposes.

![mRemoteNGDraw](https://user-images.githubusercontent.com/61977070/76452161-056ded80-63a7-11ea-82c5-406c5f922ce8.png)

**Comment by farosch** [comment]
> If I minimize and restore/maximize the mRemoteNG window everything is drawn properly on the screen.

This is most likely related to hardware and or drivers on your system - Most likely your graphics card.


- Are all you drivers up to date?
- Does this happen with Windows 10 2004 also?
- Does this happen in the latest Prerelease build?
- Does this also happen when only using the internal monitor? 
- Does this also happen when all diplays are UHD?
- Does your laptop officially support Windows 10?

**Comment by dron99999** [comment]
I looked into all of that.  No hardware issues. Drivers up to date.  And
none of the dozens of other applications I use were affected.

I'm frankly not interested in blaming a laptop or working without an
external monitor for an extended time frame to see if an intermittent issue
appears.

Do you have any other suggestions for troubleshooting where you consider
this software to be the problem and not something else?

**Comment by farosch** [comment]
Since yesterday I am having this kind of error in several programs, but only when running on more than one monitor.
Looks like this could be a problem related to the latest WIndows 10 2004 update.

This is my notepad++ atm:
![notepad++_Mv7WWLW8eV](https://user-images.githubusercontent.com/22905106/86352027-77738680-bc65-11ea-9c78-64ad62a5e6dc.png)
