### ISSUE TITLE
No visible result of generated background bitmap by BGInfo when using a RDP protocol higher than rdc6

### ISSUE THREAD

**Issue by messefilme** [mRemoteNG/mRemoteNG#1716]
On servers BGInfo can be used to draw some useful Information About the Server inside the background image of the Windows Desktop. We are running Windows Server 2012R2 and newer and use this feature to ensure that we are connected to the Right Server and to see e.g. ist boot time.
mRemoteNG 1.77.1.27654 Comes with an Option to specify which RDP protocol Version should be used to connect to Servers. By Default it is set to Rdc6. When trying to choose a higher Version like Rdc8 or "highest" the new RDP session is no longer showing the Background of the Windows Desktop. It just appears black.
The option to show the Background Image is set.
As older versions do not Show this Problem it seems that it was introduced with the possibility choosing the RDP Version.

**Comment by farosch** [comment]
@messefilme 
You have to set the _Display Wallpaper_ option to true when using RDC>v6:
![image](https://user-images.githubusercontent.com/22905106/83328132-1846de80-a281-11ea-8b16-fdd0b38a6069.png)
