### ISSUE TITLE
Language Bar disappears on host when guest is a Windows OS

### ISSUE THREAD

**Issue by techpavan** [mRemoteNG/mRemoteNG#1717]
I use multiple remote sessions. Few being Linux and few Windows Servers. All work well on the host when working with remote Linux, but when Windows is activated, the Language Bar icon in notification area of host disappears. It appears back when the guest session is not in foreground - say I click somewhere else, even within the mRemoteNG, but outside the guest window. This causes problem when I need to click on other apps on host that have any notifications like Outlook. The moment I click on the notification icon, it moves aside as the Language bar icon reappears.

## Expected Behavior
Language bar icon in Windows host should not disappear when Windows guest is activated.

## Current Behavior
The icon disappears when Windows guest is activated, reappears when it is deactivated.

## Steps to Reproduce (for bugs)

1. Configure Windows Host to display Language bar icon in notificatoion area.
2. Configure Windows Guest in mRemoteNG (in my case, its Windows Server 2016 Standard) and connect.
3. Click inside the guest window
4. Language bar icon disappears on host

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 enterprise 1909, 64 bit

**Comment by Pyfhon** [comment]
It seems the problem is not only in mRemoteNG, mstsc does as well.
There is a certain logic in this, but it is really annoying
Env: Windows 10 Pro 1903
