### ISSUE TITLE
The crash att startup, no UI is shown

### ISSUE THREAD

**Issue by mevolution** [mRemoteNG/mRemoteNG#1718]
Running latest windows 10
since this morning it did not start anymore, tried to reinstall but without luck.
The log had no entries from today at all

please find the crashlog attached:

[CrashDumps.zip](https://github.com/mRemoteNG/mRemoteNG/files/4373766/CrashDumps.zip)

**Comment by fatihtashan** [comment]
> Running latest windows 10
> since this morning it did not start anymore, tried to reinstall but without luck.
> The log had no entries from today at all
> 
> please find the crashlog attached:
> 
> [CrashDumps.zip](https://github.com/mRemoteNG/mRemoteNG/files/4373766/CrashDumps.zip)

I had a similar problem for the last 3 days. I uninstalled all versions of .net framework and then installed the latest version. The problem got resolved. Maybe this sloution could help you.

**Comment by farosch** [comment]
There are two possible solutions for this:

1) Your .NET is messed up:
Run Microsoft .NET Framework Repair Tool

2) Your user profile file is messed up:
Delete the user.config file from %LOCALAPPDATA%\The_mRemoteNG_Team\ or simply delete all folders in this path
