### ISSUE TITLE
Feature request: implement "audioqualitymode" for RDP sessions

### ISSUE THREAD

**Issue by creopard** [mRemoteNG/mRemoteNG#172]
Recognizing that the audio quality is quite poor, when listening via remote desktop, I came across the setting "audioqualitymode" for RDP sessions.
To enhance this (if bandwidth is not the issue), it is recommended to set the RDP parameter "audioqualitymode" to "audioqualitymode:i:2".

There are 3 quality setting (that cannot be set within the RDP GUI):

**Dynamic Audio Compression**
`audioqualitymode:i:0`

**Medium Audio Compression**
`audioqualitymode:i:1`

**No Audio Compression**
`audioqualitymode:i:2`

This might be a nice feature for users of mRemoteNG!

**Comment by sparerd** [comment]
Thanks for the suggestion, we will look into it. Looks like this feature was introduced in RDP8, so it is indeed available to us.

**Comment by kmscode** [comment]
Depends on #177 

Since we need to update the schema version, this is the perfect time to add this as a newly configurable parameter. Scheduling for 1.75.

**Comment by infectormp** [comment]
and how i can set `audioqualitymode`?

**Comment by sparerd** [comment]
You must be using version 1.75 Beta 1 (or higher, though that is the current highest version). The RDP connection record must be configured where **Sounds** = `Bring to this computer`. Then the **Sound Quality** option will be available.
