### ISSUE TITLE
Users have to press Alt+Tab twice to switch between application's windows when an SSH connection is open

### ISSUE THREAD

**Issue by diegolagoglez** [mRemoteNG/mRemoteNG#1721]
If an SSH connection is open using mRemoteNG in Windows 10 and the SSH tab has the focus, users have to press Alt+Tab twice to switch to the next application window.

What I think is happening is when the tab has the focus, the first Alt+Tab switch the focus to the mRemoteNG window and the next Alt+Tab switch the focus to the next application window.

## Expected Behavior
Users should press Alt+Tab **only once** to switch to the next window even when an SSH connection is open and the corresponding tab has the focus.

## Current Behavior
Users have to press Alt+Tab **twice** to switch to the next window when the SSH connection tab has the focus.

## Steps to Reproduce (for bugs)
1. Open an SSH connection in a new tab with only one window.
2. Other application should be opened.
3. Press Alt+Tab once to switch to the next application's window: nothing happens. Focus is still in mRemoteNG main window (not the tab).
4. Press Alt+Tab again to switch to the next application's window: it works. Focus is on the next application's window.

## Your Environment
mRemoteNG 1.76.20.24615 (2019-04-12)
Windows 10 Enterprise version 1809 (build 17763.1039)

**Comment by aswzen** [comment]
This is same like https://github.com/mRemoteNG/mRemoteNG/issues/520

**Comment by diegolagoglez** [comment]
> 
> 
> This is same like #520

That's closed but the error is not fixed.

**Comment by sokol-44** [comment]
I have the same problem, workaround works but this should be default behavior not "hack" to make it work.

**Comment by aswzen** [comment]
Still in their to do list bucket

https://github.com/mRemoteNG/mRemoteNG/issues/290

**Comment by farosch** [comment]
Please use #290 to track this issue
