### ISSUE TITLE
Icons blurry in mRemoteNG

### ISSUE THREAD

**Issue by worldsdream** [mRemoteNG/mRemoteNG#1724]
Version: 1.77.1.27713
The text is not blurry, that is great.
The icons are blurry, all of them.

Could not find any bug reported, that's why I am creating this one.

Scale and layout: 125%
Resolution: 1920x1080
Operating System: Windows 10 1909

**Comment by lygoing** [comment]
I feel the same problem, but I think the focus issue is the first priority.

**Comment by farosch** [comment]
Hi @worldsdream could you please post a screenshot so I can identify those icons?

**Comment by farosch** [comment]
Closing as OP is not responding.
