### ISSUE TITLE
HTTP Gecko does not open

### ISSUE THREAD

**Issue by mariowitdoek** [mRemoteNG/mRemoteNG#1731]
I define a HTTP call to a web page on port 8080 with the Gecko engine and it does not open. I tried with the latest and stable release.
I have a windows 10 pro 64 bit (newly installed with latest FireFox) and I tried putting the mozglue.dll in the same map as mRemoteNG.
It worked before the reinstall.

I get this error in the log file:
2020-04-12 11:26:24,286 [1] ERROR - Kon geen nieuwe HTTP verbinding aanmaken!
Poging om een programma te laden met een onjuiste indeling. (Uitzondering van HRESULT: 0x8007000B)
   bij Gecko.Xpcom.Alloc(IntPtr size)
   bij Gecko.nsAString..ctor() in D:\temp\2ea25a5\Geckofx-Core\nsString.cs:regel 883
   bij Gecko.nsAString..ctor(String value) in D:\temp\2ea25a5\Geckofx-Core\nsString.cs:regel 895
   bij Gecko.Xpcom.Initialize(String binDirectory) in D:\temp\2ea25a5\Geckofx-Core\Xpcom.cs:regel 324
   bij mRemoteNG.Connection.Protocol.Http.HTTPBase..ctor(RenderingEngine RenderingEngine) in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\Http\Connection.Protocol.HTTPBase.cs:regel 28
2020-04-12 11:26:24,395 [1] ERROR - Instellen HTTP Eigenschappen mislukt!
Failed to initialize Gecko Rendering Engine.
   bij mRemoteNG.Connection.Protocol.Http.HTTPBase.Initialize() in C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\Protocol\Http\Connection.Protocol.HTTPBase.cs:regel 71

## Expected Behavior
Open a new window on HTTP.

## Current Behavior
No new window and also no message that there was an error. Maybe that can be an adjustment as well.

## Possible Solution
I think it has something to do with 64/32 bit. 
Can the dependency dll's be encorporated in the installation (like in the old days :S)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I want to connect to my router, VM host, switch, ... with HTTP(s) for configuration.

## Your Environment
latest windows 10, clean reinstall

**Comment by mariowitdoek** [comment]
This behaviour has something to do with dependencies or lack of files. I have installed the Visual Studio 2019 Community edition (with just Windows Application C# package) and now I am able to open a webpage.
I will close this issue and this comment can help as a workaround but it may need further investigation (since it was an installation on a clean Windows 10). 
In a way a computer with lot of software (de)installed is more stable than a newly configured.

KUTGS(oftware)

**Comment by psix048** [comment]
For clean install gecko need visual c++ redistr 2013
