### ISSUE TITLE
PuTTYNG 0.71 fails to connect IPv6 through SOCKS

### ISSUE THREAD

**Issue by ophers** [mRemoteNG/mRemoteNG#1733]
Basically, please update PuTTYNG to upstream PuTTY 0.73.
This is a PuTTY bug (that isn't listed on their changes page) in 0.71. It works correctly in 0.73.

I create a SOCKS-5 Proxy session in PuTTY [PuTTY-SOCKS.reg.txt](https://github.com/mRemoteNG/mRemoteNG/files/4494113/PuTTY-SOCKS.reg.txt) (remove the .txt suffix to import).
I then try to connect to a literal IPv6 address (e.g. ```240b:abcd:123:1234::123```).

## Expected Behavior
It should connect :)

## Current Behavior
 I get this error:
![image](https://user-images.githubusercontent.com/11839190/79592736-1666f880-80e3-11ea-8872-7afc3f95ab8b.png)
notice the connection was tried to a "host" consisting of just the first part of the IPv6 address.
Trying to bracket the IPv6 still fails, changing the message just a bit:
![image](https://user-images.githubusercontent.com/11839190/79593466-2af7c080-80e4-11ea-8746-3b09208e8ce7.png)

## Possible Solution
As a workaround I need to do both the following to get it to work:
1. In the SOCKS session set the "Do DNS name lookup at proxy end" to ```No```:
![image](https://user-images.githubusercontent.com/11839190/79594323-7ced1600-80e5-11ea-9be4-9d8f295bde82.png)
2. Bracket the literal IPv6 address.

## Steps to Reproduce (for bugs)
Please see the above.

## Context
Trying to connect via VPN to an internal network available only through a SOCKS 5 proxy.

## Your Environment

* Version used: 1.77.1.27654
* Operating System and version: Windows 10 1909 x64 (OS Build 18363.778)

**Comment by farosch** [comment]
@ophers Does it work with the latest PuTTY release?

**Comment by kmscode** [comment]
Latest pre-release of puttyng is available here:
https://github.com/mRemoteNG/PuTTYNG/releases/tag/0.75.0.1

Closing this issue as it's confirmed to be resolved in PuTTY 0.73.

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
