### ISSUE TITLE
Porque no puedo copiar y pegar con MremoteNG o como habilito esa opcion

### ISSUE THREAD

**Issue by jarroyo77** [mRemoteNG/mRemoteNG#1734]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Benchwork** [comment]
please check your configuration settings and make sure that clipboard is set to Yes 
compruebe sus ajustes de configuración y asegúrese de que el portapapeles esté configurado en Sí 
![image](https://user-images.githubusercontent.com/7304823/81222335-20796a00-8fb2-11ea-800c-78bbf34afd9b.png)

**Comment by RafaelHGBotelho** [comment]
Bug version 1.77.1.
