### ISSUE TITLE
Feature Request: Right click tab to disable interaction with window

### ISSUE THREAD

**Issue by Ezekial711** [mRemoteNG/mRemoteNG#1743]
As a sysdba there are a lot of times where we want to view a window, but right clicking in putty could cause MAJOR problems if we paste something in. Would be awesome to have an option to protect against that by having an option to toggle inputs

**Comment by Benchwork** [comment]
something like this (mockup only)
![image](https://user-images.githubusercontent.com/7304823/81222062-b52f9800-8fb1-11ea-9bd7-b9258d92286e.png)

**Comment by farosch** [comment]
This already is a PuTTY setting:

**Comment by farosch** [comment]
This already is a PuTTY feature:
![image](https://user-images.githubusercontent.com/22905106/82500286-662a4c80-9af3-11ea-86ac-3d0a2a75360d.png)

Configure you PuTTYNG settings from here:
![image](https://user-images.githubusercontent.com/22905106/82500539-d638d280-9af3-11ea-9da2-bfd1a45d84df.png)
