### ISSUE TITLE
Can even open a connection window

### ISSUE THREAD

**Issue by mailtosmyk** [mRemoteNG/mRemoteNG#1744]
Not able to connect to remote server. With putty able.

## Expected Behavior
When click on connection i should see black ssh screen with credentials asking.

## Current Behavior
On click to open connection black screen popup for a second and closed.

## Steps to Reproduce (for bugs)
1. Having putty connection setup and working
2. Create a new connection with ssh2 and putty session as default
3. Click on open connection
4. Nothing happens. Black windows just showing up for a second than closed.

## Your Environment
 Windows 10 x64

!Please add debug window so we can share details from it

**Comment by Benchwork** [comment]
you should be putting your credentials in the connection configurations 
![image](https://user-images.githubusercontent.com/7304823/81219810-57e61780-8fae-11ea-8f54-ab4a82088cc8.png)

does this fix your issue?

**Comment by farosch** [comment]
closed due to op not responding
