### ISSUE TITLE
Hotkey to switch between tabs

### ISSUE THREAD

**Issue by leifnel** [mRemoteNG/mRemoteNG#1746]
I want a hotkey to switch between tabs
## Expected Behavior

Some hotkey to switch netween tabs.
I'm used to alt-tabbing between several putty sessions; I'd like something similar

## Current Behavior

Currently alt-tab switches to the next window, to switch tab I need to lift hands from keyboard and use mouse.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Benchwork** [comment]
this feature would be nice, and to keep with how the tabbed browsers do it, I think ctrl+tab would be the best combo to use.

 just my two cents.

**Comment by romber** [comment]
I think use Right Ctrl as a switch would be great, like VirtualBox / Remmina behavior.
Press Right Ctrl one time, the key would send to remote computer, press Ctrl again, then the key send to local computer.

**Comment by farosch** [comment]
Closing this in favor of #196.
Please use the above isse to add your ideas. No ETA still though, as hotkeys are requested very often and thus need to implement a hotkey system that is useable throughout the whole application,
