### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by journeym** [mRemoteNG/mRemoteNG#1748]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
Yes

**Comment by journeym** [comment]
For anyone interested, there is a new fork that has ACTUAL, WORKING RELEASES check out the fork by robertpopa22 (yes, admin censored links to other githubs :sad: )
