### ISSUE TITLE
Allow for a keyboard shortcut to exit key redirect mode

### ISSUE THREAD

**Issue by doswell** [mRemoteNG/mRemoteNG#1749]
## Expected Behavior
It'd be handy to have a method to get out of the RDP session via a keyboard shortcut when 'key redirect' is enabled. This would allow switching to another local window and switching back without having to use the mouse.  I think VMWare had something similar via hitting CTRL twice very quickly

## Current Behavior
Have to use the mouse to regain key control on the local system when key redirect is enabled.

## Possible Solution
Add some key combination which will be picked up locally, or hitting something ie CTRL,CTRL that is not normally used by anything else.

## Steps to Reproduce (for bugs)
Enable key redirect, open RDP, try and get out of it to control local system with keyboard shortcuts without using the mouse.

## Your Environment
* Version used:
* Win 10, Version 1.76.20.24615

**Comment by farosch** [comment]
I don't think this will ever be implemented as we would need to reconnect the RDP session to do so.
You just need to take care of where your focus is when working with remote system.
