### ISSUE TITLE
Unable to expand MRemoteNG terminal

### ISSUE THREAD

**Issue by lotfiMahmoud** [mRemoteNG/mRemoteNG#1751]
On the latest version currently (1.76.20.24615) at the time of this writing, on mRemoteNg it is impossible to have a console in full screen, each time you open a new session, the window of the console is displayed in the middle but cannot enlarge or change its size.
Is it normal to have this behavior?
Is there a way to fix this problem?

**Comment by farosch** [comment]
closed for voidness

**Comment by freakbsd** [comment]
I confirm this issue on the same version. 
farosch can this be re-opened ? Or should i create a new issue ?
I have some extra info related to this issue, in fact some workaround which is ugly but maybe will help dev team to identify the issue.

**Comment by farosch** [comment]
Hi @freakbsd 
Yes, open a new issue if you have that problem.
**Please** take the time to fill out the issue template, it exists for a reason.
Also as the v1.76 version is very old please verify that the issue still exists in the preview version v1.77
