### ISSUE TITLE
mRemote won't run properly after latest Windows 10 update

### ISSUE THREAD

**Issue by voltz5000** [mRemoteNG/mRemoteNG#1755]
I've been using mRemote for years and it's awesome.  

After I installed the latest Windows 10 update windows won't bring up the user interface.  It will just run in the background (task manager).

Tried uninstalling mremote, restarting, tried installing the latest unstable version.

**Comment by dmalyshok** [comment]
Hi!

Rename %APPDATA%\mRemoteNG\
or AppData\Local\mRemoteNG. I have too issue with this

**Comment by voltz5000** [comment]
Thanks, but still the UI doesn’t load up it only runs in the background task manager.

**Comment by farosch** [comment]
Sounds like a corrupted user file. Delete this file:

Installed Version
%LOCALAPPDATA%\mRemoteNG\<most recently updated folder>\<mRemoteNG version>\user.config

Portable Version
%APPDATA%\mRemoteNG\<most recently updated folder>\<mRemoteNG version>\user.config
