### ISSUE TITLE
 Cannot type any character on MultiSSH toolbar

### ISSUE THREAD

**Issue by plkamote** [mRemoteNG/mRemoteNG#1756]
I would like to ask if there is config need to change as I cannot type any character on MultiSSH toolbar? 

I am using MremoteNG version 1.77.1.27654

**Comment by farosch** [comment]
Was not really a bug but a feature... A poor one though.
You were only allowed to type into the MultiSSH Toolbar whenever at least one PuTTY/SSH session were open. Otherwise the method yould just return.
Fixed that behaviour.
