### ISSUE TITLE
unable to connect to VM

### ISSUE THREAD

**Issue by alihamzane** [mRemoteNG/mRemoteNG#1757]
I'm using mRemoteNG to connect to several VM from a stepping stone server, it was working fine until recently I get an error message (couldn't save connextions file...)

## Expected Behavior
 when I connect on a specefic server, I should get the authentication interface of that server.

## Current Behavior
 I get the attached error 
![error mRemoteNG](https://user-images.githubusercontent.com/65599928/82429149-fe381f80-9a7a-11ea-8fa9-e092c8963274.jpg)

## Context
 multiple connection using RDP is difficule to manage, mRemouteNG allows to switch easily between different servers (time saving).

## Your Environment

* Version used: mRemoteNG version 1.76.19.35762
* Operating System and version (e.g. Windows 10 1709 x64): 
- source server : Windows server 2016 (from which I connect to other servers)
- target servers : Windows server 2008/ 2008R2 / 2012

**Comment by farosch** [comment]
@alihamzane You dont Have write permission to the path displayed in the error message.
Check your permissions on that folder or chose another destination.
