### ISSUE TITLE
UI bugs (quick connect text box and drop-down menus)

### ISSUE THREAD

**Issue by iSteph77** [mRemoteNG/mRemoteNG#176]
Hello guys,

I encountered few UI bugs with the quick connect text box and drop-down menus :
1) When the focus is on the putty window session, I can't edit the quick connect text box when I click on it.
I have to click on the connections panel, config panel or main window (title bar) to be able to edit the text box.
It only happens with putty sessions, no problem with RDP sessions.
I didn't have this issue with 1.72 or 1.73.

2) With both RDP and putty sessions if I click on File, View, Tools, Help, Protocol button (quick connect) or Connections button (quick connect), it opens a drop-down list/menu.
If I click back on the RDP or putty session, it doesn't close the drop-down list and it stays opened until I click on it again. 

|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.74 |

You can close issue MR-941 :)
Steph

**Comment by kmscode** [comment]
Hi Steph! We didn't forget about the JIRA bugs... Just haven't had the time to get to most of them. We are working them down as best we can! Slowly migrating to GH issues for better integration with other things that we're doing. Will get to this one ASAP. Thanks!

**Comment by dragoninwater** [comment]
I too have encountered issues with the quickconnect in version 1.74.6023.x but have not in 1.72 or 1.73. 
I'm unable to type or edit the "Connect:" entry field with a hostname/IP address intermittently.

Only workaround in the interim has been to select "View" in the menu and then unselect the quickconnect toolbar and reselct it again. Very cumbersome workaround but at least doable in the interim while we wait for a bug fix.

**Comment by quangnhut123** [comment]
So how long thats bug will be fixed ? i waiting for this bug because everyday i use quick connect section !

**Comment by ouberlord** [comment]
I'm happy that someone else has already reported this bug; I only began to have it once I started using a mix of SSH2 and RDP tabs and now it's driving me nuts.  Also glad to hear that this is already a known issue and is being worked on.

**Comment by varnar** [comment]
I have switched to 1.7.2.5065.32737 and it works perfect for me
Also, I noticed that the window moving is faster.
Also, if I need to click on Title Bar -  it works as expected, in the latest version I need to click exactly on the "mRemoteNG" text on the title bar.

Thanks for application

**Comment by mrwulf** [comment]
Not sure why it didn't link, but PR #651 addresses this bug.

**Comment by sparerd** [comment]
Merged fix provided by @mrwulf. This will be available in the next patch
