### ISSUE TITLE
Update PuTTY

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#1764]
PuTTY needs to be updated to the latest version ~~0.73~~ 0.74

This should fix #1733

**Comment by kmscode** [comment]
Sorry for the long absence. Life... I'll see if I can get this done within the next week or so.

**Comment by benwa** [comment]
Just a note, 0.74 is out now

**Comment by lukeattard** [comment]
Just to confirm are you meaning the putty binary that is part of the repo or are you suggesting code needs to be updated?

If it is the binary, download the binary from putty and copy it into your install directory, or use the custom path option in the settings?

**Comment by farosch** [comment]
@lukeattard It's not as simple as that. The changes from the PuTTY repo need to be merged into our own fork of PuTTY (https://github.com/mRemoteNG/PuTTYNG)

**Comment by userjohn808** [comment]
> 
> 
> @lukeattard It's not as simple as that. The changes from the PuTTY repo need to be merged into our own fork of PuTTY (https://github.com/mRemoteNG/PuTTYNG)

Hello,
any time line on when the latest version putty will be merged with the mRemoteNG PuttyNG version?
Thanks.

**Comment by kmscode** [comment]
Latest pre-release of puttyng is available here:
https://github.com/mRemoteNG/PuTTYNG/releases/tag/0.75.0.1

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemote stable build.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
