### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by Neustradamus** [mRemoteNG/mRemoteNG#1765]
A new release is possible with fixes?

For example not updated since several versions:
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

More one year after the last stable:
- https://github.com/mRemoteNG/mRemoteNG/releases

**Comment by farosch** [comment]
Closed for voidness.
This is not an issue.

**Comment by Neustradamus** [comment]
@farosch: Any news about this problem since one year after last devel build?

**Comment by farosch** [comment]
Nope, sadly not.
I need @sparerd or @kmscode to publish a new release but haven't heard from them in month....

**Comment by Neustradamus** [comment]
Any news?

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2271
- https://github.com/mRemoteNG/mRemoteNG/issues/2441
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2458
- https://github.com/mRemoteNG/mRemoteNG/issues/2474

**Comment by Neustradamus** [comment]
4 years after my request, this ticket is always not solved.

**Comment by Kvarkas** [comment]
I don't depend on user requests, even I am interested in feedbacks (btw preview team leaved project because of such psychologic pressure) I am strong enoght for such :) so I will release once I will be happy with functionality, stay tuned! 
p.s. If you wish things happened sooner - welcome to do commits! :)
