### ISSUE TITLE
Some small suggestions

### ISSUE THREAD

**Issue by azbo** [mRemoteNG/mRemoteNG#1768]
![image](http://user-images.githubusercontent.com/5110699/82888425-da457400-9f7b-11ea-8465-f02856d86290.png)

**Comment by azbo** [comment]
![image](https://user-images.githubusercontent.com/5110699/82888562-0bbe3f80-9f7c-11ea-87d2-131795b84fa0.png)

**Comment by azbo** [comment]
![image](http://user-images.githubusercontent.com/5110699/82888594-1bd61f00-9f7c-11ea-8ab2-a2738ae10eba.png)

**Comment by farosch** [comment]
You are just showing me pictures of some app that is not mremoteNG?
The fuck am I supposed to do with this?
