### ISSUE TITLE
Support for window animation and content dragging in RDP

### ISSUE THREAD

**Issue by djkrose** [mRemoteNG/mRemoteNG#1770]
Windows Remote Desktop Connection dialog contains two performance setting that are not available in mRemoteNG:

 - Show window contents while dragging
 - Menu and window animation

![rdp](https://user-images.githubusercontent.com/30222867/82897078-55e0fa00-9f57-11ea-925d-73339fa0faaf.png)

They are implicitly on in mRemoteNG and cannot be turned off.

The feature request is to add support for those options in mRemoteNG to allow turning them off individually.

This was also mentioned in a comment here, but not picked up as feature request:
https://github.com/mRemoteNG/mRemoteNG/pull/1498#issuecomment-504933071

**Comment by farosch** [comment]
There are two more properties:
 - DisableCursorShadow
 - DisableCursorBlinking

**Comment by farosch** [comment]
@djkrose I have created a branch where these settings are implemented.
Would you be willing to test it?
You can pull the Artifacts from here:
[Installer](https://ci.appveyor.com/project/mremoteng/mremoteng/builds/33131707/job/52iu2fahtqw7pbkl/artifacts) [Portable ](https://ci.appveyor.com/project/mremoteng/mremoteng/builds/33131707/job/mm8fkyxhio4gaprq/artifacts)

**Comment by djkrose** [comment]
I tested
- disable window dragging
- disable window animation
- disable cursor shadow
and they work!

I don't know exactly what _disable cursor blinking_ is and the option is broken in config (duplicate cursor shadow instead) at least in my German language setup.
![mremote](https://user-images.githubusercontent.com/30222867/82993565-153dbb00-a001-11ea-825f-862db8da35e2.png)

**Comment by farosch** [comment]
Hey @djkrose 
Thank you very much for the (fast) feedback. I am very confident that the disable cursor blinking-property will also work, as it is implemented exectly the same way as these other options are.
I couldn't find any proper information on this settings though - Not even Microsoft seems to list the value anymore (https://docs.microsoft.com/de-de/windows-server/remote/remote-desktop-services/clients/rdp-files). My wild guess is that it is an old rdp relict that is only used by very old Windows systems, that have reached EOL by now and thus it's not documented anymore. ¯\_(ツ)_/¯
I'm gonna leave it in non the less...

As for the wrong translation it seems like there already existed translation entries for some of those properties that got forgotten in the code. I cleaned those up
