### ISSUE TITLE
Version Hashes

### ISSUE THREAD

**Issue by Arkanyus** [mRemoteNG/mRemoteNG#1771]
Is anyone aware of a way for me to get the SHA256 of every version of mRemoteNG reasonably easily?

**Comment by farosch** [comment]
For the moment, checksums are currently available in the following places (depending on update channel and edition):

https://mremoteng.org/update.txt
https://mremoteng.org/update-portable.txt
https://mremoteng.org/beta-update.txt
https://mremoteng.org/beta-update-portable.txt
https://mremoteng.org/dev-update.txt
https://mremoteng.org/dev-update-portable.txt

They will be available directly on the downloads page in the future, see #1449

**Comment by Arkanyus** [comment]
As far as I could see that was only the latest version and a SHA512. Is there a way getting of previous versions and a SHA256?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
