### ISSUE TITLE
组件检查，ICA检查说明存在错别字

### ISSUE THREAD

**Issue by HashimotoSakura** [mRemoteNG/mRemoteNG#1780]
## Expected Behavior
启用ICA需要提前安装 XenDesktop Online 插件，并正确注册wfica.ocx库文件。您可以在此下载此插件：http://www.citrix.com/download/
如果您已安装 XenDesktop Online 插件，但仍旧检测失败，请手动注册 wfica.ocx 。
## Current Behavior
启用ICA需要提前安装 XenDesktop Online 插件，并正确注册wfica.ocx库文件。您可以在此下载此插件：http://www.citrix.com/download/
如果您已安装 XenDesktop Online 插件，但人就检测失败，请手动注册 wfica.ocx 。
## Possible Solution
修改成仍旧

**Comment by farosch** [comment]
ICA ని సక్రియం చేయడానికి, మీరు ముందుగానే XenDesktop ఆన్‌లైన్ ప్లగ్-ఇన్‌ని ఇన్‌స్టాల్ చేసి, లైబ్రరీ ఫైల్ wfica.ocx ను సరిగ్గా నమోదు చేసుకోవాలి. మీరు ఈ ప్లగ్‌ఇన్‌ను ఇక్కడ డౌన్‌లోడ్ చేసుకోవచ్చు: http://www.citrix.com/download/
మీరు XenDesktop ఆన్‌లైన్ ప్లగ్-ఇన్‌ని ఇన్‌స్టాల్ చేసినప్పటికీ పరీక్ష ఇంకా విఫలమైతే, wfica.ocx ను మానవీయంగా నమోదు చేయండి.

ప్రస్తుత ప్రవర్తన
ICA ని సక్రియం చేయడానికి, మీరు ముందుగానే XenDesktop ఆన్‌లైన్ ప్లగ్-ఇన్‌ని ఇన్‌స్టాల్ చేసి, లైబ్రరీ ఫైల్ wfica.ocx ను సరిగ్గా నమోదు చేసుకోవాలి. మీరు ఈ ప్లగ్‌ఇన్‌ను ఇక్కడ డౌన్‌లోడ్ చేసుకోవచ్చు: http://www.citrix.com/download/
మీరు XenDesktop ఆన్‌లైన్ ప్లగ్-ఇన్‌ని ఇన్‌స్టాల్ చేసి ఉంటే, కానీ వ్యక్తుల గుర్తింపు విఫలమైతే, wfica.ocx ను మానవీయంగా నమోదు చేయండి.

సాధ్యమైన పరిష్కారం
నిశ్శబ్దంగా మార్చబడింది
