### ISSUE TITLE
mRemoteNg adds 'g' to keyboard buffer when MS Teams banner popup occurs

### ISSUE THREAD

**Issue by padillah** [mRemoteNG/mRemoteNG#1782]
When using mRemoteNg and a MS Teams Banner notification popsup a 'g' will be typed in the remote VM.

## Expected Behavior
Nothing.

## Current Behavior
A single 'g' is typed in the active remote VM.

## Steps to Reproduce (for bugs)
Start MS Teams. It does not matter if this is before or after making a remote connection.
1. Connect to a remote machine via mRemoteNg
2. Open a text editor (or, in fact, anything that will allow text input. Browser URL input, settings text box, anything)
3. Have someone send a chat that would cause a Banner notification.
4. Observe the 'g' in the text.

## Context
This has caused several syntax errors in various code files I've written. It will mess up URLs, settings... any text inout you happen to be making at the time.

## Your Environment

* Version used: 1.77.1.27654
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Home
Surface Pro X (Microsoft SQ1 16Gb/256Gb)

**Comment by farosch** [comment]
Hi @padillah 
I cannot reproduce this. Neither with RDP nor SSH.
**The Windows Version you are using has reached end of life on the 9th April of 2019.**
Please update to the most recent Version and report back if the problem still exists.
