### ISSUE TITLE
Windows 7 installation blocked

### ISSUE THREAD

**Issue by brian2github** [mRemoteNG/mRemoteNG#1795]
## Expected Behavior
I am hoping to install this on my Windows 7, and whatever happens happens.
Can I bypass this KB check which is faulty (it is describing a KB that I can't install - when I try to install it, it says "this update is not applicable to your computer".

## Current Behavior
I am blocked from installing, it says I need KB2574819, but when I try to install this KB, it says "this update is not applicable to your computer".

I am using RDP every day for work, and have no problems.  I RDP over VPN connection.  I would like to bypass this KB check and if it doesn't work so be it.

## Possible Solution
Can I bypass this check with a MSIEXEC property?  Or a fake registry entry?

## Context
I am using mRemoteNG at work, and it is handy for keeping profiles for each server I connect to.  I want to use it at home, but I am on Windows 7.  I have no problem using RDP, so I just want to bypass this installation blocker.

## Your Environment
Windows 7 SP 1

**Comment by kmscode** [comment]
This should allow you to install:

msiexec /i C:\Path\To\mRemoteNG-Installer.msi IGNOREPREREQUISITES=1

Or you can use the portable version.

Windows 7 is fully end of life at this point. Future builds will not be tested against Windows 7 at all. Bugs that are Windows 7 specific will not be addressed.

Reference:
https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020
