### ISSUE TITLE
Feature Request: Config location in GUI

### ISSUE THREAD

**Issue by kcmazie** [mRemoteNG/mRemoteNG#1799]
I like to save multiple copies of my config file as backups.  It would be nice to see the path displayed  somewhere within the GUI that the currently loaded config.xml file is using.

**Comment by Benchwork** [comment]
this funtion is already there

![image](https://user-images.githubusercontent.com/7304823/85938626-05094c00-b8dd-11ea-819f-30f55f0b259e.png)

**Comment by Kvarkas** [comment]
please enable corresponding option for that. 
Version 1.76.20
