### ISSUE TITLE
mremote error

### ISSUE THREAD

**Issue by yannledu** [mRemoteNG/mRemoteNG#1812]
[
![image](https://user-images.githubusercontent.com/67790255/86471144-15865000-bd3d-11ea-8834-3224306e724e.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by farosch** [comment]
Closed for voidness, also this is a problem with your local computers COM classes.
Google the error message to get some tips on how to solve this:
https://www.google.com/search?q=regdb_e_classnotreg&rlz=1C1GTPM_enDE877DE877&oq=regdb_e&aqs=chrome.1.69i57j0l7.2864j0j7&sourceid=chrome&ie=UTF-8
