### ISSUE TITLE
"Report a bug" doesn't render correctly

### ISSUE THREAD

**Issue by chrwei** [mRemoteNG/mRemoteNG#1815]
Clicking the Report a Bug menu opens a tab in mRemoteNG, that tab is using IE7 rendering mode and so renders in an unusable state.

You can set a registry key to ask the web control to use a newer IE mode https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330730(v=vs.85)?redirectedfrom=MSDN#browser_emulation

but since this opens github, which requires login, the more sensible and easier option to implement is to Process.Start() the URL so the users preferred browser and existing github session can be used.

**Comment by farosch** [comment]
I guess you are running an old version of mRemoteNG.
Clicking on "Report a bug" simply opens github in your default browser.
Actually it runs something similar to:
`Process.Start("http://www.github.com/")`

**Comment by chrwei** [comment]
i have 1.76.20.  latest stable is old?

**Comment by chrwei** [comment]
ok, i see it in the change log for the prereleases, so fixed in a future stable version

**Comment by farosch** [comment]
Yeah, unfortunately I cannot push new releases as I need @sparerd to do so.
Hopefully there will be a new stable release soon, or at least a new preview build.
