### ISSUE TITLE
MSSQL database script fails to configure required tables

### ISSUE THREAD

**Issue by emnavarro02** [mRemoteNG/mRemoteNG#1819]
The MSSQL database script for configuring the tables fails when executed and presents the following error:

```
Msg 2716, Level 16, State 1, Line 16
Column, parameter, or variable #25: Cannot specify a column width on data type tinyint.
```

## Expected Behavior
The expected behavior would be configuring the databases properly.

## Possible Solution
A possible solution would be changing the following line
https://github.com/mRemoteNG/mRemoteNG/blob/a9b1d84b6e418f7dc36ea5fc75215e58286337a8/mRemoteNG/Documentation/mssql_db_setup.sql#L41

to 
```
 [Favorite] tinyint NOT NULL, 
```

## Steps to Reproduce (for bugs)

1. Create a new database on MSSQL Server named mRemoteNG
2. Excute the script `mssql_db_setup.sql` on this database

## Context
I'm trying to configure mRemoteNG to use SQL Server. 
I created a new database named mRemoteNG in MSSQL Server 2017 Express. After that I copied the code of the script `mssql_db_setup.sql` to a new query tab on Management Studio and executed it. The management studio returned the above-mentioned error. 

To workaround this error I had to change line 41 and remove the number between parenthesis `(1)`

## Your Environment

* Version used:
* Microsoft Windows 10 [Version 10.0.19041.329]
* MSSQL Server 2017 Express Edition

**Comment by hubb3r** [comment]
i have same problem.
win 10 1903
mssql express 2019
mremoteNG 1.76.20.24615

if i delete string [Favorite] tinyint NOT NULL, 
script run without errors.

but if 
i use  script from help inside programm - all ok
which script is current?

script from help
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[tblCons]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblCons]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[tblRoot]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblRoot]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[tblUpdate]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblUpdate]
GO

CREATE TABLE [dbo].[tblCons] (
	[ID] [int] IDENTITY (1001, 1) NOT NULL ,
	[ConstantID] [varchar] (128) NULL ,
	[PositionID] [int] NOT NULL ,
	[ParentID] [varchar] (128) NULL ,
	[LastChange] [datetime] NOT NULL ,
	[Name] [varchar] (128) NOT NULL ,
	[Type] [varchar] (32) NOT NULL ,
	[Expanded] [bit] NOT NULL ,
	[Description] [varchar] (1024) NULL ,
	[Icon] [varchar] (128) NOT NULL ,
	[Panel] [varchar] (128) NOT NULL ,
	[Username] [varchar] (512) NULL ,
	[DomainName] [varchar] (512) NULL ,
	[Password] [varchar] (1024) NULL ,
	[Hostname] [varchar] (512) NULL ,
	[Protocol] [varchar] (32) NOT NULL ,
	[PuttySession] [varchar] (128) NULL ,
	[Port] [int] NOT NULL ,
	[ConnectToConsole] [bit] NOT NULL ,
	[UseCredSsp] [bit] NOT NULL ,
	[RenderingEngine] [varchar] (10) NULL ,
	[ICAEncryptionStrength] [varchar] (32) NOT NULL ,
	[RDPAuthenticationLevel] [varchar] (32) NOT NULL ,
	[RDPMinutesToIdleTimeout] [int] NOT NULL,
	[RDPAlertIdleTimeout] [bit] NOT NULL,
	[Colors] [varchar] (32) NOT NULL ,
	[Resolution] [varchar] (32) NOT NULL ,
	[DisplayWallpaper] [bit] NOT NULL ,
	[DisplayThemes] [bit] NOT NULL ,
	[EnableFontSmoothing] [bit] NOT NULL ,
	[EnableDesktopComposition] [bit] NOT NULL ,
	[CacheBitmaps] [bit] NOT NULL ,
	[RedirectDiskDrives] [bit] NOT NULL ,
	[RedirectPorts] [bit] NOT NULL ,
	[RedirectPrinters] [bit] NOT NULL ,
	[RedirectSmartCards] [bit] NOT NULL ,
	[RedirectSound] [varchar] (64) NOT NULL ,
	[SoundQuality] [varchar] (20) NOT NULL,
	[RedirectKeys] [bit] NOT NULL ,
	[Connected] [bit] NOT NULL ,
	[PreExtApp] [varchar] (256) NULL ,
	[PostExtApp] [varchar] (256) NULL ,
	[MacAddress] [varchar] (32) NULL ,
	[UserField] [varchar] (256) NULL ,
	[ExtApp] [varchar] (256) NULL ,
	[VNCCompression] [varchar] (10) NULL ,
	[VNCEncoding] [varchar] (20) NULL ,
	[VNCAuthMode] [varchar] (10) NULL ,
	[VNCProxyType] [varchar] (20) NULL ,
	[VNCProxyIP] [varchar] (128) NULL ,
	[VNCProxyPort] [int] NULL ,
	[VNCProxyUsername] [varchar] (512) NULL ,
	[VNCProxyPassword] [varchar] (1024) NULL ,
	[VNCColors] [varchar] (10) NULL ,
	[VNCSmartSizeMode] [varchar] (20) NULL ,
	[VNCViewOnly] [bit] NOT NULL ,
	[RDGatewayUsageMethod] [varchar] (32) NOT NULL ,
	[RDGatewayHostname] [varchar] (512) NULL ,
	[RDGatewayUseConnectionCredentials] [varchar] (32) NOT NULL ,
	[RDGatewayUsername] [varchar] (512) NULL ,
	[RDGatewayPassword] [varchar] (1024) NULL ,
	[RDGatewayDomain] [varchar] (512) NULL ,
	[InheritCacheBitmaps] [bit] NOT NULL ,
	[InheritColors] [bit] NOT NULL ,
	[InheritDescription] [bit] NOT NULL ,
	[InheritDisplayThemes] [bit] NOT NULL ,
	[InheritDisplayWallpaper] [bit] NOT NULL ,
	[InheritEnableFontSmoothing] [bit] NOT NULL ,
	[InheritEnableDesktopComposition] [bit] NOT NULL ,
	[InheritDomain] [bit] NOT NULL ,
	[InheritIcon] [bit] NOT NULL ,
	[InheritPanel] [bit] NOT NULL ,
	[InheritPassword] [bit] NOT NULL ,
	[InheritPort] [bit] NOT NULL ,
	[InheritProtocol] [bit] NOT NULL ,
	[InheritPuttySession] [bit] NOT NULL ,
	[InheritRedirectDiskDrives] [bit] NOT NULL ,
	[InheritRedirectKeys] [bit] NOT NULL ,
	[InheritRedirectPorts] [bit] NOT NULL ,
	[InheritRedirectPrinters] [bit] NOT NULL ,
	[InheritRedirectSmartCards] [bit] NOT NULL ,
	[InheritRedirectSound] [bit] NOT NULL ,
	[InheritSoundQuality] [bit] NOT NULL,
	[InheritResolution] [bit] NOT NULL ,
	[InheritUseConsoleSession] [bit] NOT NULL ,
	[InheritUseCredSsp] [bit] NOT NULL ,
	[InheritRenderingEngine] [bit] NOT NULL ,
	[InheritICAEncryptionStrength] [bit] NOT NULL ,
	[InheritRDPAuthenticationLevel] [bit] NOT NULL ,
	[InheritRDPMinutesToIdleTimeout] [bit] NOT NULL,
	[InheritRDPAlertIdleTimeout] [bit] NOT NULL,
	[InheritUsername] [bit] NOT NULL ,
	[InheritPreExtApp] [bit] NOT NULL ,
	[InheritPostExtApp] [bit] NOT NULL ,
	[InheritMacAddress] [bit] NOT NULL ,
	[InheritUserField] [bit] NOT NULL ,
	[InheritExtApp] [bit] NOT NULL ,
	[InheritVNCCompression] [bit] NOT NULL, 
	[InheritVNCEncoding] [bit] NOT NULL ,
	[InheritVNCAuthMode] [bit] NOT NULL ,
	[InheritVNCProxyType] [bit] NOT NULL ,
	[InheritVNCProxyIP] [bit] NOT NULL ,
	[InheritVNCProxyPort] [bit] NOT NULL ,
	[InheritVNCProxyUsername] [bit] NOT NULL ,
	[InheritVNCProxyPassword] [bit] NOT NULL ,
	[InheritVNCColors] [bit] NOT NULL ,
	[InheritVNCSmartSizeMode] [bit] NOT NULL ,
	[InheritVNCViewOnly] [bit] NOT NULL ,
	[InheritRDGatewayUsageMethod] [bit] NOT NULL ,
	[InheritRDGatewayHostname] [bit] NOT NULL ,
	[InheritRDGatewayUseConnectionCredentials] [bit] NOT NULL ,
	[InheritRDGatewayUsername] [bit] NOT NULL ,
	[InheritRDGatewayPassword] [bit] NOT NULL ,
	[InheritRDGatewayDomain] [bit] NOT NULL ,
	[LoadBalanceInfo] [varchar] (1024) NULL ,
	[AutomaticResize] [bit] NOT NULL DEFAULT 1 ,
	[InheritLoadBalanceInfo] [bit] NOT NULL DEFAULT 0 ,
	[InheritAutomaticResize] [bit] NOT NULL DEFAULT 0
) ON [PRIMARY]
GO
 
CREATE TABLE [dbo].[tblRoot] (
	[Name] [varchar] (2048) NOT NULL ,
	[Export] [bit] NOT NULL ,
	[Protected] [varchar] (4048) NOT NULL ,
	[ConfVersion] [float] NOT NULL 
) ON [PRIMARY]
GO
 
CREATE TABLE [dbo].[tblUpdate] (
	[LastUpdate] [datetime] NULL 
) ON [PRIMARY]
GO
