### ISSUE TITLE
Feature Request: Use defeault browser instead of embedded browser

### ISSUE THREAD

**Issue by bveldkamp** [mRemoteNG/mRemoteNG#1832]
I'd like to have an option where any hyperlink (e.g. Help → Website, Help → Donate, etc) would open in my default browser instead of the embedded (IE?) browser.

**Comment by VShawn** [comment]
?
when i click <kbd>help</kbd>-><kbd>website</kbd>, it did open https://www.mremoteng.org/ in my chrome.

Version 1.77.1.27713

**Comment by bveldkamp** [comment]
That's strange, is there already a setting that I overlooked? For me it
opens a new tab with that page.

Op za 15 aug. 2020 18:12 schreef VShawn <notifications@github.com>:

**Comment by VShawn** [comment]
no idea, for me i using the default setting

**Comment by jvleeuwe** [comment]
That is solved in the Prerelease (1.77) version.
See: [#1223 ](https://github.com/mRemoteNG/mRemoteNG/pull/1223)

**Comment by Kvarkas** [comment]
That working exactly from 1.77.1 > 
I don't like idea making browser from our connection manager too, so external browser is best way to do it.
