### ISSUE TITLE
Feature request : add DEV server icon

### ISSUE THREAD

**Issue by stef1811** [mRemoteNG/mRemoteNG#1835]
It will be useful (for me at least) to have a dev server icon in addition to the Test server icon

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by johny2015** [comment]
You can add your own custom icons in mRemoteNG... just copy your *.ico file (16x16 size) to appropriate folder (in my case it is: c:\Program Files (x86)\mRemoteNG\Icons\). HTH.

**Comment by Kvarkas** [comment]
I thinking in version 1.8 will be possible to assign a tags to connections. Adding more icons to default install package for me seems useless. Perhaps will be additional icon pack to add - not sure, will see.
