### ISSUE TITLE
ClusterSHISH no longer recognizes PuTTy sessions in mRemoteNG

### ISSUE THREAD

**Issue by penguinairlines** [mRemoteNG/mRemoteNG#1838]
## Expected Behavior
When mRemoteNG SSH2 sessions are active, and ClusterSHISH v0.17 is open, should be able to select the shell and use the ClusterSHISH hotkey Ctrl+Alt+M to add a new shell to control. Alternatively, in ClusterSHISH you should be able to click File > Find all PuTTies. 

## Current Behavior
Neither method discover/select any PuTTy shells managed by mRemoteNG

## Possible Solution
I know this used to work a couple years back, but I use the tool somewhat infrequently and not sure of an exact date it failed, but I suspect there must be a change in mRemote's implementation of PuTTy, or a change in Windows, that prevents these shells from looking exactly like it expects from a PuTTy shell. 

Alternatively, extend "Multi SSH" function to be able to select certain open shells, rather than blindly broadcasting the command to all shells. Command history would be nice to see also. 

## Steps to Reproduce (for bugs)
1. Install mRemoteNG and download the portable executable ClusterSHISH.exe
2. Open 1 or more SSH shells in mRemote. Feel free to open in PuTTy as well to validate what it should look like.
3. Use either the hotkey Ctrl+Alt+M or File > Find all PuTTies.

## Context
Prevents select multi-shell command capabilities. Multi SSH toolbar can do this, but I don't know how to select only certain open shells rather than broadcasting to all. Would be nice to make use of existing structures such as Panels to modify the broadcast scope.

## Your Environment
I tried this on both machines. In both cases I am using version 1.76.20 (2019-04-12)
1 machine is Win10 1809 and 1 is Win10 1909

**Comment by farosch** [comment]
There is no way for us to investigate this, as ClusterSHISH is closed source.
mRemoteNG uses a modified version of PuTTY (https://github.com/mRemoteNG/PuTTYNG). That is most likely the reason that File > Find all PuTTies isn't working.
Using Ctrl+Alt+M is working fine for me though.

We will not investigate the compatibility with ClusterSHISH any further, as the current goal is to replace PuTTY with SSH.NET (#181 )

> Alternatively, extend "Multi SSH" function to be able to select certain open shells, rather than blindly broadcasting the command to all shells. Command history would be nice to see also.

Please make a separate issue if you would like to see this implemented

**Comment by penguinairlines** [comment]
Thanks farosch, this is good insight. Regarding the Multi SSH toolbar, I'll consider opening an enhancement with some more color on this feature request.
