### ISSUE TITLE
Add use of accounts for easier use with multiple servers

### ISSUE THREAD

**Issue by Anders-Ryden** [mRemoteNG/mRemoteNG#1841]
I use nRemoteNG to connect to a large number of different server environments each with a multitude of servers and use the ability to save username ans password in the config.

Howerever, when a change of password has been made (which happens more and more frequently) all connections have to be updated manually.

I'd like the ability of saving the user credentials as an "Account" and then assign that account to the connections, somewhat akin to External Tools.

That would let me update password, and Username or Domain for that matter, in a single place and it will affect all the connections that use the account.

## Expected Behavior
To only have to update a password once

## Current Behavior
Update password for every connection

## Possible Solution
Add new option, Account, under Tools where you have the following fields
-Display Name
-User Name
-Password
-Domain

Add new field Account under Config/Connections.

If user credentials are entered in this section, those will be used.
If instead Account has a value the credentials from Account will be used.

To have both should probably not be possible

## Context
This would greatly improve the ability to keep credentials updated over a large number of connections that all use the same credentials.

**Comment by Shananiganeer** [comment]
This functionality already exists with folders. Create a folder for each unique set of credentials. Save the credentials into the folder. Create connections within that folder and enable inheritance on them for Username, Domain, and Password.

![image](https://user-images.githubusercontent.com/20528114/91582865-6cb03780-e91e-11ea-8499-e46256b12d37.png)

**Comment by Anders-Ryden** [comment]
Brilliant!
I must confess that I've never looked at the properties of folders☺

I can see that I have some editing to do on Monday.

Then we can close this suggestion


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Shananiganeer** [comment]
Glad I could point you that way. It's the killer feature that makes me use mRemoteNG in the first place!

**Comment by Anders-Ryden** [comment]
I've played around with this a bit and it's working, but not quite as I expected.
Inheritance here works from the bottom up instead for the top down.

I need to enter the config of each of my 70+ connections in various folders for this account, and the folders as well, and turn inherintance on instead of just pushing the fields I want  inherited down into the configs from the top folder level.

It seems as if new connections will have the inheritance by default, but there needs to be a way to update existing connections as well or this will take enormous amount of time to set up.

Maybe it's there somewhere but I haven't found it yet.

**Comment by Shananiganeer** [comment]
You can set the default inheritance for the entire connection file or for a specific folder, but it will only apply that inheritance to new connections. PR  #1451 looks to add a menu option to force children to re-grab their inheritance settings.

![image](https://user-images.githubusercontent.com/20528114/91733460-8c8e6800-eb77-11ea-9e0e-9096e2088bdf.png)

**Comment by Anders-Ryden** [comment]
PR1451 is exactly what I want, hopefully it will be merged into the main branch soon.

I'm looking into creating all my connections again in a new folder with inheritance set up, it might be simpler to do it that way

**Comment by Shavo26** [comment]
Hello, I had the same "inheritance modification" issue.
What I did is mass replacing values in the confCons.xml file, with a text editor.
Fastest way I found yet.

**Comment by Anders-Ryden** [comment]
Functionality already existed, eagerly awaiting #1451
