### ISSUE TITLE
White windows on HTTPS Requests

### ISSUE THREAD

**Issue by titou44260** [mRemoteNG/mRemoteNG#1842]
Hi everybody,

I'm having issues getting connection on Firewall (Juniper FG-200D) on HTTPS.
Connect to FW is ok (credentials are recognized) but a white windows appears and no error messages

With SSH no problem

mRemoteNG version : 1.76.20.24669
Connection : HTTPS, port 443, Gecko (Firefox)

it works fine when attempting to connect with browser directly (Firefox)

Regards

**Comment by farosch** [comment]
Hi @titou44260
On v1.76.20 the default HTTPS rendering engine is IE. You can set Firefox as an alternative engine by changing the connection properties..
If neither IE nor FF work for you I would recommend using the latest development snapshot.
We have replaced firefox with chromium in this release for better compatibility:
https://ci.appveyor.com/api/buildjobs/b4pg6fqocff66pxh/artifacts/Release%2FmRemoteNG-Installer.msi

Please reopen this issue if you are still unable to connect to your Juniper web interface using mRemoteNG.
When reopening please also tell us if you are able to connect to your web interface using IE, FF or Chrome using these browsers directly.

**Comment by jackmoscow** [comment]
> Hi @titou44260 On v1.76.20 the default HTTPS rendering engine is IE. You can set Firefox as an alternative engine by changing the connection properties. Unfortunately the embedded version of Gecko we are using in v1.76.20 is quite outdated. Due to the fact that Gecko is not as simple to program for as Chromium and also the lower compatibility we have replaced FF in favor of Chrome in our latest branch. You can grab the build from our automated build system: https://ci.appveyor.com/api/buildjobs/b4pg6fqocff66pxh/artifacts/Release%2FmRemoteNG-Installer.msi
> 
> Please reopen this issue if you are still unable to connect to your Juniper web interface using mRemoteNG.

I try new version [1.77.1] - 2019-09-02
And in it the same situation as the colleague described, the fortinet console does not open.
In the program itself, the status of available protocols remained the same (IE and Gecko)

**Comment by simonai1254** [comment]
I can confirm running 1.77.2-nb in the Windows 10 Sandbox (Windows 2004, x64) and setting the Protocol to HTTPS and the Rendering Engine to "Edge Chromium" I do get a grey screen when trying to access the Fortinet Management page (with invalid and valid certificate). Furthermore I could not get any other page to load over HTTPS, also using the Internet Explorer as rendering engine the attempts end with a disconnection error.
