### ISSUE TITLE
Remote audio no longer working on Insider Preview Build 2004

### ISSUE THREAD

**Issue by MarkusMcNugen** [mRemoteNG/mRemoteNG#1844]
## Expected Behavior
Remote audio is passed to the host running mRemoteNG. The default Remote Desktop client that comes with Windows has working remote audio, it's just mRemoteNG that has stopped working.

## Current Behavior
No audio is heard although the Remote Audio device is shown in the sound control panel

## Possible Solution
Not a dev, no idea. I did compile it from source thinking that might resolve the issue but it did not.

## Steps to Reproduce (for bugs)
1. Install insider preview build 2004 from the fast ring

## Context
Remote desktop into my work laptop from my home computer so I can use mRemoteNG's amazing scaling to the panel size rather than the built in remote desktop clients crappy "smart" scaling.

## Your Environment
* Version used: 1.77.0.41252
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 2004 x64 Build 20197.1000

**Comment by farosch** [comment]
We are not investigating issues on unstable operating systems.
The past has shown that these issues mostly disappear when Microsoft releases a stable build.

As Microsoft states to all their users in fast ring:

> Be prepared for issues that might block key activities [...] .
> 
> ***Source: https://docs.microsoft.com/en-us/windows-insider/at-home/rings#fast-ring***
