### ISSUE TITLE
RDP is not in the taskbar after changing the size of screen

### ISSUE THREAD

**Issue by thoew** [mRemoteNG/mRemoteNG#1847]
After changing the RDP session from fullscreen to a smaller size, the RDP session is not in the taskbar anymore. If I go turn back to fullscreen and minimize the connection again, the RDP session is not visible in mRemoteNG and taskbar so that I have to reconnect the connection.

**Comment by VShawn** [comment]
can not reproduce issue on my app(1.77.1.27713 from win10 2004 to win2016).

may be you can describe the steps to reproduce the issue.

or try to update  the lastest build from Appveyor: https://ci.appveyor.com/project/mremoteng/mremoteng/builds/33630769/job/rcjjfr03bn5u8kkt/artifacts

or try my remote manage tool
https://github.com/VShawn/PRemoteM

**Comment by farosch** [comment]
You cannot change settings when your session is connected. After changing settings you have to reconnect that session for the settings to be applied.
