### ISSUE TITLE
Startup connection file could not be loaded - 1.77.1.27654 - after unsuccessful sql connection

### ISSUE THREAD

**Issue by Karuczka** [mRemoteNG/mRemoteNG#1852]
After unsuccessful ms-sql connection MremoteNg never start again.

In the log I found : ERROR - Connections file "" could not be loaded!
The config file confCons.xml on the normal folder (c:\Users\xxx_xxx\AppData\Roaming\mRemoteNG\ )

I found an other config file on c:\Users\xxx_xxx\AppData\Local\The_mRemoteNG_Team\ folder user.config.
When I renamed it, the MremoteNg recreate and started again (not need to reinstall or ccleaner)

[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/5149315/mRemoteNG.log)

**Comment by Shananiganeer** [comment]
The following xml in the user.config is the culprit. Changing LoadConsFromCustomLocation to False or adding a value to CustomConsPath will resolve the issue.

```<setting name="LoadConsFromCustomLocation" serializeAs="String">
  <value>True</value>
</setting>
<setting name="CustomConsPath" serializeAs="String">
  <value />
</setting>```
