### ISSUE TITLE
Option to Allow Duplicate Connections

### ISSUE THREAD

**Issue by kalliej** [mRemoteNG/mRemoteNG#1854]
Option to allow duplicate connections

## Expected Behavior
Must be able to open multiple connections to same saved connection

## Current Behavior
If connection is opened and you double click it just goes to opened connection.

## Possible Solution
Option in Settings: Allow duplicate connections <No> <Yes> <Ask>

## Context
This would just be a good new feature

## Your Environment
Windows
* Version used:
* Windows 10 x64

**Comment by shawn-ag** [comment]
I totally agree.  There could be a setting for what double-clicking does.  Single-click to go to that session, double click to duplicate.  I VERY frequently use at least 2 sessions when doing things on the Linux servers I manage - one for performing the functions, one for resource monitoring.  Is there even a work-around?

**Comment by kalliej** [comment]
OK I found a way - just right-click on the open tab and then 'Duplicate Tab'
