### ISSUE TITLE
v1.76.20 - Hashes for this version

### ISSUE THREAD

**Issue by userjohn808** [mRemoteNG/mRemoteNG#1857]
There doesn't seem to be any hashes available for this version (v1.76.20). Could they be provide, please?

There is an issue open with a general request to have hashes available all the time. In that issue someone provided hashes, but they are for an older version (1.76.11.40592). Related issue - https://github.com/mRemoteNG/mRemoteNG/issues/1449

These really should be available upon release. I have very little coding skills, but if there is something I can do help with making these hashes available I would be willing to pick up this task.

**Comment by farosch** [comment]
You can find the hashes for 1.76.20 here:
https://github.com/mRemoteNG/mRemoteNG.github.io/blob/master/_data/releases.json

We are in the middle of changing our automated build system and the homepage at the same time, which obviously broke some things...
We'll try to get the checksum thing working again in general.
