### ISSUE TITLE
RDP Disconnects When Resizing MRemoteNG Panels

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#1859]
If I have an RDP session established with a Windows Server 2016 STD host, when I drag the mRemoteNG panel to resize it I get disconnected from the RDP host & mRemoteNG indicates it is re-establishing connection.  Truly bizarre.  This issue is 100% reproducible.

## Expected Behavior

I should not lose the RDP connection/session.

## Current Behavior

The RDP sessions drops & then reconnects.

## Steps to Reproduce (for bugs)

Establish an RDP session.
Drag the mRemoteNG panel to resize it.

1.
2.
3.
4.

## Context

I am trying to resize the panel to display more information.

## Your Environment

* Version used:
Portable (ZIP) version 1.76.20.24669
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 10 1803 x64.

**Comment by farosch** [comment]
This is not a bug but rather a limitation of the RDP protocol/mstsc.
When you resize your window the RDP connection **has to be reconnected** in order to apply your new virtual monitor dimensions.
Set Resolution to "Smart Size" under Appearence to get the default mstsc behaviour.
