### ISSUE TITLE
RDP Disconnects When Resizing MRemoteNG Panels #2

### ISSUE THREAD

**Issue by wingmaker101** [mRemoteNG/mRemoteNG#1860]
RDP Disconnects When Resizing MRemoteNG Panels

## Expected Behavior
should not disconnect

## Current Behavior
disconnects

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

win 10 ver 1909

**Comment by farosch** [comment]
Duplicate of #1859
