### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by Crackdown04** [mRemoteNG/mRemoteNG#1868]
Hello it would be nice if you can update built-in tools like Putty, because they have many security vulnerabilities that have been fixed in the current version.

Exampel Putty: https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

**Comment by OraDotNetDev** [comment]
Some of the putty vulnerabilities are fairly serious:

[https://www.cvedetails.com/vulnerability-list/vendor_id-471/Putty.html](https://www.cvedetails.com/vulnerability-list/vendor_id-471/Putty.html)

**Comment by kmscode** [comment]
Latest pre-release of puttyng is available here:
https://github.com/mRemoteNG/PuTTYNG/releases/tag/0.75.0.1
