### ISSUE TITLE
SQL Server is not listening on default Port

### ISSUE THREAD

**Issue by m0rph2k** [mRemoteNG/mRemoteNG#1884]
Hello

My Mysql Server is not listening on the default Port is it possible to change the Port eg. Server:PORT ??

**Comment by HiNsKeY** [comment]
+1 for this. I have a number of external facing databases and this port is already taken on my chosen host. A field to specify the port would be great

**Comment by farosch** [comment]
@m0rph2k @HiNsKeY 
This will be available in the next stable release, that we are planning on releasing this month.
This was actually a fairly simple fix. Setting the Port on MySQL connections was already possible.
