### ISSUE TITLE
SSHv2 not connect to server and interferes installed Putty

### ISSUE THREAD

**Issue by Zwixx** [mRemoteNG/mRemoteNG#1889]
mRemote doesn't connect to server and only shows a blank black screen for a second.

## Expected Behavior
connect to the Server

## Current Behavior
Only a short time a black screen occurs

## Possible Solution
I don't know why, but if I install mRemoteNG, my putty (version 0.74) also doesn't work any more. If I uninstall mRemoteNG it works fine. I tested it with the current release and the prerelease version.

## Steps to Reproduce (for bugs)
1. Start mRemoteNG
2. click on any imported putty-connections or create a own one and try to connect.

## Context
I tried to install mRemoteNG and testet a litte bit around. This effect that's the console window closes I know about a old Version of putty. The same effect I had in a specific Version of putty (I don't know the Version Number any more). The next version works flawlessly.

## Your Environment
* Version used: 0.77.1 and 0.76.20
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 2004 x64

**Comment by Kvarkas** [comment]
We are using our specific putty implementation, but unsure why its interfere with existing install, need to investigate

**Comment by farosch** [comment]
IMHO this sounds like someone/something tempered with the puttyng.exe and mRemoteNG is thus unable to hook into the session window anymore.

I could be wrong though. In this case please reopen this issue after confirming it still exists in the current prerelease version.
