### ISSUE TITLE
Is this project still under active development 

### ISSUE THREAD

**Issue by GregoryMachin** [mRemoteNG/mRemoteNG#1890]
Is this project still under active development. 
- I see there have been project commits but no releases for a long time.
- The pre-release 1.77.0 was the last release in April 2019.
- no updates on the blog since January 2017. 

Please not this is not intended as a criticism of the project, just I regularly check-in to see if there are updates. 

BTW its great product.

**Comment by VShawn** [comment]
the lastest commit at 3 months ago, no idea why thers was no new release.

---

well i can understand why no updates on the blog, writing document is soooo boring. LOL

**Comment by LIyoai** [comment]
It's open source. So it's as active as the community wants it to be.
Since I'm not a developer I donated a few $.

[Contribute](https://mremoteng.org/contribute)

Btw question was already asked twice
#1823 
#1748

**Comment by Kvarkas** [comment]
it is
