### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by sharjeelakhan** [mRemoteNG/mRemoteNG#1891]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I can connect to all remote servers except for one, which did not have any issues earlier. Receiving following error message on nRemoteNG software: Protocol Event Disconnected. Host; Protocol: "RDP" Message: "Because of a protocol error 3334, this session will be disconnected. Please try connecting to the remote computer again

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by LIyoai** [comment]
Maybe you can fill out the template, especially the part about the version you are using.
Otherwise it will be hard to get help.

**Comment by Kvarkas** [comment]
Could you confirm that latest build facing same issue?

**Comment by farosch** [comment]
Closing as stale.
