### ISSUE TITLE
Feature Request: Display current windows dimensions

### ISSUE THREAD

**Issue by nelgin** [mRemoteNG/mRemoteNG#1903]
It would be nice for mRemoteNG to display the current terminal size since some sites I connect to require specific rows or columns.

This should be dynamically displayed and change and the window is resized. For example, I need to log into sites that requite 24x80 so I must resize to make that work.

**Comment by farosch** [comment]
This cannot be done, as mremoteng completely relies on PuTTY for terminal connection and it simply does not have this function.
You can set your default terminal size in the options though.

![image](https://user-images.githubusercontent.com/22905106/146282594-da37f9d1-7c22-4a68-980b-85182be1caf8.png)

![DfSeD](https://user-images.githubusercontent.com/22905106/146282625-6f8ff405-6edd-4289-9020-2ca6ba62a276.png)
