### ISSUE TITLE
RDP connection hang on file tranfer

### ISSUE THREAD

**Issue by infectormp** [mRemoteNG/mRemoteNG#191]
RDP connection hang on file transfer (~50MB) between Windows 10 x64 and Windows Server 2016 x64

Other RDP client like mstsc and RD Tabs work fine.

mRemoteNG version - 1.74\1.75 aplha 3

**Comment by infectormp** [comment]
same with  Windows 10 x64 and Windows Server 2012 x64

**Comment by infectormp** [comment]
any comments?

**Comment by kmscode** [comment]
@infectormp sorry for the delay... Could you clarify? How are you transferring the files (auto mapped drives via connection options perhaps)? Does just the RDP session hang? For example, does the rest of the mRemoteNG window respond? If you had another connection option, could you switch to it and used it effectively?

**Comment by infectormp** [comment]
@kmscode i transfer files via auto mapped drives. Only RDP session hang, main window of the mRemoteNG work fine, i can switch to other rdp\ssh session and work in it.

**Comment by sparerd** [comment]
We will need to investigate whether this is an issue with our implementation or something in the version of the RDP library we are using.

**Comment by infectormp** [comment]
session hang happens only on files bigger than 2MB-3MB if i transfer small files all fine.

**Comment by jotatsu** [comment]
Candidate for 1.8, requires checkings on the ocx rdpclient behavior

**Comment by nmat** [comment]
I did some quick testing here with a hyper-v instance and I had no problems with transferring files.

Is there any feedback on if this still is a problem? I have worked with 2016 machines a lot with later releases of mRemoteNG and not experienced problems transferring files even if they are gb big.

**Comment by farosch** [comment]
Just like @nmat I cannot reproduce this issue.

> @kmscode i transfer files via auto mapped drives. Only RDP session hang, main window of the mRemoteNG work fine, i can switch to other rdp\ssh session and work in it.

This sounds like it is unlikely this problem derives from mrng code...

@infectormp Can you please verify if this is still a problem for you?

**Comment by infectormp** [comment]
@farosch I can't verify a problem. I not use mRemoteNG anymore.
