### ISSUE TITLE
No username setting for VNC

### ISSUE THREAD

**Issue by Jefronty** [mRemoteNG/mRemoteNG#1913]
When setting up a new connection as VNC there is no way to set a username for the connection.  
![VNC config](https://i.ibb.co/qpsqq5C/m-Remote-NG-vnc.png)  
When attempting to connect I get the error "Opening connection failed! Unable to read next byte(s)."

**Comment by LIyoai** [comment]
Never noticed that I need a username for vnc.
Is a connection with another vnc client working? And there you need to enter an username?

**Comment by LIyoai** [comment]
#465

**Comment by farosch** [comment]
Closing as duplicate of #444. Please follow this issue for updates.
