### ISSUE TITLE
.NET Runtime unhandled exception

### ISSUE THREAD

**Issue by JobvanDalen** [mRemoteNG/mRemoteNG#1917]
After the latest Windows 10 updates, mRemoteNG crashes directly when started, giving me .NET Runtime error 1026 and 1000. 
I've installed the latest version of mRemoteNG, updates and patches of Windows 10 and .Net.

mRemoteNG.exe, version: 1.76.20.24615
Windows 10 Pro 20H2 - 19042.572
Windows Feature Experience Pack 120.2212.31.0

**Comment by VShawn** [comment]
According to Microsoft's information, no relevant solutions were found:
maybe re-install net framework can help.
https://docs.microsoft.com/en-us/answers/questions/55228/event-id-1000-and-1026.html

or you can try my RDP tools written with reference to mRemoteNG in WPF:
https://github.com/VShawn/PRemoteM

**Comment by JobvanDalen** [comment]
Reinstalling net framework dit not help.
After some additional research, deleting the user.config file in the %localappdata% appears to be the solution.
