### ISSUE TITLE
mRemoteNG Application freezes for 10+ seconds when you right click a connection.

### ISSUE THREAD

**Issue by SashaCoppess** [mRemoteNG/mRemoteNG#1929]
**When I right click a connection (in the connections panel), the application freezes for about 13 seconds and then performs the action.**
## Expected Behavior

**My expected behavior would be that if I right click a connection, it pulls up with the menu without having to wait an extended amount of time.**

## Possible Solution

**I believe the cause of this has to do with how many external tools I have set up in the application (over 200 tools built).**

## Steps to Reproduce (for bugs)

**1. Right click a connection within the connection panel
2. Wait around 13 seconds
3. Able to see the right click menu popup after 13 seconds**
4.

## Context

**I would like the right click menu to popup in a quicker manner while also having all my external tools configured within the app.**

## Your Environment

* Version used: **1.76.20.24615**
* Operating System and version (e.g. Windows 10 1709 x64): **10.0.19041 Build 19041  Windows 10 x64**

**Comment by farosch** [comment]
Issue no longer present
