### ISSUE TITLE
Feature Request: Chromium rendering engine for http connections

### ISSUE THREAD

**Issue by SimplifyAndAddCoffee** [mRemoteNG/mRemoteNG#1930]
It would be nice to have a third option that's not gecko or IE

**Comment by Kvarkas** [comment]
Currently latest build use only Chromium

**Comment by farosch** [comment]
We have replaced gecko with webview2 already in the current develop branch.webview2 is basically edge chromium and helps us for better compatibility with homepage rendering in general and easier implementation code-wise (aside from some other benefits).
This is a question of #2023
