### ISSUE TITLE
Cut & Paste from Clipboard still not working

### ISSUE THREAD

**Issue by winvis** [mRemoteNG/mRemoteNG#1941]
Cut & Paste from Clipboard still not working

## Expected Behavior
 Cut & Paste from Clipboard still not working
Cut & Paste from Clipboard 

## Current Behavior
 nothing happens

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 Cut & Paste from Clipboard. I tried all suggestions on Github and what I found via Google, but nothing seems to work. The Clipboard Redirect is definitely set to TRUE, but still nothing is pasted. Without cut & paste this program is absolutely useless.

## Your Environment

* Version used: 1.76 and 1.77 both tested
* Operating System and version (e.g. Windows 10 1709 x64): W10 20H2

**Comment by VShawn** [comment]
I tried my 1.76, it did works. Have you tried official mstsc.exe? If mstsc.exe works to you, then it may be the compatibility issues. or you can tried my works: [censored]

**Comment by mpowrie** [comment]
I have this same issue on version 1.77.2.28290 (the latest commit as of 19/8/2021)
OS system and version: Windows 10 21H1 (OS build 19043.1165)
The clipboard works using MSTSC

**Comment by eckard** [comment]
I've had the same issues with the nightly builds until I realized that the server connections got an additional config item responsible for this behaviour: Check if "Cliboard" is set to "yes" in the Redirect Category of your existing server connection configs. See https://github.com/mRemoteNG/mRemoteNG/issues/1652

@devteam: Would be a good idea to default this to "yes" when updating server configs from older versions.

**Comment by Kvarkas** [comment]
> @DevTeam: Would be a good idea to default this to "yes" when updating server configs from older versions.

Hi, in the plans is to add settings profiles so you can create how settings should be look like by default, or apply them once needed to parent container or single instance etc.
(several names may be for such settings profile so user will have full control if not limited by policy to apply one or another depending on his needs) 

@winvis please have a look into settings to enable such:
![image](https://user-images.githubusercontent.com/3611964/148786236-c6792f05-6bc8-49b1-aa8b-19f11305a889.png)
