### ISSUE TITLE
How to Disable Pop Up Automatic Update Settings first start

### ISSUE THREAD

**Issue by saipraveenjan10** [mRemoteNG/mRemoteNG#1942]

**Comment by VShawn** [comment]
U can deploy mremoteNG with file `mRemoteNG.settings`, and set the `CheckForUpdatesOnStartup` to `False` in the `mRemoteNG.settings`

**Comment by Saijanjam** [comment]
How to disable auto updates for mremoteNG through registry or config. .json file? can someone please help me

**Comment by simonai1254** [comment]
If you provide a predefined user config (see Readme for file paths) the prompt shouldn't appear
