### ISSUE TITLE
Is the project stalled? Time for a fork?

### ISSUE THREAD

**Issue by lars18th** [mRemoteNG/mRemoteNG#1948]
Hi,

I open this issue to ask about the "real" state of this project.
Could you please comment?

**Comment by KDGundermann** [comment]
- 600+ open issues
- last release 2 years ago
- last commit 6 months ago
does not look as if it is active
Sad, its a nice tool

**Comment by lars18th** [comment]
> * 600+ open issues
> * last release 2 years ago
> * last commit 6 months ago
>   does not look as if it is active
>   Sad, its a nice tool

That's the reason to ask about.

**Comment by Laim** [comment]
Definitely looks it, which is a shame.  Was active for quite sometime and was already a fork of mRemote in the first place.

**Comment by heitmanr** [comment]
maybe it's time to donate?

//no offense at all: this thought is valid for me, too - I started donating for open-source-tools i regularly use, but I forgot mRemoteNG :-(

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/1949

**Comment by lars18th** [comment]
We continue in #1949 :hand:
