### ISSUE TITLE
The future of mRemoteNG

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#1949]
Hello everyone,

It goes without saying that over the last few years this project has not seen the support that it needs and deserves. The blame for that lack of support lies squarely on me, and for that I am sorry. It was a lot of fun working on and managing this project, but I don't have the energy to devote to it anymore.

At this point, it would be best if control of the project was passed on to someone else.

Ideally, you should be very familiar with C# and at least know the basics of WinForms. You don't have to be a Senior Software Architect III or anything, but you should know how to code and be willing to learn and improve. Other areas that would be helpful to have some experience with are: MS SQL server and/or MySQL, the RDP protocol, the SSH protocol, applied security (authenticate/authorization, encryption practices, etc).

However, this position isn't just about coding. A fair amount of time is required triaging issues, looking over PRs, planning releases, and coordinating volunteer help. If you haven't managed a Github org before, please know that it can be a massive amount of work. This project has built up a hefty backlog (again, sorry) which may seem fairly daunting in the beginning. mRemoteNG is a fairly popular project with a large userbase. Sometimes you will have to deal with rude comments or extreme expectations. For some, this can take a toll on your emotional health if you get too invested.

If I haven't scared you off yet, good. Because there are some great upsides to leading an open source project. I guarantee you that you will grow as a developer and as a project manager. Working on all aspects of a project's development cycle is both enlightening and pretty fun. It is pretty likely that you will have the chance to work with technology you haven't dealt with before. If you aren't already far along in your career (and even if you are), it can also look great on a resume. Building software that people use on a daily basis is gratifying and even more so when they come back just to thank you for it. And finally, overall the community is very supportive and just wants to see the project grow and succeed.

If you are interested and feel you would be a good candidate to take over the project, please email support@mremoteng.org with the subject line **"mRemoteNG Candidate"** and some info about why you feel you would be a good candidate. In the coming weeks, I will reach out to candidates and we will go from there.

If you don't feel up to taking ownership of the project, but still want to help jumpstart its revival, feel free to leave a comment on this issue with how you are willing to contribute.

Thank you,
David

**Comment by andre-faria** [comment]
You have done a great work, and you don't have to blame your self, everyone have limits.

**Comment by NextBlaubeere** [comment]
Thank you for all your time and effort! You clearly made the live of a whole community more convenient. :-)

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/1948

**Comment by r01k** [comment]
Thank you for such a great software. I've tried many other RDP clients but they're too clunky or a kitchen sink. mRemoteNG is practical and just what's needed. I think the project would benefit from paid licensing, since so many open source efforts die relying on donations.

**Comment by Goldshop** [comment]
I have being using mRemoteNG for years, while I have never manged a git repository before I would be more than happy to assist where I can to whoever wants to take it on.

**Comment by marclaporte** [comment]
I am willing to help. I have been managing Open Source projects since 2003 and I am familiar with all aspects (community management, marketing. licenses, documentation, dev process/lifecycle/etc.). Precise way to help will depend on what the new leadership needs.

Congrats and thanks for all the great accomplishments so far!

**Comment by VShawn** [comment]
Thank you for your great contribution, this app helps me a lot.

**Comment by rudyonsnow** [comment]
Thank you for the great work!

**Comment by cuiliang** [comment]
Thank you!

**Comment by Xhanti** [comment]
If you need help working on the code, I'll throw my name in the pot. 
Used for years and have recommended it to everyone I know.

**Comment by kneely** [comment]
I can help as well. I have quite a bit of experience with C# and Windows Forms

**Comment by c3rberus** [comment]
You have done an amazing job, this is our go to tool for a shop with a few sysadmins looking to share RDP connection list. 

I am no coder, but I do hope this continues to be developed and new releases made available. This lightweight highly configurable easy to use tool is irreplaceable.

We should setup some sort of donation to whoever takes the lead on this to keep the project alive.

**Comment by steenstra** [comment]
Thanks for all the work you've put in to this program. I use it on a daily basis. In fact it might be the only program that's keeping me on Windows.

**Comment by frankenzipfel** [comment]
me too ... "I would pay to continue if needed..."

**Comment by lars18th** [comment]
Please, until a new fork is started, write in the README that the project is freezed.

**Comment by tboege** [comment]
Thank you for your work. I am a (happy) daily user of mRemoteNG

**Comment by sparerd** [comment]
User @kvarkas has offered to take over some maintainer duties. I've given him access to manage issues/PRs and push to the repo. It will take some time to complete the transition, but in the meantime I am hoping issues/PRs will start to see some movement again. Please give him a warm welcome!

Thank you to all who have expressed your support, it means a lot.

@lars18th Good idea, I've added a note to the readme.

**Comment by simon1tan** [comment]
thanks. I don't know how you picked this new maintainer but you might as well just kill this project and let it die peacefully

**Comment by XtremeOwnageDotCom** [comment]
> thanks. I don't know how you picked this new maintainer but you might as well just kill this project and let it die peacefully

I am going to actually agree with this comment. 

Looking at that user's profile....

No contributions, at all.... its pretty bare.....

**Comment by zam264** [comment]
For people such as myself who were looking for a potential replacement, I just switched to using the free version of [Remote Desktop Manager](https://remotedesktopmanager.com/).  It feels pretty similar, albeit a bit more bloated.  Thankfully it also supports [importing mRemote connections](https://forum.devolutions.net/topics/29549/import-to-mremoteng-connections) which made the transition pretty quick.

**Comment by Kvarkas** [comment]
Hello, don't think this will die :) happy to lead this project to the glory! I promise to take care of it as much as i can and I am with that project already from a time then it was rewrited from older version of original owner so give me a bit of time and we will move these wheels forward, hope you will be happy to help me as well ;)

**Comment by Kvarkas** [comment]
> thanks. I don't know how you picked this new maintainer but you might as well just kill this project and let it die peacefully

Its to good to let it die!

**Comment by lars18th** [comment]
Hi @Kvarkas ,

Great to see you want to continue with the project. When you can, do you want to provide a Roadmap or TODO list, please?

**Comment by lars18th** [comment]
> > Great to see you want to continue with the project. When you can, do you want to provide a Roadmap or TODO list, please?
> 
> First I am planning to r…

Great to hear it! Perhaps you want to create a new entry in the WIKI page listing your current TODO. Or publish it a the top of the README.

Good luck with this new responsability.  I hope I can help with some ideas.
Regards.

**Comment by Kvarkas** [comment]
> Great to hear it! Perhaps you want to create a new entry in the WIKI page listing your current TODO. Or publish it a the top of the README.
yes happy to do such once got enoght permissions

**Comment by Goldshop** [comment]
I am happy to help with PRs and Issues to actually get things moving if you are interested

**Comment by Karuczka** [comment]
Thank you for your time, we are daily users of mRemoteNG.
We also would pay to continue.

**Comment by bereldhuin** [comment]
@Kvarkas , thanks for the time you will (and already started ;-) ) to spend on maintaining mRemoteNG.

I can participate in testing and translation if needed. 

Is there a doc somewhere on how to compile the source code (I don't have Visual Studio, just the free compiler provided by M$ on Win 10) ?

**Comment by Kvarkas** [comment]
> I can participate in testing and translation if needed.
You are welcome :)
 
> Is there a doc somewhere on how to compile the source code (I don't have Visual Studio, just the free compiler provided by M$ on Win 10) ?
You can download Visual Studio Community Edition for free! (https://visualstudio.microsoft.com/downloads/)

We have a documentation that is needed (will update it slightly soon)

**Comment by ErMaqui** [comment]
> Is there a doc somewhere on how to compile the source code (I don't have Visual Studio, just the free compiler provided by M$ on Win 10) ?

Compiling it are very simple. Just download it, open solution with VS2019, right click on project mRemoteNG and press Build. It works like a charm. And you get a "beta" version with the latest features pushed by @Kvarkas.

**Comment by bereldhuin** [comment]
> Compiling it are very simple. Just download it, open solution with VS2019, right click on project mRemoteNG and press Build. It works like a charm. And you get a "beta" version with the latest features pushed by @Kvarkas (Thanks to all of these coders who requested these PRs, obviously).

Thanks, it works fine with the free version of VisualStudio. I can now have a daily build of mRemoteNG :-)

**Comment by FSharpCSharp** [comment]
First of all, I think it's great that this great project has found a new supervisor. Unfortunately, the development had stalled more and more in recent years, which was a great pity. 

Now I have to ask a question about the future development. Is there already a plan for future developments or a kind of roadmap for the planned future developments?

What I would like to see is to use the possibility of the GitHub discussions to have a kind of forum where you can discuss topics outside of this issue list. I would think that would be great!

**Comment by Kvarkas** [comment]
> What I would like to see is to use the possibility of the GitHub discussions to have a kind of forum where you can discuss topics outside of this issue list. I would think that would be great!
We are using [Reddit](https://www.reddit.com/r/mRemoteNG/) for such :)

**Comment by Neustradamus** [comment]
It is possible to release a new build?

I have done a ticket here a long time ago (May 25, 2020):
- https://github.com/mRemoteNG/mRemoteNG/issues/1765

**Comment by Kvarkas** [comment]
> It is possible to release a new build?

Currently its a nightly builds there, I will commit fixes once I can so yes, its will be there, but final release will be once i am happy with most bugs solutions.

**Comment by FSharpCSharp** [comment]
@Kvarkas 
Sorry to ask again in this already closed issue. 

I would be interested to know if there is a roadmap or something similar somewhere that accompanies the short/long term future of this product. 

Have seen that there are already a few partially orphaned projects among the GitHub projects. The most recent one (1.8x.x) was last updated a month ago.

Therefore, I just wanted to inquire when to expect an official new release or to find any plans for the future.

**Comment by Kvarkas** [comment]
not yet prepared, but once feel better will process with bugs and issues fix/implementation. So far not planed any new features to include into 1.7.x only sql fix and perhaps profiles. also need to update and release stable version as well so have less head aich about support different versions.

**Comment by pjamesburwell** [comment]
> me too ... "I would pay to continue if needed..."

As would I...

**Comment by pjamesburwell** [comment]
I know many in my consultancy that would be happy to lead this project. Have you decided yet? 2019 is too long ago to be considered viable pretty soon: we will need a stable release soon, or this app will not be considered for dissemination. So, based on this criteria, whom do we have a discussion with about the management of this project?
You can reach out to my email to discuss.

**Comment by Kvarkas** [comment]
project need coding and that include bug fixing so far I am preparing for release of stable version but need a wait a bit till main issues will be fixed.

**Comment by lars18th** [comment]
Hi to all,

Remenber that the current roadmap is public: https://github.com/mRemoteNG/mRemoteNG/projects

**Comment by TBG-FR** [comment]
> 
> 
> For people such as myself who were looking for a potential replacement, I just switched to using the free version of . It feels pretty similar, albeit a bit more bloated. Thankfully it also supports [importing mRemote connections](https://forum.devolutions.net/topics/29549/import-to-mremoteng-connections) which made the transition pretty quick.

Although it could be sufficient for your personal needs, this solution will cost 6000 $ to any small company who wants an efficient software to manage SSH connections, that's quite a lot, even for a solution with a modern look and feel and some advanced features (external password management). Not even talking about the fact that you can't see what's behind the scenes, since you can't see the code.

I'm glad that this **open source** project exist and is still maintained, I feel like we should all contribute together if we want things to improve faster. Anyway, thanks a lot for your involvement @Kvarkas (and the others) !

**Comment by lars18th** [comment]
> > [...] I just switched to using the free version of [...]
> 
> [...] that's quite a lot, even for a solution with a **modern look and feel** [...]

From my point of view this "modern look and feel" it's a real cause to not use it at all!
Administration tools require to be *fast* and *confortable*. And the "new" Win8/10/11 look-and-feel are not useful for such tools. So I prefer to use "old" Win7/XP useable tools.

Regards.

**Comment by maz8462** [comment]
> > For people such as myself who were looking for a potential replacement, I just switched to using the free version of [Remote Desktop Manager](https://remotedesktopmanager.com/). It feels pretty similar, albeit a bit more bloated. Thankfully it also supports [importing mRemote connections](https://forum.devolutions.net/topics/29549/import-to-mremoteng-connections) which made the transition pretty quick.
> 
> Although it could be sufficient for your personal needs, this solution will cost 6000 $ to any small company who wants an efficient software to manage SSH connections, that's quite a lot, even for a solution with a modern look and feel and some advanced features (external password management). Not even talking about the fact that you can't see what's behind the scenes, since you can't see the code.
> 
> I'm glad that this **open source** project exist and is still maintained, I feel like we should all contribute together if we want things to improve faster. Anyway, thanks a lot for your involvement @Kvarkas (and the others) !

Just to clarify, the "Free" version of this allows for "Commercial" use as indicated on their website and can be used to manage both SSH and RDP connections for a small company if they so desired.  Enterprise edition simply adds nice-to-have features.  I've been using it since my last post and I am still happy with it, and will continue to use it until either a new open-source product enters the space, or this product receives updates.

If you don't feel comfortable using a non open-source solution, I can respect that, to each their own - I am just providing potential alternatives.

**Comment by c3rberus** [comment]
I use FDM and mRemoteNG. I hate the bloated UI of FDM, its slooooooow at best. However I find it powerful for SSH connections because I can store my keys, command templates, etc.

**Comment by Smir** [comment]
Only just saw this, its a shame, used this for years and years, not very good at coding or even ssh but I knew the basics and I love how simple it is to use, there are a few annoying issues recently, and even upgrading to fix those caused more =-/ hope one day this comes back, I really do.

**Comment by MiguelQuijano** [comment]
I just downloaded it, and it's so great! I really hope some developer takes this project and continue giving it some love. I don't have the skills to do it, but I am willing to donate to help the development and maintenance of it. To the original creator: Great job bro!

**Comment by lars18th** [comment]
Hi @MiguelQuijano ,

> I just downloaded it, and it's so great! I really hope some developer takes this project and continue giving it some love. I don't have the skills to do it, but I am willing to donate to help the development and maintenance of it. To the original creator: Great job bro!

I recomend to try this _in dev_ fork from @robertpopa22 the **mRemoteNG — Community Edition** version: <censored> 

This is side-to-side to the current main developement but ready to use.

**Comment by Kvarkas** [comment]
I am not welcome to promote somebody else repo on our resource, if Robert will want to work together then all builds will be in our release page, so far please dont post any link to 3rd party repositories as this confuse users

**Comment by Laim** [comment]
> I am not welcome to promote somebody else repo on our resource, if Robert will want to work together then all builds will be in our release page, so far please dont post any link to 3rd party repositories as this confuse users

Please be careful looping someone in that is heavily relying on AI.  AI can be a good assistant and it would be good to get a release out the door now it's been years since the last one, but AI also makes mistakes and this tool is something that MANY companies use, every company I've ever worked at has used it.

**Comment by jafin** [comment]
> > I am not welcome to promote somebody else repo on our resource, if Robert will want to work together then all builds will be in our release page, so far please dont post any link to 3rd party repositories as this confuse users
> 
> Please be careful looping someone in that is heavily relying on AI. AI can be a good assistant and it would be good to get a release out the door now it's been years since the last one, but AI also makes mistakes and this tool is something that MANY companies use, every company I've ever worked at has used it.

Humans make mistakes to. Protect yourself with test coverage , guard rails and validation.  Human or AI can then do the work.
