### ISSUE TITLE
Access to https with self-signed certificates not working

### ISSUE THREAD

**Issue by MaRRiK74** [mRemoteNG/mRemoteNG#195]
As the title says. Using https links that use selfsigned certs are impossible to open.
The option to 'continue' is missing.

|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.75 aplha 3 |

**Comment by kmscode** [comment]
https://mremoteng.atlassian.net/browse/MR-977
https://mremoteng.atlassian.net/browse/MR-995

**Comment by sparerd** [comment]
Need to handle the `NSSError` event thrown by the Gecko browser. Default should be to prompt the user whether they would like to continue.

Not entirely sure how to get the IE browser working yet.

**Comment by sparerd** [comment]
The IE browsers inability to prompt to continue was introduced in commit `a1beff7` that was meant to fix another bug. Trying to find that ticket..

**Comment by sparerd** [comment]
Here is the related bug report for commit `a1beff7`: [MR-706](https://mremoteng.atlassian.net/browse/MR-706)

This may require us to add a connection-specific option for toggling error suppression.

**Comment by sparerd** [comment]
The geckofx documentation isn't that great. Going to need to play around with this for awhile. No guarantees this will make it into 1.75

**Comment by kmscode** [comment]
There is a workaround listed in #259

**Comment by l0wBoB** [comment]
Any news or schedule on this? @kmscode

**Comment by Platanisiotis** [comment]
I'm trying to pitch this software for my company and we're running into this same issue which is a major problem if we were to use it.

**Comment by kmscode** [comment]
From #259:

>Allow embed Firefox(GeckoFx) to access SSL w/invalid certs in Remote Connection HTTPS
>
>Manual fix to use your firefox exception SSL w/invalid certs:
>Copy:
>c:\users%USERNAME%\AppData\Roaming\Mozilla\Firefox\Profiles{RANDOM}\cert_override.txt
>and place it here
>c:\users%USERNAME%\AppData\Local\Geckofx\DefaultProfile\cert_override.txt
>
>Note: https://developer.mozilla.org/en-US/docs/Cert_override.txt

**tentatively scheduled for 1.76**

**Comment by Alkaceq** [comment]
Ïs there any plan to have this fix released?

**Comment by rscanman** [comment]
Hi Guys,

Any chance this can be re-addressed?

**Comment by JOduMonT** [comment]
Funny it is:
I added Internet Explorer as [External App](https://mremoteng.readthedocs.io/en/latest/external_tools_cheat_sheet.html#id5) and integrate it to mRemote, and I could launch/use website with self SSL without any issue.
But I still try to figure how to pass username and password...

**Comment by dubdesigndesk** [comment]
Since GeckoFX is replaced and no longer being used is there a new method to ensure that the cert can be overridden, I would rather use the native HTTPS connection than an external app. The path c:\users%USERNAME%\AppData\Local\Geckofx\DefaultProfile\cert_override.txt does not exist. 

Also each time you have a new connection do you need to first login in firefox and accept the issue and then copy the new text_override.txt?

**Comment by MattyKatos** [comment]
Hey guys,
You're on version 1.76.20, any idea when we'll see this?

**Comment by Maitwo** [comment]
Hi guys,
the problem is still present (mRemoteNG-Portable-1.76.20.24669), do you have any update on this?
I have to use Internet Explorer (edge).
Thanks a lot.

![Image](https://github.com/user-attachments/assets/0bd85f8f-c5d5-4e75-8e37-8fbec1ba2dd2)

**Comment by MarcVJ** [comment]
Hello, I have the same problem here with v1.76.20.24615 (2019-04-12), HTTPS sessions are unable to work : 

- If I try an HTTPS connexion with "Internet Explorer", I have this and can't log in : 

<img width="679" height="192" alt="Image" src="https://github.com/user-attachments/assets/840ecd09-db9b-41d5-a1e9-e278c85ce78c" />

- If I try an HTTPS connexion with "Gecko (Firefox)", I have an alert "The document contains no data. " and nothing happens. 

On the other hand, HTTP sessions work with both Internet Explorer and Gecko (Firefox). But I have some devices where only HTTPS is allowed. 

Regards,
