### ISSUE TITLE
Configuration pane: tab-key reversed

### ISSUE THREAD

**Issue by roxsman** [mRemoteNG/mRemoteNG#1953]
When you select a connection, the configuration of this connection is displayed below it.
If you -for instance- click the first field ("Name") to fill in the name and press TAB to go to the next field ("Description"), you are sent to the bottom of the list. SHIFT-TAB goes forward, TAB goes backward.

## Expected Behavior
The tab-key should make the cursor jump to the next field/option/etc.

## Current Behavior
The tab-key makes the cursor jump to the previous field/option/etc.

## Possible Solution
Reverse the tab-key behavior :)

## Steps to Reproduce (for bugs)
1. Create connection or select an existing one from the Connections panel.
2. Click a value in the Config panel
3. Press tab (the previous field will then be selected)
4.

## Your Environment
* Version used: 1.77.0.41252
* Operating System: Windows 10 Pro 20H2 (19042.928)

**Comment by Kvarkas** [comment]
has been fixed in version 1.77.1
