### ISSUE TITLE
Clipboard not in my version. pls update!!!

### ISSUE THREAD

**Issue by maestroat** [mRemoteNG/mRemoteNG#1954]
<
## Steps to Reproduce (for bugs)

1. No Clipboard in this Version in Forum nobody can help, other Version i cant download. 
2. under Redirect some other thinks but no Clipboard, but without this feature mremoteng is not realy to use for me :(
3.
4.

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version: Windows 10 Pro 20H2 x64 (all Updates)

**Comment by VShawn** [comment]
check 

![image](https://user-images.githubusercontent.com/10143738/115864894-20e06e80-a46a-11eb-9eba-d93a71e601df.png)


![image](https://user-images.githubusercontent.com/10143738/115864849-11f9bc00-a46a-11eb-93a7-b81b76d17779.png)

**Comment by Kvarkas** [comment]
Is its still a case?

**Comment by maestroat** [comment]
Prerelease v1.77.0
Mon, Apr 29, 2019 in this Version is this Clipboard, but i have only always use stable version Stable v1.76.20
Fri, Apr 12, 2019, there is no clipboard

**Comment by bereldhuin** [comment]
Clipboard is present and works fine in version 1.77.2.25058
