### ISSUE TITLE
mremoteng won't open (or very slowly) when I don't have an Internet connexion

### ISSUE THREAD

**Issue by nenos11** [mRemoteNG/mRemoteNG#1957]
Hello,

I've been using mremoteng for quite sometime. I'm using it to monitor my lan computers which don't have an internet connexion. 

I know that that mremoteng searches for an internet connexion when starting and that it doesn't work very well without it.

I used to modify something ina conf file to prevent this issue but i can't remerber what it was.....

Thank you for your help.

**Comment by LIyoai** [comment]
Maybe you can try to disable the update check in the settings.

**Comment by Kvarkas** [comment]
not able to reproduce in 1.77.1 could you confirm that issue still exist?

**Comment by bereldhuin** [comment]
No problem for me as well witth version 1.77.2.25058 (built today from latest commits).

If I try to manually check updates, I instantly have a red warning "Check failed!", which is normal without internet connection ;-)
