### ISSUE TITLE
Password storage on mRemoteNG

### ISSUE THREAD

**Issue by ketjow123** [mRemoteNG/mRemoteNG#1963]
I am looking for information, how and where passwords are stored for mRemoteNG? I was looking for in documentation but haven't found anything.
I got some information from https://gitter.im/mRemoteNG/PublicChat?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications, but it would be nice to have it more documented that we would be sure that 2 person working on the same PC cant see the secrets/passwords other person.

**Comment by bytefish163** [comment]
@ketjow123  `%APPDATA%\mRemoteNG\confCons.xml`

**Comment by nmat** [comment]
you want it to say if its salted and hashed?

and also make not recoverable using any means to get the password from the XML I suppose?

**Comment by Kvarkas** [comment]
> you want it to say if its salted and hashed?
> 
> and also make not recoverable using any means to get the password from the XML I suppose?

using external tools it still possible to reveal it

**Comment by farosch** [comment]
As long as you have set a connections password, you're fine. Otherwise, the default key is known to **everybody** atm.
We are working on a fix for this. Please watch #306 on updates on this.
