### ISSUE TITLE
Clipboard defaults to No. Option to set default for all connections with override per connection.

### ISSUE THREAD

**Issue by AgentX-64** [mRemoteNG/mRemoteNG#1968]
## Expected Behavior
Working as expected except the default for Clipboard: is NO
Would like to be able to change the default to YES.

## Current Behavior
Clipboard: NO

## Possible Solution
Add default options to TOOLS > Options > Connections
Override on each connection from Defaults.

## Context
mRemoteNG is my preferred tool for managing multiple servers and workstations.
When accessing a new connection I am confounded that clipboard does not work. I begin troubleshooting to realise it is mRemoteNG default setting of Clipboard:No causing the issue. I change this to Clipboard:Yes and reconnect so can use the clipboard. Apart from having to change each and every connection to Clipboard:Yes after upgrading to latest version, I have to remember to change this setting on every new connections. A minor pain.

## Your Environment
1.77.0.41252
Windows 10 21H1 x64

**Comment by LIyoai** [comment]
You can change the default and enable inheritance so for new connection you don't need to do anything.
To change existing connections it might be related to #1451

**Comment by simonai1254** [comment]
> You can change the default and enable inheritance so for new connection you don't need to do anything. To change existing connections it might be related to #1451

I tested this on 1.77.2-nb (20220107), and I had a really hard time to get the inheritance working. I'm still not sure if I understand how it works. 

In my opinion there should be a way to define the connection settings default for each host, independently if there is inheritance or not. It should be possible to set a general default without the need of enabling inheritance. Inheritance is here in case you need to change some settings for a small subset of the devices and not all of them.

**Comment by tecxx** [comment]
just my 2 cents, i would also like to see a little improvement on the inheritance function as it is slightly confusing. one idea i had was to not hide inherited fields but make them greyed out. this way it is easy to see that "ahh... that setting comes from one entry higher".
since the connection panel is already quite grey (depends on theme probably?) this might be hard to see so maybe keep the grey but make editable fields white instead. anyway - don't hide inherited fields - it's counterintuitive. opinions?

**Comment by simonai1254** [comment]
I can only support that. Should we open a new issue for that or are you going to reopen this?

**Comment by Kvarkas** [comment]
I was mentioned somewhere - my plan is to make connection profiles, so once create instance you may apply (select from dropdown) that profile to use so it will set all desired options, so we will have clean view in connections tree,

**Comment by LIyoai** [comment]
I like it as is and I don't want to see the inherited options😉 either it works because I setup everything ok or i disable it and set other options.

But this could maybe need some attention  #975

@Kvarkas I hope we will don't need to select a profile for each connection.
So we should be able to inherit the connection profile as well.

**Comment by tecxx** [comment]
> I can only support that. Should we open a new issue for that or are you going to reopen this?

i tried to code it myself in the last couple of hours but have to give up - i cannot find a working solution. the one that looked most promising was something along these lines:

`
        public static void SetReadOnlyAttribute(this PropertyDescriptor p, bool value)
        {
            var attributes = p.Attributes.Cast<Attribute>()
                .Where(x => x is not ReadOnlyAttribute).ToList();
            attributes.Add(new ReadOnlyAttribute(value));
            typeof(MemberDescriptor).GetProperty("AttributeArray",
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)
                .SetValue((MemberDescriptor)p, attributes.ToArray());
        }
`
this seems to set the property correctly, but nothing changes in the UI. i'm out of ideas :(

**Comment by Kvarkas** [comment]
@LIyoai no, idea is instead having such bunch options under each instance - move them to profile, however inheritance will work same way (or a bit better :))
