### ISSUE TITLE
Bug with fonts. 

### ISSUE THREAD

**Issue by mcsimz** [mRemoteNG/mRemoteNG#1970]
Font 'Segoe UI Symbol' dosn't supports style 'Regular'.

## Expected Behavior

open Tools/options window

## Current Behavior

Rised Exception

## Steps to Reproduce (for bugs)

1. Navigate to Tools / Options

## Context

Stack trace:
   в System.Drawing.Font.CreateNativeFont()
   в System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   в System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   в System.Drawing.Font..ctor(String familyName, Single emSize)
   в mRemoteNG.UI.Controls.Base.NGCheckBox.OnPaint(PaintEventArgs e) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Controls\Base\NGCheckBox.cs:строка 125
   в System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   в System.Windows.Forms.Control.WmPaint(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

## Your Environment

OS: Microsoft Windows NT 10.0.19042.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI

**Comment by bereldhuin** [comment]
No problem for me with 1.77.2.25945 (on Windows 10 1903)

**Comment by farosch** [comment]
This issue is no longer present in the current develop branch
