### ISSUE TITLE
Multi SSH

### ISSUE THREAD

**Issue by souman101** [mRemoteNG/mRemoteNG#1976]
We need a Multi SSH Feature in this tool. Thats the only thing missing here.
Need to send commands to all the sessions at once

**Comment by LIyoai** [comment]
There is already a multi ssh toolbar.
![image](https://user-images.githubusercontent.com/6205123/123770617-b8c76200-d8ca-11eb-821e-0380310fd020.png)

**Comment by souman101** [comment]
> There is already a multi ssh toolbar.
> ![image](https://user-images.githubusercontent.com/6205123/123770617-b8c76200-d8ca-11eb-821e-0380310fd020.png)

Thank you . I now downloaded the 1.76.20 and its there. I was using 1.75.
