### ISSUE TITLE
Command Line parameters required

### ISSUE THREAD

**Issue by amitverma80** [mRemoteNG/mRemoteNG#1978]
We need command line feature for mremoteng from where I can pass host ip-address,  user name and password as arguments to mremoteng.exe and m-remoteng should open the RDP.
**OR** 
Some library to generate connections xml from C# Windows Form so that I can pass the path of xml to m-remoteng.exe as argument.

Currently there is no way to generate connections.xml from C# Windows Form or any direct way to pass the host ip,  user name and password as argument to exe.

**Comment by farosch** [comment]
Duplicate of #1692
