### ISSUE TITLE
Credential groups

### ISSUE THREAD

**Issue by araujorafalucas** [mRemoteNG/mRemoteNG#1980]
Is there way to create credentials groups in order to make easy to assign to the connections?

Or make all connections inherit from the parent root credentials?
![properties](https://user-images.githubusercontent.com/67080458/123695550-10b18a80-d831-11eb-93ad-c105ab15bd2b.png)

**Comment by Kvarkas** [comment]
please check inherit option for connections, credentials groups not necessary as that a bit different way how its working.

**Comment by nmat** [comment]
https://mremoteng.readthedocs.io/en/latest/folders_and_inheritance.html

**Comment by araujorafalucas** [comment]
Great, that option will be helpful.

But I tried to use that feature but something goes wrong. The app show the following message:
"Your credentials did not work The system administrator does not allow the use of saved credentials for login..."

![error properties inherited](https://user-images.githubusercontent.com/67080458/123847001-6ac35600-d8ec-11eb-93c8-09e72a3a13cf.png)

Is a network configuration which enable inherit option on mRemote?

**Comment by nmat** [comment]
See if you get the same result by using normal RDP outside of mremoteNG

![image](https://user-images.githubusercontent.com/383031/123873352-aa169480-d936-11eb-94c0-e082cb5494ad.png)

make sure you have the "Allow me to save credentials" checked. If that does not work and you get the same issue then probably the setting for: Do not allow passwords to be saved

in the group policy might be checked.

you can verify this by:

1. On the remote server
2. Win + Q (or just press the start menu)
3. type: gpedit.msc
4. go to: User Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Connection Client > Do not allow passwords to be saved

Check what the setting is set to. 

This can be a setting set by the group policy from the company too as a security and control measure.

**Comment by Apollon-Theos** [comment]
Inheritance, like my issue :)
