### ISSUE TITLE
Rework menu in configuration for connection

### ISSUE THREAD

**Issue by Apollon-Theos** [mRemoteNG/mRemoteNG#1990]
![image](https://user-images.githubusercontent.com/46534073/124648369-d9318680-de9f-11eb-87a8-c202ec51c415.png)

## Expected Behavior
Not repeat word "Redirect", normal name of configuration point.

## Current Behavior
Unknown "Redirect", but in description exist info about this point.

## Possible Solution
Rework with menu

## Steps to Reproduce (for bugs)
1. Open config for connection
2. Look at end of menu, after "Redirect"
3.
4.

## Your Environment
* Version used: 1.77.2 24062021
* Operating System and version:  Windows 10 20H2 x64, Windows Server 2019

**Comment by farosch** [comment]
Thanks for bringing attention to this @Apollon-Theos !
This will be fixed in the nextr preview/release.

![image](https://user-images.githubusercontent.com/22905106/129489281-deecb761-30bf-4865-97ea-e028293ccc21.png)
