### ISSUE TITLE
From EventViewer text not copied to clipboard

### ISSUE THREAD

**Issue by Apollon-Theos** [mRemoteNG/mRemoteNG#1993]
![image](https://user-images.githubusercontent.com/46534073/124716916-48918f80-df0d-11eb-87c8-5d88a1ca0bf3.png)

at this moment, Ctrl+C not copy text to local clipboard.

## Expected Behavior
Text into clipboard, can be paste to other application.

## Current Behavior
Clipboard is empty, or contains previous text.

## Steps to Reproduce (for bugs)
1. Open EventViewer in tab
2. Open any event
3. select part of message? and press Ctrl+C
4.  open locally notepad and press Ctrl+V

## Context
Today I work remotely, tomorrow verify by work through console

## Your Environment
* Version used: 1.77.2 24062021
* Operating System and version: Windows 10 20H2 x64

**Comment by Apollon-Theos** [comment]
Exit from v 1.77.2, start 1.76.20, reconnect to same server and transfer text though clipboard work.
Continue my work remotely, change version of mRemoteNG (two version stored in different folder).

**Comment by Apollon-Theos** [comment]
Work at console with 1.77.2 (without RDP to work computer), error confirmed. 
Not copied to clipboard by press Ctrl+C

**Comment by Apollon-Theos** [comment]
from Notepad on remote computer, also. By press Ctrl+C or select "Copy" from menu.
Remote computer work with Windows Server 2016.

**Comment by nmat** [comment]
what is the setting for:

![image](https://user-images.githubusercontent.com/383031/124927834-56bfd880-dfff-11eb-9b58-2e39ac781182.png)

**Comment by nmat** [comment]
because I am not following how you explain the problem...

**Comment by Apollon-Theos** [comment]
Tomorrow, I verify this option for may connection. But I check it before write there, but verify again.

**Comment by Apollon-Theos** [comment]
![image](https://user-images.githubusercontent.com/46534073/125578184-b6124ebc-fcfe-4ddc-b3bc-92bca546dd48.png)
This is part of config in 1.76.20 -> Clipboard always is ON, and this is not configurable option
In 1.77.2 added to configurable, and always is OFF, by default.  
Switch between versions is complex.

**Comment by Kvarkas** [comment]
?

**Comment by Apollon-Theos** [comment]
In v 1.76.20 redirect clipboard is always ON. In v 1.77.2  now is configurable.
I make new connection and not verify configuration for "redirect clipboard", because early this is "always ON" by default.
This issue can be closed. 
+++ But mRemoteNG team can return this option to "always on" +++ :)

**Comment by Kvarkas** [comment]
in case of security its better have defaults as off than on :) but as well you spotted its configurable now so everybody can set this as they wish :)

**Comment by Apollon-Theos** [comment]
Security begin from login/password. Not all user can connect to server via RDP.
But, if realize my issue #1982, many settings can be define on folder. Usability of new version mRemoteNG will be increased.
