### ISSUE TITLE
[request] Limit number on config copies.

### ISSUE THREAD

**Issue by TristisOris** [mRemoteNG/mRemoteNG#1996]
config folder looks like this
![изображение](https://user-images.githubusercontent.com/1270117/124817686-c936a700-df72-11eb-9292-460fdfc67d6d.png)

i setup it right to cloud folder, to sync across devices. So my recycle in cloud always looks like 
![изображение](https://user-images.githubusercontent.com/1270117/124817792-e9666600-df72-11eb-9629-5221f0bd0fe5.png)

any action > write to current config, write new backup, remove old backup. a lot of unnecessary syncing.

would be great to have only in 1 current config.

**Comment by LIyoai** [comment]
Configurable backups #474

**Comment by Kvarkas** [comment]
has been fixed and from now backup location can be separate from config file location, nb is comming!

**Comment by TristisOris** [comment]
yeah it works amazing. thanks.
