### ISSUE TITLE
Proposal to improve the storage of connections in the database

### ISSUE THREAD

**Issue by Traineratwot** [mRemoteNG/mRemoteNG#1997]
### Proposal to improve the storage of connections in the database

The ability to synchronize database connections seems to me to be one of the best features of this application, and I want it to develop

I suggest to save in the database
  - names and parameters of launching external applications
  - application settings: theme, language, connection settings, ...
  - custom connection icons in base64 format

**Comment by Kvarkas** [comment]
Curently its a big work on that happening. Idea to support multiple DB and depending on profile to allow not only create db and save in it connection details but also implement ACL so some users may have only read access and depending on they profile some connections data can be stored in one db, some in other (that not include case then vpn is in use, with vpn only one connection can be active) so be patient - working on it :) how ever if you would like to help project to implement such you are more than welcome to join dev team or at least share you ideas in out [TechChat](https://gitter.im/mRemoteNG/TechChats)
