### ISSUE TITLE
mRemoteNG using high CPU even after closing

### ISSUE THREAD

**Issue by taylorn-ai** [mRemoteNG/mRemoteNG#2000]
I've noticed that mRemoteNG starts using a lot of CPU (90%+) after it's been running for an hour or so. Even if I close connections, it's still using a lot of CPU. Also, if I close the app, I usually still find a process called mRemoteNG.exe running, using 30-40% CPU, even though the UI is closed.

**Comment by Kvarkas** [comment]
hello, interesting, could you specify what version you are using?

**Comment by nmat** [comment]
also....are you running it on windows 11 or windows 10?

could help to get the version from: winver that you can type on run dialog.

just Win+R and then type in "winver"

another thing that can be good to have is to know what system you are running on so can you tell us the cpu model etc you are using.

open a powershell window and type:

get-wmiobject win32_processor

**Comment by taylorn-ai** [comment]
Sorry, I meant to provide some further info before I submitted it.

**mRemoteNG Version** 1.76.20.24615
**Windows Version** Windows 10 1809 17763.1935
**CPU** Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by farosch** [comment]
This is a known bug in 1.76, that has already been resolved.
