### ISSUE TITLE
Request for release Portable version of Nightly builds

### ISSUE THREAD

**Issue by cra3yk** [mRemoteNG/mRemoteNG#2002]
Please release Portable version of Nightly builds. Some of us are using portable version of mRemoteNG and wanted to test new (nightly) builds (without install "normal" version)

**Comment by Kvarkas** [comment]
was a bit sick, but fill better, will try to do it on weekend.

**Comment by cra3yk** [comment]
No problem, I wish You recovery :-)

**Comment by ghost** [comment]
How is it going? To me it's still using %APPDATA% to store data.

**Comment by LIyoai** [comment]
Would be awesome for testing, without the risk of messing up the old version.

**Comment by Kvarkas** [comment]
will do tonight

**Comment by cra3yk** [comment]
Please :-)

**Comment by LIyoai** [comment]
I think this can be closed

https://github.com/mRemoteNG/mRemoteNG/releases/download/2022.01.07-1.77.2-nb/2022.01.07-1.77.2-nb.mRemoteNG.Portable.rar
