### ISSUE TITLE
Feature Request: Option to disable window resizing

### ISSUE THREAD

**Issue by magriiiii** [mRemoteNG/mRemoteNG#2007]
Running mRemoteNG not full screen on a 4k monitor. It happens quite often that I accidentally drag a border of mRemoteNG. This leads to resizing all open rdp sessions. Sometime there are rdp sessions running inside other rdp sessions. It takes a while until all sessions are resized.
An option to disable resizing would be very helpful. Optimal would be a button in the toolbar.

**Comment by farosch** [comment]
There is an `Automatic resize` option in your connections settings.
Have you tried it out? 

![mRemoteNG_6sEUrXeeoh](https://user-images.githubusercontent.com/22905106/128106836-8f4fff01-ac72-4edd-8469-a22dc731c815.png)

**Comment by magriiiii** [comment]
Looks like I missed this option. Well it's not exactly what I'm looking for.  After thinking about my request I think this should rather be a feature of the operating system.
