### ISSUE TITLE
PuTTY key format too new

### ISSUE THREAD

**Issue by alan-bowman** [mRemoteNG/mRemoteNG#2027]
PuTTY upgraded to 0.75 and now when trying to SSH with a new private key via mRemoteNG I get this error: 

Unable to load key file "C:\Users\.ssh\Key.ppk" (PuTTY key format too new)

I've tried recreating the key with older formats but it still has issues loading the key.

**Comment by farosch** [comment]
Please see this for further explanation: https://ccportal.ims.ac.jp/en/node/2914
This has nothing to do with mRemoteNG but instead is caused by putty changing the default ppk file format.

**Comment by jimerman** [comment]
First of all @farosch, shame on you for that answer!  That has everything to do with mRemoteNG not being up to date!  Second, to solve the problem, go to Tools / Options in mRemoteNG, go to Advanced, check off "Use custom PuTTY path" and browse and pick the path to your putty.exe.  You should be able to connect now.

**Comment by Kvarkas** [comment]
@jimerman well that perhaps we need to add to documentation so users know how to deal with, but formally farosch point to that change is not on our side its by putty developer and perhaps as me don't have any ideas that @alan-bowman don't know how to point app to use right version (upgraded) of puttyng

**Comment by simonai1254** [comment]
Another option might be to just replace the %programfiles%\mRemoteNG\PuTTYNG.exe with the one having the current version. Though I guess this file should be kept up to date together with the mRemoteNG package...

**Comment by Kvarkas** [comment]
currently we dont have setup a process to check if version of additional apps is latest, perhaps good idea to add to next release

**Comment by jimerman** [comment]
My point was, if you have a dependency on another product (i.e. PuTTY), then when that product issues an update, you need to have a product cycle that incorporates that update.  I'm not sure why checking off custom path makes it behave properly, while unchecking it does not - since when I click the PuTTY button from mRemoteNG, it launches the same program code.  But, custom path perhaps forces the app to use the updated PuTTY for connection.  Either way, it is a very good workaround.

**Comment by jimerman** [comment]
> currently we dont have setup a process to check if version of additional apps is latest, perhaps good idea to add to next release

I'm not sure if that's the issue.  I had the same problem as @alan-bowman, and I only had the latest version of PuTTY installed (haven't updated it in a while), and the latest mRemoteNG (in fact I updated to the Beta channel to see if that fixed it).  I suspect that there may be some embedded PuTTY functionality in mRemoteNG code that is older?  My suspicion is checking off custom path forces mRemoteNG to use external PuTTY functions.

**Comment by Kvarkas** [comment]
@jimerman mRemoteNG using own puttyNG for better compatibility nobody remember why :D but we still use it, perhaps new version of putty will work without our changes but need to check it.

**Comment by simonai1254** [comment]
mRemoteNG 1.76.20 comes bundled with PuTTYNG.exe version 0.71.0.1, which I assume is loaded by default unless you specify in the Settings to use the one you installed on the system (that might be newer, currently 0.76 is out) instead.

**Comment by Kvarkas** [comment]
@simonai1254 thanks to pointing to that, actually it should be 0.76, just find out our deployment token has been expired! Updated and seems build is ok now, will relink as well

**Comment by simonai1254** [comment]
Just had a look at the properties of the PuTTYNG.exe included in the nightly build (1.77.2nb-20220107), there no version information is included. It even sais "unidentified build, Source Commit Unavailable", maybe this is because the deployment token was expired. 

Further when packaging mRemoteNG as 64bit, we might want to build the PuTTYNG as well with x64 (currently it's x86).

**Comment by simonai1254** [comment]
Further @Kvarkas / @farosch would you mind reopening this issue while we're on it? I think this project should keep an eye on third parties included in the project, and putty definitively is a vital part of it.

There are a lot of issues pointing back to this problem, eg. #2012, #2055, #2028, #1868, #1764

Alternatively I can file a new issue that addresses this topic specifically.

**Comment by Kvarkas** [comment]
ok, lets reopen till we will be 100% sure we address it properly

**Comment by Kvarkas** [comment]
> there no version information is included

I fix that for coming nb, manually you may download and update [puttyNG.exe](https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.76.0.95/PuTTYNG.exe)

**Comment by scottfarwellzt** [comment]
Glad to report that manually downloading and putting the new puttyNG.exe in place and then de-selecting Tools --> Options --> Advanced --> "Use custom PuTTY patch:" seems to work fine now.

The expired deployment token may be the only reason we saw this issue at all as i assume puttyNG.exe was auto-built with MremoteNG version 1.76.20.24615.

I see in the change log : 

> 1.76.17 (2019-03-20):
> 
> Fixes:
> ------
> #1362: Updated PuTTYNG to 0.71"

But not a similar issue for 1.76.20 Updating puttyNG to 0.76

I may try a re-download and re-install to see if it adds it.  Don't want to use a Franken-copy.

**Comment by Kvarkas** [comment]
puttyng could be downloaded manualy from there: https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.78.0.10/PuTTYNG.exe

**Comment by simonai1254** [comment]
> ok, lets reopen till we will be 100% sure we address it properly

Just building the new version does not fix the underlying issue of keeping the dependencies up to date 😉 

Or should I create a new issue for that?

**Comment by Kvarkas** [comment]
technicly i think it was about putty key format to new, what solved by updating to new version so nothing we could do for such more, but if you think for dependency we may need an issue perhaps lets open new one so we dont misleed by naming ;)

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by mikeleblank** [comment]
> First of all @farosch, shame on you for that answer! That has everything to do with mRemoteNG not being up to date! Second, to solve the problem, go to Tools / Options in mRemoteNG, go to Advanced, check off "Use custom PuTTY path" and browse and pick the path to your putty.exe. You should be able to connect now.

1 hour trying, until I found you

**Comment by SpiralBrad** [comment]
Closed, yet this is still an issue?

Yeesh.

**Comment by simonai1254** [comment]
> Closed, yet this is still an issue?
> 
> Yeesh.

It hasn't made it into the official build, but only the nightly previews.

**Comment by SpiralBrad** [comment]
> It hasn't made it into the official build, but only the nightly previews.

Just noticed that, but admittedly it remains an issue, then.

Edit: well maybe not, but a 5 year old issue involving shipping highly outdated and insecure software that could be fixed with a simple update to the stable build... does not inspire confidence.

**Comment by Kvarkas** [comment]
its complicated to support old versions as keep in mind mostly its one-man-band and I am focused more in realise a new official version to make all new functionality available. However we have what we have
