### ISSUE TITLE
set key

### ISSUE THREAD

**Issue by 756616071** [mRemoteNG/mRemoteNG#2039]
## Steps to Reproduce (for bugs)
Hello, please ask a question, how is the password encrypted,

Where to set the encryption key

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
![image](https://user-images.githubusercontent.com/44856671/131782143-1bc9171b-cb8c-4bc7-9c37-e6a207a5e0b6.png)

**Comment by farosch** [comment]
You can set the encryption key by selecting the root connection tree node and take a look at the "connection settings":
![image](https://user-images.githubusercontent.com/22905106/146072208-8ad1d945-ce10-4ce9-8d36-79697b4944c1.png)

**Comment by 756616071** [comment]
I mean the password stored in the database
The secret key that generates this password
![image](https://user-images.githubusercontent.com/44856671/148234230-87a650c1-eb5e-46ff-85a5-1e79d727ec03.png)

**Comment by DoozyDoz** [comment]
> You can set the encryption key by selecting the root connection tree node and take a look at the "connection settings": ![image](https://user-images.githubusercontent.com/22905106/146072208-8ad1d945-ce10-4ce9-8d36-79697b4944c1.png)

This works as enough security for me 👌
