### ISSUE TITLE
copy/paste in sessions freeze mremote

### ISSUE THREAD

**Issue by federicozanardi** [mRemoteNG/mRemoteNG#204]
sometimes (not always), after copying some text (only text) to clipboard from my pc, when swtching focus to mremote cause the software to freeze for 30 seconds, then I am able to continue work and pasting data.

closing and reopening mremote temporanealy fix the issue 

using latest alpha but the bug is present on last public rel

**Comment by sparerd** [comment]
Thanks for the report. Does this happen even when small amounts of text are copied? A few characters/words?

I think that rdpclip.exe usually handles clipboard transfer between localhost and remotes, though I'm not sure if the library we use also uses that exe. Generally, restarting rdpclip.exe resolves things. If our library has a built in way to handle the shared clipboard, then restarting rdpclip just won't do anything.

There are some lines of code that hook into the system clipboard. We would have to dig a bit, but it would be worth checking out.

**Comment by federicozanardi** [comment]
even with simple phrases or a single word
for example when I copy/paste passwords from my keepass, or from a notepad or a link from browser

**Comment by jotatsu** [comment]
Candidate to verify in 1.8

**Comment by farosch** [comment]
Closing as stale. @OP please reopen if you still experience this issue.
