### ISSUE TITLE
Copy from server and paste to local PC

### ISSUE THREAD

**Issue by FelipeZimmermann2003** [mRemoteNG/mRemoteNG#2042]
When copying from server and trying to paste on local pc it is no longer leaving in the latest version. Version 1.77.2.41427

**Comment by Kvarkas** [comment]
please check settings

**Comment by FelipeZimmermann2003** [comment]
![Captura de tela 2021-09-08 105833](https://user-images.githubusercontent.com/90207835/132523452-ee9a8288-af6d-448e-9eb8-4b59ba5eb19d.png)

This is the configuration I use, in the previous version it worked, in the new version I can't make it work... I need some help.
In the rest mRemote is a great app.

**Comment by FelipeZimmermann2003** [comment]
![image](https://user-images.githubusercontent.com/90207835/132523958-a9343838-9ef7-4186-8dea-5e4e15b5caa6.png)

**Comment by Kvarkas** [comment]
Set audio capture to yes please and check

**Comment by FelipeZimmermann2003** [comment]
It worked, thank you... Very good application
