### ISSUE TITLE
Is there a way to open a local session on mRemoteNG on windows?

### ISSUE THREAD

**Issue by zactill** [mRemoteNG/mRemoteNG#2044]
Is there a way to open a local session on mRemoteNG on windows?

**Comment by Kvarkas** [comment]
hi, could you explain that you have in mind, don't get it

**Comment by cpiment** [comment]
What I do is to set up an "External Tool" pointing to a console emulator (ConEmu, Windows Terminal), and then configure a "New Connection" with protocol "External Tool". When you open that connection the console emulator starts and you have a local session.

ConEmu has the advantage that the application starts inside mRemoteNG window, but Windows Terminal always pops up a new window.

Hope this helps.

**Comment by nmat** [comment]
You just want to start a terminal in a mremoteng window? Without connecting to anything...?

**Comment by farosch** [comment]
We try to provide a way of integrating third party apps as far as we can, and it is reasonable.
We will never be able to make everything integrateable with mremote nor do we want to. This is a little feature that might be useful for some cases but will never work for everything.

**Comment by needleshaped** [comment]
Seems to depend on application, if it can be integrated.

Found PowerShell ISE can:

`%WINDIR%\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe`

https://iceburn.medium.com/external-tool-configurations-for-mremoteng-d84b1f644ce3
