### ISSUE TITLE
Update French translation

### ISSUE THREAD

**Issue by ejacquemoud** [mRemoteNG/mRemoteNG#2045]
Hi,

I noticed that the French translation for this awesome software was old and unaccurate and lots of strings are currently missing.
I began to clean, update and complete this translation in my local computer.

Could you please create a branch "french-translation", so I can work on it?
Or you can give me the right to push on the develop branch if you prefer. I'll modify just the French translation ressource file.

Thanks in advance :)

**Comment by Kvarkas** [comment]
hello, thanks for that, if you do a clone to you env. then finish just make PR and will merge it into dev

**Comment by ejacquemoud** [comment]
You're welcome!
I tried to create a translation branch, then commit and push but I'm getting a 403 error... I just completed the French translation; you'll find the related ressource file attached :)

[Language.fr.resx.zip](https://github.com/mRemoteNG/mRemoteNG/files/7142892/Language.fr.resx.zip)

**Comment by Kvarkas** [comment]
ok, will add to dev a bit later today, thanks

**Comment by Kvarkas** [comment]
added to dev branch
