### ISSUE TITLE
Immediate paste when using right click to copy

### ISSUE THREAD

**Issue by JonathonAnderson** [mRemoteNG/mRemoteNG#2050]
When I right-click an SSH session to copy text, it copies and immediately pastes what was copied back into the session.

## Expected Behavior
right-click should copy the selected text without also pasting

## Current Behavior
right-click causes copy and immediate paste back into the same SSH session

## Possible Solution
Don't know. Sorry :(

## Steps to Reproduce (for bugs)
1. Open an SSH2 session (happens to be to a Ubuntu 18.04 LTS server)
2. Highlight text
3. Right click

## Context
This is mostly an annoyance, but could cause problems if the wrong thing is highlighted and copy/pasted

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version: Windows 10 Pro 21H1 19043.1202 (Experience Pack 120.2212.3530.0)

**Comment by nmat** [comment]
hmmm isnt this a feature inside putty configuration?

![image](https://user-images.githubusercontent.com/383031/134677663-e454da01-7af3-4302-975c-c91add41b152.png)

**Comment by JonathonAnderson** [comment]
@nmat you are correct... I misunderstood how the copy feature works. I didn't realize it auto-copied on highlight.... been doing this wrong for so long SMH

https://documentation.help/PuTTY/using-selection.html

> PuTTY's copy and paste works entirely with the mouse. In order to copy text to the clipboard, you just click the left mouse button in the terminal window, and drag to select text. When you let go of the button, the text is automatically copied to the clipboard. [...]
> 
> Pasting is done using the right button. [...] When you click the right mouse button, PuTTY will read whatever is in the Windows clipboard and paste it into your session, exactly as if it had been typed at the keyboard. [...]

**Comment by nmat** [comment]
@JonathonAnderson to give you some extra know-how...

In Linux if you ever move over to that platform, this is a common behavior to select and paste text. Just a good to know thing
