### ISSUE TITLE
Check For Updates feature Shows Latest Version that is older than Installed Version

### ISSUE THREAD

**Issue by keithhuster** [mRemoteNG/mRemoteNG#2052]
I recently ran the **Check for Updates** command and the resulting output is incorrect (see the screenshot below).

![image](https://user-images.githubusercontent.com/42976208/134556612-d4fb0824-818a-4e4f-a42b-ab6fa0e4268e.png)

## Expected Behavior
* The **Installed version** value should always be less than or equal to the **Latest version**.

## Current Behavior
* The **Installed version** value is greater than the **Latest version**.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Open the mRemoteNG application (tested using version 1.76.20.24615).
2. Execute the **Help -> Check for Updates** menu command.
3. View the results of the Installed/Latest versions.

## Context
This required me to double check, via the mRemoteNG website, that I was actually using the latest version. Also, I am unsure if the update check will work at all based on these results.

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version:  Windows 10 Pro for Workstations 21H1 (19043.1237)

**Comment by sadden3194** [comment]
same here

**Comment by LIyoai** [comment]
duplicate #1853 #1909

**Comment by farosch** [comment]
Follow the above issue for follow-ups
