### ISSUE TITLE
Private key format too new

### ISSUE THREAD

**Issue by JJussi** [mRemoteNG/mRemoteNG#2055]
I have OpenSSH key pair, generated in Linux.  Format "ssh-rsa 3072 SHA256".
Used puttygen.exe 0.76.0.0 to create required .ppk file
When tried to use that file with version 1.76.20.24615, opening remote SSHv2 connection, PuTTYNG.exe 0.71.0.1 show me error message about key which format was too new.

I solved this downloading newest putty.exe and renaming it to puttyng.exe, replacing current puttyng.exe

## Expected Behavior
Open of connection, using provided ppk file

## Current Behavior
Error message about key file format too new

## Possible Solution
Pack newer version of puttyng.exe to the distribution (Windows) package

## Steps to Reproduce (for bugs)
1. Create keypair with ssh-keygen (ssh-rsa 3072 SHA256)
2. Convert that private key with the newest puttygen.exe
3. Configure mRemoteNG's Putty to use that file
4. Try to open an SSH session to the machine what accepts login only with key

## Context
Use my current SSH key to connect to destination

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64):  Windows 10 Enterprise x64, 10.0.19043 Build 19043

**Comment by LIyoai** [comment]
#2012

**Comment by farosch** [comment]
This is due to #2012 as @LIyoai pointed out.
Please follow this issue for updates.
