### ISSUE TITLE
Development dead again?

### ISSUE THREAD

**Issue by marcelmah** [mRemoteNG/mRemoteNG#2059]
Hi,

It's been over a month since anything changed, all builds are failing, even the .NET6 version (see pull request).
Wondering about the status of the project...

Was really exited about the new development :(

**Comment by Apollon-Theos** [comment]
Too many issues vs experience developers. Win ISSUES :(

**Comment by Kvarkas** [comment]
hello, not much PRs are coming so codding in one person is slow :) keep in mind what amount of issues we have and releasing a new version just to keep you attracted its a bit silly for me. However I do that I can to fix issues we are already faced and so far working branch is development and its building fine, let me know that issues you have with it?

**Comment by marcelmah** [comment]
Hi,

No problem if It's taking time, just haven't seen any changes for a while, where there used to be a couple every week or so.
That made me wonder... You say dev version is building fine, but these builds aren't public or maybe I don't know where to look?

this is showing only old versions: https://github.com/mRemoteNG/mRemoteNG/releases

**Comment by Kvarkas** [comment]
I was hit by covid :( fighting for a life almost a month, and manage to win (this time) now still recovering but filling much much better. dev version release comes as Nightly Build you may see as well on web site: https://mremoteng.org/download
also will update soon with correction for a update check then it will be possible select update channel.

**Comment by Apollon-Theos** [comment]
@Kvarkas Выздоравливай! :)

**Comment by marcelmah** [comment]
Hi, sorry to hear that! Hope you will be feeling 100% again soon.

The nightly also refers to a build months old: https://github.com/mRemoteNG/mRemoteNG/releases/download/v1.77.2-nb/mRemoteNG.24062021NB.rar

**Comment by Kvarkas** [comment]
nb idea is to release dev version to check issues before stable release but not promise to happened every night ;)

**Comment by Apollon-Theos** [comment]
every week or month ? :)

**Comment by Kvarkas** [comment]
Every Thursday after rain... :) as much as have an update or fix something, so technically random a bit :)

**Comment by lars18th** [comment]
Hi @Kvarkas ,

You think it's time to publish a new nightly build now?
I feel a lot of bugs are fixed from the lasted v1.77.2-nb build at 25 Jun 2021.

Thank you!

**Comment by Kvarkas** [comment]
working towards such, have few annoying errors with test related connections attributes and they are very sensible so want to fix first

**Comment by zollo** [comment]
Hope you're feeling better @Kvarkas !

**Comment by Kvarkas** [comment]
Yes, thanks, I am back to full power but its that term now then primary job required a lot of time as IT freeze is coming but we still do a release and nb should be soon as well so stay tuned! :)

**Comment by BlueBlock** [comment]
I'm interested in contributing some dev time. Is there a current developer able to spare some time to walk me through the finer points of the project design?
