### ISSUE TITLE
[to be close] KB2574819 missing but installed

### ISSUE THREAD

**Issue by vince2010091** [mRemoteNG/mRemoteNG#206]
Hi team,

I'm trying to install the software but i get an issue
MR installer says KB2574819 is missing but KB installer says it is already install
Please see attachement

Regards
Vincent

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

![install](https://cloud.githubusercontent.com/assets/1927789/19802559/9cb42d8e-9d04-11e6-887e-af812daaf099.PNG)
![kb](https://cloud.githubusercontent.com/assets/1927789/19802560/9cb4ce38-9d04-11e6-86dc-5a8f4d1cb123.PNG)

**Comment by vince2010091** [comment]
Sorry i made a mistake between the KB2574819 from prerequisites and the KB2592687

**Comment by MagicFab** [comment]
As a workaround, you can install while ignoring prerequisite checks in the installer. Provide IGNOREPREREQUISITES=1 as an argument to the installer on the cmd line.
