### ISSUE TITLE
Bug in 1.76, please check it in 1.77

### ISSUE THREAD

**Issue by Apollon-Theos** [mRemoteNG/mRemoteNG#2069]
First time mRemoteNG 1.76 cannot connect to server. Only after connect from MSTSC.
and second, maybe linked
after edit configuration "Hostname/IP" from name to IP, same bug.

## Expected Behavior
If create new connection, mRemoteNG can connect immediately, self, without make connect from MSTSC.

## Current Behavior
for all new connections need make connect trough MSTSC

## Possible Solution
maybe MSTSC make cache, that needed for mRemoteNG. Build this cache self, without MSTSC, or remove dependence.

## Steps to Reproduce (for bugs)

1. create new connection, for new server
2. try to connect with this connection - fault
3. connect to this server with MSTSC
4. try connect with created connection - seccess

## Your Environment

* Version used: 1.76.20 (2019-04-12):
* Operating System and version:  Windows 10 1909 x64 Ent

**Comment by LIyoai** [comment]
Try 2 times with a newly created connection, should also work. In 1.77 a timeout option was introduced, newer windows server >=2012(?) sometimes need a bit longer, then the fix timeout in 1.76 allows.
In 1.77 with 20 seconds timeout there should be no problem.

**Comment by farosch** [comment]
As @LIyoai said this issue has been solved in the develop branch already, as the timeout has been increased.
