### ISSUE TITLE
Feature request: Specify a target directory for external tools.

### ISSUE THREAD

**Issue by MaRRiK74** [mRemoteNG/mRemoteNG#207]
Option to specify in which directory an external tool is started, like 'target' in shortcuts:

![image](https://cloud.githubusercontent.com/assets/19833001/19804119/a6b0ea0e-9d0c-11e6-8421-1f883e04ba35.png)

Some tools open other .exe files from within the current directory, at this moment some tools i have installed fail to do that.

|  |  |
| --: | --- |
| Operating system | Windows 7 x64 |
| mRemoteNG version | 1.75 aplha 3 |

**Comment by sparerd** [comment]
This will be available in v1.76
