### ISSUE TITLE
Bug in 1.76 IPv6 not work

### ISSUE THREAD

**Issue by AhrimanSefid** [mRemoteNG/mRemoteNG#2071]
Hi 
thank you for software.
very try IPv6 not working.

**Comment by farosch** [comment]
@AhrimanSefid 
Does it work in the latest preview release?
https://mremoteng.org/download

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/145599299-8f8b14db-460f-4689-986b-f15db9c91341.png)


![image](https://user-images.githubusercontent.com/1332246/145599413-7d9667a1-4715-4b38-8897-3d3e45191793.png)

**Comment by farosch** [comment]
@AhrimanSefid Use the link to download the latest version:
https://mremoteng.org/download

Also can you please show the configuration settings for your connection? It looks like you entered the IPv6 inside the Name field instead of the Hostname/IP field.

**Comment by farosch** [comment]
Closing as OP does not respond
