### ISSUE TITLE
Trying to integrate External Powershell 

### ISSUE THREAD

**Issue by mtloaprhn** [mRemoteNG/mRemoteNG#2072]
Hi team,

I created a new external too to can connect by ssh in Azure VM.
The app working good, but only on a separate window. If I check "Try to integrate" nothing happen. Any error or other. 
I would like to use my powershell shell into the mremoteng embedded window.

My powershell app is : powershell.exe -command az login ; az ssh --ip x.x.x.x

## Your Environment

* Version used: 1.76.20 (I tested also on the last nightly build, but same behavior)
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11

Thanks in advance for your advices :)

Best

**Comment by LIyoai** [comment]
#768

**Comment by LIyoai** [comment]
#649
