### ISSUE TITLE
.net 6 and System.Web.Services

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2073]
Just a heads up, your recent code changes to .net 6 breaks functionality of the secret server api dll. it relies on System.Web.Services for SOAP calls which is deprecated and not available in .net 6 / .net core.
i'm aware of this and will fix it when i find time. if you choose to make a public release of mremote before i can do this please remove the secret server stuff. it does not work in this state. 
cheers

**Comment by Kvarkas** [comment]
thanks for that, I would like to release before new year perhaps several nb before but yes will be glad if you found a time to have a look how to make it work.

**Comment by tecxx** [comment]
i fixed it today, here is the PR
https://github.com/mRemoteNG/mRemoteNG/pull/2074

but i'm not sure if this PR is correct. shows 14 commits, which include merging upstream changes to my own repo... i guess i will retry this tomorrow from a clean repo.
