### ISSUE TITLE
Multiple Credentials 

### ISSUE THREAD

**Issue by njohnjoel** [mRemoteNG/mRemoteNG#2082]
Not able to manage multiple credentials for servers thats are of diff region ... I have to stick to 1 username/password which is a real pain .... 
FYR - check ASG Desktop 
https://www.asg.com/en/Products/IT-Systems-Management/Applications-Management/ASG-Remote-Desktop.aspx

**Comment by farosch** [comment]
Just duplicate your connection and set different username/password for each connection.
See https://mremoteng.readthedocs.io/en/latest/ for more information.

**Comment by Kvarkas** [comment]
what ASG surprisely look like as mRemoteNG :D
