### ISSUE TITLE
Application crashes, after the update file is downloaded

### ISSUE THREAD

**Issue by Vest** [mRemoteNG/mRemoteNG#2087]
When the build is "Debug" (not portable), the application crashes, after the user attempts to install it:
![application crash](https://user-images.githubusercontent.com/1671049/146408443-f4198335-c1f7-4cbb-8161-843779672843.png)

The exception is captured by VS logs:

```InformationMsg: Saving connections...
InformationMsg: Successfully saved connections
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Diagnostics.Process.dll
'mRemoteNG.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\System.Collections.Immutable.dll'. 
ErrorMsg: The update could not be started.
An error occurred trying to start process 'C:\Users\myUser\AppData\Local\Temp\qyjcsiy3.msi' with working directory 'C:\dev\mRemoteNG\mRemoteNG\bin\x64\Debug'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at mRemoteNG.App.Shutdown.RunUpdateFile() in C:\dev\mRemoteNG\mRemoteNG\App\Shutdown.cs:line 123
   at mRemoteNG.App.Shutdown.StartUpdate() in C:\dev\mRemoteNG\mRemoteNG\App\Shutdown.cs:line 112
[END] - 12/16/2021 17:16:44
The program '[14962] mRemoteNG.exe' has exited with code 0 (0x0).
```

## Expected Behavior
The installer window should appear:
![installer window](https://user-images.githubusercontent.com/1671049/146408897-8cb6a08f-3227-45e4-87c7-3232e28ef23d.png)

## Current Behavior
The application crashes.

## Possible Solution
I have found a possible solution on SO, it says that the process should be started from shell: https://stackoverflow.com/questions/46808315/net-core-2-0-process-start-throws-the-specified-executable-is-not-a-valid-appl

## Steps to Reproduce (for bugs)
1. Change the version to something old
2. Run "Debug" build (not portable)
3. Download and install the update file

## Context
The application cannot be updated by its own installer

## Your Environment
* Version used: 1.77.2
* Operating System and version: Windows 10 1909 18363.1854 x64

**Comment by Vest** [comment]
I can prepare a PR, or you can fix it with a simple line. I hope.

**Comment by Kvarkas** [comment]
Its like you cant cut a branch on that you are sitting now :) if PR will be valid its will be easy task to merge

**Comment by Vest** [comment]
@Kvarkas, done!
