### ISSUE TITLE
Cannot pass arguments with a dollar sign.

### ISSUE THREAD

**Issue by annahri** [mRemoteNG/mRemoteNG#2095]
## Expected Behavior

Pass the arguments with the dollar sign.

## Current Behavior

Using an external tool, passing any arguments that contain a dollar sign will not work.

## Possible Solution

Add escaping mechanism for the dollar sign.

## Steps to Reproduce (for bugs)

1. Create a new external tool.
2. Fill file field with powershell.exe
3. Set the arguments as `echo dollar$sign; echo dollar\$sign; echo dollar^$sign; sleep 100`
4. Run the tool.

![image](https://user-images.githubusercontent.com/30897918/146687217-5683e260-d4aa-42bc-b311-a1e9dc8fa4b1.png)

## Context

I have an external tool that passes the %PASSWORD% field, but some of my connections contain a dollar sign in the password.

## Your Environment

* Version used: 1.76.20 
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1909

**Comment by Vest** [comment]
Does this work for powershell (without mRemoteNG)? I have tried this, and here is the screenshot from powershell.exe

![Doesn't work](https://user-images.githubusercontent.com/1671049/146689478-e4205d3b-424e-4a92-a23a-0a04287a371e.png)

Have you tried to escape the dollar sign with a backtick --> **`**? https://stackoverflow.com/a/61736893/7482578

**Comment by Kvarkas** [comment]
use %% to disable check of special characters: https://github.com/mRemoteNG/mRemoteNG/issues/1104

**Comment by annahri** [comment]
Reopening this, the actual usage was this:
![image](https://user-images.githubusercontent.com/30897918/148741493-1c6ddb5b-d14a-4266-b666-820de305b33e.png)

When the password contains a dollar sign, the variable expands to something I don't know. But, the external tool fails for sure.

**Comment by Kvarkas** [comment]
hi, have you tried using **%!Password%** (notice the !)

**Comment by annahri** [comment]
Hi, let me try it. As far as I remember, I've tried any escaping methods
explained in the documentation.

**Comment by annahri** [comment]
Unfortunately, it doesn't work.

**Comment by annahri** [comment]
Ah, turns out I need single quotes. `'%PASSWORD%'`. It's bash that expands the variable, not mRemote.
