### ISSUE TITLE
RDP to logged in PCs, requires me to log off, before I get full control

### ISSUE THREAD

**Issue by sutty550e** [mRemoteNG/mRemoteNG#210]
I hope I'm taking the correct approach by posting this issue here. If not, please just answer with where or how I should ask such a question.

Forgive me if this is a long description, but I don't wat to leave anything out.

I run a Windows 7 VM Ware virtual machine, and the mRemoteNG application sits on that PC. This set-up is years old, and I have had no issues. I use all sorts of features, but the majority of my work is when connecting to other Windows 7 PCs by RDP, but they are all physical PCs. For years this method has worked perfectly for me. Probably I started out with just mRemote. 

Now though a very strange issue has developed as follows. If I reboot a machine, or remotely choose log off, and reconnect, everything works perfectly when I log back in, but if I lose connection and it reconnects automaticaly, or if I reconnect to it, or if I close a tab, leaving the destination PC logged in, and then later reconnect, I have alsmost no control over the target PC.

I can still invoke Crtl Alt Del, by using Ctrl Alt End, and if I then log off the PC remotely, or reboot it, when I reconnect it is perfect again, until I choose disconnect, or if it disconnects itself, perhaps due to a poor connection, or similar, for example.

I've even tried a much more recent VMWare player, just to test that, but that had no bearing on the issue either. Then again I didn't really expect it too.

I don't know what might have changed, but I have tried uninstalling and re-installing mRemoteNG. I have used the latest version, and even the beta version, but it doesn't change anything. Always the same behaviour.  

Has anyone else experienced this issue? Should I try to go back a few versions, and if so how do I find a suitable older version to try. Certainly there were no issues in the previous versions that caused me a problem.

I'm just going to try a new connection document, but if that does the trick it will be very painful for me to ressurrect all the data that is in my exisiting connection file.

Thanks for looking, and thanks all for the great tool that has been so useful to me for so long.

Best regards

Sutty

**Comment by sutty550e** [comment]
I should also say, if I make an RDP connection outside of mRemoteNG, using just RDP, the version I had to upgrade to in order to make use of the latest version of mRemoteNG, I have no such issue.

**Comment by sparerd** [comment]
What sorts of things stop working when this occurs? Some areas of the
screen becoming un-clickable? Some key strokes not being transferred?

- David Sparer

**Comment by sutty550e** [comment]
Thanks for checking in. Yes, often I cannot close windows with the X. Some menus in windows don't function, and for example I can never click the start button. I can bring the start button up by pressing Alt Home, but I cannot ever click it. In task manager I cannot reselect the applications tab after having selected one of the others. The other tabs will all remain selectable, but not Applications. Often I cannot click highlight, or select any of the icons on the desktop. As soon as I choose log off the remote PC, and log back in, they all become active again, and it is just like I was sat in front of the PC, as per normal.

**Comment by sparerd** [comment]
Most of the UI elements you mentioned are at the periphery of the RDP
window. Is the task manager in the center of the screen or on more on a
side? Essentially - does it seem like there's an invisible frame around
your RDP window?

**Comment by sutty550e** [comment]
Okay, it looks like you are onto something. It would appear to be the left and top edges. If I can still grab a window, such as task manager, and I move it to the right, I can then access the things on the left. If it's low I can select its top menu items and the cross, but if I move it to the top I cannot access any of the things at the top. It is exactly like there is a strip to the left and across the top which is 'hiding' my access. Again this is only when I reconnect to a PC that is already logged in. Force a remote log off and start again, and all is perfect.

To prove, kind of, that it is only the left and top, I can always access the small 'Show Desktop' button in the bottom right hand corner of the screen, at the end of the task bar.

Hopefully this extra info will help narrow it down.

Once again your assistance is much appreciated.

**Comment by sparerd** [comment]
Is SmartSize turned on for those connections? Does toggling it have any affect on what you are experiencing?

**Comment by sutty550e** [comment]
Smartsize is on for all all connections. Changing/toggling the setting has no effect. Making the window size change, with a different resolution, has no effect either, so even when I have to scroll, because of a resolution mismatch, these areas of the screen remain inaccessible/unclickable. A very low resolution, giving me a window in the middle of the active tab, so it has a blank surround of its own, within the tab, still doesn't make any difference. Always the top and left are inaccessible.

**Comment by jcefoli** [comment]
Do you happen to be using DPI scaling by any chance? (aka the following is not set to 100%)

![image](https://cloud.githubusercontent.com/assets/6618013/19868508/bb4241ec-9f7e-11e6-81ec-8e91ab50107b.png)

**Comment by sutty550e** [comment]
I was, though I had no idea I'd made that change. If it can be invoked by some odd key presses, I must have done that, because I'm sure I didn't do it deliberately.

Anyway, great news, because that cracked it. Reset it to 100% and now it is working exactly as it should and as it always did.

Thank you so much for that suggestion.

I feel a little blind now, after having got used to it, and the resolution of my screen is too high, but maybe I can adjust that, just using normal screen resolution options, without causing an issue. Normally laptops say, that is not the optimal resolution for the display, but this one doesn't seem to mind. I'll experiment with it tomorrow and see if changing the overall resolution, rather than scaling it, will give me a better outcome.

Thanks again, and thanks sparerd for walking me through the steps to identify exactly what the issue really was, i.e. the invisible border issue.

Nice one guys.

**Comment by sutty550e** [comment]
I couldn't resist taking a look at it right now, and I was wrong that my laptop doesn't whinge about sub-optimal resolution, however I found a much lower setting with the exact same aspect ratio and as far as I can see there is nothing negative about running it at this lower resolution, but there is a significant plus, in that I can actually read it, lol.

Having changed it to a readable resolution, but having left the scaling at 100%, everything now seems perfect.

Honestly I can't thank you enough.

Awesome!

**Comment by sparerd** [comment]
Glad to hear @sutty550e !

Made a known-issue entry for later reference: https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#cannot-click-some-ui-elements-in-an-rdp-connection-window

Thanks for the assist @jcefoli , good call.
