### ISSUE TITLE
Sub OU LDAP Import

### ISSUE THREAD

**Issue by matthiaswolf1984** [mRemoteNG/mRemoteNG#211]
There is one big feature that I'm really missing since years.
If I import from Active Directory there should be a function to import the OU and all Sub-OUs with all clients.
That would make the import so much easier!

Is there any chance that this comes true in future?

**Comment by kmscode** [comment]
Someone attached code to a JIRA request: https://mremoteng.atlassian.net/browse/MR-1000

This was done before some of the code was changed to move away from TreeNode's - so we can't just check this in any more...

Original and "new" file attached.

Looks like mRemoteV1\Config\Serializers\ActiveDirectoryDeserializer.cs and maybe mRemoteV1\Config\Import\ActiveDirectoryImporter.cs will need to have the changed ported into them...

Created branch: https://github.com/mRemoteNG/mRemoteNG/tree/211_AD_Sub_OU_Import

[ActiveDirectory.zip](https://github.com/mRemoteNG/mRemoteNG/files/576667/ActiveDirectory.zip)

**Comment by matthiaswolf1984** [comment]
Ok, thank you for adding this to the 1.75 final milestone.
Hopefully this can be changed in 1.75.
I have like 250 Servers in many OUs in AD and I always find it very hard
to keep this updated in mRemoteNG because I have to import each individual OU.

**Comment by kmscode** [comment]
Just to confirm... You'd like the tree to look like this on the AD import if you were starting at the DOMAIN level as listed below:
```
DOMAIN
│   SERVER01
│   SERVER02    
│
└───OU01
│   │   SERVER03
│   │   SERVER04
│   │
│   └───OU02
│       │   SERVER05
│       │   SERVER06
│   
└───OU03
    │   SERVER07
    │   SERVER08
```

I'm pretty sure that I've got all the code ported over to the new and it pulls OU recursively. The tree that gets built seems to depend on how servers and OUs are named... So:
```
DOMAIN
│   A-SERVER01
│   B-SERVER02    
│
└───C-OU01
│   │   A-SERVER03
│   │   B-SERVER04
│   D-SERVER05
│   E-SERVER06   
└───F-OU03
    │   SERVER07
    │   SERVER08
```

Where A-SERVER01, A-SERVER02, C-OU01, D-SERVER05, E-SERVER06 and F-OU03 are all at the same "level" within the tree, but imported in alphabetical order. The stuture is ultimately "good" and the OU nodes can be moved (to force them all to the top and any servers at the domain level will be under (UNDER, not WITHIN) the OU folders.

I'd screenshot it, but I'd have to black out basically everything so it's kind of pointless.

**Comment by matthiaswolf1984** [comment]
Hello, 
I've tried out the current beta, but unfortunately the import is not as expected.
First of all it only imports on OU deep.
So for example:

**MainOU**
 -- Sub1
    -- Sub2

**Will only import:**
MainOU
 -- Sub1

The other issue is, that it does only import the OUs, but no host.
It will result in empty OUs.

**Comment by kmscode** [comment]
hmm... It was working properly when I originally checked it in and tested... But I'm getting the same results as you now... I will look into this further...

**Comment by matthiaswolf1984** [comment]
Hi, 

any news on this issue?

**Comment by jschlie** [comment]
Hi, very interested in this feature.  Any word on if it's been resolved in the latest beta?

**Comment by kmscode** [comment]
I don't have a solid ETA, but this will be fixed prior to the next beta/release candidate - assuming it doesn't drive me nuts debugging it. I just haven't had the time yet... Hopefully at some point this week. Sorry for the delay.

**Comment by jschlie** [comment]
No problem, totally get it.  Fyi, I put in a new issue on the domain name being filmed in with an erroneous name in beta 3.

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 13, 2016 at 9:52, Sean Kaim<notifications@github.com> wrote:   
I don't have a solid ETA, but this will be fixed prior to the next beta/release candidate - assuming it doesn't drive me nuts debugging it. I just haven't had the time yet... Hopefully at some point this week. Sorry for the delay.

**Comment by jschlie** [comment]
Or, nevermind, you already replied.

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 13, 2016 at 9:52, Sean Kaim<notifications@github.com> wrote:   
I don't have a solid ETA, but this will be fixed prior to the next beta/release candidate - assuming it doesn't drive me nuts debugging it. I just haven't had the time yet... Hopefully at some point this week. Sorry for the delay.
