### ISSUE TITLE
SSH Console screen jumps off on ultra-wide monitor

### ISSUE THREAD

**Issue by marwain91** [mRemoteNG/mRemoteNG#2110]
When using an ultra-wide monitor (5120x1440), the SSH console screen jumps off the viewport assigned for this. When exiting the console to another window and returning back, the console jumps off the viewport even more until it disappears completely.

![screenshot](https://user-images.githubusercontent.com/9109986/148091551-178b7b3b-46d6-49d7-8350-06730876a140.png)

## Expected Behavior
The screen should remain in the viewport.

## Your Environment
* Version used: 1.76.20
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11 21H2, build 22000.376 (but this behavior was seen on W10 as well)

**Comment by marwain91** [comment]
just found out this is probably a duplicate of this: https://github.com/mRemoteNG/mRemoteNG/issues/2047

**Comment by Kvarkas** [comment]
Thanks yes its duplicate, currently don't have extra wide monitor, but will think how to test it.
