### ISSUE TITLE
Installed version newer than reported "Latest version"

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2111]
## Expected Behavior
Using the built-in "Check for Updates" menu item should provide the correct information.

## Current Behavior
It reports I have installed version 1.77.1.27654 and that the "Latest version" is 1.76.11.40527.

## Possible Solution
It should should that the "Latest version" is equal to or newer than my installed version.

## Steps to Reproduce (for bugs)
From "Help" menu item select "Check for Updates".

## Context
I can't tell if a newer version is available or not or if an update is available.

## Your Environment
* Version used:  1.77.1.27654
* Operating System and version:  Windows 10 Enterprise 2004 x64

**Comment by LIyoai** [comment]
Check  #1853

**Comment by pauldurham** [comment]
Thank you.
