### ISSUE TITLE
Default username/password/domain fails to work

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2112]
## Expected Behavior
I have set a default username/password/domain and turned inheritance on.  However, when I try to connect to any servers it still asks for my password.  The domain field has no slashes in it.  I have turned inheritance on for everything.  Manually entering my password at login is successful.

## Your Environment
* Version used:  1.77.1.27654
* Operating System and version:  Windows 10 Enterprise 2004 x64 to Windows Server Standard 2016 x64.

**Comment by Kvarkas** [comment]
hi, please try 1.77.2 nb version

**Comment by LIyoai** [comment]
Maybe test with a connection without inheritance and set the credentials on this connection directly to see if it is an issue with inheritance or a general issue.

**Comment by Kvarkas** [comment]
closing as no response from user
