### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by betepon** [mRemoteNG/mRemoteNG#2122]
Yesterday, the installed product version v1.76.20 stopped running. Downloading versions v1.77.1 and v1.77.2-nb  Did not help with subsequent installation. Downloaded the portable version v1.76.20. Works great.
When I try  installed product to start I get two errors.

ERROR 1

Application: mRemoteNG.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception Details: System.Xml.XmlException
   в System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   в System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   в System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   в System.Xml.XmlTextReaderImpl.ParseText()
   в System.Xml.XmlTextReaderImpl.ParseElementContent()
   в System.Xml.XmlTextReaderImpl.Read()
   в System.Xml.XmlTextReader.Read()
   в System.Xml.XmlTextReaderImpl.Skip()
   в System.Xml.XmlTextReader.Skip()
   в System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   в System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   в System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   в System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   в System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Сведения об исключении: System.Configuration.ConfigurationErrorsException
   в System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   в System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   в System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   в System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Сведения об исключении: System.Configuration.ConfigurationErrorsException
   в System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   в System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   в System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   в System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   в System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   в System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   в System.Configuration.ConfigurationManager.GetSection(System.String)
   в System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   в System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   в System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   в System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   в System.Configuration.SettingsBase.get_Item(System.String)
   в System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   в System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   в mRemoteNG.Settings.get_SingleInstance()
   в mRemoteNG.App.ProgramRoot.Main(System.String[])

ERROR 2

Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, timestamp: 0x5cb09552
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, timestamp: 0xc79f51a9
Exception code: 0xe0434352
Error offset: 0x0012b662
Faulting process ID: 0x2380
Faulting application start time: 0x01d8093414354156
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: b8a9285f-0a72-41ff-9b5e-2638f05af7b7
Full name of the failed package:
Application ID associated with the failed package: 1000

I ask for your help and support

* Version used:
* Operating System and version Windows 10 Pro  21H2   19044.1466

**Comment by simonai1254** [comment]
Hi

Did you last install windows updates lately? Could it be that your connection configuration file is corrupt? 

Please try to uninstall mRemoteNG completely (and check that the Folders "C:\Program Files (x86)\mRemoteNG" and "%appdata%\mRemoteNG" are empty - the later one you might want to backup first). 
After the complete uninstallation please install mRemoteNG again and tell us if it now works now.

**Comment by Kvarkas** [comment]
Thanks, its happening then for some reasons its not able to load connection file (was moved) but its "remember" where it was last time and try to load it, planning to fix that in coming nb

**Comment by betepon** [comment]
Latest update installed. I think I have a problem after update windows.
I trying uninstall and write to you.

пт, 14 янв. 2022 г., 13:42 Simon Monai ***@***.***>:

**Comment by betepon** [comment]
Make a complete Uninstall. Remove folder  "%appdata%\mRemoteNG" manually.
"C:\Program Files (x86)\mRemoteNG" remove automatic.
After Then reinstall programm. And Have Error
- <#> <Event xmlns="*http://schemas.microsoft.com/win/2004/08/events/event
<http://schemas.microsoft.com/win/2004/08/events/event>*">
- <#> <System>
  <Provider Name="*.NET Runtime*" />
  <EventID Qualifiers="*0*">1026</EventID>
  <Version>0</Version>
  <Level>2</Level>
  <Task>0</Task>
  <Opcode>0</Opcode>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="*2022-01-15T22:40:21.5343969Z*" />
  <EventRecordID>16207</EventRecordID>
  <Correlation />
  <Execution ProcessID="*0*" ThreadID="*0*" />
  <Channel>Application</Channel>
  <Computer>DESKTOP-QBFDVV9</Computer>
  <Security />
  </System>
- <#> <EventData>
  <Data>Приложение: mRemoteNG.exe Версия платформы: v4.0.30319 Описание.
Процесс был завершен из-за необработанного исключения. Сведения об
исключении: System.Xml.XmlException в
System.Xml.XmlTextReaderImpl.Throw(System.Exception) в
System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[]) в
System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32
ByRef) в System.Xml.XmlTextReaderImpl.ParseText() в
System.Xml.XmlTextReaderImpl.ParseElementContent() в
System.Xml.XmlTextReaderImpl.Read() в System.Xml.XmlTextReader.Read() в
System.Xml.XmlTextReaderImpl.Skip() в System.Xml.XmlTextReader.Skip() в
System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
в
System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil,
System.String, Boolean, System.String,
System.Configuration.OverrideModeSetting, Boolean) в
System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil,
System.String, Boolean, System.String,
System.Configuration.OverrideModeSetting, Boolean) в
System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
в System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
Сведения об исключении: System.Configuration.ConfigurationErrorsException в
System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean) в
System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
в System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors() в
System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object,
System.Configuration.Internal.InternalConfigEventArgs) Сведения об
исключении: System.Configuration.ConfigurationErrorsException в
System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object,
System.Configuration.Internal.InternalConfigEventArgs) в
System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
в
System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String,
System.Configuration.BaseConfigurationRecord) в
System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String,
Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object
ByRef) в
System.Configuration.BaseConfigurationRecord.GetSection(System.String) в
System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
в System.Configuration.ConfigurationManager.GetSection(System.String) в
System.Configuration.ClientSettingsStore.ReadSettings(System.String,
Boolean) в
System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,
System.Configuration.SettingsPropertyCollection) в
System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
в System.Configuration.SettingsBase.GetPropertyValueByName(System.String) в
System.Configuration.SettingsBase.get_Item(System.String) в
System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
в System.Configuration.ApplicationSettingsBase.get_Item(System.String) в
mRemoteNG.Settings.get_SingleInstance() в
mRemoteNG.App.ProgramRoot.Main(System.String[])</Data>
  </EventData>
  </Event>


And one More


- <#> <Event xmlns="*http://schemas.microsoft.com/win/2004/08/events/event
<http://schemas.microsoft.com/win/2004/08/events/event>*">
- <#> <System>
  <Provider Name="*Application Error*" />
  <EventID Qualifiers="*0*">1000</EventID>
  <Version>0</Version>
  <Level>2</Level>
  <Task>100</Task>
  <Opcode>0</Opcode>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="*2022-01-15T22:40:21.6820160Z*" />
  <EventRecordID>16208</EventRecordID>
  <Correlation />
  <Execution ProcessID="*0*" ThreadID="*0*" />
  <Channel>Application</Channel>
  <Computer>DESKTOP-QBFDVV9</Computer>
  <Security />
  </System>
- <#> <EventData>
  <Data>mRemoteNG.exe</Data>
  <Data>1.76.20.24615</Data>
  <Data>5cb09552</Data>
  <Data>KERNELBASE.dll</Data>
  <Data>10.0.19041.1466</Data>
  <Data>c79f51a9</Data>
  <Data>e0434352</Data>
  <Data>0012b662</Data>
  <Data>3c54</Data>
  <Data>01d80a60e0ebcc32</Data>
  <Data>C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe</Data>
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
  <Data>9991ec10-bd6c-46ff-b196-1a1213f957e8</Data>
  <Data />
  <Data />
  </EventData>
  </Event>


пт, 14 янв. 2022 г. в 13:42, Simon Monai ***@***.***>:

**Comment by Kvarkas** [comment]
that problem is not for mRemoteNG it self, but its not able for some reason to get access to place where it remember was confCons.xml (usually it in C:\Users\{userName}\AppData\Roaming\mRemoteNG) if it was deleted it may not able to find it so crash.
Ping me on [chat](https://gitter.im/mRemoteNG/TechChats) if need more help on that (с радостью помогу)

**Comment by betepon** [comment]
in C:\Users\betepon\AppData\Roaming\mRemoteNG i have only mRemoteNG.log = 0
bytes. What file must be here and where can I download it?
вс, 16 янв. 2022 г. в 19:36, Dimitrij ***@***.***>:

**Comment by Kvarkas** [comment]
> can I download it

just create confCons.xml and past into it such content:
```
<?xml version="1.0" encoding="utf-8"?>
<mrng:Connections xmlns:mrng="http://mremoteng.org" Name="Connections" Export="false" EncryptionEngine="AES" BlockCipherMode="GCM" KdfIterations="10000" FullFileEncryption="false" Protected="byGD6iaGM+SU8zHzIghEYHUf55xbyogNaG0ayZr3CzHIJlwiMZo9VOGgl9WPm58O4h+yzn9A3leqT6IepryhJsoc" ConfVersion="2.7" />

```
after that it should allow you to start app, and you can modify you settings, at the moment I am working to fix such,

**Comment by Kvarkas** [comment]
I think issue may happened as well the its not able to decrypt file properly, added additional check. Have a look to late nb if that issue will gone for you.

**Comment by betepon** [comment]
I create confCons.xml and past into it content
But I have the same problem.
Now I use portable version without any problem. But I have a problem with
the version installed on the same computer.

**Comment by Kvarkas** [comment]
Interesting, could you try to do such:
use portable to create confCons.xml and save it into C:\Users\betepon\AppData\Roaming\mRemoteNG then try to run installed version? I am currently unable to reproduce same on my system :(

**Comment by betepon** [comment]
confCons.xml portable contain this

<?xml version="1.0" encoding="utf-8"?>
<mrng:Connections xmlns:mrng="http://mremoteng.org" Name="Подключения"
Export="false" EncryptionEngine="AES" BlockCipherMode="GCM"
KdfIterations="1000" FullFileEncryption="false"
Protected="QYO1ztVchU9R5j72q2Ld2IbORp8vhjbADnWixM8jmvBK9OT0rO6769z3Dc0PnRLqWBFjxk2/Gzkv7qPLBQnf+6jc"
ConfVersion="2.6" />

Same error

пн, 17 янв. 2022 г. в 21:29, Dimitrij ***@***.***>:

**Comment by Kvarkas** [comment]
Sorry, cant reproduce :( if I save file content as you provide - its open it perfectly, delete file - then on start its asking to create new - all as expected... 
Are you sure you installed this version: [2022.01.07-1.77.2-nb.mRemoteNG-Installer.msi](https://github.com/mRemoteNG/mRemoteNG/releases/download/2022.01.07-1.77.2-nb/2022.01.07-1.77.2-nb.mRemoteNG-Installer.msi) ?

**Comment by Kvarkas** [comment]
@betepon check if new nb install uninstall will fix that issue for you?

**Comment by betepon** [comment]
Problem is SOLVED I was uninstalled product by WiseUninstaller. And Find
some folder in Local and some folder in Roaming. I removed it all (I
already have a backup). And after installation version  v1.76.20 the
program started working normally.
Realy thanks to the good product. Maybe someone  help this solution.


вт, 18 янв. 2022 г. в 18:13, Dimitrij ***@***.***>:
