### ISSUE TITLE
Color coding of the Server Name font in the tree view.

### ISSUE THREAD

**Issue by mlatham23** [mRemoteNG/mRemoteNG#2124]
I would like to be able to right click on a connection name and change the color of the font displayed in the connections tree.  I am onboarding an new employee and I would like to be able to color code some of the connections to help him understand how the server fits into our architecture.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Kvarkas** [comment]
That was planed to implement in coming build

**Comment by farosch** [comment]
Duplicate of #281
