### ISSUE TITLE
Time to create a new release?

### ISSUE THREAD

**Issue by mpowrie** [mRemoteNG/mRemoteNG#2127]
The last stable release was way back in 2019 - v1.76.20. There have been a ton of improvements since then.
The majority of users will see this as the latest release, and won't have the time, expertise or inclination to either pick a later release build, or build themselves from source, so would not benefit from all the work that has come since then.

So - time to create a new stable release?

**Comment by simonai1254** [comment]
It's in the making. I assume with the next nightly build the 1.77 will be promotet to stable. 
The thing here is that it's mostly only one active developer and with proper testing this requires a little more time than usual...

**Comment by mpowrie** [comment]
Thanks! Closing issue....

**Comment by Kvarkas** [comment]
we are still have several annoing issues that we know not working so we want fix them then do a release
