### ISSUE TITLE
2022.01.07-1.77.2-nb Quick Connect broken

### ISSUE THREAD

**Issue by newmrac** [mRemoteNG/mRemoteNG#2137]
After update to 1.77-nb Quick Connect panel disappeared. Possible to enable only with program restart.
After enabling, it is impossible to use: I entering IP or short name or full name of server, click on SSH2 or RDP, receive error: Cannot open connection: no hostname specified

## Expected Behavior
1. Possibility to enable\disable this panel without program restart
2. Possibility to use quick connect as in old versions

## Current Behavior
Error: Cannot open connection: no hostname specified

## Possible Solution
Probably hostname from field not gets correctly

## Steps to Reproduce (for bugs)
1. Enable Quick connect panel
2. Enter server name
3. Choose protocol (RDP\SSH2)
4. Error appearing

## Your Environment
Windows 11 x64 en-us

**Comment by Kvarkas** [comment]
check wtih new nb tonight

**Comment by matejbolko** [comment]
have the same problem as @newmrac

**Comment by cra3yk** [comment]
I have the same problem (Quick Connect -> RDP -> ip address of windows with RDP)
The error is: Unable to open connection: hostname not specified! (which is not true)

**Comment by simonai1254** [comment]
> check wtih new nb tonight

@Kvarkas You did not release a new build, so I guess It could not be tested so far

**Comment by hunnymonster** [comment]
Have the same issue (and same lack of new build)

**Comment by DrumSlayers** [comment]
Issue still existing in [20220107 Nightly build](https://github.com/mRemoteNG/mRemoteNG/releases/tag/2022.01.07-1.77.2-nb)

**Comment by simonai1254** [comment]
> Issue still existing in [20220107 Nightly build](https://github.com/mRemoteNG/mRemoteNG/releases/tag/2022.01.07-1.77.2-nb)

Yes, we are waiting for 1.77.3-nb which should fix it...

**Comment by Kvarkas** [comment]
hello sorting some mess with options, planning to push nb this weekend

**Comment by dimangelid** [comment]
Same issue here with 1.77.2 Nightly Build, at a brand new Windows 10 Pro 21H2 installation.

When do you plan to release a new version with these issues fixed @Kvarkas ?

**Comment by ivantiglao** [comment]
Same issue. 

OS: Win 10 64 build
Version:  1.77.2

![image](https://user-images.githubusercontent.com/53462528/165680736-8ee496db-1e15-4b37-93c0-35c9091d1392.png)

**Comment by dimangelid** [comment]
> Same issue here with 1.77.2 Nightly Build, at a brand new Windows 10 Pro 21H2 installation.
> 
> When do you plan to release a new version with these issues fixed @Kvarkas ?

Hello @Kvarkas , do you have any plans for releasing version 1.77.3-nb ?
