### ISSUE TITLE
Create user manual documentation for the Port Scan feature

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#214]
Create documentation for this feature which may include:
- What the feature is / what it does
- Example use cases / when would it be useful
- Where it can be found / activated
- What options are available
- Common questions / "gotcha's"

Prepare text in Markdown format for inclusion in the [User Manual Wiki](https://github.com/mRemoteNG/mRemoteNG/wiki/User%20Manual)

**Comment by benwa** [comment]
First version [here](https://github.com/mRemoteNG/mRemoteNG/wiki/Port-Scan).  Once it's okay I'll link it in the Wiki under [User Manual](https://github.com/mRemoteNG/mRemoteNG/wiki/User-Manual).
