### ISSUE TITLE
Windows 11 - clicking main windows does not revel itself

### ISSUE THREAD

**Issue by shashisadasivan** [mRemoteNG/mRemoteNG#2141]
In Windows 11, when there are multiple full screen sessions available and you want to go back to the main screen i.e. the list with all the connections, it does not bring it up.

## Expected Behavior
Clicking through each full screen remote session shows the corresponding remote desktop.
However, selecting the main window should also show it.

## Current Behavior
Clicking through each full screen remote session shows the corresponding remote desktop.
However, selecting the main window just shows the currently running remote session

## Steps to Reproduce (for bugs)

1. Windows 11
2. Open at least one remote session as full screen & keep it displaying
3. Now click on the Main mRemoteNG window 

![image](https://user-images.githubusercontent.com/2977255/151443838-45671074-7782-4d72-9f6a-526bf79389b2.png)

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version Windows 11 Pro x64

**Comment by simonai1254** [comment]
Hi Shashi

Would you mind trying the new nightly build (1.77.2-nb 20220107), if it behaves the same?

**Comment by shashisadasivan** [comment]
> Hi Shashi
> 
> Would you mind trying the new nightly build (1.77.2-nb 20220107), if it behaves the same?

Awesome, it works in the Nightly Build 👍🏽
