### ISSUE TITLE
Focus handling still problematic with 1.77.2-nb (20220107 Nightly build)

### ISSUE THREAD

**Issue by meyergru** [mRemoteNG/mRemoteNG#2143]
## Expected Behavior
The handling of "out-of-focus" output should be fixed.

## Current Behavior
Out-of-focus output is not shown correctly.

## Possible Solution
Probably, this is an artefact of an optimization? It looks as if the inactive tab does not get updated during off-focus operation, plus it does not get restored correctly after coming into focus again.

This still seems to have a common root cause as issues https://github.com/mRemoteNG/mRemoteNG/issues/1535 and https://github.com/mRemoteNG/mRemoteNG/issues/1586 - I think those are unfixed, at least the latter one.

## Steps to Reproduce (for bugs)
I just tried the "20220107 Nightly build". With that, when I switch between tabs and come back to a tab that is outputting text, I see empty lines if the window did not need to scroll. There is even a small hollow cursor in that empty section, even if the full cursor is there below on lines that were outpur after the focus came back to the tab.

When the tab had to be scrolled during off-focus time, the tab seems to have been frozen in the condition as it was left (like pressing Crtl-S). The missing output is only shown after the tab is forced to scroll via the scroll bar.

## Context
I try to switch between tabs (which is what mRemoteNG is all about).

## Your Environment
I use KiTTY instead of PuTTY on Windows 10 21H2.

**Comment by LIyoai** [comment]
I guess this is a duplicate. Since there are already open issues.
#1408

**Comment by farosch** [comment]
Exactly, closing as duplicate.
