### ISSUE TITLE
support for mstsc /remoteguard

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2147]
microsoft RDP client (mstsc.exe) supports "remote credential guard" functionality
it is activated with parameter "/remoteguard"

the effect is that the current user session (kerberos ticket) is used to authenticate to the remote system. no username/password/domain is required to be specified. this is pretty useful (and secure).

can someone add this functionality to mremote?

**Comment by simonai1254** [comment]
I guess this goes into a similar direction as #1125 though it's another flag...

**Comment by tecxx** [comment]
correct, so i guess this one here can be closed.
