### ISSUE TITLE
Slow VNC performance

### ISSUE THREAD

**Issue by emiliskvg** [mRemoteNG/mRemoteNG#2148]
mRemoteNG has poor VNC (TightVNC) handling. Using the native program **TightVNC Viewer** it's blazing fast, and can stay connected basically forever and no lag or performance issues.
But on mRemoveNG VNC connections 'work', but they're:
1. Kind of slow. (5-10 times slower)
2. Mouse lags in them.
3. Connection to client just randomly 'hangs' (Disconnects, and glitches to an empty half window border)
4. Some connections just disconnect.

And this is on a local network with 48 Gbps capacity, with a 1 Gbps straight Ethernet connection.
No dropped packets as I can see.

Maybe I'm doing something wrong? :D

## Expected Behavior
Same as any other client.

## Your Environment
* Version used: I tried Stable, Dev, and Nightly.
* Operating System and version (Windows 10 21H2 x64) both machines.
* 16 GB RAM both machines.
* SSD and NVMe
* Ethernet links.

**Comment by LIyoai** [comment]
Probably related to  #2025

**Comment by farosch** [comment]
Definitively related to #2025 
There is no reason to keep this issue open. #2025 will address these issues and there are no plans on trying to enhance the current implementation.
