### ISSUE TITLE
View settings issue - Nightly 1.77.2

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2151]
Once the Quick Connect Toolbar or Multi SSH Toolbar are enabled, they cannot be disabled.
"Resetting the layout" does not remove them either, until the application is restarted.
Once restarted, the 2 toolbars are removed again but the main menu bar is not reset to the top-left.

## Expected Behavior
When turning off the toolbars, I expected them to immediately disappear.

## Current Behavior
The toolbars remain visible.

## Steps to Reproduce (for bugs)
Once Quick Connect Toolbar and/or Multi SSH Toolbar are enabled (ticked), select one or both again to turn them off.

## Context
The display doesn't react to menu options.
Also, once toolbars are disabled & the app restarted, the main menu is left in a strange-looking position.

## Your Environment
Windows 10 Enterprise 64-bit 2004, 16 GB RAM, 250 GB HDD.

**Comment by david-sway** [comment]
This was fixed by https://github.com/mRemoteNG/mRemoteNG/pull/2114, which the NB at https://github.com/mRemoteNG/mRemoteNG/releases/tag/2022.01.07-1.77.2-nb predates.

Toggling both toolbars works as expected using the current 1.77.2 codebase

**Comment by pauldurham** [comment]
That's the issue - I am using 1.77.2-nb and it isn't working.

**Comment by Kvarkas** [comment]
> That's the issue - I am using 1.77.2-nb and it isn't working.

try [this ](https://github.com/mRemoteNG/mRemoteNG/releases/download/20223.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi)
