### ISSUE TITLE
Allow right-click to add to favourites - Nightly 1.77.2

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2156]
To offer the same feel as other apps, one should be able to right-click on a server to add it to "Favourites".  Instead, one has to find the appropriate field in Properties, and hope that field has not been set to "inherit".

## Expected Behavior
Expect to be able to right-click on an entry & select "Favourites".

## Current Behavior
One has to dig through server properties, and possibly turn off inheritance for that server.

## Context
Not a bug, but it makes using the app a little more unproductive.

## Your Environment
Windows 10 Enterprise 64-bit 20H2.

**Comment by Kvarkas** [comment]
this will be possible after new UI implementation
