### ISSUE TITLE
Application fails to launch - Nightly 1.77.2

### ISSUE THREAD

**Issue by pauldurham** [mRemoteNG/mRemoteNG#2158]
Occasionally the application fails to launch at all.  No errors, just won't start up.  Only a reboot resolves the issue.

## Expected Behavior
I expect mRemoteNG to start every time.

## Current Behavior
Occasionally the app fails to start up.

## Steps to Reproduce (for bugs)
Nothing specific.

## Context
It means I have to reboot my PC.

## Your Environment
Windows 10 Enterprise 64-bit 20H2.

**Comment by simonai1254** [comment]
This is not reproducible with this information, I do not have this issue.

**Comment by Kvarkas** [comment]
potentially has been fixed in Nightly 1.77.3
