### ISSUE TITLE
Create user manual documentation for the Quick Connect feature

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#216]
Create documentation for this feature which may include:
- What the feature is / what it does
- Example use cases / when would it be useful
- Where it can be found / activated
- What options are available
- Common questions / "gotcha's"

Prepare text in Markdown format for inclusion in the [User Manual Wiki](https://github.com/mRemoteNG/mRemoteNG/wiki/User%20Manual)

**Comment by benwa** [comment]
https://github.com/mRemoteNG/mRemoteNG/wiki/Quick-Connect
