### ISSUE TITLE
QuickConnect fails "Cannot open connection: no such hostname" 1.77.2-nightly

### ISSUE THREAD

**Issue by hunnymonster** [mRemoteNG/mRemoteNG#2162]
## Expected Behavior
If I type a target in to the QuickConnect box and hit the SSH2/RDP/etc button I expect it to attempt to connection. 

## Current Behavior
If I type a target in to the QuickConnect box and hit the SSH2/RDP/etc button, regardless of protocol chosen it returns "Cannot open connection: no such hostname". I have tried IP, hostname, FQDN over Telnet/RDP/SSH2/HTTP - all fail the same way. If I make a connection and save it, that saved connection works exactly as expected.

## Steps to Reproduce (for bugs)

1. Open mRemoteNG 1.77.2-nightly (Jan 7 edition)
2. Type hostname (or IP or FQDN) in QuickConnect box & select appropriate protocol
3. 
4.

## Your Environment

* Version used: 1.77.2-nightly
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11 21H2 (22000.469) x64

**Comment by simonai1254** [comment]
Please have a look at #2137

**Comment by hunnymonster** [comment]
Ok, but that's closed and references a new build as yet unreleased - happy to merge this bug with that one
