### ISSUE TITLE
tab behaviours in 1.77.2

### ISSUE THREAD

**Issue by wellloaded** [mRemoteNG/mRemoteNG#2167]
I would expect the connection tabs to: 

1) ![image](https://user-images.githubusercontent.com/46318040/153701585-5e9045fd-eb6a-4f6c-9645-1ba65a10037f.png)
Be disabled by default. e.g. Stay where you are please! 

2) ![image](https://user-images.githubusercontent.com/46318040/153701466-78825492-6287-4632-80ac-48d35217be60.png)
Be modified as follow:
 a - disabled by default (no action on double click)
 b - have instead a "list of of possible action" link-able to double click. e.g. reconnect/duplicate/disconnect/etc. I personally have a very sloppy connection (4G) and I would link the action to "reconnect" since I need to perform this every hour or so.

Thanks a lot for maintaining such a great software I have been using it for years!

**Comment by Kvarkas** [comment]
some changes will allow to set such as advance settings
