### ISSUE TITLE
Feature request: immersive mode

### ISSUE THREAD

**Issue by wellloaded** [mRemoteNG/mRemoteNG#2168]
I do appreciate the full screen mode, but I'm wondering if this could be improved further, perhaps introducing a new mode, let's call this "immersive":

Immersive mode would:
-  Expand to almost all the screen leaving only a small stripe on top (for the menu+group tab+connection tab) and a stripe on the left (for the connection icons). This would maximize the usable area.
-  The stripe to the left would only display mini icons where the group/connection name and perhaps FQDN/IP is shown only on mouse-hover and a connection (while in immersive mode) is triggered by a single click.

example of "immersive" mode
![image](https://user-images.githubusercontent.com/46318040/153702169-43128c02-9b87-47d3-8cdb-faba600fdf58.png)

I would leave the Windows task bar on by default while in this mode but perhaps you could add a new option to let the user choose if this is wanted or not.

Thanks!

**Comment by Kvarkas** [comment]
this is planed with release of new UI in next version
