### ISSUE TITLE
Prevent to save password in confCons

### ISSUE THREAD

**Issue by anatollizik** [mRemoteNG/mRemoteNG#2169]
## Expected Behavior

Prevent saving passwords to Nodes in the users confCons.xml (_Password=""_)

## Current Behavior

Everybody can save a password to the confCons.xml

## Possible Solution

Disable/Enable possibility to save password

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We want to accomplish more secure environment and prevent to use copied unprotected confCons.xml with passwords
## Your Environment

* Version used: v1.77.2-nb
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 Version 10.0.19042 Build 19042, Windows 2019

**Comment by simonai1254** [comment]
Yeah this would be a neat feature for shared and enterprise environments which forces the user to use the passwords out of the company password safe. Alternative: Store the Passwords separately and encrypted e.g. with the Active Directory User Certificate...

**Comment by anatollizik** [comment]
Hi, thank you for your quick answer. Could you please explain what you mean to Store the Passwords separately?

**Comment by simonai1254** [comment]
You have the %appdata%\mRemoteNG\confCons.xml (or with custom path) where at the moment all information is stored. 
I would like to have the shared confCons.xml and a user-specific %appdatalocal%\mRemoteNG\confPasswd.xml which contains the user-defined password in an encrypted form. This prevents the leakage of passwords when sharing the Connection configuration while still allowing the usage of stored passwords.

**Comment by anatollizik** [comment]
Apologies, I'm not sure I understand what are exect steps and purpuse you describing.
I'm talking about scenario, where every user has his own confCons.xml file and in there keeps his own passwords. When confCons.xml is saved in his profile, for example %appdata%\mRemoteNG\confCons.xml and it is not password protected I can copy (for example I'm in local admins of a computer ora a server) it and use his saved passwords. And that situation I want to avoid.

**Comment by Kvarkas** [comment]
hello, this will be available once we release user profiles
