### ISSUE TITLE
Create user manual documentation for the SSH File Transfer feature

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#217]
Create documentation for this feature which may include:
- What the feature is / what it does
- Example use cases / when would it be useful
- Where it can be found / activated
- What options are available
- Common questions / "gotcha's"

Prepare text in Markdown format for inclusion in the [User Manual Wiki](https://github.com/mRemoteNG/mRemoteNG/wiki/User%20Manual)

**Comment by ForensicITGuy** [comment]
Do you mind if I take a shot at this?

**Comment by kmscode** [comment]
Got for it! 😄 

If you're feeling especially limber, you could see about getting the htm file updated as well:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Resources/Help/SSHFileTransfer.htm

This would require a pull request...

😉 

Feel free to discuss anything here and we will respond.

@sparerd - did you open up the wiki for edits? https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by sparerd** [comment]
The wiki is not open for edits. Unfortunately, there does not seem to be a good secure way to do so.

The wiki is just another git repo, luckily, so you can clone it like anything else. To clone our wiki, you can do something like:

#### Via Https
git clone https://github.com/mremoteng/mremoteng.wiki.git

#### Via SSH
git clone git@github.com:mremoteng/mremoteng.wiki.git

There is an article showing the process here: https://gist.github.com/larrybotha/10650410

Admittedly, this is not an ideal way to deal with updates. But I'm also worried about just opening up the wiki for edits.

**Comment by ForensicITGuy** [comment]
No problem, I'll work on doing this via cloning/forking the wiki over the next few days. If I can't get that to work, I can always submit a Markdown document that can be placed into the wiki by its admins.

**Comment by sparerd** [comment]
Either way is good with me. Thanks for your contribution, this is great!

**Comment by ForensicITGuy** [comment]
The wiki cloning seemed a bit weird, so I went ahead and just created a Markdown document. Please find attached...
[SSHFileTransfer.txt](https://github.com/mRemoteNG/mRemoteNG/files/650853/SSHFileTransfer.txt)

**Comment by sparerd** [comment]
Sorry for the delay - page is now posted (with credits in the gitlog). Thanks for writing this up!

https://github.com/mRemoteNG/mRemoteNG/wiki/SSH-File-Transfer
