### ISSUE TITLE
Where is Language.resx ?

### ISSUE THREAD

**Issue by demovirus** [mRemoteNG/mRemoteNG#2174]
Url to Language.resx on this page is invalid - https://github.com/mRemoteNG/mRemoteNG/wiki/Translate
Please correct link to this file.

**Comment by Kvarkas** [comment]
file can be found in 1.77.3-dev\mRemoteNG\Language\Language.resx

**Comment by Kvarkas** [comment]
wiki page has been updated

**Comment by demovirus** [comment]
Update also link to [mRemoteNG repository on GitHub](http://github.com/mRemoteNG/mRemoteNG/tree/develop/mRemoteV1/Resources/Language) in 3rd paragraph. Thank you
