### ISSUE TITLE
Connection file schema for script creation in Python

### ISSUE THREAD

**Issue by luchoArg33** [mRemoteNG/mRemoteNG#2177]
Hi I want to create a Python script in order to generate connection files in XML or CSV. The easiest one and then share it to the public... I don't know anything about powershell but I can easily do something in Python. Could you please tell me where can I find the schema or docs in order to create a connection file? I'm using mRemote 1.76.20.24615

Thanks in advance for your time.
Cheers,
Luis

**Comment by Kvarkas** [comment]
Hello, current schema can be found [there](https://github.com/mRemoteNG/mRemoteNG/tree/v1.77.3-dev/mRemoteNG/Schemas) actual version 2,7, that may be soon change to 2.8

also there is ongoing developing of profiles so all connection will be move inside of local db file, and xml will be supported as rudiment till version 1.8
