### ISSUE TITLE
Remote not support linux command called 'sz' or 'rz'

### ISSUE THREAD

**Issue by crazyAJ** [mRemoteNG/mRemoteNG#2185]
Remote not support linux command called 'sz' or 'rz'

**Comment by crazyAJ** [comment]
![image](https://user-images.githubusercontent.com/49477296/158547307-b2e7538f-b560-4424-8024-17cf8959cd25.png)

**Comment by crazyAJ** [comment]
![image](https://user-images.githubusercontent.com/49477296/158547835-674c9524-d365-4460-bcf8-2c8f4f9a79bd.png)

**Comment by simonai1254** [comment]
Does the command work with another SSH client? I assume this is an issue with the host you are connecting to and not directly related to mRemoteNG.

**Comment by Kvarkas** [comment]
@crazyAJ mRemoteNG allows you to connect. That primary functionality so if you able to connect its works as desired. Next its allow you to run a command after your connect, where is nothing specific in it as it just send configured command into yours terminal on host. If something not working its seems to be limitation of that host but not mRemoteNG. Could you connect to host using vnc or ssh and check if that command can be run successfully?

**Comment by nmat** [comment]
This does not look like a problem in mRemoteNG but a way on how to use the commands on a single server type of way.

like @simonai1254 does this work if you use Putty directly? If it does then it should work in mRemoteNG too (I presume) if not then its a question on how to use the command more. Further on that note. You can use SCP to transfer files if it does have SSH2 access, unless SCP is blocked.

**Comment by crazyAJ** [comment]
Not sure and give it up

**Comment by Develkone** [comment]
I run 'sz' and 'rz' commands both in xshell and secureCRT,it works fine.But in mRemoteNG I have the same problem with author.

**Comment by simonai1254** [comment]
> I run 'sz' and 'rz' commands both in xshell and secureCRT,it works fine.But in mRemoteNG I have the same problem with author.

How does it behave when you use putty instead?
