### ISSUE TITLE
Manual uninstall or Change home directory

### ISSUE THREAD

**Issue by DoplerGanger** [mRemoteNG/mRemoteNG#2186]
.
TY for good stuff and tool.
But when i try to relocate on another PC, i create export xml config file, copy thise file on desktop on **new** PC and import it in app.
And now all backup file (when i close programm) creating in desktop folder. I try reinstall and delete  programm and configs folders in both %appdata% folders. 

Try to search answer here but didnt find ^_^

## Expected Behavior

Backup files and config file create in home directory APP.
## Current Behavior

Its create in Desktop directory.
## Possible Solution

I think its need manual uninstallation.
But i cant fint guide in wiki
## Steps to Reproduce (for bugs)

1. Place copy of export file in desktop folder on newly installed computer.
2. Import in freshly installed programm.
3. Check its create backups on dektop.
4.
5.

## Your Environment

Version of installation msi: 1.76.20.24615.
Win 10 19044.1586 (install date 04.03.2022 yep few days ago)

**Comment by Kvarkas** [comment]
you perhaps need to use portable app as it will be hold all files in app folder.

**Comment by DoplerGanger** [comment]
> you perhaps need to use portable app as it will be hold all files in app folder.

Aaha i didnt think in thise case ) 
I think i do it as you say.
Ty Дмитрий.

**Comment by DoplerGanger** [comment]
I check it, all good and work perfectly!

**Comment by simonai1254** [comment]
Did you import the connection file or open it? Because this is creates quite a different behavior in how the connection file (and it's backups) are handled...

Importing should put it in the configuration file located in the %appdata% directory (or whatever was opened before), while opening saves it exactly where you opened it from. This includes the temporary configuration backups.

**Comment by DoplerGanger** [comment]
When i first try import thats end with error like "cannot import blablabla " and ofc next try it's "open" file. After that it start backups near thise file right in desktop folder ^_^

**Comment by Kvarkas** [comment]
perhaps need to add separate option to hard set backup folder :)
