### ISSUE TITLE
Global inherit option

### ISSUE THREAD

**Issue by medrazd** [mRemoteNG/mRemoteNG#219]
I noticed problem in ver. 1.74.6023.15358, when I tried to change default inheritance options (in Connection organization unit) and save config there the changes will be not saved. Program starts with default values "no". I tried to create new config file but there the problem still exist.

**Comment by ferfebles** [comment]
It seems that it's working with 1.75 Alpha 3.

**Comment by medrazd** [comment]
Solved. Thanks!
