### ISSUE TITLE
Process to make local drives available while using mRemoteng utility to remote desktop into Win Servers

### ISSUE THREAD

**Issue by ee1242** [mRemoteNG/mRemoteNG#2190]
My organization uses the mRemoteng utility to remote destkop into Windows servers.

The homepage for this utility is https://mremoteng.org/.

What is the process to make local drives available while using mRemoteng utility to remote desktop into Windows servers?

This process is done by using the windows remote desktop utility (mstsc.exe) by clicking the Show Options button, Local Resources, More..., and putting a checkmark in the Drives checkbox.

I need to set this as a default setting so that every time that I use the mRemoteng utility to establish a remote desktop session into a Windows server the drives on my local computer (C:, D:, etc) will be available.

**Comment by thetuxinator** [comment]
Hmm, this already works, just configured drive redirection in mremoteng rdp config

**Comment by ee1242** [comment]
My coworker just discovered how to do this.

Simply navigate to the Config section, select Disk Drives, and change this option to Yes.

![image](https://user-images.githubusercontent.com/41352676/162496233-1966e047-7cac-4743-b888-8b6e3c07af28.png)
