### ISSUE TITLE
RDP protocol error 3334

### ISSUE THREAD

**Issue by Shinybro** [mRemoteNG/mRemoteNG#2198]
Just for your information.

Using version 1.76.20.24615 from Windows 11 and connecting to Windows 10 Pro version 1909 (whilst trying to update) or higher, disconnects with an RDP error 3334, since a few days.

The problem is the version of AxInterop.MSTSCLib.dll and Interop.MSTSCLib.dll.

Using the ones from the nightly build solves the problem.
Download the portable version and unzip.
Put them in C:\Program Files (x86)\mRemoteNG.

You also need to install .NET 6.0 Desktop Runtime (v6.0.3) - Windows x64 to make it work.

**Comment by simonai1254** [comment]
Does this issue happen as well when using the nightly version 1.77.3?

**Comment by Shinybro** [comment]
I've installed version 1.77.2-nb.
When the program started, it asked to install Microsoft.NETCore.App version 6.0.0.
I installed .NET 6.0 Desktop Runtime (v6.0.3) - Windows x64.

And had no problems with connecting to the concerned machines.

The installation of mRemoteNG went very well.
It removed the x86 version from C:\Program Files (x86) leaving only the files which I added afterwards like custom icons.

**Comment by Shinybro** [comment]
Hi Simon,

I've installed version 1.77.2-nb.
When the program started it asked to install Microsoft.NETCore.App version 6.0.0.
I installed .NET 6.0 Desktop Runtime (v6.0.3) - Windows x64.

And had no problems with connecting to the concerned machines.

The installation of mRemoteNG went very well.
It removed the x86 version from C:\Program Files (x86) leaving only the files which I added afterwards like custom icons.

Kind regards,

Bart

Van: Simon Monai ***@***.***>
Verzonden: dinsdag 12 april 2022 0:03
Aan: mRemoteNG/mRemoteNG ***@***.***>
CC: REYNAERTS Bart (Firebru) ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mRemoteNG/mRemoteNG] RDP protocol error 3334 (Issue #2198)


Does this issue happen as well when using the nightly version 1.77.3?

**Comment by simonai1254** [comment]
Great to hear it worked for you, would you mind closing the issue as completed?
