### ISSUE TITLE
Icon does not show up in the Windows 11 startmenu

### ISSUE THREAD

**Issue by kathodion** [mRemoteNG/mRemoteNG#2200]
## Expected Behavior
RemoteNG does not show up in the Windows 11 startmenu.
It that something you can fix or is the problem on my side?

## Current Behavior
I have to open remoteng via the explorer or a shortcut

## Steps to Reproduce (for bugs)
Fresh install of remoteng

## Your Environment
Windows 11,21H2, 22000.613
mremoteng 1.76.20.24615

**Comment by simonai1254** [comment]
Please try with the latest nightly build (1.77.2-nb) if it is still the case, thanks.

**Comment by kathodion** [comment]
with mremote... it works
with remoteng it does not work - it may be an search limitation

**Comment by Kvarkas** [comment]
this app official name mRemoteNG so it should be use as mremoteng not remoteng
