### ISSUE TITLE
preferences are no longer saved correctly

### ISSUE THREAD

**Issue by tecxx** [mRemoteNG/mRemoteNG#2202]
using the latest code changes (2022-04-03)

mremote now asks for settings customization at each start

![image](https://user-images.githubusercontent.com/4305825/163547895-eaffb7bd-d575-4986-bdbc-1fc05d76d28b.png)

the custom connections file is no longer remembered, showing an empty connections panel

![image](https://user-images.githubusercontent.com/4305825/163547960-dfe2e020-230f-424d-97ca-79572ed685ac.png)

changing any setting in options is lost upon restart, for example
![image](https://user-images.githubusercontent.com/4305825/163548119-e77dad55-a07b-4def-b4e8-68fa8cc83c3c.png)

![image](https://user-images.githubusercontent.com/4305825/163548161-b2d8a352-c594-4e86-a18c-f81dc8cf407b.png)

the issue starts since commit "refactoring options" #8db0bc6e
reverting to a version before that solves the issue

**Comment by Kvarkas** [comment]
thanks, there is ongoing work regarding such so its expected.
