### ISSUE TITLE
Feature Request: Optional disconnect after X number of seconds/minutes of inactivity

### ISSUE THREAD

**Issue by countchappy** [mRemoteNG/mRemoteNG#221]
A great feature would be to allow (if set) a number of seconds or minutes after inactivity that it will automatically close the session.

**Comment by countchappy** [comment]
I am currently testing something in `Connection.Protocol.RDP.cs`.

Trying some stuff out with the `MinutesToIdleTimeout` setting and `OnIdleTimeoutNotification` method. Will post an update with my findings.

**Comment by countchappy** [comment]
Using `MinutesToIdleTimeout` has worked. Now trying to add a configuration field in the RDP settings.

**Comment by kmscode** [comment]
@countchappy Thanks for giving this a shot! See the following commit which added a different option for RDP session: https://github.com/mRemoteNG/mRemoteNG/commit/60cd2c2b128c64ff174ecfe8a3511de560390cdc

This should be a good guide for you to follow to add in the setting...

Feel free to submit a pull request once you have it implemented and tested...

@sparerd - assuming that countchappy submits a PR in the very near future, 1.75 would be a good release to add this to due to the updated confcons.xml schema... Thoughts?

**Comment by sparerd** [comment]
Yea, sounds good to me. As long as we get a PR soonish we should be able to include it.

**Comment by countchappy** [comment]
I should be able to square this away and make a pull request by Thursday.

@kmscode Thanks again for the link to [60cd2c2](https://github.com/mRemoteNG/mRemoteNG/commit/60cd2c2b128c64ff174ecfe8a3511de560390cdc). Should speed up the process a ton!

**Comment by countchappy** [comment]
@kmscode Having issues with the PR (I have never used github before) What branch do I push it to?

**Comment by kmscode** [comment]
@countchappy Glad that you're ready for that... Looks like you didn't create a fork.... so unfortunately you'll need to do a little finagling... 

* First move your existing source tree to a different directory (mremoteng.old for example).
* Go to https://github.com/mRemoteNG/mRemoteNG and click the "Fork" link at the top. Some details on forks: https://help.github.com/articles/working-with-forks/ - YOUR fork will be https://github.com/countchappy/mRemoteNG - that is what you will work with going forward
* Copy any files that you've modified from mremoteng.old to your "current" (fork created) mremoteng directory
* Build and test
* Commit all confirmed/tested changes to your fork
* Create the PR: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by countchappy** [comment]
Pull request submitted.

@kmscode and @sparerd Thanks again for all the help!
