### ISSUE TITLE
Changelog Hyperlink Error

### ISSUE THREAD

**Issue by kramttocs** [mRemoteNG/mRemoteNG#2216]
Version 1.77.2
Clicking on the Changelog Link on the About popup generates an error

An error occurred trying to start process 'https://github.com/mRemoteNG/mRemoteNG/blob/develop/CHANGELOG.md' with working directory 'C:\Program Files\mRemoteNG'. The system cannot find the file specified.

**Comment by simonai1254** [comment]
See #2117, though it might be that it wasn't properly fixed...

**Comment by kramttocs** [comment]
You're right. It just missed the nb. Thanks!
