### ISSUE TITLE
RSA-SSH key error connecting to ubuntu 2204

### ISSUE THREAD

**Issue by wduizer** [mRemoteNG/mRemoteNG#2220]
When connecting to a Ubuntu 2204 server with mremoteng (build 1.76.20.24615) using a RSA-SSH key imported in Peagent we get an error.

## Expected Behavior
When using a saved putty session with a SSH key we connect to Ubuntu servers
On Ubuntu servers 20.04 we can connect using this saved session.
We want to use this saved session to connect with Ubuntu 22.04 servers as well 

## Current Behavior
When trying to connect to a Ubuntu 22.04 server we get an error.
In auth.log on the server the following error is reported:
_No supported authentication methods available [preauth]
do_cleanup [preauth]_

When connecting with Putty in stead of MremoteNG the connection using SSH is working as aspected

## Possible Solution
Adding the following line to /etc/ssh/sshd_config
_PubkeyAcceptedAlgorithms +ssh-rsa_
will resolve the issue

## Context
we would like to be able to connect with MremoteNG to the Ubuntu 22.04 servers using the SSH key without having to put the extra line in sshd_config

## Your Environment
* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows server 2016, Windows server 2019, Window 10, Windows 11

**Comment by trelane** [comment]
This is affecting us.  Bumping this issue.

**Comment by LIyoai** [comment]
Maybe you try replacing puttyng.exe with the one from last nightly build or with the original putty.exe

**Comment by stufently** [comment]
you need generate new key ssh and use nightly for support new key format
https://askubuntu.com/questions/1409105/ubuntu-22-04-ssh-the-rsa-key-isnt-working-since-upgrading-from-20-04

**Comment by swiedeman** [comment]
@Kvarkas can you please give an update to this issue for stable or even preview?   Our company has multiple team members that are using mRemoteNG.

**Comment by simonai1254** [comment]
> @Kvarkas can you please give an update to this issue for stable or even preview? Our company has multiple team members that are using mRemoteNG.

@swiedeman New builds are on it's way, if 1.77.2 is not stable enough for you you have the option to replace the putty.exe in the mRemoteNG program folder through a newer one. 

If you would like to support and speed up the software development, then please consider a donation

**Comment by swiedeman** [comment]
> 

Appreciate the reply and the workaround!!   We can wait for 1.77.2.   I did replace the PuTTYNG.exe with the latest Putty executable and that does work.

**Comment by Kvarkas** [comment]
hey ho, jut come back after holidays, will have a look into this as priority

**Comment by thetuxinator** [comment]
This affects more and more distros, need to update the used putty version and make a hotfix release! Can't connect to Ubuntu 22.10 Fedora Core 37 and SHA1 is deprecated!

**Comment by hgbrd23** [comment]
If you have this issue here, problems connecting to newer servers using SSH with mRemoteNG
(e. g. Ubuntu 22.04, verbose SSHD log will show "sshd[38576]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]"):
* Download the newest prerelease of mRemoteNG: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.77.1
* Download newest PuttyNG exe and overwrite the version in the mRemoteNG install directory: https://github.com/mRemoteNG/PuTTYNG/releases/tag/v0.78.0.10

This solved it for me.

**Comment by Kvarkas** [comment]
thanks @hgbrd23 - I add such into [documentation](https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html)
