### ISSUE TITLE
516 Error in mRemoteNG but not using MSTC in Windows 11

### ISSUE THREAD

**Issue by rwilkers** [mRemoteNG/mRemoteNG#2224]
When attempting to connect from a Windows 11 to a few Windows 10 workstations via mRemoteNG I get a 516 RDP error,  however if I launch MSTC in Windows 11 the computer connects without any issues.  However this is probably an issue with the  initiating Windows 11 workstation since I do not have the issue when initiating a session from mRemoteNG on a Windows 10 Pro.   Putting this issue in to document.

## Expected Behavior
mRemoteNG should connect without any problem

## Current Behavior
mRemoteNG  shows a 516 RDP error "Warning Msg 05/16/2022 09:17:04 RDP disconnected! 516 Remote Desktop can't connect to the remote computer for one of these reasons:
1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network

Make sure the remote computer is turned on and connected to the network, and that remote access is enabled.
----------"

## Possible Solution
Have no idea what the issue might be, I did try toggling the option for "Automatically get session options" but that had no effect.

## Steps to Reproduce (for bugs)
Happens every time when I connect to any of five Windows 10 Pro VM's from my Windows 11 Pro workstation.

## Context
Issue is irritating, not debilitating.  Approx 5 workstations out of 15 have this problem.  Currently I have to use MSTC along with mRemoteNG to access these device.

## Your Environment
Lab Enviroment using Esxi v7.03 and multiple VM's mostly Windows 10, 11 and multiple varieties of Linux.  My desktop that I normally initiate sessions from is Windows 11 Pro Build 22616.1.  The target machines that have this issue are Win10 Pro Build 19044.1706

**Comment by Kvarkas** [comment]
what version of mRemoteNG you are using and could you send example of you connection string to support@mremoteng.org (ip address can be removed as well as user and password - will try to check

**Comment by Kvarkas** [comment]
Close as no responce from user received and not able to reproduce

**Comment by breversa** [comment]
I’m having the same issue and can reliably reproduce it using mRemoteNG 1.76.200.24669 from a Windows 10 Entreprise 21H2 computer.
