### ISSUE TITLE
About screen adaptation

### ISSUE THREAD

**Issue by TcDhlPro** [mRemoteNG/mRemoteNG#2227]
## I hope it can adapt to the 4K screen
# It's the software itself

**Comment by simonai1254** [comment]
At the moment the software works with 4K-Screens, though some Icons do have minor issues (blurry) when scaling is enabled. I would say the software is already pretty usable with 4K-Screens.

**Comment by Kvarkas** [comment]
some works are in progress to improve it - seems best way to migrate windows forms to wpf but its a very nudge peace of work so not sure it will happening soon, but some changes are made to improve scalability and 1.77.3 nb is looks pretty on 4k display even with 200% scale

**Comment by stufently** [comment]
Very small options windows in windows 11 3k display with 200% scale, latest nightly build
![image](https://user-images.githubusercontent.com/1324096/178661754-bc07dd9f-9198-4cad-ad94-648e6596d81c.png)

**Comment by stufently** [comment]
fullscreen
![image](https://user-images.githubusercontent.com/1324096/178661862-61d02d4f-b9d5-4864-a56f-7e30322944ca.png)

**Comment by SullyPanda76cl** [comment]
+1 to this.

Problem also exists on 150% screen adaptation.

"option window" need to have at least on of these improvements:
a) bigger size according to display zoom
b) be resizable by user (instead of fixed border)
c) get scrollbars

**Comment by Kvarkas** [comment]
have a look my comment above please ;)

**Comment by stufently** [comment]
I have same problem in windows 11? 3k display , latest nb 1.77.3 , 150-200 adaptation

**Comment by BlueBlock** [comment]
Resolved, fixed size. No scrollbars at the moment.

https://github.com/mRemoteNG/mRemoteNG/pull/2401
