### ISSUE TITLE
Feature Request: splitting tabs (not only panels)

### ISSUE THREAD

**Issue by Sebor** [mRemoteNG/mRemoteNG#223]
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.74 final  |

Hello! Is ti possible to add splitting tabs feature? I know there is a splitting panel option, but I suppose that splitting tabs is more convenient. For example, you want to open 2 or more connections for one server and watch multiple logs simultaneously.

Thanks

**Comment by john-bakker** [comment]
is there an update on this Feature request already ? would really love this feature

**Comment by jotatsu** [comment]
@kmscode This feature is working on th removemagiclib branch. Candidate for close

**Comment by kmscode** [comment]
Closed at this is implemented in 1.77 (currently in the develop branch)
