### ISSUE TITLE
bug (minor/menu): develop-branch - top toolbar menu has a extra menu item that appears to do nothing.

### ISSUE THREAD

**Issue by jafin** [mRemoteNG/mRemoteNG#2234]
## Current Behavior
Minor issue
![mRemoteNG_CxsYCLtikT](https://user-images.githubusercontent.com/127927/171573368-54a2513f-f394-4fa2-b2dc-d72ebe2049be.jpg)
e with menu item that does do anything

## Possible Solution
Remove empty menu item

## Your Environment
develop [5ff4502](https://github.com/mRemoteNG/mRemoteNG/commit/5ff4502f0aeb31ae0777aa784e7214fca7ac1e6b)

**Comment by Kvarkas** [comment]
develop branch is not active, only to keep older links to documentation, use please dev 1.77.3
