### ISSUE TITLE
MRemoteNG nightly : it does not launch even if .NET (x86 or x64) is installed.

### ISSUE THREAD

**Issue by accnetdev** [mRemoteNG/mRemoteNG#2236]
MRemoteNG nightly : it does not launch even if .NET (x86 or x64) is installed.

Windows 10 or Windows 2019 server.

dotnet --info

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by simonai1254** [comment]
Hi 

You do need .Net 6 Desktop Runtime and not the Core one (see Minimum Requirements in README.md)

With that installed mRemoteNG should work without a hitch... 

Regards
Simon

**Comment by accnetdev** [comment]
Fixed : download and install the SDK ( dotnet-sdk-6.0.300-win-x64.exe ) not only the runtime as asked ( dotnet-runtime-6.0.5-win-x64.exe ).

**Comment by simonai1254** [comment]
Yeah SDK works as well, but really required is the .Net *Desktop* Runtime 6.0 (not Core Runtime) that you can download here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Also have a look at #2229

**Comment by accnetdev** [comment]
Yes, it seems to require the desktop version of the runtime, that is included in the SDK.
Man can only install the desktop runtime. My initial error was to install the console version of the runtime.
Personally, I am OK to install the SDK which could be useful for many other things.
Have a good day.
