### ISSUE TITLE
No quickly connexion from dedicated field quickly connexion

### ISSUE THREAD

**Issue by Jerem59** [mRemoteNG/mRemoteNG#2243]
When i add a hostname in field "quickly connexion", a warning message indicate no hostname specified 
and impossible to use this option

## Steps to Reproduce (for bugs)

1. add hostname in quickly field
2. click on rdp and the message appears

## Your Environment

* Version used: Nightly build 1.77.2
* Operating System and version (e.g. Windows 10 1709 x64): W10 21h1

**Comment by LIyoai** [comment]
Duplicate #2213
