### ISSUE TITLE
puttyng 0.77

### ISSUE THREAD

**Issue by HOSTED-POWER** [mRemoteNG/mRemoteNG#2246]
https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

Major improvements to network proxy support:
Support for interactively prompting the user if the proxy server requires authentication.
Built-in support for proxying via another SSH server, so that PuTTY will SSH to the proxy and then automatically forward a port through it to the destination host. (Similar to running plink -nc as a subprocess, but more convenient to set up, and allows you to answer interactive prompts presented by the proxy.)
Support for HTTP Digest authentication, when talking to HTTP proxies.

This is really really interesting, you no longer need plink.exe for SSH connections trough bastion! :)

**Comment by Neustradamus** [comment]
Any news about this?

3 months already:
2022-05-27 PuTTY 0.77 released
- https://www.chiark.greenend.org.uk/~sgtatham/putty/

**Comment by dinger1986** [comment]
can you not just rename puttyng to puttyng2, download from https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe, rename to puttyng.exe and copy to C:\Program Files (x86)\mRemoteNG? I just tested that and it works, to be fair that would be best if the software just did that automatically or just even kept its name as putty.exe so it doesnt need renamed.

**Comment by simonai1254** [comment]
The used PuttyNG is a fork of the original putty, see https://github.com/mRemoteNG/PuTTYNG. This is somehow included in the build process and has that as a name. 
Now I'm not sure if one should get rid of it or not, but it definitively needs to be kept up to date and included in the releases...

**Comment by dinger1986** [comment]
yeah understood but it maybe doesnt need forked or maintained seperately.

**Comment by Tampa** [comment]
The official version does work, but that are some quirks with using that. Anyhow, the pre-release for 0.78 is out and its release is on the horizon. It brings with it changes that break backwards compatibility especially in regards to keys and ciphers so an update to it, once released, would be greatly appreciated.

**Comment by JocPelletier** [comment]
+1 for this, I were not able to connect to my new Public Cloud machine because of "FATAL ERROR: Couldn't agree a host key algorithm (available: rsa-sha2-512,rsa-sha2-256)", I had to update my putty version and manually change the puttyng.exe to new putty version to make it work

**Comment by Kvarkas** [comment]
will have a look today

**Comment by Neustradamus** [comment]
@Kvarkas: Please look about pre-0.78:
- https://lists.tartarus.org/pipermail/putty-announce/2022/000034.html

**Comment by Neustradamus** [comment]
@Kvarkas: It is official, 0.78 is out!
- https://www.chiark.greenend.org.uk/~sgtatham/putty/
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

**Comment by Kvarkas** [comment]
I was waiting for such :)

**Comment by HOSTED-POWER** [comment]
Would be great if a new "official" puttyng could be released based on 0.78 :)

**Comment by Kvarkas** [comment]
In case you interested, we have done update to 0.78: https://github.com/mRemoteNG/PuTTYNG/releases/tag/v0.78.0.10

**Comment by HOSTED-POWER** [comment]
This is cool, already implemented for the SSH proxy and working great!!

Any chanche on a more recent mremoteng built too? A nightly perhaps? :)

One annoying thing with our current mremoteng version is that the when you select a host in another TAB, it doesn't jump to that tab. It keeps being in the active tab instead of jumping to the other group TAB

**Comment by Kvarkas** [comment]
nb should be released before end of month, working hard on primary job to release our project before freeze so almost no free time for personal life :(

**Comment by Neustradamus** [comment]
@Kvarkas: Thanks!
It is possible to have a new mRemoteNG release?

**Comment by JocPelletier** [comment]
> @Kvarkas: Thanks! It is possible to have a new mRemoteNG release?

I think you should read his last reply again ;)

**Comment by Tampa** [comment]
> In case you interested, we have done update to 0.78: https://github.com/mRemoteNG/PuTTYNG/releases/tag/v0.78.0.10

Tried that with 1.77.0.41252 and it seems to not read the password field as key passphrase. Guess this will work better with one of the nightly builds?

**Comment by Kvarkas** [comment]
unfortunately where is no back compatibility and putty is not our product so we have no force against it, we only could modify our end for new features so new versions of mRemoteNG will support such for sure

**Comment by Tampa** [comment]
Tried with 1.77.2 nightly, since the latest one is a portable-only, same thing, so I'll guess I'll wait for the full next release then.

**Comment by Kvarkas** [comment]
could you provide more information what exactly its not working anh how to recreate so will be check to be shure we dont have issue there, best to open as bug req for putty 78 if you dont mind

**Comment by simonai1254** [comment]
This issue might be related to the following changes (see [Official Change Notes](https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html#:~:text=These%20features%20are%20new%20in,forwarding%20a%20port%20through%20it.)):

- Bug fix: the -pwfile/-pw options no longer affect local key passphrase prompts, and no longer suppress Plink's anti-spoofing measures.
- New plugin system to allow a helper program to provide responses in keyboard-interactive authentication, intended to automate one-time password systems.

As the bug fixes are minor (no security updates) and the upgrade to 0.78 breaks things in mRemoteNG I would suggest to wait for the bundle until the compatibility is verified/fixed.

**Comment by Tampa** [comment]
I figured as much. That's no big problem the mainline putty still works just fine with that nightly. Will that change mean I have to adjust all my connections?

**Comment by simonai1254** [comment]
> I figured as much. That's no big problem the mainline putty still works just fine with that nightly. Will that change mean I have to adjust all my connections?

Do I understand correctly that you are saying Putty 0.78 works alongside 1.77.3-nb, while PuttyNG 0.78 doesn't? 

Generally I don't think you would need to change the connections, but mRemoteNG should be fixed to work alongside putty :)

**Comment by Tampa** [comment]
Not the latest nightly, since that is portable-only. 1.77.2 is what I installed via the installer. The putty itself is 0.78, but still the pre-release version rather than the full release out now. That combination seems to work still, have not tried the 0.78 release yet.

I put the latest puttyng 0.78 into the installation folder, so removing the custom putty path option would load that. Doing that will ask me for the passphrase each time. I can wait for the next release, this works for now :)

**Comment by simonai1254** [comment]
Just to cross-link, the underlying issue is handled with #2027.

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
