### ISSUE TITLE
Settings ("File" - "Options") are not saved in mRemoteNG 1.77.3-nb

### ISSUE THREAD

**Issue by AlektroNik** [mRemoteNG/mRemoteNG#2247]
Hello.
I go to "File" - "Options" - configure parameters - save - restart the application. The settings are not saved.
Previously, the mRemoteNG.exe.config file was created, now it is not created. Maybe this is the reason?

mRemoteNG 1.77.3-nb
Windows 10 Pro Workstation 21H2 19044.1706

**Comment by LIyoai** [comment]
See #2245
