### ISSUE TITLE
Can not import RDCMan v2.7 build 1406.0 rdg file

### ISSUE THREAD

**Issue by deathrush** [mRemoteNG/mRemoteNG#225]
|||

2016-11-07 18:00:51,144 [1] ERROR- App.Import.ImportFromFile() failed:1
Unsupported schema version (3).
2016-11-07 18:00:51,150 [1] ERROR- App.Import.ImportFromFile() failed:2
Unable to cast object of type 'mRemoteNG.Tree.Root.RootNodeInfo' to type 'mRemoteNG.Container.ContainerInfo'.

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74  |

**Comment by sbgillett** [comment]
Is this not a bug?

**Comment by sparerd** [comment]
mRemoteNG only ever had support for importing RDCMan v2.2 files. Supporting v2.7 imports would be a new feature.

**Comment by MoeSaidi** [comment]
+1 for this; would be nice to be able to easily migrate from RDC Manager to mRemoteNG

**Comment by ThoHah** [comment]
What is the status here?
This was a request in 2016...

**Comment by sparerd** [comment]
This will be included in the next major release, v1.76
