### ISSUE TITLE
Support for TLS1.3

### ISSUE THREAD

**Issue by S0rix** [mRemoteNG/mRemoteNG#2256]
Hi all,

is it possible to get a support for TLS1.3 websites?
currently we have an issue that all tls1.3 websites are not working with the built in https session option.

Greetings

**Comment by simonai1254** [comment]
Hi

What Version of mRemoteNG are you using? The newer builds (1.77.2+) should have the Chromium Engine for rendering, which I can't think that would be lacking TLS1.3...

**Comment by S0rix** [comment]
Hi,

thanks for the fast reply.
I installed now the version 1.77.2 but now I get just an blank white site with the Edge Chromium Rendering Engine.
Befor that I had the latest stable version. I think it was the 1.76.20.

Thanks for your help.

**Comment by S0rix** [comment]
I looked up the issue and it looks like that MS Edge cant access a folder.

In the log file I got following error message.

2022-06-30 08:12:57,307 [1] ERROR - Failed to contruct the URL to load
```
Zugriff verweigert (0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.Web.WebView2.WinForms.WebView2.InitCoreWebView2Async(CoreWebView2Environment environment)
```

After I opened the https page and waited like 2 minutes I got this popup.
![image](https://user-images.githubusercontent.com/104011279/176607727-fb5155bc-eaaf-4c18-a6fd-d370644119db.png)

The folder: C:\Program Files\mRemoteNG\mRemoteNG.exe.WebView2 was empty and there was no folder EBWebView. The normal windows user had no permissions to change the directory. so I gave him this permission and the https site is now working.

Greetings.

**Comment by simonai1254** [comment]
>The normal windows user had no permissions to change the directory. so I gave him this permission and the https site is now working.

Cool that you found this one out :)
Looks like this would help for issues #2241 and #2206...

**Comment by S0rix** [comment]
Thanks :)

Requirement for the Edge Chromium Engine is that webview2 for ms edge has to be installed.

wasn't the case of one of our client as well.

Download Link:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
