### ISSUE TITLE
Can someone explain to me how to install the latest nightly?

### ISSUE THREAD

**Issue by danmed** [mRemoteNG/mRemoteNG#2265]
I'm currently running v1.77.1 as i use the MySQL capabilites, but the quick connect box doesn't work.. 

i want to update to the latest version v1.77.3-nb to see if it fixes that issue.. but it's only a rar file and so far all my attempts have failed...

**Comment by simonai1254** [comment]
You need to extract the .rar file first, in there you should have an executable. But as a warning, 1.77.3-nb does not write any settings, therefore currently I'd suggest you only upgrade to 1.777.2-nb.

**Comment by Kvarkas** [comment]
will add in next nb installation file as well, however nb is not suppose to be used for work, only to check functionality or changes and in general I think will be support only portable mode - e.g. app all dependant files are in same folder and not all around operating system, if you unpack rar archive its should work from that folder without installation.
