### ISSUE TITLE
Why called "Next Generation" when there hasnt been a stable release in 3 years

### ISSUE THREAD

**Issue by c0nsaw** [mRemoteNG/mRemoteNG#2271]

**Comment by c0nsaw** [comment]
Ridiculous

**Comment by simonai1254** [comment]
mRemoteNG is the successor of mRemote which then used new technology and improved major things. Thats where the NG comes from. 

Now the question whether it's good or not that it took over three years to get a new stable build or not is completely another, but I'm confident that with the efforts of @Kvarkas there will be soon some great improvement which makes it into the stable build. So stay tuned...

**Comment by kbjc11686** [comment]
I am quite happy with 1.77.3. Had to hand create / copy a config file so a lot of my options can be saved. Once that problem is fixed, I'd imagine 1.78 or whatever is next after 1.77.3 will be close to release-worthy. Very good work @Kvarkas!

**Comment by Kvarkas** [comment]
@c0nsaw could you remind me how many lines of code you contribute to project? Or did you do donate perhaps? OR what else give you background to be so unhappy and expecting other do something for you for no support? I know that meme that programmers don't have personal life unfortunately I am not one of them :) I do have 2 kids and wife and spending on this project as mush spare time I have, but to make it to right satisfaction level (currently I am not happy also if that helps you!) a lot of changes need to be implemented I am working on such as much as I can. So please do help (PR is more than welcome! Or donate - so I can spend donated money to pro freelancers to help with code
