### ISSUE TITLE
WSL as an externat tool

### ISSUE THREAD

**Issue by plegrand1** [mRemoteNG/mRemoteNG#2279]
Hello,
I try to use "WSL" via mRemoteNG without success.
The "wsl" and "bash" commands work correctly in a DOS command line window.
The files wsl.exe and bash.exe are well present in "C:\Windows\System32\"
C:\Windows\System32\wsl.exe
C:\Windows\System32\bash.exe

When I try to create an external tool with the following configuration 
File name : cmd
Arguments : /k wsl 
A DOS window opens with the following error message: 
'wsl' is not recognized as an internal or external command, an executable program or a command file.

Indeed, when I try to search for the file "wsl.exe" in "C:\Windows\System32" via the "Browse" button of mRemoteNG, the file does not appear.
But via the explorer of windows, this file is well present.

Any idea where the problem could come from?

Thanks for your help.

Pascal

Windows    :10 21H2
mRemoteNG  :1.76.20.24669

**Comment by plegrand1** [comment]
I just discover that i have to use "sysnative" directory to make it work
then :
File name : cmd
Arguments : /K c:\windows\sysnative\wsl
works fine !!!

**Comment by thetuxinator** [comment]
@plegrand1 Could you maybe close this as you fixed it yourself?
