### ISSUE TITLE
Nightly 1.77.3 New config create every time I open the portable

### ISSUE THREAD

**Issue by Heroeskitchen** [mRemoteNG/mRemoteNG#2288]
## Expected Behavior
When opening the portable user.config should use the same config file

## Current Behavior
a new folder for the config file is created in appdata/Local/mRemoteNg and a new user.config file is generated every time

## Possible Solution
possibly store the user.config in the same directory as the portable?

## Steps to Reproduce (for bugs)
1. Run portable mRemoteng.exe from directory

## Context
I'm unable to save the theme or window positions.  I looked around the other issues, but I didn't see anyone report it for this version.  The popup for settings comes up every time I open the portable app

## Your Environment
* Version used: 1.77.3 nightly

**Comment by Kvarkas** [comment]
that not a bug that feature :) https://github.com/mRemoteNG/mRemoteNG/issues/2245
