### ISSUE TITLE
DB Schema for nightly build

### ISSUE THREAD

**Issue by pieterjanheyse** [mRemoteNG/mRemoteNG#2292]
Can someone please document the current DB schema for MSSQL on the nightly build? 

I am getting these errors when using mRemoteNG on the currently documented schema here: https://mremoteng.readthedocs.io/en/latest/sql_configuration.html

----------
ErrorMsg
09/28/2022 11:38:43
Couldn't save connections file as ""!
Column 'InheritUseRestrictedAdmin' does not belong to table .
----------
----------
ErrorMsg
09/28/2022 11:38:37
Couldn't save connections file as ""!
Column 'UseRestrictedAdmin' does not belong to table .
----------

**Comment by BastyJuice** [comment]
please also for MySQL / MariaDB

**Comment by FlamingoDaBird** [comment]
Facing similar issues with the Preview release as well (MSSQL). Not sure what script to use to set up the tables. Thank you :)

**Comment by SOlangsam** [comment]
I have created a fix for mysql. Should be an easy part to do it for mysql too.

**Comment by pieterjanheyse** [comment]
Based on the mysql file, I created the mssql file. Now patiently awaiting a new release, so I can save my settings.
[mssql_db_setup.txt](https://github.com/mRemoteNG/mRemoteNG/files/9777291/mssql_db_setup.txt)

**Comment by BlueBlock** [comment]
The SQL schema is now part of the code. The schema is created when the database exists and is empty.

https://github.com/mRemoteNG/mRemoteNG/pull/2362/commits
