### ISSUE TITLE
Too many issues that are no real issues here?

### ISSUE THREAD

**Issue by thetuxinator** [mRemoteNG/mRemoteNG#2297]
Hi,

It seems that we will never get a new version if the "new issues" not being real issues keep popping up in this speed. My suggestion would be to moderate the issues better and separate the non-dev related and "nice to have" ones from the bugs. Also some issues moderators would maybe help the developer to concentrate on bugs and new release. 

Any feedback to this suggestion is welcome.

regards

Tuxinator

**Comment by Kvarkas** [comment]
Yes, its a lot of issues that is really not issues and some are kind of issues :) if you check you will see we have nice tag cloud so they are for sure reviewed and marked, and no, each release usually cover 1-2 big issues and couple of smaller ones, however we are slow as cant spend all day on this due my primary job however trust me every evening its some work are happened ;) welcome to help btw :)
