### ISSUE TITLE
mRemoteNG not starting

### ISSUE THREAD

**Issue by senseof94** [mRemoteNG/mRemoteNG#230]
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74 Final  |

Hi. I've worked with mRemoteNG for some while now, but problem occurred today. 
Yesterday it was working fine, everything seemed to be ok, but today i simply can't make it to start. No errors, no messages, nothing. I checked in Task Manager-->Details. When i try running it, it pops up in Processes for about 3-5 seconds, then disappears. In Details i noticed that it starts, status is Running, then changes to Disabled and dissapears aswell. 
I don't see what possibly could have changed since yesterday when it was working fine.
Any solutions for this? Did try reinstalling it, no changes.

Best regards,
Kaspars

**Comment by kmscode** [comment]
Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page.

Try deleting the user.config, if that doesn't help, provide the information as noted.

**Comment by kmscode** [comment]
No feedback received. Closing.

**Comment by janborup** [comment]
Just got same problem after long time use of mRemoteNG v.1.75.
Tried to old Install ver. 1.72 that works fine but not version 1.75, still after several reinstalls and repairs.
Deleting all content in c:\Users\<user>\AppData\Local\mRemoteNG\ solved the problem.
/Cheers
