### ISSUE TITLE
start clion crash

### ISSUE THREAD

**Issue by cold-rivers-snow** [mRemoteNG/mRemoteNG#2303]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
![image](https://user-images.githubusercontent.com/43810831/203261208-1f6036f8-5fbd-497f-bef0-e409ad038d76.png)

![image](https://user-images.githubusercontent.com/43810831/203261209-f59994a9-cb39-49f7-b67e-473c55f3e440.png)

Clion can be used normally by using the software that comes with windows.Using mRemoteNG will report the error.

**Comment by Kvarkas** [comment]
its seems belongs to java nothing related with our software on first look, could you specify that version of mRemoteNg you are using?

**Comment by cold-rivers-snow** [comment]
![image](https://user-images.githubusercontent.com/43810831/203297301-a6e79916-ca68-4d1a-8b36-6e6e7a248e11.png)
I've tried all these versions and they don't work. Strange, Remote Desktop Conntction Manager can start clion normally

**Comment by simonai1254** [comment]
> I've tried all these versions and they don't work. Strange, Remote Desktop Conntction Manager can start clion normally

Would you mind elaborating what "it does not work" means? Are you unable to initiate RDP sessions, or does the application not even start? For me all above versions work with the limitation of 1.77.3-nb not being able to write configuration files...

**Comment by cold-rivers-snow** [comment]
The rdp session can be used normally, but when clion.sh is executed to start clion, a crash will occur, causing clion to fail to start. When I use Remote Desktop Conntction Manager to execute clion.sh to start clion, it can start normally.

**Comment by Kvarkas** [comment]
but question is once you connect with mRemoteNG - is that connection happening without any problem (before you are running clion)? We dont use java in our solution so its a bit interesting how it may impacting...

**Comment by cold-rivers-snow** [comment]
There is no problem with mReoteMG connection, before running clion.

**Comment by Kvarkas** [comment]
so this sounds as not mRemoteNG related issue for sure, however try to check if you run puttyNG.exe directly and try to connect same way are you see same issue?
