### ISSUE TITLE
Log4net vulnerability

### ISSUE THREAD

**Issue by procajlok** [mRemoteNG/mRemoteNG#2307]
FortiClient 6.0.9.0277 report vulnerability at **log4net.dll** in mRemoteNG 1.77.1.27654.

![obraz](https://user-images.githubusercontent.com/33727231/205227789-55f86b30-8bd4-460b-942d-54e55c3bedbd.png)

![obraz](https://user-images.githubusercontent.com/33727231/205227822-aa38a00e-c356-461a-9f07-c545793495c6.png)

**Comment by simonai1254** [comment]
This is a duplicate of #2199 (and #2019) -> use 1.77.2-nb or newer

**Comment by procajlok** [comment]
Ok, thx.

**Comment by Neustradamus** [comment]
To follow this ticket.
