### ISSUE TITLE
"Portable - 1.77.3 NB" prompts for "Automatic update settings" on every launch, never saves options

### ISSUE THREAD

**Issue by aderusha** [mRemoteNG/mRemoteNG#2314]
Nightly build "Portable - 1.77.3 NB" prompts for "Automatic update settings" on every launch.  Any changes made in "Options" do not last through a reboot.

Connection configurations persist and are saved as expected.

## Expected Behavior
Select an update setting, either in the "Automatic update settings" prompt or in options, and then that setting persists across restarts, and the user is not prompted.

Change an option, that change should persist across restarts.  They do not.

## Current Behavior

Any value set for the update settings is lost on restart, and the user is prompted on each start.  Other settings (eg, "save connections on exit") similarly do not persist across restarts.

## Steps to Reproduce (for bugs)

1.  Download and extract Portable - 1.77.3 NB
2. Run mRemoteNG, see prompt, select any option
3. Open File > Options, change any option
4. Restart mRemoteNG
5. Observe the update setting prompt re-appears
6. Check File > Options, previously made changes are lost.

## Context

This problem is only happening for me on 20220613 Nightly, previous builds save options as expected.

## Your Environment

Tested on Windows 11 and Server 2022, both patched to latest from MS.

**Comment by LIyoai** [comment]
Known issue
https://github.com/mRemoteNG/mRemoteNG/issues/2245

**Comment by rockmv** [comment]
I think it would be nice to be able to save the config in the Nightly as well. Precisely because you test it and then you can find the errors to a large extent.

**Comment by simonai1254** [comment]
Should be reintroduced with 1.77.4-nb, due soon.

**Comment by rockmv** [comment]
Then we hope that the new NB 1.77.4 will come soon.

**Comment by Kvarkas** [comment]
its for a reson, closing as changes are in place for new nb
