### ISSUE TITLE
Add exception for ctrl+win + arrows

### ISSUE THREAD

**Issue by 7OH** [mRemoteNG/mRemoteNG#2315]
Add exception for key ctrl+win+arrows to NOT redirect them to RDP.
Maybe with options.
This keys not used in rdp sessions anyway, but must work at host PC to switch between virtual screens.

Now it just not work (not at RDP , not at host).

It must work at host.

**Comment by simonai1254** [comment]
Could you please tell us what RDP settings you have for the mentioned connection (preferably add the exported XML to this issue) and what OS you are using? 
Depending on what RDP version is used it might not be possible to disable that function without keeping all combinations on your machine (https://superuser.com/questions/1070866/rdp-prevent-certain-shortcuts-from-being-passed-to-remote), mRemoteNG is using the Built-In RDP library...

**Comment by 7OH** [comment]
It's about RedirectKeys
[Test.zip](https://github.com/mRemoteNG/mRemoteNG/files/10205358/Test.zip)
I need redirect keys to rdp.
But will be nice to have ability for switch virtual screens at host PC.
Now - when i connect to remote - i can press WIN and menu shows at remote.
But if i press ctrl-win-arrow - i cannot switch virtual screen at my work pc.
Is it possible to not redirect those combinations ?

**Comment by 7OH** [comment]
Ok - understand.
It's windows behavoir.
