### ISSUE TITLE
available version is lower than installed version

### ISSUE THREAD

**Issue by vince2010091** [mRemoteNG/mRemoteNG#2319]
a picture is worth a thousand words
![Capture d’écran 2023-01-04 132701](https://user-images.githubusercontent.com/1927789/210554935-18ac4f24-a867-42ae-a8c0-8980afbfeb55.png)

**Comment by simonai1254** [comment]
Thanks for reporting. This is already known and is tracked with issue #1853.

**Comment by Kvarkas** [comment]
kits a bit a mess with versions for update but will have no back force, in latest version is implemented different approatch so it will be better
