### ISSUE TITLE
The database version 2.7 is not compatible with this version of mRemoteNG

### ISSUE THREAD

**Issue by fwehuerguweioergjioerier** [mRemoteNG/mRemoteNG#2324]
I can't do changes to my existing database.

## Possible Solution
Is there something, like an update script, that I could execute?

## Steps to Reproduce (for bugs)
Run mRemote Version 1.7.20.24615

## Context
Every user is affected.
The database is in use for some time.

## Your Environment

* Version used: mRemote Version 1.7.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11
* Database MySQL 2019 and 2016 (both tested, same result)

**Comment by Kvarkas** [comment]
does it work before? After that change its start droping issue?

**Comment by fwehuerguweioergjioerier** [comment]
> 

Hello, it did work before with the same client.
Because there are 5 users working in the same DB with different mremote clients, I don't know if maybe someone's client damaged the db for all users?

**Comment by savornicesei** [comment]
What version of mRemoteNG do the other users have?
Are there any errors displayed or in the log file (C:\Users\<your user>\AppData\Local\mRemoteNG)?

If you dump the data from db and import it into a new DB, does it work?

Thanks,
Simo

**Comment by fwehuerguweioergjioerier** [comment]
I fixed it by using the Preview release.

**Comment by Robertochavez1243** [comment]
I had the same error, my scenario is multiple users accessing the MRemote database,
Apparently a user wanted to access the sql database from the beta version, there he created a record in the tblRoot table in ConfVersion of 2.7,
I proceeded to delete the records of this table and recover the functionality of the Manager
