### ISSUE TITLE
Unsharp RDP-window when setting specific resolution on 34'' Screen 

### ISSUE THREAD

**Issue by W224EVER** [mRemoteNG/mRemoteNG#2326]
Hello mRemoteNG Team

I have a large 34'' screen with a resolution of 3860x2160 pixels. All of the rdp remote clients I connect to have a screen resolution of 1920x1200 or 1920x1080 (corresponding to the screen attached to the remote client). The problem with mRemoteNG is, that when I set 1920x1200 in the RDP-Connection, the panel that opens is NOT 1920x1200 but sort of "bigger" (2400x1500) and the the picture is not sharp at all. It does not matter how I size the main mRemote programm window - the panel shows an unsharp remote desktop screen with wrong resolution. I use the Microsoft Remote Desktop Manager 2.7 side-by-side an I do not have the same issue there! So the problem must be a setting or bug within mRemoteNG

Steps to reproduce:
1. create a new rdp connection
2. set the screen resolution to 1920x1200 (the same resoultion as the attached screen at the remote client)
3. connect to the remote client
4. if necessary resize the mRemoteNG window so that the remote desktop is fully shown (no scroll bars)
5. picture is unsharp, all the time - there is no setting to correct that
6. I use a screenshot programm to measure the size of the remote desktop window: it shows 2400x1500

Windows 11 Pro
latest mRemoteNG release

Thxs for your help
![2023-01-17  mRemoteNG Connection Settings](https://user-images.githubusercontent.com/122863983/212843581-20177a52-3254-481b-8695-bc849110cf48.png)

**Comment by W224EVER** [comment]
I found the "bug" in mRemoteNG:

mRemoteNG includes the scaling set on the local host under "System - Display - Scale" and also enlarges the remote desktop screen with the same factor!

Because I have a large Display with 3860x2160 resolution and the icons and text are quiet small, I set the scaling on my computer / screen to 125%. Now all the RDP-Connection-Windows within mRemoteNG are also enlarged to 125%: 1920x1200 will result in 2400x1500. When I set the scaling to 100%, the rdp-windows have the "right" size of 1920x1200!

So please include a option in the mRemoteNG settings to NOT include the scaling for remote connections! Is that possible? 

P.S.: And I wonder why does the Microsoft Remote Desktop Manager 2.7 does not have the same behaviour??

Thxs

![2023-01-17 Windows 11 set screen scaling](https://user-images.githubusercontent.com/122863983/212849903-64d07190-b80b-44e2-9a07-bed506a62b6c.png)

**Comment by Kvarkas** [comment]
its know issue due winforms strugling to scale properly to big screens, I was try to implement some fixes but its not work well (I am on 32" 4k display also) so please be patient will try to fix that with migration to wpf (they do work correctly on any resolution due different rendering approatch from microsoft. at this point its not much I could do with curent architecture of UI.

**Comment by W224EVER** [comment]
Thxs for the answer - I will the wait for the next relese of mRemoteNG.
