### ISSUE TITLE
Getting a new developer up and running

### ISSUE THREAD

**Issue by BlueBlock** [mRemoteNG/mRemoteNG#2327]
I'm interested in contributing some dev time. Is there a current developer able to spare some time to walk me through the finer points of the project design?

**Comment by simonai1254** [comment]
I think currently there is only @Kvarkas actually working on it, I hope he'll get in touch with you :)

Support is welcome for sure 😊

**Comment by BlueBlock** [comment]
Thanks. 

I read that the current code doesn't build and I did in fact run into that problem. I was able to 'fix' those build problems and get a clean build.

Hopefully I can tackle some of the simple low-hanging fruit issues once I get more familiar with the code base.

**Comment by mister-alien** [comment]
@BlueBlock Where did you read the code doesn't currently build? Built out of the box for me, also trying to get familiarized here too.

**Comment by Kvarkas** [comment]
hey ho, just back after holidays, will contact in person a bit later today.

**Comment by BlueBlock** [comment]
> @BlueBlock Where did you read the code doesn't currently build? Built out of the box for me, also trying to get familiarized here too.

I don't recall the issue where it was mentioned, but I was not able to build using a clean fork. One thing I had to do was adjust the build order and add 2 projects for their dependency. 

To run successfully, I also needed to add a default value for a setting.
"ConDefaultRDGatewayExternalCredentialProvider" with a value of "None"

I'll make some pull requests so the changes I needed to make can be viewed.

**Comment by savornicesei** [comment]
Hi all,

I also tried to build in Debug mode the  v1.77.3-dev branch on a clean repo. The Installer project silentry failed due to missing CustomActions.dll. To fix it I added CustomActions as a dependency for Installer project.
Still the installer post build script failed due to 
```
Copy-Item : Cannot find path 'E:\OSS\mRemoteNG\mRemoteNGInstaller\Installer\bin\Release\en-US\mRemoteNG-Installer.msi' 
2>	because it does not exist.
2>	At E:\OSS\mRemoteNG\Tools\rename_and_copy_installer.ps1:13 char:1
```
This is caused by not passing the BuildConfiguration to `rename_and_copy_installer.ps1`. Changes required:
- in `postbuild_installer.ps1`, last line
```
& "$PSScriptRoot\rename_and_copy_installer.ps1" -SolutionDir $SolutionDir -BuildConfiguration $ConfigurationName.Trim()
```
- and `rename_and_copy_installer.ps1` becomes:
```
param (
    [string]
    $SolutionDir,
    [string]
    $BuildConfiguration
)


$targetVersionedFile = "$SolutionDir\mRemoteNG\bin\x64\$BuildConfiguration\mRemoteNG.exe"
$version = &"$SolutionDir\Tools\exes\sigcheck.exe" /accepteula -q -n $targetVersionedFile
$src = $SolutionDir + "mRemoteNGInstaller\Installer\bin\$BuildConfiguration\en-US\mRemoteNG-Installer.msi"
$dst = $SolutionDir + "mRemoteNG\bin\x64\$BuildConfiguration\mRemoteNG-Installer-" + $version + ".msi"

# Copy file
Copy-Item $src -Destination $dst -Force
```
@BlueBlock Can you confirm this, please?

Thanks,
Simo

**Comment by Kvarkas** [comment]
hello, we have wiki https://github.com/mRemoteNG/mRemoteNG/wiki its have in general all you need, but happy to help wtih that is missing perhaps or not clear, so @savornicesei as you see from msg its expect project to be build first, then its create such folders. Main project is mRemoteNG, for installer you need to install [wix toolset](https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm) and [extension](https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension)

**Comment by savornicesei** [comment]
Hi @Kvarkas 
This is not related to development setup but more to the build order and path hardcodings in the build scripts. 
I can create an issue and PR later today.

Best,
Simo

**Comment by Kvarkas** [comment]
I aprove pr so this one in general to be on same page ;)

**Comment by BlueBlock** [comment]
@savornicesei , PR #2334 resolves the build order. That problem should be resolved when you build now.

**Comment by savornicesei** [comment]
@BlueBlock  I'll check it out
