### ISSUE TITLE
Clicks messed up on reconnection to RDP

### ISSUE THREAD

**Issue by brianclink** [mRemoteNG/mRemoteNG#2328]
## Expected Behavior

When I return/rec-connect to the RDP session, I should be able to continue using mRemoteNG by clicking on servers, interacting with them, etc.

## Current Behavior

Not sure when started happening, but I did change laptops recently.  When I come back / re-connect to my RDP session, first there is a general RDP UI issue - the screen seems to want to repaint, the task bar is a bunch of black boxes, etc., and have to wait a couple minutes for the GUI to return to normal.  
![image](https://user-images.githubusercontent.com/4602264/214693093-f15932e3-80ca-401d-9825-d963fa7612ae.png)

This is likely unrelated to mRemoteNG.

Then I switch / go to the mRemoteNG window which seems to be behaving oddly -- again not sure if this is actually mRemoteNG's fault or Windows is messed up.  I can't do anything in the right pane, I can't close the application using X., and if I click on a server on the left-hand side, it will show that I selected a different server, maybe three lines down.

## Possible Solution

I close it by going to the task bar, right-click on the icon, and click "close window".  This closes mRemoteNG, and then I can immediately open it up again, and it will behave normally.

## Steps to Reproduce (for bugs)

1. Use mRemoteNG in an RDP session
2. Close connection (not logoff)
3. Re-open connection
4. Go back to mRemoteNG window to interact

## Context

I don't know if this is mRemoteNG, seems very odd issue.  Windows itself seems to be having a hard time with repainting the screen after reconnecting -- maybe I have way too many windows open because I am so productive. 

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

Host OS: Windows 11
RDP to Windows 10 Enterprise 21H2 where mRemoteNG is installed
mRemoteNG version 1.76.20.24615

**Comment by Kvarkas** [comment]
UI a bit messy in current stage, planing to work on UI improvements in 77.4 builds.

**Comment by brianclink** [comment]
>> I can't close the application using X., and if I click on a server on the left-hand side, it will show that I selected a different server, maybe three lines down.

This appears to be a Windows issue, I found another application that has a list view that does the same thing where clicks are not working as expected, selecting something else -- I don't think this is mRemoteNG related, so can close this issue.  This is the weirdest Windows behavior I've seen so far.

**Comment by simonai1254** [comment]
@brianclink Do you have Windows Scaling enabled by any chance? Might be the case if you are not using 100%...

**Comment by brianclink** [comment]
Thanks for pointing this out.  On the computer where mRemoteNG is running Windows 10, and 'Advanced Scaling Settings' has a toggle 'Let Windows try to fix apps so they're not blurry' enabled.  Otherwise it is not showing me the settings because I'm in a remote session  
![image](https://user-images.githubusercontent.com/4602264/215566347-f958e21a-79d6-44b0-ab29-593445773ed7.png)
On my Windows 11 laptop which I am using to RDP to the above computer, it is showing 125%, apparently the 'recommended' value which was chosen by Windows.
![image](https://user-images.githubusercontent.com/4602264/215566525-1e135989-5ad1-428b-bbd5-b755a189dc8a.png)
Not sure which one I should look at tweaking - I could try unselecting the toggle on mRemoteNG computer, or I could force the scaling to 100% on my laptop where I am connecting from.

**Comment by simonai1254** [comment]
Just out of curiosity I would suggest you try to set your notebook that you are using for the RDP sessions to 100%, does it behave better then?

**Comment by brianclink** [comment]
Thanks, I set the scaling to 100% on the laptop, and funny thing... it fixed the mRemoteNG and another application, but then other applications (like Outlook and Word) are now exhibiting similar behavior, but its like the 'real' cursor is now above and to the left of where it appears to be pointing on screen whereas before it seemed to be just above.  So basically it fixed the issue and caused other issues.  But definitely it had an effect.

**Comment by brianclink** [comment]
I just unchecked this toggle on the computer I'm connecting to (Windows 10), and so far it seems better, I will keep updating this ticket if it sticks.

![image](https://user-images.githubusercontent.com/4602264/215794895-d82a2881-6c54-42a6-82c6-a20b8b75980e.png)

**Comment by brianclink** [comment]
Reconnected multiple times, so far this has fixed the weird behaviors.  Looks good.

- changed scaling on the laptop to 100%
- disabled the "fix scaling for apps" on the target computer

Thanks @simonai1254 for pointing me in the right direction.

**Comment by simonai1254** [comment]
Nice to hear it worked out :)

Now maybe you would like to try the Version 1.77.2-nb to see if the pre-release version behaves the same? 

Otherwise it would be great if you close this issue as resolved...
