### ISSUE TITLE
Crash with VNC tab open

### ISSUE THREAD

**Issue by milanraf** [mRemoteNG/mRemoteNG#233]
HW platform: Fujitsu S935 - 12GB - 500GBHD
Operating system - Windows 7 x64 Pro
.NET version 4.6.1
mRemoteNG version 1.74.6023.15437

App crashes while VNC connection tab is open, redirected thru SSH connection to KVM virtual host.
SSH connection is in tab aswell.

Very random appearance, unable to reproduce it.

Error trace
=======
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.NotImplementedException: RemoteDesktop in unknown State: Disconnecting.
   in VncSharp.RemoteDesktop.OnPaint(PaintEventArgs pe)
   in System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   in System.Windows.Forms.Control.WmPaint(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in VncSharp.RemoteDesktop.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    Versione assembly: 1.74.6023.15437
    Versione Win32: 1.74.6023.15437
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/mRemoteNG.exe
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    Versione assembly: 1.2.15.0
    Versione Win32: 1.2.15.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/log4net.DLL
----------------------------------------
System.Management
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Versione assembly: 2.9.0.0
    Versione Win32: 2.9.0.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light
    Versione assembly: 2.9.0.0
    Versione Win32: 2.9.0.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light.DLL
----------------------------------------
mRemoteNG.resources
    Versione assembly: 1.74.6023.15437
    Versione Win32: 1.74.6023.15437
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/it/mRemoteNG.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
MagicLibrary
    Versione assembly: 1.7.4.0
    Versione Win32: 1.7.4.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/MagicLibrary.DLL
----------------------------------------
WindowsBase
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Web
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1055.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.resources.dll
----------------------------------------
VncSharpNG
    Versione assembly: 1.3.4896.25007
    Versione Win32: 1.3.4896.25007
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/VncSharpNG.DLL
----------------------------------------
AxInterop.MSTSCLib
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/AxInterop.MSTSCLib.DLL
----------------------------------------
Interop.MSTSCLib
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Program%20Files%20(x86)/mRemoteNG/Interop.MSTSCLib.DLL
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by kmscode** [comment]
Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page and provide the information (logs and dumps) as noted.

**Comment by kmscode** [comment]
Give this one a whirl... 

Code can be viewed here: https://github.com/mRemoteNG/VncSharp/commit/2b94fe6a635e52cd1d6628314b905d146a99756a
[VncSharp.zip](https://github.com/mRemoteNG/mRemoteNG/files/579426/VncSharp.zip)

**Comment by kmscode** [comment]
@milanraf - any chance to test that binary? Did this resolve the problem?

**Comment by milanraf** [comment]
Downloaded VncSharp.zip
Unzipped VncSharp.dll in C:\Program Files (x86)\mRemoteNG
Renamed VncSharpNG.dll to VncSharpNG_OLD.dll
Renamed VncSharp.dll to VncSharpNG.dll
Assembly does not load:
ERROR- Opening connection failed!
Could not load file or assembly 'VncSharpNG, Version=1.3.4896.25007, Culture=neutral, PublicKeyToken=61974755c7bfea7c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Hope I've done it right....

**Comment by kmscode** [comment]
@milanraf 

Sorry... VncSharpNG was replaced with the standard "upstream" VncSharp library - trying to continue to contribute to other used Open Source projects where we can. This was done after the 1.74 release. So you'll need the latest [1.75 Alpha 3](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Alpha3) in order to test that binary. They have been quite stable. Maybe try with the portable version so you don't impact your current installation?

**Comment by kmscode** [comment]
@milanraf 

Are you able to try to test this in the current [beta](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Beta1)?

You can test this by running the portable version. Be sure to COPY your current confCons.xml into the extracted beta 1 portable directory, then replace the vncsharp.dll that I previously attached.

If you can validate this, then I can get the fix into beta 2.

**Comment by milanraf** [comment]
Tested with 1.75.6068.25511 with similar results.

I'm now almost able to reproduce the crash.
When VNC server crashes or is terminated, most of times VNC client in mRemote hangs pushing mRemote to crash.
More rarely a VNC server crash/kill just makes connection drop with no immediate effects but mRemote could crash within 1 hour.
Log file is always 0 bytes...

**Comment by kmscode** [comment]
@milanraf Sorry for the delay on this...

Are you able to test this with the latest 1.75 beta 3 and the previously provided vncsharp.dll? If you are still expierening crashes with that combination, could you please provide me with the stack trace from the error/crash/event log message?

Thanks.

**Comment by kmscode** [comment]
This requires further testing and validation. Not included in 1.75. Re-targeting for 1.76.

**Comment by milanraf** [comment]
Sorry, it is not clear whether I should test it with current beta or wait for 1.76.

**Comment by kmscode** [comment]
Fixed in commit d5d4fdefc8f7fa3be84afd3e2956f22f455c6358

Will be included in 1.76
