### ISSUE TITLE
Sorting of port scanner results 

### ISSUE THREAD

**Issue by Abzwingten** [mRemoteNG/mRemoteNG#2336]
While sorting the port scanner results by hosts it goes like this:

172.16.122.198
172.16.122.199
172.16.122.2
172.16.122.20

## Expected Behavior
I think more logical way is this:

172.16.122.1
172.16.122.2
.....
172.16.122.198
172.16.122.199
172.16.122.200
172.16.122.201

## Possible Solution
Implement a sorter that respects octets of the address.

## Environment
nightly build 1.77.1.27713, Windows 10

**Comment by Kvarkas** [comment]
There is idea to exclude such and allow as external app or plugin in feature, so not planed curently any changes.
