### ISSUE TITLE
Time for a new Nightly build?

### ISSUE THREAD

**Issue by lars18th** [mRemoteNG/mRemoteNG#2345]
Hi,

Last Nightly build is from around 9 months, and without support for storing configuration (it's useless). Therefore, a new version is expecting to come soon. Right?

**Comment by BlueBlock** [comment]
I am working on getting the nightly builds to begin again. I would say we'll have it going again by 1/20.

**Comment by garpunkal** [comment]
Did you get nightly builds working?

**Comment by BlueBlock** [comment]
Targeting Monday 2/20/23

**Comment by lars18th** [comment]
> Targeting Monday 2/20/23

Where we can download them?

**Comment by simonai1254** [comment]
Releases are published here on GitHub (https://github.com/mRemoteNG/mRemoteNG/releases) and are linked on the homepage itself: https://mremoteng.org/download. You can subscribe on GitHub to be notified for new releases.

**Comment by BlueBlock** [comment]
Once available, the new nightly builds will be available on the releases page:

[https://github.com/mRemoteNG/mRemoteNG/releases](url)

**Comment by lars18th** [comment]
Hi @BlueBlock ,

> Once available, the new nightly builds will be available on the releases page:
> [https://github.com/mRemoteNG/mRemoteNG/releases](url)

I'm impatient to see them! 😜

**Comment by BlueBlock** [comment]
I think Dimitrij will create the Nightly tonight at some point if there are no large bugs.

**Comment by savornicesei** [comment]
Just curious: do they need to be build and published manually? Do they count to the space limit of the GH account? Or there is no limit for releases for OSS projects?
Thanks.

**Comment by Kvarkas** [comment]
still working towards it, a bit delayed. 
@savornicesei I do it manualy but BlueBlock have some nice ideas to automate so we will try to implement it (so potentialy nb may be happened a bit more ofthen :) ) As far as I am aware github dont limit us on space so potentialy its no limit, but I may not expect nb hapening every night... but it may happened once something changes and we add some fix or feature to try... 
So far updated blog post: https://mremoteng.org/posts/

**Comment by savornicesei** [comment]
@Kvarkas Thank you.
There is a Powershell wrapper over GH api so it should be doable with the current build process. I already built a nightly pipeline that pushes NuGet packages to GH feed [here](https://github.com/Wyam2/wyam/blob/main/.github/workflows/nightly.yml) - with proper adjustments it can push new releases.
@BlueBlock Let me know if I can help you in any way with the nightly.

Best,
Simo

**Comment by Kvarkas** [comment]
@savornicesei we are using https://ci.appveyor.com/ if you wish - register and send me your email will invite, also we use element chat (matrix ex gitter, pub to all, separate for devs only - may be a bit more flexible to communicate - https://matrix.to/#/#mRemoteNG_PublicChat:gitter.im

**Comment by BlueBlock** [comment]
Thanks @savornicesei

**Comment by BlueBlock** [comment]
An update. The cert used to sign the builds has expired. Acquiring a new cert is in progress.

**Comment by Kvarkas** [comment]
Please check new [NB](https://github.com/mRemoteNG/mRemoteNG/releases/download/2023.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi)

**Comment by lars18th** [comment]
> Please check new [NB](https://github.com/mRemoteNG/mRemoteNG/releases/download/20223.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi)

The link doesn't work. Only this: https://github.com/mRemoteNG/mRemoteNG/releases/tag/2023.03.03-v1.77.3-nb

But, in any case please think that if "settings are still not alow to save" then this NB is useless. I suggest to remove it until you can publish something with settings enabled. However, IMHO that's only "a suggestion". 😉

**Comment by Kvarkas** [comment]
Link corrected, dubble 2 removed. NB are not for use in work, just to test new fixes and updates, in curent one major fix was option page speed and sql fixes, also working to make CI working properly so anybody will allow download NB from appvayor without devs interaction ;) stay tuned.

**Comment by lars18th** [comment]
> ;) stay tuned.

Yes. I'll do it.

However, plase don't say: "NB are not for use in work". The last release ([v1.77.1]) has more that three years and a half of time. And it lacks a lot of must-have functionalities. Therefore more or less _all_ users are using one NB. And for this reason we need to go forward soon with "settings allowing to save".

**Comment by Kvarkas** [comment]
лет ми спик фром май харт (c) :)
Let me explain that we have there. Where is 3 channels: Prod, Preview, Nigthly Build. So frankly speaking Release is from prod, Preview is almost ready for Release just check for some minors bugs, Nightly build is alfa version, developers check - you name it. Once we happy with major functionality we will release preview and NB switch branch (next 1.77.4-dev) and we keep working on other bits, however in preview will be adding only bug fixes if any, no features will be added. And preview versions is ok to use for work, If no complains we will do a release of it. And only security vulnerability fix will be goes into it (if any) 
So NB is not working release. I undestand what you want (not you only) and we working hard towards such :)

**Comment by lars18th** [comment]
> I undestand what you want (not you only) and we working hard towards such :)

And for this reason @Kvarkas we don't ask for ETAs or similar. You're doing a huge effort! So please, continue as you can. But, try to enable "saving config". As "advanced users" we can decide to use or not a NB.
