### ISSUE TITLE
Feature Request : Using Proxy / Jump Server per connectdion

### ISSUE THREAD

**Issue by MoHasanJ** [mRemoteNG/mRemoteNG#2351]
Is there way to select just server or proxy server per connection, I could do that in WinSSHTerm but thats only limited to SSH connection, I really liked to have such feature in mRemoteNG. 

Or if its already there, where exactly I find it?

## Your Environment
Using version **1.76.20.24669**

**Comment by Kvarkas** [comment]
hello, could you please explain what you wish to do?

**Comment by simonai1254** [comment]
Could it be that #2330 solves your problem? mRemoteNG generally supports SSH tunnels, it just has a bug in Version 1.76.20 up to 1.77.2-nb that the option is not displayed.

**Comment by Kvarkas** [comment]
close due no responce from caller

**Comment by MoHasanJ** [comment]
Oh, well, I missed it. Actually I was referring to something like this (taken from winsshterm): 
![image](https://user-images.githubusercontent.com/39223873/229755991-7f7f928c-9bdc-4883-bd88-49571d822c6f.png)
It could be really helpful as sometimes you need to connect to services by VPN. I generally use socks proxy which avoids connecting VPN need for that service and also access multiple services with their own socks5 proxy.
