### ISSUE TITLE
Unable to load key file "..." (PuTTY key format too new)

### ISSUE THREAD

**Issue by martin-erler-ksi** [mRemoteNG/mRemoteNG#2354]
mRemoteNG is not supporting PuttyGen SSH key files of the currenty PuttyGen version (PuTTY-User-Key-File-3).

## Expected Behavior
When opening a putty-saved-session, where an SSH key file is linked, and the key file was created with the current version of PuttyGen (0.76), it should use the key file and connect.

## Current Behavior
When opening a putty-saved-session, where an SSH key file is linked, and the key file was created with the current version of PuttyGen (0.76), it show this message:
"Unable to load key file "path/to/file.ppk" (PuTTY key format too new)"

## Context
I cannot use newer sessions stored by Putty.

## Your Environment

* Version used: mRemoteNG 1.77.1.27654
* Operating System and version: Windows 10 22H2 x64

**Comment by maxbethge** [comment]
Had same issue. I installed newest Putty version and updated mRemoteNG settings to point to that Putty install instead of the bundled Putty.

**Comment by Kvarkas** [comment]
please do manual update for puttyNG, copy from [where](https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.78.0.10/PuTTYNG.exe) and replace older

**Comment by maxbethge** [comment]
> please do manual update for puttyNG, copy from [where](https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.78.0.10/PuTTYNG.exe) and replace older

This also worked for me

**Comment by martin-erler-ksi** [comment]
Thanks, this workaround is working.

**Comment by simonai1254** [comment]
I would suggest to close this issue in favor of #2027 which handles the dependency problem that mRemoteNG needs to create releases to update PuttyNG.

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
