### ISSUE TITLE
migrate from mRemote3G

### ISSUE THREAD

**Issue by dsstorm** [mRemoteNG/mRemoteNG#236]
I used mRemoteNG, then moved on to mRemote3G. Now I want to use mRemoteNG.

But when I'm in a new portability mRemoteNG copy confCons.xml, extApps.xml and addons's folder from mRemote3G, the program dont see any external app. 
These fields are empty.

**Comment by kmscode** [comment]
Can you attach the extApps.xml?

Please also attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

**Comment by dsstorm** [comment]
![folder](https://cloud.githubusercontent.com/assets/18022579/20205762/5d128354-a7ec-11e6-9816-59e3868f1c15.png)
[mRemoteNG.zip](https://github.com/mRemoteNG/mRemoteNG/files/585087/mRemoteNG.zip)

**Comment by dsstorm** [comment]
are you search bug?

**Comment by kmscode** [comment]
@dsstorm The log doesn't display properly for me since it appear to be in Russian. 

However, I was able to load your extApps.xml without any problems.

I'm guessing that the messages in the mremoteng.log are mentioning about the differences in the config file format. You should be able to open the confCons.xml in mRemoteNG and then save it. That should put it into the new/correct format. Make sure you have a backup first.

Once that is done, close and reopen mRemoteNG and see if you are still having problems.

**Comment by dsstorm** [comment]
this solution does not work.
Created 2 test connections. Connecting to the same server. (ext app).
if confCons.xml ( from mRemoteNG-Portable-1.75.6067.31411) put into OLD mRemote3G.exe - it works.
if confCons.xml ( from mRemote3G) put into NEW mRemoteNG-Portable-1.75.6067.31411 - dont work
[сравнение.zip](https://github.com/mRemoteNG/mRemoteNG/files/594150/default.zip)
![oldvsnew](https://cloud.githubusercontent.com/assets/18022579/20341471/69d37008-abf7-11e6-82c2-930b12d86d4f.PNG)
![old3ginnewng](https://cloud.githubusercontent.com/assets/18022579/20341474/6be22236-abf7-11e6-8c40-e4f5ebdd43e3.PNG)

**Comment by dsstorm** [comment]
After I take a file (confCons.xml) from mRemote3G , insert into mRemoteNG, manually choose the external application and save. (new format is applied.)
Compare two files can be seen that a different file format (green - in new file)
![Uploading 666.pNG…]()

**Comment by kmscode** [comment]
@dsstorm Could you please clarify what the problem is? Are you running into problems with external apps, or with connections?

**Comment by kmscode** [comment]
[1.75 RC1](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75RC1) has been released. Please download and test if this problem has been resolved.

**Comment by kmscode** [comment]
1.75 final release will happen soon. No significant changes from 1.75 RC1. Should you still encounter problems, please reopen this bug report.
