### ISSUE TITLE
mRemoteNG making unusual connections to the internet

### ISSUE THREAD

**Issue by IcePlains** [mRemoteNG/mRemoteNG#2363]
From time to time (once an hour or even once a week) i see mRemoteNG try to make connections to internet (port 80 iirc, did not write this down). I have "Check for updates at startup" disabled.

## Expected Behavior
mRemoteNG should not make any connection anywhere by itself when automatic update checks are disabled.

## Current Behavior
mRemoteNG randomly tries to connect to the internet. I wrote down last few attempts. Probably all are port 80, but i can not be sure as i did not write this down:
tcp://178.79.227.128
tcp://8.248.117.254
tcp://93.184.221.240

## Steps to Reproduce (for bugs)
I have not found a pattern when it tries to connect. If needed i can observe further to try to see a pattern when connections are attempted.

## Context
Where is it trying to connect to and for what reason?

## Your Environment
* Version used: mRemoteNG 1.77.2
* Windows 10 x64

**Comment by simonai1254** [comment]
How did you note mRemoteNG doing these requests? Just so I could try to reproduce it myself. 

And to be sure: You don't have any connections configured to go over the Internet?

**Comment by Kvarkas** [comment]
That strange, we dont need any side request for anything - if update is disabled its even dont go to try to reach update file from git repo. Will have a look to whom belongs such ip but so far dont think its us who need them.

**Comment by IcePlains** [comment]
@simonai1254: use any application firewall to show you which process is trying to connect somewhere. I let mRemoteNG connect to some places, the rest is blocked. One such is firewall is simplewall.
I have some connections configured to go over internet, but all of those are allowed in firewall.

A few more such requests, all to port 80. IPs differ from above ones. There may be some url resolution going on but i am just logging IPs so i cant say for sure.

A few instances when this happened that i can remember is when i connect to server via RDP. It connects without any problems but at the same time it tries to connect to these IPs as well.

**Comment by arnvid** [comment]
A quick checkout of those IP threat history shows atleast those you listed are known for being part of malware distribution. I would check the rest of your machine for potentional malware or hijacked/replaced DLLs that are triggered when mRemoteNG or other software does connetions. If your system is compromised then this would be a typical vector for an attacker to use to steal your logins as you connect to other systems.

**Comment by Kvarkas** [comment]
I duble checked our code and dont see any relation to call such externals url except github check and mremoteng.org for update information, as @arnvid guesing that may happened because system you are using is compromised by mailware, I may suggest to install [eset premium security](https://www.eset.com/uk/home/free-trial/) antivirus (even trail for 30days) and do full scan of you system.

**Comment by IcePlains** [comment]
Status update:
After your replies I reinstalled windows as a precaution. Fast check for malicious things did not reveal anything out of the ordinary. I kept old installation and will try to find culprit when i have more time. Fyi mRemoteNG program files are identical to new installation, so problem comes from somewhere else.
On new install, there are no unusual connections so far.

**Comment by Kvarkas** [comment]
Thanks for conformation mate
