### ISSUE TITLE
"Prompt before disconnecting sessions box"

### ISSUE THREAD

**Issue by FlowRush** [mRemoteNG/mRemoteNG#2365]
Hello, 

We are using version 1.76.20.246.15 of your application across several Windows 10 computers at our IT company. Me and my colleagues have a complaint, that whenever 1 person is logged into one of the Windows servers with a RDP session, and another person decides to remote connect to it, then the first person is kicked without warning or notice. 

Is it possible to warn the 2nd person that the first person is busy on the server, giving you the options to either: 

-Kick the first person,  

-Ask the first person to disconnect/take over the session 

-Cancel the attempted RDP connection? 

I cannot seem to find the “Prompt before disconnecting sessions box” setting that seems to be relevant. How can I configure this on all instances of MRemoteNG? 

And is it also possible to monitor active RDP sessions with MRemoteNG, before making RDP connections?

**Comment by Kvarkas** [comment]
Hi, that not related to our software, itw windows licence. You may try do rdp from another computer without mRemote and result will be same. If you using even same account its another session, so windows without terminal licence will kick user (black screen) and process with remote user session. 
However we already looking how to overwork such if posible but in 1.76.20 will not be added, actively developing version 1.77.3

**Comment by FlowRush** [comment]
In that case I will do more research how I can configure this on our Windows Server 2019 Datacenter, thanks.

**Comment by Kvarkas** [comment]
Have a look [there](https://www.top-password.com/blog/enable-multiple-remote-desktop-connections-in-windows-server/) basicaly you need get CAL licence Initialy its support 2 remote users at a time, each CAL expand such by 5.
