### ISSUE TITLE
putty version working underneath is too old

### ISSUE THREAD

**Issue by danifern-nokia** [mRemoteNG/mRemoteNG#2418]
Hi, 

I was having issues with mremoteng when using putty profiles with ssh proxy configuration and I realized that the putty version that is currently being used by the application is based on an old one only supporting 6 proxy types ( image attached ).Latests putty release (0.78) has support to about 8 proxy types including ssh proxy. Would it be possible to upgrade putty version in the application or use the one installed in the system instead in order to avoid issues?

Many thanks in advance
Note: I think this is a great tool, I use it every day. Thanks all for a great work

<img width="1917" alt="mremoteng_putty" src="https://user-images.githubusercontent.com/118918688/229304053-9444b50e-38bc-4844-8dc1-ad52fbe21bbb.png">
<img width="1917" alt="putty_0 78" src="https://user-images.githubusercontent.com/118918688/229304052-1d818cd0-5378-4521-b14d-282516654457.png">
<img width="1917" alt="putty_0 78" src="https://user-images.githubusercontent.com/118918688/229304054-a5f624be-c77f-43d4-b958-36527348bd43.png">

**Comment by Kvarkas** [comment]
Hello, we are using our own versions (same as original but some small amendmends for our needs only and we release it separately: https://github.com/mRemoteNG/PuTTYNG/releases
As well we have a documentation portion about how to do upgrade for older version mRemote to use this newer versions of putty (what nobody reads :D) but will post a link to: https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html?highlight=puttyng#problems-connecting-to-servers-using-ssh-with-mremoteng-version-below-1-77-3 
please update if you manage to upgrade it and use it ;)

**Comment by Kvarkas** [comment]
btw for screenshots I would like to recomend use this little tool: https://app.prntscr.com/en/index.html ;)

**Comment by danifern-nokia** [comment]
Thanks for your quick response. Indeed after upgrading puttyNG is working as a charm. The error I was seen, in case you want to include it in the documentation is "Proxy Error: Unkown proxy method" ( attached )

Regards
<img width="318" alt="PuTTYNG_ProxyError" src="https://user-images.githubusercontent.com/118918688/229379821-1033afa3-8691-4311-9b13-418826f3d95d.png">

**Comment by Kvarkas** [comment]
Thanks for confirmation, I cant reproduce this message in current developed version so perhaps not worth to worry about.
