### ISSUE TITLE
dont connect mssql

### ISSUE THREAD

**Issue by eightbit8888** [mRemoteNG/mRemoteNG#2424]
good afternoon, sorry for my english.
I'm trying to connect mRemoteNG to a MsSQL database, however the error is.
i have created a database. Created a table tblRoot, with columns
![image](https://user-images.githubusercontent.com/125024293/231185882-1175b564-f10c-4281-8bfa-7d572629f8f6.png)

bug this time

   в mRemoteNG.Config.Serializers.MsSql.SqlDatabaseMetaDataRetriever.GetDatabaseMetaData(IDatabaseConnector databaseConnector) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Serializers\ConnectionSerializers\MsSql\SqlDatabaseMetaDataRetriever.cs:строка 45
   в mRemoteNG.Config.Connections.SqlConnectionsLoader.HandleFirstRun(SqlDatabaseMetaDataRetriever metaDataRetriever, IDatabaseConnector connector) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:строка 99
   в mRemoteNG.Config.Connections.SqlConnectionsLoader.Load() в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Config\Connections\SqlConnectionsLoader.cs:строка 47
   в mRemoteNG.Connection.ConnectionsService.LoadConnections(Boolean useDatabase, Boolean import, String connectionFileName) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\Connection\ConnectionsService.cs:строка 126
   в mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.ReinitializeSqlUpdater() в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:строка 82
   в mRemoteNG.UI.Forms.OptionsPages.SqlServerPage.SaveSettings() в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\OptionsPages\SqlServerPage.cs:строка 72
   в mRemoteNG.UI.Forms.FrmOptions.btnOK_Click(Object sender, EventArgs e) в C:\jenkins\workspace\Publish\Build mRemoteNG for Release\mRemoteV1\UI\Forms\FrmOptions.cs:строка 128
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

OS: Microsoft Windows NT 10.0.19044.0
mRemoteNG Version: 1.77.1.27654
Edition: MSI
Cmd line args:

**Comment by Kvarkas** [comment]
Старая версия, в новой немного другой подход и уже не нужно самому создавать таблицы - она сама создает что ей нужно, попробуй - https://github.com/mRemoteNG/mRemoteNG/releases/download/2023.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi

**Comment by eightbit8888** [comment]
> Старая версия, в другом другом подходе и уже не самое необходимое создание таблицы - она ​​сама создает что ей нужно, попробуй - [https://github.com/mRemoteNG/mRemoteNG/releases/download/2023.03.03-v1.77.3-nb /mRemoteNG-Installer-1.77.3.nb-1784.msi](https://github.com/mRemoteNG/mRemoteNG/releases/download/2023.03.03-v1.77.3-nb/mRemoteNG-Installer-1.77.3.nb-1784.msi)

Thanks a lot! That helped
