### ISSUE TITLE
click on full screen & connection interruption

### ISSUE THREAD

**Issue by daydayyuman** [mRemoteNG/mRemoteNG#2426]
## Expected Behavior

Maximize the window for convenience quickly, not to connect again.
## Current Behavior

When I click on full screen or Restore Down, there is a connection interruption and I am reconnecting again.Usually it takes a lot of time，AND It is so inconvenience.

## Possible Solution

Do you have the same question? Looking forward to your answer.
## Context

I've been troubled by this problem for a long time.
## Your Environment

* Version used:Windows 10 Operation System X64，mRemoteNG Version 1.76.20.24669

**Comment by simonai1254** [comment]
Hi

This RDP issue was somewhat addressed with version 1.77.1 (and newer) and is tracked with the following issues:

- #2054 (connection lost when resizing) and 
- #2361 (all connections lost when moving window from screen to screen).

Additionally, the following issues are related: 
- #2422 (Automatic Resizing Broken with newer Build)
- #1666 (session unlocked with resizing)

Please have a look at these issues as well, thanks. Regards
Simon

**Comment by Jenty8** [comment]
这个问题您解决了嘛？我也出现这种问题

**Comment by Kvarkas** [comment]
we unable to fix that issue for 1.76.20 version, but please check new NB version - it should not have such issue.
