### ISSUE TITLE
Feature Request: Have Putty fatal error dialogs be modal to their respective tabs, not global

### ISSUE THREAD

**Issue by inthroxify** [mRemoteNG/mRemoteNG#243]
Request: Have Putty session error dialog windows show only when the associated session tab is active, and ensure that Putty error dialogs in other tabs do not steal focus when they appear.

Currently, if PuttyNG throws a fatal error, such as a network connection closing unexpectedly (perhaps due to network connectivity loss), any error dialogs generated by Putty are associated to the global mRemoteNG window and float over it. If multiple Putty session tabs are open and generating error dialogs, this can result in a stack of error dialogs on top of everything, which are ultimately not useful information because it is difficult to determine which Putty session tab the error actually applies to (see attached screenshot). Switching between Putty session tabs (both connected and disconnected) when a stack of error dialogs is present leaves all of the error dialogs stacked on the main mRemoteNG window.

![Screenshot depicting two putty fatal error dialogs stacked on top of each other with 3 putty tabs in behind, making it unclear which error applies to which tab](https://cloud.githubusercontent.com/assets/13877157/20193322/b7e2c6ba-a74a-11e6-900f-5bc891f045a1.png)

Suggested desirable behavior: have the Putty error dialog for a particular session show only when the respective session tab has focus. If the tab loses focus, the error dialog is hidden and not shown until focus returns to the session tab that the error dialog belongs to.

Possible alternate behavior if the above is not possible: a notification bar at the top of the session window appears instead of a popup dialog, containing the error message and appropriate action buttons.

**Comment by kmscode** [comment]
Will leave this open in case things change... But it's unlikely that we will implement this anytime soon. Efforts are more likely to be put into #181

**Comment by eduardofbrito** [comment]
https://www.confidantmail.org/wordpress/index.php/2020/04/05/putty-ssh-client-eliminate-modal-fatal-error-pop-up/

**Comment by AJolly** [comment]
Would be nice to do this without recompiling

**Comment by Kvarkas** [comment]
that seems to be doable, as we use slightly modified version of putty so adding one more mod will be not a big deal :)

**Comment by Kvarkas** [comment]
Used this approach https://allones.de/2021/08/15/relax-putty-suppress-fatal-error-dialog/ to implement such, forcing updated PuTTYNG release.
![image](https://github.com/user-attachments/assets/48d4dceb-3995-4794-9062-439ee3a04acd)

**Comment by inthroxify** [comment]
Kvarkas, that is a rad solution. Thanks for this!

**Comment by AJolly** [comment]
Wow I'm impressed! This is annoyed me for years but never enough to do anything about it, since I'm no longer a sysadmin.

**Comment by Kvarkas** [comment]
> Wow I'm impressed! This is annoyed me for years but never enough to do anything about it, since I'm no longer a sysadmin.

where is no ex-sysadmins as far as I know :D
