### ISSUE TITLE
404 page not found - Nightly MSI

### ISSUE THREAD

**Issue by antoinekh** [mRemoteNG/mRemoteNG#2437]
v1.77.3.1442-NB
link: https://github.com/mRemoteNG/mRemoteNG/releases/download/20230316-1.77.3.1442-NB/mRemoteNG-Installer-1.77.3.1442-NB.msi

## Expected Behavior
Download the msi file

## Current Behavior
Error 404

## Possible Solution
fix the link

## Steps to Reproduce (for bugs)
https://mremoteng.org/download > nightly > msi

## Your Environment
windows

**Comment by Kvarkas** [comment]
thanks, has been fixed
