### ISSUE TITLE
Feature Request: Option for Notifications location. 

### ISSUE THREAD

**Issue by big-edd** [mRemoteNG/mRemoteNG#2439]
An option to have Notifications to be on the Left, rather than at the Bottom, would be really nice. 

Maybe a checkbox in the settings to select this. Or a dropdown list to select "Bottom" or "Left" (and maybe more). 
Notifications to appear on the Left, along with Config and Connections. 

No such option(s) currently, as far as I can tell. 

Maybe a checkbox in the settings to select this. Or a dropdown list to select "Bottom" or "Left" (and maybe more). 

This way the Notifications can be hidden, without causing reconnection (due to client pane resize) when it appears with a new message. 

Cheers, 
Eddie.

**Comment by Kvarkas** [comment]
we are using panels, you could change layout if you wish :)
![image](https://github.com/mRemoteNG/mRemoteNG/assets/3611964/2d460326-9522-4b12-bc03-576ea51358d1)
just drag header and drop to desired location ;)
