### ISSUE TITLE
Cannot extract rar files available in releases->Assets

### ISSUE THREAD

**Issue by JeanPluzo** [mRemoteNG/mRemoteNG#2440]
I have tried to download different nightly versions. However, using 7zip and windows integrated unzip tools, I cannot extract the contents of the compressed rar files.

## Expected Behavior
1- Download an Asset (mostly rar file)
2- Extract with my tool of choice 
3- Run mRemoteNG

## Current Behavior
7zip nor Windows are able to extract these compressed files

## Possible Solution
Change compressed format to 7zip

## Steps to Reproduce (for bugs)
See "Expected Behavior"

## Your Environment
OS: Windows 10 Pro 20H2 19042.2965
7zip 9.20

## Comments
I've also noticed that the naming convention in "Assets" isn't straight forward. Sometimes it's Portable.rar, sometimes 2022.01.07.Portable.rar, sometimes just Portable Edition.zip, and sometimes there's no compressed file.
Please choose a naming scheme and follow through. You'll save time and energy in the future.

If I can be of any help please leave a comment.

Regards,
J.

**Comment by Kvarkas** [comment]
use winrar tool.

**Comment by JeanPluzo** [comment]
Hi again,
I know I "could" use winrar, but in the spirit of open source, wouldn't it be better to use a compression format that is also open source?
Also, not everyone has complete control over their computer (work laptop is administered by the IT department), and not everyone wants to install winrar.
Please consider this in the next builds.

Regards,
J.

**Comment by Kvarkas** [comment]
winrar owners pay loaylti to me for promoting they product :D kidding 
nb are beta versions they provided only for entusiast, its have even special limitation to save settings so users not use them for work, but only who want to test early, however now then I start leading this project, nb will be provided in format of installer and portable version (not embed) so should be not a big problem ;)
