### ISSUE TITLE
Add screenshots to documentation site

### ISSUE THREAD

**Issue by swishkin** [mRemoteNG/mRemoteNG#2447]
## Expected Behavior

It'd be helpful to have screenshots of all themes shipped with mRemoteNG

## Current Behavior

No screenshots are available on the docs site, Github (unless I missed them), or elsewhere..

## Possible Solution

Below are screenshots of all themes in nightly 1.77.3

darculaNG
![mRemoteNG_darculaNG](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/f64bb6fd-db58-4b44-9a9b-20d91189d3d8)

vs2012Blue
![mRemoteNG_vs2012Blue](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/611e6330-2381-4bb8-8960-f8b5f26b72e5)

vs2012Dark
![mRemoteNG_vs2012Dark](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/f15e127f-0a1c-4020-baa4-d4afa589dc8b)

vs2012Light
![mRemoteNG_vs2012Light](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/c230eae0-30e1-4cee-84ea-b54f24aff6cf)

vs2013Blue
![mRemoteNG_vs2013Blue](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/c0008676-3a0e-4fcc-b30d-7c620ce7f907)

vs2013Dark
![mRemoteNG_vs2013Dark](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/14dd609c-275f-431e-ad23-e960b2a93b83)

vs2013Light
![mRemoteNG_vs2013Light](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/feadcfba-421d-44f0-8db2-730664a892a2)

vs2015Blue
![mRemoteNG_vs2015Blue](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/ae16dcfb-acc0-42f1-9e9e-36e5d5c07ef9)

vs2015blueNG
![mRemoteNG_vs2015blueNG](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/f4508790-1152-4089-985a-29a131d9ae54)

vs2015Dark
![mRemoteNG_vs2015Dark](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/71fa4772-88d4-4481-9c0f-0e31966b7a3c)

vs2015darkNG
![mRemoteNG_vs2015darkNG](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/3f71a66f-cb8b-41f7-9483-f51ad1eee43d)

vs2015Light
![mRemoteNG_vs2015Light](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/e5d421d8-fbe7-424e-8512-81e358796748)

vs2015lightNG
![mRemoteNG_vs2015lightNG](https://github.com/mRemoteNG/mRemoteNG/assets/19404743/34ec8bd1-8877-433c-9dd9-08ab7429a5d9)

## Steps to Reproduce (for bugs)

1. Check Github for photos
2. Check Documentation site for photos
3. Google mRemoteNG theme screenshots
4. No screenshots

## Context

I wanted to choose a theme, didn't know what they all looked like, and had to restart mRemoteNG ~13 times to see all of them.

## Your Environment

* Version used: 1.77.3
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 19044 21H2 x64

**Comment by Kvarkas** [comment]
thanks for that, where is a plan to change current thema system to adopt in better way (windows 11 style) but you did good job, will add such to docs

**Comment by Kvarkas** [comment]
added in #d8cf72d
https://mremoteng.readthedocs.io/en/v1.77.3-dev/themes.html
