### ISSUE TITLE
Unable to clone repository using Visual Studio 2022

### ISSUE THREAD

**Issue by xBounceIT** [mRemoteNG/mRemoteNG#2450]
After forking, cloning the repository using Visual Studio and opening the .sln file the following issue appears:

Not supported
The following projects cannot be opened in the current Visual Studio version.
It's possible to open this project using Visual Studio 2015, Visual Studio 2013 and Visual Studio 2010 SP1 without any edit.

Exception handled for \Installer\Installer.wixproj

**Comment by xBounceIT** [comment]
Solved by following this guide: https://stackoverflow.com/questions/26028746/visual-studio-vdproj-is-incompatible

**Comment by Kvarkas** [comment]
perhaps worth to add to documentation in case somebody else will have this. Just to confirm is yours studio is 2022?

**Comment by xBounceIT** [comment]
Hi,

yes i downloaded the latest version of Visual Studio 2022 and installed the .NET framework for C# Development. Out of the box that issue was appearing.
