### ISSUE TITLE
Update PuttyNG because very old 0.76

### ISSUE THREAD

**Issue by Neustradamus** [mRemoteNG/mRemoteNG#2452]
Dear @mRemoteNG team,

The last unstable build, currently "mRemoteNG-Installer-1.77.3.nb-1784.msi" has PuttyNG 0.76 (2021-07-17).

Can you update, currently it is 0.78 (2022-10-29) or 0.79-pre (2023-04-24)?

**Comment by Kvarkas** [comment]
Good spot! Actualy its 0.78 but in mentioned nb it was 0.76, you could update manualy or wait a bit - I am planing next nb this weekend.

**Comment by simonai1254** [comment]
See #2027

**Comment by Neustradamus** [comment]
It will be updated?

**Comment by Kvarkas** [comment]
its is updated, long time ago ;) download from there: https://github.com/mRemoteNG/PuTTYNG/releases/download/v0.78.0.10/PuTTYNG.exe

**Comment by simonai1254** [comment]
The issue is the control of the dependencies, where imho there is still potential to improve. But yes generally there is a new version of PuttyNG available to update manually which will also be included in the next build. 

See https://mremoteng.readthedocs.io/en/latest/known_issues.html#mremoteng-bundles-a-legacy-putty-version-below-1-77-2 for how to update PuttyNG manually.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2271
- https://github.com/mRemoteNG/mRemoteNG/issues/2441
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2458
- https://github.com/mRemoteNG/mRemoteNG/issues/2474

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
