### ISSUE TITLE
execute commands to multiple ssh sessions

### ISSUE THREAD

**Issue by robina80** [mRemoteNG/mRemoteNG#2456]
hi all,

is there a way to execute commands to multiple ssh sessions, this would save a lot of time as i have a few servers when i set them up i need to install cifs mount shares etc 

thanks,
rob

**Comment by JeanPluzo** [comment]
Hi,
yes there is, but mRemoteNG is not made for that.
Instead use ansible, chef or puppet.
There are also other programas/apps with a nice UI which let you control several PC/Servers from your workplace.

Regards,
J.

**Comment by robina80** [comment]
thanks

**Comment by simonai1254** [comment]
Another alternative would be https://multissh.dev/

**Comment by Kvarkas** [comment]
there is ability to run script on session start, but connection still should be initiated, this idea to add this functionality then session joined into group will alow send same comands from one window, but not yet desided how to develop such.
