### ISSUE TITLE
Next Stable Release When? 

### ISSUE THREAD

**Issue by Arkanyus** [mRemoteNG/mRemoteNG#2458]
There doesn't appear to have been a stable release in 4 years, I can see development and other releases are active - excuse the ignorance, but is there anything preventing a stable release?

**Comment by Kvarkas** [comment]
Hello, a lot of changes going on, .net 6, more secure way of handling passwords, other refactorings... but it should be a release this year for sure! :)

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2271
- https://github.com/mRemoteNG/mRemoteNG/issues/2441
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2458
- https://github.com/mRemoteNG/mRemoteNG/issues/2474
