### ISSUE TITLE
The required KB2574819 is already installed on Windows7. Failed on install.

### ISSUE THREAD

**Issue by Femtometer** [mRemoteNG/mRemoteNG#2470]
## Expected Behavior

The required KB2574819 is already installed on Windows7. Failed on install V1.77.

## Current Behavior

![截图_2023-08-03_13-56-53](https://github.com/mRemoteNG/mRemoteNG/assets/5461891/424879d7-bb56-427f-ae30-544e3b752eb7)

## Steps to Reproduce (for bugs)

1. Run msi to install.

## Your Environment

* Version used: V1.77
* Operating System and version (e.g. Windows 10 1709 x64): Windows7 x64

**Comment by Kvarkas** [comment]
hello, windows 7 is legacy already, we dont support it, please update to windows 10 at least

**Comment by Neustradamus** [comment]
I think that with CVEs in current mRemoteNG, a last release build for Windows 7 is needed.
