### ISSUE TITLE
Change theme option is disable?

### ISSUE THREAD

**Issue by heston922** [mRemoteNG/mRemoteNG#2476]
change theme option is disable? 
And the docs is outdated
https://mremoteng.readthedocs.io/en/latest/themes.html
It should be in Tools > Option

When I want to change to dark theme, it is disabled to change theme.
![image](https://github.com/mRemoteNG/mRemoteNG/assets/66485303/a09dc799-c4e3-4d77-b9ba-b97af7d91703)

![image](https://github.com/mRemoteNG/mRemoteNG/assets/66485303/08ea78c0-7f2b-4745-ada2-88b4d73f390b)

Can someone advise? Thanks
## Your Environment

* Version used: 1.76.20
* Operating System and version Windows 11 22H2 x64):

**Comment by simonai1254** [comment]
Regarding the theming: I did not encounter issues with that. Are you using the portable or the full version? 

The update check issue is tackled with #1853

**Comment by heston922** [comment]
> Regarding the theming: I did not encounter issues with that. Are you using the portable or the full version?
> 
> The update check issue is tackled with #1853

Hi Simon

Thanks for reply. I am using the full version. 
I just fresh install on my office laptop, it did the same result.

BR,
Heston

**Comment by Kvarkas** [comment]
I dont support 76.20 due we change codebase and back suprt is complicated, in new release theming is working and in next release where is some plans to chnage it a bit switching to more modern way ;)

**Comment by heston922** [comment]
> I dont support 76.20 due we change codebase and back suprt is complicated, in new release theming is working and in next release where is some plans to chnage it a bit switching to more modern way ;) 

Oh great. Im looking forward to next release. Thanks so much.
