### ISSUE TITLE
mremote dont save config and ask about auto updates every time.

### ISSUE THREAD

**Issue by stufently** [mRemoteNG/mRemoteNG#2478]
Every run mremote I see message about change settings for auto updates.

## Your Environment

* Version used: 1.77.3
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11

![image](https://github.com/mRemoteNG/mRemoteNG/assets/1324096/302c7e6b-8b08-4711-994f-1ad2e344ddda)

**Comment by simonai1254** [comment]
Config Saving is disabled for 1.77.3-NB as pre-release version. See #2245

**Comment by stufently** [comment]
> Config Saving is disabled for 1.77.3-NB as pre-release version. See #2245

How enable it ? Or get new nightbuild ?

**Comment by simonai1254** [comment]
As there is currently no newer nightly build you would need to use 1.77.2-NB to use it with config saving enabled.

**Comment by Kvarkas** [comment]
new nb of mR will allow save settings, curent nb dont as to much disturance to existing users and nobody read a warning what it will damage all saved data... so more simple way was to disable to dont create chaos untill it will be safe to switch to new way of deal with settings.
