### ISSUE TITLE
Blurry texts (not present on standard Remote Desktop Connection)

### ISSUE THREAD

**Issue by EdoardoGalletti** [mRemoteNG/mRemoteNG#2483]
I got a new laptop (different spec wrt the previous ones) and found out that some texts (not all) on remote connections are now blurry. The same texts with a standard windows Remote Desktop Connection are fine and this does not happen with previous laptop. 

Left: mRemoteNG / Right: Remote Desktop Connection

![Picture1](https://github.com/mRemoteNG/mRemoteNG/assets/7505609/6ae2007b-cbe8-478b-94de-e0645c8864f7)

Any config to adjust? 

## Your Environment

* Version used: Happened with both v1.77.1 (Preview) and v1.77.3.1784-NB (Nightly)
* Operating System and version: Windows 10 10.0.19044 Build 19044

**Comment by simonai1254** [comment]
What scaling do you use in Windows? 
And what RDP settings do you have configured for the connection? Have a look at the appearance if it does properly scale/fit.

**Comment by EdoardoGalletti** [comment]
Solved, toggling this bit (pretty self-explanatory tbh :-)) 

![image](https://github.com/mRemoteNG/mRemoteNG/assets/7505609/cf51e99b-a38f-4533-b329-63fb95954dc7)
