### ISSUE TITLE
SSH agent not available for authencation?

### ISSUE THREAD

**Issue by dot-mike** [mRemoteNG/mRemoteNG#2484]
I'm using Yubikey for storing my private SSHkey and I've installed GPG4Win which has native support for SSH authentication (as described here: https://developers.yubico.com/PGP/SSH_authentication/Windows.html).

While authentication works with both Putty + OpenSSH SSH client from Micrososft (https://github.com/PowerShell/openssh-portable) it does not work with Putty for mRemoteNg. I'm unable to SSH to a remote server even tho the ssh key is available in the local SSH agent (check this by executing `ssh-add -l` command in cmd.)

`gpg-agent.conf`:
```
enable-ssh-support
enable-putty-support
enable-extended-key-format
enable-win32-openssh-support
use-standard-socket
```

## Expected Behavior
When I ssh to a server with my yubikey inserted I except authentication to be done with my SSH key stored on the said yubikey.

## Current Behavior
When I try to SSH to a server I get error `No supported authentication methods available (server sent: publickey)`

## Steps to Reproduce (for bugs)
1. Set-up SSH key on yubikey
2. Start `gpg-connect-agent.exe`
3. Ensure that your keys are added the local SSH agent by executing the command `ssh-add -l`
4. Try to ssh to a server using mRemoteNG

## Your Environment
* Version used: 1.76.20-24616
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11 22H2

**Comment by Kvarkas** [comment]
mR use slittly modified version of putty and one that was suplied with 1.76.20 outdated, try to update to newer version manualy and compare: https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html

**Comment by dot-mike** [comment]
Resolved by updating to newer version of PuttyNG. Thanks @Kvarkas !

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523

**Comment by Neustradamus** [comment]
@Kvarkas, @kmscode: The latest mRemoteNG stable build from 2019-04-12 (4 years, 6 months, 4 days), always uses this very old unsecure version of Putty 0.71 (CVEs):
- https://github.com/mRemoteNG/mRemoteNG/issues/1362

Can you update PuttyNG to Putty 0.79 (2023-08-26):
- https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

After it, create a new mRemoteNG stable build with the good PuttyNG version.

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489
- https://github.com/mRemoteNG/mRemoteNG/issues/2484
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2354
- https://github.com/mRemoteNG/mRemoteNG/issues/2246
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2027
- https://github.com/mRemoteNG/mRemoteNG/issues/2012
- https://github.com/mRemoteNG/mRemoteNG/issues/1764
- https://github.com/mRemoteNG/mRemoteNG/issues/1733
- https://github.com/mRemoteNG/mRemoteNG/issues/1523
