### ISSUE TITLE
Fix complier warning: CA2214: Do not call overridable methods in constructors

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#249]
About 20 of these total:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA2214	'ConnectionInfo.ConnectionInfo()' contains a call chain that results in a call to a virtual method defined by the class. Review the following call stack for unintended consequences: 

ConnectionInfo..ctor()
ConnectionInfo.SetTreeDisplayDefaults():Void
AbstractConnectionInfoData.set_Name(String):Void	mRemoteV1	C:\Users\user\Documents\Source\mRemoteNG\mRemoteV1\Connection\ConnectionInfo.cs	54	Active

Reference: https://msdn.microsoft.com/library/ms182331.aspx

**Comment by farosch** [comment]
These errors no longer exist in the current develop branch
