### ISSUE TITLE
[BUG] Connections panel won't screw down.

### ISSUE THREAD

**Issue by q9HugW** [mRemoteNG/mRemoteNG#2490]
## Expected Behavior

**When I screw down it should screw down**

## Current Behavior

**It is not screwing down it automatically pops back to the top**

## Steps to Reproduce (for bugs)

1. **Create tons of connections**
2. **Try to select the connection session at the bottom of the connections panel**

## Your Environment

* Version used: **1.76.20.24615**
* Operating System and version: **Windows 11 Pro 22H2**

**Comment by JeanPluzo** [comment]
Hi,
sorry to correct you, but I think you mean "scroll" not screw.
It could clarify things for other people reading this issue.

Regards,
J.

**Comment by simonai1254** [comment]
I'm also not exactly sure what is meant, but from the behavior I think it's about "Restore Down"

**Comment by q9HugW** [comment]
> Hi, sorry to correct you, but I think you mean "scroll" not screw. It could clarify things for other people reading this issue.
> 
> Regards, J.

Yes, if you drag the bar to the bottom it will jump back to the top.

**Comment by q9HugW** [comment]
> I'm also not exactly sure what is meant, but from the behavior I think it's about "Restore Down"

You can't operate(scroll down with your mouse middle wheel or click it and drag down) the scroll bar to select the session saved at the bottom of "connection panel", it will jump back to the top.

**Comment by Kvarkas** [comment]
Hello, whus its old code base we dont release fixes for this version, please try NB and confirm if issue exist (I could not reproduce it in newer version)

**Comment by q9HugW** [comment]
> Hello, whus its old code base we dont release fixes for this version, please try NB and confirm if issue exist (I could not reproduce it in newer version)

Sorry what is NB? New Branch? But anyway the issue is gone without an update.

**Comment by q9HugW** [comment]
Sorry for late reply, issue is gone magically and never comes back since I posted this. I am closing it.

**Comment by Kvarkas** [comment]
NB - Nightly Build - kind of very early beta version

**Comment by q9HugW** [comment]
Sorry for late reply. I restarted the program and the issue was gone and never appear back again.

**Comment by Kvarkas** [comment]
ok, thanks for info!
