### ISSUE TITLE
SSH session fails to be established in mRemoteNG but works fine in Putty

### ISSUE THREAD

**Issue by uciprian** [mRemoteNG/mRemoteNG#2513]
Failing to establish SSH Session
I have a ssh session configuration in Putty and using this one in mRemoteNG to access one remote server available on VPN in my work environment on protocol SSH version 2

## Expected Behavior
SSH session should be established

## Current Behavior
If I use Putty, exact same Putty key session/key configuration and just enter the host name connection is established
If I use mRemoteNG with same Putty session, same server connection fails to establish, error displayed being: "No supported authentication methods available, server sent public key"

## Context
SSH connection to this server was working for me before using exact same configuration. After a recent upgrade on the remote server from Ubuntu 16/18 to Ubuntu 22, it ceased to be working, it may be related to some changes in protocol settings but I'm not knowledgeable enough on security to tell what it is. 
This is not the single server I have issues with, and actually with every server that has OS Ubuntu upgrade

## Your Environment
* Version used: 1.76.20.24615
* Operating System: Windows 10 Pro 10.0.19045 Build 19045

**Comment by simonai1254** [comment]
Hi 

This is a known issue, see https://mremoteng.readthedocs.io/en/v1.77.3-dev/known_issues.html or #2027 for the solution. 

The underlying issue is being tackled with #2454. 

Have a good day

**Comment by uciprian** [comment]
Thank you for your answer
I want to add that mRemoteNG still works for me for some servers but not the ones incidentally experienced os upgrades.
And I've already tried using a custom putty path option, and it did not solved my issue. The custom putty path was correct because if not, it fails early to connect to any server. My Putty version is 0.79

**Comment by simonai1254** [comment]
The issue you are describing is excactly the behavior as in e.g. #2353 and #2220, which tells you as well to update PuttyNG. Why the custom putty path is not working for you I don't know, but you should replace the executable as described in the KB article referenced before.

**Comment by ChaosCrafter** [comment]
I just tried this and it isn't working.  I updated PuttyNG to version 0.81, but while I can open my session  using Putty, it won't open using PuttyNG.  I've tried both through mRemoteNG, and directly from PuttyNG
I get the same "No supported authentication methods available, server sent public key" message
