### ISSUE TITLE
Developement Dead?

### ISSUE THREAD

**Issue by TuxOps-lab** [mRemoteNG/mRemoteNG#2516]
Hi there,

is the developement dead? Last fully working stable is from 2019.
This version still have some issues, like focus issue. Typing somehting but text is written in another tab etc.
Anyway, there is space to improvement. Just want to know, whats the current developement state?
What are the future plans?

Thx much
Greetings.

**Comment by JeanPluzo** [comment]
Hi,

take a look at this issue: #2474 
You will have nice look about the community's impressions and the developer's response.

Regards,
J.

**Comment by TuxOps-lab** [comment]
Thx very much. That helped a lot :)

**Comment by journeym** [comment]
I think everyone now understands that @Kvarkas appointing as lead dev on this project was a mistake.
He's unable to set realistic goals and keep up with them.
This project is dead as of original dev has been retired.

**Comment by Neustradamus** [comment]
@Uyunifier: I am happy that I am not alone! :)

I have done a ticket 2020-05-25 about it:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765

Latest stable version is 1.76.20 (2019-04-12):
- https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.76.20

And there are several CVEs in the latest current stable version:
- https://github.com/mRemoteNG/mRemoteNG/issues?q=is%3Aissue+cve

Linked to:
- https://github.com/mRemoteNG/mRemoteNG/issues/1765
- https://github.com/mRemoteNG/mRemoteNG/issues/2028
- https://github.com/mRemoteNG/mRemoteNG/issues/2271
- https://github.com/mRemoteNG/mRemoteNG/issues/2441
- https://github.com/mRemoteNG/mRemoteNG/issues/2452
- https://github.com/mRemoteNG/mRemoteNG/issues/2454
- https://github.com/mRemoteNG/mRemoteNG/issues/2458
- https://github.com/mRemoteNG/mRemoteNG/issues/2474
- https://github.com/mRemoteNG/mRemoteNG/issues/2516
- https://github.com/mRemoteNG/mRemoteNG/issues/2610

PuTTY:
- https://github.com/mRemoteNG/mRemoteNG/issues/2489#issuecomment-1765267431

**Comment by journeym** [comment]
**[CENSORED!] Links to external GitHub repositories are not allowed**
