### ISSUE TITLE
Quick question...do panels don't save?

### ISSUE THREAD

**Issue by DigiAngel** [mRemoteNG/mRemoteNG#2517]
Do panels save?  Using the nightly...so far not seeing them restored on exit and restart.  Thank you.

**Comment by simonai1254** [comment]
In 1.77.3-nb nothing saves, this functionality was disabled by the devs as this function is being rewritten alongside other things. If you want a version that writes but includes most of the fixes, you may currently want to look at 1.77.2-nb. 

Regards

**Comment by DigiAngel** [comment]
Perfect...just what I needed thank you much!
