### ISSUE TITLE
Menu or drop-down button for quick tab location/selection

### ISSUE THREAD

**Issue by C4rb0n** [mRemoteNG/mRemoteNG#252]
Could you please add some sort of menu or drop-down button for quickly accessing a tab when there are enough tabs to overflow the tab bar of any given panel?  Scrolling with the left/right arrow buttons gets tedious when there are lots of tabs.

Thanks

**Comment by kmscode** [comment]
Depends on #155

**Comment by kmscode** [comment]
Implemented in develop branch due to changes from #155
