### ISSUE TITLE
Right-Click on connection opens it when "Single Click on connection opens it" is selected in Connection Options

### ISSUE THREAD

**Issue by jupitermangue** [mRemoteNG/mRemoteNG#2521]
One great feature of mRemoteNG is the option to open a connection by just clicking once on the connection without the need to double-click. However, when this feature is enabled in the Connections Options ("Single click on connection opens it"), it does not only affects left-click but also right-click. I think it should not affect right-click.
## Expected Behavior

If "Single click on connection opens it" is enabled in Connection Options, when you right-click a connection it should open only the context menu of that specific connection.
## Current Behavior

If "Single click on connection open it" is enabled in Connection Options, when you right-click a connection it opens the context menu of the connection, but it also opens the connection itself. I think this is not the best approach as you might want to open the connection without credentials for example.
## Possible Solution

Right click on the connection should not open the connection
## Steps to Reproduce (for bugs)

1. Open mRemoteNG and navigate to Tools > Options > Connections.
2. Check the box "Single click on connection opens it".
3. Close and open mRemoteNG again.
4. Right-click on any connection. The context menu of the connection will open, but the connection itself will also open.

## Context

I like the one click to open a connection, but sometimes I want to start a connection without credentials which is done in the context menu of the conecction, but when I right-click the connection it opens, which was not my intention. I just watnted to go to the context menu to start the connection without crednetials.
## Your Environment

* Version used: 1.76.20 (2019-04-12)
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 22H2

**Comment by Kvarkas** [comment]
hello, try new version, this one is not supported for updates anymore
