### ISSUE TITLE
Error when build. I don't know if it's a problem or not...

### ISSUE THREAD

**Issue by xRushG** [mRemoteNG/mRemoteNG#2524]
## Exception
Error when Build:
```Powershell
2>D:\VS : Die Benennung "D:\VS" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
2>ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
2>enthalten), und wiederholen Sie den Vorgang.
2>In Zeile:1 Zeichen:23
2>+ & { $Env:DevEnvDir = (D:\VS Repository\mRemoteNG\Tools ...
2>+                       ~~~~~
2>    + CategoryInfo          : ObjectNotFound: (D:\VS:String) [], CommandNotFoundException
2>    + FullyQualifiedErrorId : CommandNotFoundException
2>
2>Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
2>In Zeile:1 Zeichen:100
2>+ ... evenv.exe); $Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','') ...
2>+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
2>    + FullyQualifiedErrorId : InvokeMethodOnNull
2>
```

Translated into english:

```
D:\VS" is not recognized as the name of a cmdlet, function, script file, or executable program. 
It suggests checking the spelling of the name and verifying if the path is correct. If there are additional 
details or context related to this error, please provide them for a more specific explanation or solution.
In line 1, char 23.
[...]
It is not possible to call a method on an expression that has a null value.
In line:1 char:100
[...]
```

## Current Behavior
When building or rebuilding the project, an error message appears if the project path contains a space. The issue seems to be related to the Pre Build PowerShell Command:

```powershell
echo $(ConfigurationName) > buildenv.tmp
powershell.exe -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command "& { $Env:DevEnvDir = ($(SolutionDir)Tools/find_vstool.ps1 devenv.exe); $Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','')).replace('`',''); $Env:DevEnvDir; if ($Env:APPVEYOR) {&'$(DevEnvDir)TextTransform.exe' -a !!BuildConfiguration!'$(Configuration)' '$(ProjectDir)Properties\AssemblyInfo.tt'} }"
```

## Possible Solution
Replacing it with the following resolves the error:
```powershell
echo $(ConfigurationName) > buildenv.tmp
powershell.exe -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command "& { $Env:DevEnvDir = ('$(SolutionDir)Tools/find_vstool.ps1 devenv.exe'); $Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','')).replace('`',''); $Env:DevEnvDir; if ($Env:APPVEYOR) {&'$(DevEnvDir)TextTransform.exe' -a !!BuildConfiguration!'$(Configuration)' '$(ProjectDir)Properties\AssemblyInfo.tt'} }"
```

I have enclosed the following part in single quotes to force a string in PowerShell.
From ==>
```Powershell
($(SolutionDir)Tools/find_vstool.ps1 devenv.exe);
```
To ==>
```Powershell
('$(SolutionDir)Tools/find_vstool.ps1 devenv.exe');
```

Can someone else confirm this?

## Steps to Reproduce (for bugs)
1. Rebuild/Build

## Why i report
idk... just for my inner MONK

**Comment by Kvarkas** [comment]
hello, could you elaborate a bit more what exactly you try to do and what are you building as all i see its powershell script what I have no idea for what its needed?

**Comment by xRushG** [comment]
Hez Kvarkas,

I'm trying to get deeper into the project and help with solving issues. During my tests, I encountered errors in the console (perhaps only for me, idk...). Therefore, I wanted to take a closer look at them.

The first note in the console was directly related to this error, indicating a problem that, prevents the PowerShell script under tools from being executed. This seems to be something worth investigating; I'm not sure if it could be relevant...

Issue when spaces in path:
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/710080c2-fa2e-4641-9c68-3aeb40f0b94a)

Without spaces in path (seems to work fine):
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/77698388-7ef9-4b37-86c4-a6da982fc89a)

Script that should be runned:
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/f08f9b73-6d21-423f-bc47-8caf4c23f2ca)

To cause this error, the project must be placed in a path with a folder that contains a space (e.g. C:\vs\mRemoteNG w space). A rebuild of the project can then be initiated to evoke the "problem". That's why I tried to adapt the prebuilt command:

![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/8812cb1a-36a5-4fbe-80c6-605f756e12e3)

While I was taking the screenshot I found an issue in my attempt to fix the problem.... Whatever it would be interesting to know whether I have the "problem" alone or whether others can reproduce this.

Issue with my attement to fix is a false slash:
![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/691b0e54-aa0e-4592-a001-dc63892fa536)


If you can replicate this, I would suggest revisiting whether it would be better to adjust the command or if we simply need to omit spaces in the path.

best regards.

**Comment by xRushG** [comment]
Ah, I got it. This issue can be ignored. The fix is only to avoid the error message. Let me explain:

This is the original command mentioned in the previous posts, made a bit more readable:
```Powershell
echo $(ConfigurationName) > buildenv.tmp
powershell.exe -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command "& { 
    # Start a script to find 'devenv.exe' from Visual Studio
    $Env:DevEnvDir = ($(SolutionDir)Tools/find_vstool.ps1 devenv.exe); 
    # If found, remove exe name from the path
    $Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','')).replace('`','');
    # Output to console
    $Env:DevEnvDir; 
    # Set properties and configurations
    if ($Env:APPVEYOR) 
    {
        &'$(DevEnvDir)TextTransform.exe' -a !!BuildConfiguration!'$(Configuration)' '$(ProjectDir)Properties\AssemblyInfo.tt'
    } 
}"

```

Importend: 
The APPVEYOR environment variable is automatically set to True in the context of AppVeyor, a continuous integration and continuous deployment (CI/CD) service, indicating that a build is currently running on AppVeyor.

Some minor adjustments were made to the script to run 'find_vstool.ps1,' and it successfully determined the correct path, showing me the results. Detailed:

```Powershell
# Set the path of 'devenv.exe' using the find_vstool.ps1 script
$Env:DevEnvDir = (. '$(SolutionDir)Tools\find_vstool.ps1' -FileName 'devenv.exe');
# Output the path to the console
$Env:DevEnvDir;   
# Console output: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe

# Remove the 'devenv.exe' from the path
$Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','')).replace('`','');
# Console output: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\

# Output the modified path to the console
$Env:DevEnvDir;
# Check if running on AppVeyor
if ($Env:APPVEYOR) 
{
    # Execute TextTransform.exe with specified arguments
    &'$(DevEnvDir)TextTransform.exe' -a !!BuildConfiguration!'$(Configuration)' '$(ProjectDir)Properties\AssemblyInfo.tt'
}
# If not on AppVeyor, output a message
Else 
{
   # Console output exactly this:
    'AppVeyor is false and nothing happened!'
}

```


The output confirmed that nothing happened:

![image](https://github.com/mRemoteNG/mRemoteNG/assets/145561288/86fdcefe-4c2b-48f7-be33-b838b40d2026)


If you want, I can create a pull request with a command corrections or simply close this case. And please, this is not layer 8. I have explained everything... In this line of the original command, there is a typo with the forward slash: "$Env:DevEnvDir = ($(SolutionDir)Tools/find_vstool.ps1 devenv.exe); " <3


Full command:
```Powershell
echo $(ConfigurationName) > buildenv.tmp
powershell.exe -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command "$Env:DevEnvDir = (. '$(SolutionDir)Tools\find_vstool.ps1' -FileName 'devenv.exe');$Env:DevEnvDir; $Env:DevEnvDir = ($Env:DevEnvDir.Replace('devenv.exe','')).replace('`',''); $Env:DevEnvDir; if ($Env:APPVEYOR) {&'$(DevEnvDir)TextTransform.exe' -a !!BuildConfiguration!'$(Configuration)' '$(ProjectDir)Properties\AssemblyInfo.tt'}"
```

**Comment by Kvarkas** [comment]
just to be sure, are you looking into 1.77.3-dev branch?
if you could make a PR will be happy to approve

**Comment by xRushG** [comment]
I'm surely on version 1.77.3 Dev with my fork:
> This branch is up to date with mRemoteNG/mRemoteNG:v1.77.3-dev.

I will make a PR in a few days. Unfortunately, I'm away this weekend.

**Comment by Kvarkas** [comment]
no rush, and thanks for you help, much appreciated
