### ISSUE TITLE
typo in german translation of error message

### ISSUE THREAD

**Issue by incendor** [mRemoteNG/mRemoteNG#2528]
If an RDP target is unavailable, the error output shows a corresponding error message. The german translation of the error message has a typo in the word "getrennt" which is "getrennnt" instead.

## Expected Behavior
no bug, just a smol typo :)

## Steps to Reproduce
1. Set language to German
2. Try to connect to an RDP target that is offline or doesn't exist
3. Wait for timeout
4. Get error message with typo

## Your Environment
* Version used: 1.77.1.27654

![image](https://github.com/mRemoteNG/mRemoteNG/assets/31634819/5fd832b1-96bf-4b20-9c1a-ca6397346df3)

**Comment by Kvarkas** [comment]
Fix has been apply for 1.77.3-dev
