### ISSUE TITLE
RDP: mstsc.exe works but mRemoteNG doesn't 

### ISSUE THREAD

**Issue by v-bulynkin** [mRemoteNG/mRemoteNG#2535]
I use mRemoteNG (beta 1.77.1.27654) for RDP connections, which stopped working after I had installed the following patches on my Windows 10 22H2 Enterprise (19045.3693):
```
    PC0001        Update           KB5032005     NT AUTHORITY\SYSTEM 08.12.2023 0:00:00
    PC0001        Security Update  KB5032189     NT AUTHORITY\SYSTEM 08.12.2023 0:00:00
    PC0001        Update           KB5031539     NT AUTHORITY\SYSTEM 08.12.2023 0:00:00
    PC0001        Update           KB5032392     NT AUTHORITY\SYSTEM 08.12.2023 0:00:00
```
If I use mstsc.exe, it works normally.

In mRemoteNG logs:
```
    2023-12-11 10:08:50,291 [1] DEBUG - Tab got focused: RDP: server1
    2023-12-11 10:08:50,304 [1] DEBUG - Requesting RDP version: Highest. Using: Rdc9
    2023-12-11 10:08:50,366 [1] INFO  - Setting Console switch for RDC 10.0.19041.
    2023-12-11 10:08:50,371 [1] INFO  - RD Gateway is supported.
    2023-12-11 10:08:52,218 [6] INFO  - Saving connections...
    2023-12-11 10:08:52,722 [6] INFO  - Successfully saved connections
    2023-12-11 10:09:01,464 [1] DEBUG - Panel got focused: General
    2023-12-11 10:09:01,464 [1] DEBUG - Tab got focused: RDP: server1
    2023-12-11 10:09:03,736 [1] WARN  - Protocol Event Disconnected. Host: "server1"; Protocol: "RDP" Message: "This computer can't connect to the remote computer.
    Try connecting again. If the problem continues, contact the owner of the remote computer or your network administrator."
    2023-12-11 10:09:03,791 [1] DEBUG - Panel got focused: General
    2023-12-11 10:09:03,795 [9] INFO  - Connection Event Closed
    2023-12-11 10:09:03,795 [9] INFO  - Connection to server1 via RDP closed by user admin.
```
In Microsoft-Windows-CAPI2 operational log I have errors:
```
    <Result value="800B0109">A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.</Result>
```
In Microsoft-Windows-TerminalServices-ClientActiveXCore there are warnings:
```
    RDPClient_SSL: An error was encountered when transitioning from TsSslStateDisconnecting to TsSslStateDisconnected in response to TsSslEventHandshakeContinueFailed. (Error code: 0x80004005).
    Disconnect RDP ClientActiveX (Reason= 8199)
```

I updated mRemoteNG to a latest nightly build but it didn't help.
I tried to connect to the same server yesterday through VPN from another computer on Windows 11 using mRemoteNG and all was working good.
I suppose it's something related to RDP ActiveX on my client at work but I haven't found any information about "Reason= 8199" and how to fix it.

Could you help me to resolve this?

Why does mstsc.exe work but mRemoteNG doesn't on this particular machine?

**Comment by Kvarkas** [comment]
Try to use 1.77.3 NB

**Comment by v-bulynkin** [comment]
> I updated mRemoteNG to a latest nightly build but it didn't help.

**Comment by Kvarkas** [comment]
Any specific data in the logs?

**Comment by v-bulynkin** [comment]
Logs are the same on all versions as shown above.

**Comment by simonai1254** [comment]
Are you loading a custom mRemoteNG configuration? In mRemoteNG one can specify which version of the RDP library is being used, and if an old one is configured it might fail. 
Can you try to make sure to start mRemoteNG with no configuration file? They usually are located `%APPDATA%\mRemoteNG` and `%LOCALAPPDATA%\mRemoteNG`.

**Comment by v-bulynkin** [comment]
For a long time I used the same configuration which worked until the incident.
When I installed last nightly build it used another path for configuration so there was no configured connections and I added one manually. However, the result was the same.

**Comment by Kvarkas** [comment]
1.77.3 is made exactly for that purpouse, its dont save configuration to dont messing up with existing one, however i cant reproduce same, so thinking its something on yours side, could you try another machine just to be sure if its local for you machine?

**Comment by v-bulynkin** [comment]
Yes, it's local on my machine because on my home computer everything works fine through VPN.
But what is the cause of this problem? Why RDP is working only by mstsc.exe?

**Comment by v-bulynkin** [comment]
I finally found the cause.
It was InfoWatch Device Monitor, the infosec department's spyware.
After removing it, RDP in mRemoteNG started working again.
Sorry for the false alarm.
