### ISSUE TITLE
Immediate crash after startup on W10Pro

### ISSUE THREAD

**Issue by ufotech** [mRemoteNG/mRemoteNG#2543]
On one W10Pro machine mRemoteNG crashes after startup. The main window shows up for a short time.
I run it on multiple machines and there is no such issue on others.
It has worked on this machine for a long time. No changes apart from Windows-Updates.

### Error in eventlog (.NET Runtime):

Anwendung: mRemoteNG.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ArgumentException
   bei System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   bei System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   bei System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
   bei mRemoteNG.App.Update.UpdateFile.FromString(System.String)
   bei mRemoteNG.App.Update.UpdateFile..ctor(System.String)
   bei mRemoteNG.App.Update.UpdateInfo.FromString(System.String)
   bei mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()
   bei System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()

### Application Error:

Name der fehlerhaften Anwendung: mRemoteNG.exe, Version: 1.76.20.24615, Zeitstempel: 0x5cb09552
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.3803, Zeitstempel: 0x4f196cbf
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0013f932
ID des fehlerhaften Prozesses: 0x1adc
Startzeit der fehlerhaften Anwendung: 0x01da3b1dd367154e
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: be771bae-1849-47f9-85de-3a789407ecfa
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

## Expected Behavior
It should start-up and wait for actions to be taken in the GUI.

## Current Behavior
Instead, the main window shows up for a short period and disapears immediately.

### Log entries:

2023-12-30 13:43:46,511 [1] INFO  - mRemoteNG 1.76.20.24615 starting.
2023-12-30 13:43:46,518 [1] INFO  - Command Line: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
2023-12-30 13:43:48,019 [1] INFO  - Microsoft Windows 10 Pro  64-bit
2023-12-30 13:43:48,019 [1] INFO  - Microsoft .NET CLR 4.0.30319.42000
2023-12-30 13:43:48,019 [1] INFO  - System Culture: de-DE/Deutsch (Deutschland)
2023-12-30 13:43:48,020 [1] INFO  - Checking FIPS Policy...
2023-12-30 13:43:48,022 [1] INFO  - Checking Lenovo AutoScroll Utility...
2023-12-30 13:43:48,355 [1] WARN  - Loading External Apps failed: Could not FIND file!
2023-12-30 13:43:49,547 [1] WARN  - XmingPortablePuttySessions.Watcher.StartWatching() failed: 'sessions' does not exist.

This WARN is NOT the issue (it appears on all machines).

## Possible Solution
No idea. Someone to tell me?

## Steps to Reproduce (for bugs)
1. Start mRemoteNG by double-clicking the desktop-icon
2. see it apear and disapear immediately again

## Context
Tried to uninstall and install from scratch, to no avail.

## Your Environment
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Betriebsystemhersteller	Microsoft Corporation
Systemhersteller	LENOVO
Systemmodell	4236AQ5
Systemtyp	x64-basierter PC
Prozessor	Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz, 2501 MHz, 2 Kern(e), 4 logische(r) Prozessor(en)
BIOS-Version/-Datum	LENOVO 83ET69WW (1.39 ), 26.03.2012
SMBIOS-Version	2.6
Version des eingebetteten Controllers	1.18
BIOS-Modus	Vorgängerversion
BaseBoard-Hersteller	LENOVO
BaseBoard-Produkt	4236AQ5
Plattformrolle	Mobil
Sicherer Startzustand	Nicht unterstützt
PCR7-Konfiguration	Bindung nicht möglich
Windows-Verzeichnis	C:\Windows
Systemverzeichnis	C:\Windows\system32
Startgerät	\Device\HarddiskVolume1
Gebietsschema	Deutschland
Hardwareabstraktionsebene	Version = "10.0.19041.3636"
Zeitzone	Mitteleuropäische Zeit

**Comment by KrzesloSzatan** [comment]
Same here, event viewer shows 

> Faulting application name: mRemoteNG.exe, version: 1.76.20.24615, timestamp: 0x5cb09552
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.3803, timestamp: 0x4f196cbf
> Exception code: 0xe0434352
> Error offset: 0x0013f932
> Faulting process ID: 0x20e0
> The time the faulty application started: 0x01da3b222fde68c8
> Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report ID: 2fed8e72-ad8a-4a15-a424-776e3901edc0
> Full name of the causing package:
> Application ID relative to the offending package:

and

> Aplikacja: mRemoteNG.exe
> Wersja architektury: v4.0.30319
> Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
> Informacje o wyjątku: System.ArgumentException
>    w System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
>    w System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
>    w System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
>    w mRemoteNG.App.Update.UpdateFile.FromString(System.String)
>    w mRemoteNG.App.Update.UpdateFile..ctor(System.String)
>    w mRemoteNG.App.Update.UpdateInfo.FromString(System.String)
>    w mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()
>    w System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
>    w System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    w System.Threading.ThreadHelper.ThreadStart()

I have tried to reinstall mremoteNG, installed newest .NET framework - nothing helped.

**Comment by simonai1254** [comment]
See #2541 and #2542, you need to disable the "check for updates on startup"

**Comment by rhodester** [comment]
I preferred to keep my config file settings so I rather did the following.

Open / Edit  (%LOCALAPPDATA%\mRemoteNG\<most recently updated folder>\<mRemoteNG version>\user.config)
Search for "CheckForUpdatesOnStartup" and change to "False".

**Comment by mikbarbarton** [comment]
I had the same problem, removed the "Check for Updates On Startup", and now it works.  Two questions:
1. What is the address used to check for updates?  I may be blocking that address inadvertently, and I would like to whitelist it.
2. Is the site down currently if several people are experiencing this?

**Comment by KrzesloSzatan** [comment]
Unchecking looking for updates did the trick.

**Comment by aisbergde** [comment]
> See #2541 and #2542, you need to disable the "check for updates on startup"

How to disable, if it crashes immediately?

**Comment by ufotech** [comment]
> How to disable, if it crashes immediately? 

Edit this (path may be slightly different)
%localappdata%l\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.76.20.24615\user.config
Search for 'CheckForUpdate' and set 'False'
Start mRemoteNG

**Comment by KrzesloSzatan** [comment]
> > See #2541 and #2542, you need to disable the "check for updates on startup"
> 
> How to disable, if it crashes immediately?

Either change it in the user.config file like someone mentioned above or disable internet (turn off network card for example) and it will open normally.

**Comment by ParAilurus** [comment]
Just hit this this morning as well, same thing in the event viewer. Note if your `user.config` file doesn't have any entry for `CheckForUpdatesOnStartup`, simply just add one:

```
            <setting name="CheckForUpdatesOnStartup" serializeAs="String">
                <value>False</value>
            </setting>
```

order probably doesn't matter, but I stuck mine after `CheckForUpdatesAsked`

**Comment by ufotech** [comment]
This fixed it.
It's probably temporary only as long as the website is under construction.

**Comment by simonai1254** [comment]
> I had the same problem, removed the "Check for Updates On Startup", and now it works. Two questions:
> 
> 1. What is the address used to check for updates?  I may be blocking that address inadvertently, and I would like to whitelist it.
> 2. Is the site down currently if several people are experiencing this?

According to the information I see in #1853 it should be querying GitHub and not the webpage itself, but maybe I've overlooked something...

**Comment by mikbarbarton** [comment]
Thanks Simon.  I wonder if the website IS the issue.  That's why I asked
the question since I could obviously get into Github.  Since a bunch of
people had the same issue at the same time, I don't think it was something
I blocked.  I will check periodically by re-enabling the update check in
the config file and see if it works. 👍

**Comment by simonai1254** [comment]
@mikbarbarton As mRemoteNG is working for users which have mremoteng.org in their hosts-file with 0.0.0.0 (see https://github.com/mRemoteNG/mRemoteNG/issues/2544#issuecomment-1872574279) it clearly is an issue caused by the website itself. 

The question is how we get that fixed for newer builds (aka. proper error handling) and how we can prevent it from happening again (e.g. putting a dummy file on the website with specific content)
