### ISSUE TITLE
Not able to set default inheritance

### ISSUE THREAD

**Issue by Radapompa** [mRemoteNG/mRemoteNG#256]
Bug
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.74  |

Just found out that there actually exist an default inheritance option. After reading the issue where it should be easier to find.
So I tried it out, but it won't work. Whenever I toogle any of the default inheritance options under Connections to True. It will be displayed as False when I check again. The even more strange thing is that in user.config file, all the inheritance options are set to True. But it seems that mRemote is not using them properly.

Thanks for a great work with this project!

**Comment by sparerd** [comment]
This seems to be resolved in v1.75 Beta 1
