### ISSUE TITLE
Always welcome screen

### ISSUE THREAD

**Issue by DocMAX** [mRemoteNG/mRemoteNG#2566]
![grafik](https://github.com/mRemoteNG/mRemoteNG/assets/5351323/428a1403-3c3b-4830-b3ae-34c4aad0f027)

I get this window everytime i start the app. No matter what select.
It seems settings are not saved. I use the portable version.

**Comment by simonai1254** [comment]
What version are you using? 1.77.3-nb does not does not save settings, so that might be one reason as this message indicates that no configuration file was found.

**Comment by Kvarkas** [comment]
That expected, in this nb build saving to settings is disabled to dont create big mess
