### ISSUE TITLE
problems with OTP copy / Paste

### ISSUE THREAD

**Issue by Tomiliy** [mRemoteNG/mRemoteNG#2567]
We start an RDP connection to a server that uses an upstream OTP WebService.
I can enter the OTP token manually, but I cannot paste the previously copied value into MREMOTE using Copy paste

## Steps to Reproduce (for bugs)

1. start an rdp connection to a windows server
2. a previously website with OTP auth ask for token
3. i can't copy paste the token, Only type in is working
4.

## Your Environment

* Version used: 1.77.3
* Operating System and version (e.g. Windows 10 1709 x64):
* Windows Server 2022 as client Windows 10

**Comment by simonai1254** [comment]
Hi

Can you copy paste any other values to the other end? Is the clipboard enabled in the connection settings? 

You also might want to use another version than 1.77.3-nb (e.g., 1.77.2-nb) because this version does not save configuration changes. 

Regards

**Comment by Tomiliy** [comment]
I think the Problem is that Copy Paste globally Not Work in my mremote. Ist
there a configuration change since 1.76? In 1.76 IT works perfekt

Simon Monai ***@***.***> schrieb am Mo. 19. Feb. 2024 um
13:25:

**Comment by simonai1254** [comment]
Not sure if they changed the default settings, but it's a known thing that 1.77.2 and 1.77.3 have the clipboard option disabled by default. You have to enable it manually

You may want to have a look at #1826 and #1968 which cover exactly this topic.

**Comment by Tomiliy** [comment]
OK. How?

Simon Monai ***@***.***> schrieb am Mo. 19. Feb. 2024 um
18:17:

**Comment by simonai1254** [comment]
How what? The RDP settings are in the connection configuration, e.g. see here: https://github.com/mRemoteNG/mRemoteNG/issues/1562#issuecomment-528502502
