### ISSUE TITLE
[DUPLICATE] PuTTY Vulnerability and mRemoteNG

### ISSUE THREAD

**Issue by jamesaepp** [mRemoteNG/mRemoteNG#2581]
## Expected Behavior
N/A

## Current Behavior
N/A

## Possible Solution
Review project code for PuTTY and update to latest software.

## Steps to Reproduce (for bugs)
N/A

## Context
[This](https://www.chiark.greenend.org.uk/%7Esgtatham/putty/wishlist/vuln-p521-bias.html) PuTTY vulnerability was released recently.

I know that mRemoteNG has some integrations with PuTTY but I'm not sure to what extent, if it has bundled software, or other similar considerations. Would be good if an experienced volunteer could review this and come up with a plan on how to remediate.

## Your Environment
N/A

**Comment by simonai1254** [comment]
See #2489

**Comment by simonai1254** [comment]
And I guess unlike #2580 one may leave this issue open until it's fixed so people like you see that this issue was already filed.

**Comment by jamesaepp** [comment]
My bad, I didn't search thoroughly. We can close this as duplicate.
