### ISSUE TITLE
Text is blurred on SSH terminal

### ISSUE THREAD

**Issue by bkiziuk** [mRemoteNG/mRemoteNG#2584]
I've been working on PuTTY for years. 
I'm trying to move to mRemoteNG and the thing that annoys me is a bit blurry SSH window font.

<img width="337" alt="mRemoteNG_1-76-20-24669_blured" src="https://github.com/mRemoteNG/mRemoteNG/assets/32905985/98345363-1c22-4e36-83be-db66a1795fc5">

The left column is from mRemoteNG, the right is from PuTTY.

## Expected Behavior
The console font is as sharp as on PuTTY

## Current Behavior
The console font is blurry

## Steps to Reproduce (for bugs)
Run the terminal window next to the PuTTY terminal.

## Context
The text is much harder to read if the eye is accustomed to the sharp font.

## Your Environment
Windows 10 Pro 22H2 19045.4291
External monitor, 2560x1440 (Native resolution), 125% size.
mRemoteNG version: 1.76.20.24669.
PuTTY version: 0.75

**Comment by Kvarkas** [comment]
what known issue, related to how windows render fonts on high dpi screens, but please update to new puttyng:  https://github.com/mRemoteNG/PuTTYNG/releases
we don't support old version (in terms of modifications and patching) current version is 1.77.3 nb what is still in development with many new features and fixes how ever its not production ready yet, but moving on, at same time it still on .NET 6 what also have issues with fonts readability but Microsoft promised fix that on .NET 8 where will be migrating on 1.77.4 version so far could recommend only to set 100% size to avoid such.
