### ISSUE TITLE
Can't Full Screen

### ISSUE THREAD

**Issue by YaMang0w0** [mRemoteNG/mRemoteNG#2586]
## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

When I press F11 to full screen or cancel full screen, the rdp connection is disconnected. Reconnecting to the session. After this occurs, there is no reduction or enlargement.

Also, i cannot go to full screen by pressing the f11 key.

This also happens when you try to change the program ratio. Is there a solution?
## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64):  Windows 11 Pro 23H2 x64

**Comment by Kvarkas** [comment]
This version is not supported anymore, for testing 1.77.3 - nb
