### ISSUE TITLE
list declaration as [] 

### ISSUE THREAD

**Issue by Bjelko** [mRemoteNG/mRemoteNG#2594]
Dear,
How to compile?

```
 private void SetNewOpenConnectionList()
        {
            OpenConnections = [];
            OpenConnections.CollectionChanged += (sender, args) => RaisePropertyChangedEvent(this, new PropertyChangedEventArgs("OpenConnections"));
        }
```

[] is used in Python not in C#
there is about 100 occurences of such list definitions in code

**Comment by xRushG** [comment]
Hey @Bjelko,

you are correct. In C#, "[ ]" is not the correct or common syntax for declaring OpenConnections = [ ]. Instead, the NEW keyword should be used. However, i think there are actually no issues with compilation at this point.  We noticed your feedback and will work on it.

First of all, please update Visual Studio and its dependencies as described here:
[mRemoteNG Development Environment Setup](https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment).

If errors continue to occur after updating, please describe them more detailed:
- VS version
- Step-by-step description
- Screenshots

If you need further assistance, feel free to ask.

kind regards

**Comment by Kvarkas** [comment]
Hello, thanks, new version of Visual Studio 17.2 sugest this change - from my point of view it's better (or let say more common for me) so I let it to do it :) btw new version with Copilot enabled also suggesting this change. So please update yours studio and it should be ok!
