### ISSUE TITLE
Crash loading connection-file with encryption

### ISSUE THREAD

**Issue by theovds** [mRemoteNG/mRemoteNG#260]
I've updated to beta-1, but I get an 'object reference is not set...etc' while loading the connection-file. WHen I go back to the latest alpha-versions there is no problem.

I reinstalled Alpha-3 and unchecked the box for 'completely encrypt connection file'. Then I did again an upgrade to Beta-1 succesfully!

![2016-11-18 09_06_50-mremoteng](https://cloud.githubusercontent.com/assets/23518492/20439675/00a90904-adbd-11e6-97b6-aae4a84f11b4.png)

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 1
[mRemoteNG.zip](https://github.com/mRemoteNG/mRemoteNG/files/600551/mRemoteNG.zip)
  |

**Comment by theovds** [comment]
See the attached mRemoteNG.zip for the log-file.

**Comment by sparerd** [comment]
Fix will be available in v1.75 beta2
