### ISSUE TITLE
Remote resolution and Local resolution

### ISSUE THREAD

**Issue by yokotsumo** [mRemoteNG/mRemoteNG#2600]
My remote RDP servers have a FullHD resolution while my Local resolution is QHD. However, I can not fit the remote screen in my local screen without activating Smartsize. I have tried all the possible resolution in the config panel, but without effect. Most of the time it is not annoying, but with specific servers, the scaling is very bad and I struggle reading texts on my remote servers.

## Expected Behavior

FullHD remote server display fit in to QHD local server screen

## Current Behavior

Remote server screen seems upscaled and do not fit into screens with far larger resolution

## Possible Solution

no idea

## Steps to Reproduce (for bugs)

1. Connect to the server
2. Activate Full screen
3. Deactivate Full screen
4. Activate Smartsize

## Context

I can not see the full screen of the remote server while its resolution is far lower. Activating Smartsize sometimes affects the quality of the displayed text.

## Your Environment

* Version used: 1.76.19
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11 x64 22631.3593

**Comment by Kvarkas** [comment]
where is limitation from technology pack we are using in that old version. In nevest version that will be addressed better by microsoft .net library
