### ISSUE TITLE
Password with char '!' not correct stored

### ISSUE THREAD

**Issue by andrek71** [mRemoteNG/mRemoteNG#2603]
Password with char '!' not correct stored

## Expected Behavior
Password correct stored

## Current Behavior
As the password revealer shows, the password is wrongly stored when there is a "!" at the password
## Steps to Reproduce (for bugs)

1. enter password with a "!" ...for example 1234!
2. check password with the password revealer (/k echo "%password%")- it will be 1234^! displayed

## Context
Every time when i want to use a WinSCP-connection, i am prompted for the password (because the PW is not correct)

## Your Environment

* Version used: 1.76.20
* Operating System and version: Windows Server 2022 Standard

**Comment by kees-z** [comment]
Use `%!password%` instead of `%password%` to avoid argument splitting and shell metacharacter escaping, see [documentation](https://mremoteng.readthedocs.io/en/v1.77.3-dev/user_interface/external_tools.html#shell-metacharacter-escaping).

**Comment by andrek71** [comment]
perfect, thank you very much :-) !!
