### ISSUE TITLE
Toolbars position resets after restart

### ISSUE THREAD

**Issue by SkyREgit** [mRemoteNG/mRemoteNG#2604]
Using Tab groups and to have bigger RDP session screen space placing Menu & Toolbar in one row.
But that not saved after mRemote restart.

## Expected Behavior
Menu, "Quick Connect", "Multi SSH" toolbars are in one row after start.
For sure configurable.

## Current Behavior
After starting mRemoteNG its Menu, Toolbars in different rows

## Steps to Reproduce (for bugs)

1. Place Menu, "Quick Connect", "Multi SSH" toolbars in one row
2. Save settings
3. Restart mRemoteNG
4. Menu, Toolbars are in different rows

## Context
To have bigger RDP session screen space

## Your Environment

* Version used: 20230303-NB-v1.77.3
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10/11

**Comment by Kvarkas** [comment]
Sorry but curent NB version have disabled option to save any changes due they are unsafe for production environments and users are try to run it without reading warning :) will be enabled in feature release.
