### ISSUE TITLE
Feature request: Preserve hostnames & IPs in Quick Connect list during restart of mRemoteNG

### ISSUE THREAD

**Issue by SkyREgit** [mRemoteNG/mRemoteNG#2605]
List of hostnames & IPs not preserved after mRemoteNG closure

## Expected Behavior
Preserve content of list in Quick connect toolbar.

## Current Behavior
Content of list in Quick connect toolbar not preserved.

## Steps to Reproduce (for bugs)

1. Use quick connect toolbar to connect to some servers
2. Restart mRemoteNG
3. List is empty in Quick Connect toolbar

## Context
Extend usability.
Not always there's a need to add new host in connections permanently.
Need connect to side IP/hostname of host that you had already connected some time ago.

## Your Environment

* Version used: 20230303-NB-v1.77.3
* Operating System and version (e.g. Windows 10 1709 x64): windows 10/11

**Comment by Kvarkas** [comment]
Current dev version have disabled save any auto changes for a purpose. Will be enabled in next nb version potentially.
