### ISSUE TITLE
Disable Pop Up Automatic Update Settings first start does't work

### ISSUE THREAD

**Issue by captaineramirez** [mRemoteNG/mRemoteNG#2607]
Hello,

As #1703 issue I can't disable pop up Automatic Update Settings first start.

I've followed the farosch's solution with **mRemoteNG.exe.config** file with both values **CheckForUpdatesOnStartup** and **CheckForUpdatesAsked** configured with **False**.

[config file content located under install directory.txt](https://github.com/user-attachments/files/15936102/config.file.content.located.under.install.directory.txt)

Silent install command used : **MsiExec.exe /i mRemoteNG-Installer-1.76.20.24615.msi /qn**

Powershell copy config file command used : **Copy-Item -Path "$DirFiles\mRemoteNG.exe.config" -Destination "C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe.config" -Force**

Silent Install works and when I launch mRemoteNG I've got the pop up Automatic Update Settings first start :
![mRemoteNg pop up Automatic Update Settings first start](https://github.com/mRemoteNG/mRemoteNG/assets/37227852/4019546a-7312-4913-af13-8fdd953d5ca1)

When I go to the "Tools" menu and then to "Options", then I click on "Updates" and "Checking for updates on startup" is unchecked :
![mRemoteNg Checking for updates on startup disable](https://github.com/mRemoteNG/mRemoteNG/assets/37227852/b60ca885-1ab8-4827-a8b4-4863363e1928)

When I open the file located under : "C:\Users\username\AppData\Local\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.76.20.24615\user.config" I've got the config below :

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <mRemoteNG.Settings>
            <setting name="MainFormLocation" serializeAs="String">
                <value>-8, -8</value>
            </setting>
            <setting name="MainFormSize" serializeAs="String">
                <value>1552, 936</value>
            </setting>
            <setting name="MainFormState" serializeAs="String">
                <value>Maximized</value>
            </setting>
            <setting name="MainFormKiosk" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="DoUpgrade" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="LoadConsFromCustomLocation" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="FirstStart" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ResetPanels" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="NoReconnect" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ExtAppsTBVisible" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ExtAppsTBShowText" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="ExtAppsTBLocation" serializeAs="String">
                <value>3, 25</value>
            </setting>
            <setting name="ExtAppsTBParentDock" serializeAs="String">
                <value>Bottom</value>
            </setting>
            <setting name="QuickyTBVisible" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="QuickyTBLocation" serializeAs="String">
                <value>3, 24</value>
            </setting>
            <setting name="QuickyTBParentDock" serializeAs="String">
                <value>Top</value>
            </setting>
            <setting name="ResetToolbars" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="UpdatePending" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ThemeName" serializeAs="String">
                <value>vs2015light</value>
            </setting>
            <setting name="PuttySavedSessionsPanel" serializeAs="String">
                <value>Général</value>
            </setting>
            <setting name="EncryptionEngine" serializeAs="String">
                <value>AES</value>
            </setting>
            <setting name="EncryptionBlockCipherMode" serializeAs="String">
                <value>GCM</value>
            </setting>
            <setting name="LogFilePath" serializeAs="String">
                <value>C:\Users\username\AppData\Roaming\mRemoteNG\mRemoteNG.log</value>
            </setting>
            <setting name="ThemingActive" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="MultiSshToolbarLocation" serializeAs="String">
                <value>3, 0</value>
            </setting>
            <setting name="MultiSshToolbarParentDock" serializeAs="String">
                <value>Top</value>
            </setting>
            <setting name="MultiSshToolbarVisible" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="MainFormRestoreSize" serializeAs="String">
                <value>1145, 610</value>
            </setting>
            <setting name="MainFormRestoreLocation" serializeAs="String">
                <value>78, 78</value>
            </setting>
        </mRemoteNG.Settings>
    </userSettings>
</configuration>`

mRemoteNG installed version : **1.76.20.24615**
**Windows 10 22H2**

Thank you in advance for your help.

Best regards.

**Comment by xRushG** [comment]
Hey,

Could you set up some registry settings in HKLM? I am working on making all options configurable in the registry. Currently, update and credential settings can be configured via the registry.

For your current request, you can set this under:

**HKEY_LOCAL_MACHINE\SOFTWARE\mRemoteNG\Updates**

1. **Disable all update checks (Disables the promt too)**
   - Type: REG_SZ
   - Name: `AllowCheckForUpdates`
   - Set Value: `false`
   - Default: `true`

2. **Allow or disallow automatic search for updates**
   - Type: REG_SZ
   - Name: `AllowCheckForUpdatesAutomatical`
   - Set Value: `false`
   - Default: `true`

3. **Allow or disallow manual search for updates**
   - Type: REG_SZ
   - Name: `AllowCheckForUpdatesManual`
   - Set Value: `false`
   - Default: `true`

4. **Control whether a prompt for checking the updates preferences is displayed at startup**
   - Type: REG_SZ
   - Name: `AllowPromptForUpdatesPreference`
   - Set Value: `false`
   - Default: `true`


If you choose option one, all update configurations are disabled. 
You can configure options 2, 3, and 4 as desired.
If you only want to disable the popup use option 4: 'AllowPromptForUpdatesPreference'

If you need further assistance, please let me know.

**Comment by captaineramirez** [comment]
Hello thank you for your quick reply,

I've created the registry settings in HKLM but it doesn't work :
![image](https://github.com/mRemoteNG/mRemoteNG/assets/37227852/1199be86-3e88-48e8-920b-faebc0f5c50a)

My mRemoteNG installation is under Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node but I've tried also to create the registry settings under Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\mRemoteNG but same issue :
![image](https://github.com/mRemoteNG/mRemoteNG/assets/37227852/56a7a55d-f6af-4bf8-9a81-32d2cff897f7)

![image](https://github.com/mRemoteNG/mRemoteNG/assets/37227852/336fd30f-16d7-41db-93bc-0af3c0a93941)

I've tried also to change Type by REG_DWORKD with value 1 but it doesn't work.

Thank you in advance for your help.

Best regards.

**Comment by xRushG** [comment]
Oh, I just noticed that you're using the latest Nightly build.

Is it an option for you to download the current source code and compile the MSI installer yourself? The changes have only been included since the beginning of the year. I use as well in our environment at work.

It's generally not recommended to use development software, of course. However, I can't assist you with this issue otherwise.
Otherwise, as fixing it will only be available in the development state until the next nightly build release.

Sorry.

And to your idea of using DWORD: "I've also tried changing Type to REG_DWORD with value 1, but it doesn't work." When you use DWORD (not documented by me, but an option), you need "0" to disable and "1" to enable. But I think using a string with "true/false" is a better choice if you can use registry settings.

King regards.

**Comment by captaineramirez** [comment]
Good morning,

Thank you for your reply.

Indeed, in the type of environment where I work it is complicated to use a version in development.

I will wait for the next versions no worries and thank you again for your help.

Best regards.

**Comment by Kvarkas** [comment]
As was mentioned due some complexity of changes what are going into dev version it strictly dont recommended to use in production environments and to avoid any mess it could create saving is disabled for a purpose.
