### ISSUE TITLE
No clipboard redirect option on RDP connection

### ISSUE THREAD

**Issue by Quixus** [mRemoteNG/mRemoteNG#2609]
The option to redirect the clipboard seems to be missing. It used to be possible to copytext etc. from the remote computer and paste it on the local machine

## Expected Behavior
I expected the option to redirect the clipboard to be in the connection properties. 
When connected to the remote machine, CTRL+C should copy data and CTRL+V on the local machine should paste it there.
## Current Behavior
You cannot select whether the clipboard should be redirected or not in the connection properties.
![Screenshot 2024-06-28 070921](https://github.com/mRemoteNG/mRemoteNG/assets/29638423/81dcc604-5823-4e99-8899-54d7872f0168)

Paste on the local machine does not paste data copied from the remote machine.
  
## Possible Solution
Add the option and functionality back.
## Steps to Reproduce (for bugs)
See above

## Your Environment

* Version used: 1.76.20.24615
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 22H2,OS build 19045.4529

**Comment by Kvarkas** [comment]
thanks however this version is not supported anymore and no updates  are planed, in newer version where is already ability to redirect clipboard.

**Comment by Quixus** [comment]
In that case I found a separate issue, but I am not sure if you can address it. winget lists the version above as the most recent. 

BTW which versions are still supported? Is there a stable version that is in support?

**Comment by Kvarkas** [comment]
if you not a corporate user then check this latest (I call them night builds) version: https://github.com/mRemoteNG/mRemoteNG/releases/tag/2023.03.03-v1.77.3-nb
it has disabled saving due refactoring on going but hope soon will release update version that have high chances become release candidate.
