### ISSUE TITLE
Double clicking on a folder in the treeview doesn't work in beta-1

### ISSUE THREAD

**Issue by theovds** [mRemoteNG/mRemoteNG#261]
I've updated to beta-1. 

Double clicking on a folder in the treeview doesn't work anymore. I've to click the '+' in front of the folder to open the folder.
This was not an issue in alpha-3.

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 1  |

**Comment by sparerd** [comment]
Re-added feature, this was an oversight when rewriting the connection tree. Will be present in 1.75 beta2
