### ISSUE TITLE
Auto scroll issue with 1.76.20

### ISSUE THREAD

**Issue by smeyernyc** [mRemoteNG/mRemoteNG#2613]
When opening up an SSH session, the session extends below the visual space of the tab. Interestingly, if you go to "about" and then close that tab, the problem resolves for the rest of the session. Windows 11 23H2 confirmed on multiple computers.

![Screenshot 2024-07-08 105545](https://github.com/mRemoteNG/mRemoteNG/assets/29100931/fa5b0698-1148-420e-9e7e-124900c61480)
![Screenshot 2024-07-08 105622](https://github.com/mRemoteNG/mRemoteNG/assets/29100931/9eb216cd-0362-40eb-a7fc-dffa6bf08626)

**Comment by Kvarkas** [comment]
Unfortunately old version is not supported any more and no fix release is planned, for non work environment please check last NB version or wait for release release candidate (soon)
