### ISSUE TITLE
Can't turn off windows bell 

### ISSUE THREAD

**Issue by sanddastan** [mRemoteNG/mRemoteNG#2615]
No option to disable windows sound effect

## Expected Behavior
When typing in the terminal, for example, pressing tab, a bell sound effect from the Windows suite of sounds plays.  There should be a setting in the options to turn this off.

## Current Behavior
There is no way of turning this off 

## Possible Solution
Add option to turn off the sound

## Steps to Reproduce (for bugs)
Type in the terminal and press tab repeatedly 

## Context
It is annoying to hear the bell throughout navigating inside the terminal

## Your Environment
Windows 11 build 22621.3737

**Comment by Kvarkas** [comment]
hi, what version you are referring?

**Comment by simonai1254** [comment]
See #2283

**Comment by Kvarkas** [comment]
try as follow, open a session, call for settings, set bell off (that putty setting, not our, so what should be done by user on his end)
![image](https://github.com/user-attachments/assets/6e269326-fcf6-49b2-b1dc-11ae2f5dfdcf)

![image](https://github.com/user-attachments/assets/79d82a08-3c4a-4d25-b04b-fc520bd20a8e)

hope that helps

**Comment by Kvarkas** [comment]
as no response from @sanddastan I consider we answered this and now could close
