### ISSUE TITLE
Do we have a telnet auto logon feature?

### ISSUE THREAD

**Issue by AmerDwight** [mRemoteNG/mRemoteNG#2641]
Do we have a telnet auto logon feature?

## Expected Behavior
Let user to fill-in account & password in telnet protocol
Auto logon on connect

## Current Behavior
account & password column is gone when choosing  telnet protocol

Is this feature a built-in function in mRemoteNG?
I didn't see setup or guild about this.

I will be so grateful, if someone can point me out. 

Environment
* Version used: mRemoteNG-Portable-1.76.20.24669
* Operating System and version ( Windows 10 17763 x64):

**Comment by simonai1254** [comment]
In General: Is Telnet really necessary for this use case? Is there no way to use SSH with Keys?

Independently of this, mremoteng is using putty as telnet backend. If you add another external tool (e.g. KiTTY) aparently you can pass the parameter.
You could also use the "Copy Password" external tool as described in other issues, to simplify copy & paste, which is the method I mosly use for the few connections I actually store the credentials in mRemoteNG. Anyhow, with the current way mRemoteNG stores the credential, we discourage to store any secrets within the mRemoteNG configuration.

**Comment by AmerDwight** [comment]
Using SSH instead is kind of a solution, in general, that is a good choice fine enough.
But in my case, for some magical reasons, it may not work, that's why I'm still trapped in Telnet.

I greatly appreciate your guidance; using an external tool seems to be a satisfactory solution for me!
