### ISSUE TITLE
When will a new version be released?

### ISSUE THREAD

**Issue by JustBeta** [mRemoteNG/mRemoteNG#2646]
Hello world

no new update for mRemoteNG since 2019, mRemoteNG is a closed project?

I'm really sad.

JoBar.

**Comment by JustBeta** [comment]
At the moment, I'm using 1.77.3-dev. 
I can't find a new stable or preview update.

Where is the new version?
Give me the link for the update please.

**Comment by Kvarkas** [comment]
its still in development and not stable, curent version you could pull and compile from the git
