### ISSUE TITLE
Quick connect is having some problem, some times we are not able to copy the hostname

### ISSUE THREAD

**Issue by saiprathapreddy** [mRemoteNG/mRemoteNG#268]
||| 
i have opened one session and i want to open another session with different IP, i am trying to paste it into Quick connect but not able to do some times.
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
What session types are you using? RDP? SSH?

**Comment by saiprathapreddy** [comment]
Thanks for the replay.
I am using ssh2

**Comment by LIyoai** [comment]
Same issue here. When I open a ssh session the quick connection field is somehow locked.
When I switch to a rdp tab it works again.

**Comment by Elokku** [comment]
On Windows 10 x64 I have the same problem (issue #402). Only applies when having one ssh conenction opened. Problem started from 1.74 version and is still present in 1.75 RC1. 

It is REALLY annoying - I would appreciate if you can fix this :)

**Comment by Alibaskins** [comment]
Hi,

Same problem here. 
We would appreciate if you can fix this too :)

**Comment by sparerd** [comment]
Hey all, doing a bit of ticket cleanup and noticed this one is a duplicate of #176. I'm going to close this ticket, so please follow #176 for further updates.
