### ISSUE TITLE
Update DockPanelSuite

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#269]
Currently using 2.16. 

[3.0.4](https://github.com/dockpanelsuite/dockpanelsuite/releases/tag/Release_3.0.4) was released in Jan 2018.

Not sure if this is still an issue:
May need to open an issue with DPS since there is some thicker border around both RightToolStripPanel and BottomToolStripPanel in frmMain when using 2.11 (no other code changed).

**Comment by jotatsu** [comment]
DockPanelSuite  was updated to 2.16 with the introduction of the new themes.  Please close this one.

**Comment by kmscode** [comment]
Updated description for latest DPS release...
