### ISSUE TITLE
Install package is not using the last installation path

### ISSUE THREAD

**Issue by patboy29** [mRemoteNG/mRemoteNG#271]
Hi
The install package is not using the last installation path. It want to install in the default directory C:\Program files (x86)\mRemoteNG even if the previous installed version is in another drive or folder.

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74 and 1.75 Beta 1  |

**Comment by sparerd** [comment]
Resolved - this will be included in the 1.75 beta 2 release. Please note that it requires registry entries to be present to work. You will not see a difference in functionality when upgrading from <= 1.75 beta 1. When upgrading from 1.75 beta 2 to newer versions, the installer will remember the previous install path.
