### ISSUE TITLE
CTRL+D no longer working in Beta-1

### ISSUE THREAD

**Issue by theovds** [mRemoteNG/mRemoteNG#276]
The hotkey CTRL-D for duplicating a connection is no longer working in Beta 1. 

It is possible with the mouse, but not with the keyboard.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 beta 1  |

**Comment by sparerd** [comment]
Another oversight when we rebuilt the connection tree. I'll re-add that hotkey

**Comment by theovds** [comment]
I noticed that also F2 (rename) was no longer working.
After I restared mRemoteNG everything is working as aspected. 
This is strange. Do you need the logs?

**Comment by sparerd** [comment]
Hmm odd - yes please the logs may help.

**Comment by theovds** [comment]
[mRemoteNG.zip](https://github.com/mRemoteNG/mRemoteNG/files/619332/mRemoteNG.zip)

**Comment by sparerd** [comment]
Not able to replicate the issue and the log file didn't help much. Are you able to consistently replicate, or was it just that one time?

**Comment by theovds** [comment]
I'm also not able to replicate the issue. Seems to be a onetime issue.
