### ISSUE TITLE
BUG: HTTP links. Upgrade http links to https.

### ISSUE THREAD

**Issue by ypid** [mRemoteNG/mRemoteNG#286]
GitHub automatically redirects to HTTPS and they even have HSTS deployed, just no preloading.

Can you check http links and upgrade them to https?

Places I noticed:

* Repo description: https://github.com/mRemoteNG/mRemoteNG
* Repo description: https://github.com/mRemoteNG
* README: http://waffle.io/mRemoteNG/mRemoteNG
* http://forum.mremoteng.org/ (https needs to be fully setup first before switching)

**Comment by sparerd** [comment]
Yea, we can edit them to be https. Though we have https rewrites turned on for (nearly) all subdomains anyways.

The forum has been a bit of a thorn and will take a bit more work to update. We need to migrate it to a new hosting service first.

**Comment by kmscode** [comment]
Fixed the waffle.io link in the readme.

Opened #288 for the forum since that will be slightly longer term. 

@sparerd You'll have to do the repo descriptions so we can close out this issue.

**Comment by sparerd** [comment]
ack - will do

**Comment by sparerd** [comment]
Resolved the repo description links. Closing issue as resolved, with the caveat that we will be working on the forum via #288

**Comment by ypid** [comment]
Thanks very much for fixing this so quickly! Keep up the good work.
