### ISSUE TITLE
Make forum and links to it https

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#288]
Make forum and links to it https

**Comment by sparerd** [comment]
We need to get the forum onto a different hosting solution. It is (i think) the last thing being hosted on rmcardle's account. Would be good to get that moved somewhere else by end of 2016.

Need:
1. Set up a phpBB app
2. Transfer DB (mysql) from old instance to the new one
3. Verify (=hope) everything worked

**Comment by kmscode** [comment]
They aren't that active... Plus requires an additional account that people might forget about... kill the forum and redirect to reddit?

**Comment by kmscode** [comment]
Or... https://www.prophpbb.com/

**Comment by sparerd** [comment]
prophpbb looks good. We'll just have to ensure we can upload our current DB

**Comment by theWoodman** [comment]
@sparerd I don't get why you as such a small project should spend that many hours on hosting and operating a forum platform that basically is just a forum. 
IMO i would rather see you spend hours on developing new features. If we need a forum like place, lets use well known foras like Reddit or Slack or what ever suites us fine.

I am sure that this projects audience is well known in how to use other platforms than phpbb or similar platforms.

**Comment by jcefoli** [comment]
That is a very good suggestion. A subreddit would be completely decent to use as forums, and you wouldn't need to worry about maintaining a PaaS forum hosting solution or VPS (patching, updates etc.)

**Comment by kmscode** [comment]
@sparerd The community has spoken! :wink:

We could have the subreddit setup today and DNS redirected fairly soon after.

Migrating the old phpbb for historical purposes when they aren't super active and then maintaining them (even though prophpbb.com should make that easier for us) doesn't feel like the best use of our time to me either...

**Comment by sparerd** [comment]
I worry a little bit about losing obscure info that has built up on the forums over time. (It's been a prominent hit on Google search for some errors.) Though on the other hand, if the info is important enough to keep it should be documented on the wiki rather than buried in the forums.

**Comment by sparerd** [comment]
I'm a bit torn over this. But if we give the community-at-large enough forewarning, I'd be ok with it. Would definitely be nice to have one less thing to secure.

**Comment by kmscode** [comment]
Agreed... Maybe:

1. setup the subreddit and link to that
2. post announcement that reddit is the place new goto community
3. Set the forum to read-only 
4. migrate any necessary info to the wiki
5. shut down in 3-6 months

**Comment by sparerd** [comment]
I'm good with that. Timeline for shutdown is up for debate. I may have to talk with Riley about forum pricing. We might be able to work it out with him to sublease the current forum hosting and re-imburse him from the org funds. That would at least get us out of migrating the forum.

**Comment by kmscode** [comment]
I'm fine with 3-6 days... 😄 I can't imagine that there is that much applicable gold in there at this point...

**Comment by sparerd** [comment]
I think 1 month would be sufficient (a week or two might even be plenty). I just don't want people to be blindsided by it.

**Comment by Benchwork** [comment]
if you wanted. once the DB is offline, I could load a copy of it and start
consolidating information, pruning threads and moving it over to the
wiki... it will take a while. but at least I can offer this as a
contribution to the community.

**Comment by sparerd** [comment]
@Benchwork thanks for the offer! We could probably start that now. Just skim through the support sub-forum and look for common/recurring questions or anything that seems useful. Compile a document and we can figure out which sections of the wiki to add it to. Some might be more Q&A/known issues, some might be worth putting in the user manual (we do need help updating and filling out the user manual!)

**Comment by sparerd** [comment]
Proposed timeline (comments requested):
- Post a community notice of our intention with a timeline of events. Deadline: today
- Get the reddit community up and running. We already have the name saved. Just need to make it public and set owners/mods/sidebar info. Deadline: end of the weekend (Dec. 4)
- Update website with links to Reddit community.
- Turn on read-only mode for the phpBB forum sometime next week (Dec 9th?).
- Turn off the forum and redirect DNS entries to reddit community. Deadline: Dec. 31st

I will take a backup of the DB before deleting things, just in case we need it again.

**Comment by kmscode** [comment]
@sparerd Sounds good to me!

**Comment by sparerd** [comment]
I've created #293 for compiling useful info from the wiki. Any help with it is much appreciated!

**Comment by sparerd** [comment]
Notice of intention posted to the forums.

**Comment by sparerd** [comment]
Forum is now read-only. It will remain operational for a little while. We need to put a link to the reddit community on the website.

**Comment by sparerd** [comment]
Forum is still online but all activity is now on Reddit. I've created #606 to track final decomm tasks. Closing this issue
