### ISSUE TITLE
External tools not working

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#291]
External Tools are note working since 1.75.
When I right click a host the External Tools is a button not a list.
![image](https://cloud.githubusercontent.com/assets/6205123/20827188/9650d0fa-b870-11e6-82cf-430b16c85271.png)

When I go to the menu View -> External Tools Toolbar I just get an empty line at the bottom
![image](https://cloud.githubusercontent.com/assets/6205123/20827163/666c61ec-b870-11e6-9919-12698d547660.png)

I deleted extApps.xml which I had copied from 1.74 and restarted. A new one got created but still the same issue.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 beta 3  |

**Comment by sparerd** [comment]
I'm not able to replicate the issue. Is this the portable or installed version?

**Comment by kmscode** [comment]
Related to #236 

I was not able to replicate this either.

Looking to add some messages into that area of code and running into a lot of funkyness (nullref's when clearly there are no nullrefs...).

**Comment by LIyoai** [comment]
I'm using the portable version.

**Comment by kmscode** [comment]
[1.75 RC1](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75RC1) has been released. Please download and test if this problem has been resolved. If not, please post the mremoteng.log.

**Comment by LIyoai** [comment]
Started 1.75 RC1 with a blank extApps.xml and recreated my external apps. Now it works.
Thanks for your support.
