### ISSUE TITLE
Default Connection values are not saved

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#295]
Default Connection values are not saved. I set Redirect -> Key Combinations to Yes. After saving and restarting the application it is set back to No.

||||
|--:|---|---|
|Operating system | Windows 7 x64 | 
|mRemoteNG version| 1.75 beta 3  | Portable |

**Comment by sparerd** [comment]
I think i've found the issue. Working on building a test for this now

**Comment by sparerd** [comment]
built out some tests and resolved the underlying issue in commit `6019515`
