### ISSUE TITLE
CLR20r3 error while trying to open the application

### ISSUE THREAD

**Issue by fdicarlo** [mRemoteNG/mRemoteNG#298]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.74.6023.15437  |

Version=1
EventType=CLR20r3
EventTime=131255048727212584
ReportType=2
Consent=1
ReportIdentifier=b7f1cd09-bbb8-11e6-9dd1-e4a471d1ed8a
IntegratorReportIdentifier=b7f1cd08-bbb8-11e6-9dd1-e4a471d1ed8a
WOW64=1
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=mRemoteNG.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.74.6023.15437
Sig[2].Name=Problem Signature 03
Sig[2].Value=57728afa
Sig[3].Name=Problem Signature 04
Sig[3].Value=mRemoteNG
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.74.6023.15437
Sig[5].Name=Problem Signature 06
Sig[5].Value=57728afa
Sig[6].Name=Problem Signature 07
Sig[6].Value=91c
Sig[7].Name=Problem Signature 08
Sig[7].Value=12
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.NullReferenceException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=6153
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0a9e
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0a9e372d3b4ad19135b953a78882e789
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0a9e
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=0a9e372d3b4ad19135b953a78882e789
UI[2]=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
UI[3]=mRemoteNG has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
LoadedModule[1]=C:\Windows\SysWOW64\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\SysWOW64\SYSFER.DLL
LoadedModule[4]=C:\Windows\syswow64\KERNEL32.dll
LoadedModule[5]=C:\Windows\syswow64\KERNELBASE.dll
LoadedModule[6]=C:\Windows\syswow64\ADVAPI32.dll
LoadedModule[7]=C:\Windows\syswow64\msvcrt.dll
LoadedModule[8]=C:\Windows\SysWOW64\sechost.dll
LoadedModule[9]=C:\Windows\syswow64\RPCRT4.dll
LoadedModule[10]=C:\Windows\syswow64\SspiCli.dll
LoadedModule[11]=C:\Windows\syswow64\CRYPTBASE.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\Windows\syswow64\SHLWAPI.dll
LoadedModule[14]=C:\Windows\syswow64\GDI32.dll
LoadedModule[15]=C:\Windows\syswow64\USER32.dll
LoadedModule[16]=C:\Windows\syswow64\LPK.dll
LoadedModule[17]=C:\Windows\syswow64\USP10.dll
LoadedModule[18]=C:\Windows\system32\IMM32.DLL
LoadedModule[19]=C:\Windows\syswow64\MSCTF.dll
LoadedModule[20]=C:\Windows\system32\PGPmapih.dll
LoadedModule[21]=C:\Windows\system32\VERSION.dll
LoadedModule[22]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[23]=C:\Windows\system32\MSVCR120_CLR0400.dll
LoadedModule[24]=C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\affcb83bba04f782c2586a1788330891\mscorlib.ni.dll
LoadedModule[25]=C:\Windows\syswow64\ole32.dll
LoadedModule[26]=C:\Windows\system32\PGPhk.dll
LoadedModule[27]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[28]=C:\Windows\syswow64\OLEAUT32.dll
LoadedModule[29]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System\d03eb8a47500f40d5428f9c6875f8e56\System.ni.dll
LoadedModule[30]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\nlssorting.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\a57805cc2d492d82e327b83ab24fad62\System.Core.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\6b3bc806e6d6a2c73c6d9f1429395698\System.Configuration.ni.dll
LoadedModule[33]=C:\Windows\syswow64\urlmon.dll
LoadedModule[34]=C:\Windows\syswow64\api-ms-win-downlevel-ole32-l1-1-0.dll
LoadedModule[35]=C:\Windows\syswow64\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[36]=C:\Windows\syswow64\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[37]=C:\Windows\syswow64\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[38]=C:\Windows\syswow64\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[39]=C:\Windows\syswow64\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[40]=C:\Windows\syswow64\normaliz.DLL
LoadedModule[41]=C:\Windows\syswow64\iertutil.dll
LoadedModule[42]=C:\Windows\syswow64\WININET.dll
LoadedModule[43]=C:\Windows\syswow64\USERENV.dll
LoadedModule[44]=C:\Windows\syswow64\profapi.dll
LoadedModule[45]=C:\Windows\system32\Secur32.dll
LoadedModule[46]=C:\Windows\syswow64\SHELL32.dll
LoadedModule[47]=C:\Windows\system32\api-ms-win-downlevel-advapi32-l2-1-0.dll
LoadedModule[48]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[49]=C:\Windows\system32\rsaenh.dll
LoadedModule[50]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\48453ce4573683172752f7fdc00f8820\System.Drawing.ni.dll
LoadedModule[51]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\7b437291b260f008653ebc86553ab462\System.Windows.Forms.ni.dll
LoadedModule[52]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\36599a72e79974ff4c004c43df9fce2b\System.Xml.ni.dll
LoadedModule[53]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[54]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Management\2b2d69274742cfa9cac75a84dbd6fdf9\System.Management.ni.dll
LoadedModule[55]=C:\Windows\syswow64\CLBCatQ.DLL
LoadedModule[56]=C:\Windows\system32\wbem\wmiutils.dll
LoadedModule[57]=C:\Windows\system32\wbemcomn.dll
LoadedModule[58]=C:\Windows\syswow64\WS2_32.dll
LoadedModule[59]=C:\Windows\syswow64\NSI.dll
LoadedModule[60]=C:\Windows\system32\wbem\wbemprox.dll
LoadedModule[61]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\wminet_utils.dll
LoadedModule[62]=C:\Windows\system32\wbem\wbemsvc.dll
LoadedModule[63]=C:\Windows\system32\wbem\fastprox.dll
LoadedModule[64]=C:\Windows\system32\NTDSAPI.dll
LoadedModule[65]=C:\Windows\syswow64\psapi.dll
LoadedModule[66]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=mRemoteNG
AppPath=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe

**Comment by sparerd** [comment]
Haven't seen this sort of error before. Does this happen every time you attempt to start the app?

**Comment by fdicarlo** [comment]
hi @sparerd, yes, it happens everytime I'm trying to open the application.

**Comment by sparerd** [comment]
Might be worth trying to uninstall/reinstall the app, if you haven't already.

**Comment by fdicarlo** [comment]
hi @sparerd unfortunately uninstall/reinstall didn't to the trick

**Comment by sparerd** [comment]
Could you provide the mRemoteNG log? Details here: https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

You can also try deleting the user.config file (also mentioned in that article.)

**Comment by kmscode** [comment]
Try deleting the user.config as @sparerd mentioned. If that doesn't help, we'll need the stack trace / crash dump to see what is going on.

**Comment by fdicarlo** [comment]
hi @sparerd and @kmscode before posting here I checked on both repo and a google search, either without success, there is no user.config file, the only system folder is C:\Users\fdc\AppData\Roaming\mRemoteNG and cointain the startup log of the application:

2016-12-06 13:34:29,906 [1] INFO - mRemoteNG 1.74.6023.15437 starting.
2016-12-06 13:34:29,913 [1] INFO - Command Line: System.String[]
2016-12-06 13:34:31,036 [1] INFO - Microsoft Windows 7 Professional Service Pack 1 64-bit
2016-12-06 13:34:31,036 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2016-12-06 13:34:31,037 [1] INFO - System Culture: en-US/English (United States)
2016-12-06 13:37:08,346 [1] INFO - mRemoteNG 1.74.6023.15437 starting.
2016-12-06 13:37:08,362 [1] INFO - Command Line: System.String[]
2016-12-06 13:37:09,469 [1] INFO - Microsoft Windows 7 Professional Service Pack 1 64-bit
2016-12-06 13:37:09,469 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2016-12-06 13:37:09,469 [1] INFO - System Culture: en-US/English (United States)
[and so on]

I attached the .wer file in C:\Users\fdc\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_mRemoteNG.exe_8a56244a0be2e4ed83967aa4839dbd3aca4c90_1e9be684
[Report.wer.txt](https://github.com/mRemoteNG/mRemoteNG/files/635021/Report.wer.txt)

**Comment by sparerd** [comment]
Can you attached the entire mremoteng.log file?

**Comment by fdicarlo** [comment]
Done! Funny stuff, I activated DebugDiag on mRemote and now started to work
[mRemoteNG - Copy.txt](https://github.com/mRemoteNG/mRemoteNG/files/635062/mRemoteNG.-.Copy.txt)

**Comment by sparerd** [comment]
Based on that log, it looks like the app was crashing sometime between setting the system culture and trying to import putty entries.

**Comment by kmscode** [comment]
Likely failed in the compatibility checker from the looks of things...

```
Startup.cs

InitializeProgram()
{
...
LogStartupData();
CompatibilityChecker.CheckCompatibility();
...
}

**Comment by rsdan** [comment]
Hello,
I have approximatively the same problem.
I tried with the 1.74 and the beta 3 1.75

Sorry, I don't find the user.profil file.

![mremoteng_log](https://cloud.githubusercontent.com/assets/24717984/21428136/ce50571c-c858-11e6-9544-de21146c1005.PNG)
![windowslogs](https://cloud.githubusercontent.com/assets/24717984/21428185/0cf71668-c859-11e6-8dad-98d27dbc2d02.PNG)

Regards

**Comment by meffect** [comment]
Have you tried pointing to the config file with the switch in a shortcut target

Example:
`"C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe" /c:C:\Config\mRemoteNG\confCons.xml`

**Comment by rsdan** [comment]
Thank you but same results.

**Comment by kmscode** [comment]
@rsdan Your crash appears to be different.... You're getting an [SEHException](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.sehexception(v=vs.110).aspx) in the frmMain.InitializeComponent() method. This occurs a bit later in execution than InitializeProgram().

The SEHException is a bit odd/concerning as this could have been generated by "unmanaged" code. But I wasn't able to quickly find any smoking guns after a code review in that area.

I've done some code cleanup and added some additional logging via a few commits as I've been reviewing this issue. Hopefully the next build we release will be better, or at least provide us some more info.

**Comment by rsdan** [comment]
Thank you.
Do you know when the next build will be release ?

**Comment by kmscode** [comment]
No solid ETA at this time. Likely not until the beginning of January though. It will likely be another beta or release candidate version.

**Comment by kmscode** [comment]
[1.75 RC1](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75RC1) has been released. Please download and test if this problem has been resolved. If not, please post the updated stack trace.

**Comment by kmscode** [comment]
1.75 final release will happen soon. No significant changes from 1.75 RC1. Should you still encounter problems, please reopen this bug report.

**Comment by minsouk1** [comment]
download portable zip file and try again (not msi file)
