### ISSUE TITLE
closing connections

### ISSUE THREAD

**Issue by federicozanardi** [mRemoteNG/mRemoteNG#302]
on previous version (berfore 1.75 beta 1) when I logoff from a session, a tab used to remain with a  "reconnect" button
now I cannot figure out to have this behaviour back and the connection pane close

this is really useful to "remember" previous connection  even when i move to different customers and have mremote reconnect when I get back to base

**Comment by kmscode** [comment]
Tools -> Options -> Advanced -> Check: Automatically try to reconnect when disconnected from server (RDP & ICA only)

Not sure why that setting may have been turned off between versions though...

**Comment by federicozanardi** [comment]
great! you are right
tnx
