### ISSUE TITLE
mRemoteNG does not start after windows crash

### ISSUE THREAD

**Issue by andreaskoe** [mRemoteNG/mRemoteNG#309]
My Windows stopped (blue screen). mRemoteNG was active in the background, but I don't expect mRemoteNG caused that issue.
After computer restart, mremoteNG does not open the graphical windows on startup. Searching the event viewer shows some XML related issues, so I checked the xml files in ...\AppData\Roaming\mRemoteNG (confCons.xml, ...). The had been corrupt - which had been described somewhere else before. So I replaced them from backup. But this did not fix the problem.
After scanning my system I found another config file:
"C:\Users\Andreas\AppData\Local\mRemoteNG\mRemoteNG.exe_Url_pjpxdehxpaaorqg2thmuhl11a34i3ave\1.74.6023.15437\user.config"
This file was corrupt, too (first lines OK, then only NULLs).
Deleting this file fixed the problem.

Some ideas which might improve this (allready very good) program:
- Catch the exception which occurs during reading the config xmls and show the problematic file names in a window.
- Close the config files after reading them, and open them again if a chage/write is necessary. Maybe that reduces the risct of coruppting the file during accidents.

|||
|--:|---|
|Operating system | Windows 10 pro x64 |
|mRemoteNG version| 1.74.6023.15437  |

**Comment by aurelienGITHUB** [comment]
Same issue !  Delete C:\Users\%username%\AppData\Local\mRemoteNG\ solve the issue. Tks @andreaskoe

**Comment by kmscode** [comment]
Crashes related to the user.config happen very early on in execution and are largely related to the .NET Framework itself. This is well outside of our control. 

All of the user.config related code is all .NET Framework code:
https://msdn.microsoft.com/en-us/library/bb397750(v=vs.110).aspx

If we were to maintain our own settings, this would require a very significant amount of code/time/effort and would likely destabilize the application in the short-term.
