### ISSUE TITLE
[Idea] Credential Manager / Connection file seperation

### ISSUE THREAD

**Issue by Silent-Joker** [mRemoteNG/mRemoteNG#310]
Cleaned up:

I was wondering what options were planned for the Credential Manager.  I am hoping that we can separate Credentials and Connections into two separate files.  Still leaving an option to make a default credential for the connection.

Case 1:  I have Two people who want to share a connection file.  They both can open the file saved on say G:\MremoteNG\conf.xml.  When a user opens the connection file it allows users to assign their password saved separately to connections inside the file.  So if User 1 opens the file he can link his passwords to the connections.  Same with User2.  Of course either user cannot see what passwords are being used etc.  This way User1 can choose to either use the default credentials saved when the connection was made or choose to use his own password.  Same with anyone else who opens the conf.xml file.  Now users can share connections and update them for everyone but have their own password saved personally.

I am thinking that for the user's password file it saves the links inside there instead of the conf.xml file.  This way its secure and no one see's anything in the conf.xml file that is shared.

This is very brief and simple but i think you get the point.

Thoughts?

**Comment by Silent-Joker** [comment]
I hate apple this was an accident.

My pc crashed so i thought are there plans to seperate passwords and connections?  So i can share my connection file with another person but we specify our own passwords or use one thats saved with the connection.

**Comment by Silent-Joker** [comment]
Cannot find edit post on mobile apple

**Comment by kmscode** [comment]
@Silent-Joker This is already planned and has some work on it in a branch: https://github.com/mRemoteNG/mRemoteNG/tree/MR-184_Credential_Manager

Reference #208 - Please upvote this Issue accordingly (for further comments and notifications).

Closing this one as a duplicate...
