### ISSUE TITLE
Import from Active Directory does not use machine's domain by default

### ISSUE THREAD

**Issue by jschlie** [mRemoteNG/mRemoteNG#311]
Performing an import from active directory opens the AD import panel with the domain field filled in with "tant-a01" as the domain to use rather than using the registered domain of the computer the app is running on.  Manually filling in the field and clicking the change button does bring up the domain.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 Beta 3  |

**Comment by kmscode** [comment]
Not sure how that happened... Looking back at past checkins... Will fix ASAP.

**Comment by NVader2000** [comment]
Yeah, still does not seem to work. Running 1.77.1.27654. I can enter in the FQDN (e.g. domain.net) and click Change, but nothing appears to happen. Will it allow IP or FDQN of a domain controller?

However, my device is not domain joined. So not sure if I need to do something different here.
