### ISSUE TITLE
Caret being put Into password

### ISSUE THREAD

**Issue by jfen** [mRemoteNG/mRemoteNG#313]
When using filezilla as an external tool it is putting a "^" in my password. This looks to be an issue when using special characters. i have put an example below, not my really password btw. i have tried to copy and paste my password as well but it gets the same result. i was able to find out what was being sent by using %Password%:%Username% which has the user and pass swapped.  I did not have this issue with version 1.5.

i have put the password in manually and it does work. So the issue is likely when it grabs the password from and replaces %Password%. i have not tested it with the username but i would suspect it would do the same.

entered: notpass!!@#$%^&*()
result: notpass^!^!@#$^%^^^&*^(^)

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Working as designed. You'll need to change the option to %!PASSWORD%. Reference:
https://github.com/mRemoteNG/mRemoteNG/wiki/External%20Tools

**Comment by jfen** [comment]
thanks for the quick response that was it.

**Comment by kmscode** [comment]
😄 Glad to get an easy one every now and then...
