### ISSUE TITLE
May I ask for migration guide of mRemoteNG?

### ISSUE THREAD

**Issue by youjenli** [mRemoteNG/mRemoteNG#315]
Greetings, Maintainers of mRemoteNG

May I ask for migration guide of software settings (especially connection settings...) from version 1.72.5065.32743 to current version?
Our members of software system operating team already use this software for several years. They appreciate your work. Now they seek to migration their configuration to current version, could you give us some help?

Thank you~

Since web forums of mRemoteNG does not allow any registration, please forgive me for posting this question here.

**Comment by kmscode** [comment]
@youjenli There's no migration needed. 1.74 (the current final release) will load 1.72 version connection settings and well upgrade the file format automatically.

You may want to backup the confCons.xml just to be on the safe side however...

**Comment by sparerd** [comment]
Closing this issue. Please feel free to reopen it if you have further questions.
