### ISSUE TITLE
PCB (VMid) option for RDP Remote Desktop

### ISSUE THREAD

**Issue by ethancedrik** [mRemoteNG/mRemoteNG#316]
In clients like FreeRDP you can specify a PCB (preconnection blob/VMid) if you are connecting to a HyperV console session. I think this feature should be implemented in mRemoteNG. 

Here is some more info on how that can be done and implemented in an existing/in development Remote Desktop client, https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/6527eebb-e2db-4607-8ab0-be3d16b5f1cd/rdp-preconnection-blob-settings-on-windows-server?forum=windowsgeneraldevelopmentissues

**Comment by vincentparrett** [comment]
+1

**Comment by sparerd** [comment]
We are doing some RDP enhancements in v1.77. This could probably be squeezed in at the same time.

**Comment by S-dn-Y** [comment]
Hi Guys,

I really love mRemoteNG, this feels like the only thing that is missing.
I see there's an active pull request on this.
Is this still scheduled in the 1.77 release and/or when is the update (or this functionality) expected to arrive :)

Appreciate the effort!

Best regards.

**Comment by sparerd** [comment]
It is very likely we will be able to include this with v1.77. We are still in the development stages for this release and don't know when this particular feature will be included

**Comment by S-dn-Y** [comment]
Alright, thanks for the reply David.
I'm looking forward to it!
Have a good one, cheers!
