### ISSUE TITLE
Override quick connect username when using user@domain

### ISSUE THREAD

**Issue by benwa** [mRemoteNG/mRemoteNG#319]
| | |
|--:|---|
| Operating system | Windows 10 1607 x64 |
| mRemoteNG version | 1.75 alpha 3  |

When connecting via the quick connect bar, it would be nice to override the default username and password if you use the `user@host` convention.

**Comment by kmscode** [comment]
Start coding... :wink:

**Comment by sagipael** [comment]
Any news?
