### ISSUE TITLE
Option to show existing configured connection icon on each tree item instead of pause icon.

### ISSUE THREAD

**Issue by johnwc** [mRemoteNG/mRemoteNG#326]
It would be nice to visualy see the icon we select in the tree instead of the pause icon for every item.  The play icon is fine for when it is currently connected, or maybe an overlay play icon over the selected icon would be cool too.

**Comment by sparerd** [comment]
Some rewrites of the connection tree have made this a bit easier to implement. Tentatively set for v1.76

**Comment by fred9176** [comment]
+1 :-)

**Comment by sierramike** [comment]
Didn't find this thead before posting #507, so my +1 :)

**Comment by julianscheideggerleanuxch** [comment]
+1 that is the missing feature i looking for :)

**Comment by kmscode** [comment]
This was implemented in 1.76 via #558 
Closing.
