### ISSUE TITLE
RDP options for Remote Apps

### ISSUE THREAD

**Issue by johnwc** [mRemoteNG/mRemoteNG#327]
Can we get the following options added for RDP connections types.  This will allow us to create connections for RDP Remote Apps.  Also, to pick up these lines in the RDP import functionality too.

remoteapplicationmode
remoteapplicationprogram
disableremoteappcapscheck
alternate shell

**Comment by sparerd** [comment]
We are doing some RDP upgrades in v1.77, might be able to fit this in as well

**Comment by sparerd** [comment]
Duplicate ticket #539 has good examples/use cases in it. Took me a while to make the connection between these requests.

**Comment by tfletcher87** [comment]
Is there a proposed release date for 1.77, or is it known for sure if this will be implemented in 1.77?

There are some security tools out there, such as CyberArk, who leverage the RemoteApp functionality for security purposes, such as recording session connections in an environment, and it would be awesome to have a tool like mRemote be usable in these instances.

**Comment by mmncbrgovpl** [comment]
HI, same request from me. I would like to have this option also. And also because of Cyberark. Is there any chance to have this in a short period of time ?

**Comment by sparerd** [comment]
No release date has been set as of now. We might be able to get an early alpha build of 1.77 in a week or so, but development on this particular feature has not started yet.

**Comment by almdag** [comment]
I am also very interested in this feature, we used it for CyberArk.
Can you confirm if it will be in future versions?

**Comment by sparerd** [comment]
As mentioned, this will be in v1.77. No release date has been set

**Comment by ogulcanozugenc** [comment]
Hello. We need this for CyberArk. It would be perfect because this is the best app to RDP for us. Thanks for this great app! I am at Development channel. I hope it will be here soon.

**Comment by PeterHCauseway** [comment]
This would be great

**Comment by vmmorris** [comment]
This would be very nice to have

**Comment by japimentel** [comment]
Anything we could do to help move this along?  mRemoteNG is the preferred RDP platform for our company, but without this functionality we are crippled for privileged access.

Please help move this forward if you can.  It's been in queue for some time now. OP was Jan 2017...

**Comment by ChUnderwood** [comment]
Hope to see this is 1.77! This would be a huge win for my team.

**Comment by adthorn** [comment]
Agreed, I see 1.77 as pre-release. Is this option available yet?

**Comment by mcgr3g0r73** [comment]
How about the functionality  for CyberArk in version 1.77?

**Comment by adthorn** [comment]
Agreed, Cyberark is one of many that uses an option like this. I feel like this should be fairly easy to do as it's just a variable.

**Comment by adthorn** [comment]
We're forced to use CyberArk now for our jump box. Now unfortunately can't do it. Definitely need to be able to run an app on connect.

**Comment by ogulcanozugenc** [comment]
I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.

**Comment by adthorn** [comment]
> I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.

Not to be rude, but okay? I do too, but this is for mRemoteNG. This is pretty simple functionality that is in a standard RDP file. I love mRemoteNG hence the request here. RDCM is old and outdated.

**Comment by ogulcanozugenc** [comment]
I know you are right but I just wanted to give people an advice and a tip that works. I am also waiting for a long time for this improvement in mRemoteNG. Good day 🙂

**Comment by adthorn** [comment]
> I know you are right but I just wanted to give people an advice and a tip that works. I am also waiting for a long time for this improvement in mRemoteNG. Good day 🙂

Yep, not a problem. I just feel like this request has been back tabled. I know it's opensource, but I'd be willing to help contribute funds to help develop this further. It's a security feature we need. Literally variables it needs to pass to the session.

**Comment by adthorn** [comment]
@sparerd - Any update to this?

**Comment by eckard** [comment]
Would like this feature because I have to use CyberArc, too, but not seeing any hints for this in the development branch release notes 1.77.1

**Comment by wel781** [comment]
> I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.

Could you please share with us how do you configure RDCM 2.7 to use CyberArk?
Thanks in advance

**Comment by AneeshENV** [comment]
> I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.

Can we use RDCM for putty/ssh connections?

**Comment by AneeshENV** [comment]
Dev team, any update on adding this feature?

**Comment by eckard** [comment]
I'm not from dev team, however this issue seems scheduled for the next release 1.77 - see the todo list of [milestone 1.77](https://github.com/mRemoteNG/mRemoteNG/projects/3).

Probably it'll appear in the official [changelog](https://github.com/mRemoteNG/mRemoteNG/blob/develop/CHANGELOG.md) as soon when it's ready, therefore I'm looking forward to the upcoming version :-)

**Comment by adthorn** [comment]
> I'm not from dev team, however this issue seems scheduled for the next release 1.77 - see the todo list of [milestone 1.77](https://github.com/mRemoteNG/mRemoteNG/projects/3).
> 
> Probably it'll appear in the official [changelog](https://github.com/mRemoteNG/mRemoteNG/blob/develop/CHANGELOG.md) as soon when it's ready, therefore I'm looking forward to the upcoming version :-)

Unfortunately, it's been on the "to-do" list for 9 months almost with no change or talk about it. Wondering how we can get some traction on it since it seems simple enough to implement as you're just passing a native varible to the RDP client.

**Comment by adthorn** [comment]
@sparerd  or @jotatsu - Do we have a timeline for this?

**Comment by brokensyntax** [comment]
Also throwing in my hat to request RemoteApp features.
I'm definitely not an amazing coder, but would be willing to throw some effort at it to help someone who is a capable programmer.

**Comment by adthorn** [comment]
> Also throwing in my hat to request RemoteApp features.
> I'm definitely not an amazing coder, but would be willing to throw some effort at it to help someone who is a capable programmer.

I would help if I had some programming experience but I do not. I'd be willing to donate additionally if we could get this feature.

**Comment by Stan-Tastic** [comment]
I'd be happy to see this feature as well!

**Comment by JEFMendes** [comment]
+1

This feature deserves some attention...

**Comment by khoobze** [comment]
+1 I am waiting this since 2 years ago

**Comment by aivaras-v** [comment]
+1 Hopefully there will be updates soon

**Comment by adthorn** [comment]
Still waiting :)

**Comment by malix0** [comment]
+1 for "alternate shell" support

**Comment by japimentel** [comment]
Wow this request has been open for over 3 years.  Is there any hope that this will ever get addressed?  Even more important now that MS RDC Manager is now deprecated.

**Comment by japimentel** [comment]
> I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.

Not any more :-(

**Comment by adthorn** [comment]
It is 3 years old for such, I think, simple thing. Maybe it's a lot more complicated than it looks but who knows.

> > I use Remote Desktop Connection Manager 2.7 for CyberArk. You can edit the .rdg file with an editor and add new servers easily.
> 
> Not any more :-(

**Comment by vardars** [comment]
Hi, I would like to work on "alternate shell" feature.

**Comment by johnwc** [comment]
I have created a PR #1848 that adds the Alternative Shell properties. I will add the others as I have time within the next few weeks.

**Comment by ErMaqui** [comment]
PR #1849 has been merged, this issue can be closed.

**Comment by johnwc** [comment]
It may have been merged, but it did not add the working directory setting. This is sometimes required. Also, the other PR did not address any needed scheme version change or update the SQL tables for the new settings. Think the updates I requested PR from only had the XML things missing. These two should have been pulled together and then merged.

**Comment by Kvarkas** [comment]
> update the SQL tables for the new settings. Think the updates I requested PR from only had the XML things missing. These two should have been pulled together and then merged.
Currently I am working to change SQL stuff a bit completely so working on that part

**Comment by ErMaqui** [comment]
> 
> 
> It may have been merged, but it did not add the working directory setting. This is sometimes required. Also, the other PR did not address any needed scheme version change or update the SQL tables for the new settings. Think the updates I requested PR from only had the XML things missing. These two should have been pulled together and then merged.

Maybe if you update your PR #1848 for support the changes already merged, then @Kvarkas can approve it and got this problem solved.

**Comment by johnwc** [comment]
Well, to be honest I feel like I've wasted my time with the first PR. As it was not merged, but rather one that came after it was that had less updates and fixes.

**Comment by Kvarkas** [comment]
> Well, to be honest I feel like I've wasted my time with the first PR. As it was not merged, but rather one that came after it was that had less updates and fixes.

hello, could you point me to that was you first PR? currently I merge ones that not cause any issues with a bild test, but perhaps missed dependency?

**Comment by johnwc** [comment]
It is mentioned a few times in this thread. PR #1848 that was completed the very previous day that PR #1849 was. No clue why @vardars felt it necessary to do all the work the very next day when he knew I had did it and submitted the PR.

**Comment by vardars** [comment]
Hi there @johnwc , I started my work on August 29th, after my message, at that time there was no information about any work on this 3 years old issue. So you should've written a message before you started working, that way we could know that you were working. Nobody checks if any pr is created or not in hours for such an old issue.
I mentioned on this thread and on my pr that it had only alternate shell feature.
Your pr automated checks are failing, you can work on that first.
This is not a race between anybody, public will benefit each of our contributions. Keep that in mind. So don't be overwhelmed by such events.
Have a good day.

**Comment by johnwc** [comment]
You got notified that same day that I created the PR... It even shows that above in the history of this thread. You as well did not say that you were working on anything, you only stated that you would like to work on this.

The automated checks at that time were not relevant to what I did, so I was not responsible for those. They pasted 5 out of 10 builds.

The public may benefit from our work, but both of our time is valuable to each their own. Two people working on the same thing is a waist for all who is involved.

**Comment by vardars** [comment]
> You got notified that same day that I created the PR... 
Yes after I completed my work.

> You as well did not say that you were working on anything, you only stated that you would like to work on this.
At least I wrote something about it.

Actually I was already using that feature I implemented on a local build for a while and wanted to share it with people.

A failing build is a failed build no more no less.
You can ask the maintainer to reverse commit my pr (no big deal for me) and ask to merge yours after you fix failing build and add xml configuration. No need to whine this much.

**Comment by Kvarkas** [comment]
Guys I am just overtake control of that projects PR - honestly I wast track who is doing what so please understand if i see PR with no issues its easy points to apply it, also currently we have 2 versions to maintain one is 1.77 and 1.76 as i see @johnwc did pr for 1.76 and vardans for 1.77 and 1.76 have other stuff to implement perhaps so build is failing, I will review such changes and do merge, but in feature i prefer to have one versions (1,8) to maintain so we avoid split. I am really thanks for you both for help but we dont have challenge there and I have a bit different vision how we need to fix that than you both :D just dont have time to all stuff need to be corrected on that project so take easiest way first :) so @johnwc and @vardars you both are valued for this project but give me some time to sort curent problems we have ;)

**Comment by mcdonamw** [comment]
It is now 2023, has this feature ever been added?  I have 1.77 but I cannot seem to find it.  I'm expecting since this is still open it never made its way into 1.77 as noted would above.

**Comment by BlueBlock** [comment]
It looks like it is scheduled for 1.78
