### ISSUE TITLE
Menu items do not fit or not redrawn correctly when running chrome as external app

### ISSUE THREAD

**Issue by MaRRiK74** [mRemoteNG/mRemoteNG#332]
Menu's are not redrawn/refreshed correctly resulting in 'empty' menu's. Also the color schemes are confusing when used on Windows 10/Server2016 operating systems.

Chrome after opening a session (doesn't fit):
![image](https://cloud.githubusercontent.com/assets/19833001/21760223/bb7274fe-d64a-11e6-9d44-00cc99117656.png)

IE after opening a session (menu items disappear):
![image](https://cloud.githubusercontent.com/assets/19833001/21760256/ece80fda-d64a-11e6-8c15-402b792a3c96.png)

**Comment by sparerd** [comment]
Thanks for the report. We'll take a look at it

**Comment by farosch** [comment]
No need to run Chrome as external app any more as of #2022
