### ISSUE TITLE
Retain Putty Settings

### ISSUE THREAD

**Issue by wrightt** [mRemoteNG/mRemoteNG#333]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
Can you elaborate more on what you would like? Putty settings can already be saved within Putty, and mRemoteNG allows you to select Putty profiles to use for a given connection.

**Comment by sparerd** [comment]
Closing due to lack of response
