### ISSUE TITLE
The Quick Connect Toolbar > Connection view does not show open connections with the play icon.

### ISSUE THREAD

**Issue by c0ling** [mRemoteNG/mRemoteNG#335]
The Quick Connect Toolbar does not show any open connections with the play icon. All connections are shown with the pause icon.

![image](https://cloud.githubusercontent.com/assets/25031206/21805706/7fd0e3fc-d72d-11e6-8be8-fc30f160a6e3.png)

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.6179.28160 (beta 3)  |

**Comment by sparerd** [comment]
Good catch. We'll look into this

**Comment by sparerd** [comment]
The fix provided by @pedro2555 will be included in the patch 9 release shortly
