### ISSUE TITLE
Windows 10 - Build 15002

### ISSUE THREAD

**Issue by bdn02** [mRemoteNG/mRemoteNG#337]
Operating system: Windows 10 - Build 15002
mRemoteNG version: 1.74.6023.15358

When i try to open mRemoteNG my computer crash with a blue screen (that in this version is green).

The detailed error that i see in event viewer:

> Bucket errato 0x13A_win32kfull!DesktopAlloc, tipo 0
> Nome evento: BlueScreen
> Risposta: Non disponibile
> ID CAB: 54a94c99-7e62-4306-986e-a78ad438092a
> 
> Firma problema: 
> P1: 13a
> P2: 6
> P3: ffffc19040800000
> P4: ffffc1904089e9e0
> P5: 0
> P6: 10_0_15002
> P7: 0_0
> P8: 256_1
> P9: 
> P10: 
> 
> File allegati:
> \\?\C:\WINDOWS\Minidump\011017-5796-01.dmp
> \\?\C:\Windows\Temp\WER-8250-0.sysdata.xml
> \\?\C:\WINDOWS\MEMORY.DMP
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3393.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33C2.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33D2.tmp.txt
> 
> I file potrebbero essere disponibili qui:
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Kernel_13a_cf6cd811c3d8dc6da97e25fcedebff24caa93835_00000000_cab_171286b7
> 
> Simbolo analisi: 
> Nuova ricerca di soluzioni: 0
> ID rapporto: bd3080b5-f2d9-4786-901d-0813456fdd20
> Stato rapporto: 268435456
> Bucket con hash: 
>

**Comment by kmscode** [comment]
If you post the memory dump and Windows Error Report data, we can review it to see if there was anything related to mRemoteNG... However, mRemoteNG is a user mode application - there is no direct kernel hooks/access. It's highly unlikely that mRemoteNG is the cause of the blue screen. If anything there is an underlying component (.Net Framework, system call, etc) that is the cause of the crash.

Being that this is an insider build/beta, it's more likely that the problem is with Windows and not mRemoteNG.

**Comment by bdn02** [comment]
Some differents programs don't work with this version of insider preview, i think that you are right and the problem is related to OS. I've opened an issue to Microsoft.
Thank you for your response

**Comment by sparerd** [comment]
Reopening this issue as a place to keep track of resolution progress for build 15002.

**Comment by sparerd** [comment]
Created post to warn other users of this issue:
https://www.reddit.com/r/mRemoteNG/comments/5ncqz5/win10_insider_preview_build_15002_unstable/

**Comment by BrunoCrFr** [comment]
I have exactly the same problem with latest 1.75 beta 3 version. Hope M$ will correct it soon.

**Comment by kmscode** [comment]
I've setup a test VM out of curiosity... Just waiting for the fast build to be pushed out to me. @bdn02 @BrunoCrFr do either of you know how to speed up that process of getting the build?

**Comment by Silent-Joker** [comment]
usually its 24 hours after the install or change in level.

**Comment by Silent-Joker** [comment]
Did anyone try the High DPI compatibility option?

**Comment by Silent-Joker** [comment]
I just installed this build and it works fine for me.  I can do everything i could before i installed the build.  I did have Mremote installed prior to the fast ring update.  I also have an encrypted connection file that prompts for password on launch.

1.75.6179.28160

**Comment by kmscode** [comment]
Looks like there are multiple known issues with [15002](http://windowsreport.com/windows-10-build-15002-bugs/) and MS released [15007](https://blogs.windows.com/windowsexperience/2017/01/12/announcing-windows-10-insider-preview-build-15007-pc-mobile/#c4Vzd0E40EoWrYKj.97) just 3 days after 15002... So I'm guessing 15002 was just a "bad" build.

I wasn't able to get 15002 pushed to me and only received 15007 by the time I attempted to test this and the push actually started...

No problems with 15007. 

I'm going with my original assessment of OS problem.
