### ISSUE TITLE
Screen of death on mRemoteNG on Win10 new insider preview (170102-1700)

### ISSUE THREAD

**Issue by BrunoCrFr** [mRemoteNG/mRemoteNG#339]
Green screen of death on launching mRemoteNG.
![img_20170111_101351](https://cloud.githubusercontent.com/assets/25054951/21846143/fc79b690-d7f5-11e6-8ee7-d1bfc365db0d.jpg)

All was ok before last night Windows Insider Preview Update (fastring).

|--:|---|
|Operating system | Windows 10 x64 | 
![version w10](https://cloud.githubusercontent.com/assets/25054951/21846158/0eb6ce92-d7f6-11e6-80fe-ff2c05c2af7d.PNG)

|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
Related to #337

This was determined to most likely be an issue with the new insider build rather than mRemoteNG.

**Comment by sparerd** [comment]
Closing this issue as duplicate. We have reopened the original ticket #337 as the master ticket for tracking this issue. Thanks for reporting this to us!
