### ISSUE TITLE
Save Configurations without Restarting

### ISSUE THREAD

**Issue by strike5150** [mRemoteNG/mRemoteNG#340]
Operating System Windows 10 x64
mRemoteNG Version 1.72

It would be really great if settings for new connections were saved immediately after making them.  I create a lot of connections and sometimes the program crashes and I will lose a bunch of connections I've made.

Steps to Reproduce:
1 - open mRemoteNG
2 - create a new ssh connection, add hostname username/password and port
3 - open connection to see its working
4 - crash the program
5 - reopen and notice the new connection and other settings have reverted to the state before any new changes were made.

I don't remember if this was done before I don't remember having this issue in the past, I have used this program for several years now.

Other than that wonderful program thank you very much for your efforts.  I would also be happy to help with the issue if that is of interest.

**Comment by kmscode** [comment]
@strike5150 1.72 is quite old. You should update to at least 1.74, though the 1.75 beta3 is quite stable. 

You can always save your connection file via Ctrl +S or File -> Save Connection file. Though External Tools could still run into the same problem that you described. 

Will leave this open as a feature request to implement auto save functionality.

**Comment by sparerd** [comment]
Just for completeness, there is a timed auto-save feature available in Tools -> Connections -> Auto save every [X] minutes.

However, there is not an auto-save-after-every-change feature as @strike5150 is requesting.

**Comment by kmscode** [comment]
Forgot about that one! 😉 

I think we should look into an auto save feature to write any changes immediately for connections, external tools and the UI layout (and anything else that I might be missing that has an xml/config file).

**Comment by sparerd** [comment]
I agree. It'd be worth looking into.

**Comment by strike5150** [comment]
I didn't even see the Ctrl+S  :P  It will certainly help alleviate my issues until it is autosaving.

**Comment by erpico** [comment]
Please add option to save configuration on changes.
I forgot to press Ctrl+S after every change and miss configuration changes on crashes or APP\PC restart.
