### ISSUE TITLE
Be able to set login cred in folder settings

### ISSUE THREAD

**Issue by johnwc** [mRemoteNG/mRemoteNG#341]
Every connection that has blank cred should walk backwards up the path of the folder structure to the root checking if cred are in one and use them if given. Else use the global in the app settings.

This will help when we have more than one environment that we work with that uses diff cred.

**Comment by kmscode** [comment]
Have you looked into Inheritance at all?

https://github.com/mRemoteNG/mRemoteNG/wiki/Folders-and-Inheritance

**Comment by Silent-Joker** [comment]
i guess it would be nice to be able to have inheritance by default option.  I just create a blank folder with inherit all and copy it when i make new ones.  Minor annoyance..
