### ISSUE TITLE
External Tools Documentation: sftp client examples

### ISSUE THREAD

**Issue by TheLeftMoose** [mRemoteNG/mRemoteNG#345]
Hi All

i love mRemoteNG, but i still miss some small additions that would bring it to the stars.

F.x a builtin sftp client that would run along side with a linux session. This way transfering files from and to a terminal would be very convenient.

If this could be solved by external app, please help me with some ideas.
\d

**Comment by kmscode** [comment]
I'm mobile right now, but I'll post some external tool examples to the wiki later. 

This is a popular request outside of external tools. It's low priority since external tools solve this very sufficiently. It will need to be discussed in the future.

**Comment by kmscode** [comment]
Here's a screenshot of my external tools config:
![image](https://cloud.githubusercontent.com/assets/16654335/21943293/9fae34c2-d99e-11e6-8b07-5b8995aa2327.png)


And the entries in my extApps.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<Apps>
    <App DisplayName="WinSCP" FileName="C:\Program Files (x86)\WinSCP\WinSCP.exe" Arguments="&quot;sftp://%username%:%!password%@%hostname%:%port%&quot;" WaitForExit="False" TryToIntegrate="False" />
    <App DisplayName="Ping" FileName="C:\Windows\System32\PING.EXE" Arguments="&quot;-t %HostName%&quot;" WaitForExit="False" TryToIntegrate="False" />
    <App DisplayName="Trace Route" FileName="C:\Windows\System32\TRACERT.EXE" Arguments="&quot;%HostName%&quot;" WaitForExit="False" TryToIntegrate="False" />
    <App DisplayName="Filezilla FTP" FileName="C:\Program Files\FileZilla FTP Client\filezilla.exe" Arguments="-l ask %Username%@%Hostname%" WaitForExit="False" TryToIntegrate="False" />
    <App DisplayName="Filezilla SSH" FileName="C:\Program Files\FileZilla FTP Client\filezilla.exe" Arguments="-l ask sftp://%Username%@%Hostname%" WaitForExit="False" TryToIntegrate="False" />
</Apps>
```

I'll get some more details on the Wiki soon-ish... However, the existing External Tools overview should be looked at: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools
(especially for variable escaping notes).

**Comment by kmscode** [comment]
Reference #183 for the integrated FTP client request. Will leave this one opened for documentation purposes and that one as the feature request. Upvote that one if desired to be notified of any future updates.

**Comment by dboc** [comment]
Great! Thanks a lot... I just made one different configuration to insert password on FileZilla.

![image](https://user-images.githubusercontent.com/7704278/53246245-eb277b80-368e-11e9-9b0e-efeee0e5ab2f.png)

**Comment by nmat** [comment]
Feels like this can be closed since we do have the information in place now and there are a bunch of examples ready to be tested.

Anyone feel like we can't close this?

**Comment by nmat** [comment]
This will be covered in the new documentation coming in 1.77.
