### ISSUE TITLE
Newbie question - Feature Add

### ISSUE THREAD

**Issue by W-C-R** [mRemoteNG/mRemoteNG#350]
Being new, I am starting to add a number of RDP connections to my installation.
Because a lot of the systems that I connect to are for graphics purposes (user platforms), every time I create a new connection, I have been altering most of the Appearance settings ('Cache Bitmaps', 'Display Wallpaper', 'Display Themes', 'Font Smoothing' and 'Desktop Composition').

I am looking for a means of changing the default values of all of these options when the connection is created.

**Comment by SaschaJohn** [comment]
Use the inheritance feature of mRemoteNG

**Comment by W-C-R** [comment]
Currently on 1.74 (2016-06-28).  I have not been able to locate anything like 'inheritance' in the program.

**Comment by kmscode** [comment]
It's buried... But it's there...

https://github.com/mRemoteNG/mRemoteNG/wiki/Folders-and-Inheritance
