### ISSUE TITLE
state & position of button bar / state (visible/hidden) is not (re-)stored after restart

### ISSUE THREAD

**Issue by abma** [mRemoteNG/mRemoteNG#358]
|||
|--:|---|
|Operating system | Windows Server 2008 R2 x64 |
|mRemoteNG version| 1.75 beta 3  |

To reproduce:
deselect view->direct-connect bar 
save config

restart mRemote:

direct-connect bar is visible again.

**Comment by kmscode** [comment]
Could you please clarify? I don't have an option for direct-connect bar. Do you mean "Quick Connect Toolbar"?

Screen shot if needed.

Regards.

**Comment by abma** [comment]
yes, i meant "Quick Connect Toolbar".  i translated the localized back to english and failed it seems, sorry :-|

**Comment by abma** [comment]
not sure if relevant: i'm using the portable version.

**Comment by kmscode** [comment]
duplicate of #264. no longer able to reproduce. closing.
