### ISSUE TITLE
more flexible search in "connections"

### ISSUE THREAD

**Issue by abma** [mRemoteNG/mRemoteNG#366]
currently when searching in connections the current selection jumps to the first entry. If there are multiple matches its not possible to continue search.

would be nice if its possible to go to the "next" or "prev" search "result".

**Comment by kmscode** [comment]
Related to #338 

We may implement Filter logic which, depending on specific implementation may prevent the need for next/previous...

**Comment by sparerd** [comment]
down/up arrows can be used to move through the list of matches. Might be worth having a UI element for next/previous search though.

**Comment by abma** [comment]
> down/up arrows can be used to move through the list of matches. Might be worth having a UI element for next/previous search though.

Oh, i didn't know that. Thats basicly what i missed. So i guess this request is obsolete / partly a duplicate of report 338.

thanks!

**Comment by sparerd** [comment]
No worries @abma . We need to make it more obvious that that feature is available.
