### ISSUE TITLE
Ability to run External tools on folders.

### ISSUE THREAD

**Issue by Benchwork** [mRemoteNG/mRemoteNG#375]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.74  |

I would like the ability to run External tools on folders.
when I'm doing routine tasks, one of them is to reboot a bunch of production stations. I have been using MremoteNG to do it, and it has worked very well for years. however I need to right click on each connection to do it.  It would be nice to be able to have a checkbox when you setup your external tool to allow it to run the command on everything in the folder.
![image](https://cloud.githubusercontent.com/assets/7304823/22397886/c3a41994-e549-11e6-883c-2a448a6b3000.png)

although I gave one example, I believe this could be very useful across meany tools.

Thank you all for the hard work reviving and continuing such an awesome program!!
Peter.

**Comment by sparerd** [comment]
Makes sense, good suggestion!

**Comment by charles4308** [comment]
Any Updates on this feature request?
