### ISSUE TITLE
Single clicking on SSH in Connections Panel launches connection

### ISSUE THREAD

**Issue by Eldaw** [mRemoteNG/mRemoteNG#378]
If I double-click on an SSH connection in the Connections panel to initiate a connection, and then immediately single click on a different SSH connection (with the intention of simply selecting it), a connection to that one is also initiated.

1.75 RC 1 on Windows 10

**Comment by kmscode** [comment]
Reproduced.

**Comment by sparerd** [comment]
Also able to confirm. The first click after activating an SSH connection seems to be viewed as a double click, but only within the tree. Double clicking an RDP connection then single clicking something does not have the same effect (treated correctly as a single click).

**Comment by sparerd** [comment]
Uh... odd. Here's what i'm seeing:

1. Double click an ssh connection (single click executes, double click executes - this is expected)
2. Single click another ssh connection (double click executes)
3. Mouse over a treelist item (single click claims that it executes)

Step 2 is obviously wrong, but I also didn't expect step 3 to occur.

**Comment by sparerd** [comment]
This feels like a bug in ObjectListView, since we're hooking into their CellClicked event. Will have to test with their source to confirm.

**Comment by sparerd** [comment]
Re-implementing the same functionality using standard events does not produce the bug. This strongly points to ObjectListView as the cause.

**Comment by sparerd** [comment]
Pushed the fix to the 1.75 RC branch. A fix will be included in the next release.

Thanks for the report!
