### ISSUE TITLE
Passwords with Spaces not working

### ISSUE THREAD

**Issue by viper539** [mRemoteNG/mRemoteNG#381]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG portable version| 1.74.6023  |

i created a "external tool" to connect to VMware with this options:
 -s %Hostname% -u %username% -p %Password%

My Password contains an Blank/Space and all after it is not transmitted.
i.e. Password is "1234 qwer" only "1234" is transmitted as password.

Thank you for your really cool Tool!
Keep up your good work!

**Comment by kmscode** [comment]
Reference [external tools](https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools)

How would you run this command manually from a command line with the space in the password?

You may want to try "%PASSWORD%" or "%!PASSWORD%" (quotes included).

**Comment by viper539** [comment]
Hello kmscode,

my fault. the quotes are missed.

Issue can be closed.

Thank you,
viper539
