### ISSUE TITLE
Active Directory Sub OU Import Does Not Allow Import from Domain Object

### ISSUE THREAD

**Issue by jschlie** [mRemoteNG/mRemoteNG#382]
When attempting to import from the sub OUs in AD the user is unable to select the domain object as a base for the import.  The domain object should be selectable as the top level object from which to begin the import process.  The ability to select to domain object would simplify the import process and save a great deal of time in complex domains with numerous root OUs.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by farosch** [comment]
This has already been fixed. Closing
