### ISSUE TITLE
copy and paste inserts a lot of \n when a vnc session is active

### ISSUE THREAD

**Issue by abma** [mRemoteNG/mRemoteNG#384]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 beta 3  |

When a vncsession is active sometimes copy/paste date gets corrupted, i.e

line1
line2

becomes to 

line1
<hundreds of empty lines>
line2

when pasting.

I don't have a reliable way to reproduce it, atm it looks like it happens randomly. Only way to "fix" it is to close the vnc session and copy again the text.

**Comment by SteNeo** [comment]
got the same problem, 

with multiple VNC connection, any copy done is pasted with very many blank lines inserted between paste content

**Comment by abma** [comment]
sorry, forgot to add this info:

it seems this is a bug in tightvnc:

when we updated to a newer version this problem seems to be gone.

https://www.tightvnc.com/whatsnew.php

very likely this bug:

TightVNC 2.8.2:
"Server for Windows: Fixed server-side clipboard handling. After receiving clipboard contents from a client, the server could return the same clipboard data back to the same client, and clipboard could be damaged on the viewer side (sf bug 1255)."

@SteNeo: which vnc server are you using? does upgrading it fix the problem?

**Comment by SteNeo** [comment]
Am not using tightvnc i have the control that ships with mRemote VncSharp Control Version 1.0.0.0.
How do i switch it to TightVNC?

**Comment by sparerd** [comment]
@SteNeo I think @abma was referring to the VNC server that is installed on the remote host.

**Comment by SteNeo** [comment]
i will try to upgrade the VNC and let you know if that fixed the problem

**Comment by sparerd** [comment]
@SteNeo Have you had a chance to try upgrading VNC server? Is this issue still present?

**Comment by kmscode** [comment]
server side VNC bug. Closing.
