### ISSUE TITLE
UpdateCheck not working correctly

### ISSUE THREAD

**Issue by feutl** [mRemoteNG/mRemoteNG#386]
after installing your latest 1.75 RC1 release the update check somehow looks weird. it shows that the installed version is newer than the available version.
I have installed RC1 and the channel is set to Beta

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 RC1  |

![c3pk8iew8aecqnx](https://cloud.githubusercontent.com/assets/8522012/22555031/9e8c9fec-e962-11e6-933c-75ac6a63203a.jpg)

**Comment by kmscode** [comment]
For now, this is correct. The file that provides the data for the update check hasn't been updated yet. We didn't want to trigger any auto updates without some additional testing first.

It will likely be updated at some point next week.

**Comment by kmscode** [comment]
Update checks have been enabled and point to the 1.75 hotfix 1 release:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix1
