### ISSUE TITLE
Copy Paste Not working to RDP sessions

### ISSUE THREAD

**Issue by siddjoshi** [mRemoteNG/mRemoteNG#390]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74.6023.15358 (Portable)

Cannot copy paste text or files to and from remote desktop sessions. It works with RDP sessions when opened with mstsc.

**Comment by infectormp** [comment]
Try update to 1.75.6236.27923. Not have problem with this version.

**Comment by kmscode** [comment]
@siddjoshi Make sure "rdpclip.exe" is running and running as the user account you're logged in as. If it's running (as your user), but not functioning try killing it and restarted it (Run -> rdpclip.exe).

**Comment by siddjoshi** [comment]
@infectormp Same issue with version 1.75.6236.27923. 

@kmscode Initially rdpclip.exe was not running, i started it but copy-paste did not work, killed and restarted rdpclip.exe multiple times but no change. 

I am running on windows 10 Enterprise Build 10586 if that can be of help.

**Comment by lebe-dev** [comment]
Copy&paste may be disabled by remote side policies

**Comment by sparerd** [comment]
@siddjoshi Any updates on this issue? Still occurring?

**Comment by siddjoshi** [comment]
I found that it is working now for most of the server sessions. but couple of servers still has the copy-paste issue. Config to connect is same for all servers. Tried killing and restarting rdpclip.exe on the server too but it doesn't help. if i just to rdp using mstsc, copy-paste works. 
I guess its not the problem with mRemoteNG , Probably i'm missing something , just not ablt to figure out yet where.

**Comment by lebe-dev** [comment]
@siddjoshi check group policy restrictions for that servers at first

http://tritoneco.com/2013/10/04/disable-remote-desktop-copy-paste/

**Comment by sparerd** [comment]
@siddjoshi I'm going to closing this ticket as it seems to be an environment issue. Feel free to reach out again if you need more community help. Serverfault.com may be a good resource as well

**Comment by vishalkdotcom** [comment]
This might also be helpful.
https://github.com/mRemoteNG/mRemoteNG/issues/618#issuecomment-316986654
