### ISSUE TITLE
Error when decrypting saved connection password

### ISSUE THREAD

**Issue by eupo** [mRemoteNG/mRemoteNG#392]
I have a password saved for one system which i connect using "External tools":
^g7F^fw6
When trying to connect to this system with that saved password i have password error and in "Password" field i have 2 more asterisks (external tool shows real count of characters in password) than when copy password by hands (so password in two chars longer then needed). I think it is of "^" chars in password.
After making "dumb" external tool -- justecho.vbs
Set args = Wscript.Arguments

For Each arg In args
  Wscript.Echo arg
Next
And calling it instead of real external tool a can see that "^" are duplicated.
So password passed to external tool looks like
^^g7F^^fw6

|||
|--:|---|
|Operating system | Windows 8.1 x64 |
|mRemoteNG version| 1.75 RC 1  |

**Comment by sparerd** [comment]
Use `%!Password%` (notice the exclamation mark) to disable meta character escaping in passwords.

More details on this page:
https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#shell-metacharacter-escaping

**Comment by sparerd** [comment]
Closing this issue. Feel free to re-open if you have further concerns
