### ISSUE TITLE
Password protect doesn't work as expected

### ISSUE THREAD

**Issue by mighelon** [mRemoteNG/mRemoteNG#395]
Hi all,
I've recently enabled the password protect option to encrypt the entire connection file.
Unfortunately if I try to open it using an editor, I can see the content in clear.
Do you have an idea if it's a bug or if I can try to do something to solve the issue?
Cheers.

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74 stable  |

**Comment by kmscode** [comment]
@sparerd ... I haven't played with this enough to answer off the top of my head. I can test this next week if needed.

**Comment by sparerd** [comment]
The password protect option (seen when clicking the "Connections" tree node) just allows you to set a custom encryption password. By default, mRemoteNG uses a default password for encryption (bad). There is a different option to enable full file encryption - it sounds like that is what you are looking for. I think for v1.74 that was located in Tools -> Options -> Advanced -> Completely encrypt connection file.

Encryption got a minor update in v1.75 (stable release coming soon).
The entire credential management system is being overhauled for v1.76

**Comment by mighelon** [comment]
Thank you very much for your clarification.
That was the option I was searching for!
Have a great day.

m.

**Comment by sparerd** [comment]
No problem, happy to help!
