### ISSUE TITLE
Cannot use quick connect toolbar when only 1 tab is open

### ISSUE THREAD

**Issue by Elokku** [mRemoteNG/mRemoteNG#402]
| Operating system | Windows 10 x64 |
| mRemoteNG version | 1.75 RC1, 1.74 |

Hi.
I cannot use quick connect toolbar when only one ssh connection (only ssh connection, rdp seems fine) tab is open. When there is no tabs or 2 (or more) tabs everything is ok. The toolbar cannot be focued nor can I put any text into it.

Problem appeared in 1.74 version. In 1.72 this worked fine.

**Comment by kmscode** [comment]
Seems related to #268

**Comment by Elokku** [comment]
Yep, that's the same issue. Sorry for duplicate.

**Comment by sparerd** [comment]
Closing as duplicate issue
