### ISSUE TITLE
Description Preview

### ISSUE THREAD

**Issue by saviodsouza** [mRemoteNG/mRemoteNG#406]
Can Connection Description be seen as tool tips on printing to a connection.

Secondly what is the max length of description are line spacing supported

Great application (thumps up)
Really appreciate all existing features.

**Comment by kmscode** [comment]
Tools -> Options - Appearance -> Check show description tool tips
![image](https://cloud.githubusercontent.com/assets/16654335/23036122/95ae4c8e-f44f-11e6-85c0-66fe5ae682f5.png)


I was not able to find any defined limits in the code. I tested with over 380 characters. New lines are not accepted as input for that control.

**Comment by saviodsouza** [comment]
What about showing Description as tool tip when just pointing on a
connection?

**Comment by saviodsouza** [comment]
Sorry got it

Thanks again

**Comment by saviodsouza** [comment]
Ok got it
