### ISSUE TITLE
Update SQL Script with new tables to support new database scheme

### ISSUE THREAD

**Issue by Whatsek** [mRemoteNG/mRemoteNG#408]
In 1.75 RC 1,new tables are used. Could the SQLScript be modified?

https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Resources/Help/SQLScript.txt

**Comment by ConnorLinfoot** [comment]
Hey @kmscode,

Just wondering if this is going to be fixed anytime soon? Working in quite a large team and having it use SQL would be much preferred.

**Comment by Totorman** [comment]
Waiting the updated MSSQL script like a fool here too ! :)

**Comment by sparerd** [comment]
Hey all, ill try to get and update out this week. It'll be prioritized

**Comment by sparerd** [comment]
I think I have this worked out. I'll release it on the `Development` update channel today if you'd like to test it out. mRemoteNG should be able to update your DB columns automatically.

**Comment by sparerd** [comment]
A fix is now available on the `Development` channel. Please let me know if this resolves the issue

**Comment by ConnorLinfoot** [comment]
Doesn't seem to be working for me, after rebuilding the tables with the script and turning on SQL I get the following error:

----------
ErrorMsg
13/03/2017 09:31:52
Couldn't save connections file!
The given ColumnMapping does not match up with any column in the source or destination.
----------

**Comment by sparerd** [comment]
@ConnorLinfoot Could you run the following on your mRemoteNG db and paste the results here? Just to verify - your mRemoteNG version is 1.75.7002?

```sql
select ORDINAL_POSITION,COLUMN_NAME,DATA_TYPE
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'tblCons'
```

**Comment by ConnorLinfoot** [comment]
I'm on version 1.75.7002.26449

**Comment by sparerd** [comment]
Thanks Connor - 1 more query for you. Given the columns present in the last output, your confversion should show 2.5.  If it's 2.6, we'll need to modify that.

```sql
select ConfVersion
from tblroot
```

**Comment by ConnorLinfoot** [comment]
It is showing as 2.6, should I just edit that to be 2.5?

**Comment by sparerd** [comment]
Yea, push that back to 2.5. Then when you run mRemoteNG again, it should auto-alter the columns to be 2.6 compatible

**Comment by ConnorLinfoot** [comment]
That's worked in regards to getting it writing connections, seems to crash when attempting to import from an XML so not sure what's happening there.

Not sure if this is a bug but when I'm adding connections/folders it'll deselect the item I'm editing (assuming this is the SQL reload?) and thus causes my changes in the connection config to not save. If you need a video of this I should be able to get one.

**Comment by sparerd** [comment]
Good to hear the writing is working now. Whats the error on import? Anything in the log?

Yea, sounds like the sql reload is causing the deselection.

**Comment by ConnorLinfoot** [comment]
Is there a specific path where I can look for the logs? The program just stops responding.

I'm assuming there'll be a fix for the reload at somepoint?

**Comment by sparerd** [comment]
Log locations for your edition: https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

Yea, we'll need to look into a usability fix for the deselection bug.

**Comment by ConnorLinfoot** [comment]
Attached what I could find to hopefully help debug the crash.

[mRemoteNG.log.txt](https://github.com/mRemoteNG/mRemoteNG/files/842040/mRemoteNG.log.txt)
[mRemoteNG.exe.2348.zip](https://github.com/mRemoteNG/mRemoteNG/files/842043/mRemoteNG.exe.2348.zip)

**Comment by cagosti** [comment]
Im having exactly the same issue here, the same error in the log file to

**Comment by sparerd** [comment]
@ConnorLinfoot I'm looking into the import failures you reported. Few questions:

- What is the confCons version of the .xml file?
- Is the "Export" attribute set to "True"?

**Comment by cagosti** [comment]
Thank you for your response.

I would have created the confcons version originally in the stable versions before then installing the pre-release version.

I’ve set this to true in the database.

I hope this is what you required

Chris Agostini
Technical Support Engineer, Invu

[invu-logo]<http://www.invu.net/>
Providing Document Management<http://www.invu.net/solutions/document-management> (eDM), Accounts Payable<http://www.invu.net/solutions/accounts-payable-ap> (AP) and Purchasing<http://www.invu.net/solutions/purchasing> solutions.

t: 01604878010
e: chris.agostini@invu.net<mailto:chris.agostini@invu.net>
w: www.invu.net<http://www.invu.net/>
Follow Us: LinkedIn<https://www.linkedin.com/company/82884?trk> | Facebook<https://www.facebook.com/InvueDM> | twitter<https://twitter.com/invuECM>

**Comment by ConnorLinfoot** [comment]
@sparerd The ConfVersion is "2.6" and the export attribute is set to "False"

**Comment by sparerd** [comment]
@ConnorLinfoot Due to an unrelated bug, you will need to set the Export property to "True" on the xml file.

Found out what was going on with the import crash. More details in #464

**Comment by kmscode** [comment]
Corrected in hotfix2

**Comment by torabimilad** [comment]
if exists (select * from dbo.sysobjects
    where id = object_id(N'[dbo].[tblCons]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblCons]
GO

if exists (select * from dbo.sysobjects
    where id = object_id(N'[dbo].[tblRoot]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblRoot]
GO

if exists (select * from dbo.sysobjects
    where id = object_id(N'[dbo].[tblUpdate]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[tblUpdate]
GO

CREATE TABLE [dbo].[tblCons] (
        ID int NOT NULL IDENTITY(1,1),
        ConstantID varchar(128),
        PositionID int NOT NULL,
        ParentID varchar(128),
        LastChange datetime NOT NULL,
        Name varchar(128) NOT NULL,
        [Type] varchar(32) NOT NULL,
        Expanded bit NOT NULL,
        Description varchar(1024),
        Icon varchar(128) NOT NULL,
        Panel varchar(128) NOT NULL,
        Username varchar(512),
        DomainName varchar(512),
        Password varchar(1024),
        Hostname varchar(512),
        Protocol varchar(32) NOT NULL,
        PuttySession varchar(128),
        Port int NOT NULL,
        ConnectToConsole bit NOT NULL,
        UseCredSsp bit NOT NULL,
        RenderingEngine varchar(10),
        ICAEncryptionStrength varchar(32) NOT NULL,
        RDPAuthenticationLevel varchar(32) NOT NULL,
        RDPMinutesToIdleTimeout int NOT NULL,
        RDPAlertIdleTimeout bit NOT NULL,
        Colors varchar(32) NOT NULL,
        Resolution varchar(32) NOT NULL,
        DisplayWallpaper bit NOT NULL,
        DisplayThemes bit NOT NULL,
        EnableFontSmoothing bit NOT NULL,
        EnableDesktopComposition bit NOT NULL,
        CacheBitmaps bit NOT NULL,
        RedirectDiskDrives bit NOT NULL,
        RedirectPorts bit NOT NULL,
        RedirectPrinters bit NOT NULL,
        RedirectSmartCards bit NOT NULL,
        RedirectSound varchar(64) NOT NULL,
        SoundQuality varchar(20) NOT NULL,
        RedirectAudioCapture bit NOT NULL,
        RedirectKeys bit NOT NULL,
        Connected bit NOT NULL,
        PreExtApp varchar(256),
        PostExtApp varchar(256),
        MacAddress varchar(32),
        UserField varchar(256),
        ExtApp varchar(256),
        VNCCompression varchar(10),
        VNCEncoding varchar(20),
        VNCAuthMode varchar(10),
        VNCProxyType varchar(20),
        VNCProxyIP varchar(128),
        VNCProxyPort int,
        VNCProxyUsername varchar(512),
        VNCProxyPassword varchar(1024),
        VNCColors varchar(10),
        VNCSmartSizeMode varchar(20),
        VNCViewOnly bit NOT NULL,
        RDGatewayUsageMethod varchar(32) NOT NULL,
        RDGatewayHostname varchar(512),
        RDGatewayUseConnectionCredentials varchar(32) NOT NULL,
        RDGatewayUsername varchar(512),
        RDGatewayPassword varchar(1024),
        RDGatewayDomain varchar(512),
        InheritCacheBitmaps bit NOT NULL,
        InheritColors bit NOT NULL,
        InheritDescription bit NOT NULL,
        InheritDisplayThemes bit NOT NULL,
        InheritDisplayWallpaper bit NOT NULL,
        InheritEnableFontSmoothing bit NOT NULL,
        InheritEnableDesktopComposition bit NOT NULL,
        InheritDomain bit NOT NULL,
        InheritIcon bit NOT NULL,
        InheritPanel bit NOT NULL,
        InheritPassword bit NOT NULL,
        InheritPort bit NOT NULL,
        InheritProtocol bit NOT NULL,
        InheritPuttySession bit NOT NULL,
        InheritRedirectDiskDrives bit NOT NULL,
        InheritRedirectKeys bit NOT NULL,
        InheritRedirectPorts bit NOT NULL,
        InheritRedirectPrinters bit NOT NULL,
        InheritRedirectSmartCards bit NOT NULL,
        InheritRedirectSound bit NOT NULL,
        InheritSoundQuality bit NOT NULL,
        InheritRedirectAudioCapture bit NOT NULL,
        InheritResolution bit NOT NULL,
        InheritUseConsoleSession bit NOT NULL,
        InheritUseCredSsp bit NOT NULL,
        InheritRenderingEngine bit NOT NULL,
        InheritICAEncryptionStrength bit NOT NULL,
        InheritRDPAuthenticationLevel bit NOT NULL,
        InheritRDPMinutesToIdleTimeout bit NOT NULL,
        InheritRDPAlertIdleTimeout bit NOT NULL,
        InheritUsername bit NOT NULL,
        InheritPreExtApp bit NOT NULL,
        InheritPostExtApp bit NOT NULL,
        InheritMacAddress bit NOT NULL,
        InheritUserField bit NOT NULL,
        InheritExtApp bit NOT NULL,
        InheritVNCCompression bit NOT NULL,
        InheritVNCEncoding bit NOT NULL,
        InheritVNCAuthMode bit NOT NULL,
        InheritVNCProxyType bit NOT NULL,
        InheritVNCProxyIP bit NOT NULL,
        InheritVNCProxyPort bit NOT NULL,
        InheritVNCProxyUsername bit NOT NULL,
        InheritVNCProxyPassword bit NOT NULL,
        InheritVNCColors bit NOT NULL,
        InheritVNCSmartSizeMode bit NOT NULL,
        InheritVNCViewOnly bit NOT NULL,
        InheritRDGatewayUsageMethod bit NOT NULL,
        InheritRDGatewayHostname bit NOT NULL,
        InheritRDGatewayUseConnectionCredentials bit NOT NULL,
        InheritRDGatewayUsername bit NOT NULL,
        InheritRDGatewayPassword bit NOT NULL,
        InheritRDGatewayDomain bit NOT NULL,
        LoadBalanceInfo varchar(1024),
        AutomaticResize bit DEFAULT ((1)) NOT NULL,
        InheritLoadBalanceInfo bit DEFAULT ((0)) NOT NULL,
        InheritAutomaticResize bit DEFAULT ((0)) NOT NULL,
        RedirectClipboard bit DEFAULT ((0)) NOT NULL,
        InheritRedirectClipboard bit DEFAULT ((0)) NOT NULL,
        RdpVersion varchar(10),
        InheritRdpVersion bit DEFAULT ((0)) NOT NULL,
        VmId varchar(100),
        UseVmId bit,
        UseEnhancedMode bit,
        InheritVmId bit,
        InheritUseVmId bit,
        InheritUseEnhancedMode bit
) 

CREATE TABLE [dbo].[tblRoot] (
        [Name] [varchar] (2048) NOT NULL ,
        [Export] [bit] NOT NULL ,
        [Protected] [varchar] (4048) NOT NULL ,
        [ConfVersion] [float] NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[tblUpdate] (
        [LastUpdate] [datetime] NULL
) ON [PRIMARY]
GO
