### ISSUE TITLE
Unable to import connection xml file exported from portable version 1.75 Beta

### ISSUE THREAD

**Issue by vivekbksingh** [mRemoteNG/mRemoteNG#412]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
There was a bug in that version when seeializing the export file. Check the
exported xml and make sure that export="true" then try the import again.

**Comment by vivekbksingh** [comment]
Thanks, it is working now
