### ISSUE TITLE
When adding new connection, don't have focus, no editable, need to rename.

### ISSUE THREAD

**Issue by MartinY** [mRemoteNG/mRemoteNG#413]
When one new conecction added, don't have focus, i need to rename to edit label.

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 RC 1  |

**Comment by kmscode** [comment]
@MartinY - could you please clarify this, and/or provide the exact sequence that you perform, the results and the expected/desired results? Possibly with annotated screen shots?

**Comment by sparerd** [comment]
I think this is the same as #479. I'll close this one as the duplicate since we have a PR open on the other.

**Comment by kmscode** [comment]
@sparerd - agreed.
