### ISSUE TITLE
Copy Paste from clipboard doesn't work in ssh/rdp session windows

### ISSUE THREAD

**Issue by madushan1000** [mRemoteNG/mRemoteNG#415]
<-- Bug -->
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 RC 1  |

Copy Paste from clipboard doesn't work in ssh/rdp session windows.
I can't Ctrl-C/Ctrl-V from any external window (eg. Notepad) to mRemoteNG session windows (checked for SSH/RDP sessions)

**Comment by maconstantin-bbm** [comment]
Isn't this supposed to work with just right click?

**Comment by madushan1000** [comment]
duplicate of #312

**Comment by cawoodm** [comment]
I looked at #312 but don't see the resolution: `Ctrl+V` does not work in an SSH session in mRemoteNg to paste - though `Shift+Ins` and `Right-Click` do - is there any way to configure this?

**Comment by RSKothari** [comment]
I'm not sure why this issue is closed. Highlighting enables us to copy and paste on the same session but does not get copied to the clipboard.

**Comment by ResearchRobert** [comment]
Within putty:

1. Under Category, select Window → Selection.
2. Set Ctrl + Shift + (C,V) to 'System clipboard'.
    _Also a great opportunity to disable mouse paste if you find that annoying..._
3. Under Category, select Session.
4. Select 'Default Settings' from the saved sessions list, and then click **Save**.
5. Close and reopen PuTTY to confirm your default settings have been updated.

If you are using individualized session preferences for different host session:

1. Load each session prior to making a change.
2. Save each session prior to making a change.

**Comment by simonai1254** [comment]
> I'm not sure why this issue is closed. Highlighting enables us to copy and paste on the same session but does not get copied to the clipboard.

This issue is not caused by mRemoteNG, but it's how PuttyNG (a fork of Putty), an external utility used to do the ssh connegtions, behaves. As @ResearchRobert pointed out this can be done by tuning the Putty settings, but has nothing to do with mRemoteNG to not work correctly. Therefore this issue will remain closed.
