### ISSUE TITLE
Feature Request: Ability to Enable/Disable Clipboard Sharing 

### ISSUE THREAD

**Issue by kainz0r** [mRemoteNG/mRemoteNG#416]
Hello - mRemoteNG is my favorite Remote Desktop client! Thanks for all the work of contributors for this project, it's much appreciated.

Would it be possible to request adding a control for Clipboard Sharing functionality? There's frequently times where I don't want to accidentally copy/paste sensitive information out of systems I'm working on, however I'm unable to disable this functionality.

If there's a way to do this already that I might have missed however, let me know.

**Comment by sparerd** [comment]
This may be possible by creating a setting to toggle the IMsTscAdvancedSettings.DisableRdpdr property. The downside is that this seems to also disable printer redirection along with the clipboard.

More details:
https://msdn.microsoft.com/en-us/library/aa381808(v=vs.85).aspx

**Comment by Deviruchi1** [comment]
I also vote for this feature.  Just now have automation agents running in RDP sessions, and when open multiple RDP sessions to check, they immediately share clipboard and interfering each other clipboard data.
So disabling clipboard sharing is necessity for me.

**Comment by balooka** [comment]
Same need here, using remote desktop to run some automation script which does heavy usage of clipboard. the fact that it is synced with my local clipboard means I cannot use mremoteng for this purpose, going back to mstsc.exe due to this.

Disabling printer redirection is a non issue in my case (as would be for most people needing this option I suspect)

**Comment by sparerd** [comment]
This feature will be avialable in v1.77. Thanks to @CrAbelleira for providing the pull request!

**Comment by kmscode** [comment]
Closing as this was merged via #951

**Comment by Aidolii** [comment]
Where is this for the VNC protocol?
