### ISSUE TITLE
Unable to send keys combination to mRemoteNG

### ISSUE THREAD

**Issue by katnissExpert** [mRemoteNG/mRemoteNG#418]
Whenever i press Windows+R - mRemoteNG doesn't pick it up.

May i know how i can resolve this ?

**Comment by sparerd** [comment]
I'm not able to replicate the issue. Can you give me some more details? Did you have any connections open? If so, which connection was currently active on the screen? Do you know which portion of the application had focus?

**Comment by katnissExpert** [comment]
Hi, thanks for responding. In other words when i open an remote session (RDP) and try to press i.e Windows button+R - my RUN will only pop on my local machine but not one on mRemoteNG.

**Comment by kmscode** [comment]
Do you have Redirect -> Key Combinations set to yes in that connections config?

![image](https://cloud.githubusercontent.com/assets/16654335/23513557/745f39ec-ff32-11e6-8d62-2754bef687cc.png)


May the odds be ever in your favor. 😄

**Comment by katnissExpert** [comment]
my version is 1.74.6023.15437

**Comment by kmscode** [comment]
I just loaded up 1.74 and it's there for me.

Please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

What OS are you running?

**Comment by katnissExpert** [comment]
Windows 10. Loaded 1.75. still cant see it.

**Comment by katnissExpert** [comment]
i uninstall and delete appdata finally have the option.

now i keep getting this

![image](https://cloud.githubusercontent.com/assets/26075545/23538573/368bca9e-000f-11e7-81ba-848c88dfaa28.png)

**Comment by kmscode** [comment]
Can you click details and provide me with the info about the crash (copy and paste or screen shot - need the stack trace to review further)? As well as the mremoteng.log (if it gets generated)?

Thanks.

**Comment by katnissExpert** [comment]
somehow it miraculously works fine now without any errors. thank you all

**Comment by umesh2385** [comment]
Thanks a lot. This saved a lot of time for me
