### ISSUE TITLE
Connection info name is garbled after save to sqlserver

### ISSUE THREAD

**Issue by ysqi** [mRemoteNG/mRemoteNG#419]
|item|version|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.74.6023.15437  |

i found sqlserver table  tblcons.name is garbled ,after save connection item . and my connection'name is Chinese.  e.g  Name=`服务器(Server)`

**Comment by ysqi** [comment]
bug from help document SQL Table creation Script, need remote Collate setting by default.
```sql
[Name] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
```

**Comment by sparerd** [comment]
Thanks for the report @ysqi we will get this updated

**Comment by sparerd** [comment]
Script has been updated. All `COLLATE SQL_Latin1_General_CP1_CI_AS` have been removed
