### ISSUE TITLE
Export doesnt remove properties 

### ISSUE THREAD

**Issue by TehDuffman** [mRemoteNG/mRemoteNG#427]
Using 1.75 (and RC's before it) and I export my MRemote file and uncheck all options under Export Properties. When I open the file in MRemote or text editor all usernames, passwords and other properties are not removed and are still in the file. I know this used to work on 1.72. I have tried this with encrypted and non-encrypted files.
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 |

**Comment by sparerd** [comment]
Resolved the issue. This fix will be available in the 1.75 hotfix 1 release that will be released in a few days.
