### ISSUE TITLE
High memory usage?

### ISSUE THREAD

**Issue by orangeredbrown** [mRemoteNG/mRemoteNG#432]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |
Running version 1.75.6269.29939 on Win 7 x64. Seeing high RAM usage, was told to post here from reddit. Can provide any details necessary. I typically use this for RDP sessions, and for the most part have < 10 RDP sessions running concurrently, but I see a lot of RAM usage (or at least, in my opinion, a lot), so I was wondering if there was something going wrong on my system, or some sort of a leak. Right now with 8 fresh RDP sessions open, mRemoteNG.exe is using 1.25gb ram. This seems excessive to me, but I could be wrong because I don't know how the program runs on the back-end. KMSCode stated they were having a much smaller RAM footprint than myself. Let me know if there is anything I can do to test/help with this. Or of this is just how it is, which is fine too. Thanks for a great program.

**Comment by kmscode** [comment]
The first thing that I would recommend is disabling "Cache Bitmaps" on all RDP sessions. This was known to use more memory and (in previous versions) limit the total number of RDP sessions that could be active at one time. 

It's possible that lowing the resolution to 15-bit may help as well (without making it look noticeably different).

At 1.25 gigs and 8 RDP sessions, your looking at an average of 160mb per session. Which is higher than what I've see on my system. I'm running Windows 10 x64 with the latest .NET framework. While not required, you may want to ensure that you have the latest .NET framework installed in case there are better optimizations in the later versions...

In addition, as it's a .NET application, looking into some more user friendly ways to troubleshoot this, there might not really be much for us to do from a code perspective. This is pretty clear and informative:  http://stackoverflow.com/questions/223283/net-exe-memory-footprint

Being as there were multiple complaints about memory usage on Reddit, we may need to do something better to debug these scenarios. This may require additional build options and/or tools to to be run on the problem systems.

[One such option](https://msdn.microsoft.com/en-us/library/dn342825.aspx) would require us to change the minimum framework version to 4.5 - which shouldn't be a problem for most people, but Windows 7 ships with 3.5 if I recall correctly. We currently require 4 (as we use some methods introduced in 4), so the added requirement for 4.5 would annoy some users...

**Comment by jcefoli** [comment]
@kmscode @dsparer This came up before... I understand that you want to compile the app against an older framework so mRemoteNG works out of the box on older versions of Windows. However, if there are optimizations which will make the app run better and if you want to be able to use C#5.0, I think we should consider upgrading. If you look at the audience of mRemoteNG users, most are IT professionals, tech people or developers. They should know how to install the latest version of .NET if they don't have Windows 10/Server 2016. (Although considering many users you'd be surprised). You already need to install  hotfixes in a specific order to get this working on Windows 7, so what's the difference?

**Comment by kmscode** [comment]
@jcefoli noted and 100% valid points!  I think going to .net 4.5 might be through way to go, but I need to do a but more research.

**Comment by kmscode** [comment]
Some great test results/details from another user reported via Gitter:
>I did some tests after reading about the RAM usage: it seems that connections to 2012r2 needs double the RAM than connections to 2008r2 (don't know why). In overall, 10 connections used 800MB. The same time my running Firefox with a bunch of open tabs used 1GB (!). Running RDP directly uses 270MB for only one connection to a 2012r2 server: i don't think that mremoteng has a memory problem... 

There were some problems when making multiple connections to 2012+ systems that were resolved in 1.74:
https://mremoteng.atlassian.net/browse/MR-451
https://mremoteng.atlassian.net/browse/MR-582

It's highly unlikely that we'll be able to do much since we're using the MS libraries for making the RDP connections. But still there might be some minor optimizations that we can do (and should look into).

**Comment by kmscode** [comment]
Closing this one out. Haven't seen or heard any other memory relating complaints in a while. All of my testing has been very reasonable. The current 4.6 .Net target (vs 4.0 when this was originally filed) includes Garbage Collection improvements.

**Comment by orangeredbrown** [comment]
Thanks Sean. I agree, the latest versions have been great. Have not had any
noticeable memory leakage even with a bunch of tabs open. Great job.

Andy
