### ISSUE TITLE
App crashes with NullRefException on click in empty tree area

### ISSUE THREAD

**Issue by jo-me** [mRemoteNG/mRemoteNG#433]
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.6269.29939  |

When you click in the empty area in the connection window, the app crashes with a NullReferenceException.

Stacktrace:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei mRemoteNG.UI.Controls.ConnectionTree.OnMouse_SingleClick(Object sender, MouseEventArgs mouseEventArgs)
   bei System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   bei System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by kmscode** [comment]
Duplicate of #422 a new build will be released next week that includes the fix.
