### ISSUE TITLE
1.75 hf1 unable to open password protected connections file

### ISSUE THREAD

**Issue by jtown84** [mRemoteNG/mRemoteNG#440]
I was initially running 1.75RC1 While running this I set a password on my connections file.
I ran into an issue where the program would no longer launch giving errors in the application log in windows.  I then updated to 1.75 Hotfix1 https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix1
This allowed the application to launch, however my password is not accepted.
Has anyone seen this or know how to remove a password from a connections file?

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 RC 1  || 1.75 HF1  |

**Comment by kmscode** [comment]
@sparerd Anything thoughts on this one?

**Comment by sparerd** [comment]
@jtown84 Could you provide the mremoteng.log file (or at least the last few entries from it)?

Also, have you tried loading a backup?

**Comment by jtown84** [comment]
I'll provide the backup as soon as I am able to.  (not at the computer right now)  I did try several backups, without help.

**Comment by sparerd** [comment]
Ok, hopefully the log file has some details about what happened.

**Comment by sparerd** [comment]
I'm going to close this issue since it is pretty old. @jtown84 feel free to reopen if necessary
