### ISSUE TITLE
Error listing PuTTY-stored sessions

### ISSUE THREAD

**Issue by jroosen** [mRemoteNG/mRemoteNG#442]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7000.19194 |
When PuTTY connection list contains session names with spaces (eg. something like "Server01 (My Host)"  ) those connections aren't listed.
When PuTTY sessions are modified within PuTTY while mRemoteNG is running, after appying a new entry to PuTTY's session list mRemoteNG connection tab starts a funny behavior: It lists the missing PuTTY sessions below the existing ones, then clears them from display, repainting them and so on. This looks like all those missing sessions are rolled down at the end of mRemoteNG's putty list, then roll them away from scren and then from the start. This looping lasts for an estimated minute after the last change to session list in PuTTY, then this behaviour stops leaving only those session entries in the list that don't contain spaces. The only exception here is the PuTTY Default Session which is showed all the time. I can not remember that the Default Session was listed in old versions of mRemoteNG.

**Comment by sparerd** [comment]
Scheduling for 1.76

**Comment by sparerd** [comment]
Moved the fix up in the schedule - we will release this with 1.75 hotfix 5 (should be this week)

Resolved in commit 1520b8b
