### ISSUE TITLE
Not saving to SQL DB

### ISSUE THREAD

**Issue by tommybuck** [mRemoteNG/mRemoteNG#448]
Trying to save connections to SQL but its not saving anything. I have data reader and writer rights on the database.

Windows 8.1 x64
SQL Express 2005 SP4
mRemoteNG 1.75.7000.19194
SQL script from help file.

Can you provide a test SQL file that I can import to SQL just to test the opening/reading of the database part of the program?

**Comment by sparerd** [comment]
It just so happens I was looking into this today while trying to finish up #408 

I think I have a fix ready. I'll release it on the `Development` update channel today if you'd like to test it out.

**Comment by sparerd** [comment]
A fix is now available on the `Development` channel. Please let me know if this resolves the issue

**Comment by tommybuck** [comment]
Nope still not working.

**Comment by sparerd** [comment]
@tommybuck Can you run the following sql on your mRemoteNG db and provide the output here?

```sql
select COLUMN_NAME,ORDINAL_POSITION
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'tblCons'
```

**Comment by tommybuck** [comment]
COLUMN_NAME	ORDINAL_POSITION
ID	1
ConstantID	2
PositionID	3
ParentID	4
LastChange	5
Name	6
Type	7
Expanded	8
Description	9
Icon	10
Panel	11
Username	12
DomainName	13
Password	14
Hostname	15
Protocol	16
PuttySession	17
Port	18
ConnectToConsole	19
UseCredSsp	20
RenderingEngine	21
ICAEncryptionStrength	22
RDPAuthenticationLevel	23
RDPMinutesToIdleTimeout	24
RDPAlertIdleTimeout	25
Colors	26
Resolution	27
DisplayWallpaper	28
DisplayThemes	29
EnableFontSmoothing	30
EnableDesktopComposition	31
CacheBitmaps	32
RedirectDiskDrives	33
RedirectPorts	34
RedirectPrinters	35
RedirectSmartCards	36
RedirectSound	37
SoundQuality	38
RedirectKeys	39
Connected	40
PreExtApp	41
PostExtApp	42
MacAddress	43
UserField	44
ExtApp	45
VNCCompression	46
VNCEncoding	47
VNCAuthMode	48
VNCProxyType	49
VNCProxyIP	50
VNCProxyPort	51
VNCProxyUsername	52
VNCProxyPassword	53
VNCColors	54
VNCSmartSizeMode	55
VNCViewOnly	56
RDGatewayUsageMethod	57
RDGatewayHostname	58
RDGatewayUseConnectionCredentials	59
RDGatewayUsername	60
RDGatewayPassword	61
RDGatewayDomain	62
InheritCacheBitmaps	63
InheritColors	64
InheritDescription	65
InheritDisplayThemes	66
InheritDisplayWallpaper	67
InheritEnableFontSmoothing	68
InheritEnableDesktopComposition	69
InheritDomain	70
InheritIcon	71
InheritPanel	72
InheritPassword	73
InheritPort	74
InheritProtocol	75
InheritPuttySession	76
InheritRedirectDiskDrives	77
InheritRedirectKeys	78
InheritRedirectPorts	79
InheritRedirectPrinters	80
InheritRedirectSmartCards	81
InheritRedirectSound	82
InheritSoundQuality	83
InheritResolution	84
InheritUseConsoleSession	85
InheritUseCredSsp	86
InheritRenderingEngine	87
InheritICAEncryptionStrength	88
InheritRDPAuthenticationLevel	89
InheritRDPMinutesToIdleTimeout	90
InheritRDPAlertIdleTimeout	91
InheritUsername	92
InheritPreExtApp	93
InheritPostExtApp	94
InheritMacAddress	95
InheritUserField	96
InheritExtApp	97
InheritVNCCompression	98
InheritVNCEncoding	99
InheritVNCAuthMode	100
InheritVNCProxyType	101
InheritVNCProxyIP	102
InheritVNCProxyPort	103
InheritVNCProxyUsername	104
InheritVNCProxyPassword	105
InheritVNCColors	106
InheritVNCSmartSizeMode	107
InheritVNCViewOnly	108
InheritRDGatewayUsageMethod	109
InheritRDGatewayHostname	110
InheritRDGatewayUseConnectionCredentials	111
InheritRDGatewayUsername	112
InheritRDGatewayPassword	113
InheritRDGatewayDomain	114
LoadBalanceInfo	115
AutomaticResize	116
InheritLoadBalanceInfo	117
InheritAutomaticResize	118

**Comment by sparerd** [comment]
Thanks for that - think I've found a better solution for the problem now. I'll push another update.

**Comment by sparerd** [comment]
Another update was pushed to the `Development` channel. Hoping this will do it.

The previous code seemed to be relying on column ordering for doing bulk DB inserts. We're now matching up column names which should be much safer

**Comment by tommybuck** [comment]
confirmed as working now :)

**Comment by sparerd** [comment]
Awesome! Glad to hear :)
