### ISSUE TITLE
Passwords in SQL encrypted - feature request

### ISSUE THREAD

**Issue by tommybuck** [mRemoteNG/mRemoteNG#449]
Can you encrypt the passwords stored in SQL please?

**Comment by sparerd** [comment]
Yep, we can definitely do that.

**Comment by sparerd** [comment]
In fact, this may be taken care of in v1.76 anyways since we're redoing the credential management system.

**Comment by sparerd** [comment]
Related to #208

**Comment by tommybuck** [comment]
👍

**Comment by tommybuck** [comment]
Can I give this issue a push again please?

**Comment by lindazhi** [comment]
Can I give this issue a push again please? we also have this problem.

**Comment by sparerd** [comment]
v1.77 will be a good time to tackle this since we will be finally implementing the credential manager feature. We can add encrypted shared passwords stored in the DB at the same time.

**Comment by sparerd** [comment]
I've had to do some db work for a v1.76 hotfix, so I'm going to pull this ahead to v1.76 as well

**Comment by sparerd** [comment]
This will be available in v1.76.12

**Comment by cguadall** [comment]
@sparerd Where & How is stored the encryption key for SQL Entries? Any doc pointing that?
