### ISSUE TITLE
send CTRL+ALT+END

### ISSUE THREAD

**Issue by kal10bach** [mRemoteNG/mRemoteNG#453]
via rdp CTRL+ALT+END can be used to send CTRL+ALT+DEL to the host (start task manager and so on)
is there a way to do this within mremoteng?
thanx, georg

**Comment by kmscode** [comment]
You have to set Redirect -> Key Combinations to yes and this will work.

**Comment by jason-delaplain** [comment]
Mine is set to "Yes" for Key Combinations, and it's not working.  I made sure I clicked in the window, etc. I'm on 1.76.20 (2019-04-12).

**Comment by jason-delaplain** [comment]
Adding comment to say that "Ctrl + Alt + End" works for this purpose, but I didn't find it easily.

**Comment by iraklis10** [comment]
> Adding comment to say that "Ctrl + Alt + End" works for this purpose, but I didn't find it easily.

Thanks for that - was pulling my hair out
