### ISSUE TITLE
Problem with CredSSP settings after upgrade to version 1.75 hotfix 1

### ISSUE THREAD

**Issue by gielu** [mRemoteNG/mRemoteNG#455]
Hi,

after upgrading to version 1.75 hotfix 1 when you set a global CredSSP option to False in configuration file application still starting quick connect and every new connection with CredSSP setting to true.

**Comment by kmscode** [comment]
What version were you using previously?

**Comment by gielu** [comment]
1.74.6023.15437

**Comment by nmat** [comment]
I think this can be closed because it is documented with information.

**Comment by farosch** [comment]
@gielu Can you please explain this a little more detailed?
We do not have a
> global CredSSP option

**Comment by farosch** [comment]
Closed due to OP not responding
