### ISSUE TITLE
Issue with connecting to sql server and then trying to import Connections (crashing)

### ISSUE THREAD

**Issue by cagosti** [mRemoteNG/mRemoteNG#464]
I can setup to a SQL server however when i try to import connections or try to save connections, mremote crashes out and i have to reopen from a config file.

I have attached the mremote log file 
I have also attached eve
[mRemoteNG.zip](https://github.com/mRemoteNG/mRemoteNG/files/857678/mRemoteNG.zip)
[Mremote Crashing.zip](https://github.com/mRemoteNG/mRemoteNG/files/857682/Mremote.Crashing.zip)

ntviewer log

**Comment by cagosti** [comment]
This hasn’t resolved the issue for me I still get a crashing issue when importing connections, thanks for the prompt response though

Chris Agostini
Technical Support Engineer, Invu

[invu-logo]<http://www.invu.net/>
Providing Document Management<http://www.invu.net/solutions/document-management> (eDM), Accounts Payable<http://www.invu.net/solutions/accounts-payable-ap> (AP) and Purchasing<http://www.invu.net/solutions/purchasing> solutions.

t: 01604878010
e: chris.agostini@invu.net<mailto:chris.agostini@invu.net>
w: www.invu.net<http://www.invu.net/>
Follow Us: LinkedIn<https://www.linkedin.com/company/82884?trk> | Facebook<https://www.facebook.com/InvueDM> | twitter<https://twitter.com/invuECM>

**Comment by sparerd** [comment]
Found the issue.

This was happening due to a small bug in the import feature where parent references weren't being updated correctly. Resolved in commit `d49d58f7f85afcc2642f07ce4e16fdc2abf73ce1`

This fix will be released today in version 1.75.7003 on the `development` update channel.

**Comment by cagosti** [comment]
Is there anyway of stopping the auto refresh when connected to the sql server?

Chris Agostini
Technical Support Engineer, Invu

[invu-logo]<http://www.invu.net/>
Providing Document Management<http://www.invu.net/solutions/document-management> (eDM), Accounts Payable<http://www.invu.net/solutions/accounts-payable-ap> (AP) and Purchasing<http://www.invu.net/solutions/purchasing> solutions.

t: 01604878010
e: chris.agostini@invu.net<mailto:chris.agostini@invu.net>
w: www.invu.net<http://www.invu.net/>
Follow Us: LinkedIn<https://www.linkedin.com/company/82884?trk> | Facebook<https://www.facebook.com/InvueDM> | twitter<https://twitter.com/invuECM>

**Comment by sparerd** [comment]
Currently, no

**Comment by kmscode** [comment]
Closing issue as this was fixes in build 7003
