### ISSUE TITLE
VNC, Username section

### ISSUE THREAD

**Issue by Numufar** [mRemoteNG/mRemoteNG#465]
Hi to all.
Please add in VNC field "Username" section.
If VNC server set up for domain auth, there no way to connect throught mRemoteNG.
Thanks.

**Comment by tjgng** [comment]
More or less this: https://github.com/mRemoteNG/mRemoteNG/issues/444

**Comment by farosch** [comment]
Closing as duplicate of #444. Please follow this issue for updates.
