### ISSUE TITLE
Installer still failing on Win7 for updates

### ISSUE THREAD

**Issue by Ketrel** [mRemoteNG/mRemoteNG#466]
With the latest stable installer from your site
It tells me that I need a specific KB, which Windows says is already installed.

http://i.imgur.com/KE4BBdX.png

**Comment by kmscode** [comment]
@Ketrel 

Check out this FAQ: https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#classnotreg

>A common issue is that KB2574819 is either missing or has been installed after KB2592687. They must be installed in the correct order. If you do not have KB2574819, follow these instructions:
>
>    Uninstall KB2592687
>    Install KB2574819
>    (Re)Install KB2592687
>    Reboot your machine

**Comment by Ketrel** [comment]
1. KB2574819 is present and cannot be uninstalled.
2. Once uninstalled KB2592687 cannot be reinstalled: http://i.imgur.com/JAEQU7D.png

**Comment by Ketrel** [comment]
I should point out that even with KB2592687 uninstalled, if I use the ignoreprerequisites option, it installs and runs just fine.

What exactly would that be required for?

**Comment by sparerd** [comment]
Do you have KB2923545 installed? 

KB2592687 (RDP 8.0) *or* KB2923545 (RDP 8.1) are required for using RDP connections.

**Comment by Ketrel** [comment]
KB2592687: Not installed, not installable  
KB2574819: Installed, not removable  
KB2923545: Installed, have not tried to remove

If KB2923545 can satisfy KB2592687 (and prevents the re-installation) perhaps the installer should check for its presence and ignore KB2592687's status if it's installed?

**Comment by sparerd** [comment]
The installer should be looking for KB2574819 and then either KB2592687 or KB2923545.

Can you run the following powershell command and paste the results here?

```powershell
Get-HotFix -Id "KB2574819","KB2592687","KB2923545" | select -Property "HotFixID","InstalledOn"
```

**Comment by Ketrel** [comment]
Output is

`Get-HotFix : This command cannot find hot-fix on the machine 'localhost'. Verify the input and Run your command again.
At line:1 char:11
+ Get-HotFix <<<<  -Id "KB2574819","KB2592687","KB2923545" | select -Property "HotFixID","InstalledOn"
+ CategoryInfo          : ObjectNotFound: (:) [Get-HotFix], ArgumentException
+ FullyQualifiedErrorId : GetHotFixNoEntriesFound,Microsoft.PowerShell.Commands.GetHotFixCommand`

**Comment by kmscode** [comment]
@sparerd 

Looks like KB2830477 is the RDC v8.1 update. [Reference](https://blogs.technet.microsoft.com/enterprisemobility/2013/11/12/remote-desktop-protocol-8-1-update-for-windows-7-sp1-released-to-web/), which links to https://www.microsoft.com/en-us/download/details.aspx?id=40986 ("To download the packages, go to Remote Desktop Protocol 8.1 update for Windows 7 SP1")

So we should be checking for KB2574819 && (KB2592687 || KB2830477) during the installation.

KB2923545 looks like it's a fix for a fix and the title/name of the update is deceiving... 

😕

**Comment by sparerd** [comment]
yep, doing some testing for it and im seeing the same. component check works fine when only KB2574819 and KB2830477 are installed

**Comment by sparerd** [comment]
should be able to change the install checks pretty quickly - hopefully it'll be done and tested today

**Comment by sparerd** [comment]
Seems to be working well. We now look for (KB2574819 && (KB2592687 || KB2830477))

@kmscode what do you think of including this with hotfix5?

**Comment by kmscode** [comment]
@sparerd 
If you're comfortable with the changes, this would be great for inclusion in hotfix5!

I think we'll need to update FAQs/Prereq documentation also since we mention KB2923545 as opposed to KB2830477.

**Comment by sparerd** [comment]
Sounds good - let's include this. Yep, the wiki and a few other places will need to be updated

**Comment by kmscode** [comment]
Fix was included in hotfix5 as a pre-release (see commit: 547ec3cb3a03381f1e6c3e1e9c76d42a4868bdc9). Hotfix8 is available as a final release:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8

**Comment by Ketrel** [comment]
This is still failing in Hotfix8

http://i.imgur.com/LGJLM7v.png

**Comment by sparag** [comment]
Please check the system architecture and make sure you are downloading proper updates either for -x86 or -x64 machines.

We had same problem on WIN7x64 bit machine and none of the update was readily available.
We downloaded Updates for Windows 7 for x64-based Systems and installed in given order.
First Install KB2574819 and then Install KB2592687. Reboot the machine and then installed latest available stable mRemoteNG.

Hope it helps.

**Comment by Ketrel** [comment]
I'm on x64 Win 7, and that makes no difference.
