### ISSUE TITLE
default properties: custom panel name is not saved

### ISSUE THREAD

**Issue by sumulu** [mRemoteNG/mRemoteNG#468]
We talk about default properties of connections. The setting which you make under "Display --> Panel" is not saved, if I restart the program. Looks like this setting is overwritten by default language of windows-user profile on every program start. Change of default Icon is saved. My problem is that I saved all my connections under one name. If I use quick connect bar, I got a new panel which I don't want.

|Operating system | Windows 7 Ultimate x64 |
|mRemoteNG version| 1.75 hotfix 1  |

**Comment by sparerd** [comment]
The `Panel` property of the default connection record is now saved to settings. This will be released in the next major release v1.76
