### ISSUE TITLE
mRemoteNG installation problem

### ISSUE THREAD

**Issue by omolaski** [mRemoteNG/mRemoteNG#473]
Can someone please help me with this problem? I'm trying to install mRemote and this is the error I get below:

mRemoteNG require RDP 8.0 or higher to run. Windows 7 users will need to install KB2592687

**Comment by kmscode** [comment]
See the [Prerequisites page](https://github.com/mRemoteNG/mRemoteNG/wiki/Prerequisites#full-list-of-required-windows-updates-for-windows-7--server-2008-clients) for more info...


You can also check out this FAQ:
https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#classnotreg

While the question isn't the same, the solution is. You need to ensure that the appropriate windows KBs are installed.

**Comment by kmscode** [comment]
closing due to no response
