### ISSUE TITLE
Configurable backups

### ISSUE THREAD

**Issue by benwa** [mRemoteNG/mRemoteNG#474]
I would like to be able to configure:
* how often a backup is performed (daily, weekly, only on setting change)
* how many backups are retained
* where the backups are saved

**Comment by benwa** [comment]
In addition to this, though a bit specific to my setup:
I keep the config file in a network share that get's backed up to AWS S3, which does versioning on it's own (this may apply to other backup software too).  By having the filename include the date, it creates a bunch of files in S3.
It's not the worst problem, but if I could also chose the backup naming scheme, then I could do something like `backup1`, `backup2`, and `backup3` and have them rotate.

**Comment by vmario89** [comment]
hi. I think the same about backing up files. because i use mremote really often it messed my directory with too much backup files of connection settings. Each file is around 1~2 mb which easily generates hundreds of megabytes in some days.

**Comment by sparerd** [comment]
I plan on adding options to control the backup settings from the regular Options pages in the next major release (v1.77). That work will be pretty quick and easy.

**Comment by padillah** [comment]
I'd like to help with this but I can't assign it to me. What should I do?

**Comment by sparerd** [comment]
Thanks for offering to help, @padillah! Here's a rough list of what would need to be done:
- Update the `Ui\Forms\OptionsPages\ConnectionsPage` and add controls for the desired settings.
   - Keep in mind that this page will need to work well on multiple monitor scaling settings. Use TableLayoutPanels for any sort of complex layout design.
   - Any UI text should be placed in the `Resources\Language\Language.resx` file so our translators can provider localizations. Bind the text to your controls in the `public override void ApplyLanguage()` method.
   - Hook up the controls to the relevant `mRemoteNG.Settings` entries in the following methods:
      - `public override void LoadSettings()`
      - `public override void SaveSettings()`
- You may need to update the `FileBackupCreator` class to support some of these settings. This class is responsible for adding backup support to file-based saving actions.

If you have any questions, I'd be happy to help!

**Comment by padillah** [comment]
Hey, QQ: I'm trying to set the text of a label to a Resource string but the
designer keeps changing it back to the original text.

Any example of how to do this and make it stay?

Tom P.

**Comment by padillah** [comment]
Well, I found this...
https://stackoverflow.com/questions/1843051/winforms-strings-in-resource-files-wired-up-in-designer

... which suggests there is no way to use a project level resx file for all
win forms.

I don't know how you feel about this. Let me know how you want to proceed.

Tom P.

**Comment by sparerd** [comment]
@padillah I can't see your comments anymore, so not sure if you've deleted them/figured out the answer to your question. If not, take a look at the code-behind for the ConnectionsPage form. You can assign the localization text to form elements in the `ApplyLanguage()` method in that .cs file.

**Comment by padillah** [comment]
Yeah, sorry. I found it. Forgive me for being jumpy, this is my first foray into Open Source and I'm a bit nervous. Thanks for the patience.

**Comment by sparerd** [comment]
Don't worry, you'll be just fine :)

**Comment by padillah** [comment]
Ready for review (sorry about the extra PR)

**Comment by LIyoai** [comment]
Configurable Backups #1476
