### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by skyrobber** [mRemoteNG/mRemoteNG#476]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

SSH to a Linux machine only gives you up to 26 lines on the screen. Until you restore/maximize the screen then it gives you the full screen on the terminal.

**Comment by creopard** [comment]
I can't verify this using 1.75 hotfix 1.
SSH to a linux host from Win7 x64 with mRemoteNG (already) in fullscreen does not seem to have this issue.

What does your PuttyNG-session settings in tab "Window" look like?

**Comment by farosch** [comment]
Closed as OP is not responding and three users (including me) weren't able to reproduce this.
