### ISSUE TITLE
New nodes in connection tree should start in editing mode

### ISSUE THREAD

**Issue by pfjason** [mRemoteNG/mRemoteNG#479]
When right clicking Connections => New Node or New Folder the new item should start in editing mode so that it can be named immediately without additional clicks.

**Comment by sparerd** [comment]
Note for posterity: this is a regression from previous behavior.

**Comment by sparerd** [comment]
Accepted PR by @pfjason. This will be included in v1.76

**Comment by nordcore82** [comment]
This feature should have been added to 1.76 but is not in the alpha version that was released in dec.

**Comment by sparerd** [comment]
Found the issue - fix should be available in the next v1.76 alpha release
