### ISSUE TITLE
Importing RDG Files

### ISSUE THREAD

**Issue by TDMPro2K** [mRemoteNG/mRemoteNG#481]
I am unable to import my rdg file with all my servers on. 
It says import, but fails and says error. I am running rdcman 2.7 currently.
Is there a fix or a way around it?

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
The last version of RDCMan files that was supported was v2.2. We are hoping to add this feature in the next major release.

Closing as duplicate #225
