### ISSUE TITLE
Enable domain for protocol Ext. App

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#485]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 hotfix 1 |

When selecting Ext. App as protocol I can't configure a domain.
At the moment I need to set it to RDP, configure the domain, change the protocol to Ext. Apps and then I can use the variable %Domain% in the external tools.

**Comment by sparerd** [comment]
Yep we can do that - should be a pretty quick change.

**Comment by kmscode** [comment]
Tentatively scheduled for 1.76

**Comment by sparerd** [comment]
`Domain` is now available on connection records with protocol of Int App
