### ISSUE TITLE
Span - Multiple Monitors

### ISSUE THREAD

**Issue by g-pearl** [mRemoteNG/mRemoteNG#486]
Would like to be able to span across multiple monitors.  If this is possible I can not find any documentation and what settings I need to change/enable.

Thanks

**Comment by jcefoli** [comment]
This is the setting that would need to be added to mRemoteNG if available in the RDP libraries provided by Microsoft. I'd assume it'd be a boolean true/false option whether or not to use all monitors for full screen connections and the inheritance would work the same way as all other folders/features.

![image](https://cloud.githubusercontent.com/assets/6618013/24871232/f0978064-1de6-11e7-9110-06223926bc65.png)

**Comment by andrewsav-datacom** [comment]
Similar to https://github.com/mRemoteNG/mRemoteNG/issues/192

**Comment by heyfrank** [comment]
Has this been updated yet?

**Comment by kmscode** [comment]
Duplicate of #192

Please follow that issue for further update.
