### ISSUE TITLE
User.config in appdata local/roaming

### ISSUE THREAD

**Issue by crfiemme** [mRemoteNG/mRemoteNG#488]
mRemoteNG is installed on multi user environement (Terminal Server with Citrix Xenapp 6.5 in this case).
User profile is configured to roam. In this configuration, appdata/local content will be deleted at logoff.
Opening mRemoteNG, user.config stored (manually) in appdata/roamin will load correctly and all config are OK.
If you edit configuration using Tools/Options a new user.config is created in appdata/local (using running configuration parameters) and not in appdata/roaming.
Existing user.config stored originally in appdata/roamin will not be updated.
At Operating System user logoff the file is deleted because all appdata/local and subfolders are discarded in TS environement with roaming profiles.

|||
|--:|---|
|Operating system | Windows 2008 R2 x64 |
|mRemoteNG version| 1.75.7003 (2017-03-24)  |

**Comment by kmscode** [comment]
Duplicate. Please upvote/follow #414 for updates.
