### ISSUE TITLE
mRemoteNG + SQL + CSV - Supported or new request

### ISSUE THREAD

**Issue by jmoneste** [mRemoteNG/mRemoteNG#491]
Hello, I am trying to get a CSV imported into the SQL and then connect mRemoteNG to it.

Connecting mRemoteNG to SQL and saving connections work like a charm but I have more than 7000 connections on a CSV and a manual input will not be a viable option.

However when I try to import the CSV (which matches the columns) it fails with many errors one of them being that the ID column is read only. I tried leaving it blank or populated and it fails.

Windows 2008R2 + MS SQL 2008R2 mRemoteNG 1.74.6023.15437

If this is not supported still, can this be added to mRemoteNG as a feature request? 
File > Import > CSV

**Comment by jmoneste** [comment]
I made it work. NM.
The catch was the column ID should not be present in the CSV.
The columns PositionID and DateTime should be populated.

There will be errors saying Base64 character issues  (since the CSV has them in plain text)  when mremote reads the SQL DB and saves the DBit encrypts them. Just press "Enter" to all of those errors (I had more than 7000) and it will work.

**Comment by yilmazc** [comment]
Hello, 
can you show the columns used in the file please 
thanks you
