### ISSUE TITLE
Time for Backup File differed 2 houres to MEZ

### ISSUE THREAD

**Issue by peter-franken** [mRemoteNG/mRemoteNG#493]
Closing the mRemoteNG saves a Backup File like
**Filename.xml.20170407-1135075365.backup**.
The Time **1135** differed from the save time 2 houres.
I closed mRemoteNG at **1335**.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |
|mRemoteNG version| Prerelease v1.75.7003 (Hotfix 4) |

**Comment by sparerd** [comment]
resolved in commit 6dcef71

The backup code was using using UTC in the backup name. I've changed this to use local system time.

**Comment by rmcardle** [comment]
The reason this was using UTC is to ensure that the most recent backup is always the highest numbered. Using local time could cause this to not be the case if the time zone is changed, daylight savings time changes effect, or if multiple users in different time zones access the configuration file (some users share their configuration files on a server). I would recommend reverting this change.
