### ISSUE TITLE
Emails (translations@mremoteng.org) are not available.

### ISSUE THREAD

**Issue by gyuha** [mRemoteNG/mRemoteNG#499]
I want to create a translation file and send it but I do not have an email.
The forum can not log in. Is there any other way to pass the translation file?

**Comment by kmscode** [comment]
@gyuha you can submit a [Pull Request](https://github.com/mRemoteNG/mRemoteNG/wiki/Pull-Requests) against the Develop branch.

The language files can be found [here](https://github.com/mRemoteNG/mRemoteNG/tree/develop/mRemoteV1/Resources/Language)

**Comment by kmscode** [comment]
@sparerd 

I think we'll have to adjust the procedure for adding translations and update the [wiki](https://github.com/mRemoteNG/mRemoteNG/wiki/How-to-Help-Translating-mRemoteNG) accordingly.

**Comment by kmscode** [comment]
Wiki has been updated to note that we accept translations via pull requests or via e-mail to support@mremoteng.org
