### ISSUE TITLE
Reconnecting SSH automatically

### ISSUE THREAD

**Issue by NextBlaubeere** [mRemoteNG/mRemoteNG#500]
Hi,

Is it somehow possible to set an auto-reconnect feature?
I often reboot my devices via ssh, and then the connection is of course lost. in KITTY (based on putty) there is a feature which automatically reconnects the session if you press enter.

Would be cool to have that too in mRemote, without always right-clicking on the tab and pressing "reconnect".

greets

**Comment by jmoneste** [comment]
Hi,

You can set mremoteng to use Kitty as the default SSH handler and that will fix your request. I had that question as well.

**Comment by NextBlaubeere** [comment]
I looked into settings, but how do i do that?
there where i can set a "own putty path" ?

**Comment by jmoneste** [comment]
Tools > Options > Advanced
Use custom Putty path, point that to Kitty.
I moved the exe to the same install path as mremoteng.

![kitty](https://cloud.githubusercontent.com/assets/26974441/24917230/bffcc104-1e99-11e7-8792-111ad863fbb4.png)

**Comment by NextBlaubeere** [comment]
Ahh, thats so much better! Thank you. 👍 
Issue can be closed.
