### ISSUE TITLE
Connection icons

### ISSUE THREAD

**Issue by sierramike** [mRemoteNG/mRemoteNG#507]
Hello,

The icon choice feature is a nice added value, but it would be great if the icon could be shown in the connections tree also, as it is IMHO a great help identifying servers in the list. It could be just grayed out when not connected and coloured when connected, or get the "play/pause" sign smaller as a layer on top of the icon.

Otherwise thanks for the great tool I just discovered.

**Comment by sparerd** [comment]
We agree! Though there is a request for this already - follow #326 for updates. Glad you like the tool!

Closing as duplicate of #326.
