### ISSUE TITLE
Automatic Update Settings Popup

### ISSUE THREAD

**Issue by andyzib** [mRemoteNG/mRemoteNG#508]
|||
|--:|---|
|Operating system | Windows Server 2008 R2 |
|mRemoteNG version| 1.75.7000.19194
![mremoteng_automaticupdatesettings](https://cloud.githubusercontent.com/assets/1699232/25012447/2d518ca6-2036-11e7-9113-e789f0c57df9.png)
  |
Since updating to the latest stable release of mRemoteNG I'm getting the Automatic Updates Settings window appear every time mRemoteNG is launched. I suspect it's do to running in in a Citrix session where %APPDATA%\Local is discarded after every user session or mRemoteNG is writing a setting to another location that doesn't persist as we use Citrix Provisioning Services and any changes made are lost when the VM is rebooted as a result. So far I've been unable to figure out where the setting is being written and why it is not persisting between sessions.

**Comment by kmscode** [comment]
Setting is saved in user.config which is in C:\Users\[user]\AppData\**Local**\mRemoteNG\mRemoteNG.exe_Url_[randomstring]\[version]

This will be fixed in a future release... Reference #414 

Please following #414 for further updates.
