### ISSUE TITLE
Multiple data sources

### ISSUE THREAD

**Issue by adrianandreias** [mRemoteNG/mRemoteNG#51]
Feature suggestion: would be useful to have multiple data source (a few xml files, one or a few SQL connections etc.) opened at the same time in the left connections tree.
At the very minimum there should be the SQL data source and a local file since it's common to have some shared connections with your colleagues while you want to keep some private.

**Comment by Silent-Joker** [comment]
Can this be re opened as a request?  I would love to have multiple connection files open.  This way i can have my personal on encrypted and a share on with no passwords not encrypted and be open at the same time.
