### ISSUE TITLE
MremoteNG crash when I click in panel config

### ISSUE THREAD

**Issue by stufently** [mRemoteNG/mRemoteNG#510]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7003.25190 |

mRemoteNG crash every time when I click panel config, I can not edit my connections

**Comment by kmscode** [comment]
Please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) and any stack traces generated. Check the Windows Event logs (Application or System) for the stack traces if you didn't get prompted to show the details when the crash occurred.

**Comment by kmscode** [comment]
closing due to lack of response and cannot reproduce.
