### ISSUE TITLE
mRemoteNG corrupted parameter in external tool

### ISSUE THREAD

**Issue by bakemonoru** [mRemoteNG/mRemoteNG#517]
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 hotfix 1 (2017-03-06)  |

Problem: when using external program (Winbox) username or password are transferred incorrectly in some situations.

1. Settings for external app
![image](https://cloud.githubusercontent.com/assets/27729695/25132074/d777e86a-2450-11e7-9ffd-ec400b0a3245.png)
2. Settings for host 
![image](https://cloud.githubusercontent.com/assets/27729695/25132143/1c1ec63c-2451-11e7-8d77-5d700b7a9809.png)
3. And here the result:
![image](https://cloud.githubusercontent.com/assets/27729695/25132036/c270b672-2450-11e7-9603-01a1418ef262.png)

As you see, combination "a!" -> became "a^!" in username and in password field.

**Comment by kmscode** [comment]
This is working as designed. See:
https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools
