### ISSUE TITLE
Missing File->Load Connections menu option.

### ISSUE THREAD

**Issue by Kzorith** [mRemoteNG/mRemoteNG#519]
||| When trying to merge two connection files, I attempted an Import of one file into another.  It returned the following message:
----------
InformationMsg
4/19/2017 11:07:46 AM
You cannot import a normal connection file.
Please use File - Load Connections for normal connection files!
----------
This would be fine except there is no File -> Load Connections menu option.
Is the functionality to merge connection files not available yet?
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 alpha 3  |

**Comment by kmscode** [comment]
Looks like that might just be a "typo" in the message. You should have "Open Connections File..." in the file menu.

**Comment by Kzorith** [comment]
I do, but that's not what I want to do.  I don't want to simply open the connections file. I want to merge the connections file I have with another one.  I would have thought that Import would support that, but it does not.

The person who gave me the connection file, had just used Save As to create it, but perhaps we are using the wrong functionality and we should have used Export.
{checking}
Yes, if it's exported and then imported, that performs the functionality I was looking for.

So that leaves the question of the message.  You are correct that it should likely read File - Open Connections rather than Load Connections.

Might I suggest the message read:
You cannot import a normal connection file.  It can only be opened.
Please use File - Open Connections to open the file or File -Export to File to create entries that can be imported.

**Comment by kmscode** [comment]
Thanks for the confirmation. I will update the message. Scheduled for 1.76.

**Comment by sparerd** [comment]
We now no longer prevent importing normal mremoteng connection files. This error message should no longer show up.
