### ISSUE TITLE
Loadbalanceinfo and Azure Cloud Service

### ISSUE THREAD

**Issue by MilanDasek** [mRemoteNG/mRemoteNG#523]
Hello,

I have windows 10 and 1.75.7002.26449 of mremote

I am trying to connect to Azure CS using cookies:

LoadBalanceInfo: Cookie: mstshash=sometihing#sometinhg_IN_0

But doesn't work.

Can you please advise?

**Comment by kmscode** [comment]
Looks like someone else is having the same problem using the RDP ActiveX Control (which is what mRemoteNG does):
http://stackoverflow.com/questions/43433766/cannot-connect-to-azure-hdinsight-rdp-cluster-with-rdp-activex-control 

Per the [documentation](https://msdn.microsoft.com/en-us/library/aa381177(v=vs.85).aspx) you MUST specify \r\n at the end of your string:

```
Cookie: mstshash=sometihing#sometinhg_IN_0\r\n
```

**Comment by kmscode** [comment]
Also... Check the mRemoteNG.log for any exceptions that might start with the message "Unable to set load balance info."

**Comment by kmscode** [comment]
This was fixed via #829 and included in 1.76. Closing.
