### ISSUE TITLE
Bug: 1.75.7003 - PuTTY Saved Connections with spaces in name are not listed

### ISSUE THREAD

**Issue by dmorris68** [mRemoteNG/mRemoteNG#525]
Recently updated my 1.72 version at home to 1.75.7003. First thing I noticed was that my PuTTY Saved Connections menu had only a couple of entries. Looking further, I realize that except for "Default Settings" it's ignoring all PuTTY connections with spaces in their name. Many of my connections have spaces, for example "Home - qnap1" or "Home - fw1" and such. Version 1.74 at work does not have this issue, so it seems to have been introduced in 1.75. 

|Operating system | Windows 10 x64 b1703 |
|mRemoteNG version| 1.75.7003  |

**Comment by sparerd** [comment]
Resolved this under #442 - the fix will be released this week in hotfix 5.

**Comment by sparerd** [comment]
hotfix 5 released on the `development` update channel
