### ISSUE TITLE
mRemoteNG Crashes on windows server 2012

### ISSUE THREAD

**Issue by ikapoulas** [mRemoteNG/mRemoteNG#527]
Hello,

mRemoteng crashes on startup for windows server 2012.  

mremoteng version: 1.75.7003.25190
Windows server 2012

Please advise.
Best Regards 

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page.

Try deleting the user.config, if that doesn't help, provide the information as noted.

**Comment by ikapoulas** [comment]
Thanks a lot for your response.

I already tried to delete the config but the same issue. It open once and
if i close and re-open the application, the application crashes.

*Problem signature:*

  Problem Event Name:                        CLR20r3

  Problem Signature 01:                       mRemoteNG.exe

  Problem Signature 02:                       1.75.7000.19194

  Problem Signature 03:                       58bd9ee6

  Problem Signature 04:                       mscorlib

  Problem Signature 05:                       4.6.1087.0

  Problem Signature 06:                       583e5abb

  Problem Signature 07:                       321

  Problem Signature 08:                       10

  Problem Signature 09:                       System.ArgumentException

  OS Version:                                          6.3.9600.2.0.0.272.7

  Locale ID:                                             1033

  Additional Information 1:                  5861

  Additional Information 2:                  5861822e1919d7c014bbb064c64908
b2

  Additional Information 3:                  6ee2

  Additional Information 4:                  6ee2432e64e99bdcea5e4be767a3b1
a2



*Read our privacy statement online:*

  *http://go.microsoft.com/fwlink/?linkid=280262
<http://go.microsoft.com/fwlink/?linkid=280262>*



If the online privacy statement is not available, please read our privacy
statement offline:

  *C:\Windows\system32\en-US\erofflps.txt*



2 Errors in event viewer and 1 information:



Event ID: *1026*

Application: mRemoteNG.exe

Framework Version: v4.0.30319

Description: The process was terminated due to an unhandled exception.

Exception Info: System.ArgumentException

   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)

   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=
b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon,
System.__Canon, Boolean)

   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=
b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon,
System.__Canon)

   at mRemoteNG.App.Update.UpdateFile.FromString(System.String)

   at mRemoteNG.App.Update.UpdateFile..ctor(System.String)

   at mRemoteNG.App.Update.UpdateInfo.FromString(System.String)

   at mRemoteNG.App.Update.AppUpdater.GetUpdateInfo()

   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)

   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)

   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object, Boolean)

   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
System.Threading.ContextCallback, System.Object)

   at System.Threading.ThreadHelper.ThreadStart()







Event ID: *1000*

Faulting application name: mRemoteNG.exe, version: 1.75.7000.19194, time
stamp: 0x58bd9ee6

Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp:
0x5736541b

Exception code: 0xe0434352

Fault offset: 0x00014878

Faulting process id: 0x7560

Faulting application start time: 0x01d2bf20095caa6f

Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe

Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll

Report Id: 4b355e09-2b13-11e7-80c2-b4b52f5e4f36

Faulting package full name:

Faulting package-relative application ID:



Information:

Fault bucket , type 0

Event Name: CLR20r3

Response: Not available

Cab Id: 0



Problem signature:

P1: mRemoteNG.exe

P2: 1.75.7000.19194

P3: 58bd9ee6

P4: mscorlib

P5: 4.6.1087.0

P6: 583e5abb

P7: 321

P8: 10

P9: System.ArgumentException

P10:



Attached files:



These files may be available here:

C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_mRemoteNG.exe_
b9b2433aa867d0806590d46d4eafc55f2c6e1f9_21f3262c_4892f597



Analysis symbol:

Rechecking for solution: 0

Report Id: 4b355e09-2b13-11e7-80c2-b4b52f5e4f36

Report Status: 2048

Hashed bucket:

**Comment by kmscode** [comment]
So I can't tell 100% from the stack trace, but if I had to guess, it would be failing here:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/App/Update/UpdateFile.cs#L46

But that doesn't make much sense since there are a number of checks before we get to that point...

- After deleting the user.config, were you prompted in regards to update settings?
- Did you enable or customize the update settings?
- What update channel are you configured to use?
- Installed or Portable version?
- Can you access any of the following URLs successfully?
    - https://mremoteng.org/update-portable.txt
    - https://mremoteng.org/beta-update-portable.txt
    - https://mremoteng.org/dev-update-portable.txt
    - https://mremoteng.org/update.txt
    - https://mremoteng.org/beta-update.txt
    - https://mremoteng.org/dev-update.txt

These should just return a few lines of text:
```
Version: 1.75.7000.19221
dURL: https://github.com/mRemoteNG/mRemoteNG/releases/download/v1.75Hotfix1/mRemoteNG-Portable-1.75.7000.19221.zip
clURL: https://raw.githubusercontent.com/mRemoteNG/mRemoteNG/v1.75Hotfix1/CHANGELOG.TXT
Checksum: D4A811CAD17D7A928EB71D73F487D52D0832F40FE4829516563A9BE0061767C810F32CF6A43AB4878476D12E02AD9CA6F39B86DAC012609DFEF5EC5346B49F4F
```

Assuming that you configured the update settings (clicked anything other than "Ask Later") after deleting the user.config, if you were to delete the user.config again and the click "Ask Later" - I suspect that mRemoteNG would continue to run - could you please confirm?

Hope that helps...

**Comment by ikapoulas** [comment]
when mremoteng openning I used to choose (use recommended settings)
I using Installed version
I cannot access the above links (our firewall blocking the sites)
If i choose ask me later the application don't crashes.

Thanks a lot for your support.


Best Regards

**Comment by ikapoulas** [comment]
The issue was on update settings.

Problem solved after i disable the automatic updates.

Thanks a lot for your support.

Best Regards

**Comment by kmscode** [comment]
No problem... I'll classify this as a bug so I can build a proper fix for other users that might have problems accessing those URLs due to firewall configurations.
