### ISSUE TITLE
Update PuTTYNG to 0.69

### ISSUE THREAD

**Issue by igor2x** [mRemoteNG/mRemoteNG#531]
Putty was released 0.69 mostly with security fixes.
http://www.chiark.greenend.org.uk/%7Esgtatham/putty/
> 2017-04-29 PuTTY 0.69 was released.
> 
> PuTTY 0.69, released today, fixes further problems with Windows DLL hijacking, and also fixes a small number of bugs in 0.68, including broken MIT Kerberos support and the lack of jump lists on the Start Menu.

**Comment by kmscode** [comment]
Will most likely get this in the next hot fix release. Will try for sometime this week.

**Comment by kmscode** [comment]
Resolved in commit e377a72f750d95ce68c454c90e354bef40bdee0e
