### ISSUE TITLE
Missing Dlls trying to build the project

### ISSUE THREAD

**Issue by joelharkes** [mRemoteNG/mRemoteNG#533]
I'd like to contribute to this project but i feel like i'm missing certain files:

* AxWFICALib
* AxICAClient

I see they are added as a COMReference but i have no idea how i would make this work on my pc. Any assistence would be nice.

![image](https://cloud.githubusercontent.com/assets/2960938/25624166/dc79d39c-2f58-11e7-966d-16383d94c49c.png)

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| master branch  |
|Tool version| Visual studio 2015  |

**Comment by schittli** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thomas.schittli@akros.ch
    Domain jig.ch has exceeded the max emails per hour (207/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:35457)
	by rs111.nsresponse.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-aac0-github=jig.ch@sgmail.github.com>)
	id 1d5ZRC-000hWS-Et
	for github@jig.ch; Tue, 02 May 2017 10:10:12 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=dlphSakxqFVoGUu2Lebm1ME1kFM=; b=tCayxcFW8zQ/jd+4
	GJqK5/Fk1LfLv0mnl38172s1rsugTUb0nyX/2OopJXMFp3sU03YTZGhaLDyEnR7m
	Vba3ixpx+IyLs4f+vgoEQFQWyezdHeu6YHnNX54y2klXz7o60/JvqTWRvw16YHGb
	Houil0HMhy51dDfTlfA6iM1Q70M=
Received: by filter0981p1mdw1.sendgrid.net with SMTP id filter0981p1mdw1-18424-59089FC7-17
        2017-05-02 15:03:35.126471441 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id yU3_RIa7TuWpcLBAWcB1QQ
	for <github@jig.ch>; Tue, 02 May 2017 15:03:34.820 +0000 (UTC)
Date: Tue, 02 May 2017 08:03:33 -0700

**Comment by sparerd** [comment]
Hi @joelharkes, glad to hear that you want to contribute!

Here is our guide for getting your development environment set up:
https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment

The DLLs shown in your screenshot are related to Citrix Receiver, which must be installed in order to build the program.

**Comment by joelharkes** [comment]
Awesome!

 I totally missed the wiki page, sorry to bother you with that

**Comment by schittli** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thomas.schittli@akros.ch
    Domain jig.ch has exceeded the max emails per hour (225/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:53846)
	by rs111.nsresponse.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-aac0-github=jig.ch@sgmail.github.com>)
	id 1d5Zjl-000no1-1b
	for github@jig.ch; Tue, 02 May 2017 10:29:25 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=4DEuZWN8hHpqX0PSFdR0MBH67aA=; b=cqgdWXJsp+ZvAipl
	8jnS2fMMAgN7OvY0wBqWaLoRTE8F9JpHJYrYdSeNwdmL1P/sgAG7dTgras0W7ZqY
	iNebMLk0umSh+fuq4i/wk0U6IttLEvq+av76bEmlEbk1drkC8OGMJtQFD/pnO36U
	5ykd26K1/4dRut9agfJQ7v36TVc=
Received: by filter0929p1mdw1.sendgrid.net with SMTP id filter0929p1mdw1-20667-5908A39F-2A
        2017-05-02 15:19:59.131713354 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id FmnOWYgETaybpzqdrf2XIw
	for <github@jig.ch>; Tue, 02 May 2017 15:19:59.021 +0000 (UTC)
Date: Tue, 02 May 2017 08:19:58 -0700

**Comment by schittli** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thomas.schittli@akros.ch
    Domain jig.ch has exceeded the max emails per hour (227/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:49867 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs111.nsresponse.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1d5Zjx-000nrG-B1
	for github@jig.ch; Tue, 02 May 2017 10:29:30 -0500
Date: Tue, 02 May 2017 08:28:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1493738924;
	bh=hHm44QcS2Ur8S/01IiW6e1PNffgg/WXbZAydo9bYjR4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jjny6yrAQ3eMLCGHy/jtAqSy7P/QhG3OW1YsLsuPSeLi7mOSQo38qBhlVIrrmNCf3
	 3HH6hTQM/LRaqaYpL2M3vqu/l/FVD4fBTW5pLfYqeqZrWp653ZnT2H0KgfZUEwpuxa
	 8003WRM8CRJ7cp/Sn3I1IQBhcDfEBgDZJNILm0mc=

**Comment by schittli** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thomas.schittli@akros.ch
    Domain jig.ch has exceeded the max emails per hour (226/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:46366 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs111.nsresponse.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1d5Zjx-000nrE-8a
	for github@jig.ch; Tue, 02 May 2017 10:29:30 -0500
Date: Tue, 02 May 2017 08:28:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1493738924;
	bh=LrAEF6vJkopGvMTky8d9cSrjyuVYTx/jf7k/IWNJf3o=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NzYWcq2t0LZZ6MGJTqb30L1JjCc4uyeJnooaiJiTn1uXbGI9RJ9RVwDUB7S9r1GmO
	 QCKK4pyArS+3bi4CVE3YuJMgB+EEQlEQqqxLui4Yy3AffiFqcTszpuNz+AKBkWGajS
	 xrg/rmbev19eqKN3eo3noWsD5DAN3xg/fyOv3H3Y=

**Comment by andur** [comment]
Get the latest Citrix-Receiver installed and rebuild
https://www.citrix.com/downloads/citrix-receiver/windows/receiver-for-windows-latest.html
