### ISSUE TITLE
mRemoteNG.log file locked

### ISSUE THREAD

**Issue by agiz10** [mRemoteNG/mRemoteNG#536]
After v 1.74 i finally tried new version. It writes log file regardless if setting "Write log file (mRemoteNG.log)" is ticked or not.
The problem arises when i try to sync config folder between different computers, and with log file locked i get errors as sync program (Syncthing in my case) can not copy it over if program is open on different computers.
This should be a fast fix, but for me, somewhat important one.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
Thanks for the report - we will take a look

**Comment by agiz10** [comment]
I would just like to do a gentle ***bump*** for this litle bug. Thanks!

**Comment by kmscode** [comment]
Resolved by PR #700

**Comment by agiz10** [comment]
Sweet, thx! :)
