### ISSUE TITLE
RDP session disconnecting when resizing window (full screen/restore/minimise) I was using an earlier version before where I could resize without losing the connection. 

### ISSUE THREAD

**Issue by rtonge** [mRemoteNG/mRemoteNG#538]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by infectormp** [comment]
same https://github.com/mRemoteNG/mRemoteNG/issues/296#issuecomment-265551071?

**Comment by kmscode** [comment]
@infectormp is correct. This is working as designed with "fit to panel". Setting to "smart size", or a specific resolution should avoid the disconnects.

Minimize shouldn't cause any disconnects since the resolution doesn't change in that scenario.

**Comment by industrialstr** [comment]
Terrible design then. It loses it's mind and often can't even reconnect often times.

In my opinion this is a horrible 'working as intended' - maybe someone sees value in this I do not.

**Comment by sparerd** [comment]
All these options have trade-offs, and you as the user can determine which trade-offs you prefer. However, if you don't want dead space / scroll bars and want to preserve the aspect ratio of the connection, you must reconnect. That is a limitation of the RDP protocol.

- `Resolution: Fit to Panel` and `Automatic Resize: Yes`
   - Ensures no dead space or scroll bars when connecting or resizing connection window
   - Preserves aspect ratio
   - Requires reconnect when connection window size changes
- `Resolution: Fit to Panel` and `Automatic Resize: No`
   - Ensures no dead space or scroll bars when initially connecting
   - Resizing connection window will create dead space or scroll bars
   - Preserves aspect ratio
   - Does not require reconnect when connection window size changes
- `Resolution: Smart Size`
   - Ensures no dead space or scroll bars when connecting or resizing connection window
   - Does not preserve aspect ratio (stretches the image to fill the window)
   - Does not require reconnect when connection window size changes
- `Resolution: [Width] x [Height]`
   - Initial connection may have dead space or scroll bars
   - Resizing connection window will create dead space or scroll bars
   - Preserves aspect ratio
   - Does not require reconnect when connection window size changes

**Comment by industrialstr** [comment]
I see - I stand fully corrected. I am just accustomed to a different behavior and, when I lose connectvity, it's a pain in the posterior because immediately my security apps lose connection and so I have to jump through a bunch of hoops and 2-factor authentication etc.

For some reason it also simply seems to have a problem quickly reconnecting - sometimes taking minutes. This may be isolated to my setup but it's strange compared to my past experiences.

Thanks very much for the detailed response.

**Comment by sparerd** [comment]
Yea, I've noticed it takes a long time to reconnect too. We call the built-in "Reconnect" method when resizing the connection. It might go faster if we do a disconnect / connect instead of using the built in reconnect. I opened #1152 to investigate that option

**Comment by nicovv44** [comment]
https://github.com/mRemoteNG/mRemoteNG/issues/538#issuecomment-432648356
> All these options have trade-offs, and you as the user can determine which trade-offs you prefer. However, if you don't want dead space / scroll bars and want to preserve the aspect ratio of the connection, you must reconnect. That is a limitation of the RDP protocol.

Maybe it was a limitation, but not anymore.

[Microsoft Remote Desktop](https://www.microsoft.com/en-au/p/microsoft-remote-desktop/9wzdncrfj3ps?activetab=pivot:overviewtab) does it properly.

With it you can resize the window and have have no scroll bar, and no disconnect, so I believe **mRemoteNG** could do the same.

So... Can we re-open that issue?

**Comment by nicovv44** [comment]
Duplicate of https://github.com/mRemoteNG/mRemoteNG/issues/2054
