### ISSUE TITLE
Move connections between panels 

### ISSUE THREAD

**Issue by Git2Swarm** [mRemoteNG/mRemoteNG#544]
## New feature request:

User should be able to move the connection from one panel to another...

Often times we duplicate a connection and then feel handicapped to view content of both the connection side by side. The current option is to launch as a new connection a different panel right from the get go.

**Comment by jancgd** [comment]
The final solution would be to allow drag and drop of the tabs to another panel.
But maybe, as a first step you could add a new entry to the context menu of the tabs like "Move Tab to..." to open the "Select Panel" dialog.

**Comment by kuroburki** [comment]
I have been using this workaround for 4+ years : Options->Check "Always show panel selection dialog when opening connections". With this option enabled, if you select "Duplicate Connection" the application will prompt you to pick a panel for the duplicated connection. Click New -> Give a different panel name and you are done. I rarely go beyond 3 panels for all my connections.

![image](https://cloud.githubusercontent.com/assets/7956309/26017660/5e18aa16-3730-11e7-8ca4-e2c49888f851.png)

**Comment by jancgd** [comment]
Nice trick @kuroburki ! This helps when creating new tabs. But if I already have a tab open, there still is no way to move it to another panel.

**Comment by sjeeva** [comment]
I face this issue quite often.. Also when duplicate a connection, there should be a duplicate to a new panel option..

**Comment by seidls** [comment]
I also would love to see this Enhancement.  I've tried the "Always show panel selection dialog when opening connections" option, and can't stand the popup cause 90% of the time it's not needed.  Drag/drop or a right-click send-to-panel option would be great.

**Comment by kmscode** [comment]
With the implementation of #155, you can now have side by side tabs within the same connection panel by simply dragging and dropping to the desired docked location. Currently in the develop branch, a 1.77 alpha is expected soon.
