### ISSUE TITLE
Quick Connect displays warning when left-clicking on a folder

### ISSUE THREAD

**Issue by icnocop** [mRemoteNG/mRemoteNG#546]
Hi.

I'm experiencing the behavior indicated in #334, but with the left mouse click button.

| Operating system | Windows 7 SP1 x64 |
|--------------------|---------------------|
| mRemoteNG version| 1.75.7000.19194  |

1. Right-click on system tray notification icon
2. Left-click on Connections
3. Left-click on Connections
4. Notice the warning message "Cannot open connection: No hostname specified!"

![image](https://cloud.githubusercontent.com/assets/507649/25881673/326ed9b0-34f3-11e7-86b6-44dcf984106b.png)

I didn't expect a new window to appear, but instead just the Connections sub-menu to expand.

Thank you!

**Comment by sparerd** [comment]
Good find - this one should be a pretty quick fix too

**Comment by ejhutch** [comment]
I am testing Alpha version 1.76.2.14965 and see this same issue, when I click on the Quick Connect drop down, and there are no windows already open, I get this same error. Thanks.
