### ISSUE TITLE
Double-click rename instead of connecting

### ISSUE THREAD

**Issue by Mjolinir** [mRemoteNG/mRemoteNG#550]
When double-clicking on an item in the Connections menu, mRemoteNG tries to rename the connection instead of connecting. It does not seem to care if it is a show or fast double-click. This has only been an issue in the past couple versions. 

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7000.19194 |

**Comment by mrwulf** [comment]
I'm seeing this too- although only when slowly double-clicking a connection. Since rename is on the context menu and available with F2 it seems like we should probably just disable double-click to rename.

**Comment by Mjolinir** [comment]
I think that would be a good fix

**Comment by sparerd** [comment]
@mrwulf that sounds good to me

**Comment by sparerd** [comment]
Merged fix provided by @mrwulf. This will be available in the next patch
