### ISSUE TITLE
Request: Config file security improvement with passphrase

### ISSUE THREAD

**Issue by Tetsumaki** [mRemoteNG/mRemoteNG#552]
Hello,

First of all, thank you for this application which makes me life easier.

It is possible to add a passhrase in the security tab when launching the application when the connection file is encrypted so that the file can not be used when copying / pasting on another computer (potential hack).

**Comment by sparerd** [comment]
Passphrases can already be set by clicking on the Connections tree node and setting "Password" to yes. Is this what you were looking for?

**Comment by Tetsumaki** [comment]
Hello sparerd, yes is that.

I had never seen this configuration option.

Good corporate practice would therefore be :
Tools > Options > Security tab > Completely encrypt connection file
Connections tree node > set Password protect to Yes

If a bad person takes the file confCons.xml, he can not use it or decrypt it, is that right or will it still have a solution?

Thanks.

**Comment by sparerd** [comment]
> Good corporate practice would therefore be :
Tools > Options > Security tab > Completely encrypt connection file
Connections tree node > set Password protect to Yes

Yes those settings would be the most secure. The most important of them is setting "password protect" to yes. There is no simple way to defeat the security of the file when that is set.

**Comment by Tetsumaki** [comment]
OK very nice and sorry for issues when the option already exists.

**Comment by sparerd** [comment]
Np! Happy to help
