### ISSUE TITLE
Better multi-monitor support - detach panel and display as independent view

### ISSUE THREAD

**Issue by kuroburki** [mRemoteNG/mRemoteNG#554]
Often times, I need to move my terminal windows between multiple monitors. I can drag a panel out of main window and move it to another display (monitor). However, this panel visibility is still tied to the main window. If any other application is displayed on top of main window, the panel moved into to second display also gets hidden. Is there is a way to treat the detached panel as a separate process? I am thinking of a way similar to Chrome browser. Detach panel -> detached panel will be independent of main window. Re-attach panel -> it's part of the main window again.

**Comment by KyferEz** [comment]
YES PLEASE! This is the biggest feature I miss from MS Remote Desktop Connection Manager.

**Comment by kmscode** [comment]
This is now possible in 1.77 (in the develop branch, alpha release expected soon). Reference #155 - All tabs are now handled by DockPanelSuite and can be undocked and moved to other monitors (as well as other options).
