### ISSUE TITLE
External Tools issue with %Password%

### ISSUE THREAD

**Issue by d66n** [mRemoteNG/mRemoteNG#559]
**External Tool:**
Display Name: Filezilla SSH
Filename: C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe
Arguments: sftp://%Username%:%Password%@%Hostname%:22

**Example Config:**
192.168.1.23
Username: sysuser
Password: *6j9VNuozw!j

**Protocol:**
Protocol: Ext. App
External Tool: Filezilla SSH
Port: 0

Correct my if I'm wrong but I'm expecting this to build up the following command line:

"C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe" sftp://sysuser:*6j9VNuozw!j@192.168.1.23:22

When the above is run from a command prompt in Windows, Filezilla connects successfully.
However, when launched from mRemoteNG through the external tool, Filezilla reports 'Authentication failed'. Please note that simpler passwords do not suffer this problem through this external tool but only those with certain characters. 

|Operating system | Windows 7 SP1 x64 |
|mRemoteNG version| 1.74 (2016-06-28) |

**Comment by kmscode** [comment]
You need to use %!Password%
https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools
