### ISSUE TITLE
Installer gui bug - 1.75.7005.28220

### ISSUE THREAD

**Issue by tommybuck** [mRemoteNG/mRemoteNG#561]
Just upgraded to build 1.75.7005.28220 and when its copying the files it doesn't display the actual file names. It displays the place holders such as file [1] or location [9] etc.
![capture1](https://cloud.githubusercontent.com/assets/22301046/26223514/466488aa-3c16-11e7-9e3e-a440c4633647.PNG)

**Comment by sparerd** [comment]
Thanks for reporting this - I'll take a look at it

**Comment by sparerd** [comment]
Seems this was an issue specific to Win10. This has now been corrected in our installer

**Comment by sparerd** [comment]
https://stackoverflow.com/questions/44161526/wix-copying-new-files-file-1-directory-9-size-6-shown-during-instal
