### ISSUE TITLE
Add mRemoteNG to OpenHatch

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#562]
In an effort to increase awareness of the project and solicit help from other developers, we should add mRemoteNG to OpenHatch.org.

**Comment by sparerd** [comment]
Created https://openhatch.org/projects/mRemoteNG

**Comment by kmscode** [comment]
I wouldn't spend much/any time on this... Looks like they might be shutting down operations soon:
http://blog.openhatch.org/2017/celebrating-our-successes-and-winding-down-as-an-organization/

**Comment by sparerd** [comment]
Gotcha, good find. It seems their dynamic bug crawler doesn't work, or doesn't work quickly anyways. Profile is up on the site, so this is probably as done as it will get
