### ISSUE TITLE
MRemoteNG freezes when closing SSH sessions (manual / remote)

### ISSUE THREAD

**Issue by leonardo0014** [mRemoteNG/mRemoteNG#563]
MRemoteNG ist ein wunderbares Programm, dass mir so manche administration erleichtert. Leider gibt es aber einen Fehler, der das Ergebnis trübt.
Das Programm friert ein, wenn viele offene TABs schnell geschlossen oder die SSH Session remote beendet wird. Der Task Manager zeigt, die auslösende Putty Session ist beendet, aber MRemoteNG reagiert nicht mehr. Ich konnte das erfolgreich nachstellen: Öffne mindestens 7 SSH Sessions und Tippe in jede etwas ein. Dann schließe schnell per Doppelklick auf die TABs nacheinander alle Sessions. In 70% aller Fälle friert MRemoteNG ein und reagiert nicht mehr.
Ich vermute das Programm bekommt nicht mit, dass die Putty SSH Session geschlossen wurde und wartet noch auf eine Rückmeldung. Ich konnte diesen Fehler bisher mit jeder MRemoteNG Version nachstellen. Ich benutze den mitgelieferten Putty.

Hat jemand eine Idee woran das liegen könnte?
<hr>
MRemoteNG is a wonderful program, which makes it easy for me to administer. Unfortunately, there is a mistake that blurs the result.
The program freezes when many open TABs are closed quickly or the SSH session is terminated remotely. The Task Manager shows that the triggering putty session is finished, but MRemoteNG no longer responds. I could successfully recreate this: Open at least 7 SSH sessions and type in each something. Then quickly close all sessions by double-clicking the TABs. In 70% of all cases, MRemoteNG freezes and stops responding.
I guess the program does not get that the Putty SSH session has been closed and is still waiting for a feedback. I was able to correct this error with every MRemoteNG version. I use the included putty.
Does anyone have any idea why this might be?

|||
|--:|---|
|Operating system | Windows 2008 x64/32 or<br /> Windows 7 x64/32|
|mRemoteNG version| Stable 1.75 (Hotfix 1) or <br /> Prerelease v1.75.7005 (Hotfix 5)|

**Comment by kmscode** [comment]
This bug also cropped up during implementation of #155 and is expected to be fixed in the develop branch. 1.77 alpha is expected to be released soon.
