### ISSUE TITLE
Resize disconnects RDC

### ISSUE THREAD

**Issue by flkeysils** [mRemoteNG/mRemoteNG#564]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

When you resize the connections pane to the right, your rdc connection disconnects then reconnects.  So when you resize you will see the "Reconnecting" window pop-up for a few seconds then disappear.  After that your connect restores.

**Comment by kmscode** [comment]
This is working as designed with the RDP resolution set to "fit to panel". Setting it to "smart size", or a specific resolution should avoid the disconnects.
