### ISSUE TITLE
ConfCon file zeroing out when after closing mremote

### ISSUE THREAD

**Issue by freakmoister** [mRemoteNG/mRemoteNG#569]
||| confcon file becomes 0 bytes after closing mremote even after issuing save command.
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

Are you attempting to save to remote device (mapped drive, cloud drive, etc)?

**Comment by kmscode** [comment]
Closing due to no response.

**Comment by kmscode** [comment]
Reference #340
