### ISSUE TITLE
Copy password with ease.

### ISSUE THREAD

**Issue by ozgurerdogan** [mRemoteNG/mRemoteNG#575]
For many reasons, I may need to copy host's password. And to do that I have use 3rd party password unmask software to make host's password clear and copy it. 
So please please please make an option like: Right click on host and select copy password, or make an option to show password in clear format so I can see and copy host's password easily.

**Comment by Benchwork** [comment]
if the password is the same.... is the username the same?   if so, just duplicate the connection.
it will inherent all the settings from the one you had.
![image](https://user-images.githubusercontent.com/7304823/27134410-76c7de84-50e3-11e7-96ac-f20eca86fd70.png)

Peter.

**Comment by KOTRET** [comment]
+1, sometimes there is a need to know the password. Optionally there could be a button to make the password visible, maybe this should require some "master-password" to show.

**Comment by kmscode** [comment]
copying the password can be seen as insecure. We will not implement this feature. However, a credential manager feature is planned which would effectively negate the need to copy the password: #208

**Comment by KOTRET** [comment]
well, currently i use an `echo` with the password-arg as external cmd-tool to show it - is that more secure? 😁

**Comment by kmscode** [comment]
@kotret

That's a loophole that we don't advertise (though our users do) and we're going to attempt to fix with the credential manager.

Some users want to share access, but not passwords (especially nwith the experimental SQL feature)...

We're not going to purposefully make it easier/less secure. Security through obscurity basio... 

:smile:

**Comment by onguarde** [comment]
You can simply add the following under mremote's external tools,

Application: Username to Clipboard

Filename: `C:\Windows\System32\cmd.exe`
Arguments: `/c "echo %username%|clip"`

Application: Password to Clipboard

Filename: `C:\Windows\System32\cmd.exe`
Arguments: `/c "echo %password%|clip"`

![image](https://user-images.githubusercontent.com/681355/139800057-4d63e234-eeec-4d8a-9803-f1777d5ad8d4.png)
