### ISSUE TITLE
ssh key auth not working with built in putty

### ISSUE THREAD

**Issue by tpcnz** [mRemoteNG/mRemoteNG#576]
Latest mremoteng seems to have broken ssh key authentication. If I configure the advanced settings to use a separately installed putty then key auth to servers works fine. No other changes to connection settings required. Issue was not present on an older version (unsure of version sorry) and is repeatable 100% of the time. Private key file is 4096 bit RSA2.  Reproduced behaviour with ssh to a current Check Point Linux server and a current Citrix NetScaler appliance.
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7000.19221  |

**Comment by sparerd** [comment]
We are getting ready to do a minor release to the built in putty for some upstream security fixes. @kmscode is a bit more familiar with the puttyng code than I am - he might be able to comment.

**Comment by kmscode** [comment]
@tpcnz 

The release that @sparerd is referring to will have PuTTYNG 0.69 which is available from here:
https://github.com/mRemoteNG/mRemoteNG/raw/develop/mRemoteV1/Resources/PuTTYNG.exe

Could you please try that version and let us know if you still have the problem?

**Comment by farosch** [comment]
@tpcnz Since this is a very old issue (which is apparently only relevant for version 1.75), we can't recreate the problem and haven't heard back from you in nearly 2 years, I will close this issue.
Feel free to re-open it, if this issue still persists for you!

**Comment by ali-avci** [comment]
I have the same issue. 
mRemoteNG Version 1.77.1.27654

Key file saved with version 3 resulted in "unable to load key file '......' (PuTTY key format too new)" before any login attempt

key file saved with version 2 resulted in "server refused our key" after the login attempt

PuTTY 0.76
has no problem with any of these key files. 

Observed the problem in mRemoteNG while trying to connect to an Ubuntu 22.04 Server located in AWS, but did not face the problem when connecting to an AWS Amazon Linux 2. Same key is used on both destinations. 

I hope that this will help to fix the problem.

**Comment by ali-avci** [comment]
@farosch may I ask you to re-open the ticket.

**Comment by ali-avci** [comment]
Solved it by adding/changing these entries into the servers /etc/ssh/sshd config file. After investigating the auth.log file.

PubkeyAuthentication yes
PubkeyAcceptedKeyTypes=+ssh-rsa

**Comment by brendanvz** [comment]
I can confirm this worked for me as well. Thanks @ali-avci 

> Solved it by adding/changing these entries into the servers /etc/ssh/sshd config file. After investigating the auth.log file.
> 
> PubkeyAuthentication yes PubkeyAcceptedKeyTypes=+ssh-rsa

**Comment by eskes1** [comment]
PubkeyAcceptedKeyTypes=+ssh-rsa are a workaround not fixing the issue. Still a bug.


A better suction are in this bug https://github.com/mRemoteNG/mRemoteNG/issues/2354 Replace PuTTYNG wit latest.

**Comment by Kvarkas** [comment]
have you update a puttyng?

**Comment by eskes1** [comment]
Yes, then will it work without adding PubkeyAcceptedKeyTypes=+ssh-rsa
