### ISSUE TITLE
All ssh sessions opening disconnected from mRemoteNG main window

### ISSUE THREAD

**Issue by AcousticRand** [mRemoteNG/mRemoteNG#583]
|||
|--:|---|
|Operating system | Windows 10 x64 v1703 build 15063.332 |
|mRemoteNG version| 1.75.7006.16707  |

I just upgraded to this version of mRemoteNG from 7001 (or 7000 cannot recall), and upon trying to open any pre-existing ssh entry from the tree on left, the connection opens in a separate window rather than in a tab or panel like it was doing before the upgrade.  See image below.

![2017-06-13 16_25_01-mremoteng](https://user-images.githubusercontent.com/1158199/27105474-4ebdd346-5055-11e7-962d-578170499913.png)

**Comment by davidjbv** [comment]
Hi, I have the same issue after updated mremote

**Comment by syndgr** [comment]
The panel opens. The connection tab is displayed. But the PuTTYNG window is not embedded in the tab.

If I close the "General" panel, it closes PuTTYNG. If I right click the connection tab ("Gateway"), I can control PuTTYNG still (e.g. "Disconnect" closes PuTTYNG).

Screenshot:

![image](https://user-images.githubusercontent.com/20760738/27106311-c938de42-508a-11e7-9980-1b042d27c0c4.png)

**Comment by walteryee** [comment]
Same result here on version 1.75.7006.16707.

**Comment by pandvan** [comment]
Same issue here with a fresh install of version 1.75.7006.16707

**Comment by fabricat** [comment]
Same for me, after (manually) upgrading to version 1.75.7006.16707

**Comment by svenruetz** [comment]
same here "1.75.7006 (2017-06-13)"

**Comment by grassreaper** [comment]
Same issue after upgrading to latest 1.75.7006.16707 on Windows 7 x86 & x64.
But previous version 1.75.7005.28220 behaves ok.

**Comment by syndgr** [comment]
Downloading PuTTYNG 0.67 (from here: https://github.com/mRemoteNG/PuTTYNG/releases) and replacing the EXE in the mRemoteNG installation resolves the issue.

I also tried PuTTYNG 0.68 (from here: https://github.com/mRemoteNG/mRemoteNG/blob/69f310c02c89d3df8993f8112fbcce4a8154fa73/mRemoteV1/Resources/PuTTYNG.exe) but the same issue occurs.

Issue appears to be related to PuTTYNG versions 0.68 and 0.69 and mRemoteNG version 1.75.7006.16707.

**Comment by sparerd** [comment]
Hey all - taking a look at this now

**Comment by kmscode** [comment]
I'm reviewing as well... Not sure why this is happening. I've been running with 0.68 and 0.69 for like a combined 2-3 months on previous builds and I *didn't* have this problem before flipping the switch yesterday.

Sorry everyone. We'll get this squared away ASAP.

**Comment by kmscode** [comment]
testing some new builds puttyng builds now that look promising.

**Comment by blutgens** [comment]
Same issue, win 8.1. 
MremoteNG 1.75.7006.16707
PuttyNG 0.69

**Comment by sibernetik** [comment]
I found a work-around. If you go to Tools > Options > Advanced. Under "Use custom PuTTY path" I navigated to the non-PuttyNG (downloaded from http://www.putty.org/) location and used that. Now all of my SSH sessions launch within mRemoteNG.

**Comment by kmscode** [comment]
Looks like the MSI build didn't pick up the new puttyng.exe binary... Looking into that now. However replacing your current puttyng.exe with [this one](https://github.com/mRemoteNG/mRemoteNG/raw/master/mRemoteV1/Resources/PuTTYNG.exe) should take care of the problem.

**Comment by blutgens** [comment]
That worked.

**Comment by sibernetik** [comment]
I am actually still having the issue after upgrading to 1.75.7007 (2017-06-14)

**Comment by blutgens** [comment]
That fixed it too! Thnx

**Comment by kmscode** [comment]
@sibernetik the new puttyng.exe doesn't seem to have been picked up by out automated build for some reason - even though the same process builds the portable release and that was picked up properly... 😕 

Looking into that further now...

**Comment by AcousticRand** [comment]
By the way - I posted the original bug without even saying the following:
Fantastic software and I really appreciate your hard work and dedication!  Your prompt responses on this issue just proves that dedication.
