### ISSUE TITLE
All ssh sessions opening disconnected from mRemoteNG main window - Part 2

### ISSUE THREAD

**Issue by sibernetik** [mRemoteNG/mRemoteNG#589]
|Operating system | Windows 10 Enterprise v1703 Build 15063.296 |
|mRemoteNG version| 1.75.7007.16235  |

This issue was reported in a previous version, and 1.75.7007.16235 was supposed to fix it, but after upgrading I am still experiencing the issue. All of my SSH sessions are launching external to mRemoteNG. Is the bug still present or am I doing something wrong?

Link to previous issue: https://github.com/mRemoteNG/mRemoteNG/issues/583

Edit: I found a work-around. If you go to Tools > Options > Advanced. Under "Use custom PuTTY path" I navigated to the non-PuttyNG (downloaded from http://www.putty.org/) location and used that. Now all of my SSH sessions launch within mRemoteNG.

**Comment by kmscode** [comment]
@sibernetik the new puttyng.exe doesn't seem to have been picked up by out automated build for some reason - even though the same process builds the portable release and that was picked up properly... 😕 

Looking into that further now...

**Comment by sibernetik** [comment]
Thanks, @kmscode. After I posted this I found your fix on the previous page. That appears to be working for me.

> Looks like the MSI build didn't pick up the new puttyng.exe binary... Looking into that now. However replacing your current puttyng.exe with this one should take care of the problem.

**Comment by kmscode** [comment]
Just some updates...

Local builds for @sparerd seem to pull the correct version of PuTTYNG. My local builds and the automated builds do not. We're still looking into this further.

**Comment by dsiminiuk** [comment]
@sibernetik - you can download putty.exe and save it as PuttyNG.exe and then you don't need to set the custom path. That also works.

**Comment by kmscode** [comment]
Hotfix 8 corrects this problem:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8
