### ISSUE TITLE
PuttyNG Home/End keys do not work

### ISSUE THREAD

**Issue by blutgens** [mRemoteNG/mRemoteNG#591]
Home and End keys do not seem to work in PuttyNG
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |
|PuttyNG Version|https://github.com/mRemoteNG/mRemoteNG/blob/70bd2e8a784b0ab3075173fdf3b06f632fb39158/mRemoteV1/Resources/PuTTYNG.exe|

If this is expected behavior, please ignore/close.

**Comment by kmscode** [comment]
They work out of the box for me... Mostly connecting to Linux systems running bash and TERM set to xterm (putty's default).

Solaris with ksh or bash, home/end print funky chars.

A bit of [Googling](https://www.google.com/search?q=putty+home+end&ie=utf-8&oe=utf-8) shows that this seems to be system/terminal/shell dependent...

**Comment by mueller-ma** [comment]
I cannot use ctrl+left-arrow for word moving. I have configured it in ~.inputrc: https://github.com/mueller-ma/linux-home-config/blob/master/config-files/.inputrc#L41
Windows 10 x64
mRemoteNG: 1.75.7010.21169

Target:
Raspbian GNU/Linux 8 (jessie)
Bash

**Comment by kmscode** [comment]
@mueller-ma 

This works for me:
```
# cat ~/.inputrc
"\eOD": backward-word
"\eOC": forward-word
```

You're .inputrc looks different - not sure if this is because of different keyboard layouts...

```
# localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```

**Comment by mgutt** [comment]
How do I set the Terminal-type in mRemoteNG/PuttyNG? If I set it to "putty" the Home/End Keys will work (tested in Putty), but if i leave the default "xterm", they won't. The [default is mentioned in the config file](https://github.com/mRemoteNG/PuTTYNG/blob/master/DOC/CONFIG.BUT#L1849), but I can't find a setting in mRemoteMG to modify it.

EDIT: Ok solved it as follows:
- Open Extras > Options > Advanced > Start Putty
- In Putty > Connection > Data > Terminal-type string > set to "putty"
- save as "Default Settings" profile
- restart nRemoteNG
- connect to server
- execute `echo $TERM`
- returns `putty`

For other servers, which don't support the `putty` profile, you could add an additional `xterm` session to Putty and set it as the default in the protocol settings of an mRemoteNG connection:
![image](https://user-images.githubusercontent.com/10757176/142584072-526967cd-ec03-4e15-a0e2-880995a5a2c4.png)
