### ISSUE TITLE
Review installer: binary file version check

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#595]
Review the need for the MSI binary version checks as this may cause us additional headaches down the road (See #589) should updates to upstream packages be required without changing the version numbers. When the version # is the same, the MSI will not update the file even if it's technically newer:
```
MSI (s) (C8:E4) [11:12:06:040]: Executing op: FileCopy(SourceName=PuTTYNG.exe,SourceCabKey=PuttyNGFile,DestName=PuTTYNG.exe,Attributes=512,FileSize=709096,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=0.69.0.0,Language=2057,InstallMode=58982400,,,,,,,)

MSI (s) (C8:E4) [11:12:06:041]: File: C:\Program Files (x86)\mRemoteNG\PuTTYNG.exe;	Won't Overwrite;	Won't patch;	Existing file is of an equal version
```

**Comment by farosch** [comment]
As of my understanding, this is no longer true for the current build implementation.
