### ISSUE TITLE
NullReferenceException when manually launching an external tool if no connection is selected.

### ISSUE THREAD

**Issue by jcugniere** [mRemoteNG/mRemoteNG#596]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.17907  |

When starting mRemoteNG, if I click on an external tools in the "external tools" toolbar, I received the following exception :

> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>    à mRemoteNG.UI.Forms.frmMain.tsExtAppEntry_Click(Object sender, EventArgs e)
>    à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    à System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    à System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    à System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    à System.Windows.Forms.Control.WndProc(Message& m)
>    à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    à System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

If I select a connection before clicking on the external tool, it runs fine. It should be possible to execute external tools without having to select a connection first.

**Comment by kmscode** [comment]
Fixed in commit: 9a2efd9686208c2682b8c9ad2b5f68815088ff80
