### ISSUE TITLE
If "Upload Reports" fails during automated build, don't report error to GitHub

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#599]
![image](https://user-images.githubusercontent.com/16654335/27230161-565f23f6-527c-11e7-9947-e6097d7add20.png)

If the build was otherwise successful, report the success to GitHub so we're aware of the "real" build status to avoid unnecessary red X's:
![image](https://user-images.githubusercontent.com/16654335/27230261-a454dc0e-527c-11e7-91c4-e1b9b254fcb4.png)

**Comment by sparerd** [comment]
These were failing pretty regularly and we dont use the reports much, so I've just removed the upload reports step entirely
