### ISSUE TITLE
Missing horizontal scrollbar on Connections Panel

### ISSUE THREAD

**Issue by YogurtuNgue** [mRemoteNG/mRemoteNG#600]
|||
|--:|---|
|Operating system | Windows 10 Pro x64 1703 (15063.413)|
|mRemoteNG version| 1.75.7008.17907 |

I've updated to the latest Windows 10 (creators update), and I've lost the horizontal scrollbar for the Connections Panel.  I've tried starting from scratch (new mremote installation with new config xml), but still nothing.

![image](https://user-images.githubusercontent.com/29486044/27232173-6630f962-528b-11e7-9b73-dbb30c5b3ab4.png)

**Comment by kmscode** [comment]
I believe that this is related to the newer "TreeNode" code that was implemented in 1.75...

The scroll bar is created in 1.74 on Win10 1703.

**Comment by YogurtuNgue** [comment]
You are correct, I downgraded to 1.74.6023.15437 and the scroll bar is back.  I do have to recreate my xml though

**Comment by smoras** [comment]
Shouldn't this issue remain open ? Since #613 is closed!

**Comment by kmscode** [comment]
@smoras this issue is open and was not closed.

**Comment by devinderdev** [comment]
Hi Team,
Any update for this issue, since otherwise the connections panel occupies too much screen on windows 10.
Please help.
Thanks,

**Comment by sparerd** [comment]
Implemented a fix for this that will be available in the next patch

**Comment by smoras** [comment]
Thank you @sparerd David and contributors for fixing this. This was a much needed fix.
