### ISSUE TITLE
The Putty window is opening outside the mRemoteNG window

### ISSUE THREAD

**Issue by Poil** [mRemoteNG/mRemoteNG#602]
Hi,

Since last update, The Putty window is opening outside the mRemoteNG window I've tried to reset all option to default, but not working, I've checked all components, all is OK.
Any idea ?

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7006.16707  |

**Comment by kmscode** [comment]
Fixed in 7008:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8
