### ISSUE TITLE
Password with special character

### ISSUE THREAD

**Issue by tristangallet** [mRemoteNG/mRemoteNG#604]
|||
|--:|---|
|Operating system | Windows 8 x64 |
|mRemoteNG version| 1.75.7005 (2017-04-27 |

Hello all ! I've upgraded from mremoteNG 1.72

I've got some password with special characters like "=" or "!" and they seems be defect in this version of mRemoteNG.

If i check with an external tool : /k echo %password%, password is the good one.
But launching an external tool like vsphere i've got bad authentication.

Any idea ?
Thanks

**Comment by LIyoai** [comment]
Try %!password%

**Comment by tristangallet** [comment]
Let me be more precise : i've got 2 external tools : 
- launching vsphere client : 
command Filename : C:\Program Files (x86)\VMware\Infrastructure\Virtual Infrastructure Client\Launcher\VpxClient.exe
Argument : -s %Hostname% -u %Username% -p %Password%

And for displaying my password :
command filename : cmd
agument : /k echo %password%

It was ok with version 1.72

Migrating with v 1.75 :  my command display the same old good passwords, but the vsphere client says it's not the good password !

If i copy and paste the password from the external tool (DOS Window), it's ok in vsphere client so the password is ok.

Strange...

**Comment by kmscode** [comment]
Between 1.72 (a very old version) and the current version meta-characters are now escaped. Using %!Password% as @LIyoai suggested will resolve this issue for you. Reference: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools

**Comment by tristangallet** [comment]
Thanks for your time, the link is welcome ! Problem solved !

**Comment by Jugurtha13** [comment]
Hello,
I still have the problem of special characters in the password.
I have the "!" character in my password for an RDP connection and it doesn't work.
I'm on the latest version: 1.76.20.24615

**Comment by kees-z** [comment]
This can be solved easily by using `%!password%` instead of `%password%`. This prevents metacharacter escaping and argument splitting. See #1635, #1651 and #1664.

**Comment by rsmanning** [comment]
I've tried %!password% instead of %password% and it still doesn't work for passwords that contain a % symbol, it is for other passwords though.
