### ISSUE TITLE
Run command after SSH connection.

### ISSUE THREAD

**Issue by theramist** [mRemoteNG/mRemoteNG#607]
Feature request.

Give option on SSH connection to execute a command in the terminal window after connection.
Could be via an entry in the config section or a link to a local file.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
Duplicate of #503 - please subscribe/like that issue for further updates. Thanks!
