### ISSUE TITLE
Change "support forum" menu item

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#608]
The support forums are going to be decommissioned. Change the Help -> Support Forums menu item within mRemoteNG to point to the subreddit.

**Comment by sparerd** [comment]
Related to #606

**Comment by igor2x** [comment]
... may I add additional simple task related to forum. On Tools | Components Check at "ICA (Citrix ICA) Check" last sentence is: If you are still not able to pass this check or use ICA in mRemoteNG please consult the mRemoteNG Forum at **http://forum.mremoteng.org/"**

Maybe just remove whole sentence. Isn't it obvious if someone has problem to search for Help menu and see the forum?

**Comment by sparerd** [comment]
Thanks for catching that @igor2x! I'll update that as well.

**Comment by sparerd** [comment]
Updated the relevant url
