### ISSUE TITLE
Unable to Copy/Paste from desktop to remote machines and vice versa

### ISSUE THREAD

**Issue by jgill12** [mRemoteNG/mRemoteNG#609]
I am unable to perform copy/paste from my Windows 10 desktop to any remote machine connections created within the software.  Has worked before.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Are these all RDP sessions? Make sure rdpclip.exe is running. If it isn't, start -> run -> rdpclip.exe. If it is running, kill it and restart it via the same procedure.

**Comment by nmat** [comment]
Is this still a issue with the latest version/versions? I have not encountered the problem from my testing.

**Comment by farosch** [comment]
@jgill12 Since this is a very old issue which is apparently only relevant for version 1.75 aplha 3 and we can't recreate the problem, i will close this issue.
Feel free to re-open it, if this issue still persists for you!
