### ISSUE TITLE
mRemoteNG cannot start /crashes  for some users on Windows server 2012 R2 server

### ISSUE THREAD

**Issue by lucbobski** [mRemoteNG/mRemoteNG#610]
Hi,
Could you please help with this issue, I installed 1.75 version of m RemoteNG on a windows sevrer 2012 R2. Please find below errors

EventLog : Application .Net Runtime, EventID 1026, Error
Application: mRemoteNG.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at mRemoteNG.Tools.IeBrowserEmulation.Register()
   at mRemoteNG.App.Startup.InitializeProgram()
   at mRemoteNG.App.ProgramRoot.StartApplication()
   at mRemoteNG.App.ProgramRoot.Main(System.String[])

EventLog : Applicatin error EventID 1000, Error
Faulting application name: mRemoteNG.exe, version: 1.75.7008.17907, time stamp: 0x5942ae47
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x05fd067e
Faulting process id: 0x29f8
Faulting application start time: 0x01d2ee8c9d8a1f61
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: unknown
Report Id: dca172b1-5a7f-11e7-80f5-005056bd1c0b
Faulting package full name: 
Faulting package-relative application ID: 

Error at the crash 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	mRemoteNG.exe
  Problem Signature 02:	1.75.7008.17907
  Problem Signature 03:	5942ae47
  Problem Signature 04:	mRemoteNG
  Problem Signature 05:	1.75.7008.17907
  Problem Signature 06:	5942ae47
  Problem Signature 07:	9ab
  Problem Signature 08:	12
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	5f25
  Additional Information 4:	5f2531ae070278f893fa99352dadd49e

Read our privacy statement online:
http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Report.WER file content 

Version=1
EventType=CLR20r3
EventTime=131429619065925583
ReportType=2
Consent=1
ReportIdentifier=0b04ff81-5a7e-11e7-80f5-005056bd1c0b
IntegratorReportIdentifier=0b04ff80-5a7e-11e7-80f5-005056bd1c0b
WOW64=1
NsAppName=mRemoteNG.exe
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=mRemoteNG.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.75.7008.17907
Sig[2].Name=Problem Signature 03
Sig[2].Value=5942ae47
Sig[3].Name=Problem Signature 04
Sig[3].Value=mRemoteNG
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.75.7008.17907
Sig[5].Name=Problem Signature 06
Sig[5].Value=5942ae47
Sig[6].Name=Problem Signature 07
Sig[6].Value=9ab
Sig[7].Name=Problem Signature 08
Sig[7].Value=12
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.NullReferenceException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.16.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=5861
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=5861822e1919d7c014bbb064c64908b2
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=5f25
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=5f2531ae070278f893fa99352dadd49e
UI[2]=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
UI[3]=mRemoteNG has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\SYSTEM32\KERNEL32.dll
LoadedModule[4]=C:\Windows\SYSTEM32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\SYSTEM32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\Windows\SYSTEM32\SHLWAPI.dll
LoadedModule[14]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[15]=C:\Windows\SYSTEM32\USER32.dll
LoadedModule[16]=C:\Windows\SYSTEM32\GDI32.dll
LoadedModule[17]=C:\Windows\system32\IMM32.DLL
LoadedModule[18]=C:\Windows\SYSTEM32\MSCTF.dll
LoadedModule[19]=c:\progra~2\citrix\system32\mfaphook.dll
LoadedModule[20]=C:\Windows\system32\RTWORKQ.DLL
LoadedModule[21]=C:\Windows\SYSTEM32\AVRT.dll
LoadedModule[22]=C:\Program Files (x86)\Citrix\system32\CtxMFPlugin.dll
LoadedModule[23]=C:\Windows\SYSTEM32\ole32.dll
LoadedModule[24]=C:\Windows\SYSTEM32\OLEAUT32.dll
LoadedModule[25]=C:\Windows\SYSTEM32\MF.dll
LoadedModule[26]=C:\Windows\SYSTEM32\MFPlat.DLL
LoadedModule[27]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[28]=C:\Windows\SYSTEM32\MFCORE.DLL
LoadedModule[29]=C:\Windows\SYSTEM32\ksuser.dll
LoadedModule[30]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[31]=C:\Program Files (x86)\Citrix\system32\CtxGraphicsHelper.dll
LoadedModule[32]=C:\Windows\SYSTEM32\SETUPAPI.dll
LoadedModule[33]=C:\Program Files (x86)\Citrix\system32\mmhook.dll
LoadedModule[34]=C:\Program Files (x86)\Citrix\system32\Sfrhook.dll
LoadedModule[35]=C:\Windows\SYSTEM32\WTSAPI32.dll
LoadedModule[36]=C:\Program Files (x86)\Citrix\system32\ShellHook.dll
LoadedModule[37]=C:\Windows\SYSTEM32\SHELL32.dll
LoadedModule[38]=C:\Program Files (x86)\Citrix\system32\scardhook.dll
LoadedModule[39]=C:\Program Files (x86)\Citrix\system32\twnhook.dll
LoadedModule[40]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[41]=C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[42]=C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\9bc9fee57df2a57a6240f7f470ec1222\mscorlib.ni.dll
LoadedModule[43]=C:\Windows\system32\uxtheme.dll
LoadedModule[44]=C:\Program Files (x86)\Citrix\System32\sehook20.dll
LoadedModule[45]=C:\Windows\SYSTEM32\MSVCR120.dll
LoadedModule[46]=C:\Program Files (x86)\Citrix\System32\cutildll.dll
LoadedModule[47]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[48]=C:\Windows\SYSTEM32\ACTIVEDS.dll
LoadedModule[49]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[50]=C:\Program Files (x86)\Citrix\System32\ctxwsapi.dll
LoadedModule[51]=C:\Windows\SYSTEM32\adsldpc.dll
LoadedModule[52]=C:\Windows\SYSTEM32\netutils.dll
LoadedModule[53]=C:\Windows\SYSTEM32\srvcli.dll
LoadedModule[54]=C:\Windows\SYSTEM32\wkscli.dll
LoadedModule[55]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[56]=C:\Windows\SYSTEM32\WLDAP32.dll
LoadedModule[57]=C:\Windows\SYSTEM32\LOGONCLI.DLL
LoadedModule[58]=C:\Windows\SYSTEM32\NSI.dll
LoadedModule[59]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[60]=C:\Windows\SYSTEM32\SAMCLI.DLL
LoadedModule[61]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[62]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System\5df585584381151e83bfc54fe1871cdb\System.ni.dll
LoadedModule[63]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\5cf61f792cd7e170c732974525d11d16\System.Configuration.ni.dll
LoadedModule[64]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\08f825349a5263b5fa06b976585c1927\System.Core.ni.dll
LoadedModule[65]=C:\Windows\SYSTEM32\version.dll
LoadedModule[66]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[67]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[68]=C:\Windows\SYSTEM32\WININET.dll
LoadedModule[69]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[70]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[71]=C:\Windows\SYSTEM32\SHCORE.dll
LoadedModule[72]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[73]=C:\Windows\system32\rsaenh.dll
LoadedModule[74]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[75]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Drawing\b78ba048842088d08f7d1486c50cbdd8\System.Drawing.ni.dll
LoadedModule[76]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\35d703cd56c74317f28557c64ab87c9f\System.Windows.Forms.ni.dll
LoadedModule[77]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\2068d496bd4fd80f57502dc1d794ee53\System.Xml.ni.dll
LoadedModule[78]=C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Management\2ae50a41775bc99be18128213d7e07d8\System.Management.ni.dll
LoadedModule[79]=C:\Windows\SYSTEM32\clbcatq.dll
LoadedModule[80]=C:\Windows\system32\wbem\wmiutils.dll
LoadedModule[81]=C:\Windows\SYSTEM32\wbemcomn.dll
LoadedModule[82]=C:\Windows\SYSTEM32\WS2_32.dll
LoadedModule[83]=C:\Windows\system32\wbem\wbemprox.dll
LoadedModule[84]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\wminet_utils.dll
LoadedModule[85]=C:\Windows\system32\wbem\wbemsvc.dll
LoadedModule[86]=C:\Windows\system32\wbem\fastprox.dll
LoadedModule[87]=C:\Windows\SYSTEM32\psapi.dll
LoadedModule[88]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=mRemoteNG
AppPath=C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=322A9C1C41EF8266868A9FF8107ED190

Log file (tried to increase log4net loglevel to debug but couldn't get any)

when it doesn't work  we get

2017-06-26 16:58:05,517 [1] INFO - mRemoteNG 1.75.7008.17907 starting.
2017-06-26 16:58:05,528 [1] INFO - Command Line: System.String[]
2017-06-26 16:58:07,616 [1] INFO - Microsoft Windows Server 2012 R2 Standard  64-bit
2017-06-26 16:58:07,617 [1] INFO - Microsoft .NET CLR 4.0.30319.36366
2017-06-26 16:58:07,617 [1] INFO - System Culture: en-US/English (United States)
2017-06-26 16:58:07,617 [1] INFO - Checking FIPS Policy...
2017-06-26 16:58:07,618 [1] INFO - Checking Lenovo AutoScroll Utility...

and then no user.config file created neither any xml file

Thank you in advance for your help

**Comment by sparerd** [comment]
I took a quick look at this and think I know why this is happening.

In `IeBrowserEmulation.Register():201` we get some sort of exception - not great but we should be able to handle it. We catch the exception as expected, but the issue comes in line `IeBrowserEmulation.Register():205`. We try to add this message to the message collector, but at this point in the startup the message collector hasn't been initialized.

Relevant stack trace bits:
```Exception Info: System.NullReferenceException
Stack:
at mRemoteNG.Tools.IeBrowserEmulation.Register()
at mRemoteNG.App.Startup.InitializeProgram()

The good news is that this has already been solved. The bad news is that it wasn't originally scheduled for release until v1.76. We can look into cherry-picking the necessary changes into a patch.

**Comment by lucbobski** [comment]
Thank you sparerd for the explanations.
Looking foward for the patch or the new version :)
Many thanks for your quick analysis

**Comment by lucbobski** [comment]
Do you know if it's possible to by pass via the mRemoteNG.exe.config file ?

**Comment by lucbobski** [comment]
Hi sparerd, I could find a solution, it appeared to be windows registry issue. We couldn't create new key under HK_current_user\software/Microsoft/internetexplorer/Main  it looked that the program has to write a subkey in this location in order to set permissions for mremoteNG to use the IE feature control. I just deleted this key HK_current_user\software/Microsoft/internetexplorer/Main then relaunched IE and checked that all settings came back (and I could create a subkey from there) and then started mRemoteNG successfully. Thank you for your help

**Comment by sparerd** [comment]
No problem! We will still plan to resolve this issue in a patch in case others run into the same problem.

**Comment by sparerd** [comment]
Added a work around fix for the next patch (check MessageCollector for null).

A better fix (initialize the MessageCollector earlier in the startup sequence) will be included in the next major release.
