### ISSUE TITLE
Multi-exec/Parallel SSH feature

### ISSUE THREAD

**Issue by mrwulf** [mRemoteNG/mRemoteNG#611]
I would love to see someone implement a way to replicate typing to multiple sessions at the same time. I'm frequently diagnosing issues in small clusters (and love being able to "connect" to a folder and have all contained connections opened) and this would be a killer feature. For an example implementation, check out mobaxterm's multi-execution feature: http://mobaxterm.mobatek.net/features.html

**Comment by lolomin** [comment]
Hi,

I have just found this feature request while searching for the same thing and approve also the development of this feature on mRemoteNG, above all nowadays when clusters are being deployed a lot everywhere.

Regards,

Laurent

**Comment by larsen0815** [comment]
@mrwulf @lolomin You might be interested in https://github.com/jimradford/superputty
I regularly use this to connect to all of my ~40 linux servers and execute commands simultaneously.

**Comment by sparerd** [comment]
This feature will be available in v1.76
