### ISSUE TITLE
Horizontal bar

### ISSUE THREAD

**Issue by joseaguardia** [mRemoteNG/mRemoteNG#613]
Hello.

In this version the horizontal bar is hidden and I can't see the entire name of some connections.

http://imgur.com/a/DW9qw

Regards

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7000.19194  |

**Comment by sparerd** [comment]
Duplicate of #600 - please follow that issue for further updates
