### ISSUE TITLE
Credits.txt file is refering to Putty 0.68 instead of 0.69

### ISSUE THREAD

**Issue by igor2x** [mRemoteNG/mRemoteNG#615]
In mRemoteNG 1.75 hotfix 8 (I am using portable version) if looking into Tools | Component Check there is Putty with "Release: 0.69" info, but if looking into install folder there is file CREDITS.TXT with the following info: PuTTY 0.6**8**, which is obviously wrong it should be 0.69.

I know this is trivial issue, but it is little bit annoying little typos here and there. Maybe there should be no version numbers in CREDIT.TXT file or to have some commit checklist when components are updated and committed to also update version numbers.

**Comment by sparerd** [comment]
I agree with not including version numbers in the credits file. Keeping that file updated when external components are updated is extra tedious work. If we want to have a way for folks to quickly check component versions we could create a screen within mRemoteNG to inspect them dynamically (similar to the current Component Check screen, just expanded).

@kmscode thoughts?

**Comment by kmscode** [comment]
Sounds like a plan!

**Comment by philippgille** [comment]
What's the location of the `credits.txt` in the repo? I can't find it with [this search on GitHub](https://github.com/mRemoteNG/mRemoteNG/search?utf8=%E2%9C%93&q=%22credits.txt%22&type=).

**Comment by sparerd** [comment]
@philippgille Its in the root level folder along with the Readme.md file. It's in all caps for some reason `CREDITS.TXT`, which might have thrown off your search.
