### ISSUE TITLE
Crashing when connecting to multiple RDP sessions

### ISSUE THREAD

**Issue by rimroot** [mRemoteNG/mRemoteNG#616]
Hi,
we have an issue when connecting to multiple RDP sessions. It crashes at the moment of login to RDP session. It usually happens when connecting to 8-11 RDP sessions. All remote servers are 2012 R2.

> Faulting application name: mRemoteNG.exe, version: 1.75.7008.17935, time stamp: 0x5942ae7f
> Faulting module name: ntdll.dll, version: 10.0.14393.479, time stamp: 0x58256ca0
> Exception code: 0xc00000fd
> Fault offset: 0x00046b6e
> Faulting process id: 0x2f8c
> Faulting application start time: 0x01d2ef35de3045ac
> Faulting application path: C:\Users\user\Downloads\mRemoteNG-Portable-1.75.7008.17935\mRemoteNG.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
> Report Id: 73af049e-03df-4cc5-9cf7-e80be22270f9
> Faulting package full name: 
> Faulting package-relative application ID: 

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.17935

**Comment by kmscode** [comment]
Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page.

Will need the stack trace to review this further.

**Comment by rimroot** [comment]
Is this what you need?

![image](https://user-images.githubusercontent.com/29730129/28669499-20f50768-72dd-11e7-988a-9fb0d5947fcb.png)

**Comment by kmscode** [comment]
No. The stack trace would like this:
https://github.com/mRemoteNG/mRemoteNG/issues/467#issue-216094441

It's generally logged in the Application event logs.

**Comment by farosch** [comment]
#328

**Comment by farosch** [comment]
Closing this as of inactivity.
@rimroot For us to further investigate we would need the stack trace. If this issue still exists for you please provide it to us.
