### ISSUE TITLE
Help text missing for Password protect item

### ISSUE THREAD

**Issue by igor2x** [mRemoteNG/mRemoteNG#617]
1. Make sure View | Connections and View | Config are both enabled.
2. In Connections panel click on "Connections" (the world icon).
3. Now click on Config panel and inside of panel click on "Password protect" item.
4. Still in Config panel at the bottom there is help window where it is bold text displayed "Password protect", but obviously if looking at other items there are two texts:
  - bold text (the same name as item from top Config dialog item)
  - normal text (item description).

  In the case of "Password protect" it is not clear what this option really does.
  It is trivial issue, but may I ask to add some description for this item please.

|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 hotfix 8  |

**Comment by farosch** [comment]
Good observation! I've added a description:
![image](https://user-images.githubusercontent.com/22905106/64079038-b56cea80-cce2-11e9-9972-cb87f5d3a7b3.png)
