### ISSUE TITLE
Over time ~ Keep Apprearing in my LINUX Sessions

### ISSUE THREAD

**Issue by jekish** [mRemoteNG/mRemoteNG#619]
I am running win10 on version 1.75.7008
When sessions are open I am receiving the ~ charicter in my sessions. I have to delete them to properly enter commands. 

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Are you using the out of the box PuTTYNG or a 3rd party PuTTY client?

As a workaround:
Ctrl + C would be a quick way to clear those to run your commands.

**Comment by farosch** [comment]
Closed due to inactivity of OP. Will be reopened if OP provides more info.
Likely already solved since two users (including me) were unable to reproduce this and OP was using an old alpha build.
