### ISSUE TITLE
Clone and build errors

### ISSUE THREAD

**Issue by mickeyperlstein** [mRemoteNG/mRemoteNG#626]
I decided to maybe fix my issues myself,
i cloned the repo
installed citrix (still dont really understand why)
installed nunit 3
installed wix toolset 3.11
re-referenced the wixExtension and UI to my localdir (was unable to figureout where to update the (WixExtDir)

###however i fall on the build:

## Error	
The command ":: When passing paths to powershell scripts, check if the path ends with a backslash "\"
:: If it does, then the backslash may be interpreted as an escape character. Add another backslash to cancel the first one.

powershell -noprofile -command "sleep 2"
set /p buildenv=<buildenv.tmp
set solutionDir=C:\devnew\tools\mRemoteNG\\
set targetDir=%cd%
set psScriptsDir=C:\devnew\tools\mRemoteNG\Tools
set certPath=
set certPassword=

:: Call the post build powershell script
powershell.exe -ExecutionPolicy Bypass -File "%psScriptsDir%\postbuild_mremotev1.ps1" -SolutionDir "%solutionDir%" -TargetDir "%targetDir%" -TargetFileName "mRemoteNG.exe" -ConfigurationName "%buildenv%" -CertificatePath "%certPath%" -CertificatePassword "%certPassword%" -ExcludeFromSigning "PuTTYNG.exe"" exited with code 1.	mRemoteV1			

this just fails and i dont know what to do, any help would be appreciated

**Comment by kmscode** [comment]
What version of VS a e you running? If you are building develop, you'll be better off with 2017. Master will need 2015. The community edition is fine.

If you build, run, test develop it will upgrade/convert your confcons.xml. So make a copy/backup. 

Citirx is needed because mRemoteNG can connect to Citrix servers. The build requires the libraries to be there or it will fail.

Don't worry about wix, and failures for it. that's for the installer.

I'm a bit disconnected right now, but I'll be back in civilization tomorrow afternoon/evening EDT. Due to the us holiday, my schedule is a bit packed... but... If you are still having problems, we could try to setup a chat on gitter or Google Hangouts for a screen share at some point this week. 

Thanks for the attempts and any contributions you can make to the project!!

**Comment by sparerd** [comment]
Look in the output window for the build, there may be a powershell script error. It might not have found a valid microsoft tool for editbin.exe or dumpbin.exe (needed for setting and validating the LargeAddressAware flag on the exe).

If that is what is causing the failure then we can look at a few ways to resolve.

**Comment by kmscode** [comment]
@mickeyperlstein Were you able to get the build going successfully?

**Comment by mickeyperlstein** [comment]
Sorry, busy day
This is my build error


Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ":: When passing paths to powershell scripts, check if the path ends with a backslash "\"
:: If it does, then the backslash may be interpreted as an escape character. Add another backslash to cancel the first one.

powershell -noprofile -command "sleep 2"
set /p buildenv=<buildenv.tmp
set solutionDir=C:\devnew\tools\mRemoteNG\\
set targetDir=%cd%
set psScriptsDir=C:\devnew\tools\mRemoteNG\Tools
set certPath=
set certPassword=

:: Call the post build powershell script
powershell.exe -ExecutionPolicy Bypass -File "%psScriptsDir%\postbuild_mremotev1.ps1" -SolutionDir "%solutionDir%" -TargetDir "%targetDir%" -TargetFileName "mRemoteNG.exe" -ConfigurationName "%buildenv%" -CertificatePath "%certPath%" -CertificatePassword "%certPassword%" -ExcludeFromSigning "PuTTYNG.exe"" exited with code 1.	mRemoteV1

**Comment by enc0mium** [comment]
I think the hint is in the error message.  Try removing the backslash at the end of the solutionDir line:

set solutionDir=C:\devnew\tools\mRemoteNG

**Comment by mickeyperlstein** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ":: When passing paths to powershell scripts, check if the path ends with a backslash "\"
:: If it does, then the backslash may be interpreted as an escape character. Add another backslash to cancel the first one.

powershell -noprofile -command "sleep 2"
set /p buildenv=buildenv.tmp
set solutionDir=C:\devnew\tools\mRemoteNG
set targetDir=%cd%
set psScriptsDir=C:\devnew\tools\mRemoteNG\Tools
set certPath=
set certPassword=

:: Call the post build powershell script
powershell.exe -ExecutionPolicy Bypass -File "%psScriptsDir%\postbuild_mremotev1.ps1" -SolutionDir "%solutionDir%" -TargetDir "%targetDir%" -TargetFileName "mRemoteNG.exe" -ConfigurationName "%buildenv%" -CertificatePath "%certPath%" -CertificatePassword "%certPassword%" -ExcludeFromSigning "PuTTYNG.exe"" exited with code 1.	mRemoteV1			


could you maybe show your build execution ?

**Comment by mickeyperlstein** [comment]
I tried to run it manually

powershell -ExecutionPolicy Bypass -File "c:\devnew\tools\mRemoteNG\Tools\postbuild_installer.ps1"

cmdlet postbuild_installer.ps1 at command pipeline position 1
Supply values for the following parameters:
SolutionDir: c:\devenv\tools\mRemoteNG
TargetDir: %cd%
TargetFileName: mRemoteNG.exe
ConfigurationName: buildenv.tmp
+=================================================================+
|             Beginning mRemoteNG Installer Post Build            |
+=================================================================+

Name               Value
----               -----
ExcludeFromSigning
TargetDir          %cd%
ConfigurationName  buildenv.tmp
SolutionDir        c:\devenv\tools\mRemoteNG
TargetFileName     mRemoteNG.exe


===== Beginning sign_binaries.ps1 =====
This is not a release build - we won't sign files.
===== Beginning verify_binary_signatures.ps1 =====
This is not a release build - we won't verify file signatures.

c:\devenv\tools\mRemoteNG
c:\devenv\tools\mRemoteNGInstallerProjects\Installer\bin\Release\en-US\mRemoteNG-Installer.msi
& : The term 'c:\devenv\tools\mRemoteNG\Tools\sigcheck.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\devnew\tools\mRemoteNG\Tools\rename_installer_with_version.ps1:12 char:13
+ $version = &"$SolutionDir\Tools\sigcheck.exe" /accepteula -q -n $targ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\devenv\tools...ls\sigcheck.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

%cd%
c:\devenv\tools\mRemoteNG\Release

anyway i turned it off, its a post build for signing or something. not important in development anyway

**Comment by mickeyperlstein** [comment]
I need your help
I want to add functionality to load servers from aws into mremoteNG

I want to read a config file that says what autoscaling groups you have and then load instances in the hierarchy of the servers.

all I need from any experienced (in mRemoteng) dev is a piece of code on how to add a connection and how to write a plugin.

**Comment by kmscode** [comment]
>all I need... ...and how to write a plugin
Oh... that's all? 😉 

So, we don't have any plugin interface currently. Any customizations, would need to be done directly in mremoteng code or through out of the box functionality (import and rdg file for example)...

>read a config file
An mremoteng config file? Which one?

>autoscaling groups
?

As noted, we don't have any plugin interface currently, however we do have some classes that assist with importing different types of source data:
https://github.com/mRemoteNG/mRemoteNG/blob/master/mRemoteV1/App/Import.cs

If you wanted to create a new connection, you'll need the [ConnectionInfo] (https://github.com/mRemoteNG/mRemoteNG/blob/master/mRemoteV1/Connection/ConnectionInfo.cs) object. An example of ussage can be found in [PortScanDeserializer](https://github.com/mRemoteNG/mRemoteNG/blob/master/mRemoteV1/Config/Serializers/PortScanDeserializer.cs#L76) (among others).

Feel free to ping us on Gitter: https://gitter.im/mRemoteNG/PublicChat

**Comment by Fyers** [comment]
I had the same error with VS 2017 Enterprise but after installing the missed c++ integration with the installer everything worked fine for me. Maybe same issue?

**Comment by kmscode** [comment]
@mickeyperlstein closing this one out. Feel free to reach out via other issues, Gitter https://gitter.im/mRemoteNG/PublicChat to submit any PRs if necessary.
