### ISSUE TITLE
MremoteNG crash

### ISSUE THREAD

**Issue by stufently** [mRemoteNG/mRemoteNG#628]
When I click config panel MremoteNG crash
From event viewr

EventData 

   Application: mRemoteNG.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at System.Windows.Forms.UnsafeNativeMethods.LoadLibrary(System.String) at System.Windows.Forms.Control+ControlAccessibleObject.set_Handle(IntPtr) at System.Windows.Forms.Control+ControlAccessibleObject..ctor(System.Windows.Forms.Control) at System.Windows.Forms.PropertyGridInternal.PropertyGridView+PropertyGridViewAccessibleObject..ctor(System.Windows.Forms.PropertyGridInternal.PropertyGridView) at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CreateAccessibilityInstance() at System.Windows.Forms.Control.get_AccessibilityObject() at System.Windows.Forms.PropertyGridInternal.GridEntry.set_Focus(Boolean) at System.Windows.Forms.PropertyGridInternal.PropertyGridView.OnGotFocus(System.EventArgs) at System.Windows.Forms.Control.WmSetFocus(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.PropertyGridInternal.PropertyGridView.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)  

 mRemoteNG.exe 
   1.75.7008.17935 
   5942ae7f 
   pshook.dll_unloaded 
   4.3.6.1853 
   58a6d2a6 
   c0000005 
   00002b80 
   37b4 
   01d2f3d0804d704a 
   C:\temp\mremote2\mRemoteNG.exe 
   pshook.dll 
   0585937c-7698-49a1-8661-a230e06ac479 

Windows report
Version=1
EventType=BEX
EventTime=131435417015138138
ReportType=2
Consent=1
UploadTime=131435417022706658
ReportStatus=268435456
ReportIdentifier=9bdd25fd-ac3c-4b95-9ae6-3bfdbf27a00f
IntegratorReportIdentifier=0585937c-7698-49a1-8661-a230e06ac479
Wow64Host=34404
Wow64Guest=332
NsAppName=mRemoteNG.exe
AppSessionGuid=000037b4-0001-0004-4a70-4d80d0f3d201
TargetAppId=W:00063c865437571ff4bcadeab2dfa79a4cec00000000!0000b557393f8c3f1f1c4452bdc899043b2b1d9fb71d!mRemoteNG.exe
TargetAppVer=2017//06//15:15:57:51!14df55!mRemoteNG.exe
BootId=4294967295
ServiceSplit=3539031
TargetAsId=67510
Response.BucketId=770885ad39e2dc3ebb623f26023bdb1c
Response.BucketTable=5
Response.LegacyBucketId=116401143043
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=mRemoteNG.exe
Sig[1].Name=Application Version
Sig[1].Value=1.75.7008.17935
Sig[2].Name=Application Timestamp
Sig[2].Value=5942ae7f
Sig[3].Name=Fault Module Name
Sig[3].Value=pshook.dll_unloaded
Sig[4].Name=Fault Module Version
Sig[4].Value=4.3.6.1853
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=58a6d2a6
Sig[6].Name=Exception Offset
Sig[6].Value=00002b80
Sig[7].Name=Exception Code
Sig[7].Value=c0000005
Sig[8].Name=Exception Data
Sig[8].Value=00000008
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=1166
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=11664e1249ccfb63b493e251b39a3d75
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=4606
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=46060baedf4e510978068aacead10d28
UI[2]=C:\temp\mremote2\mRemoteNG.exe
UI[3]=mRemoteNG has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\temp\mremote2\mRemoteNG.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[14]=C:\WINDOWS\System32\combase.dll
LoadedModule[15]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[16]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[18]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[19]=C:\WINDOWS\System32\USER32.dll
LoadedModule[20]=C:\WINDOWS\System32\win32u.dll
LoadedModule[21]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[22]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[24]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[26]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\60168c5ef35b35be068c18c672f7ba34\mscorlib.ni.dll
LoadedModule[27]=C:\WINDOWS\System32\ole32.dll
LoadedModule[28]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[29]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[30]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\ba223c5c083a41166f7b7d790879f789\System.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\1bdacc82098e745c7eacfe10be776e59\System.Core.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Configuration\efca6f656ffd237f59b7541ff1acbe39\System.Configuration.ni.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[35]=C:\WINDOWS\System32\shcore.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[37]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[38]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[39]=C:\WINDOWS\System32\profapi.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\msiso.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[43]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[44]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[45]=C:\WINDOWS\System32\shell32.dll
LoadedModule[46]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[47]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Drawing\70acc1acf2e52050f5f9d8fbf33bdedf\System.Drawing.ni.dll
LoadedModule[48]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\76807b8a6a26dbae040543cb64fdc509\System.Windows.Forms.ni.dll
LoadedModule[49]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml\7d8bd5ee70f8ba414fc6ace0d6121400\System.Xml.ni.dll
LoadedModule[50]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Management\da4be058e46dd2e05ee952b4179bc240\System.Management.ni.dll
LoadedModule[51]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[52]=C:\WINDOWS\system32\wbem\wmiutils.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\wbemcomn.dll
LoadedModule[54]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[55]=C:\WINDOWS\system32\wbem\wbemprox.dll
LoadedModule[56]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\wminet_utils.dll
LoadedModule[57]=C:\WINDOWS\system32\wbem\wbemsvc.dll
LoadedModule[58]=C:\WINDOWS\system32\wbem\fastprox.dll
LoadedModule[59]=C:\WINDOWS\System32\psapi.dll
LoadedModule[60]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.15063.413_none_55bc94a37c2a2854\comctl32.dll
LoadedModule[61]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_583b8639f462029f\comctl32.dll
LoadedModule[62]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[63]=C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.15063.0_none_d802f55807fa1ec7\gdiplus.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[65]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[67]=C:\Program Files (x86)\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[68]=C:\WINDOWS\System32\TextInputFramework.dll
LoadedModule[69]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[70]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\usermgrcli.dll
LoadedModule[74]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[75]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[76]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[77]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[78]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[79]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Data\b7976fc761d4bb54ef6aba77b55b99bf\System.Data.ni.dll
LoadedModule[80]=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[81]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[82]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[83]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Web\6a392c2d368f28b72d03d9880667d22d\System.Web.ni.dll
LoadedModule[84]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[87]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.V9921e851#\4b18da24fdacfab1714b9ed8faa11ed1\Microsoft.VisualBasic.ni.dll
LoadedModule[88]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Dired13b18a9#\36fd3d404de36e68667199d20ac1a1c1\System.DirectoryServices.ni.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\activeds.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\adsldpc.dll
LoadedModule[91]=C:\WINDOWS\System32\WLDAP32.dll
LoadedModule[92]=C:\WINDOWS\system32\adsldp.dll
LoadedModule[93]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[94]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[95]=C:\WINDOWS\system32\wshqos.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\wshtcpip.DLL
LoadedModule[97]=C:\WINDOWS\SYSTEM32\wship6.dll
LoadedModule[98]=C:\WINDOWS\SYSTEM32\logoncli.dll
LoadedModule[99]=C:\WINDOWS\SYSTEM32\netutils.dll
LoadedModule[100]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[101]=C:\WINDOWS\System32\NSI.dll
LoadedModule[102]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[103]=C:\Windows\System32\rasadhlp.dll
LoadedModule[104]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[105]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\WindowsBase\4e702b73935a90b472d873558141feff\WindowsBase.ni.dll
LoadedModule[106]=C:\WINDOWS\System32\comdlg32.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\XmlLite.dll
LoadedModule[108]=C:\WINDOWS\SYSTEM32\LINKINFO.dll
LoadedModule[109]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[110]=C:\WINDOWS\system32\explorerframe.dll
LoadedModule[111]=C:\WINDOWS\system32\DUI70.dll
LoadedModule[112]=C:\WINDOWS\system32\DUser.dll
LoadedModule[113]=C:\Windows\System32\thumbcache.dll
LoadedModule[114]=C:\Windows\System32\Windows.Globalization.dll
LoadedModule[115]=C:\Windows\System32\Bcp47Langs.dll
LoadedModule[116]=C:\WINDOWS\SYSTEM32\globinputhost.dll
LoadedModule[117]=C:\WINDOWS\system32\OLEACC.dll
LoadedModule[118]=C:\Windows\System32\uiautomationcore.dll
LoadedModule[119]=C:\WINDOWS\SYSTEM32\atlthunk.dll
LoadedModule[120]=C:\WINDOWS\System32\StructuredQuery.dll
LoadedModule[121]=C:\WINDOWS\system32\Windows.Storage.Search.dll
LoadedModule[122]=C:\Windows\System32\Windows.StateRepository.dll
LoadedModule[123]=C:\Windows\System32\StateRepository.Core.dll
LoadedModule[124]=C:\WINDOWS\System32\coml2.dll
LoadedModule[125]=C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
LoadedModule[126]=C:\Windows\System32\twinapi.dll
LoadedModule[127]=C:\WINDOWS\SYSTEM32\ntshrui.dll
LoadedModule[128]=C:\WINDOWS\SYSTEM32\srvcli.dll
LoadedModule[129]=C:\WINDOWS\SYSTEM32\cscapi.dll
LoadedModule[130]=C:\WINDOWS\system32\WINMM.dll
LoadedModule[131]=C:\WINDOWS\SYSTEM32\winmmbase.dll
LoadedModule[132]=C:\Windows\System32\ActXPrxy.dll
LoadedModule[133]=C:\WINDOWS\system32\mssprxy.dll
LoadedModule[134]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[135]=C:\WINDOWS\system32\NetworkExplorer.dll
LoadedModule[136]=C:\WINDOWS\SYSTEM32\policymanager.dll
LoadedModule[137]=C:\WINDOWS\SYSTEM32\msvcp110_win.dll
LoadedModule[138]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml.Linq\de110324b29b8a36aabf447f8193d007\System.Xml.Linq.ni.dll
LoadedModule[139]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[140]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Accessibility\d994c79f29be82786b1d79e6e5a833f7\Accessibility.ni.dll
LoadedModule[141]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=BEX
AppName=mRemoteNG
AppPath=C:\temp\mremote2\mRemoteNG.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=69853C4A45B15F644E0F830E956B5F63
MetadataHash=-815481582

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 7008  |

**Comment by stufently** [comment]
Solved
deleted program Punto Switcher

**Comment by kmscode** [comment]
Closing due to the fact that the crash is in a module (pshook.dll) associated with a virus:
https://www.symantec.com/security_response/writeup.jsp?docid=2015-120705-5313-99&tabid=2
