### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by particularly** [mRemoteNG/mRemoteNG#632]
When opening version 1.75.7007.16235 of mRemoteNG and going to full screen after connecting to a server my console tab it very small and doesn't use all the room it can [example](http://prntscr.com/fscywm) I have tried reinstall and everything. Nothing seems to fix it.

|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7007.16235 |

**Comment by ouldskuhl** [comment]
Try to disable TeamViewer's Quick Connect feature

**Comment by AnthonyHebig** [comment]
"Try to disable TeamViewer's Quick Connect feature" >> worked for me

**Comment by pedro2555** [comment]
why is this still open?

**Comment by sparerd** [comment]
No one closed it :P
