### ISSUE TITLE
Update PuTTYNG to 0.70

### ISSUE THREAD

**Issue by igor2x** [mRemoteNG/mRemoteNG#635]
Putty 0.70 was released:
https://www.chiark.greenend.org.uk/~sgtatham/putty/releases/0.70.html

Release notes states there were security fixes for Putty:
https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

**Comment by LIyoai** [comment]
Security fixes should get a higher priority.
Maybe you can fix this and then release hotifx 9 and move all other open issues in this milestone to hotfix 10?

**Comment by kmscode** [comment]
@LIyoai - time was the big problem. 

Changes have been merged into the [PuTTYNG repo](https://github.com/mRemoteNG/PuTTYNG) having what is likely a minor problem on our build system. Once the build is completed I'll check in the binary to this repo and we'll be one step further. Still going to try to squeak out some more fixes for this release.
