### ISSUE TITLE
mRemoteNG crashes when clicking the Connections (blue marble) drop-down - Sporadic Issue

### ISSUE THREAD

**Issue by sibernetik** [mRemoteNG/mRemoteNG#637]
Every once in a while mRemoteNG will crash when I click on the Connections (blue marble) drop-down. I have attached the Windows Error logs as well as a crash dump file.
[Windows Event Log.txt](https://github.com/mRemoteNG/mRemoteNG/files/1143199/Windows.Event.Log.txt)
[CrashDumps.zip](https://github.com/mRemoteNG/mRemoteNG/files/1143204/CrashDumps.zip)

|||
|--:|---|
|Operating system | Windows 10 Enterprise x64 v1703 |
|mRemoteNG version| 1.75.7008  |

**Comment by kmscode** [comment]
Do you have any more events in the application log which might show a stack trace?

Unfortunately it looks like I don't have symbols for the 7008 binary so I can see the specific of the dump. I've opened #647 to ensure that we created and save symbols accordingly.
