### ISSUE TITLE
putty restart session closes connection

### ISSUE THREAD

**Issue by waltervdb** [mRemoteNG/mRemoteNG#64]
With mRemoteNG 1.67 and Putty 0.60 I have a problem using the Putty feature 'restart session'.

When my SSH2 connection gets disconnected because I lost my network connection, its tab is still visible in mRemoteNG. Putty detects that the connection is lost and if you press control + right mouse button in the panel Putty offers the option to 'restart session'.

When I choose this I expect to see the SSH login prompt in that panel so that I can continue and keep the history of the previous session in the panel.

The problem is that mRemoteNG closes the panel instead.

It must be related to the automatic login, because if I leave the Username and Password fields in the Config panel empty for the connection, all works as expected.

**Comment by izmogikan** [comment]
_Workaround From Jira:_

> Sean K
> October 19, 2016, 6:38 PM
> 
> Note:
> Right click on mRemoteNG tab -> Reconnect -> Session is closed and reopened - history is lost
> 
> Ctrl + Right click in session window to bring up PuTTY menu -> Restart session - history IS NOT lost.
