### ISSUE TITLE
issue with Maximize when application is ideal

### ISSUE THREAD

**Issue by pidile007** [mRemoteNG/mRemoteNG#641]
Maximize is not working properly after some time when application kept ideal. either need to retore and work or close and reopne. no matter windows/linux session i have.
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
I'm sorry. I don't fully understand. Could you please clarify and/or provide screenshots/[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)?

**Comment by kmscode** [comment]
closing due to no response.
