### ISSUE TITLE
Impossible to use external apps with password

### ISSUE THREAD

**Issue by FR-TheS** [mRemoteNG/mRemoteNG#643]
Impossible to connect with winscp or filezila because password contains some characters like "<" which is not useful for password.
Needs to be double quote.

Will have us an SFTP client someday?

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7008.17935  |

**Comment by LIyoai** [comment]
Use %!Password%
https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools

**Comment by FR-TheS** [comment]
Nice, I didn't see this option.
It work, thanks you !

**Comment by kmscode** [comment]
Thanks @LIyoai for replying to this. I wasn't able to get to it quick enough...
