### ISSUE TITLE
AltGr key combinations stop working in other apps when connected to RDP

### ISSUE THREAD

**Issue by skajfes** [mRemoteNG/mRemoteNG#655]
AltGr keyboard combinations stop working in other applications when connected to RDP.
The issue is that my keyboard layout is set to Croatian (or Standard keyboard in windows 10) and AltGr key combinations are used to type braces, brackets and such. (using AltGr + v, g, h, b, n)

I've noticed that this occurs only after the RDP connection is reconnecting automatically, while mRemoteNg is not in focus. After I focus the mRemoteNg window it works correctly again.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.17907  |

Related issue:  #95

**Comment by Bjorn4Work** [comment]
I just want to confirm this issue. AltGr stops working and it's impossible to @£$ etc. which is very annoying.

**Comment by hangy** [comment]
FWITW, I've also repeatedly had this problem on Windows 8.1 when connected to RDP, but also  _without_ mRemoteNG being involved. Disconnecting the RDP session always helps, so this might very well not be an issue that can be solved by mRemoteNG.

**Comment by WilliamVannuffelen** [comment]
I can confirm that this issue is not related to mRemoteNG. I personally always use mRemoteNG and have never noticed this issue, but I manage a RemoteApp environment for several thousand users and sometimes hear these complaints from people using RDP (nobody uses mRemoteNG). This has been a known issue (without known solution) in RDP since at least XP/Server 2003.

**Comment by sparerd** [comment]
Thanks @hangy and @WilliamVannuffelen for providing some context around this. I will create a FAQ entry for this issue

**Comment by sparerd** [comment]
FAQ entry: https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#altgrstopsworking

**Comment by Clebam** [comment]
FAQ entry 2020 : https://mremoteng.readthedocs.io/en/latest/known_issues.html#altgr-key-combinations-stop-working-in-other-apps-when-connected-to-rdp
