### ISSUE TITLE
Unable to Add new folder and add new connection

### ISSUE THREAD

**Issue by ezalae** [mRemoteNG/mRemoteNG#657]
when i clicked on add new connection and add new folder, nothing happens.

**Comment by kmscode** [comment]
Sorry for the delay... Do you have existing connections? Do those function properly? Or is this a new install?

Please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

**Comment by ezalae** [comment]
New install..

**Comment by pedro2555** [comment]
Probably fixed by #705

**Comment by sparerd** [comment]
The potential fix submitted by @pedro2555 will be release in patch 9 shortly. Please reopen this issue if the new update does not resolve the issue
