### ISSUE TITLE
Keep Port Scan Tab After Import

### ISSUE THREAD

**Issue by changbowen** [mRemoteNG/mRemoteNG#658]
Is it possible to keep the Port Scan tab (and scan results) when I click import? Sometimes i want to import multiple protocols and i can't do that without having to scan twice.

**Comment by changbowen** [comment]
it's OK as i just found out it can be done via right click menu. so not important right now...

**Comment by kmscode** [comment]
Nope... I agree... It's annoying and we don't close other windows/tabs like this...
