### ISSUE TITLE
Multitab in one view

### ISSUE THREAD

**Issue by stevealexandre** [mRemoteNG/mRemoteNG#661]
Hi team,

It can be powerfull if we can see 2 or 4 tab in one view.
Like that, we can do a job in one tab and supervise in other tab.
I don't know if i'm the only one who is asking this feature.
Something like that
![screen](https://user-images.githubusercontent.com/21204359/28662510-b180841a-72ba-11e7-98b0-5706416becf4.PNG)

**Comment by fred9176** [comment]
+1, this feature is great

**Comment by sarus** [comment]
Turns out you can do this already (it's just not very intuitive).  See this issue #257.

You have to create the connection panels and move them before you add a connection to it:

![image](https://user-images.githubusercontent.com/306319/29547561-bc9d42d0-86c8-11e7-9d79-50cedd094036.png)

Once you add the panel, click and drag it to where you want:

![image](https://user-images.githubusercontent.com/306319/29547563-cc0badd8-86c8-11e7-8ce2-e80cf80401bc.png)

**Comment by mrwulf** [comment]
It seems like not being able to move a connection between panels greatly limits this feature. I've been toying with adding an option to always create connections in their own panel. Then the awesome built in docking always just works. Thoughts?

**Comment by silicoid** [comment]
Hi

Using the Panels is actually not a good solution. e.g. I have RDP and SSH connections. If I do this with Panels then my RDP sessions get resized. If I could have tabs side side beside within a panel then I could put ssh sessions side by side without interfering with the RDP sessions.

**Comment by BloodyIron** [comment]
Any chance we can get this extended so I can drag existing sessions to the new connection view? Please?

**Comment by sparerd** [comment]
I believe this is resolved by #155 and #1258. Connections can now be moved and docked in whatever configuration you would like.

**Comment by BloodyIron** [comment]
@sparerd I didn't see any way to do this for established connections

**Comment by sparerd** [comment]
It will be available in v1.77. We are getting ready to release an alpha version hopefully by the end of February.

**Comment by BloodyIron** [comment]
Yay! \o/

**Comment by kmscode** [comment]
Still gearing up for the 1.77 release, but closing this one out so the changelog can be updated with all closed 1.77 tagged issues.

**Comment by how-do-i-computer** [comment]
> It will be available in v1.77. We are getting ready to release an alpha version hopefully by the end of February.

I'm on 1.77.2 and don't see a way to do this. Only the clunky Connection Panel workaround, which requires selecting the second panel before starting the connection. Am I missing something?
