### ISSUE TITLE
Bug on connections panel with first putty session

### ISSUE THREAD

**Issue by cryptage21** [mRemoteNG/mRemoteNG#663]
Hi,

I've detected a bug with SSH sessions (Putty).
After launching mRemoteNG, if you start a SSH connection, it's working perfectly.

To open a second connection, I click on the "connections panel" and when I want to write the name of the session, it's writing in the opened putty tab instead of selecting the name of the session in the list.

After another click on the list, that's good. With 2 or more opened tabs, it's working correctly too.
The problem is only when there's only one putty session.

Could you please check this issue ? I'm using mRemoteNG 1.75 Hotfix 8.

Best regards

**Comment by kmscode** [comment]
This is just another scenario caused by focus issues with puttyng. See #290
