### ISSUE TITLE
Can not add new connection or new folder

### ISSUE THREAD

**Issue by iahim** [mRemoteNG/mRemoteNG#665]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| mRemoteNG-Portable-1.75.7008.17935  |

I have just downloaded the portable version and tried to add a new connection or a connection folder. It just doesn´t do anything. 
I tried from the file menu or from the right click menu... and the same issue.

**Comment by Michaellcosta** [comment]
I just installed version 1.75.7008.17907 and am having the same problem.

**Comment by vordee** [comment]
Same problem.

Windows 10 Pro

**Comment by eli-b** [comment]
Same here.
Windows 10 Pro.
Components check shows everything in green except Citrix ICA.
Version 1.75.7008.17907.

**Comment by bpazzetti** [comment]
I have the same isssue, workaround, click on (select) Connections, then you can create a new connection

**Comment by kmscode** [comment]
Resolved via PR #705
