### ISSUE TITLE
Feature Request: Panel layout should be defaults on install/upgrade

### ISSUE THREAD

**Issue by garyhahn** [mRemoteNG/mRemoteNG#668]
|||
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

When I upgraded to 1.75.7008.17907, it took me about 10 minutes to figure out how to even start to use the application, having come from what I think was a no-panels version.  I didn't understand what had happened...just thought the app was completely not functioning properly at first....even reinstalled.  Then I figured out the panels feature must have been added; noting some grab points, but still could not even find the Config panel, even though it showed active in the View menu.  Ultimately I finally found the "Reset Layout" menu option and got back my old, beloved view: Connections upper left, Config lower left, in progress "General" sessions large and right.   My suggestion would be that upgrading from no-panels to panels version should automatically reset layout; or check for pre-upgrade layout and retain.  Not sure what will happen the next time I upgrade, but at least I know to reset layout.

Thanks for a great product, in general!  Love it.

**Comment by sparerd** [comment]
Hi @garyhahn sorry that cause you some grief - we've noticed that the layout can become corrupted during an upgrade and we haven't yet figured out why. Glad it didn't discourage you!

**Comment by djsmiley2k** [comment]
I have a simular issue, except my layout doesn't save.... ever.

Each time I launch the application I have to go to reset view again.

Do you want me to create a new issue with a log, I'm unsure of what's required to try and debug this?

**Comment by Kvarkas** [comment]
close as not actual at the moment of new version
