### ISSUE TITLE
Fault Application

### ISSUE THREAD

**Issue by paolomarin-mq** [mRemoteNG/mRemoteNG#669]
|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008 |

Faulting application name: mRemoteNG.exe, version: 1.75.7008.17907, time stamp: 0x5942ae47
Faulting module name: KERNELBASE.dll, version: 10.0.15063.483, time stamp: 0xc3955624
Exception code: 0xe0434352
Fault offset: 0x000eb802
Faulting process id: 0x313c
Faulting application start time: 0x01d30c17b8fbd99a
Faulting application path: C:\Program Files (x86)\mRemoteNG\mRemoteNG.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a83bd1fe-9797-45b5-b653-dbb40824ff6a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by kmscode** [comment]
Do you have any more details about what lead up to the crash?

Please see the [troubleshooting and logging](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging) page and provide the stack trace and mremoteng.log so I can review this further.

**Comment by kmscode** [comment]
closing due to no response.
