### ISSUE TITLE
mRemoteNG is askig for a password whet I open it

### ISSUE THREAD

**Issue by John3** [mRemoteNG/mRemoteNG#670]
|||
|--:|---|
|Operating system | Windows 7 x64 Enterprise |
|mRemoteNG version| 1.75.7008.17935 |

Hi, today I was working as usual, close mRemoteNG (from X) and rebooted my machine, and then when I open mRemoteNG asked my for a password. I never added a password for the beginning of mRemoteNG.

Thanks to mRemoteNG do backups for confCons.xml, so I was seeing whats going on... all the confCons.xml from today 04/08/17 8:39am was encrypted, and if you try to open it ask for a password, so you can't use mRemoteNG.

From the backup I use a backup form yesterday 03/08/17 5:11pm, this is working.

Notice I closed yesterday like 5:11pm and I opened today from 8:00am and started use it until I reboot my machine like 8:39pm, after that, it asked for the password. If some config was added, when I opened today it needed to asked for the password, but this not happen, so I can used as usual until I restart my laptop. So what happen?

**Comment by John3** [comment]
not sure what to share, because the log not said something I can show, or any change in the configuration, or either I don't know how to replicate this. So I will closed. Thx

**Comment by lucasvanhalst** [comment]
Got the same, my confcons.xml only contained zeros. restoring a backup fixed it..
