### ISSUE TITLE
Portable version startup issue

### ISSUE THREAD

**Issue by SsjCosty** [mRemoteNG/mRemoteNG#676]
mRemoteNG supports a command line option to load a specific connections file:

> /cons:PathToConnectionsFile

The problem is that if I use this option on a freshly downloaded portable version of mRemoteNG, it will just open the program but with no connections loaded. If I close it and then open it again with the same command line option, then the connection file does get loaded on startup.

I have narrowed this down to the fact that when you first run the program it creates a new user.config file in
C:\Users\<user_folder>\AppData\Local\mRemoteNG\

When this config file exists, I can load preload connection files just fine, however if I delete the user.config file, then I get the same behavior where no connections get loaded during the first startup.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.17935  |

**Comment by sparerd** [comment]
Resolved by @pedro2555 

The fix will be available in the next release
