### ISSUE TITLE
New icon more noticable on windows black panel

### ISSUE THREAD

**Issue by anuar45** [mRemoteNG/mRemoteNG#681]

**Comment by kmscode** [comment]
Anyone good at Photoshop, etc...?

Looks like this is the "source" file for the icon:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Resources/Other%20Graphics/mRemoteNG%20-%20Icon.psd

But when I open it in Paint.Net (with the PSD Plugin) it doesn't look like our current icon... Best we have at the moment it seems... 

Starting from scratch would be fine too... 😄

**Comment by sparerd** [comment]
The psd files can be opened via GIMP too

**Comment by kmscode** [comment]
Resolved via #1232
