### ISSUE TITLE
During export host address not saves

### ISSUE THREAD

**Issue by ags67** [mRemoteNG/mRemoteNG#685]
|||During export host address not saves. After import from xml file the host address item does not exist
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by pedro2555** [comment]
Can you check that this behaviour is fixed for you on [1.75.7008](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8)?

I could confirm this is not the case on my side, all hostname/IP exported and have been imported successfully.

Using latest version as of today [1.75.7008](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Hotfix8)

**Comment by ags67** [comment]
Hello!

After update to 1.75.7008 problem solved.

Thaks!


>Пятница,  1 сентября 2017, 17:20 +03:00 от Pedro Rodrigues <notifications@github.com>:
>
>Can you check that this behaviour is fixed for you on  1.75.7008 ?
>I could confirm this is not the case on my side, all hostname/IP exported and have been imported successfully.
>Using latest version as of today  1.75.7008
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Best regards,
Andrew

**Comment by pedro2555** [comment]
Thank you sir for the help.

If one of the admins could mark this as closed. Thank you.
