### ISSUE TITLE
Citrix ICA Resource Mapping e.g. Disk Drives

### ISSUE THREAD

**Issue by PatMis16** [mRemoteNG/mRemoteNG#686]
In other tools like VisionApp Remode Desktop there is the feature to map Citrix ICA Ressources. For example the mapping of the Disk Drives in the Citrix environment to a connected Windows Server. There are a lot of benefits for file transfer and so on.

**Comment by kmscode** [comment]
Reference #1202 - Further Citrix support is not planned. Closing.
