### ISSUE TITLE
Cannot use Quick Connect box if the focus was on open connection/terminal

### ISSUE THREAD

**Issue by avolani** [mRemoteNG/mRemoteNG#688]
Often I use the quick connect input textbox / dropdown for ssh connection.
Since some release early this year, the input box has some focus issues.

When the focus is somewhere in the left panel i can move to the quick connect box and write / copy / use the dropdown.
When the focus is on a putty session, clicking mouse over the box seems highlight it, but i cannot copy / write or view the last used connections on the dropdown.

![immagine](https://user-images.githubusercontent.com/31508728/29922384-aaba6c0c-8e55-11e7-820e-fdd3897abdfb.png)

|--:|---|
|Operating system | Windows 10 pro x64 |
|mRemoteNG version| 1.75.7008.17907  |

**Comment by LIyoai** [comment]
Should be fixed in the next hotfix
https://github.com/mRemoteNG/mRemoteNG/issues/176

**Comment by avolani** [comment]
I confirm that the issue is fixed, thank you!

**Comment by Elokku** [comment]
Hello.
Thanks for fixing it in 1.75, however in v1.76 Alpha 1 this problem occurs again.

**Comment by sparerd** [comment]
I've reapplied the fix to v1.76 - it will be available in the next alpha build (alpha 3)
