### ISSUE TITLE
mRemoteNG saves User-Settings not in RoamingProfiles

### ISSUE THREAD

**Issue by tcn-pdr** [mRemoteNG/mRemoteNG#690]
User-Settings are saved in Path C:\ Users\ %Username%\ AppData\ Local\ mRemoteNG\ *Crypted Path*\ 1.75.7008.17907\ user.config and not in RoamingProfiles.
We use mRemoteNG on a Citrix XenApp Server and would like to set the User-Settings via GPO. The Problem is the CryptedPath where mRemoteNG saves the Settings. 
It would be nice to save the User-Settings in RoamingProfiles or in a path that is always the same. 
|||
|--:|---|
|Operating system | Windows Server 2012 x64 |
|mRemoteNG version| 1.75.7008.17907  |

**Comment by LIyoai** [comment]
Do you use the portable version?
https://github.com/mRemoteNG/mRemoteNG/issues/414 (scheduled for 1.76)
https://github.com/mRemoteNG/mRemoteNG/issues/487

**Comment by tcn-pdr** [comment]
No, we use the installed version

**Comment by sparerd** [comment]
@penguinairlines As of v1.76 the portable version saves user preferences in the same folder as mRemoteNG.exe. The installed version still saves to AppData\Local

(Thanks for pointing out the badges, I've updated them now)

**Comment by penguinairlines** [comment]
@sparerd Awesome! Looks like we can close this issue then!

**Comment by sparerd** [comment]
The installed (msi) version saves to AppData\Local and should still be changed

**Comment by penguinairlines** [comment]
Ah good point! Carry on then!

Keep up the awesome work guys, your tool is fantastic!

**Comment by kmscode** [comment]
Now that #414 is fixed in the portable version, we could fix this easily either with a quick change in PortableSettingsProvider - basically mimic what we do in SettingsFileInfo.cs:

```
public static string SettingsPath => Runtime.IsPortableEdition ? ExePath : Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\" + Application.ProductName;
```

**Comment by farosch** [comment]
Closed, because both versions (MSI and Portable) now use the `%APPDATA%` directory
