### ISSUE TITLE
CONTRIBUTION: How to?

### ISSUE THREAD

**Issue by pedro2555** [mRemoteNG/mRemoteNG#691]
Ok, this is more of a QA I want to host from the questions side.

I've cloned the project on my side to fixe something that was annoying me. And here are my questions:

1. There are 2 dependencies missing (`AxWFICALib.dll`, and `WFICALib.dll`), they seem to be ActiveX controls from the era where redistributables simply didn't exist. Is there a reason for those components not be included in the git tree?

2. I couldn't figure how you separate branches and versioning here, there's a `master` and a `develop` branch, and pull requests seem to prefer neither one or another, sometimes they target one others another. How is the scope separation for each, and where should I merge what?

3. The post build actions call for a script at `%psScriptsDir%\postbuild_mremotev1.ps1`, by that name there is `mRemoteNG\Tools\postbuild_mremotev1.ps1`. Is this the one? `%psScriptsDir%` does not resolve, how is it supposed to resolve?

Thanks for the time.

**Comment by kmscode** [comment]
@pedro2555 

Check out the wiki here:
https://github.com/mRemoteNG/mRemoteNG/wiki/Development-Environment

1.  The DLLs are part of the Citrix Receiver listed on that page.

1.  So... This one is a little more difficult to answer since we we hit some minor scheduling problems... In general, develop... But for now if you want to submit anything against [Patch9](https://github.com/mRemoteNG/mRemoteNG/tree/Patch9) that would likely be best...

1. Which branch were you working off of?


Feel free to ping us on [Gitter](https://gitter.im/mRemoteNG/PublicChat). I try to respond as quickly as I can on there - especially when I'm usually in front of a computer. :wink:

**Comment by pedro2555** [comment]
@kmscode 

Thanks for the help. Guess I missed the Wiki part of the deal :P, sorry my bad. But that should actually be noted in the readme.

1. Great, fixed.

2. I will take `develop` as the main branch then, and for now PRs to `patch9`

3. `Master`

**Comment by dekelMP** [comment]
@pedro2555 Did you manage to solve no. 3?

**Comment by pedro2555** [comment]
@dekeIMP thanks for checking in. I did not.

I'm deleting that script for development and pasting back in before pushing, pretty annoying..

**Comment by kmscode** [comment]
@pedro2555 

This is set in the post build event:

    set solutionDir=$(SolutionDir)\
    set targetDir=%cd%
    set psScriptsDir=$(SolutionDir)Tools

It should resolve only during the post build step.

However, I had just setup a new build env on my home system with VS 2017 Community and found some problems with some of the other postbuild steps. Take a look at my latest checking to the Patch9 branch and see if that resolves your problems.

If not, go to the "output" tab in VS and copy all of the build output:
![image](https://user-images.githubusercontent.com/16654335/30242815-82053bd0-956b-11e7-9660-92b5ee04981e.png)


The "Errors List" tab doesn't show all of the details and can sometimes be misleading.

**Comment by pedro2555** [comment]
Nop. Same thing.

![image](https://user-images.githubusercontent.com/1645623/30242850-3e4c0196-9596-11e7-9b7b-771d9bc5c7b8.png)

I'm at 6aaf2f03

**Comment by kmscode** [comment]
You'll need to install the wixtoolset for the Installer projects to load. See the wiki. If that doesn't help, save the full text from the output window and attach it as a .txt file to this issue and I'll review further.

**Comment by pedro2555** [comment]
@kmscode I'm closing this for now. I'm not really interested in building the installer, so it may take a while for me to look at this; if ever.

It is not preventing development/use in anyway, so, yeah better close this.

**Comment by jotatsu** [comment]
One thing to add here, lately i've been building the installer version lately for testing and the postbuild event always fails. This seems to be related to some shenanigans in the vs 2017 community, see https://github.com/dotnet/project-system/pull/2367   https://github.com/dotnet/sdk/issues/677  . 

I've ended doing the workaround mentioned in the issues as

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell.exe -ExecutionPolicy Bypass -File %22$(SolutionDir)Tools\postbuild_mremotev1.ps1%22 -SolutionDir %22$(SolutionDir)\%22 -TargetDir %22$(TargetDir)\%22 -TargetFileName %22mRemoteNG.exe%22 -ConfigurationName %22buildenv.tmp%22 " />
  </Target>

I dont sign the installers so i removed that part.
