### ISSUE TITLE
ConfCons.xml file is not saving connections with host details

### ISSUE THREAD

**Issue by swatityagi17** [mRemoteNG/mRemoteNG#694]
I am facing issue where i am dealing with multiple projects so for that i have created different folder with project name. Each Project folder contains sub folder that are for test, dev & prod environment and those folders have config like hostname username and password. When i am trying to reimport conf cons.xml file i cannot see sub folder under project one. All are blank. Also i can see multiple backup copies of confcons getting created every now n then
Please help asap

**Comment by kmscode** [comment]
The backup file generation is normal. 

Is mRemoteNG exiting normally? The confCons.xml is only saved at exit by default currently.

You could try Tools -> Options -> Connections -> Auto save every X minutes (set the value to something like 2-5 minutes).

**Comment by farosch** [comment]
Closed due to inactivity of OP.
