### ISSUE TITLE
Feature request: Add "Find Next (CTRL+G)" on Connection panel.

### ISSUE THREAD

**Issue by 4SiB** [mRemoteNG/mRemoteNG#696]
Please add the Find Next (CTRL+G) on bottom of connection panel. Now when I write "server-datacenter1-" and have got 3 that entries I must know and write next letter at least.
Those Find Next will be perfect to fast and found proper connection entry.

BR Marcin.

**Comment by pedro2555** [comment]
I agree.

**Comment by peter-franken** [comment]
When i using search, then press i press "cursor down" (Arrow down) and the next client comes in focus. I hope this helps.

**Comment by 4SiB** [comment]
Arrow UP/Down insted of ctrl+G is proper for me.
I hope in 1.77 integration with KeePassXC will be exist !.
