### ISSUE TITLE
Cisco SSH

### ISSUE THREAD

**Issue by thewos** [mRemoteNG/mRemoteNG#699]

**Comment by pedro2555** [comment]
connected and begin_disconnect scripts, maybe?

That actually sounds useful, having the option to script commands to be sent to, after a connection; or even to clean a connection before closing it (can't really think of anything, but I'm sure someone else can).

**Comment by sparerd** [comment]
Would be solved by #503

**Comment by sparerd** [comment]
Closing as duplicate - please follow #503 for updates
