### ISSUE TITLE
Ext apps with password containing '!' caracter

### ISSUE THREAD

**Issue by 21Damien** [mRemoteNG/mRemoteNG#711]
Hi,
Thank you for this project. 
I can't connect on my Unix servers via _sFTP (filezilla)_ if their passwords contains an exclamative point "!"
To see that i passed the %Password% argument instead of the %Hostname%, i saw that my Password is transformed.
`!someword! to ^!somewords^!`
Have you an idea ? 
The connection arguments are when i try directly to connect from a command line.

|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3 (1.75.7008.17907) |

**Comment by pedro2555** [comment]
You're passing a username and password to filezilla via the arguments option on the external tools window, correct?

**Comment by pedro2555** [comment]
Just confirmed this, and it does happen.

![image](https://user-images.githubusercontent.com/1645623/30371682-416b7958-9873-11e7-9270-0dcc68e6d935.png)

**Comment by kmscode** [comment]
This is working as designed. Use:

    %!PASSWORD%

Reference documentation: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools

**Comment by pedro2555** [comment]
Oddly, this took quite a while to understand. (probably needs some comment decoration around this code anyway)

You probably need [this](https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#variable-examples).

**Comment by jotatsu** [comment]
I'll add something i think it cannot be done currently. I'm trying to integrate with winscp and some password have characters like +. I did the exercise directly using cmd and this 
^+
Is not valid, but this works
 %2B
As far as i can see mremote cannot output hexa for file integreation, so maybe an improvement?

**Comment by 21Damien** [comment]
Hi!
Than you for you information. I type %!PASSWORD% and it works fine. 
My bad i escaped the documentation.
Problem solved cause no real problem.
