### ISSUE TITLE
App hanging on folder/connection rename

### ISSUE THREAD

**Issue by pedro2555** [mRemoteNG/mRemoteNG#713]
Renaming a connection/folder hangs the application for a couple seconds.

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008.7  |

**Comment by kmscode** [comment]
@pedro2555 I can't reproduce this at all...

Maybe set a break point in ConnectionTree.cs for RenameSelectedNode()? But since this UI element requires input, a breakpoint might not work so well... Log messages along the way to find out where the hang up is?

**Comment by pedro2555** [comment]
@kmscode don't worry too much. I posted this because it had just happened to me.

When double clicking the connection/folder name to allow renaming in place, when the control loses focus I'm getting a 500 to 2000ms stuter.

It might be due to a known issue in Windows 10 with my hardware. I'll post a link to the issue asap.

Anyway, I will look into it when I can find free time.

**Comment by pedro2555** [comment]
@kmscode Not sure about it, but probably was just a miss on some driver part on my side. Updated windows last night, and all seems fine.
