### ISSUE TITLE
allow for Connection Credendials to be embedded (as variables?) in the External Tools section

### ISSUE THREAD

**Issue by z-vap** [mRemoteNG/mRemoteNG#714]
For example, if one would want to use PSEXEC they could have %USERNAME% and %PASSWORD% variables to embed into the command line

**Comment by pedro2555** [comment]
They are

https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools

**Comment by z-vap** [comment]
is there a way to test this?  It doesn't seem to be working for me  I am using 1.75.7008.17907

**Comment by pedro2555** [comment]
I've just made a big round of testing yesterday, and I could not find any issue.

Can you post the full argument string you're passing to the external app?

**Comment by z-vap** [comment]
Most of my connections have the USERNAME and PASSWORD blank.  but in Options they get their connection parameters from there.   I tested this and it seems to show nothing for %USERNAME% %PASSWORD%.    

```
Filename :  CMD.EXE
Arguments:  /K TITLE %HOSTNAME%
Arguments:  /K TITLE %USERNAME%
Arguments:  /K TITLE %PASSWORD%
```
in the above the cmd window's title shows the hostname as it should, but the title is blank for username or password.

**Comment by pedro2555** [comment]
It seems neither username or password are set, then.

Does it work in a supported protocol? SSH, RDP? I suspect it doesn't.

You either have the credentials set explicitly or via inheritance, you must have one of those set for the connection you're trying to use, otherwise, if there is no username/password set, they will be blank as you report.

**Comment by sparerd** [comment]
Related to / duplicate of #492

**Comment by z-vap** [comment]
yeagh all connections work as they should.   Oh Ok so there is an open ticket on this.  Thanks

**Comment by pedro2555** [comment]
@sparerd thanks, looking later today.
