### ISSUE TITLE
scrollbars added to RDP window after minimize/restore of mRemoteNG

### ISSUE THREAD

**Issue by SanderP** [mRemoteNG/mRemoteNG#72]
This is also an issue with mRemote, I upgraded to mRemoteNG hoping this issue would be fixed. It's actually a little worse.
- maximize mRNG
- start RDP session
- note lack of scrollbars on bottom and right. This indicates the remote machine and mR agree on the desktop size
- minimize mRNG
- restore mRNG
- now one or two scroll bars appear. mR and remote machine no longer agree on desktop size
- on classic mR the following workaround can be used to restore proper window size: 'restore down' and 'maximize'. This does not work with mRNG.

Thanks for looking into this. mRNG is terrific besides this small issue.

**Comment by wkl17** [comment]
This issue is still exist. I'm using the mRemoteNG  v1.75.7005 (2017-04-27) .
