### ISSUE TITLE
Allow saving passwords outside of the connections file

### ISSUE THREAD

**Issue by codearoo** [mRemoteNG/mRemoteNG#721]
Passwords right now are saved encrypted into this XML file. It's nice we can export without the passwords, but it might be safer if we had an option to store the passwords using Windows security method.. or somewhere in the registry.

**Comment by sparerd** [comment]
This sort of enhancement will be enabled by #255. While we do not yet have a way to save/load credentials from other sources, that enhancement will make it possible. Another related enhancement is #187

**Comment by peterlouvel** [comment]
## Idea on why to separate the usernames/passwords from the connection list

SQL connection or even XML file
separate the connections from the usernames and passwords

so you can share the connection with others in your office but not use another users credentials.


## Current Behavior

connection info and username/password currently on the same file.



## Possible Solution

by having the SQL databoase have another table for credentials and using the connection name for each person who logs into the database as your primary key their credentials are not seen/used/altered by other users. 
same for when someone shares the XML file for connections the usernames/passwords can be in a separate file.  

You can use the same ContantID as the link between the two tables/files


## Context

useful when more than one person needs to use the connection list and each user has their own credentials on systems.


## Your Environment

* Version used:  1.76.11.40592   Portable Edition
* Operating System and version: Windows 10 1809  x64
