### ISSUE TITLE
Frequent crashing problem

### ISSUE THREAD

**Issue by AliKeremOzdemir** [mRemoteNG/mRemoteNG#729]
|||
Hello,
My mRemoteNG crashes frequently and I cannot understand the reason. Either it has only one connection or more than five, it hangs and when I click on debug it gives me this;
![image](https://user-images.githubusercontent.com/32295580/30854135-790dfa5c-a2b9-11e7-9065-f60ecb39c0f4.png)

Crash reports are below;
[mRemoteNG.exe.60916.zip](https://github.com/mRemoteNG/mRemoteNG/files/1332609/mRemoteNG.exe.60916.zip)
[mRemoteNG.exe.84100.zip](https://github.com/mRemoteNG/mRemoteNG/files/1332615/mRemoteNG.exe.84100.zip)
[mRemoteNG.exe.16284.zip](https://github.com/mRemoteNG/mRemoteNG/files/1332619/mRemoteNG.exe.16284.zip)

Please help, I use this great program alot.

|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by sparerd** [comment]
Can you also provide the mRemoteNG.log file? Details here: https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by AliKeremOzdemir** [comment]
Here's mRemoteNG.log file
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/1335949/mRemoteNG.log)

**Comment by AliKeremOzdemir** [comment]
is there any solution for this problem?
it occurs very frequently

**Comment by AliKeremOzdemir** [comment]
waiting for a solution...

**Comment by sparerd** [comment]
Exception seems to be happening in unmanaged code. From the first minidump:

> Unhandled exception at 0x7761E3BE (ntdll.dll) in mRemoteNG.exe.60916.dmp: 0xC0000005: Access violation reading location 0x047D2D6C.

@kmscode Any ideas?

**Comment by farosch** [comment]
Closed due to inactivity. OP probably has a corrupted .NET environment.
Will be reopened if OP still has this issue and wants us to investigate.
