### ISSUE TITLE
Error 0x80040154 on RDP connection

### ISSUE THREAD

**Issue by s-projects** [mRemoteNG/mRemoteNG#741]
No crash dump in localappdata\crashdumps.

Steps to reproduce: 
1. Download as ZIP and unpack mRemoteNG
2. Set up a RDP connection
3. Connect by double clicking on the connection
4. Get the following error:

![image](https://user-images.githubusercontent.com/32839693/31611159-3e180ec0-b27b-11e7-8de9-cc1eb9403310.png)

Log file:
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/1387326/mRemoteNG.log)

Full stack trace:
Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.Runtime.InteropServices.COMException (0x80040154): Třída není zaregistrována (Výjimka na základě hodnoty HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   v System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   v System.Windows.Forms.AxHost.CreateWithLicense(String license, Guid clsid)
   v System.Windows.Forms.AxHost.CreateInstanceCore(Guid clsid)
   v System.Windows.Forms.AxHost.CreateInstance()
   v System.Windows.Forms.AxHost.GetOcxCreate()
   v System.Windows.Forms.AxHost.TransitionUpTo(Int32 state)
   v System.Windows.Forms.AxHost.CreateHandle()
   v System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   v System.Windows.Forms.Control.CreateControl()
   v System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   v System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   v System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   v System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   v System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   v System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   v System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   v System.Windows.Forms.Control.WmShowWindow(Message& m)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemoteNG
    Verze sestavení: 1.75.7008.17935
    Verze Win32: 1.75.7008.17935
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/mRemoteNG.exe
----------------------------------------
System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BouncyCastle.Crypto
    Verze sestavení: 1.8.1.0
    Verze Win32: 1.8.15362.1
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/BouncyCastle.Crypto.DLL
----------------------------------------
log4net
    Verze sestavení: 1.2.15.0
    Verze Win32: 1.2.15.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/log4net.DLL
----------------------------------------
System.Management
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Verze sestavení: 2.9.0.0
    Verze Win32: 2.9.0.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light
    Verze sestavení: 2.9.0.0
    Verze Win32: 2.9.0.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012Light.DLL
----------------------------------------
System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
MagicLibrary
    Verze sestavení: 1.7.4.0
    Verze Win32: 1.7.4.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/MagicLibrary.DLL
----------------------------------------
WindowsBase
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
ObjectListView
    Verze sestavení: 2.9.1.1072
    Verze Win32: 2.9.1.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/ObjectListView.DLL
----------------------------------------
System.Data
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.36415 built by: FX452RTMLDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.resources.dll
----------------------------------------
AxInterop.MSTSCLib
    Verze sestavení: 1.0.0.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/AxInterop.MSTSCLib.DLL
----------------------------------------
Interop.MSTSCLib
    Verze sestavení: 1.0.0.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/IXTENT/mRemoteNG/Interop.MSTSCLib.DLL
----------------------------------------
mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Ladění JIT **************
Aby bylo povoleno ladění JIT, musí konfigurační soubor
pro tuto aplikaci nebo počítač (machine.config) mít
v oddílu system.windows.forms nastavenou hodnotu njitDebugging.
Aplikace rovněž musí být kompilována s povoleným
laděním.

Příklad:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Je-li ladění JIT povoleno, budou všechny neošetřené výjimky
odeslány ladicímu programu JIT, který je registrován v počítači,
a nebudou zpracovány tímto dialogovým oknem.

Additionally, I got on main window resize the following error:
![image](https://user-images.githubusercontent.com/32839693/31611309-dc9a6a48-b27b-11e7-98a8-0ac765c49624.png)
System.ArgumentNullException: Hodnota nemůže být NULL.
Název parametru: v1
   v System.Version.op_LessThan(Version v1, Version v2)
   v mRemoteNG.Connection.Protocol.RDP.ProtocolRDP.ReconnectForResize()
   v mRemoteNG.Connection.Protocol.RDP.ProtocolRDP.ResizeEnd(Object sender, EventArgs e)
   v mRemoteNG.UI.Window.ConnectionWindow.Connection_ResizeEnd(Object sender, EventArgs e)
   v System.EventHandler.Invoke(Object sender, EventArgs e)
   v System.Windows.Forms.Form.OnResizeEnd(EventArgs e)
   v System.Windows.Forms.Form.WmExitSizeMove(Message& m)
   v System.Windows.Forms.Form.WndProc(Message& m)
   v mRemoteNG.UI.Forms.frmMain.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Updated log file:
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/1387337/mRemoteNG.log)

|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7008.17935  |

**Comment by sparerd** [comment]
The following page may help resolve this:
https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#classnotreg
