### ISSUE TITLE
connections pane is not visible sometimes in windows 10

### ISSUE THREAD

**Issue by devinderdev** [mRemoteNG/mRemoteNG#744]
|Hi Team,
i am using windows 10. and once the laptop recovers from a sleep. i cannot see the connections panel at all, but its there , as once i double click anywhere ,i attempts to connect.
Please help 

|--:|---|
![image](https://user-images.githubusercontent.com/7370417/31735010-212938ea-b45e-11e7-8f5b-fa2c85aa27e5.png)

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by arrrghhh** [comment]
I've had the connection panel blank in Win7, and it wasn't returning from sleep... I'm not sure how to recreate the issue, it seemed to blank at random.  It is a Win7 VM I'm running mRemoteNG in however.

**Comment by 4SiB** [comment]
I can create this problem at W10 every time when I "collaps" the tree by using the LeftArrow on keyboard that on random tree level the connection windows is full blank.
When I try search any think on connection pane then I recover just a little of window.
**Workaround is to re-open the connection pane**.

![image](https://user-images.githubusercontent.com/18070741/32495256-35f9273c-c3c5-11e7-8a19-13976c218c5d.png)

**Comment by sparerd** [comment]
Likely related to #763. Fix will be released with 1.75.7011

**Comment by kmscode** [comment]
Closing since #763 was resolved and release.
