### ISSUE TITLE
Feature Request: Unless already exists, a way to merge one confcons.xml file with another.

### ISSUE THREAD

**Issue by enwarner** [mRemoteNG/mRemoteNG#745]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by tjgng** [comment]
It's a plain text xml file, you can do this manually. Google 'merge multiple xml files into one' for a tool.

**Comment by sparerd** [comment]
This can be done by going to File -> Import -> Import from file
