### ISSUE TITLE
RealVNC External tool - user and  passord

### ISSUE THREAD

**Issue by gunnarh79** [mRemoteNG/mRemoteNG#746]
I use Mremote and use External tool for RealVNC viewer with this Arguments: %HostName% but then i have to input user and password in the RealVNC viewer. Do anybady now if there are eny Arguments so i don,t need to input user and password?  The user and password is saved int the Mremote?

**Comment by sparerd** [comment]
According to https://www.realvnc.com/en/connect/docs/viewer-parameter-ref.html only a Username parameter exists, and that is only supported until version 5.3.2
