### ISSUE TITLE
Failed to load file C:\Users\d\AppData\Roaming\mRemoteNG\credentialRepositories.xml

### ISSUE THREAD

**Issue by bihubihu** [mRemoteNG/mRemoteNG#748]
ErrorMsg
2017-10-20 14:10:25
Failed to load file C:\Users\d\AppData\Roaming\mRemoteNG\credentialRepositories.xml
     System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 

--------
I cant find this .xml file...even gooogle..

Thanks

**Comment by sparerd** [comment]
Please provide the version of mRemoteNG you are running

**Comment by farosch** [comment]
Closed. Probably irrelevant by now.
