### ISSUE TITLE
sourceFileName / CustomConsPath empty

### ISSUE THREAD

**Issue by evilbaschdi** [mRemoteNG/mRemoteNG#756]
Storing configuration file at - in my case - one drive doesn't work anymore and results in an "file name may not be null. parameter name "sourceFileName".

I think it has something to do with "CustomConsPath" in the user.config file. that is always empty after closing 1.75 hf9.

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7009  |

**Comment by CVB2000** [comment]
+1

**Comment by evilbaschdi** [comment]
maybe that's the correct translation :) I'm using mremote with UI in de-de (german)

**Comment by CVB2000** [comment]
![mremote](https://user-images.githubusercontent.com/29163764/32145298-37b3eedc-bcc6-11e7-9eeb-0430ec7e2c0b.PNG)
me too ;-)

**Comment by sparerd** [comment]
Taking a look

**Comment by sparerd** [comment]
Found and resolved the issue - releasing the fix now since this is a pretty serious bug. You will need to delete your user.config file after installing the update. 

https://github.com/mRemoteNG/mRemoteNG/wiki/User-settings-file

**Comment by sparerd** [comment]
Actually, you may not need to delete your user.config file. Try updating to 1.75.7010 first and see if that works.

**Comment by CVB2000** [comment]
Confirming it is working after deleting user.config.
Keeping user.config did not work. Everything is back fine now.

**Comment by evilbaschdi** [comment]
comming from hf8 directly everythings working fine. comming from hf9 you'll have a corrupted config file that has to be deleted first.

everythings working now. thank you for that quick fix.

**Comment by cpickard** [comment]
Updating to 1.75.7010 did not work for me, nor did deleting my user.config.  I had to manually set the CustomConsPath in user.config to point to my confCons.xml file (mine is in OneDrive too).
