### ISSUE TITLE
Active Directory Import

### ISSUE THREAD

**Issue by benwa** [mRemoteNG/mRemoteNG#759]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010  |

When importing devices/OUs from Active Directory, the default protocol should be RDP.

**Comment by farosch** [comment]
@benwa I cannot reproduce this. Seems to me like RDP is always set when importing from AD.
Can you please check if this issue has been resolved since 1.75?
