### ISSUE TITLE
"Download & Install" button too small to display full translated text

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#762]
![image](https://user-images.githubusercontent.com/22905106/32221565-41e4c478-be36-11e7-9b84-ebc03af61be4.png)

At least for the german translation the button is too small to display the full translated text.
The button should either be resized or just labeled **Install** - which would be better in my opinion.

**Comment by sparerd** [comment]
@kmscode What do you think - make the button a variable size or just make it say "Install"

**Comment by kmscode** [comment]
increased button size by about 150%.

Changing the text would require all translations to be updated also...
