### ISSUE TITLE
Minimize Folder in Connections loses tree

### ISSUE THREAD

**Issue by RJC84** [mRemoteNG/mRemoteNG#763]
Latests version of MRemote has an issue where i minimize a folder in the connections section which  then leads to the entire tree disappearing until i close and reopen.

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment]
Are you using SQL for connection storage? If you change the size of the connection tree window, does the tree reappear?

**Comment by RJC84** [comment]
No not using SQL....resizing the connection window doesnt bring them back im afraid

**Comment by sparerd** [comment]
I was able to reproduce it once while resizing the window, but not when minimizing a folder. Does it happen very often for you?

**Comment by RJC84** [comment]
Ive narrowed it down to one specific folder ….every time I collapse it I lose the tree

Thanks
Rob

**Comment by sparerd** [comment]
If I provided a portable build, would you be able to test if it resolves the issue you're seeing?

**Comment by RJC84** [comment]
Morning I deleted the folder that seemed to be causing the issue (it had around 20 rdp connections in it)

Since recreating the folder I haven’t had the issue so ill keep an eye on it and let you know

Thanks
Rob

**Comment by farosch** [comment]
I have the exact same issue and would be willing to test it out

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 Build 16299.19|
|mRemoteNG version| 1.75.7010.21169  |

**Comment by sparerd** [comment]
@RJC84 that is definitely weird

@farosch I'll try to get you a build within the next few hours

**Comment by sparerd** [comment]
@farosch give this one a try: https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011.r1

**Comment by farosch** [comment]
@sparerd Seems like the issue has been resolved with this version - Everything works as expected again! Thanks a lot :)

**Comment by sparerd** [comment]
Good to hear!

**Comment by stoertel** [comment]
@sparerd Same issue here with a Windows 7 Pro as well as with a Win 10 LTSB client. Your fix resolved it for both machines. Thanks!! :-)

**Comment by sparerd** [comment]
v1.75.7011 has been released
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011
