### ISSUE TITLE
Port Scan Issues

### ISSUE THREAD

**Issue by arrrghhh** [mRemoteNG/mRemoteNG#765]
Using Port Scan feature, I want to only scan port 3389.  I put '3389' as start/end port, yet system still seems to scan all of the default ports.

Also, the port scan itself when I changed the range it did not update properly.  It would still scan the old range, I had to close the tab and open a new port scan tab in order to scan a new IP range.

I find using PortQry.exe is quite fast (assuming the port is open) so I would imagine this would speed up the port scan itself quite a bit if it only focused on one port.
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment]
Relevant discussion:
https://www.reddit.com/r/mRemoteNG/comments/7a4nwi/port_scan/
