### ISSUE TITLE
Password field is not transmitted correctly when opening external application

### ISSUE THREAD

**Issue by kleinerbub** [mRemoteNG/mRemoteNG#766]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

When I start an external Program with Password field as parameter it sends wrong characters, in some cases.
For example if the Password field contains` !` the external application receives `^!`
or if I send `"` the external application receives `\^"`

Before I used version 1.72 and it worked as expected.

**Comment by sparerd** [comment]
Try using `%!Password%` (note the !) to disable shell character escaping. More details here: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#special-character-escaping

**Comment by kleinerbub** [comment]
Thanks, @sparerd , you were right. With character escaping it works like a charm :+1
