### ISSUE TITLE
Empty file name is not legal. Parameter name sourceFileName

### ISSUE THREAD

**Issue by emanuelpsilva** [mRemoteNG/mRemoteNG#767]
![screenhunter_05 nov 02 14 37](https://user-images.githubusercontent.com/23637079/32331637-554d6780-bfdb-11e7-83af-7d5d1383f2b1.png)
Hi,

After updating to latest version (v1.75.7010 - Hotfix 10) every time mRemoteNG starts shows an error window saying 'Empty file name is not legal. Parameter name: sourceFileName'

I've tried to run mRemoteNG from command line with /c parameter but the error persists!
I've also tried uninstall/install from scratch but no luck...

I'm running Windows 10 x86

Any help will appreciate :)

Thanks,
Emanuel

**Comment by sparerd** [comment]
Do you load from a custom connection file path?
Make sure that the CustomConsPath contains a value in your user settings file (https://github.com/mRemoteNG/mRemoteNG/wiki/User-settings-file)

```
<setting name="CustomConsPath" serializeAs="String">
    <value>C:\your\path\here\confCons.xml</value>
</setting>
```

You can also try deleting your user settings file, though you will lose other settings as well.

**Comment by emanuelpsilva** [comment]
Thanks!!! It solved the problem :)
Now I have another problem: External Tools are not being saved. I'm able to configure it, but after reloading mRemoteNG there are no tools configured...

**Comment by sparerd** [comment]
When you setup an external tool, is anything being written to `%APPDATA%\mRemoteNG\extApps.xml`?

**Comment by emanuelpsilva** [comment]
Nop!
And the extApps.xml exists with the configurations I have in my mRemoteNG prior to update...

**Comment by sparerd** [comment]
Check the mRemoteNG.log file, where does it say it is loading the external tools from? Example log here:

```
2017-11-02 11:13:43,950 [1] INFO - mRemoteNG 1.75.7010.21169 starting.
2017-11-02 11:13:43,960 [1] INFO - Command Line: System.String[]
2017-11-02 11:13:45,095 [1] INFO - Microsoft Windows 10 Enterprise  64-bit
2017-11-02 11:13:45,095 [1] INFO - Microsoft .NET CLR 4.0.30319.42000
2017-11-02 11:13:45,096 [1] INFO - System Culture: en-US/English (United States)
2017-11-02 11:13:45,096 [1] INFO - Checking FIPS Policy...
2017-11-02 11:13:45,097 [1] INFO - Checking Lenovo AutoScroll Utility...
2017-11-02 11:13:45,979 [1] INFO - Loading External Apps from: C:\Users\User\AppData\Roaming\mRemoteNG\extApps.xml
2017-11-02 11:13:45,980 [1] INFO - Adding External App: git-bash C:\Program Files\Git\git-bash.exe --cd-to-home
2017-11-02 11:13:45,980 [1] INFO - Adding External App: PowerShell ISE %windir%\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe 
```

**Comment by emanuelpsilva** [comment]
That's odd... nothing is being write in the log file, and I checked the user config and it's enabled:

            <setting name="WriteLogFile" serializeAs="String">
                <value>True</value>
            </setting>

**Comment by sparerd** [comment]
That is very odd - it should be writing to one of the locations detailed here https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

If it's not logging to either location then something may have become corrupted

**Comment by emanuelpsilva** [comment]
Ok, I decided reinstall it from scratch using the MSI package and all is ok now.
Thanks for the great support :)

**Comment by sparerd** [comment]
Good to hear @emanuelpsilva! Happy to help
