### ISSUE TITLE
Unclickable "border" on tabbed RDP connections

### ISSUE THREAD

**Issue by vlf** [mRemoteNG/mRemoteNG#769]
There is some unclickable zone around inside of the tab window for RDP connections. This prevents clicking on elements like windows taskbar, startmenu, minmax buttons etc.
It seems the smaller the tab window is, the bigger the no-click zone gets. At window splitter near 50% of the screen size, clicks aren't registered for about 3 whole icon rows on RDP connection window. Splitter at 5% (smallest possible connections/configuration) seem to result in about 10-20 pixels "border".
Tested with resolution setting at "fit to panel" (default).

|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7010.21169  |

**Comment by kmscode** [comment]
Could you please provide a screenshot?

**Comment by vlf** [comment]
I should have been more specific, it's not a visible glitch. It's just border-like zone that does not registers any mouse clicks.
