### ISSUE TITLE
SQL Updates no longer work

### ISSUE THREAD

**Issue by Venix42** [mRemoteNG/mRemoteNG#770]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010  |

We have 3 computers running mRemote on a SQL Server. On the .7008 version, everything worked nicely (if you don't mind the trail going up every time there a modification)

We updated to .7010 version but we noticed that updates no longer go to the database, as if they are only staying local.
We tried with one .7008 version and one .7010 version. Modification made using .7008 seems to be reflected in .7010 but not the opposite way: modification made by .7010 do not reflect on .7008 (and the trail don't go all the way up aswell)

Note: we jumped from .7008 to .7010 directly

**Comment by peanek** [comment]
Duplicate of issue #758

**Comment by sparerd** [comment]
v1.75.7011 has been released. I'm fairly sure this should resolve the issue you are seeing, but please confirm
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011

**Comment by Venix42** [comment]
Problem has been resolved thanks!
