### ISSUE TITLE
External Tools issues -version 1.75.7010

### ISSUE THREAD

**Issue by fullv2** [mRemoteNG/mRemoteNG#772]
I face issues with latest version with many of my custom external tools such as 
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -P %hostname%

I revert to version 1.75.6269.29909 and everything works perfect.

**Comment by EffEss** [comment]
I'm having the same issue, seems like the parameters aren't getting passed on to the external tool in this version (%hostname% and %description% in my case).

**Comment by LIyoai** [comment]
Duplicate? https://github.com/mRemoteNG/mRemoteNG/issues/761

**Comment by sparerd** [comment]
Tested the cases you mentioned in v1.75.7011 and couldn't replicate, so this next version should resolve the issues you are seeing

**Comment by sparerd** [comment]
v1.75.7011 has been released
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011
