### ISSUE TITLE
Connections are auto-saved even if Save On Exit is un-ticked

### ISSUE THREAD

**Issue by ilog2000** [mRemoteNG/mRemoteNG#776]
After upgrade to version 1.75.7010.21169 it started auto-save data temporarily put into Config Hostname. Options / Save Connection OnExit setting remains un-ticked. Previous version behaved correctly. My problem is that I have main AWS server, and a number of auto-scale instances with the same RDC settings, so I used to temporarily replace main server hostname with autoscale one and simply exit mRemote after job done. Now I see autoscale hostname after re-opening the application.

|Detail|Value|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010.21169  |

**Comment by sparerd** [comment]
Do you remember the previous version of mRemoteNG you were using?

**Comment by ilog2000** [comment]
Unfortunately, I don't remember exactly. I have two files in downloads:
* mRemoteNG-Installer-1.74.6023.15437.msi
* mRemoteNG-Installer-1.75.7008.17907.msi
so, one of these versions, but I cannot recall, did I do manual upgrade before or used the eldest one.

**Comment by sparerd** [comment]
That helps, thanks @ilog2000. I'll look into it

**Comment by Annihilator** [comment]
This issue still persists in the latest available versions. Unticking Save connections on exit isn't honored and connections get saved regardless.

**Comment by sparerd** [comment]
@Annihilator is `Tools -> Options -> Connections -> Save connections after every edit` enabled?

**Comment by Annihilator** [comment]
> @Annihilator is `Tools -> Options -> Connections -> Save connections after every edit` enabled?

It is indeed enabled. I guess that disabling it is in fact the solution, and that the effect is the result of that option. Thanks.
