### ISSUE TITLE
Starting with /c:"Connection/file/path" not working

### ISSUE THREAD

**Issue by archonik** [mRemoteNG/mRemoteNG#778]
Starting with /c:"Connection/file/path" not working properly, file exists, but is not loaded and previously used connection file is used instead.

|OS|Mremote Version|
|---|---|
Windows 10 x64 | 1.75.7010.21169

**Comment by sparerd** [comment]
Found the issue. Fix will be available in the next hotfix release 1.75.7011

**Comment by archonik** [comment]
Thanks man, i am using mremoteng to manage over 2k servers, so i use this a lot :).

**Comment by sparerd** [comment]
v1.75.7011 has been released https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011
