### ISSUE TITLE
Asking me a password at start since last update

### ISSUE THREAD

**Issue by Gecko64** [mRemoteNG/mRemoteNG#780]
Asking me a password when i launch the program since the last update (Version 1.75.7011.26523)
I tried to downgrade but same problem...
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment]
Can you please provide a copy of the mRemoteNG.log file?

https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by sparerd** [comment]
Closing due to lack of response
