### ISSUE TITLE
New version overwrites Hostname with the Name

### ISSUE THREAD

**Issue by codearoo** [mRemoteNG/mRemoteNG#781]
One of the updates now sets the Hostname to be the same as what you type for the Name of a connection. While that was really annoying to have to do them twice before... when you are duplicating a connection and you rename, or just rename a connection, you don't expect it to overwrite the Hostname if they were different to begin with.

I would say that one of the following should be how it works:
- If the Name matches the Hostname exactly, allow edits of the Name to update Hostname too. Otherwise, if a Hostname is changed and it no longer matches, they should continue to function independently.
- If there is no Name, copy the Hostname into Name or vice versa. (useful for new connections)

I put this as a bug because, when I had some connections there and I just renamed them to indicate something slightly different, it blew away my actual Hostname. I luckily found it because I had made another copy of that connection. But otherwise I would have lost it completely and would have to find it elsewhere.
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010.21169  |

**Comment by sparerd** [comment]
Check if Tools -> Options -> Connections -> "Set hostname like display name when creating or renaming connections" is enabled. If you did not enable this option explicitly, I can look into that as a bug (it should default to "disabled").

**Comment by kmscode** [comment]
closing - most likely "Set hostname like display name when creating or renaming connections" is enabled as noted by @sparerd
