### ISSUE TITLE
Ext Tool not working anymore

### ISSUE THREAD

**Issue by MahoH** [mRemoteNG/mRemoteNG#782]
Since the update, all my external tool is not working anymore, when using it via the connection shortcut but are still working when I use them directly via Tools > External Tools > double click on it or via connection panel > connection > right click > ext tool > select your external application.

So I suppose the direct call via the config panel > ext tool > my tool (cmd show password or other) is not working correctly 

Thanks !

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010  |

**Comment by sparerd** [comment]
Give v1.75.7011 a try - that bug should be fixed in this version
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011

**Comment by Milkanet** [comment]
Hello

I was answering this topic, saying I had the same problem ... when .. POUF ..... I saw your answer...

Quick download... and quick test (no deep test yet) .... and indeed, seems to work now! GREEEEEAAAAAT )

THANKS for the nice work !

**Comment by MahoH** [comment]
Indeed it fix my issue thanks
