### ISSUE TITLE
Panel Issue

### ISSUE THREAD

**Issue by DBT76** [mRemoteNG/mRemoteNG#783]
Every time I select an item to open (ex. RDP connection), I am prompted to select a panel. I already assigned all my connections to a specific panel. The current version of the issue is 1.75.7011.34963.

Thanks!

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by brucetp** [comment]
Check Tools->Options->Tabs & Panels->Always show panel selecttion...

**Comment by DBT76** [comment]
Sorry!

Thanks! I did figure that out then.

**Comment by sparerd** [comment]
@DBT76 Is it ok if we close out this issue?

**Comment by DBT76** [comment]
Yes
