### ISSUE TITLE
Texts from Settings seem to be hard-coded and are thus not translatable

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#785]
Hopefully I am not overlooking something here but to me it seems like the following fields can not be translated through a resource file.

![1](https://user-images.githubusercontent.com/22905106/32577860-8db70144-c4db-11e7-9817-c0361d73fa19.png)
![2](https://user-images.githubusercontent.com/22905106/32577861-8dd389e0-c4db-11e7-957d-278f3feb9270.png)

**Comment by kmscode** [comment]
Off the top of my head, I believe you are correct. These are newer ui components so we might have inadvertently skipped the localization bits. Will look to get them into the EN resource asap.
