### ISSUE TITLE
Connection tree disappears when it is collapsed when the root is not visible

### ISSUE THREAD

**Issue by simonTIG** [mRemoteNG/mRemoteNG#789]
The bug appears in the following conditions:
The list of connections is greater than the height of the Connections panel
AND
the tree root is not visible in the connection panel
AND
the folder that is collapsed has more connections displayed than can fit the connections panel

[I have uploaded a video showing the problem](https://sea01.gva.net.itguys.ch/f/428dc904b5/)
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7010.21169  |

**Comment by sparerd** [comment]
[v1.75.7011](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011) should resolve this bug for you

**Comment by simonTIG** [comment]
Thank you so much :)




*Simon Cateau*Technologist

T: +41 22 552 0111 <http://www.theitguys.ch> | E: simon@theitguys.ch  | W:
www.theitguys.ch

CONNECT WITH US    [image: LinkedIn]
<http://www.linkedin.com/company/the-it-guys-sarl>     [image: Google Plus]
<https://plus.google.com/+TheitguysCh>     [image: Twitter]
<https://www.twitter.com/theitguys>

*SECUREADVANTAGE  | THE LEADING ALL-IN-ONE IT MANAGEMENT SOLUTION FOR SMBs*

*24/7 MONITORING + UNLIMITED SUPPORT + GUARANTEED RESPONSE TIMES + SLA
BACKED + LOW MONTHLY FEE*
