### ISSUE TITLE
External apps without the checkbox "Try to integrate" are integrated

### ISSUE THREAD

**Issue by simonTIG** [mRemoteNG/mRemoteNG#790]
I have configured external apps such as Google Chrome and VMWare Vsphere, they do not have the box "Try to integrate" checked, but when I double-click on the connection mremoteNG integrates it and it does not work. A new tab opens in mremoteNG and the external app is not launched.

[I have uploaded a video showing the problem](https://sea01.gva.net.itguys.ch/f/0053e0e12f/)

This issue did not happen on version 1.72

|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7010 |

**Comment by sparerd** [comment]
I was able to replicate the issue in v1.75.7010 and verified that it is fixed in [v1.75.7011](https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75.7011)
