### ISSUE TITLE
Strings passed to external tools contains extra character "^"

### ISSUE THREAD

**Issue by slym** [mRemoteNG/mRemoteNG#792]
When strings such as USER or PASSWORD uses special character such as "!", the passed string to the external tools has some extra characters "^". Examples : Adm!n will be passed as Adm^!n to external tools. It can be easily reproduced.

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7011.34996  |

**Comment by sparerd** [comment]
Use `%!PASSWORD%` (note the `!`) to disable shell meta-character escaping

More info here: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#special-character-escaping
