### ISSUE TITLE
Remove duplicate translated strings

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#797]
*This is a great project for new contributors!*

There are many duplicate translatable strings in the `mRemoteV1\Resources\Language\Language.resx` class. We should remove duplicates to make them easier to discover and reduce the work of our translators.

Examples:
> strConnectionOpenFailed = "Opening connection failed!"
strVncConnectionOpenFailed = "Opening connection failed!"
strRdpOpenConnectionFailed = "Open RDP Connection failed!"
strRdpConnectionOpenFailed = "Opening connection failed!"

There is no reason to have this many (mostly) identical strings. In this case, I would keep the `strConnectionOpenFailed` string (since it is the most general) and delete the rest.

**Comment by farosch** [comment]
this has been fixed by #1776
