### ISSUE TITLE
German umlaute not shown under PuTTY sessions

### ISSUE THREAD

**Issue by mueller-ma** [mRemoteNG/mRemoteNG#800]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7010.21169 |

I have created a putty session with name "üöäß" and hostname "üöäß". In mRemoteNG the name is shown as "����", the hostname as "üöäß"

**Comment by sparerd** [comment]
I'm able to replicate. We will need to add support for parsing the extended ascii characters as they are saved in the registry. Example:
`HKEY_CURRENT_USER\SOFTWARE\SimonTatham\PuTTY\Sessions\%FC%F6%E4%DF`
