### ISSUE TITLE
File path command line argument not working with network path

### ISSUE THREAD

**Issue by iron51** [mRemoteNG/mRemoteNG#803]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7011.34996  |

Custom connection file path command line argument (/c) not working with network path like 

mRemoteNG.exe /cons:"\\\192.168.1.1\connessioni\ufficio.xml"
or
mRemoteNG.exe /c:\\\192.168.1.1\connessioni\ufficio.xml

thank you

**Comment by sparerd** [comment]
I'm able to replicate the issue - I'll look into it

**Comment by BasicHumanUnit** [comment]
Same issue here, been happening for a while.

**Comment by sparerd** [comment]
I think I've fixed it - this will be included in the 1.75.7012 release
