### ISSUE TITLE
Plus/Minus Tree View Controls Display Issue

### ISSUE THREAD

**Issue by jtwp** [mRemoteNG/mRemoteNG#812]
The plus/minus buttons on the tree view are too big. Is this a known issue or something with the HIGH DPI of my screen. Note I have tried running it in compatibility mode but still looks the same.

![tree](https://user-images.githubusercontent.com/4807091/33086900-fe76d18e-cee0-11e7-8962-3fed7df8d15e.png)

Am running Windows 8.1 and the latest stable version of mRemoteNG.

**Comment by sparerd** [comment]
This is likely a highdpi issue - i haven't noticed this on any other test machines. Related to #321

**Comment by kmscode** [comment]
Expected to be resolved in 1.77 which has HiDPI support.
