### ISSUE TITLE
Feature Request - Ability to select local drives for session

### ISSUE THREAD

**Issue by DennisT1** [mRemoteNG/mRemoteNG#813]
It would be nice to have the ability to select which local resources are available for the remote session.  EG In the Windows RDP client go to Show Options -> Local Resources -> Local devices and resources -> More -> Drives and you can select which local drives will be usable in the remote session.

**Comment by sparerd** [comment]
Thanks for spotting that, @HengzhiShao.

@DennisT1 Closing this issue as a duplicate. Please follow #317 for further updates on this request.
