### ISSUE TITLE
Instability on RDP connection

### ISSUE THREAD

**Issue by seijied** [mRemoteNG/mRemoteNG#815]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by farosch** [comment]
@seijied You are running an outdated version of mRemote. Does the issue still exist on v1.75.7011?
Please update and specify what "instabilities" you're exactly experiencing.

**Comment by iron51** [comment]
I use several RPD connection to Windows 2008 R2, 2012, 2012 R2 and 2016 at the same time and everything is always stable. May be a problem with your connection ?

**Comment by harrysummer** [comment]
I am using the latest alpha 2 version 1.76.0.36642. Every time I change the size of the panel, such as maximize, the RDP connection would be disconnected.

**Comment by sparerd** [comment]
@harrysummer If your RDP connection is set to `Fit to panel`, ensure that `Automatic Resize` is set to No

**Comment by harrysummer** [comment]
Thanks @sparerd ! It works for me. But it seems to be just a workaround. I cannot use the auto resize feature with this method. Will/Can this be handled? I didn't find any issue related to auto-resize bug.

**Comment by sparerd** [comment]
Unfortunately no. The reconnection **is** the auto resize feature. Currently, RDP has no way to resize to client area while a connection is active. The work around is to restart the connection with the updated client area dimensions.

The closest feature RDP has to a dynamic resize is SmartSize. However, SmartSize just stretches the client area provided by the server to fit the client area on your local host.

**Comment by farosch** [comment]
Closing this because of the time that has passed and because of @seijied never responding on the issue.
