### ISSUE TITLE
mRemoteNG blocks spcial characters

### ISSUE THREAD

**Issue by TieleDeclercq** [mRemoteNG/mRemoteNG#818]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

After some time without closing mRemoteNG I can no longer enter any special characters that require the AltGr button. I have no idea when of why this happens. Closing mRemote fixes this issue. I can start mRemote again and it stays fixed.

While the AltGr button works, I can use these special chars on my local computer as well as in mRemote sessions. When it's no longer working on my local computer, I can not use this in mRemote sessions as well.

Closing the mRemote sessions does not help. I need to totally close mRemote to fix this.

**Comment by farosch** [comment]
Detail | Value
-- | --
Operating system | Windows 10 x64 1709
mRemoteNG version | 1.75.7012.16814

One of my colleagues and I are having the same problem. Unfortunately none of us have been able to reproduce it yet. I will report back here as soon as I find out when this happens.

**Comment by farosch** [comment]
This seems to be the same issue: #354

**Comment by teimahu** [comment]
Hi, same problem for me.
I am using Window 7 Enterprise SP1 x64, with mRemoteNG 1.75.7012.16814, also tried with mRemoteNG 1.74
This is quite annoying when using SSH, I use the @, |, ~ ... characters many times a day :s

Note: Anyway, thanks you all for this great software

**Comment by farosch** [comment]
@teimahu @notes90
Just found you can still use special characters when you press `CTRL` additionally.

**Comment by farosch** [comment]
FAQ entry: https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#altgrstopsworking
