### ISSUE TITLE
mRemoteNG does not start

### ISSUE THREAD

**Issue by svanschu** [mRemoteNG/mRemoteNG#820]
Since some MS updates I have the issue that mRemoteNG won't start. I've update mRemote to 1.75.7011 but the issue is the same.

I have to reboot my pc and start mRemote as first program after log in.

A colleague of mine has the same issue. He say that he have to start Outlook 2010 before mRemote, else mRemote would not open.

|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7011  |

**Comment by svanschu** [comment]
Another colleague has an old version and he does not have that issue with the same OS and Outlook version 

1.70.4814

**Comment by smonthony** [comment]
I'm having the same problem.

**Comment by sparerd** [comment]
Are you seeing any errors? Could you provide your mremoteng.log file?

https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by svanschu** [comment]
Sorry for the delay. Just tested the new version, but it's the same.
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/1600106/mRemoteNG.log)

**Comment by farosch** [comment]
@svanschu Sorry for the late reply!
I'm guessing newer versions of mRemotNG already fixed this issue.
Can I close it or does it still apply to you?

**Comment by svanschu** [comment]
Well I have no Win7 PC anymore and I don't use mRemoteNG anymore. But I'll ask my former colleagues if they see the issue or not.

**Comment by farosch** [comment]
@svanschu That's sad to here! (The mRemoteNG part of course, not the win7 one  :D)
If your colleagues still have this problem please tell them to open a **new** issue instead of adding to this one. Thank you very much!
