### ISSUE TITLE
Allow selecting RDP version to use when connecting

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#826]
When creating an RDP connection record, I should be able to select the version of RDP protocol to use.

This provides several benefits:
- Application requirements can be relaxed a bit. The currently required KBs are only required to make RDP work correctly. If we have older RDP protocol versions available, those KBs may not be required.
- We are not using the newest RDP protocols. Allowing users to select the protocol version lets users on newer systems take advantage of bug fixes and new features while not forcing users on older or more restrictive systems to use old versions of mRemoteNG itself (just for older versions of the RDP protocol).

This comes with some challenge:
- How do we determine which RDP protocols are supported? COM searches? Something similar to the component check page?
- Some versions of RDP introduce new functionality. Someone using an older RDP protocol will need to know which settings are valid for their version and which are not. How do we handle this in a user friendly way? This must also work in a shared environment (db support, but also xml synced between multiple machines that may not have the same capabilities).

**Comment by sparerd** [comment]
Basic work for this is done:
- Users can now select the `RDP Protocol Version` to use when connecting via RDP. The default is `Highest`.
- Updated the component check page to show all supported RDP protocol version on the machine. We only show an error if *no* versions are supported (very rare these days).
- The installer no longer requires certain KB updates be installed on Win7 machines. There have been several reports of issues installing on Win7 due to different combinations of KBs that provide the same necessary components but which aren't honored by the installer.

I am still trying to find a way to inform a user when a particular RDP property will not be used because the required protocol version isn't available. I would like it to display in the config window, but the WinForms property grid isn't very easy to modify.

**Comment by farosch** [comment]
@sparerd How about just showing a warning in the notifications window?

**Comment by sparerd** [comment]
@farosch Yea that could work. I'll give it a shot and see how it looks

**Comment by sjuffe** [comment]
When will this become available to download?  I've downloaded beta for 1.77.0 but it is not an option to change the RDP Protocal version to highest.

**Comment by sjuffe** [comment]
Any response to this?  I can't seem to get any response about this.

> When will this become available to download? I've downloaded beta for 1.77.0 but it is not an option to change the RDP Protocal version to highest.

**Comment by Kvarkas** [comment]
will check
