### ISSUE TITLE
Feature Request: Add windows shortcuts to folders

### ISSUE THREAD

**Issue by garyhahn** [mRemoteNG/mRemoteNG#831]
I like to use mRemoteNG to organize as much of my administrative connections as possible.  I do find that I have to keep separate organization folders outside of this app.  It would be nice if we could add Windows standard shortcuts to the organization structure of mRemoteNG for connections to related text files, documents, RDP links, web admin GUIs or even specific admin apps....basically anything that may already have or could have a Windows shortcut.   

Although the app does have the ability to embed browser and RDP, I often find it somewhat limiting to have the session exist "within" the app.  Also, many admin consoles seem to have browser compatibility issues; might need Java, Flash, etc, so I'm never sure if they're going to work right in the app.   So ideally, I could just shortcut these things.   I know, I might sacrifice the autologin in some cases, for which there is often a workaround.

So what I'd end up with is, say, a folder for the New York office, under which I might have:
- mRemote SSH's to router and switches
- shortcut to ASA ASDM GUI
- shortcut to Firefox to wireless LAN controller
- shortcut to Visio diagram

Not sure if it's even possible to achieve.  Thanks for considering it!  -Gary

**Comment by sparerd** [comment]
If I'm understanding your request correctly, most of this should be possible by using external tools. If the built-in browsers dont work for a particular web page, you can setup an external tool to launch the page in your own browser. Visio files can be opened via external app as well, if you set the `UserField` property on the connection to be the path (or part of the path) to the visio file and pass in the `%USERFIELD%` variable to the external tool.

Does that solve what you are wanting to do, or is there more to it that I didn't pick up on?

- The External tools page: https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#variables
- Some example external tool configurations: https://github.com/mRemoteNG/mRemoteNG/wiki/Common-External-Tool-Configurations

**Comment by garyhahn** [comment]
Oh my!   Well this appears to be a bad case of RTFM on my part!  Because, well, this one is already fully rocked out and then some!  Sorry.  Now it's a matter of using it!  Thanks for the quick feature enhancement!  ;-)

**Comment by sparerd** [comment]
Hehe good to hear, glad to help!
