### ISSUE TITLE
update to vs2017 on jenkins so we can use some newer syntax

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG#832]
MSBuild is now in the VS install dir:
C:\Program Files (x86)\Microsoft Visual Studio\2017\*\MSBuild\15.0\Bin

For example:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin

This will allow for using more expression bodies (like gets/sets) and simplify some syntax.

**Comment by sparerd** [comment]
Build box now has an updated vs2017 and jenkinsfiles have been updated to use msbuild15
