### ISSUE TITLE
installer issue - white screen

### ISSUE THREAD

**Issue by systemsNinja** [mRemoteNG/mRemoteNG#842]
Installed 1.75 and coulnd't import the new version of RDG, so downloaded new version. Forgot to close the old version and started the installed. The installer goes through validation, and than just shows a white page without being able to hit next. Had to cancel, close app, and relaunch installed.

|--:|---|
OS: Win 7 PRO
Ver: mRemoteNG-Installer-1.76.0.25712

**Comment by sparerd** [comment]
Wasn't able to reproduce this one yet. Pushing to the next release program
