### ISSUE TITLE
Toolbar layout forgotten between restarts

### ISSUE THREAD

**Issue by aldago** [mRemoteNG/mRemoteNG#846]
|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| v1.76 Alpha 1 |

I'm not sure if it's something wrong with my install (unzipped 1.76 on existing mremoteng folder), but every time I start mremoteng, the toolbars are using two rows (first row multi shh, second row quick connect and menus). No matter how I position the toolbars, on next restart settings are reset.

This does not affect the rest of the layout.

**Comment by sparerd** [comment]
Yes this has been annouing me also. Thanks for writing up the bug. Ive been dreading fixing this since toolbar position issues can be a pain..

**Comment by jotatsu** [comment]
pull #840 half fixes this, at least the initial layout is ok. After restart the menu is changed but not exactly as before the app was closed.

**Comment by sparerd** [comment]
Thanks @jotatsu! I should hopefully have some time in the next few days to review it

**Comment by johnwc** [comment]
Why are the toolbar also all over the place, they are not left aligned like they were before. There is like a 1/4 of my screen space between the menu and the left side.

![capture](https://user-images.githubusercontent.com/2798441/34575075-61fa3374-f171-11e7-98ad-c7eb36e78fdf.JPG)

**Comment by sparerd** [comment]
Thats a bug with windows forms toolbars (specifically how we load toolbar positions). Its a pain to fix, but ill try to get to it soon. It will be in the next alpha release. Ive been pretty busy lately, but im going to try to get some work done on mremote this week
