### ISSUE TITLE
How many connections at one time?

### ISSUE THREAD

**Issue by Greenice33** [mRemoteNG/mRemoteNG#854]
Please help! Tell me how many simultaneous connections you can open in the program? Doesn't open anymore 18. How to do to open more connections?

**Comment by sparerd** [comment]
Generally, the maximum number of connections you can open is capped at the amount of memory your system has to run mRemoteNG. This is usually only associated with RDP connections. You can try to reduce the memory consumption of individual connections by turning off `Cache Bitmaps`, which is the single largest contributor to connection memory use. Turning down the color to a lower bit-value may help as well.

**Comment by Greenice33** [comment]
I want to I have launched at the same time 40 of the compounds, can I upgrade RAM PC? Or what would you recommend more?

**Comment by Greenice33** [comment]
How to disable Cache Bitmaps?

**Comment by sparerd** [comment]
![image](https://user-images.githubusercontent.com/6999446/35862183-54e259ba-0b10-11e8-9acb-4710125ac508.png)

**Comment by kmscode** [comment]
Closing due to no additional feedback. #915 will likely help this scenario.
