### ISSUE TITLE
Menus not aligned to left border

### ISSUE THREAD

**Issue by loreggiap** [mRemoteNG/mRemoteNG#861]
![mremoteng_1 76 0 25712](https://user-images.githubusercontent.com/35289400/34761428-a7fe0bc0-f5db-11e7-98ab-787e733d7d90.jpg)
Hello
I'm using 1.76.0.25712 and found these two little errors:
The Menus (File, View, Tools, Help) do not appear aligned to the left border, but approx. 8 cm (3 inches) form the left border.
Under the menu View I have de-selected "Multi SSH Toolbar", but on a new program start it keeps reappearing.

|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.0.25712  |

**Comment by hemantmits** [comment]
I am also seeing this issue.
Even after I align them manually, after restart alignment is lost.

**Comment by HeXDeMoN** [comment]
+1 i also have this issue , even with just hiding multi SSH , closing and restarting the app it will re-appear everytime

**Comment by sparerd** [comment]
The fix for these issues should be present in the v1.76 alpha 2 release
