### ISSUE TITLE
mRemoteNG no longer starts after Microsoft update

### ISSUE THREAD

**Issue by kingofbytes** [mRemoteNG/mRemoteNG#862]
After a rather large windows update yesterday, I noticed that mRemoteNG is no longer launching. 
 When I view in Task Manager, I see that it actually gets spawned, then roughly 5 seconds later, it's auto-killed.  I tried to run the Microsoft compatibility troubleshooter with no success.  I also tried reinstalling mRemoteNG with no success.  Help! |Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by daves127** [comment]
same issue, same OS, mRemoteNG 1.75.7012.
My work-around was to pull 1.76 & copy the confCons.xml file from the original to the new.

**Comment by ichvets** [comment]
Hi  kingofbytes, I wonder if you resolved your issue. I have similar issue with 1.75 on my Win7. After the laptop crashed with blue screen and rebooting and starting Win7 again I am no longer can launch mRemoteNG 1.75. Tried to run repare from the Add/remove Programs but its looking for the msi file I do not have.
daves127, where did you find confCons.xml file. I seems can not find where all my connections are stored.
Thank you for the reply.

**Comment by daves127** [comment]
@ichvets, the xml file was in same directory of the mRemoteNG.exe file.  just type the file name, search your drive. copy/paste of the xml file from the 1.75.. directory to the 1.76.. directory, then launched the new exe... all saved servers available.

**Comment by ichvets** [comment]
Thank you I was able to find it in administrator users directory \AppData\Roaming along with all backups. The issue was resolved after uninstalling mRemoteNG.exe, installing again and opening the confCons.xml file from \AppData\Roaming.

**Comment by sparerd** [comment]
Sorry for the late reply - if anyone is still experiencing the issue, can you please provide the mRemoteNG version, portable/installed, and Win10 version with build number. Providing a copy of the mRemoteNG.log file would help too (https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging). There *might* be something in the Windows event viewer logs too, but that's hit or miss.

I tried replicating the issue with mRemoteNG portable 1.75.7008 and 1.75.7012 on Win10 Version 10.0.16299 Build 16299 and wasn't able to get it to crash.

**Comment by lolo6218** [comment]
Hello, i facing the same issue on mremoteNG version all 1.75 or 1.76 "Le programme a cessé de fonctionner. Un problème est à l'origine .."
I had to rollback on version 1.74 to continue to use mremoteNG in my job
Regards,
[mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/1743487/mRemoteNG.log)

**Comment by farosch** [comment]
Closing this as it's probably not valid anymore and everyone involved failed to give sparer proper answers to his questions.
Only @lolo6218 did, and he/she is running v1.75 on Microsoft Windows 8.1 Enterprise 64-bit, which we wont support anymore and is not helpful at all in this issue since we were talking about Windows 10
