### ISSUE TITLE
Set default Config values for connections

### ISSUE THREAD

**Issue by briantist** [mRemoteNG/mRemoteNG#863]
The most frustrating thing when doing a quick connect from the top bar, or to a lesser extent creating new connections, is that it doesn't use the settings I want.

I know this is somewhat mitigated for new permanent connections, as long as they are cloned from an existing one (or sometimes they can inherit from the folder).

This is most of all a problem for the immediate connections at the top. I type in a server, connect with RDP, then go to use a shortcut key and it goes to my local machine instead.

I would like a way to set global defaults that apply to new connections (unless those settings are overridden by the folder or something), and especially apply to immediate connections from the top bar.

**Comment by sparerd** [comment]
There is sort-of a way around this by setting the default value you want on the default connectioninfo screen of the connection tree (click Connections node, click the third-from-left button at the top of the connections tree, set the values you want). Though this process and its relationship to the quick connect feature is, at best, cryptic. I think #239 may help with this issue.

Do you think that would solve the issue you are seeing, or is there some other workflow that would be more helpful?

**Comment by briantist** [comment]
Thanks! That definitely was not intuitive but it does solve my issue. I tried to search for this before posting but it seems I missed 2 other instances of it somehow. Since the feature exists, it seems it's better addressed as UI/UX in #238 or #239.
