### ISSUE TITLE
Change location of confCons.xml

### ISSUE THREAD

**Issue by Spockstar** [mRemoteNG/mRemoteNG#869]
Hi, Hope I am not repeating a earlier problem.  Have installed the Windows MSI version of mRemoteNG, imported the connections from the portable version and all working fine.  Have noticed that each time I open the software and close it, it is creating confCons.xml on my desktop.  How do I get it to put these files to save this file into the mRemoteNG programs folder

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment]
I dont think it is configurable at the moment. It will save backups to the same location as the currently loaded connections file

**Comment by BluewateR34** [comment]
Hey, I was searching the solution for the same issue and saw this thread. I found the solution and wanted to share it. Take all these connection files and move them into any folder. Next time when you open the application, it is asking the location of backup files. Simply select and locate the folder which contains your backup files. That's all.
