### ISSUE TITLE
Windows Remote Desktop sessions disconnect and reconnect every time screen is resized

### ISSUE THREAD

**Issue by msmigiel** [mRemoteNG/mRemoteNG#880]
When using Windows Remote Desktop within mRemoteNG, whenever the program window is resized (for example, maximize the window from a non-maximized state), I see the popup from the remote desktop session saying that the session was lost and it is reconnecting. Usually it reconnects in a second or 2 but it still disrupts the session and this shouldn't be happening.

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by sparerd** [comment]
This is due to the option `Automatic Resize`. Set this to `No` for all connections where you do not want to reconnect when the panel size changes
