### ISSUE TITLE
Connected state not saved without "Save connections on exit" option 

### ISSUE THREAD

**Issue by rubaboo** [mRemoteNG/mRemoteNG#883]
|Detail|Value|
|--:|---|
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75.7012.16846  |

I disconnect from every session before exiting, but since "Save connections on exit" is unchecked, the app does not remember that and reconnects to those sessions on next startup.

And why would I keep "Save connections on exit" on, if they get saved on every edit anyways.

Perhaps I'm misunderstanding the option, and it really means "Remember which sessions are open on exit". In that case, it should be renamed to avoid confusion.

**Comment by sparerd** [comment]
I believe this is resolved in v1.76.

A new option `Save connections after every edit` was introduced which makes that functionality configurable. Typically, you would not need both "save after edit" and "save on exit" enabled at once.

Connecting/disconnecting now also counts as an edit, triggering a save. This produced the correct behavior when `Reconnect to previously opened sessions on startup` is enabled.
