### ISSUE TITLE
Menu to copy all and clear scrollback for Putty sessions

### ISSUE THREAD

**Issue by msmigiel** [mRemoteNG/mRemoteNG#890]
In Putty, if you click on the top left icon, you are presented with a menu. Some very useful things don't seem possible in mRemoteNG:

1.) Copy All to Clipboard
2.) Clear Scrollback
3.) Reset Terminal

It would be very handy if these would be present in the right click menu for a given tab.

It would also be very nice to combine both #2 and #3 into a customizable hotkey as I find myself frequently wanting to clear my terminals of old data.

**Comment by kmscode** [comment]
Sorry for the delayed response on this. This is possible in all versions with Ctrl + Right Click in the PuTTYNG session.

Since PuTTYNG is a separate process that is integrated into mRemoteNG's window, there's not much that we can do to put this menu in a more accessible location within mRemoteNG.
