### ISSUE TITLE
Add a View Only mode

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#896]
There are times where I would like to be able to move the mouse over a remote session (RDP/VNC/etc) without the mouse being tracked on the remote machine. I would like to be able to toggle a view-only mode per-connection while connected to a remote machine.

**Comment by sparerd** [comment]
This will be fairly easy for mouse movement/clicks. We can create a transparent panel over the connection and intercept all mouse events. Might be a bit more involved with keyboard input though. It might be enough to unfocus the connection and not provide a way to focus it again for keyboard purposes.

**Comment by sparerd** [comment]
Turns out that doing this for RDP connections is very easy. Simply setting the AxHost control's `Enabled` property to false puts it into a view only mode. This won't be a connection info property so the implementation is very light. I'm going to add this to v1.77

**Comment by FickoDeLux** [comment]
This implementation kicks out logged in user on windows 10.

The right one would be:

`
HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services set to 4
`
`
mstsc.exe /v:<server> /shadow:<ID> /noConsentPrompt
`
