### ISSUE TITLE
can not execute win10 bash from external tool

### ISSUE THREAD

**Issue by Pisamad** [mRemoteNG/mRemoteNG#897]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

Hi,
I want to open win10 bash from external tool but, bash is no seen !
If I open cmd from external tool and list content of c:\windows\system32, there is no bash.exe.
From the host, I can check that bash.exe exists.

How can I do ?

Thanks

**Comment by zzjeagle** [comment]
You should call cmd.exe
