### ISSUE TITLE
Expanded mandatory in confCons.xml but not described in xsd

### ISSUE THREAD

**Issue by syco26** [mRemoteNG/mRemoteNG#898]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7012.16814 |

Hi all
I'm having toubles generating a valid confCons file using java/jaxb.
One of the difficulties I've met is with the expanded xml element.
**mRemoteNg enforces this field which is not described in the xsd I've checked 2.6 to 2.8.**

Error for a missing such field results in a failure to load confCons; starting is impossible.
#########
at mRemoteNG.Config.Serializers.XmlConnectionsDeserializer.AddNodesFromXmlRecursive(XmlNode parentXmlNode, ContainerInfo parentContainer)
at mRemoteNG.Config.Serializers.XmlConnectionsDeserializer.AddNodesFromXmlRecursive(XmlNode parentXmlNode, ContainerInfo parentContainer)
at mRemoteNG.Config.Serializers.XmlConnectionsDeserializer.Deserialize(Boolean import)
##########

Having this fixed would prevent a quite ugly work around in my code...
Any idea?

Thanks for support
Best regards, Syco

**Comment by sparerd** [comment]
The xsd was a little out of date. I've done a bit of work to bring it in line with the current connection models we are using. An updated version is available here: https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Schemas/mremoteng_confcons_v2_6.xsd

We currently do not use the v2.7 or v2.8 schemas - those were created for the credential manager feature which was delayed. v2.6 is the xml schema in use for mRemoteNG v1.75 (and v1.76, currently in alpha)

Let me know if that XSD works for you.

**Comment by syco26** [comment]
Thanks a lot for the quick fix and the information.
It seems we have another glitch in the xsd is with the "Export" optional field; it is not described in xsd while mRemoteNg always set it.

**Comment by sparerd** [comment]
Schema is updated with the Export field. I had originally removed that field since v1.76 does not require it, but that is not safe for v1.75 which still checks for that field.

**Comment by syco26** [comment]
I'm sorry I was not aw<are of your changes in 1.76 regarding the export field, I should have checked it.
And of course the xsd in master branch should be aligned with the code.
And this was anyway a non blocker issue for me, as the confCons.xml file is loaded ok without it.

Thanks
Syco

**Comment by sparerd** [comment]
Not a problem. I haven't been very disciplined in versioning the xml files which will get me into trouble at some point. I'm glad you brought all of this up so I can get some more testing in place before the v1.76 general release.
