### ISSUE TITLE
DoNotPlay is Case Sensitive in XML Serialization

### ISSUE THREAD

**Issue by nerddtvg** [mRemoteNG/mRemoteNG#899]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.1 Alpha 3  |

The XML file contains the setting:

`RedirectSound="DoNotPlay"`

When the XML file is saved by the application, DoNotPlay is converted to lowercase:

`RedirectSound="donotplay"`

When the application is reopened, errors parsing the files occur:

```
ErrorMsg
2/27/2018 9:19:13 AM
An error occured while loading the connection entry for "SERVER_NAME" from "". Requested value 'donotplay' was not found.
```

Manually editing the XML file to camel-case DoNotPlay resolves this issue.

**Comment by sparerd** [comment]
Thanks for reporting this. I fixed the bug and it will be available in the next v1.76 pre-release

**Comment by nerddtvg** [comment]
@sparerd 

Thank you. Super fast!

**Comment by duttyend** [comment]
I can confirm it is fixed, thanks a lot !
