### ISSUE TITLE
Floating menu bar

### ISSUE THREAD

**Issue by ghgymo** [mRemoteNG/mRemoteNG#902]
In previous versions, you could move (float) the File menu bar to say the bottom of the screen so as to have a completely clean screen once connected to a host.  I cannot move the File menu bar anymore.  Please re-enable that feature again.  It was very very very very useful.

**Comment by rootkiting** [comment]
totally agree ！

**Comment by sparerd** [comment]
Sure thing, I'll re-enable that in the next v1.76 pre-release.

**Comment by sparerd** [comment]
The ability to move the menu bar is now tied to the View -> "Lock toolbar positions" menu item. This will be available in the next v1.76 release

**Comment by runguyenhuu** [comment]
Hi everyone !
Can we hide menu bar, workspace will be wider ?

**Comment by sparerd** [comment]
@runguyenhuu You can follow issue #666 for that enhancement request

**Comment by runguyenhuu** [comment]
Dear Team !
Can you send to me privious version ( dremote) ? I like this verision very much. My email is runguyenhuu@gmail.com.
Thank you very much
