### ISSUE TITLE
Add option to disable trimming leading/trailing whitespace in username/password

### ISSUE THREAD

**Issue by chekamarue** [mRemoteNG/mRemoteNG#907]
Hey,

Is there anyway to disable auto space deletion from the username form

**Comment by johnwc** [comment]
I think you need to give more details, possibly with screenshots. What form?

Also, what purpose is this for? As far as I am aware, most OS do not support using spaces in usernames.

**Comment by chekamarue** [comment]
As an extra security measure I add space at the end of my usernames string but when using mremoteNg in the the rdp username box ! there is a function of removing space!
my username: "Admin "
but entering this value in the username box 
my username: "Admin" which will be declined 
is there anyway to disable space remove and keep the username as it's entered by the user?

**Comment by farosch** [comment]
Adding a space behind a username is ***not*** a security measurement, it's just adding a character.
Just like the login name **Users** isn't safer than **User**, it's just longer. Usernames are nevertheless readable through the UI so there's no advantage here, if anything it's a disadvantage for users copy-pasting usernames.
Since you're talking about RDP I'm guessing youre talking about Windows machines. Windows does indeed allow spaces in usernames, if they are notat the end or beginning, and these are not trimmed off by mRemoteNG.
So I don't see any reason why this should be implemented.

**Comment by chekamarue** [comment]
Well ! in first place, I was asking if there is a way to diable trim function from the username variable ! since you dont see the need of it to be implemented ! I would say just unfortunate cause it would have helped a lot

**Comment by johnwc** [comment]
He clearly states that what you are claiming is not in fact happening via mRemoteNG.

> Since you're talking about RDP I'm guessing you're talking about Windows machines. Windows does indeed allow spaces in usernames, if they are not at the end or beginning, **and these are not trimmed off by mRemoteNG.**

**Comment by chekamarue** [comment]
but what i'm experiencing it through mRemoteNg ! i'm using for more 50 Vps ! and the space is removed if exist in the beginning or the end of the username string which i'm asking if i can disable this function as most of my usernames login are with space at the end 

My only solution for now is setting the default logins option if no credentials exist ! as there is no trim function for that field

**Comment by farosch** [comment]
You really need to start answering questions if you want us to help you ;)
-What protocols are you talking about?
-What kind of operating system are you connecting to?
To get back to your question: **NO**, currently there is no such feature to disable trimming of login names. It could be easily implemented if you can give us a reason why it should be.
I have nearly 1000 machines in my configuration, all different operating systems and protocols and have never in 5 years needed the possibility to have leading/trailing spaces for a username.
Linux does not allow spaces in usernames at all (like most other operating systems) and Windows _does not allow spaces in usernames when trailing/leading_, so why should it be possible to do so in mRemoteNG?

**Comment by chekamarue** [comment]
Sorry for the delay reply I thought my request was already closed !
Well i'm using rdp protocol to connect to my windows 2003 & 2008 machines and both allow space in the end or the beginning of username string!
i'm not asking you to implement it cause most of windows users dont know this trick and trim function help to solve many copy past unwanted spaces
but i was hoping if there is a easy way to disable it, I would be really thankful

**Comment by chekamarue** [comment]
for note ! i have been using both Remote Desktop Connection Manager 2.7 and Terminals_v4.0.1 and none use the trim function for username ! I think you should let the user choose to enable it or disable it ! as it look like a restriction

**Comment by sparerd** [comment]
Probably wouldn't hurt to add an option to disable the trimming. Not sure when I will be able to get to it though

**Comment by chekamarue** [comment]
can please we see it in te next  v1.76 pre-release

**Comment by chekamarue** [comment]
Thank you very much for your hard and good work 
will contribute through my bitcoin wallet to your project since i'm using it daily

**Comment by chekamarue** [comment]
that so unfortunate... 
Can you please show me how to disable that function in the source code of 
https://github.com/mRemoteNG/mRemoteNG/archive/v1.75.7012.zip
which file should i look into ? even tho my programmation skills are so limited --
if anyone can make it for me! i would pay for it 
please advise

**Comment by johnwc** [comment]
I can do a pull request and make the needed modification. I'll try to get it done sometime this next week.

**Comment by chekamarue** [comment]
that would be highly appreciated,, will be waiting for it !

**Comment by chekamarue** [comment]
@johnwc  how can i contact you ?
