### ISSUE TITLE
Inheritance enabled after upgrade

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#908]
I copied my confCons.xml and extApps.xml from 1.75.7012 to 1.76 Alpha 3 (portable).
First everything looks fine. Today I started mremoteng again and now inheritance is enabled for everything also on fields where I had disabled it before like username and password.

My configuration was: I enabled Inherit All on the root connection and disabled it on subfolders/connections where needed.

1.75
![175_root](https://user-images.githubusercontent.com/6205123/37020372-d4491254-211b-11e8-9c86-eb1bba2e1794.png)
![175_admin](https://user-images.githubusercontent.com/6205123/37020373-d463b488-211b-11e8-83ca-1e9c09780890.png)

1.76
![176_root](https://user-images.githubusercontent.com/6205123/37020374-d47a477a-211b-11e8-858e-7b78d6c0bea7.png)
![176_admin](https://user-images.githubusercontent.com/6205123/37020376-d4922b9c-211b-11e8-9c9a-1c58a718ce1c.png)

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.1.21655  |

**Comment by malfuncion** [comment]
This looks to be related to my issue #903. This was resolved for me in build 1.76.2.14923

**Comment by LIyoai** [comment]
Thanks @malfuncion 
I tried mRemoteNG-Portable-1.76.2.14965.zip right now. My issue from above is resolved but now default inheritance in the root connections is disabled which was enabled in the 1.75.
Not a big issue for me but if you don't notice that it gets disabled during the update it can create some work afterwards.
What I also noticed: the first start with my old confcons.xml took about 3 minutes with an unresponsive window, maybe a status window or a message box can indicate that mremote is doing something in the background (updating connection file?).

**Comment by sparerd** [comment]
@LIyoai Is this still an issue you are noticing? Was this just when initially upgrading from v1.75 to v1.76?

**Comment by LIyoai** [comment]
Default Inheritance on the root connection is disabled after going from 1.76.6 to 1.76.7.

**Comment by sparerd** [comment]
If you are using the portable edition, are you also copying the mRemoteNG.settings file to the new version? This is the file where default connection/inheritance information is saved.

**Comment by sparerd** [comment]
@LIyoai I am fairly sure that the default-inheritance behavior you are seeing is due to the default settings being saved in the `mRemoteNG.settings` rather than in the connections XML file. When migrating to a new portable version, also copy the `mRemoteNG.settings` from the old portable folder to the new one.
