### ISSUE TITLE
could you design multiple credential for every group not one credential in Options?

### ISSUE THREAD

**Issue by wgboy168** [mRemoteNG/mRemoteNG#909]
|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75.7008  |

**Comment by johnwc** [comment]
You can add credentials at the folder level, and then have your sub folders and items inherit from their folder they are in.

**Comment by sparerd** [comment]
The credential repository feature (#208) will allow you to do this once implemented. Please follow that issue for further updates
