### ISSUE TITLE
Need more simultaneous connections

### ISSUE THREAD

**Issue by Greenice33** [mRemoteNG/mRemoteNG#910]
When will it be done to support simultaneous connection of more than 20 pieces? Really need( I'm willing to pay for eto'o

**Comment by sparerd** [comment]
It may be a bit before we can support this. We need to build the project for x64 so we can use more memory.

**Comment by Greenice33** [comment]
Can I import and run multiple connections at once? Example
54.202.139.61 Administrator ?Uuvfy?Pj=K
54.212.215.27 Administrator-aP*LQSa&J
54.2012.11.171 administrator pbox-Ycjh%M
If not, make this a very useful feature for everyone?

**Comment by kmscode** [comment]
This will require the 64 bit build. Please follow #915 for further progress.
