### ISSUE TITLE
Create 64-bit build

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#915]
Create an x64 release of mRemoteNG to make use of higher memory limit. There have been several issues that would be resolved or mitigated by this.

Other questions to answer:
- Do we keep the x86 build around?
- The Citrix ICA protocol library seems to be x86 only. Do we drop support for ICA?

**Comment by sparerd** [comment]
Sounds good - is #155 something that could be done in v1.77? That release is getting pretty full already, but having 2 windowing frameworks is annoying.

**Comment by kmscode** [comment]
I'd rather have this in 1.77 than some of the other stuff... This will simplify things going forward and allow us to more easily get to some other bugs/enhancements by just having to detail with DockPanelSuite.

**Comment by kmscode** [comment]
And by "this" I mean DPS only (no MagicLib) AND 64 bit build.

**Comment by sparerd** [comment]
I'd like to at least get a survey of how many users are using ICA. If it's large enough, maybe we can find some sort of work around. Maybe keep the x86 build as well and offer ICA as a plugin. I'd hate to cut off a bunch of users that may consider lack of ICA support a deal breaker.

**Comment by chris-sung** [comment]
OR we can just support both builds with the limitation of ICA only supports for x86

**Comment by domoaligato** [comment]
I also have issues trying to created x64 powershell processes from mremoteng because of the builds being x86.

**Comment by farosch** [comment]
Since merging #1763 ICA support has been removed from mRemoteNG.
There's nothing holding us back from releasing 64bit builds now.

IMHO we should just drop 32 bit builds and switch to x64 entirely. What do you guys think? @Kvarkas @kmscode ?

**Comment by Neustradamus** [comment]
@farosch: Note that it is possible to enable some "parts" only in x86 and disable in x64...

Important: It is needed to always publish x86 in more x64 builds!

**Comment by Kvarkas** [comment]
I think we can, as almost all systems now can work in x64 mode and we not gona support legacy stuff

**Comment by simonai1254** [comment]
I guess the new releases are built x64, therefore one might check if the memory issue is still around...

In my point of view there is no need to provide x86 builds anymore.

**Comment by farosch** [comment]
Yes, builds are now 64bit, and I fully agree on @simonai1254 that there is no need for 32 bit any more.
