### ISSUE TITLE
Default properties not saved

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#916]
I thought there was already a bug regarding this but I could not find it.
Default properties for example for redirect key combinations is not stored. Which is really annoying.

|Detail|Value|
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.2.14965  |

**Comment by sparerd** [comment]
Found the issue and improved the testing around this area. I still want to add some more tests, but this should be resolved in the next alpha release

**Comment by LIyoai** [comment]
Awesome. Thank you :-)

**Comment by sparerd** [comment]
Note to self: finish tests for default connection inheritance saving/loading

**Comment by sparerd** [comment]
Tests are finished and merged to develop. I will be releasing a new v1.76 pre-release this weekend that includes this fix
