### ISSUE TITLE
Resizing RDP connection causes reconnect

### ISSUE THREAD

**Issue by Titus-s** [mRemoteNG/mRemoteNG#917]
Hi, 
In RDP resizing window causes reconnect connection. Later it gives message that service remote desktop cannot find computer, but I can still connect to this computer by doubleclick. 
Is it possible to avoid reconnection on resize? Remote Resktop Manager resize embedded RDP in this case.

**Comment by sparerd** [comment]
I just wrote up an FAQ section for this. Let me know if this answers your question:

https://github.com/mRemoteNG/mRemoteNG/wiki/FAQ#rdp-tries-to-reconnect-whenever-i-resize-the-window-
