### ISSUE TITLE
general+new panel tab in alpha

### ISSUE THREAD

**Issue by ibrahim052** [mRemoteNG/mRemoteNG#919]
|Detail|Value|
Every time a connection is initiated, opens in GENERAL tab besides NEW PANEL tab.
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.76.3.32942  |

**Comment by malfuncion** [comment]
I had this problem until I closed the "New Panel" tab. It does appear that new connection are being created with the PANEL option blank which will cause it to prompt you on each connect. I modified my XML and did a replace PANEL="" with PANEL="General". Hope that helps for a work around.

**Comment by ibrahim052** [comment]
its so nice of you to respond instantly and with complete guidance. What I did is slightly different but it worked. In my XML I changed "General" to "New Panel" and everything is working normally. Thank you for your help.

**Comment by kmscode** [comment]
Related to #802 which has been fixed.
