### ISSUE TITLE
Notification for "No Host Specified" when navigating

### ISSUE THREAD

**Issue by deancmdowell** [mRemoteNG/mRemoteNG#924]
## Expected Behavior

When using the Connections icon to navigate you receive a notification stating "Cannot open connection:  No host specified" each time you click on a folder.

## Current Behavior

You can hover over the folders and connections with no issues but when you mouse-click on a folder you get this error message.

## Possible Solution

The solution for me at the minute is to not click on the folders but as a habit I had been clicking to navigate through the folders.

## Steps to Reproduce (for bugs)

1.  Click on the Connection icon (globe) - no issues at this point
2.  Click on a folder - you will get redirected to the notifications tab with the error
This will happen if you click on any folder until you get to your server connection

## Context

It is an annoyance as being redirected to the notifications tab is a distraction but does not impact what the application is designed for.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Win10 Enterprise - 64bit
mRemoteNG Version:  1.76.3.32942

**Comment by sparerd** [comment]
This is now resolved. If we detect a menu click on a folder, we will just ignore it and open the next sub-menu. The fix will be available in the next v1.76 release
