### ISSUE TITLE
Include server name in Notification - enhancement request

### ISSUE THREAD

**Issue by daves127** [mRemoteNG/mRemoteNG#929]
## Expected Behavior
----------
WarningMsg
3/29/2018 1:23:50 PM
RDP disconnected from server <xxx>!
516 Remote Desktop can’t connect to the remote computer for one of these reasons:
1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network
Make sure the remote computer is turned on and connected to the network, and that remote access is enabled.
----------

## Current Behavior
----------
WarningMsg
3/29/2018 1:23:50 PM
RDP disconnected!
516 Remote Desktop can’t connect to the remote computer for one of these reasons:
1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network
Make sure the remote computer is turned on and connected to the network, and that remote access is enabled.
----------

## Possible Solution
na

## Steps to Reproduce (for bugs)
go to lunch, have servers inactive time out.  Good luck remembering which ones were open. 

## Context
After lunch, or meeting, or extended interruption... lose rdp to some servers... dont recall which ones.. yet I stay logged to them till ...

## Your Environment
Windows desktop, using mRemoteNG to rdp to windows servers... versions 2008-2016.

**Comment by farosch** [comment]
As a workaround you can enable this
![mremoteng_2018-04-11_22-42-04](https://user-images.githubusercontent.com/22905106/38642202-adf3a972-3dd9-11e8-9149-c35243a7523d.png)

**Comment by sparerd** [comment]
*Dev notes*
Looks like `ConnectionInitiator.Prot_Event_Disconnected()` is the method to update for this particular RDP error. However, it looks like there are 2 or 3 places where RDP errors can be caught/handled. It might be worth taking the time to refactor and simplify things.

**Comment by kmscode** [comment]
@sparerd - any other places that this needs to be implemented? In my review/testing, looks like most of them now include the hostname...

**Comment by sparerd** [comment]
@kmscode I think we can consider this implemented now
