### ISSUE TITLE
When I set the system fonts to big(150%)...

### ISSUE THREAD

**Issue by sandyyz** [mRemoteNG/mRemoteNG#941]
Hello, I met a bug when I set my windows system's fonts size to big(150%). Please help me, thank you!

## Steps to Reproduce (for bugs)

1. Change windows system's display properties
2. Change system fonts to Large(150%)
3. Cannot click on the remote desktop windows' close button

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):
Windows 7 sp1 x64 (6.1.7601)

**Comment by sparerd** [comment]
Hi @sandyyz, this is due to mRemoteNG not having support for High DPI environments. You can follow #321 for further updates
