### ISSUE TITLE
Remove Help and Changelog from Application

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#947]
Wouldn't it be better to remove the integrated help and make **Help** > **mremoteNG Help** just open a browser pointing to [https://github.com/mRemoteNG/mRemoteNG/wiki](https://github.com/mRemoteNG/mRemoteNG/wiki)?
This would make it easier to maintain the help/wiki for people willing to do so as they could do this on github. Also it would bring all information into one place and unclutter mremoteNGs source code.
I would suggest to do the same thing with **Help** > **About**, just let it point to the specific release on [https://github.com/mRemoteNG/mRemoteNG/releases](https://github.com/mRemoteNG/mRemoteNG/releases)

**Comment by sparerd** [comment]
I'm open to having the help files just on our wiki to help maintainability.

There isn't much use in getting rid of the change log file though, since we update that as we work through a release and copy it into the Github release once we publish.

**Comment by farosch** [comment]
Can be closed. See above comment and #1201 #1223 #1228
