### ISSUE TITLE
AltGr combinations not working properly with the embedded VNC client 

### ISSUE THREAD

**Issue by vicenten** [mRemoteNG/mRemoteNG#95]
With mRemoteNG 1.68 and 1.69RC1, I cannot use the AltGr key combinations in VNC sessions. These key combinations are very important in the Spanish keyboard as they are required for characters such as \ | [ ] { } # ~.

When using AltGr key combinations I may get a weird character, but in any case, not the expected one. 

I can use AltGr combinations without problems in RDP sessions.

**Comment by Phyliares** [comment]
This bug still exists on windows 7 with fr-fr locales

**Comment by FRibadeau** [comment]
Hello,

Please note that this bug still exists with version 1.76.20.
As I use your product to connect to my Linux Desktop, having no pipe ( | ) character is not acceptable.

Thanks for your help
