### ISSUE TITLE
Always empty panel 'Neues Panel' (1.76 Alpha)

### ISSUE THREAD

**Issue by Laetterman** [mRemoteNG/mRemoteNG#952]
Hi
Every time I open an connection there is an empty Panel 'Neues Panel' created (see Screenshot)
Regards
Marc
![image](https://user-images.githubusercontent.com/38464361/38870654-c6166232-424e-11e8-98a6-f0b54e763dbc.png)

**Comment by LIyoai** [comment]
Maybe somehow related https://github.com/mRemoteNG/mRemoteNG/issues/952

**Comment by sparerd** [comment]
An option was added in 1.76 alpha 6 (defe9e0) to allow you to toggle this. Options -> Tabs & Panels -> `Create an empty panel when mRemoteNG starts`

This also allows you to name the panel
