### ISSUE TITLE
Feature Request : Secure launch by a password ?

### ISSUE THREAD

**Issue by dcpc007** [mRemoteNG/mRemoteNG#953]
Hi

Is it possible to secure the config content when opening the application, having like a password to unlock the config file (especially when password are stored). ?

**Comment by sparerd** [comment]
There is currently no 'temp lock' like you've mentioned, though you can encrypt the connections file with a custom password. Click the Connections tree node -> Set `Password protect` to `Yes` -> Enter your desired password.  When mRemoteNG starts, you will need to provide that password to open the connections file.

**Comment by Pouet78** [comment]
Agreed. Should be offered as default behavior.

**Comment by sparerd** [comment]
You can follow #376 to get updates about making the custom password a mandatory feature.
