### ISSUE TITLE
errore reading xml with mremote

### ISSUE THREAD

**Issue by lucaalbizzati** [mRemoteNG/mRemoteNG#956]
Good morning,
i have a errore during read the xml file at last line.
Any idea ?

Thankyou

**Comment by sparerd** [comment]
Does your mRemoteNG.log file have any useful errors? https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by Kvarkas** [comment]
Unclear and to old, but i am expecting its related to Connections loading process that is under rework now.
