### ISSUE TITLE
Encrypted password for sites in SQL DB

### ISSUE THREAD

**Issue by dnzmartijnkamminga** [mRemoteNG/mRemoteNG#957]
Encrypted password for sites in SQL DB is currently not the case

## Expected Behavior
Hashed passwords or another security measure would be better to increase security and defaulting to this app.

## Current Behavior
When having access to the DB's passwords can be viewed by viewing the table properties.
Credentials for the SQL DB must be provided, giving access to the DB.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Using SQL Studio Management and Accessing the DB

## Context
I'm trying to standardize the application, enforcing if you may, but credentials are not to be retrieved.

## Your Environment
Operating System and version Windows 2016 1607
Operating System and version Windows 10 1709 x64
Application: SQL Server 2012r2
Application: SQL Management Studio 2016

**Comment by damousys** [comment]
Hey is there any update about this problem / feauture request ?

**Comment by sparerd** [comment]
Closing as duplicate of #449
