### ISSUE TITLE
Unable to save putty settings in the mremoteNG

### ISSUE THREAD

**Issue by mugali93** [mRemoteNG/mRemoteNG#960]
Unable to save putty settings in the mremoteNG

## Expected Behavior

Under Tools>Option>Advanced> launch putty

I changed some settings for the putty like background color but unable to save those.
So I have change the seeting every time whenever i open a new session.

I should be able to save those custom putty settings 

## Current Behavior

I changed some settings for the putty like background color but unable to save those.
So I have change the seeting every time whenever i open a new session.

## Steps to Reproduce (for bugs)

Use the version 1.75.7012.16814 and try to save your custom putty session settings

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by kmscode** [comment]
When in the PuTTY setting, Load the "Default Settings" -> make you changes -> Save "Default Settings"
![image](https://user-images.githubusercontent.com/16654335/43367235-ed992956-9317-11e8-8d23-9ad76d6bb6af.png)
