### ISSUE TITLE
confCons.xml overwritten

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#961]
Entering wrong password at start prompt will save an empty confCons.xml

## Expected Behavior
I expect that the file would not be changed.

## Current Behavior
Empty file will be saved

## Possible Solution
I guess this is from the option "save connection on exit".
Configuration file should be locked for read and write when the provided password was wrong.

## Steps to Reproduce (for bugs)
1. Start mRemoteNG
2. Type three times a wrong password 
3. empty mRemoteNG will start
4. Close mRemoteNG
5. confCons.xml is overwritten

## Your Environment

* Version used: 1.76.2.14965
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 x64

**Comment by sparerd** [comment]
I've committed a fix for this in 9659ac1. We will now prompt for what to do when decryption fails, similar to how we prompt when a connection file cant be found. This should no longer cause the confCons file to be overwritten.

This will be available in the next v1.76 release
