### ISSUE TITLE
Feature Request - Close panel

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#962]
I would like to close a panel with a right click

## Expected Behavior
When I right click on a panel I want to have a close option

## Current Behavior
I need to go to the far right 'x' to close the panel
![image](https://user-images.githubusercontent.com/6205123/39168652-f9994462-4794-11e8-9a79-daba4656f9d2.png)

## Possible Solution
Add a close option
![image](https://user-images.githubusercontent.com/6205123/39168678-231585c6-4795-11e8-8bf3-fd731ffded6b.png)

## Your Environment

* Version used: 1.76.2.14965
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 x64

**Comment by kmscode** [comment]
This was resolved with the replacement of magiclibrary via #155 and will be included in the 1.77 release - which will be alpha soon.

Each panel now has it's own close button. No right click required:
![image](https://user-images.githubusercontent.com/16654335/54090988-dfa3a800-4350-11e9-98e8-a86e6b52bcd4.png)
