### ISSUE TITLE
Feature Request - Name of 'New Panel'

### ISSUE THREAD

**Issue by LIyoai** [mRemoteNG/mRemoteNG#963]
I would like to rename the 'New Panel' because all my saved connections will open in 'General', 'Linux' etc. and the 'New Panel' is not used by me. But it is always the first in the quick connect selection.

## Expected Behavior
I would like to have an option to provide a name for this panel.

## Current Behavior
I can rename the panel but after restarting it is again 'New Panel'

## Possible Solution
Provide an option to specify a name

## Steps to Reproduce (for bugs)

1. Start mRemoteNG
![image](https://user-images.githubusercontent.com/6205123/39168854-c364fb10-4795-11e8-9b5c-b95cb5f0b380.png)

## Your Environment

* Version used: 1.76.2.14965
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 x64

**Comment by sparerd** [comment]
An option was added in 1.76 alpha 6 (defe9e0) to allow you to do this. Options -> Tabs & Panels -> `Create an empty panel when mRemoteNG starts`

This also allows you to name the panel
