### ISSUE TITLE
Putty connection names encoding

### ISSUE THREAD

**Issue by jelinj8** [mRemoteNG/mRemoteNG#968]
PuTTY connection created with Putty named "Pyšely", "ostrá"... produce unknown characters in connection list

## Expected Behavior
original characters expected

## Current Behavior
question marks in place of accented characters

## possible workaround
+ an option to set codepage for setting from registry?

## Your Environment
* Version used: 1.75.7012.16846
* Operating System and version Windows 10 1709 x64, Czech (probably win-1250 in registry)

**Comment by LIyoai** [comment]
Is it related to https://github.com/mRemoteNG/mRemoteNG/issues/800?
This is fixed in 1.76 Alpha2. Maybe worth a try.

**Comment by kmscode** [comment]
closing as duplicate of #800
