### ISSUE TITLE
Program Not Responding and needs to close..

### ISSUE THREAD

**Issue by smadz** [mRemoteNG/mRemoteNG#970]
## Expected Behavior

not crash all the time.. this happens to me several times a day..

## Current Behavior

i get this error message 2 - 4 times a day..

## Possible Solution

??

## Steps to Reproduce (for bugs)

i have tried forcing a crash by doing different things.. one desktop open to ten remote
desktops open and it still crashes.. it seems to be random.. very strange..

1.
2.
3.
4.

## Context

we have over 60 servers in our schools and it is very frustrating to have connections
going and updating servers and checking on servers and have the program crash..

## Your Environment

* Version used: 1.75.7012.16814
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1709 64bit

![mremoteng_2018-05-02_075918](https://user-images.githubusercontent.com/38914530/39524929-34c3f4fa-4de0-11e8-8418-47100236bfd8.jpg)

**Comment by carlowolter** [comment]
We have a similar problem.
Sometimes by opening a session (even the first one...) leads to a grey panel, and "Not responding" behaviour.
In addition, no way to close is forcefully (Task Manager, Process Explorer, taskill....  to no avail...)
Very often (Windows 10 Pro) is not allowing even a restart, need to switch off the notebook by hand

**Comment by kmscode** [comment]
Open Task Manager -> Details -> Right click on the mRemoteNG.exe process -> Create Dump file. Attach the dump to the issue. 

Also, please attach the [mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging)

**Comment by kmscode** [comment]
If you have any cloud storage options available (Google Drive, etc) you can upload to there and share via e-mail to support@mremoteng.org

https://nofile.io/ seems like it should do the trick as well, though I haven't found many reviews of this site (outside of one MakeUseOf post) and haven't used it personally (yet).

Optionally, if you can attempt to zip it again using 7-Zip and use a .7z archive with LZMA2/ultra compression - that tends to get dump files down to a reasonable size. The attachment limit is 25mb. You may need to then rename to .zip or then add the .7z into a .zip file if the .7z is small enough to attach.

**Comment by farosch** [comment]
Closed due to inactivity. Will reopen and investigate further whe a dump file is provided.
