### ISSUE TITLE
mRemoteNG 1.76.x (1.76.3.32991) won't accept / won't load user.config changes (Win DC-Netzwork)

### ISSUE THREAD

**Issue by Qixuga** [mRemoteNG/mRemoteNG#973]
Normaly, after first start the user.config in AppDataLocal-Folder will be loaded with given settings to config files confCons.xml and other scripts.

But every restart the assistant pop of and ask again - no config loaded.

Also the generating of new config files failed.

Version 1.75.x did work correctly. 

We used clients in a windows-network with domain-controller.
AppDataLocal is on the local Store, AppData is relocated through the fileserver.

- Windows 10 1709 x64

**Comment by sparerd** [comment]
If I'm understanding correctly, you are having issues with saving/loading user.config because your environment uses roaming profiles. Is that correct?

If so, this is related to #690 / #414.

**Comment by Willi3390** [comment]
I'm facing the same problem.  Roaming profiles are not supported by mRemoteNG. Is there any perspective that this Problem will get fixed?

**Comment by farosch** [comment]
Closed, because both versions (MSI and Portable) now use the `%APPDATA%` directory
