### ISSUE TITLE
Unable to close docked connection panels

### ISSUE THREAD

**Issue by sadegr** [mRemoteNG/mRemoteNG#977]
## Expected Behavior

The "X" button in the top right corner of a connection panel should close the panel.

## Current Behavior

The "X" button in the top right corner of a connection panel appears to do nothing.

## Steps to Reproduce (for bugs)

I've provided a screenshot to clarify what I'm referring to. The "New Panel" connection panel encircled in red (in both the View > Connection Panels menu as well as the connected sessions view) has an "X" button in the top right which does not close the panel. The arrow buttons next to it don't appear to do anything either.

![docked connection panel](https://user-images.githubusercontent.com/20391979/39781741-164767ca-52de-11e8-8787-62173fbf9345.png)

To replicate this example:
1. Go to View > Add Connection Panel
2. Drag the new connection panel into a docked configuration by left clicking (and holding the mouse button down) on the connection panel's tab (shown in blue and labeled "New Panel 1" in the screenshot) and then dragging it to any of the options shown on the "docking" interface that appears on the screen, other than the "middle" docking option (which docks the connection panel to the view it is already in).
3. The connection panel will now no longer have a tab at the top; there will be a left arrow, right arrow, and X buttons in the top right corner of the panel. However, this "X" button does not close the connection panel and I have not found a way to close a connection panel in a docked configuration other than a) dock another connection panel to the same view as the connection panel you're trying to close, causing tabs to appear for both connection panels, or b) close the connection in the connection panel, if there is one.

## Your Environment

* Version used: 1.75.7012.16814
* Operating System and version: Windows 10 1709 x64

**Comment by kmscode** [comment]
This was resolved with the replacement of magiclibrary via #155 and will be included in the 1.77 release - which will be alpha soon.

**Comment by interbiznw** [comment]
Where can one get this release? really a pain not being able to completely close panels

**Comment by simonai1254** [comment]
> Where can one get this release? really a pain not being able to completely close panels

All releases can be found here: https://github.com/mRemoteNG/mRemoteNG/releases
Right now i suggest you use 1.77.2 which works best, the newer 1.77.3 currently has "Saving Settings" disabled for development features.

**Comment by mesnati** [comment]
It doesn't work on 1.77.2 neither :( Panel always stays open even if close all connections. :(

**Comment by camacici** [comment]
2026 here, same problem!
v1.76.20.24615
