### ISSUE TITLE
mRemoteNG is not opening anymore...

### ISSUE THREAD

**Issue by Tommy2112** [mRemoteNG/mRemoteNG#983]
Hi,

I'm using mRemoteNG for years now, have everything configured perfectly for me and I have to work daily with it.
Since today in the morning it doesn't open anymore. I had no updates installed (windows, mremote, ...) in the last few days, until yesterday in the evening mRemote worked like always...

I've already repaired it, and also I already made a clean new installation. But the program doesn't open anymore...

I have a Lenovo Yoga 12" running on Windows 10 (1709)

**Comment by Philippwolf** [comment]
Not involved in this project, but check out the Windows Event-Viewer Errorlog and post the corresponding log here.

A software simply not executing without a trace is not possible!

**Comment by sparerd** [comment]
In addition to @Philippwolf's suggestion, check the mRemoteNG.log file as well.

https://github.com/mRemoteNG/mRemoteNG/wiki/Troubleshooting-and-Logging

**Comment by kmscode** [comment]
On the same page that @sparerd noted, check out the section about the crash on startup and the user.config file. 😄

**Comment by sparerd** [comment]
Glad it's working for you again!

**Comment by lilkoolaid** [comment]
@sparerd 's recommended article helped me fix my issue as well.

Thank you!

**Comment by w-turner-getbamboo-io** [comment]
Clearing these two folders fixed the problem for me - however my connections were lost - you may want to take a copy of any connection files in the folder before deleting and copy them back after
```
C:\Users\<your_username>\AppData\Local\mRemoteNG
C:\Users\<your_username>\AppData\Roaming\mRemoteNG
```

**Comment by hugofana** [comment]
Hi,

In my case I had confCons.xml.xxx.backup.
So I deleted the main file and tried to open with Notepad++ a backup one.
The most recent file that opened without any error with notepad, i renamed it to confCons.xml and saved it.
Then I did clear the folder:

C:\Users\<your_username>\AppData\Local\mRemoteNG

Opened again mRemoteNG and searched for the file that i renamed and saved.
Everything works normally. Probably was a problem occurred in the last mRemoteNG utilisation and the file become corrupted.

Thanks you all.

**Comment by Arnd-Peter** [comment]
Even though this article is from 2018 it helped me a lot. Deleting the user.ini file was the working approach.
Still I had backups of the old file so it was the solution to me ! Thanks !

**Comment by Bleauhaus** [comment]
Same results as below 

@w-turner-getbamboo-io 
Clearing these two folders fixed the problem for me - however my connections were lost - you may want to take a copy of any connection files in the folder before deleting and copy them back after

C:\Users\<your_username>\AppData\Local\mRemoteNG
C:\Users\<your_username>\AppData\Roaming\mRemoteNG
