### ISSUE TITLE
Problème base de données SQL

### ISSUE THREAD

**Issue by Jula79** [mRemoteNG/mRemoteNG#987]
# Problème rencontré
A l'ouverture de mRemoteNG les connexions stockés dans la base de données ne remonte pas. Alors je vais rentrer de nouveaux les identifiant pour la base de données, cela fonctionne mais elle remplace toutes les données déjà sauvegarder par ceux du poste en question.

# Solution
Y'a t'il des solutions pour pallier à ce problème ?

## Your Environment

* Version used: 1.75.7011.34963
* Operating System and version (e.g. Windows 10 1709 x64):

**Comment by Daiben** [comment]
je ne parle pas français

**Comment by farosch** [comment]
Google Translate:
> When you open mRemoteNG, the connections stored in the database do not go back up. Then I will enter new IDs for the database, it works but it replaces all data already backed up by those of the post in question.

**Comment by farosch** [comment]
I cannot reproduce this. Also I wouldn't know any code in mrng where it would overwrite an existing database.
