### ISSUE TITLE
Acceptance testing - v1.76

### ISSUE THREAD

**Issue by sparerd** [mRemoteNG/mRemoteNG#989]
Perform acceptance testing on v1.76 to ensure the app functions as expected before releasing the stable version. I will be going through this list and marking each completed section. 

If you would like to help with testing, please test a full section (bullet point) at a time and report back with your findings. Please report any issues in this issue with the mRemoteNG version that you tested with. If you are unsure about how a feature should behave or think that there may be a bug, feel free to ask about it. If bugs are found and verified we can create a new issue to track the fix.

https://github.com/mRemoteNG/mRemoteNG/wiki/Acceptance-Testing

- [x] Loading the program
- [x] Testing Connections
- [x] Main Menus
    - [x] File Menu
    - [x] View Menu
    - [x] Tools Menu
    - [x] Help Menu
- [x] Toolbars
- [x] Connection Tree Panel
    - [x] Button Menu
    - [x] Renaming Tree Items
    - [x] Moving Tree Items
    - [x] Context Menu
    - [x] Search Bar
- [x] Config Panel
    - [x] Button Menu Strip
    - [x] Property Grid
- [x] Connection Window
- [x] Options window
    - [x] Startup/Exit page
    - [x] Appearance page
    - [x] Tabs & Panels page
    - [x] Notifications page
    - [x] Connections page
    - [x] Credentials page
    - [x] SQL Server page
    - [x] Updates page
    - [x] Theme page
    - [x] Advanced page
- [x] Quick Connect Toolbar
- [x] External Programs
    - [x] List view
    - [x] Bottom edit area
    - [x] Context menu / button menu
    - [x] Starting external tools
    - [x] Arguments
- [x] Port Scan
- [x] SSH File Transfer
- [x] Miscellaneous tests

**Comment by sparerd** [comment]
Almost done with File menu testing, just need to test the export feature a bit more.

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _File Menu_ section on _Windows 10 LTSB 2016_ with _.NET Framework 4.7.1_. Following problems and suggestions were found:

**Functionality problems**
_Unsorted:_
- Hotkeys for new folder and new connection stop working if _File_ menu was called when _PuTTy Saved Sessions_ was selected.

8 (_Rename Folder_):
- HotKeys stop working and stop being shown in right click menu if _F2_, _Ctrl + N_ or _Ctrl + Shift + N_ is pressed on _PuTTy Saved Sessions_ node or any node inside it;
- Also it's possible to create new element inside _PuTTy Saved Sessions_ - you have to create new folder in root element, then delete it - PuTTy node will be active (but, I guess, not focused), and it'll be possible to create new node inside it through hotkey.

9 (_Duplicate_): 
- Duplicating root or PuTTy node through hotkey causes unhandled exception.

10 (_Import_). All problems are in  _Port Scan_ functionality:
- Can't move through octets of IPs by arrows or Tab;
- Stop button does nothing - Scan goes until completion;
- Ports range also does nothing - if I'll point out, for instance, from 3389 to 3389, I still see other ports in _Closed_ or _Open ports_;
- Can't sort results;
- Why _Protocol to import_ is needed? If I'll choose _RDP_, it still imports only the selected node from the list, not all where RDP is available;
- If I choose single node and do the import through _Import_ button at the lower right corner, _Port Scan_ tab is closed. Reopening it crashes the app;
- If I try to import several nodes through _Import_ button at the lower right corner, I get unhandled exception immediately,

11 (_Export to file_)
- If I'm choosing export while folder is selected, _Export_ menu opens with _Export everything_ option. Same for connection export. I think the option should be _Export selected folder_ or _Export selected connection_, respectively;
- Why _File name_ section is needed at all? User automatically thinks that he already made an export by pressing _Save_ in _Save As_ dialog. I suggest to remove this section and replace _OK_ button to _Export_.
- There's no check for _Assigned Credentials_ flag
- _Assigned Credential_ means "password only" - login is still being exported. May be you should rename this flag;
- _Ctrl + E_ is a good combination for _Export_ function ;)
	


**_Acceptance testing_ guide**
5 (_Save Connection File_ testing): 

- Changes persist after restart even if I don't save connection file. May be some steps are missed here? Or may be it's better to check if modify date is changed after saving the file?

7 (_Delete_):
- i-iv: hotkey for deletion should be tested too.
- v.a: not very significant, but root node name depends on locale (in Russian it's called _Подключения_ and so on);
- v-vi: hotkey for deletion should be tested too, but in this case no actions is expected;
- 12 (_Exit_): Hotkey testing?

**Comment by sparerd** [comment]
@PetbkA Great stuff here! I should have a little time tonight to start going through these notes. Thanks for helping with testing!

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _View Menu_ section on _Windows 7 x64 SP1_ with _.NET Framework 4.7.1_. The results are:

_1 (Add Connection Panel)_

- If only one panel is opened, it can't be closed through _x_ button. [GIF](https://user-images.githubusercontent.com/22843816/41652309-5b9cbcac-748b-11e8-8652-74fc22cb7a38.gif) that shows it.

_7 (Jump To)_

- It would be nice to add _Quick Connections_ to _Jump To_ menu, hotkey - _Ctr+Alt+Q_.

_8 (Reset Layout)_
- Resetting the layout doesn't affect toolbars and _External Tools_ windows. I guess this is as designed, although I'm not sure about exttools...

**Also there's some "out-of-order" bugs concerning localization:**

- Whenever Themes are enabled or not ([GIF](https://user-images.githubusercontent.com/22843816/41653400-9e83003c-748e-11e8-9ee0-2cec86f57562.gif)):

  * Switching language still leaves some interface elements from home locale. In my case Russian text is present in context menus when English locale is enabled:
- When Themes are enabled, there are several bugs in Russian locale (see [GIF](https://user-images.githubusercontent.com/22843816/41654130-17539682-7491-11e8-8180-bac7ce93ca41.gif)):
  * When app is started with russian locale, opening _Options_ switches menu toolbar (but none of it's sections contents) to English;
  * If _Options_ window is closed on _Connections_ tab, opening _Options_ again causes unhandled exception
(see [Exception.txt](https://github.com/mRemoteNG/mRemoteNG/files/2118932/Exception.txt)).


- Also in Russian locale there's English text in _Notification_, _Theme_ and _Security_ tabs, but I guess it's just lack of translation

**Comment by sparerd** [comment]
>  Hotkeys for new folder and new connection stop working if File menu was called when PuTTy Saved Sessions was selected

Resolved under #999

> Also it's possible to create new element inside PuTTy Saved Sessions - you have to create new folder in root element, then delete it - PuTTy node will be active (but, I guess, not focused), and it'll be possible to create new node inside it through hotkey.

Resolved under #998

**Comment by sparerd** [comment]
@PetbkA I edited both your posts to add checkboxes to the issues you have raised. This will help me track which ones I've handled. Thanks again for your thorough testing, it is an immense help to getting 1.76 released.

**Comment by PetbkA** [comment]
@sparerd , thank you for the app :) Another "out-of-order" bug concerning _Connections tree panel_: 

- [ ] Hotkeys stop working and disappear from the menu if I'll do the folowing steps:
1. Right click on the node to call context menu;
2. Left click on the same node to close menu.

[GIF](https://user-images.githubusercontent.com/22843816/41710912-80d61a76-754f-11e8-8c35-ff22abc7de60.gif) that shows it. After this steps hotkeys stop working immediately. Bug doesn't reproduce if the left click will be on the other node or the right click will be done on the same node

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _Tools_ and _Help_ menus section on _Windows 7 x64 SP1_ with _.NET Framework 4.7.1_:

**Functionality problems**
_Tools Menu_
No problems.

_Help Menu_
- 2-5 (_Websites_). It's better to open links in default browser instead of mRNG tab that uses _IE_. Moreover, _Report a Bug_ opens _GitHub_ that says that browser is [no longer supported](https://user-images.githubusercontent.com/22843816/41715017-ca739360-755a-11e8-8a07-473bbcfe9445.png);
- 7 (_Check for updates_). I suggest to also show update channel that is selected in options;
- 8.i (_About_). Some text [is hard to see](https://user-images.githubusercontent.com/22843816/41715083-0026e462-755b-11e8-9cf1-2679efd191c6.png) in dark themes.

**Acceptance testing guide issues**
_Help Menu_
- 6 (_Announcements_). There's no _Announcements_ button at all;
- 7.i. What is considered the _correct_ version? On the website I see _Prerelease v1.76 Alpha 6_, which doesn't equal to _1.76.4.16229_. I suggest to use version from  OS _Uninstall or change a program_ window;
- 7.ii. Same question, although I don't know what to use as correct version

**Comment by sparerd** [comment]
> What is considered the correct version? On the website I see Prerelease v1.76 Alpha 6, which doesn't equal to 1.76.4.16229. I suggest to use version from OS Uninstall or change a program window;

That is a fair point. I've been thinking about changing how we display the release versions on the website that is more indicative of the actual version number and also supports our update channels. (For example, 1.76.4.16229 could have been promoted to the beta update channel, which makes "v1.76 alpha 6" a very confusing label.) For this verification, it is probably enough to check that the About page version matches the version number shown when right clicking the app icon -> Properties -> Details -> Product version.

I think the value shown in the OS uninstall window can differ from the actual program version, depending on how the MSI was set up. Though this would probably be good to verify as well.

**Comment by sparerd** [comment]
> 2-5 (Websites). It's better to open links in default browser instead of mRNG tab that uses IE. Moreover, Report a Bug opens GitHub that says that browser is no longer supported;

This one will probably need to be moved out to v1.77 since it would be a larger change. There are a lot of unintuitive things that happen when connections are created (even going to a website). If you changed the browser engine set in the default connection info (must select Http/s protocol first) to Firefox, then the github message should go away.

But like you said, opening those sites in the default browser is probably the better way to go though.

**Comment by sparerd** [comment]
> Hotkeys stop working and disappear from the menu if I'll do the folowing steps:
> 1. Right click on the node to call context menu;
> 1. Left click on the same node to close menu.
>
> GIF that shows it. After this steps hotkeys stop working immediately. Bug doesn't reproduce if the left click will be on the other node or the right click will be done on the same node

Resolved under #1001.

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _Toolbars_ section on _Windows 10 LTSB 2016_ with _.NET Framework 4.7.1_. Also I'm using _vs2015dark_ theme and disable themes when I think that it might be the reason. The results are:

**[GUI problems](https://user-images.githubusercontent.com/22843816/41746794-518dc9e8-75b4-11e8-821e-bf8e2457c260.png)**
- [ ] In dark themes, when toolbars aren't locked, it's hard to see their anchors;
- [ ] In dark themes, can't see buttons in the list of connections and drop-down menus in _World_ icon;
- [ ] When list of connections is too tall, can't scroll through it using mouse wheel.

**Functionality problems**

- [ ] 2.i. If something is entered in address field, changing protocol already opens connection. I guess that connection should start only when I press the button;
- [ ] 2.iii. Caught an exception, it seems that I've choose connection from history and changed its type but I couldn't reproduce it;

**Acceptance testing guide**

- [ ] 2.iv (_Quick connect world icon_). I guess that 2.v-viii are subitems of 2.iv, so 2.iv should be 3, and 2.v-viii - 3.i-iv;
- [ ] 3.i (_External Tools Toolbar_). By default, there will be no tools, so steps for adding them should be first

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _Button Menu_ and _Renaming tree items_ on _Windows 7 x64 SP1_ and _.NET Framework 4.7.1_:

**Functionality problems**
_Button Menu_

- [ ] 3.i (_View_). Catched #993.


_Renaming tree items_

- [ ] 1.i.c (_Context menu_). Strange, but English name [isn't bolded](https://user-images.githubusercontent.com/22843816/41795454-7b8bbf2c-766b-11e8-88e0-73c72f536c12.gif) in root node config. Not reproduced when renaming through _Config_ pane;
- [ ] 1.ii.c (_Config panel rename_). Root node changes name in _Connections_ only [after mouse hover](https://user-images.githubusercontent.com/22843816/41795538-ce09dd7e-766b-11e8-8ad1-a6811b1ee7c7.gif);
- [ ] 2.i.a (_PuTTy hover-rename_). If by "hover-rename" you mean selecting node and clicking on it once again, then it's not working at all. I guess this is connected with "Right click - Left click - No hotkeys" problem;
- [ ] 2.iii.a (_PuTTy Config panel rename_). Name property is not read-only, and I can change it. Name comes back to default after restart.

**Acceptance guide**
_Button Menu_
- [ ] 4.ii (_Sort Descending_). Need to point out that in this case sorting is called through context menu (or just make a button :)).


_Renaming tree items_
- [ ] Hover-rename check appears only in the end, for _PuTTy Saved Sessions_

**Comment by sparerd** [comment]
@PetbkA I went through some your port scan testing results.

> Can't move through octets of IPs by arrows or Tab;

Noted - we will probably want to put in an enhancement request for this. It shouldn't been hard to add, but I'm not sure it's really a bug. Moving forward through octets can be done by using period (.), though there isn't a good way to move between start range/end range controls. Even the period key to move through octets doesn't seem like that great of a decision in hindsight. I'm not sure that all cultures use a period for octet separation. For example, German uses a comma for decimal number separation (1,25), do they use commas for octet separation too?

Also fixed the tab ordering between elements on this page to make it easier to fill out.

> Stop button does nothing - Scan goes until completion;

Looks like the scan itself is done within 1-2 seconds for 255 hosts. The delay seen in the UI is due to huge inefficiencies in how the results are updated. The main issue seems to be that we try to update the UI for each individual ip result. The UI can't keep up and the update events queue up, leading to UI lock and unintuitive behavior of the "stop" scan button. By the time the UI is responsive, the scan has likely finished. We will want to rework this screen quite a bit to fix that.

> Can't sort results;

Enhancement request: #841

> Why Protocol to import is needed? If I'll choose RDP, it still imports only the selected node from the list, not all where RDP is available;

This controls the protocol assigned to the port scan results that are imported. Selecting "RDP" will import all selected scan results as connections with a protocol set to RDP. It does not control *which* results are imported. We may need to update the label text to be more clear about this - maybe "Protocol for imported connections:".

**Comment by PetbkA** [comment]
**1.76.4.16229** - tested _Moving tree items_ section on _Windows 7 x64 SP1_ with _.NET Framework 4.7.1_:

No functionality problems.

**Acceptance testing guide**

- [ ] 1.iv (_Drag a folder onto a connection_). If I move the folder _onto_ a connection, [nothing happens](https://user-images.githubusercontent.com/22843816/41875615-15db64dc-78d4-11e8-99dc-b81808227711.png). I guess I should drag folder _between_ connections or connection and its containing folder;
- [ ] 1.v (_Drag a folder onto itself_). ["Cannot drag node onto itself"](https://user-images.githubusercontent.com/22843816/41875593-0145d03e-78d4-11e8-9ca7-80d0e1ac3f8f.png) message should be checked as well;
- [ ] 1.vi (_Drag a folder onto one of its children_). ["Cannot drag parent node onto child"](https://user-images.githubusercontent.com/22843816/41875631-323e1f0c-78d4-11e8-8b14-a8f42f78b565.png) message should be checked as well + same as for 1.iv;
- [ ] 2.ii (_Drag a connection onto another connection_). Same as for 1.iv;
- [ ] 3.i (_Root node_).["This node is not draggable"](https://user-images.githubusercontent.com/22843816/41875651-45ba041a-78d4-11e8-8415-94350154666d.png) message should be checked as well;
- [ ] 4,5 (_PuTTy_). Same as for 3.i

**Comment by sparerd** [comment]
> Strange logic. If I select 10 connections with SSH protocol on half of them, what's the point of importing them as RDP connections? IMHO importing only the connections that contain selected protocol is better

I think the reasoning was that while some ports may be well-known (3389, 22, 23, etc), a user may need to connect to a custom port (9260) for a protocol. But really I'm just guessing

**Comment by Vershner** [comment]
I've just tried importing an rdg file from RDCman 2.7 and it gives the same error as 1.75 did. 
These are the log entries: 
2018-07-13 17:49:20,854 [1] ERROR - Unable to import file.
Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.

**Comment by sparerd** [comment]
> 2.iii. Caught an exception, presumably when I've choose connection from history and changed its type. I couldn't reproduce it.

Seems to be a weird case where the deletion target is null. I think c74f37f should fix this.

**Comment by sparerd** [comment]
> 2.i. If something is entered in address field, changing protocol already opens connection. I guess that connection should start only when I press the button with protocol name;

This is working as originally designed, though I can see how this could be confusing. If it is problematic enough, we can open an issue to discuss it further.

**Comment by sparerd** [comment]
> If I choose single node and do the import through Import button at the lower right corner, Port Scan tab is closed. Reopening it crashes the app;
> If I try to import several nodes through Import button at the lower right corner, I get unhandled exception immediately,

Resolved via #1030

**Comment by sparerd** [comment]
> If only one panel is opened, it can't be closed through x button. [GIF](https://user-images.githubusercontent.com/22843816/41652309-5b9cbcac-748b-11e8-8652-74fc22cb7a38.gif) that shows it.

That X button is actually to close a connection within the panel, not to close the panel itself. Since you don't have the "Always show panel tabs" option enabled and there is only one panel, you do not see the X button to close the panel. This should be less confusing when we remove one of the two windowing libraries that we are using (#155). Also slightly related to the conversation in #368.

**Comment by sparerd** [comment]
> Switching language still leaves some interface elements from home locale. In my case Russian text is present in context menus when English locale is enabled

I was able to find a fix for this. We were setting the language of the connection context menu before loading the culture/language that should be used. Resolved under #1034

**Comment by sparerd** [comment]
> When app is started with russian locale, opening Options switches menu toolbar (but none of it's sections contents) to English;

This one has me stumped. I can replicate the issue, but I can't seem to find how this is happening or why. The menu text changes during a system level WndProc() call, but I'm not seeing any C# code that could be causing it. This one may take a bit to track down.

> If Options window is closed on Connections tab, opening Options again causes unhandled exception
Resolved under #1036

**Comment by sparerd** [comment]
Standard regression testing is done for v1.76
