### ISSUE TITLE
Error when deleting host in filtered view

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#991]
## Steps to Reproduce (for bugs)

1. Create a Host
2. Filter for the name of the Host (filtering must be enabled in connection settings)
3. Delete the host

## Environment

* Version used: 1.76.4.16229
* Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 Build 17134.82

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
> Parametername: index
>    bei System.Collections.ArrayList.IListWrapper.InsertRange(Int32 index, ICollection c)
>    bei BrightIdeasSoftware.TreeListView.Tree.InsertChildren(Branch br, Int32 index)
>    bei BrightIdeasSoftware.TreeListView.Tree.RebuildChildren(Object model)
>    bei BrightIdeasSoftware.TreeListView.RefreshObjects(IList modelObjects)
>    bei BrightIdeasSoftware.ObjectListView.RefreshObject(Object modelObject)
>    bei mRemoteNG.UI.Controls.ConnectionTree.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
>    bei System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
>    bei mRemoteNG.Tree.ConnectionTreeModel.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
>    bei mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
>    bei mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
>    bei mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
>    bei mRemoteNG.Container.ContainerInfo.RaiseCollectionChangedEvent(Object sender, NotifyCollectionChangedEventArgs args)
>    bei mRemoteNG.Container.ContainerInfo.RemoveChild(ConnectionInfo removalTarget)
>    bei mRemoteNG.Connection.ConnectionInfo.RemoveParent()
>    bei mRemoteNG.Tree.ConnectionTreeModel.DeleteNode(ConnectionInfo connectionInfo)
>    bei mRemoteNG.UI.Controls.ConnectionTree.DeleteSelectedNode()
>    bei mRemoteNG.UI.Controls.ConnectionContextMenu.OnDeleteClicked(Object sender, EventArgs e)
>    bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3110.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> mRemoteNG
>     Assembly-Version: 1.76.4.16229.
>     Win32-Version: 1.76.4.16229.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/mRemoteNG.exe.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3110.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> WeifenLuo.WinFormsUI.Docking
>     Assembly-Version: 2.16.0.0.
>     Win32-Version: 2.16.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.DLL.
> ----------------------------------------
> mRemoteNG.resources
>     Assembly-Version: 1.76.4.16229.
>     Win32-Version: 1.76.4.16229.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/de/mRemoteNG.resources.DLL.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> WeifenLuo.WinFormsUI.Docking.ThemeVS2003
>     Assembly-Version: 2.16.0.0.
>     Win32-Version: 2.16.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2003.DLL.
> ----------------------------------------
> WeifenLuo.WinFormsUI.Docking.ThemeVS2012
>     Assembly-Version: 2.16.0.0.
>     Win32-Version: 2.16.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2012.DLL.
> ----------------------------------------
> WeifenLuo.WinFormsUI.Docking.ThemeVS2013
>     Assembly-Version: 2.16.0.0.
>     Win32-Version: 2.16.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2013.DLL.
> ----------------------------------------
> WeifenLuo.WinFormsUI.Docking.ThemeVS2015
>     Assembly-Version: 2.16.0.0.
>     Win32-Version: 2.16.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL.
> ----------------------------------------
> System.Xml.Linq
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
> ----------------------------------------
> MagicLibrary
>     Assembly-Version: 1.7.4.0.
>     Win32-Version: 1.7.4.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/MagicLibrary.DLL.
> ----------------------------------------
> log4net
>     Assembly-Version: 2.0.8.0.
>     Win32-Version: 2.0.8.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/log4net.DLL.
> ----------------------------------------
> ObjectListView
>     Assembly-Version: 2.9.1.1072.
>     Win32-Version: 2.9.1.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/ObjectListView.DLL.
> ----------------------------------------
> BouncyCastle.Crypto
>     Assembly-Version: 1.8.1.0.
>     Win32-Version: 1.8.15362.1.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/BouncyCastle.Crypto.DLL.
> ----------------------------------------
> System.Management
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> System.Web
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
> ----------------------------------------
> AxInterop.MSTSCLib
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/AxInterop.MSTSCLib.DLL.
> ----------------------------------------
> Interop.MSTSCLib
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/Interop.MSTSCLib.DLL.
> ----------------------------------------
> Accessibility
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
> ----------------------------------------
> System.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
> ----------------------------------------
> VncSharp
>     Assembly-Version: 1.2.0.0.
>     Win32-Version: 1.2.0.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/mRemoteNG/VncSharp.DLL.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by sparerd** [comment]
Thanks for reporting @farosch. I'll take a look at this right away

**Comment by sparerd** [comment]
This is now fixed and will be in the next v1.76 release. Added tests to catch issues like this in the future as well.
