### ISSUE TITLE
Fips Compliance

### ISSUE THREAD

**Issue by mremotegod** [mRemoteNG/mRemoteNG#992]
## Expected Behavior
Id love to see this application use fips compliant algorithms. as a system admin this tool has proved very useful for everyday task to include ssh and remote desktop.

## Current Behavior
Currently i receive an error that this application cannot run because it is not fips compliance and therefore will close

## Possible Solution
Enable Fips compliance to the application

**Comment by sparerd** [comment]
Closing as duplicate of #222. Please follow that issue for further updates
