### ISSUE TITLE
Connection names not fully displayed when filtering

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG#993]
Sometimes when filtering connection names get cut off like seen in the picture (**sbeesx...**). It looks like the connection names column loses its width property.

![applicationframehost_2018-06-15_19-34-33](https://user-images.githubusercontent.com/22905106/41484464-39d1e004-70dd-11e8-9f80-47a623ea6101.png)

## Steps to Reproduce (for bugs)
Unfortunately I have not been able to find a way to reproduce this issue.

## Environment
Version used: 1.76.4.16229
Operating System and version (e.g. Windows 10 1709 x64): Windows 10 1803 Build 17134.82

**Comment by sparerd** [comment]
Good find. I'll look into this one. There was some special logic we had to add to get the column width updating properly to avoid the connection name truncation (...). It's likely this was an edge case that got missed

**Comment by sparerd** [comment]
Thanks @PetbkA, I can get that one fixed pretty easily.

@farosch Had you used the "Expand all folders" button at any point when you noticed this bug?

**Comment by farosch** [comment]
@sparerd No, I have not. But I think I found out how to reproduce the bug:
1. Filter for a connaction that is in a nested folder
![mremoteng_2018-06-22_19-25-29](https://user-images.githubusercontent.com/22905106/41790326-84a27f24-7652-11e8-8cc8-d96f89e82851.png)
2. Collapse a folder obove the connection
![mremoteng_2018-06-22_19-27-02](https://user-images.githubusercontent.com/22905106/41790415-d30000b0-7652-11e8-819a-49d02ae82165.png)
3. After emptying the search filter string the connection panel looks like this:
![mremoteng_2018-06-22_19-27-27](https://user-images.githubusercontent.com/22905106/41790425-dbdc0738-7652-11e8-81ad-c666ffebf0e5.png)

**Comment by sparerd** [comment]
I've fixed the issue with the Expand All button. I'm able to reproduce the issue your issue now as well, @farosch. Those steps were very helpful. I should be able to get a fix for that shortly.

**Comment by sparerd** [comment]
@farosch I've committed a fix for your issue. I will be available in the next v1.76 build
