### ISSUE TITLE
Symbol substitution in external utilities

### ISSUE THREAD

**Issue by Yurii84** [mRemoteNG/mRemoteNG#994]
Hello!
Sorry for my english.
If you add a character ! as a parameter for an external utility, it is escaped by the ^ character which is also passed to the external utility as a parameter. for example, if the password is 123! then as a parameter is transmitted 123^!
if you specify ip for examle of couse 192.168.1.1! then you will see in the external application 192.168.1.1^!

**Comment by sparerd** [comment]
This is due to the Shell Metacharacter Escaping feature. Use `%!HOSTNAME%` (note the '!' at the beginning of the parameter) to disable escaping these characters.

More information:
https://github.com/mRemoteNG/mRemoteNG/wiki/External-Tools#shell-metacharacter-escaping
