### ISSUE TITLE
[FR][Connections]: filter connections while searching

### ISSUE THREAD

**Issue by PetbkA** [mRemoteNG/mRemoteNG#997]
## Expected Behavior
It would be nice то have a filtering similar to [one in _Total Commander_](https://user-images.githubusercontent.com/22843816/41659284-84a6b2a4-74a1-11e8-9db1-187cdb33b609.gif) when searching in _Connections_.

## Current Behavior

Connections aren't filtered: cursor just moves to the connection containing keyword.

## Possible Solution

1. There should be a switch to enable/disable filtering, it should be in search filed, and it's state should be saved when app is restarted;
2. Keyword should be searched in any part of the name (not from the start or from the end etc);
3. If search returns no results when new symbol is entered in the keyword, app should remove this symbol from input. It's hepls against mystyping;
4. Don't know if wildcards should be supported. Personally I think this isn't necessary.

## Context

It's easier to find the needed connection in cases like these:
1. I have about a hundred connections, from which the one is with IP 10.157, and the other is 157.10. Without filtering I sometimes pick wrong connection when searching _157_ 'cause it's harder to see it in the list;
2. I have different _Exchange Servers_ installed on different OSes. When I need to connect to one of them, I type _Exc_ and cycle through them. With filtering I'd found the needed server faster.

## Your Environment
Doesn't matter in this case

**Comment by sparerd** [comment]
This was implemented under #338 and is available from v1.76 alpha 1 and onward. Does that handle your use-case?

**Comment by PetbkA** [comment]
Not quite well, but I'll better make another request for it

**Comment by sparerd** [comment]
Maybe the main feature that is missing in our currently implementation is that you must activate filtering from Options -> Connections -> Filter search matches in connection tree. A small icon in the search box or a drop-down option would be useful if you intend on switch between normal search and filtering somewhat often.
